### ISSUE TITLE
What is the status of expressions like x + (x > 0) in SymPy?

### ISSUE THREAD

**Issue by normalhuman** [sympy/sympy#14077] opened 2018-02-04 03:43 UTC
Motivated by #14073. One can execute `expr = x + (x > 0) ` (where x is a SymPy symbol) without an exception raised. Operators like `expr*2` or `expr**2` work as well. Curiously, `expr.is_commutative` is False. And an attempt to substitute any number for x, `expr.subs(x, 3)`, yields an error.

On the other hand, `f = lambdify(x, x + (x > 0))` returns valid code, which can be used to find f(0), f(1), and so on. The Boolean True gets coerced to 1 here. 

Is direct use of relationals in SymPy expressions acceptable? Should it just raise an error immediately at creation, like `x + True` does? Should it be rewritten as Piecewise automatically, by the evaluation of Add? As is, it sort of works half the time.

**Comment by leewz** [comment] 2018-02-04 03:52
Copying my comment from #14073:

> In my opinion, 10 + (x < 1) should either be considered commutative, or throw an error.
> 
> I think it's safe to assume that (10 + (x < 1)) is commutative. I can only see x being a number or bag of numbers, not a matrix or other algebraic element.
> 
> The other option is to throw an error. While that won't help me, it would be more consistent.

**Comment by asmeurer** [comment] 2018-02-05 22:03
See https://github.com/sympy/sympy/pull/13435 and related discussions. Booleans are separate from expressions (not equal to 0 and 1) by design. As I mentioned in the other issue, I believe an `IndicatorFunction` object that maps {True, False} -> {1, 0} would be a good way to manage this in a mathematically meaningful way.

**Comment by leewz** [comment] 2018-02-09 06:52
Would you be open to a context or symbol setting that would "taint" any symbolic value created from it, forcing booleans to be evaluated as ints?

Example:

    x = S('x', intbools=True)  # setting
    y = (x == 1)*2 - 1  # tainted

**Comment by normalhuman** [comment] 2018-02-10 04:44
Doesn't look like a good approach to me. The assumptions on a symbol are mathematical: integer, positive, real, etc. There are "intbools" numbers in mathematics.

**Comment by leewz** [comment] 2018-02-10 04:56
What is mathematics except rules and their consequences? Algebraic structures describe the combinations of abstract objects. In this case, the intbool flag will help model a system that is itself abstract: Python.

"There are no intbools in math" makes a false distinction. It's also not true. Computability theory often uses integer representations of booleans (or multi-boolean representation of integers, depending on how you look at it), and computability theory is certainly math. It only happens to be math that models programming.

**Comment by oscarbenjamin** [comment] 2019-12-17 22:37
I've opened #18053 which makes `Relational` not a subclass of `Expr` and disallows using `Relational` in `Add`, `Mul` and `Pow`. I think that that can close this issue.

**Closed** 2020-01-02 17:23 UTC
