### ISSUE TITLE
Text styling of units in Latex output

### ISSUE THREAD

**Issue by alugowski** [sympy/sympy#16060] opened 2019-02-24 06:32 UTC
Latex output should follow best practice and wrap unit names with `\textrm{}` or `\text{}`.

Today `sympy.latex()` emits unit names as simple strings. This is fine for normal text mode, but results in a few issues in math mode.

- units are indistinguishable from variable names. Does `10m` mean "ten meters" or "ten times `m`"?
- units should not be italicized, but math mode letters by default are.
- consecutive letters in math mode are presented as if they're individual variable names. This means words, such as unit names, have larger kerning. `ft` is formatted as if it's two variables multiplied together, `f*t`. The first letter in a word is given slightly more space, making words look odd.

See this article for examples and best practice: https://texblog.org/2012/09/24/normal-text-in-math-mode/

The following should emit `$10 \textrm{meter}$` instead of `$10 meter$`:
```python
import sympy
from sympy.physics.units import meter

x = 10 * meter

print(sympy.latex(x, mode="inline"))
```

Example math mode formatting:
<img width="231" alt="image" src="https://user-images.githubusercontent.com/2730364/53295896-fc20db80-37b9-11e9-923c-dd9bca3a652c.png">

**Comment by alugowski** [comment] 2019-02-24 06:33
One could argue that all multi-letter symbols should get this treatment, not just unit names.

**Comment by oscargus** [comment] 2019-02-24 15:43
I think `\text` is the way to go, see discussion in #15934 (solved in #16056 ). rm indicates stuff that one not necessarily wants.

There is also a test which seems to indicate that initially the idea was to do something different for multi-character variables names. However, since one easily can select the name on creating of the variable, `Vdd = Symbol('V_{\text{dd}}')` that seems to be less of a problem compared to the units. (There is also an optional argument to the LaTeX printer that allows this type of conversion.)

What is your opinion on spacing? Personally, I prefer a space before the unit. Normally, when writing LaTeX by hand, I would do `$5$~m`, but when put inside the equation the hard space will be there automatically since equations do not line break anyway. "My" approach is good form the perspective that LaTeX will even out the length of the spaces on a single line, while writing it inside an equation the distance will be well defined by the spacing character. Or one can simply do `5\text{ m}` which may actually adapt to the spacing on that line, not sure.

**Comment by oscargus** [comment] 2019-02-24 15:44
It also opens up the question if it should emit meter or m.

**Comment by alugowski** [comment] 2019-02-24 16:49
I agree about `\text` vs `\textrm`, I just wasn't sure if a dependency on `amsmath` is ok.

I agree there should be a space. I think `10~\text{m}` is neater than `10\text{ m}`, but it's only a slight preference.

**Comment by alugowski** [comment] 2019-02-24 16:51
> It also opens up the question if it should emit meter or m.

I strongly think it should emit `m`.

At least there is a hack where that can be enabled globally.

See #15135

**Comment by oscargus** [comment] 2019-02-24 17:01
Good! I agree with that, so in case you or I solve it, both will be happy.

Turns out that quite a lot of things already depends on `amsmath` anyway, even though I had the some doubt a few weeks ago.

**Comment by sylee957** [comment] 2019-03-16 13:33
I see `amsmath` shipped with Jupyter, and that may be the reason why SymPy had implicitly used amsmath package.

However, for displaying units, it may need some other packages like `siunitx`, and I'm not sure such packages would be available for jupyter.

I think the latex printer can be extended to print out `usepackage{}`, while still being able to represent units with basic alphabets for jupyter usage.

And also, I think that the printing had regressed from sympy 1.3
Before, it had printed at least something that make sense

<img src="https://user-images.githubusercontent.com/34944973/54475890-32da9680-483a-11e9-863f-2e7d0a8d212b.png" width="512px">

though it had not been well integrated to Jupyter.

But now, it prints like 

<img src="https://user-images.githubusercontent.com/34944973/54475911-6f0df700-483a-11e9-948b-ab64f75f2f48.png" width="512px">

**Comment by sylee957** [comment] 2019-03-19 14:37
Okay, this regression may have to be investigated, before next release

**Comment by oscargus** [comment] 2019-03-19 15:52
If it is printing it like that it will be a piece of cake to sort it out. I'll assign it to myself although I probably not have time to fix it until the weekend. (I actually haven't tried the unit system.)

I may have a look at siunitx but I think that just putting it in `\text` will do it quite well.

**Comment by oscargus** [comment] 2019-03-24 12:14
I've got something that can do:

```
In [82]: 10*meter
Out[82]: 

```
![image](https://user-images.githubusercontent.com/8114497/54879127-d11bbd00-4e35-11e9-9496-ffd1fe7a38ff.png)

right now. However, it also does things like 
![image](https://user-images.githubusercontent.com/8114497/54879140-e5f85080-4e35-11e9-9ac6-68fafab5c3f7.png)

so while it is a step in the correct direction, I believe that one should try to improve the handling of units in the printing in two ways:

  1. Separate value and units
   2. Add optional argument for the different LaTeX, pretty and MathML presentation abbreviations that may be suitable.

Two example of the latter is `um` which prints as 

```
In [83]: 5*um
Out[83]: 
```
![image](https://user-images.githubusercontent.com/8114497/54879196-63bc5c00-4e36-11e9-917b-b183a864b699.png)
an `planck_acceleration`

```
In [84]: planck_acceleration
Out[84]: 
planck_acceleration

In [85]: latex(planck_acceleration)
Out[85]: '\\text{ a_P}'
```

Clearly, in the former one should be able to specify that \mu etc should be used and in the latter one should be able to specify that it should be (something like) `a_{\text{P}}`. Still, I believe that the current approach is at least better than what was there before.

**Comment by asmeurer** [comment] 2019-03-29 22:28
What is the status of this? I want to do a release candidate in the next couple of days and this is marked as blocking the release.

**Comment by oscargus** [comment] 2019-03-29 23:08
I have a version that prints with non-italics. However, I started to add alternative LaTeX descriptions, like `\mu \text{m}` for `um` and this is not complete yet. Also, I would like to implement a method for separating the units and print them separately. Now, if there is a Rational number like `x*meters/(y*seconds)` it prints like that and not like `x/y m/s`.

So I can push something that partly solves it, but not really what I would call the final solution. (And it should not really be blocking, it was more something I aimed for...)

**Comment by oscargus** [comment] 2019-03-29 23:10
Oh yeah, it was described earlier... The update is that I have added special printing for some units. But the separation of units and "numbers" are missing.

**Comment by oscarbenjamin** [comment] 2019-10-26 19:43
I guess this had the milestone for 1.4 because there was a regression since 1.3. That was punted to 1.5 though so that this made it out in the 1.4 release.

It's not clear to me why this needs to hold up the release of 1.5 so unless someone wants to work on this I'll remove the 1.5 milestone

**Comment by oscarbenjamin** [comment] 2019-11-19 01:27
I'm removing the 1.5 milestone from this issue

**Comment by eagleoflqj** [comment] 2022-05-07 19:16
This is already fixed.

**Closed by eagleoflqj** 2022-05-07 19:16 UTC
Labels: printing, printing.latex
