### ISSUE TITLE
enforce lines formatting 

### ISSUE THREAD

**Issue by maciejskorski** [sympy/sympy#24261] opened 2022-11-14 17:47 UTC
Line length is checked manually by reviewers and is opinionated. 
This is a waste of collective time.

Would be good to early enforce the formatting, by enabling a directive in flake-8 or so.

**Comment by oscarbenjamin** [comment] 2022-11-14 18:00
This is a duplicate of #17287.

**Closed by oscarbenjamin** 2022-11-14 18:00 UTC
