### ISSUE TITLE
Generated C code contains x**y expressions

### ISSUE THREAD

**Issue by WarShoe** [sympy/sympy#12714] opened 2017-06-07 14:40 UTC
Both print_ccode() and CCodePrinter().doprint() do not change all expressions A**B to pow(A,B)

Reproducing code example:

```
from sympy import *
from sympy.printing import print_ccode

a, b, r, s0, K, F0, s, z, x, T = symbols('a, b, r, s0, K, F0, s, z, x, T')
C = x**b
z_bs = a*(F0**(1-b)-K**(1-b))/(s0*(1-b))
z_b1 = log(F0/K)*a/s0
expr2 = integrate( 1/x**b , (x,K,F0))
Fmid = (F0+K)/2
g1 = (diff(C,x)/C).subs(x,Fmid)
g2 = (diff(C,x,x)/C).subs(x,Fmid)
D = log( (sqrt(1-2*r*z+z*z)+z-r)/(1-r) )
e = T * a**2
expr4a = (2*g2-g1**2)/24*(s0*C.subs(x,Fmid)/a)**2
expr4b = r*g1/4 * s0*C.subs(x,Fmid)/a
expr4c = (2-3*r**2)/24
expr4 = 1+( expr4a + expr4b + expr4c ) * e
vn_bs = a*(F0-K)/D.subs(z,z_bs) * expr4
vn_b1 = a*(F0-K)/D.subs(z,z_b1) * expr4.subs(b,1)
N =  1-erfc(x/sqrt(2))/2
zcr = (K-F0)/(s*sqrt(T))
BNc = (F0-K)*N.subs(x,-zcr) + s*sqrt(T)/sqrt(2*pi)*exp(-(zcr**2)/2)
BNc_sabr_bs = BNc.subs({'s':vn_bs})
print_ccode(BNc_sabr_bs)
```

Error message:

The printed C-code fragment contains "a**2" expressions.

SymPy version 1.0

**Comment by rasto2211** [comment] 2017-06-17 10:27
When I run the code with the current version of SymPy which is in pip3 (SymPy 1.0) then I get this output:
```
// Not supported in C:
// erfc
(1.0L/2.0L)*sqrt(2)*sqrt(T)*a*(F0 - K)*(T*pow(a, 2)*(-1.0L/8.0L*pow(r, 2) + 1.0L/12.0L + (1.0L/4.0L)*b*r*s0*pow((1.0L/2.0L)*F0 + (1.0L/2.0L)*K, b)/(a*((1.0L/2.0L)*F0 + (1.0L/2.0L)*K)) + pow(s0, 2)*pow((1.0L/2.0L)*F0 + (1.0L/2.0L)*K, 2*b)*(-1.0L/24.0L*pow(b, 2)/pow((1.0L/2.0L)*F0 + (1.0L/2.0L)*K, 2) + (1.0L/12.0L)*b*(b - 1)/pow((1.0L/2.0L)*F0 + (1.0L/2.0L)*K, 2))/pow(a, 2)) + 1)*exp(-1.0L/2.0L*pow(-F0 + K, 2)*pow(log((a*(pow(F0, -b + 1) - pow(K, -b + 1))/(s0*(-b + 1)) - r + sqrt(pow(a, 2)*pow(pow(F0, -b + 1) - pow(K, -b + 1), 2)/(pow(s0, 2)*pow(-b + 1, 2)) - 2*a*r*(pow(F0, -b + 1) - pow(K, -b + 1))/(s0*(-b + 1)) + 1))/(-r + 1)), 2)/(T*pow(a, 2)*pow(F0 - K, 2)*pow(T*pow(a, 2)*(-1.0L/8.0L*pow(r, 2) + 1.0L/12.0L + (1.0L/4.0L)*b*r*s0*pow((1.0L/2.0L)*F0 + (1.0L/2.0L)*K, b)/(a*((1.0L/2.0L)*F0 + (1.0L/2.0L)*K)) + pow(s0, 2)*pow((1.0L/2.0L)*F0 + (1.0L/2.0L)*K, 2*b)*(-1.0L/24.0L*pow(b, 2)/pow((1.0L/2.0L)*F0 + (1.0L/2.0L)*K, 2) + (1.0L/12.0L)*b*(b - 1)/pow((1.0L/2.0L)*F0 + (1.0L/2.0L)*K, 2))/pow(a, 2)) + 1, 2)))/(sqrt(M_PI)*log((a*(pow(F0, -b + 1) - pow(K, -b + 1))/(s0*(-b + 1)) - r + sqrt(pow(a, 2)*pow(pow(F0, -b + 1) - pow(K, -b + 1), 2)/(pow(s0, 2)*pow(-b + 1, 2)) - 2*a*r*(pow(F0, -b + 1) - pow(K, -b + 1))/(s0*(-b + 1)) + 1))/(-r + 1))) + (1.0L/2.0L)*(F0 - K)*erfc(sqrt(2)*(-F0 + K)*log((a*(F0**(-b + 1) - K**(-b + 1))/(s0*(-b + 1)) - r + sqrt(a**2*(F0**(-b + 1) - K**(-b + 1))**2/(s0**2*(-b + 1)**2) - 2*a*r*(F0**(-b + 1) - K**(-b + 1))/(s0*(-b + 1)) + 1))/(-r + 1))/(2*sqrt(T)*a*(F0 - K)*(T*a**2*(-r**2/8 + 1/12 + b*r*s0*(F0/2 + K/2)**b/(4*a*(F0/2 + K/2)) + s0**2*(F0/2 + K/2)**(2*b)*(-b**2/(24*(F0/2 + K/2)**2) + b*(b - 1)/(12*(F0/2 + K/2)**2))/a**2) + 1)))
```
I can see that the problematic part is:
```
sqrt(a**2*(F0**(-b + 1) - K**(-b + 1))**2/(s0**2*(-b + 1)**2)
```

However, it seems that this issue has been fixed in `Sympy 1.0.1.dev`. That is the current version that is on master. The output of your script is:
```
(1.0L/2.0L)*sqrt(2)*sqrt(T)*a*(F0 - K)*(T*pow(a, 2)*(-1.0L/8.0L*pow(r, 2) + 1.0L/12.0L + (1.0L/4.0L)*b*r*s0*pow((1.0L/2.0L)*F0 + (1.0L/2.0L)*K, b)/(a*((1.0L/2.0L)*F0 + (1.0L/2.0L)*K)) + pow(s0, 2)*pow((1.0L/2.0L)*F0 + (1.0L/2.0L)*K, 2*b)*(-1.0L/24.0L*pow(b, 2)/pow((1.0L/2.0L)*F0 + (1.0L/2.0L)*K, 2) + (1.0L/12.0L)*b*(b - 1)/pow((1.0L/2.0L)*F0 + (1.0L/2.0L)*K, 2))/pow(a, 2)) + 1)*exp(-1.0L/2.0L*pow(-F0 + K, 2)*pow(log((a*(pow(F0, -b + 1) - pow(K, -b + 1))/(s0*(-b + 1)) - r + sqrt(pow(a, 2)*pow(pow(F0, -b + 1) - pow(K, -b + 1), 2)/(pow(s0, 2)*pow(-b + 1, 2)) - 2*a*r*(pow(F0, -b + 1) - pow(K, -b + 1))/(s0*(-b + 1)) + 1))/(-r + 1)), 2)/(T*pow(a, 2)*pow(F0 - K, 2)*pow(T*pow(a, 2)*(-1.0L/8.0L*pow(r, 2) + 1.0L/12.0L + (1.0L/4.0L)*b*r*s0*pow((1.0L/2.0L)*F0 + (1.0L/2.0L)*K, b)/(a*((1.0L/2.0L)*F0 + (1.0L/2.0L)*K)) + pow(s0, 2)*pow((1.0L/2.0L)*F0 + (1.0L/2.0L)*K, 2*b)*(-1.0L/24.0L*pow(b, 2)/pow((1.0L/2.0L)*F0 + (1.0L/2.0L)*K, 2) + (1.0L/12.0L)*b*(b - 1)/pow((1.0L/2.0L)*F0 + (1.0L/2.0L)*K, 2))/pow(a, 2)) + 1, 2)))/(sqrt(M_PI)*log((a*(pow(F0, -b + 1) - pow(K, -b + 1))/(s0*(-b + 1)) - r + sqrt(pow(a, 2)*pow(pow(F0, -b + 1) - pow(K, -b + 1), 2)/(pow(s0, 2)*pow(-b + 1, 2)) - 2*a*r*(pow(F0, -b + 1) - pow(K, -b + 1))/(s0*(-b + 1)) + 1))/(-r + 1))) + (1.0L/2.0L)*(F0 - K)*erfc((1.0L/2.0L)*sqrt(2)*(-F0 + K)*log((a*(pow(F0, -b + 1) - pow(K, -b + 1))/(s0*(-b + 1)) - r + sqrt(pow(a, 2)*pow(pow(F0, -b + 1) - pow(K, -b + 1), 2)/(pow(s0, 2)*pow(-b + 1, 2)) - 2*a*r*(pow(F0, -b + 1) - pow(K, -b + 1))/(s0*(-b + 1)) + 1))/(-r + 1))/(sqrt(T)*a*(F0 - K)*(T*pow(a, 2)*(-1.0L/8.0L*pow(r, 2) + 1.0L/12.0L + (1.0L/4.0L)*b*r*s0*pow((1.0L/2.0L)*F0 + (1.0L/2.0L)*K, b)/(a*((1.0L/2.0L)*F0 + (1.0L/2.0L)*K)) + pow(s0, 2)*pow((1.0L/2.0L)*F0 + (1.0L/2.0L)*K, 2*b)*(-1.0L/24.0L*pow(b, 2)/pow((1.0L/2.0L)*F0 + (1.0L/2.0L)*K, 2) + (1.0L/12.0L)*b*(b - 1)/pow((1.0L/2.0L)*F0 + (1.0L/2.0L)*K, 2))/pow(a, 2)) + 1)))
```
The buggy part looks like this:
```
sqrt(pow(a, 2)*pow(pow(F0, -b + 1) - pow(K, -b + 1), 2)/(pow(s0, 2)*pow(-b + 1, 2))
```
I think that is is correct now. When I grep the output of your script I don't see any `**`.

Can we close this issue now?

**Comment by moorepants** [comment] 2017-06-17 14:30
It would be worth finding which commit fixed this by bisecting and seeing if a regression test has been added. If there is no regression test, it would be worth adding.

**Comment by rasto2211** [comment] 2017-06-17 20:09
This commit returns correct output:
49b4fa8e40379f4956db0cd2605972b5d8baa8c2
and this one returns incorrect output:
05179116ffce339b480a9d3fee68981da4f5f313
I had to reverse the exit codes in `git bisect` in order to find the newest incorrect commit.

The "correct" commit adds `test_ccode_Pow()` to `sympy/printing/tests/test_ccode.py` and I think that it tests all the cases that we want.

**Closed** 2017-07-11 15:00 UTC
Labels: codegen, printing

**Comment by moorepants** [comment] 2017-07-11 15:09
@bjodah Was this fixed?

**Comment by bjodah** [comment] 2017-07-11 15:17
'**' is not being emitted for the code in the issue when using SymPy 1.1
