### ISSUE TITLE
InconsistentAssumptions sympy error

### ISSUE THREAD

**Issue by jdmallo25** [sympy/sympy#22537] opened 2021-11-21 09:45 UTC
My program crushes with error. (you can find code here: https://github.com/jdmallo25/beam_deflection_computing/blob/main/program.py)
It happens in different moments (100 iterations - 200 iterations), but error is always the same.
This is 80th iteration. I start the program like this (previously ):  python d.py -lbi -274 -rbi 0
I would like to know what I did wrong. Thank you!
`
[13:24:42]       [0]     solve(24.0, -776.0, 10, 0.001)
[13:24:42]       [1]     solve(24.0, -774.6666666666666, 10, 0.001)
[13:24:42]       [2]     solve(24.0, -773.3333333333334, 10, 0.001)
[13:24:42]       [3]     solve(24.0, -772.0, 10, 0.001)
[13:24:44]       [0]     iteration #0
[13:24:44]       [3]     iteration #0
[13:24:44]       [2]     iteration #0
[13:24:45]       [1]     iteration #0
Exception in thread 3:
Traceback (most recent call last):
  File "C:\Users\Andrey\AppData\Local\Programs\Python\Python38\lib\site-packages\sympy\core\assumptions.py", line 462, in getit
    return self._assumptions[fact]
KeyError: 'zero'
[13:24:53]       [2]     iteration #1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Andrey\AppData\Local\Programs\Python\Python38\lib\site-packages\sympy\core\assumptions.py", line 462, in getit
    return self._assumptions[fact]
KeyError: 'extended_real'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Andrey\AppData\Local\Programs\Python\Python38\lib\site-packages\sympy\core\assumptions.py", line 462, in getit
    return self._assumptions[fact]
KeyError: 'finite'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Andrey\AppData\Local\Programs\Python\Python38\lib\site-packages\sympy\core\assumptions.py", line 462, in getit
    return self._assumptions[fact]
KeyError: 'integer'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Andrey\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "d.py", line 16, in run
[13:24:55]       [1]     [uw]    [8.85295568e-01 1.15775414e+00 1.00442109e+00 5.71818390e-01 2.68289195e-15 -5.71818390e-01 -1.00442109e+00 -1.15775414e+00 -8.85295568e-01 -4.14948517e-01 -7.52727968e-01 -9.96851869e-01 -1.14379881e+00 -1.19282330e+00 -1.14379881e+00 -9
.96851869e-01 -7.52727968e-01 -4.14948517e-01]
    self._return = self._target(*self._args, **self._kwargs)
[13:24:55]       [0]     iteration #1
  File "d.py", line 133, in solve
    f0 = sp.matrix2numpy(equations_matrix.subs(uw_tuples), dtype=np.float64)
  File "C:\Users\Andrey\AppData\Local\Programs\Python\Python38\lib\site-packages\sympy\matrices\common.py", line 2417, in subs
    return self.applyfunc(lambda x: x.subs(*args, **kwargs))
  File "C:\Users\Andrey\AppData\Local\Programs\Python\Python38\lib\site-packages\sympy\matrices\common.py", line 2047, in applyfunc
    return self._eval_applyfunc(f)
  File "C:\Users\Andrey\AppData\Local\Programs\Python\Python38\lib\site-packages\sympy\matrices\common.py", line 1987, in _eval_applyfunc
    out = self._new(self.rows, self.cols, [f(x) for x in self])
  File "C:\Users\Andrey\AppData\Local\Programs\Python\Python38\lib\site-packages\sympy\matrices\common.py", line 1987, in <listcomp>
    out = self._new(self.rows, self.cols, [f(x) for x in self])
  File "C:\Users\Andrey\AppData\Local\Programs\Python\Python38\lib\site-packages\sympy\matrices\common.py", line 2417, in <lambda>
    return self.applyfunc(lambda x: x.subs(*args, **kwargs))
  File "C:\Users\Andrey\AppData\Local\Programs\Python\Python38\lib\site-packages\sympy\core\basic.py", line 953, in subs
    rv = rv._subs(old, new, **kwargs)
  File "C:\Users\Andrey\AppData\Local\Programs\Python\Python38\lib\site-packages\sympy\core\cache.py", line 72, in wrapper
    retval = cfunc(*args, **kwargs)
  File "C:\Users\Andrey\AppData\Local\Programs\Python\Python38\lib\site-packages\sympy\core\basic.py", line 1067, in _subs
    rv = fallback(self, old, new)
  File "C:\Users\Andrey\AppData\Local\Programs\Python\Python38\lib\site-packages\sympy\core\basic.py", line 1039, in fallback
    arg = arg._subs(old, new, **hints)
  File "C:\Users\Andrey\AppData\Local\Programs\Python\Python38\lib\site-packages\sympy\core\cache.py", line 72, in wrapper
    retval = cfunc(*args, **kwargs)
  File "C:\Users\Andrey\AppData\Local\Programs\Python\Python38\lib\site-packages\sympy\core\basic.py", line 1067, in _subs
    rv = fallback(self, old, new)
  File "C:\Users\Andrey\AppData\Local\Programs\Python\Python38\lib\site-packages\sympy\core\basic.py", line 1044, in fallback
    rv = self.func(*args)
  File "C:\Users\Andrey\AppData\Local\Programs\Python\Python38\lib\site-packages\sympy\core\cache.py", line 72, in wrapper
    retval = cfunc(*args, **kwargs)
  File "C:\Users\Andrey\AppData\Local\Programs\Python\Python38\lib\site-packages\sympy\core\operations.py", line 85, in __new__
    c_part, nc_part, order_symbols = cls.flatten(args)
  File "C:\Users\Andrey\AppData\Local\Programs\Python\Python38\lib\site-packages\sympy\core\mul.py", line 266, in flatten
    if not a.is_zero and a.is_Rational:
  File "C:\Users\Andrey\AppData\Local\Programs\Python\Python38\lib\site-packages\sympy\core\assumptions.py", line 466, in getit
    return _ask(fact, self)
  File "C:\Users\Andrey\AppData\Local\Programs\Python\Python38\lib\site-packages\sympy\core\assumptions.py", line 509, in _ask
    a = evaluate(obj)
  File "C:\Users\Andrey\AppData\Local\Programs\Python\Python38\lib\site-packages\sympy\core\add.py", line 691, in _eval_is_zero
    if a.is_extended_real:
  File "C:\Users\Andrey\AppData\Local\Programs\Python\Python38\lib\site-packages\sympy\core\assumptions.py", line 466, in getit
    return _ask(fact, self)
  File "C:\Users\Andrey\AppData\Local\Programs\Python\Python38\lib\site-packages\sympy\core\assumptions.py", line 521, in _ask
    _ask(pk, obj)
  File "C:\Users\Andrey\AppData\Local\Programs\Python\Python38\lib\site-packages\sympy\core\assumptions.py", line 521, in _ask
    _ask(pk, obj)
  File "C:\Users\Andrey\AppData\Local\Programs\Python\Python38\lib\site-packages\sympy\core\assumptions.py", line 521, in _ask
    _ask(pk, obj)
  File "C:\Users\Andrey\AppData\Local\Programs\Python\Python38\lib\site-packages\sympy\core\assumptions.py", line 509, in _ask
    a = evaluate(obj)
  File "C:\Users\Andrey\AppData\Local\Programs\Python\Python38\lib\site-packages\sympy\core\mul.py", line 1458, in _eval_is_imaginary
    if self.is_finite is False:
  File "C:\Users\Andrey\AppData\Local\Programs\Python\Python38\lib\site-packages\sympy\core\assumptions.py", line 466, in getit
    return _ask(fact, self)
  File "C:\Users\Andrey\AppData\Local\Programs\Python\Python38\lib\site-packages\sympy\core\assumptions.py", line 521, in _ask
    _ask(pk, obj)
  File "C:\Users\Andrey\AppData\Local\Programs\Python\Python38\lib\site-packages\sympy\core\assumptions.py", line 509, in _ask
    a = evaluate(obj)
  File "C:\Users\Andrey\AppData\Local\Programs\Python\Python38\lib\site-packages\sympy\core\mul.py", line 1635, in _eval_is_composite
    if not (arg.is_integer and arg.is_positive):
  File "C:\Users\Andrey\AppData\Local\Programs\Python\Python38\lib\site-packages\sympy\core\assumptions.py", line 466, in getit
    return _ask(fact, self)
  File "C:\Users\Andrey\AppData\Local\Programs\Python\Python38\lib\site-packages\sympy\core\assumptions.py", line 501, in _ask
    assumptions._tell(fact, None)
  File "C:\Users\Andrey\AppData\Local\Programs\Python\Python38\lib\site-packages\sympy\core\facts.py", line 491, in _tell
    raise InconsistentAssumptions(self, k, v)
sympy.core.facts.InconsistentAssumptions: {
        algebraic: None,
        antihermitian: None,
        commutative: True,
        complex: True,
        composite: False,
        even: False,
        extended_negative: False,
        extended_nonnegative: True,
        extended_nonpositive: False,
        extended_nonzero: True,
        extended_positive: True,
        extended_real: True,
        finite: True,
        hermitian: True,
        imaginary: False,
        infinite: False,
        integer: False,
        irrational: None,
        negative: False,
        noninteger: True,
        nonnegative: True,
        nonpositive: False,
        nonzero: True,
        odd: False,
        positive: True,
        prime: False,
        rational: None,
        real: True,
        zero: False}, integer=None
[13:25:02]       [2]     [uw]    [8.84874443e-01 1.15725047e+00 1.00400082e+00 5.71583173e-01 -3.36461180e-16 -5.71583173e-01 -1.00400082e+00 -1.15725047e+00 -8.84874443e-01 -4.14440760e-01 -7.51819208e-01 -9.95657806e-01 -1.14243411e+00 -1.19140179e+00 -1.14243411e+00 -
9.95657806e-01 -7.51819208e-01 -4.14440760e-01]
[13:25:03]       [0]     [uw]    [8.85714798e-01 1.15825532e+00 1.00483919e+00 5.72052374e-01 -1.46025706e-15 -5.72052374e-01 -1.00483919e+00 -1.15825532e+00 -8.85714798e-01 -4.15455875e-01 -7.53636004e-01 -9.98044974e-01 -1.14516242e+00 -1.19424366e+00 -1.14516242e+00 -
9.98044974e-01 -7.53636004e-01 -4.15455875e-01]
Traceback (most recent call last):
  File "d.py", line 281, in <module>
    main()
  File "d.py", line 270, in main
    w_len = int(len(solution) / 2)
TypeError: object of type 'NoneType' has no len()
`

**Comment by oscarbenjamin** [comment] 2021-11-21 11:43
This looks like a bug in the assumptions system but it's hard to debug from a program like this.

**Comment by oscarbenjamin** [comment] 2021-11-21 11:45
Is the use of threads necessary to reproduce this? A non-threaded program would be much easier to debug.

**Comment by jdmallo25** [comment] 2021-11-22 11:27
> Is the use of threads necessary to reproduce this? A non-threaded program would be much easier to debug.

It can be rewritten without threads and it solves my problem, but only partially, because with threads the program works faster (not exactly, because I didn't calculate average time of execution :) ). I would like to see this with threads, I like how it works, but there is the error, which can't be solved by me. (using of threads isn't necessary, but desirable in here)

I make this without threads and it's works, maybe my custom Thread class is the problem I don't know. But it works. Thank you. But also I would like to know where is the error is. I can't sleep well if I know there is a problem. :)

P.S. 4-threaded faster then single threaded the program. (x1.5 times)
P.P.S. I didn't get any errors while I used single threaded version of the program. So I would like to know where I mistaken.

**Comment by oscarbenjamin** [comment] 2021-11-22 12:45
Typically in Python a CPU-bound program will not be made faster using threads because of the GIL.

The cause of the problem is most likely a bug in SymPy. The reason I ask if the threads are needed to reproduce this is because it is difficult for me to identify the cause of the problem in a threaded program.  Actually though I think that the bug here is specifically to do with threading.

The error comes from here which tries to detect inconsistent facts in the assumptions dict:
https://github.com/sympy/sympy/blob/555c8cbfabffb47fc89e12b936a94dea52fdbae5/sympy/core/facts.py#L487-L491
That was called by this line (which I have always disliked and would like to remove, but that's not easy to do):
https://github.com/sympy/sympy/blob/555c8cbfabffb47fc89e12b936a94dea52fdbae5/sympy/core/assumptions.py#L516-L518
That in turn is called from here:
https://github.com/sympy/sympy/blob/555c8cbfabffb47fc89e12b936a94dea52fdbae5/sympy/core/assumptions.py#L535-L538
The guard `if pk in assumptions` is supposed to prevent `_ask` being called for an assumption that is already known. However in a multithreaded context there is a race condition in between the check and the call to `_tell` so if the same assumptions query gets resolved in a different thread then `_tell` will object to being told to make the value `None` if it has already been set to True or False.

I expect that this will be problematic for any multithreaded code where the same SymPy expression is manipulated in two different threads. The solution is to remove the call to `_tell` but it is there to guard against a large number of `_eval_is` methods that effectively have infinite recursion. Fixing this would require reworking all the core assumptions handlers so that they never recurse to a direct query on the same object. An example of the infinite recursion would be something like:
```python
def _eval_is_positive(self):
    if self.is_negative:
        return False
```
Here the `self.is_negative` query will internally lead to `is_positive` being checked which would lead back to this function leading to infinite recursion. The `_tell(fact, None)` line ensures that `is_positive` doesn't get called by any recursive assumptions queries so that we don't see the infinite recursion. Instead of infinite recursion we just get non-deterministic and non-thread-safe behaviour.

Personally I think that call to `_tell` is just there to hide bugs but removing it would require fixing *all* of those bugs at least in the SymPy codebase. It's also unclear what the impact would be in downstream code that might potentially have implemented assumptions handlers (although I expect that there isn't much of that).

**Comment by oscarbenjamin** [comment] 2021-11-22 12:51
A quick fix for this particular problem could be
```diff
diff --git a/sympy/core/assumptions.py b/sympy/core/assumptions.py
index b8a8c1990d..22b42c4be8 100644
--- a/sympy/core/assumptions.py
+++ b/sympy/core/assumptions.py
@@ -210,7 +210,7 @@
 
 """
 
-from .facts import FactRules, FactKB
+from .facts import FactRules, FactKB, InconsistentAssumptions
 from .core import BasicMeta
 from .sympify import sympify
 
@@ -515,7 +515,10 @@ def _ask(fact, obj):
 
     # Store None into the assumptions so that recursive attempts at
     # evaluating the same fact don't trigger infinite recursion.
-    assumptions._tell(fact, None)
+    try:
+        assumptions._tell(fact, None)
+    except InconsistentAssumptions:
+        return assumptions[fact]
 
     # First try the assumption evaluation function if it exists
     try:
```

**Comment by jdmallo25** [comment] 2021-11-22 15:02
> A quick fix for this particular problem could be
> 
> ```diff
> diff --git a/sympy/core/assumptions.py b/sympy/core/assumptions.py
> index b8a8c1990d..22b42c4be8 100644
> --- a/sympy/core/assumptions.py
> +++ b/sympy/core/assumptions.py
> @@ -210,7 +210,7 @@
>  
>  """
>  
> -from .facts import FactRules, FactKB
> +from .facts import FactRules, FactKB, InconsistentAssumptions
>  from .core import BasicMeta
>  from .sympify import sympify
>  
> @@ -515,7 +515,10 @@ def _ask(fact, obj):
>  
>      # Store None into the assumptions so that recursive attempts at
>      # evaluating the same fact don't trigger infinite recursion.
> -    assumptions._tell(fact, None)
> +    try:
> +        assumptions._tell(fact, None)
> +    except InconsistentAssumptions:
> +        return assumptions[fact]
>  
>      # First try the assumption evaluation function if it exists
>      try:
> ```

Thanks for the answers!

**Comment by oscarbenjamin** [comment] 2021-11-23 11:19
GitHub issues are not for you to resolve your problem. They represent things that should be improved in SymPy itself. Since there is something that can be improved here I am reopening the issue.

**Closed** 2021-11-27 12:37 UTC
Labels: assumptions
