### ISSUE TITLE
bell(n).limit(n, oo) should be oo rather than bell(oo)

### ISSUE THREAD

**Issue by sethebner** [sympy/sympy#9184] opened 2015-03-22 09:10 UTC
`bell(n).limit(n,oo)` should take the value infinity, but the current output is `bell(oo)`. As the Bell numbers represent the number of partitions of a set, it seems natural that `bell(oo)` should be able to be evaluated rather than be returned unevaluated. This issue is also in line with the recent fixes to the corresponding limit for the Fibonacci numbers and Lucas numbers.

```
from sympy import *
n = symbols('n')
bell(n).limit(n,oo)

Output:
bell(oo)
```

I'm new to Sympy, so I'd appreciate the opportunity to fix this bug myself if that's alright.

**Comment by pelegm** [comment] 2015-04-05 12:45
Isn't that a duplicate of #8772?

**Closed** 2017-10-13 04:35 UTC

**Comment by pelegm** [comment] 2017-10-15 11:40
Should this close #8772 as well?

**Comment by gxyd** [comment] 2017-10-15 11:59
Yes, I have closed the issue. Thanks, I forgot to close this.
