### ISSUE TITLE
refine(sqrt(x**2), Q.positive(x)) stopped working

### ISSUE THREAD

**Issue by certik** [sympy/sympy#10082] opened 2015-10-30 15:31 UTC
Before 270c351966f75cb4edbdf780af7081f82b616b5e we had the following (correct) behavior:
```
In [1]: refine(sqrt(x**2), Q.positive(x))
Out[1]: x
```
After that commit, we have the following (incorrect) behavior:
```
In [1]: refine(sqrt(x**2), Q.positive(x))

```
Or in master, we get:
```
In [1]: refine(sqrt(x**2), Q.positive(x))
Out[1]: │x│
```
Either way, this looks like a major regression. I don't quite understand that none of our tests failed.

**Comment by debugger22** [comment] 2015-10-30 15:54
Hi Ondrej. I'll try to fix it today.

**Comment by certik** [comment] 2015-10-30 17:49
@debugger22 thanks. I just discovered that with @woodscn today. It's weird, because I thought it is part of our doctests here: http://docs.sympy.org/dev/modules/assumptions/refine.html#sympy.assumptions.refine.refine

**Comment by asmeurer** [comment] 2015-10-30 18:58
Looks like those doctests were changed at 9a7732a8. We should revert them back to how they were and add real tests to this too (after fixing the issue).

**Comment by asmeurer** [comment] 2015-11-17 00:42
@debugger22 are you still planning to fix this?

The problem is that `_eval_refine` uses the old assumptions, but it needs to use the new assumptions. Also, `_eval_refine` itself needs to take `assumptions` as an argument, and use things like `ask(Q.positive(e), assumptions)` instead of `e.is_positive`. Other `_eval_refine` functions should be fixed as well. 

If you don't have time to fix it I will do it, but let me know either way, since this is blocking the release.

**Comment by asmeurer** [comment] 2015-11-17 17:24
Also `refine_Pow` needs to call `refine` recursively when it returns an `abs`.

**Comment by asmeurer** [comment] 2015-11-18 17:21
Oh never mind on the recursive thing. `refine` does that automatically.

**Comment by asmeurer** [comment] 2015-11-18 18:29
I'm hitting some snags fixing this because of https://github.com/sympy/sympy/issues/10148. Also, it seems that refine is much slower when using ask than using the old assumptions (which is to be expected).

**Comment by asmeurer** [comment] 2015-11-18 20:34
A "fix" at https://github.com/asmeurer/sympy/tree/eval_refine, but there are some issues.

**Comment by debugger22** [comment] 2015-11-19 07:38
Sorry about it. I was carried away by other things. I've commented on the PR.

**Comment by asmeurer** [comment] 2015-12-29 19:19
The PR in question is https://github.com/sympy/sympy/pull/10149

**Comment by kshitij10496** [comment] 2015-12-29 19:33
Thanks @asmeurer 
I will try to work on this.

**Comment by thisch** [comment] 2016-01-10 20:13
@kshitij10496 any updates on your work on this issue?

**Comment by kshitij10496** [comment] 2016-01-11 08:46
@thisch I am a bit stuck on @asmeurer 's suggestions [here](https://github.com/sympy/sympy/pull/10149).
Meanwhile feel free to share your ideas on this.

**Comment by asmeurer** [comment] 2016-02-15 21:31
Fix at https://github.com/sympy/sympy/pull/10600

**Closed** 2016-02-16 16:00 UTC
Labels: assumptions
