### ISSUE TITLE
Website "Documentation" links: change from `http` to `https`

### ISSUE THREAD

**Issue by jessexknight** [sympy/sympy#14910] opened 2018-07-13 16:54 UTC
The Documentation links on the [project website](http://www.sympy.org/en/index.html) have destination
`http://www.sympy.org/en/index.html`.

This non-secure `http` protocol results (for me) in a hung page on Google Chrome (never loads).
However, simply typing `https://www.sympy.org/en/index.html` (note `https`) into my search-bar results in immediate (secure) page load.

Try it yourself!
[`http` link](http://www.sympy.org/en/index.html)
[`https` link](https://www.sympy.org/en/index.html)

Can the webmaster update these links to `https`?

PS
It appears most links on the project website use `http` (though these do not result in hung pages) - perhaps they should all be updated.

**Comment by sidhantnagpal** [comment] 2018-08-15 18:01
Similar to #13313. Both the links redirect to https version for me, though the connection is not fully secure.

**Comment by asmeurer** [comment] 2018-08-15 18:32
Close this issue as a dupe of that one.

**Closed by asmeurer** 2018-08-15 18:32 UTC
