### ISSUE TITLE
Dsolve and substitution leads to an equation that looks correct but isn't solved

### ISSUE THREAD

**Issue by petschge** [sympy/sympy#20629] opened 2020-12-18 22:00 UTC
Consider the following example:

```python
import sympy

C1, T, n0, z = sympy.symbols("C1 T n0 z", positive=True)
n = sympy.symbols("n", cls=sympy.Function)
dndz = n(z).diff(z)

ODE1 = sympy.Eq(T*dndz, -n(z))
sol = sympy.dsolve(ODE1, n(z))

print("sol = "+str(sol))

eq1 = sympy.Eq(sol.rhs.subs(z,0), n0)
print("eq1 = "+str(eq1))
sol = sympy.solve(eq1, C1)
print("sol = "+str(sol))

eq2 = sympy.Eq(sympy.exp(C1/T), n0)
print("eq2 = "+str(eq2))
sol = sympy.solve(eq2, C1)
print("sol = "+str(sol))

print("eq1 == eq2: "+str(eq1 == eq2))

```

which outputs

```
sol = Eq(n(z), exp((C1 - z)/T))
eq1 = Eq(exp(C1/T), n0)
sol = []
eq2 = Eq(exp(C1/T), n0)
sol = [T*log(n0)]
eq1 == eq2: False
```

ODE1 is correctly solved. The equation from the lower boundary conditions looks correct too. But it only produces an empty solution. Retyping the equation manually as eq2 produces something that looks identical to print, but that can be correctly solved and does not compare as equal.

**Comment by asmeurer** [comment] 2020-12-18 23:22
The reason is that you specified an assumption `positive=True` when creating `C1`, which makes it distinct from the `C1 = Symbol("C1")` with no assumptions returned by `dsolve`. Symbols with the same name but different assumptions compare unequal.

**Comment by asmeurer** [comment] 2020-12-18 23:24
There's an issue about being able to specify the constants manually https://github.com/sympy/sympy/issues/11024. Some method to extract the constant symbols from the ODE solution might be useful as well. I don't know if there's already an issue for that.

**Comment by petschge** [comment] 2020-12-18 23:31
right. While C1 ends up being positive, not forcing that on the symbol level did fix that issue. Thanks.

**Comment by asmeurer** [comment] 2020-12-19 00:22
Also, I should point out that you can use the `ics` flag to dsolve to solve for constants automatically:

```py
>>> dsolve(ODE1, n(z), ics={n(0): n0})
Eq(n(z), exp((T*log(n0) - z)/T))
```

**Comment by oscarbenjamin** [comment] 2020-12-19 00:22
Yes, so the issue is just that symbols with different assumptions are considered independent which is by design. Otherwise everything seems to be working so I'll close this.

Thanks for reporting!

**Closed by oscarbenjamin** 2020-12-19 00:22 UTC
