### ISSUE TITLE
While plotting using symplot y label comes misaligned 

### ISSUE THREAD

**Issue by abhishek-kuma** [sympy/sympy#24872] opened 2023-03-07 06:37 UTC
`y=(1/2*pi)*exp(-(x**2)/2)
symplot(y)`
![output](https://user-images.githubusercontent.com/96915839/223341791-c84bc4bb-7abc-421b-a306-1753c87c083f.png)

**Comment by samithkavishke** [comment] 2023-03-07 09:56
I will try to solve this bug

**Comment by samithkavishke** [comment] 2023-03-07 15:38
Can you give me the full code of this. Because it shows me there is no function call symplot.

**Comment by abhishek-kuma** [comment] 2023-03-07 20:40
yes
from sympy import *
from sympy.plotting import plot as symplot

x = symbols('x')
y=(1/2*pi)*exp(-(x**2)/2)
symplot(y)
`
`

**Comment by abhishek-kuma** [comment] 2023-03-07 20:40
`from sympy import *
from sympy.plotting import plot as symplot

x = symbols('x')
y=(1/2*pi)*exp(-(x**2)/2)
symplot(y)
`

**Comment by victorian177** [comment] 2023-03-08 10:59
Hey, @abhishek-kuma. There seems to be no problem here. I copied your code and could not reproduce the above error. I replicated your code snippet in matplotlib and it gave the same plots.

```
import matplotlib.pyplot as plt
import numpy as np
from sympy import *
from sympy.plotting import plot as symplot

# SymPlot Implementation
x = symbols("x")
y = (1 / 2 * pi) * exp(-(x**2) / 2)
symplot(y)

# Matplotlib Implementation
def f(x):
    return (1 / 2 * np.pi) * np.exp(-(x**2) / 2)


x = np.linspace(-5, 5, 100)
y = f(x)

plt.plot(x, y)
plt.xlabel("x")
plt.ylabel("y")
plt.show()
```

**Comment by TiloRC** [comment] 2023-03-10 21:42
> `from sympy import * from sympy.plotting import plot as symplot
> 
> x = symbols('x') y=(1/2*pi)*exp(-(x**2)/2) symplot(y) `

I tried running this code and it worked fine:
<img width="630" alt="Screen Shot 2023-03-10 at 1 41 42 PM" src="https://user-images.githubusercontent.com/67246777/224433791-01e2494a-7554-49f1-8d08-f971c3882103.png">

**Comment by oscarbenjamin** [comment] 2023-03-10 22:05
It works fine for me as well. Without more information there is nothing much we can do with this issue so I'm going to close it.

**Closed by oscarbenjamin** 2023-03-10 22:05 UTC
