### ISSUE TITLE
dsolve doesn't work with dynamicsymbols

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#12044] opened 2017-01-13 20:00 UTC
Reported from the mailing list. First, if you use dynamicssymbols with dsolve, it fails:

```

    from sympy import *;
    init_printing()
    
    Ex,Ey,Ez,Bx,By,Bz,c,m0,t,u,we,wb,q=symbols('E_x E_y E_z B_x B_y B_z c m_0 t u omega_E omega_B q')
    tau=dynamicsymbols('tau')
    
    u0=Function('u^0')(tau) 
    u1=Function('u^1')(tau)
    u2=Function('u^2')(tau)
    u3=Function('u^3')(tau)
    
    u=Matrix([u0,u1,u2,u3])
    Emat=Matrix([[0,Ex/c,Ey/c,Ez/c],[Ex/c,0,Bz,-By],[Ey/c,-Bz,0,Bx],[Ez/c,By,-Bx,0]])
    RHS=q/m0*Emat*u
    
    odesys=[Eq(u0.diff(),RHS[0]),Eq(u1.diff(),RHS[1]),Eq(u2.diff(),RHS[2]),Eq(u3.diff(),RHS[3])]
    odesys
    dsolve(odesys,[u0, u1, u2, u3])
```

This fails with

```
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-44-bf3106e3938d> in <module>()
----> 1 dsolve(odesys,[u0,u1,u2,u3])

/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/solvers/ode.py in dsolve(eq, func, hint, simplify, ics, xi, eta, x0, n, **kwargs)
    582     """
    583     if iterable(eq):
--> 584         match = classify_sysode(eq, func)
    585         eq = match['eq']
    586         order = match['order']

/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/solvers/ode.py in classify_sysode(eq, funcs, **kwargs)
   1381                     max_order = order_
   1382                     eq_no = i
-> 1383             if eq_no in func_dict:
   1384                 list_func = []
   1385                 list_func.append(func_dict[eq_no])

UnboundLocalError: local variable 'eq_no' referenced before assignment

```

If you use a normal Symbol, `dsolve` hangs and eventually returns `None`.

**Comment by moorepants** [comment] 2017-01-13 21:37
All a dynamicsymbol is is:

```
F = Function('F')
t = symbols('t')
F(t) == dynamicsymbols('F')
```

Looks the above does:

```
t = symbols('t')
tau = Function('tau')(t)
u0=Function('u^0')(tau)
```

**Comment by asmeurer** [comment] 2017-01-13 23:08
Ah, the problem is it uses `diff`, which takes the derivative wrt `t` instead of `tau`, which confuses the solver. The UnboundLocalError should be fixed in any case.

**Comment by pspbot7** [comment] 2017-03-17 17:55
I tried to type the code but it is giving the following error

> NameError: name 'dynamicsymbols' is not defined

can you explain me the reason for this error

**Comment by asmeurer** [comment] 2017-03-17 17:57
I guess you have to import it from `sympy.physics.mechancs`.

**Comment by vishalg2235** [comment] 2018-02-19 17:33
@pspbot7 are you still working on this issue ? Can I open a PR for this ?

**Comment by pspbot7** [comment] 2018-02-19 18:16
I am currently not working on it, so you can open a new PR on the issue.

**Comment by vishalg2235** [comment] 2018-02-20 07:33
>the problem is it uses diff() with no arguments, which takes the derivative wrt t instead of tau
>
@asmeurer where does it uses `diff()`?? is it here -> `t = list(list(eq[0].atoms(Derivative))[0].atoms(Symbol))[0]` in line 1497 ? Can you please elaborate the problem here?

**Comment by jksuom** [comment] 2018-02-20 08:25
The user code uses `diff()`:

`odesys=[Eq(u0.diff(),RHS[0]),Eq(u1.diff(),RHS[1]),Eq(u2.diff(),RHS[2]),Eq(u3.diff(),RHS[3])]`

**Comment by vishalg2235** [comment] 2018-02-20 12:52
Ok the problem should use `diff(tau)` : 
`odesys=[Eq(u0.diff(tau),RHS[0]),Eq(u1.diff(tau),RHS[1]),Eq(u2.diff(tau),RHS[2]),Eq(u3.diff(tau),RHS[3])]`

Then, 
```
(Pdb) eq
[-E_x*q*u^1(tau(t))/(c*m_0) - E_y*q*u^2(tau(t))/(c*m_0) - E_z*q*u^3(tau(t))/(c*m_0) + Subs(Derivative(u^0(_xi_0), _xi_0), (_xi_0,), (tau(t),)), B_y*q*u^3(tau(t))/m_0 - B_z*q*u^2(tau(t))/m_0 - E_x*q*u^0(tau(t))/(c*m_0) + Subs(Derivative(u^1(_xi_0), _xi_0), (_xi_0,), (tau(t),)), -B_x*q*u^3(tau(t))/m_0 + B_z*q*u^1(tau(t))/m_0 - E_y*q*u^0(tau(t))/(c*m_0) + Subs(Derivative(u^2(_xi_0), _xi_0), (_xi_0,), (tau(t),)), B_x*q*u^2(tau(t))/m_0 - B_y*q*u^1(tau(t))/m_0 - E_z*q*u^0(tau(t))/(c*m_0) + Subs(Derivative(u^3(_xi_0), _xi_0), (_xi_0,), (tau(t),))]
(Pdb) order
{}
(Pdb) funcs
[u^2(tau(t)), u^3(tau(t)), u^0(tau(t)), u^1(tau(t))]
```
The equations has `Subs(Derivative(u^0(_xi_0), _xi_0), (_xi_0,), (tau(t),))`, I think due to that `ode_order(eqs_,func)` (in line 1517) is returning 0 order wrt elements in `funcs`.
@jksuom  please help me in resolving the main problem.

**Comment by oscarbenjamin** [comment] 2018-11-14 23:08
I can't reproduce any problem with using `dynamicssymbols`. They generally work fine in `dsolve` e.g.:
```julia
In [1]: from sympy.physics.mechanics import dynamicsymbols

In [2]: tau = dynamicsymbols('tau')

In [3]: dsolve(tau.diff()-1)
Out[3]: τ(t) = C₁ + t
```

Simplifying the problem above and replacing the coefficient symbols with numbers I get a (complicated) solution with this:
```python
#!/usr/bin/env python

from sympy import *
from sympy.physics.mechanics import dynamicsymbols

x, y, z, w = dynamicsymbols('x y z w')
t = Symbol('t')

X = Matrix([x, y, z, w])

M = Matrix([
[0,  1,  2,  3],
[1,  0,  6, -5],
[2, -6,  0,  4],
[3,  5, -4,  0]])

eq = list(X.diff() - M * X)
pprint(eq)
pprint(dsolve(eq, list(X)))
```

The fact that it hangs (for a little while) is down to computing the Eigenvectors of a 4x4 symbolic matrix. You can reproduce that with an equivalent but simplified matrix (I haven't waited long enough to see the output of this):
```python
#!/usr/bin/env python

from sympy import *
from sympy.abc import a, b, c, d, e, f

M = Matrix([
[0,  a,  b,  c],
[a,  0,  f, -e],
[b, -f,  0,  d],
[c,  e, -d,  0]])

pprint(M.eigenvals())
pprint(M.eigenvects())
```

I don't think this is a valid issue in `dsolve` (any more at least). It's possible that `eigenvects` could do a better job getting a simpler/faster output for the symbolic matrix above but I don't know of any reason why a simpler output would exist.

**Comment by arooshiverma** [comment] 2019-03-09 14:00
Is this issue open?

**Comment by oscarbenjamin** [comment] 2019-03-09 15:28
Okay I see the problem:
```julia
In [1]: f = Function('f')                                                                                                                                     

In [2]: t = Symbol('t')                                                                                                                                       

In [3]: from sympy.physics.mechanics import dynamicsymbols                                                                                                    

In [4]: tau = dynamicsymbols('tau')                                                                                                                           

In [5]: tau                                                                                                                                                   
Out[5]: τ(t)
```
Note that tau is a function of t (because that's what dynamicsymbols means)

Using no argument diff allows to differentiate based on the argument of a function e.g.:
```julia
In [6]: f(t)                                                                                                                                                  
Out[6]: f(t)

In [7]: f(t).diff()                                                                                                                                           
Out[7]: 
d       
──(f(t))
dt      

In [8]: f(x).diff()                                                                                                                                           
Out[8]: 
d       
──(f(x))
dx 
```
The original example in this thread does:
```julia
In [9]: f(tau)                                                                                                                                                
Out[9]: f(τ(t))

In [10]: f(tau).diff()                                                                                                                                        
Out[10]: 
  d            d       
─────(f(τ(t)))⋅──(τ(t))
dτ(t)          dt
```
That doesn't work the way expected because what was wanted was to differentiate with respect to tau not t. I think it's entirely reasonable though that no argument diff guess this should differentiate wrt t. The solution is to tell diff which argument to use:
```julia
In [11]: f(tau).diff(tau)                                                                                                                                     
Out[11]: 
  d           
─────(f(τ(t)))
dτ(t)
```
Also there's no point using dynamicsymbols for the independent variable anyway.

I'm closing this as it's based on a misunderstanding and isn't an issue to solve.

**Closed by oscarbenjamin** 2019-03-09 15:28 UTC
Labels: physics.mechanics, solvers.dsolve
