### ISSUE TITLE
"from sympy import *" imports every package name

### ISSUE THREAD

**Issue by p-tka4enko** [sympy/sympy#13592] opened 2017-11-12 16:56 UTC
I noticed that `from sympy import *` additionally imports every package name, like `core` or `functions`. Is it an intended behavior?

**Comment by BMaxV** [comment] 2017-11-14 21:53
All __init__.py s are written that way. So yes, this happens for everyone. I have to assume it's intentional.

**Comment by pavel-tkachenko** [comment] 2017-11-17 17:50
@asmeurer has already noticed (#13525) that this is not intended behavior for submodules.
But now I mean the main packages (`core`, `logic`, `assumptions`, `polys`, `series`, `functions`, etc).

**Comment by BMaxV** [comment] 2017-11-17 20:08
To be honest, I could speculate about this, but I'd rather leave you with [the documentation](https://docs.python.org/3/tutorial/modules.html) about imports and __all__.

**Comment by asmeurer** [comment] 2017-11-18 00:22
Adding `__all__` to the main `__init__.py` would fix this. But we need to figure out a way to do this that doesn't lead to accidentally leaving things out. I guess we should have some tests that `__all__` is consistent across the `__init__.py` files.

**Comment by oscarbenjamin** [comment] 2019-02-27 22:41
I would rather explicitly list all the things that are being imported in the `__init__.py` files. That does mean you have to explicitly add things if you want them to make it to the main sympy namespace but I think that's a good thing.

**Comment by asmeurer** [comment] 2019-02-27 22:48
You mean the top-level `sympy/__init__.py` should list everything, in addition to the lower level ones (like `sympy/solvers/__init__.py`)?

**Comment by asmeurer** [comment] 2019-02-27 22:53
Actually I guess you have to define `__all__` in the main `sympy/__init__.py` in order to avoid the module names from being included in `from sympy import *`. So we might as well duplicate the imports as well. But we should include some code quality checks that 

- `__all__` and imported names match each other
- Any name in `__all__` in a submodule that is imported in `sympy/__init__.py` is actually imported there.

A middle ground would be to do the `__all__` merge in `sympy/__init__.py` automatically. 

```py
__all__ = []

from .core import *
__all__ += core.__all__
...
```

Although we should make sure this doesn't affect import time too much.

**Comment by asmeurer** [comment] 2019-02-27 22:57
There's also https://github.com/sympy/sympy/issues/13525. I thought of closing this as a dupe of it, but I guess they are technically different. To fix this issue, we need to define `__all__` in `sympy/__init__.py`. But that issue is about defining `__all__` in each submodule's `__init__.py`. That issue can be fixed separately of this one. It is also most likely a prerequisite of fixing this one, assuming we do the `__all__` merging or code quality checks I mentioned. There are also some submodules that aren't included in the main `sympy/__init__.py`, but should be using `__all__` nonetheless.

**Comment by oscarbenjamin** [comment] 2019-02-27 23:23
> Although we should make sure this doesn't affect import time too much.

What makes you think that import time would be affected in any significant way at all?

CPython is well optimised for importing lots of .py files that define functions, classes and basic data structures. Using `__all__` or not will not significantly affect the fact that the interpreter has to read many files and parse many things. Probably some SymPy imports involve symbolic computations that could easily dwarf other things.

Here's a profile of importing SymPy:
```console
$ cat t.py
import sympy
$ time python -c 'import sympy'

real	0m1.797s
user	0m0.909s
sys	0m0.241s
$ python -m cProfile -s cumulative t.py 
         864019 function calls (827792 primitive calls) in 1.668 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
       27    0.002    0.000    2.676    0.099 __init__.py:1(<module>)
        3    0.001    0.000    1.766    0.589 __init__.py:12(<module>)
    521/1    0.014    0.000    1.668    1.668 {built-in method builtins.exec}
        1    0.000    0.000    1.668    1.668 t.py:1(<module>)
    496/1    0.007    0.000    1.668    1.668 <frozen importlib._bootstrap>:978(_find_and_load)
    496/1    0.004    0.000    1.668    1.668 <frozen importlib._bootstrap>:948(_find_and_load_unlocked)
    472/1    0.005    0.000    1.668    1.668 <frozen importlib._bootstrap>:663(_load_unlocked)
    449/1    0.004    0.000    1.668    1.668 <frozen importlib._bootstrap_external>:722(exec_module)
    579/1    0.001    0.000    1.667    1.667 <frozen importlib._bootstrap>:211(_call_with_frames_removed)
    86/20    0.001    0.000    1.281    0.064 {built-in method builtins.__import__}
      449    0.014    0.000    0.773    0.002 <frozen importlib._bootstrap_external>:793(get_code)
33239/30940    0.013    0.000    0.728    0.000 <frozen importlib._bootstrap>:1009(_handle_fromlist)
      449    0.027    0.000    0.576    0.001 <frozen importlib._bootstrap_external>:914(get_data)
      449    0.549    0.001    0.549    0.001 {method 'read' of '_io.FileIO' objects}
        1    0.000    0.000    0.411    0.411 summations.py:1(<module>)
        2    0.000    0.000    0.401    0.201 __init__.py:10(<module>)
        1    0.000    0.000    0.401    0.401 singularities.py:16(<module>)
        3    0.000    0.000    0.394    0.131 __init__.py:2(<module>)
        1    0.000    0.000    0.334    0.334 diophantine.py:1(<module>)
        1    0.000    0.000    0.331    0.331 solveset.py:12(<module>)
    48/46    0.000    0.000    0.329    0.007 singleton.py:105(__getattr__)
  7194/52    0.006    0.000    0.328    0.006 cache.py:92(wrapper)
    27/24    0.000    0.000    0.328    0.014 singleton.py:173(__call__)
        1    0.000    0.000    0.328    0.328 fancysets.py:1106(__new__)
        1    0.000    0.000    0.328    0.328 fancysets.py:836(__new__)
        8    0.000    0.000    0.327    0.041 decorators.py:84(__sympifyit_wrapper)
        5    0.000    0.000    0.327    0.065 decorators.py:122(binary_op_wrapper)
      3/2    0.000    0.000    0.327    0.164 operations.py:28(__new__)
        2    0.000    0.000    0.327    0.163 expr.py:128(__add__)
        1    0.000    0.000    0.326    0.326 add.py:78(flatten)
        1    0.000    0.000    0.323    0.323 tensor.py:30(<module>)
        1    0.000    0.000    0.293    0.293 polyhedron.py:1(<module>)
        1    0.000    0.000    0.285    0.285 polyhedron.py:596(_pgroup_calcs)
        1    0.000    0.000    0.262    0.262 polytools.py:1(<module>)
        2    0.000    0.000    0.256    0.128 __init__.py:6(<module>)
        2    0.001    0.000    0.254    0.127 polyhedron.py:672(_pgroup_of_double)
        1    0.000    0.000    0.243    0.243 constructor.py:1(<module>)
1052/1049    0.041    0.000    0.209    0.000 {built-in method builtins.__build_class__}
        1    0.000    0.000    0.208    0.208 expr.py:1(<module>)
       49    0.001    0.000    0.192    0.004 polyhedron.py:32(__new__)
        3    0.000    0.000    0.174    0.058 __init__.py:3(<module>)
       44    0.000    0.000    0.169    0.004 basic.py:104(copy)
      950    0.006    0.000    0.156    0.000 iterables.py:2070(minlex)
      449    0.004    0.000    0.154    0.000 <frozen importlib._bootstrap_external>:523(_compile_bytecode)
        1    0.000    0.000    0.152    0.152 polyfuncs.py:1(<module>)
      449    0.147    0.000    0.147    0.000 {built-in method marshal.loads}
        1    0.000    0.000    0.141    0.141 finitefield.py:1(<module>)
        1    0.000    0.000    0.134    0.134 evalf.py:4(<module>)
        1    0.000    0.000    0.131    0.131 numberfields.py:1(<module>)
        1    0.000    0.000    0.131    0.131 groundtypes.py:1(<module>)
        1    0.000    0.000    0.129    0.129 pythonrational.py:1(<module>)
7270/6957    0.052    0.000    0.127    0.000 compatibility.py:390(default_sort_key)
        1    0.000    0.000    0.125    0.125 rootoftools.py:1(<module>)
        1    0.000    0.000    0.122    0.122 polyroots.py:1(<module>)
        1    0.000    0.000    0.117    0.117 ctx_fp.py:1(<module>)
        1    0.000    0.000    0.115    0.115 lambdify.py:4(<module>)
        1    0.000    0.000    0.113    0.113 decorator.py:1(<module>)
        1    0.000    0.000    0.109    0.109 ctx_base.py:1(<module>)
     1693    0.008    0.000    0.109    0.000 {built-in method builtins.min}
        1    0.000    0.000    0.108    0.108 runtests.py:13(<module>)
      477    0.007    0.000    0.104    0.000 <frozen importlib._bootstrap>:882(_find_spec)
...
```

**Comment by asmeurer** [comment] 2019-02-27 23:34
You're probably right. It's just good to check things when refactoring the import system, to be sure. Doing `list +=` a bunch of time shouldn't be slow, but we should make sure.

And of course anything else that slows down the import time should be sped up too, if possible. Ideally no symbolic computations should happen at import time. I think a lot of the things in your profile could be improved. Some things probably can't be fixed without breaking compatibility (like creating instances and putting them on `S`). But for instance I suspect diophantine.py is slow because of [this `sorted` call](https://github.com/sympy/sympy/blob/f4b483507a6704f2f431494413c54766f3d77d3e/sympy/solvers/diophantine.py#L579), which could be replaced with making `diop_known` a pre-sorted list. 

This is a separate issue, though.

**Closed** 2020-01-09 03:35 UTC
Labels: Code quality
