### ISSUE TITLE
integrate(log(sin(x)), (x, 0, pi/2)) does not evaluate

### ISSUE THREAD

**Issue by divyanshu132** [sympy/sympy#16084] opened 2019-02-26 20:03 UTC
```
>>> integrate(log(sin(x)), (x, 0, pi/2))
Integral(log(sin(x)), (x, 0, pi/2))

```
It would be nice if we can make this expression evaluated instead of producing the same result.
The correct answer is `-pi*log(2)/2`

**Comment by wizardofhogwarts** [comment] 2019-03-03 04:26
Best method to solve this sort of integrals is to use series expansion or as we have a definite integral to solve we can use numerical approximation methods.
Here is a common identity:
`log(sin(x)) = -log2-cos(2x)-cos(4x)/2-cos(6x)/3- -------`

**Comment by divyanshu132** [comment] 2019-03-03 04:50
One of the way that I think will be easy to do is using `contour integrals`.
`log(sin(x)) = log|e^2*i*x - 1| - log2`

**Comment by XtremeGood** [comment] 2019-03-04 07:01
Contour integration is fine but this can be solved by chain rule too. Why don't we implement that? But maybe contour integration might be easier to do for many functions since spliting functions into two parts can be tough

**Comment by XtremeGood** [comment] 2019-03-21 17:11
Well best way to solve is using double integrals and using fubini's rule

**Comment by oscargus** [comment] 2019-08-05 13:07
Duplicate of #14074.

**Closed by oscargus** 2019-08-05 13:07 UTC
Labels: integrals, integrals.definite
