### ISSUE TITLE
dsolve should be able to set a prefix constant and fix behavior

### ISSUE THREAD

**Issue by latot** [sympy/sympy#11763] opened 2016-10-25 02:09 UTC
Hi all, following this https://github.com/sympy/sympy/issues/11756, i think dsolve should be able to set a constant prefix, and continue using "C" as default, because its too normal use that names and the actual behavior is too... undefined:

```
>>> dsolve(Derivative(f, x, 2)-f+Symbol("C1"))
                -x       x
f(x) = C₁ + C₂⋅ℯ   + C₃⋅ℯ 
>>> dsolve(Derivative(f, x, 2)-f+Symbol("C2"))
                -x       x
f(x) = C₁ + C₂⋅ℯ   + C₃⋅ℯ 
>>> dsolve(Derivative(f, x, 2)-f+Symbol("C2")*k)
                  -x       x
f(x) = C₁⋅k + C₂⋅ℯ   + C₃⋅ℯ 
```

dsolve os changing the user symbols......

So resuming:
- Improve a constant prefix for the user
- Fix behavior when constant is defined

Thx. Cya.

**Comment by asmeurer** [comment] 2016-11-01 18:25
This is a dupe of https://github.com/sympy/sympy/issues/11024 and https://github.com/sympy/sympy/issues/4838

**Closed by asmeurer** 2016-11-01 18:25 UTC
