### ISSUE TITLE
Inconsistent API of sampling from random variables

### ISSUE THREAD

**Issue by Smit-create** [sympy/sympy#19061] opened 2020-04-03 05:59 UTC
While working on sampling from external libraries in PR #18754, I see that `size` and `numsamples` arguments in different functions mean the same and has created an inconsistency of using which of them.

https://github.com/sympy/sympy/blob/63ab534ebc9bb8fa47ca80aea5a1b0eca743fb9e/sympy/stats/rv.py#L1020-L1040
In `sample` we have `size` as public API, while returning `numsamples` is by default kept as 1.

The following samplings have `size` and `numsamples` both as the argument.
https://github.com/sympy/sympy/blob/63ab534ebc9bb8fa47ca80aea5a1b0eca743fb9e/sympy/stats/rv.py#L1043

https://github.com/sympy/sympy/blob/63ab534ebc9bb8fa47ca80aea5a1b0eca743fb9e/sympy/stats/rv.py#L1130

https://github.com/sympy/sympy/blob/63ab534ebc9bb8fa47ca80aea5a1b0eca743fb9e/sympy/stats/rv.py#L1177

The following samplings have only `numsamples` as an argument.
https://github.com/sympy/sympy/blob/63ab534ebc9bb8fa47ca80aea5a1b0eca743fb9e/sympy/stats/rv.py#L1207

https://github.com/sympy/sympy/blob/63ab534ebc9bb8fa47ca80aea5a1b0eca743fb9e/sympy/stats/rv.py#L1243

https://github.com/sympy/sympy/blob/63ab534ebc9bb8fa47ca80aea5a1b0eca743fb9e/sympy/stats/rv.py#L1265

These lead to confusion and fails many times as:
```
>>> from sympy.stats import *
>>> X=Normal('X',1,2)
>>> sample(X)     # works fine
-1.57391020015325

>>> sample(X, size=3)   # works fine
[1.69231493540159, 1.69231493540159, 1.69231493540159]

>>> Y=Normal('Y',3,4)
>>> sample(X+Y, size=3)  # fails : expected 3
8.01476115427784

>>> sample(X, numsamples=3)  # fails : expected 3
-0.132248747800019

>>> sample(X+Y, numsamples=3)  # fails : expected 3
3.62703730515697

>>> list(sample_iter(X, size=3, numsamples=2))  # unexpected output(neither 2 nor 3)
[[0.310554545718285, 0.310554545718285, 0.310554545718285], [1.27257976990205, 1.27257976990205, 1.27257976990205]]

>>> list(sample_iter(X, numsamples=3))
[-1.46157892264006, 4.01242293224973, -2.73175071462870]

>>> sampling_density(X, size=2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/smit/Smit Lunagariya/sympy/sympy/stats/rv.py", line 1279, in sampling_density
    results[result] = results.get(result, 0) + 1
TypeError: unhashable type: 'list'

>>> sampling_density(X, numsamples=3) # we should expect a list of 3
{-2.61191742946724: 1, 4.20263875820254: 1, 3.97981174226570: 1}
```
Therefore, to prevent this confusion and failure, we can have only one argument throughout to maintain uniformity and consistency across all sampling methods.
Related issue #16942

**Comment by sylee957** [comment] 2020-04-03 07:05
In my opinion, I don't think that there is much a need of having finite `numsamples` for `sample_iter`, `sample_iter_lambdify`, `sample_iter_subs` as public keywords. (Because users can build a custom counter outside the iteration and terminate the loop) and `size` for `sampling_P`, `sampling_E`, `sampling_density` because it makes less sense for arrays.

**Comment by czgdp1807** [comment] 2020-04-04 08:24
In my understanding,

1. `size` - It is the size of the sample/array
2. `numsamples` - It is the number of samples upto which the iteration is to be done.

The problem I notices with sample is that the iterator is generated every time we call `sample`, so `count` never crosses, `numsamples` and basically whatever you keep it's value iteration will never be stopped,
```python
>>> sample(X, size=3, numsamples=1)
[-1.66303574818487, -1.66303574818487, -1.66303574818487]
>>> sample(X, size=3, numsamples=1)
[0.365343738337888, 0.365343738337888, 0.365343738337888]
>>> sample(X, size=3, numsamples=2)
[2.46234636558061, 2.46234636558061, 2.46234636558061]
>>> sample(X, size=3, numsamples=2)
[0.744598563038099, 0.744598563038099, 0.744598563038099]
>>> sample(X, size=3, numsamples=2)
[0.860473316355101, 0.860473316355101, 0.860473316355101]
```

IMHO, this should be fixed. 



> >>> sample(X+Y, size=3)  # fails : expected 3
> 8.01476115427784

May be a problem with `IndependentProductPSpace.sample`.



> >>> sample(X, numsamples=3)  # fails : expected 3
> -0.132248747800019
> 
> >>> sample(X+Y, numsamples=3)  # fails : expected 3
> 3.62703730515697

It's fine, `size=()`, so a single value is returned which is what I'd expect. 

> >>> list(sample_iter(X, size=3, numsamples=2))  # unexpected output(neither 2 nor 3)
> [[0.310554545718285, 0.310554545718285, 0.310554545718285], [1.27257976990205, 1.27257976990205, 1.27257976990205]]

The output is correct, two samples each of size 3.

The following doesn't work,
```python
>>> itr = sample_iter(X, size=3)
>>> next(itr)
[3.45248656070201, 3.45248656070201, 3.45248656070201]
>>> itr = sample_iter(X*X + 3, size=3)
>>> next(itr)
Traceback (most recent call last):
  File "/home/czgdp1807ssd/sympy_project/sympy/sympy/core/cache.py", line 95, in wrapper
    retval = cfunc(*args, **kwargs)
TypeError: unhashable type: 'list'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
  File "/home/czgdp1807ssd/sympy_project/sympy/sympy/stats/rv.py", line 1203, in sample_iter_subs
    yield expr.xreplace(d)
  File "/home/czgdp1807ssd/sympy_project/sympy/sympy/core/basic.py", line 1148, in xreplace
    value, _ = self._xreplace(rule)
  File "/home/czgdp1807ssd/sympy_project/sympy/sympy/core/basic.py", line 1163, in _xreplace
    a_xr = _xreplace(rule)
  File "/home/czgdp1807ssd/sympy_project/sympy/sympy/core/basic.py", line 1170, in _xreplace
    return self.func(*args), True
  File "/home/czgdp1807ssd/sympy_project/sympy/sympy/core/cache.py", line 97, in wrapper
    retval = func(*args, **kwargs)
  File "/home/czgdp1807ssd/sympy_project/sympy/sympy/core/power.py", line 275, in __new__
    b = _sympify(b)
  File "/home/czgdp1807ssd/sympy_project/sympy/sympy/core/sympify.py", line 440, in _sympify
    return sympify(a, strict=True)
  File "/home/czgdp1807ssd/sympy_project/sympy/sympy/core/sympify.py", line 362, in sympify
    raise SympifyError(a)
sympy.core.sympify.SympifyError: SympifyError: [-3.12260386276408, -3.12260386276408, -3.12260386276408]
```

It should have been.

Another thing that I'd want is sampling a matrix of values, i.e., `size=(3, 2)`. I tried and got the following,

```python
>>> itr = sample_iter(X*X + 3, size=(3, 2))
>>> next(itr)
Traceback (most recent call last):
  File "/usr/lib/python3.6/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
  File "/home/czgdp1807ssd/sympy_project/sympy/sympy/stats/rv.py", line 1194, in sample_iter_subs
    d = ps.sample(size)  # a dictionary that maps RVs to values
  File "/home/czgdp1807ssd/sympy_project/sympy/sympy/stats/crv.py", line 513, in sample
    return {self.value: self.distribution.sample(size)}
  File "/home/czgdp1807ssd/sympy_project/sympy/sympy/stats/crv_types.py", line 2742, in sample
    return [random.normalvariate(self.mean, self.std)]*size
TypeError: can't multiply sequence by non-int of type 'tuple'
```

**Comment by czgdp1807** [comment] 2020-04-04 08:32
In conclusion, `numsamples` and `size` both are required. The inconsistency is with `size`. The default should be `size=(1, )` and in that case single/scalar values should be returned as answers. It should be made more general, like if I do, `size=(1, 2, 3)` and use `numpy` as external library, then a `numpy` array should be returned with shape `(1, 2, 3)`. 
In addition, the iterator should stop when count exceeds `numsamples`. Though the user can use external loops to stop that but an internal loop is also present so makes things confusing. One way can be is to cache the output of `sample_iter`, so that the same iterator is returned in the next call(with same arguments). Not sure if caching will work but can be tried out.

**Comment by oscarbenjamin** [comment] 2020-04-04 09:49
> Not sure if caching will work but can be tried out.

That sounds fragile, not thread-safe etc. I don't know this issue in detail but I recommend against that approach.

**Comment by Smit-create** [comment] 2020-04-05 13:45
> In addition, the iterator should stop when count exceeds` numsamples`.

What if we return a list itself.
Also, I understood as `size` of samples per `numsamples` and hence, both are required. So, `numsamples` also needs to be added as an argument in `sample` instead of keeping it default as 1 .

**Comment by czgdp1807** [comment] 2020-04-06 08:35
Actually a new iterator is created whenever `sample` is called which is just wastage of CPU cycles. Following are the options,

1. Make iterator a state which is not possible since, sample is a function.
2. Returning an iterator, which can be operated open by `list()`, `next()` or whatever is the need.
3. Asking for the return type from the user. This option may lead to dirty API.
4. Returning a list always. Unambiguous but not robust.

IMO, option 2 is the best among all.

**Comment by Smit-create** [comment] 2020-04-10 05:46
```python
>>> from sympy.stats import *
>>> X=Normal('X',1,2)
>>> next(sample(X))
[0.469738066019727]

>>> next(sample(X, size=3))
[1.03193769686300, 4.37068224926506, 2.25993735941436]

>>> Y=Normal('Y',3,4)
>>> next(sample(X+Y, size=3))
[1.85229046187869, 11.3073651698796, 2.46753484877966]

>>> list(sample(X+Y, numsamples=3))
[[-3.92733920820063], [1.91237869520523], [6.39355454594779]]

>>> list(sample(X+Y, numsamples=3, library='scipy'))
[array([2.26730872]), array([-4.65409755]), array([1.24456059])]

>>> list(sample(X, numsamples=3, library='scipy'))
[array([3.16727285]), array([-1.0967364]), array([-2.74534138])]

>>> next(sample(X, size=3, library='scipy'))
array([3.14564194, 0.78263862, 1.14410964])
```

On the current diff in #18754, it is able to produce the expected results for all the examples.

I have modified 1-2 failing tests as I had few doubts regarding handling arrays in sympy:
(i) `ImmutableDenseNDimArray` raises an error when substituted in any expression and then using `evalf` on it, So needed to  modify this    ` assert variance(X + Y, numsamples=10, evalf=False).has(ImmutableDenseNDimArray)`

(ii) Probably if this supports some operations as in numpy arrays, the error can be resolved
```python
>>> import numpy as np
>>> x = np.array([1, 2, 3])
>>> x*x + 3
array([ 4,  7, 12])
```
The error I am trying to highlight is:
```python
>>> def get_samples(size):
...         return ArrayComprehensionMap(lambda: random.random(), (x, 0, size-1)).doit()
...
>>> s = get_samples(3)
>>> s
[0.942902709884289, 0.815480451481191, 0.0901518267337930]
>>> s*s + 3     # fails, the same worked with numpy arrays
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/smit/Smit Lunagariya/sympy/sympy/tensor/array/ndim_array.py", line 399, in __mul__
    raise ValueError("scalar expected, use tensorproduct(...) for tensorial product")
ValueError: scalar expected, use tensorproduct(...) for tensorial product
>>> s + s      # works good
[1.88580541976858, 1.63096090296238, 0.180303653467586]
```


Also, above pointed failure can be interpreted from the following examples where it works with 'scipy' but not with 'python', addressing [#19061(comment)](https://github.com/sympy/sympy/issues/19061#issuecomment-608995060)
```python

>>> from sympy.stats import *
>>> X = Normal('X', 0, 1)
>>> expr = X*X + 3
>>> iter = sample_iter(expr, numsamples=3)
>>> list(iter)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/smit/Smit Lunagariya/sympy/sympy/stats/rv.py", line 1245, in sample_iter_subs
    yield expr.xreplace(d)
  File "/home/smit/Smit Lunagariya/sympy/sympy/core/basic.py", line 1148, in xreplace

    value, _ = self._xreplace(rule)
  File "/home/smit/Smit Lunagariya/sympy/sympy/core/basic.py", line 1163, in _xreplace
    a_xr = _xreplace(rule)
  File "/home/smit/Smit Lunagariya/sympy/sympy/core/basic.py", line 1170, in _xreplace
    return self.func(*args), True
  File "/home/smit/Smit Lunagariya/sympy/sympy/core/power.py", line 319, in __new__
    obj = b._eval_power(e)
AttributeError: 'ImmutableDenseNDimArray' object has no attribute '_eval_power'
>>> iter = sample_iter(expr, numsamples=3, library='scipy')
>>> list(iter)
[array([4.58476961]), array([3.18017387]), array([4.29700227])]
```

**Comment by Smit-create** [comment] 2020-04-10 09:01
I am not much familiar with the tensor module but, this diff(passes all `tensor` tests) fixes almost all the error except one.
I have just tried a rough implementation, not sure whether I have done something wrong
```diff
diff --git a/sympy/tensor/array/ndim_array.py b/sympy/tensor/array/ndim_array.py
index f3861a28e0..932ec5dc4c 100644
--- a/sympy/tensor/array/ndim_array.py
+++ b/sympy/tensor/array/ndim_array.py
@@ -9,6 +9,7 @@
 from sympy.core.sympify import sympify
 from sympy.core.compatibility import SYMPY_INTS, Iterable

+
 import itertools

 class NDimArray(object):
@@ -369,24 +370,31 @@ def f(sh, shape_left, i, j):
     def __add__(self, other):

         from sympy.tensor.array.arrayop import Flatten

-        if not isinstance(other, NDimArray):
-            raise TypeError(str(other))
+        if sympify(other).is_number:
+            result_list = [i+other for i in Flatten(self)]
+        else:
+            if not isinstance(other, NDimArray):
+                raise TypeError(str(other))

-        if self.shape != other.shape:
-            raise ValueError("array shape mismatch")

-        result_list = [i+j for i,j in zip(Flatten(self), Flatten(other))]
+            if self.shape != other.shape:
+                raise ValueError("array shape mismatch")
+            result_list = [i+j for i,j in zip(Flatten(self), Flatten(other))]

         return type(self)(result_list, self.shape)

     def __sub__(self, other):
         from sympy.tensor.array.arrayop import Flatten
-        if not isinstance(other, NDimArray):
-            raise TypeError(str(other))

+        if sympify(other).is_number:
+            result_list = [i-other for i in Flatten(self)]
+
+        else:
+            if not isinstance(other, NDimArray):
+                raise TypeError(str(other))

-        if self.shape != other.shape:
-            raise ValueError("array shape mismatch")
-        result_list = [i-j for i,j in zip(Flatten(self), Flatten(other))]
+            if self.shape != other.shape:
+                raise ValueError("array shape mismatch")

+            result_list = [i-j for i,j in zip(Flatten(self), Flatten(other))]

         return type(self)(result_list, self.shape)

@@ -396,6 +404,8 @@ def __mul__(self, other):
         from sympy.tensor.array.arrayop import Flatten

         if isinstance(other, (Iterable, NDimArray, MatrixBase)):
+            if self.shape == other.shape:
+                return arrayproduct(self, other)
             raise ValueError("scalar expected, use tensorproduct(...) for tensorial product")


         other = sympify(other)
@@ -563,6 +573,13 @@ def _check_index_for_getitem(self, index):

         return index

+    def __pow__(self, power):
+        power = sympify(power)
+        if not power.is_number:
+            raise ValueError("scalar expected")
+        from sympy.tensor.array.arrayop import Flatten
+        result_list = [i**power for i in Flatten(self)]
+        return type(self)(result_list, self.shape)


 class ImmutableNDimArray(NDimArray, Basic):
     _op_priority = 11.0
@@ -575,3 +592,14 @@ def as_immutable(self):

     def as_mutable(self):
         raise NotImplementedError("abstract method")
+
+def arrayproduct(array1, array2):

+    if not (isinstance(array1, NDimArray) and isinstance(array1, NDimArray)):
+        raise TypeError
+
+    if array1.shape != array2.shape:
+        raise ValueError("array shape mismatch")
+    from sympy.tensor.array import ImmutableDenseNDimArray
+    from sympy.tensor.array.arrayop import Flatten
+    result_list = [i*j for i,j in zip(Flatten(array1), Flatten(array2))]
+    return ImmutableDenseNDimArray(result_list, array1.shape)
```
This has the following results:
```python

>>> from sympy.tensor.array import ArrayComprehensionMap
>>> import random
>>> from sympy.abc import x
>>> def get_samples(size):
...     return ArrayComprehensionMap(lambda: random.random(), (x, 0, size-1)).doit()
...
>>> s=get_samples(3)
>>> s*s + 3
[3.57431137634768, 3.25765024031484, 3.11806307028034]
>>> s
[0.757833343386053, 0.507592592848674, 0.343603070824956]
>>> s**2
[0.574311376347683, 0.257650240314840, 0.118063070280340]
>>> s*s
[0.574311376347683, 0.257650240314840, 0.118063070280340]
>>> from sympy.stats import *
>>> X = Normal('X', 0, 1)
>>> expr = X*X + 3
>>> iter = sample_iter(expr, numsamples=3)
>>> list(iter) # https://github.com/sympy/sympy/issues/19061#issuecomment-608995060
[[3.64097349353394], [6.96478819718658], [4.63120568602483]]
```

**Comment by sylee957** [comment] 2020-04-10 09:43
Unfortunately, I don't think that we have decided to support anything about array broadcasting yet.
And if it is supported, we'd arrive in some other conjectures like how a two dimensional array added with a one dimensional vector should behave, etc.
Obviously, for matrices, allowing broadcasts is not mathematically valid.

**Comment by Smit-create** [comment] 2020-04-10 16:42
> I don't think that we have decided to support anything about array broadcasting yet.

I fear, that I would lead to many errors during the `'python'` as a library without broadcasting, though this works all good with other libraries

**Comment by czgdp1807** [comment] 2020-05-06 18:24
> I fear, that it would lead to many errors during the `'python'` as a library without broadcasting

I suggest focusing on solutions for `python` after merging of your ongoing PR.

**Closed** 2020-05-28 05:31 UTC
Labels: GSoC, stats

**Comment by oscarbenjamin** [comment] 2021-03-25 10:38
This issue is pointed to by deprecation warnings that show up in CI:
```
/home/runner/work/sympy/sympy/sympy/stats/rv.py:1110: UserWarning: 
The return type of sample has been changed to return an iterator
object since version 1.7. For more information see
https://github.com/sympy/sympy/issues/19061
  warnings.warn(filldedent(message))
```
Warnings should not be emitted unless a user is using the API incorrectly or should change their code.

Tests that give warning should suppress them with either the `warns` or `ignore_warnings` context managers.

**Comment by analyzethem** [comment] 2021-06-01 13:36
Came here as I just tried to use `sympy.stats.sample()`, being surprised that it no longer worked as previously (replacing production APIs to suddenly change return behaviour _really_ should not be done unless it absolutely must, as it will break existing code), and getting the above warning that "UserWarning:  The return type of sample has been changed to return an iterator", with a link to this github issue.

I thought I'd add that the from a user standpoint, the new behavior is really confusing and makes little sense.

- Names matter, and from a naming point of view, when you call a function 'sample()', you expect that function to provide a sample - not an iterator that will generate a sample.
- The iterator aspect seems to add no value, because (unless you ask it to generate a certain number of values) it only generates a single value. Which if that is what you intend, why not just return that value right away. You do not get to "reuse" the iterator anyways. The below code fails on the last line with a StopIteration exception.

```
import sympy.stats as st
X = st.Normal('X', 100, 20)
s = st.sample(X)
print(next(s))
print(next(s))
```

There is already `sympy.stats.sample_iter()` which does the same, except it you can run `next()` on it more than once.

I am struggling a bit with what problem the new behaviour is supposed to fix. It breaks existing code, in order to replace it with something which appears to be broken. I guess I am missing something here, but from a user point of view, this change was a big "what on earth is going on here". It makes a lot more sense to have one function to request one or a number of samples (as `sample()` does already), and one for making a reusable iterator (which `sample_iter()` does though it could perhaps have been named `sampler()` as a more human friendly name).

That it being said, I love Sympy, I am happy that people are spending their free time making this stuff, and I am perfectly happy with accepting the current limitations, whether there is a good reason for them or not.

**Comment by czgdp1807** [comment] 2021-06-01 15:07
@analyzethem I totally understand your problem. Actually, iterator is the most generic thing and can be casted to any object. So for example in your case,

```python
>>> import sympy.stats as st
>>> X = st.Normal('X', 100, 20)
>>> s = st.sample(X)
/home/czgdp1807ssd/sympy_project/sympy/sympy/stats/rv.py:1110: UserWarning: 
The return type of sample has been changed to return an iterator
object since version 1.7. For more information see
https://github.com/sympy/sympy/issues/19061
  warnings.warn(filldedent(message))
>>> list(s)
[83.39889137831969]
```

It was done to introduce consistency (that always an iterator would be returned, and the user can convert to it an object of their choice if possible).

**Comment by oscarbenjamin** [comment] 2021-06-01 15:17
I also don't see why sample was change to return an iterator. The previous behaviour might have been inconsistent but the new behaviour doesn't seem useful and there doesn't seem to be anyway to write code that works unchanged with both old and new versions of sympy except perhaps by using `sample_iter` instead. For anyone wanting to workaround this change the following works with both old and new sympy versions:
```python
from sympy.stats import sample_iter
from itertools import islice

def my_sample(X, condition=None, size=None):
    samples = sample_iter(X, condition)
    if size is None:
        return next(samples)
    else:
        return list(islice(samples, size))
```

I also think that we should not issue a warning *after* a backwards incompatible change. That doesn't make any sense. Warnings are used *before* the change so that someone can change their code before it breaks. Every line in the `sample` doctests has been commented out which shows what this has done for someone who actually wants to use `sample`. The warning will be there even if someone is using `sample` correctly.

In any case where do we go from here? The current `sample` API doesn't seem useful because:

1. It unconditionally emits a warning. There is no option that can be passed to suppress the warning.
2. Currently `sample` returns an iterator. Changing that to a list or other iterable would not be compatible for anyone who is now using `next(sample(...))`.
3. It is already incompatible across recent sympy versions.
4. The finite iterator returned by sample currently is only useful in very niche cases that would be better handled using `islice` and `sample_iter` anyway.

The big fat warning probably already discourages anyone from using `sample` in recent sympy versions so I wonder how problematic it would be just to change the return value again.

Otherwise a new API should be introduced that returns sensible values.

**Comment by czgdp1807** [comment] 2021-06-01 15:28
May be we can remove the warning and add some new APIs which would just require the user to rename or use `as` in imports.

**Comment by oscarbenjamin** [comment] 2021-06-01 15:59
Maybe a new `sample_list` function could be introduced.

The current behaviour of `sample` isn't useful though so maybe instead the warning could be changed to say that in future it will be changed again to match the behaviour of `sample_list`.

Given that compatibility is already broken I wonder if it might actually be best just to break it again and switch to something that is at least compatible with the old behaviour for basic cases. Then any script that has been working for a long time will work again in future although there will be some intermediate versions of sympy where it doesn't work.

Any downstream library that was using this will already have broken by the previous changes and should use the `my_sample` workaround above. I can't imagine any downstream library choosing to use the API since the changes because it gives out an annoying warning.

**Comment by czgdp1807** [comment] 2021-06-02 02:48
Sure. Opening a separate issue would be helpful in making this noticed by contributors. It seems like an easy to fix one. Since, if our previous users are facing problem then changes should be done to make life easier.

**Comment by oscarbenjamin** [comment] 2021-06-02 07:47
Yes, @analyzethem can you open a new issue (linking back to this one) and explain what the problem is there?

**Comment by analyzethem** [comment] 2021-06-02 07:49
> In any case where do we go from here? The current `sample` API doesn't seem useful because:
> 
>     1. It unconditionally emits a warning. There is no option that can be passed to suppress the warning.
> 
>     2. Currently `sample` returns an iterator. Changing that to a list or other iterable would not be compatible for anyone who is now using `next(sample(...))`.
> 
>     3. It is already incompatible across recent sympy versions.
> 
>     4. The finite iterator returned by sample currently is only useful in very niche cases that would be better handled using `islice` and `sample_iter` anyway.

There really is no elegant way to fix it ... my $0.10 would be if there are two bad options, then take the one which is better long term. My recommendation would be to have do something like ...

- Have `sample()` revert to previous behaviour in the next release, add an API change warning, and document this in the help text (as well as transitional info, for those wanting to use an iterator use `sample_iterator()` instead)
- Introduce a function that can be used to change global behaviour (also documented on top of `sample()` help text and the warning about changing APIs), so you could do e.g. `sympy.stats.future_sample(True)` on top of your code - and this would let you instantly "port" your code to the future & legacy behaviour
- Add a keyword for e.g. `sample(future=True)` so you could get old behaviour without changing things globally (and that keyword would have to carry on into the next release)

Code should be readable. When you have defined a stochastic variable X, then doing `next(sample(X))` is quite confusing; both because (a) why would I ask for the next one when I only ask for a single sample [as the name implies, and there ought to have been a `samples()` for requesting more than one, rather than overloading `sample()` to request more with a keyword], and (b) if I can ask for the next one, why can I then not get another afterwards. It's just not the pythonic way.

**Comment by analyzethem** [comment] 2021-06-02 09:30
> Yes, @analyzethem can you open a new issue (linking back to this one) and explain what the problem is there?

Makes sense @oscarbenjamin , I have opened new issue #21563
