### ISSUE TITLE
Integrate incorrect with Abs and trigonometric functions on negative real line

### ISSUE THREAD

**Issue by jakoblem** [sympy/sympy#25066] opened 2023-04-19 08:16 UTC
Abs(cos(x)) integrates to negative number -sin(1) on [-1,0], and Abs(sin(x)) integrates to zero on [-2*pi,0]
```
# %% Init
from sympy import *
init_printing()
x = symbols('x', real=True)
# %% Cosine is positive on [-1,0], but abs(cos(x)) integrates to negative number
int1w = integrate(Abs(cos(x)),(x,-1,0,))
int1c = integrate(cos(x),(x,-1,0,))
print(int1w, int1c)
print(int1w.evalf(), int1c.evalf())
# %% abs(sin(x)) is pi-periodic, but:
int2w = integrate(Abs(sin(x)),(x,-2*pi,0,))
int2c = integrate(Abs(sin(x)),(x,0,2*pi))
print(int2w, int2c)
# %%
import sys, sympy; print(sympy.__version__, sys.version)
```
2nd cell outputs: 
```
-sin(1) sin(1)
-0.841470984807897 0.841470984807897
```
while the 3rd cell outputs:
```
0 4 
```
Version: 1.11.1 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]

**Comment by oscarbenjamin** [comment] 2023-04-19 08:46
Thanks for reporting. This is a duplicate of gh-25052 though so I'm going to close it.

**Closed by oscarbenjamin** 2023-04-19 08:46 UTC
Labels: integrals, functions.elementary.piecewise

**Comment by jakoblem** [comment] 2023-04-19 11:25
Ahh, great. Is it related to [gh-24127](https://github.com/sympy/sympy/issues/24127)?

**Comment by oscarbenjamin** [comment] 2023-04-19 11:52
I don't think so because that issue is not about integrals.
