### ISSUE TITLE
`Equality` wrongly evaluated to False

### ISSUE THREAD

**Issue by AlbertHilb** [sympy/sympy#23639] opened 2022-06-17 21:43 UTC
The following equation

```python
x = symbols(x)
Eq(sqrt(x)/2, 1)
```
is incorrectly evaluated to False: it admits the solution $x = 4$. The problem persists if you replace the number $2$ with another number, whereas it disappears if you replace the division with multiplication.

I'm using sympy 1.10.1.

**Comment by oscarbenjamin** [comment] 2022-06-17 21:45
What exactly is the `x` in that code? It should be a string:
```python
In [1]: x = symbols('x')
   ...: Eq(sqrt(x)/2, 1)
Out[1]: 
√x    
── = 1
2   
```

**Comment by AlbertHilb** [comment] 2022-06-17 22:23
Sorry for the mistake. I meant

```python
x = symbols('x')
```

This is a shot of my notebook

![Screenshot_20220618_002130](https://user-images.githubusercontent.com/1220427/174408205-cee32e2f-c3af-41b6-b59e-8583d783899a.png)

**Comment by oscarbenjamin** [comment] 2022-06-17 22:33
This has already been fixed in master in a3277e4067edbd3178450a4c37824326ed01579e from #23289. Closing as a duplicate of #23287.

**Comment by oscarbenjamin** [comment] 2022-06-17 22:34
Thanks for reporting this. It will be fixed in the next release.

**Closed by oscarbenjamin** 2022-06-17 22:33 UTC

**Comment by AlbertHilb** [comment] 2022-06-17 22:37
Thanks!!!
