### ISSUE TITLE
E**x + 2**-x + 2*cos(x) -6 @ 1.5 doesn't simplify

### ISSUE THREAD

**Issue by Kellel** [sympy/sympy#8838] opened 2015-01-16 22:09 UTC
The following code: 

    expr = E**x + 2**-x + 2*cos(x) -6
    expr.subs(x, 1.5)
   
Gives:

    -1.37683652632653 + 2**(-1.5) 

Instead of evaluating to ~ -1.02328.

Am I doing something wrong?

**Comment by aktech** [comment] 2015-01-17 06:35
You need to use evalf() to evaluate `2**(-1.5)`
```python
In [29]: expr = E**x + 2**-x + 2*cos(x) -6

In [30]: expr.subs(x, 1.5)
Out[30]: -1.37683652632653 + 2**(-1.5)

In [31]: expr.subs(x, 1.5).evalf()
Out[31]: -1.02328313573326
```

**Comment by darshanime** [comment] 2015-01-17 06:49
Or you could also use the `N()` function. 

Like this ::
```python
expr = E**x + 2**-x + 2*cos(x) -6
N(expr.subs(x, 1.5))
```
Read more about numerical evaluation [here](http://docs.sympy.org/dev/modules/evalf.html)

**Comment by pelegm** [comment] 2015-01-17 07:46
Either way, this is not a bug, so you can close this one. If you wish, you may continue the discussion on gitter.

**Closed** 2015-01-17 08:46 UTC
