### ISSUE TITLE
pi*cos(n), pi is not extracted

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#19850] opened 2020-07-27 19:02 UTC
Neither `as_coeff_mul`, nor `as_coeff_Mul` can extract `pi`.

**Comment by Raghibshams456** [comment] 2020-07-28 15:18
hey @proy87 can u explain..please..

**Comment by proy87** [comment] 2020-07-28 18:54
`pi*cos(n).as_coeff_mul()` return `(1, (pi*cos(n),))`, not `(pi, (cos(n),))`

**Comment by oscarbenjamin** [comment] 2020-07-30 22:10
Both methods are intended to extract Rational coefficients only by default. You can inform `as_coeff_mul` that e.g. anything not containing `n` should be considered part of the coefficient:
```
In [8]: (pi*cos(n)).as_coeff_mul(n)                                                                                               
Out[8]: (π, (cos(n),))
```

**Comment by oscarbenjamin** [comment] 2020-07-31 23:22
I'm closing this since it is by design.

**Closed by oscarbenjamin** 2020-07-31 23:22 UTC
