### ISSUE TITLE
Series/limit fails unless expression is simplified first.

### ISSUE THREAD

**Issue by mforbes** [sympy/sympy#9173] opened 2015-03-20 03:23 UTC
Consider the following:

``` python
>>> var('p_0 p_1 p_2 p_3 b_0 b_1 b_2');
>>> Q = (p_0 + (p_1 + (p_2 + p_3/y)/y)/y)/(1 + ((p_3/(b_0*y) + (b_0*p_2 - b_1*p_3)/b_0**2)/y + (b_0**2*p_1 - b_0*b_1*p_2 - p_3*(b_0*b_2 - b_1**2))/b_0**3)/y)
>>> Q.series(y, n=3)
y**2*(-b_0*p_2**2/p_3**2 + 2*b_1*p_2/p_3 + b_2 - b_1**2/b_0) + b_1*y + b_0 + O(y**3)
>>> Q.simplify().series(y, n=3)
b_2*y**2 + b_1*y + b_0 + O(y**3)
```

The `y**2` coefficient should be `b_2`, but is computed to be something else unless the expression is simplified first.  The issues seems to be with `limit`, and so might be related to #9075:

``` python
>>> Q.diff(y, y).limit(y, 0).simplify()
-72*b_0*p_2**2/p_3**2 + 144*b_1*p_2/p_3 + 2*b_2 - 72*b_1**2/b_0
>>> expr.diff(y, y).simplify().limit(y, 0)
2*b_2
```

**Comment by mforbes** [comment] 2015-11-20 07:23
Any update on why this might be happening?  It still seems to be an issue.

**Comment by jksuom** [comment] 2015-11-20 19:21
It seems that there is a bug in the computation of the series expansion of ``1/f`` when the order of ``f`` is negative (and that of ``1/f`` is positive).
```
>>> f = 1/x**2 - 1/x
>>> (1/f).series(x, n=6)
x**2 + x**3 + x**4 + O(x**6)
>>> (1/f).series(x, n=7)
x**2 + x**3 + x**4 + x**5 + O(x**7)
>>> (1/f).series(x, n=8)
x**2 + x**3 + x**4 + x**5 + O(x**8)
```
It is caused by an incorrect loop count in ``Pow._eval_nseries`` (on [this line](https://github.com/sympy/sympy/blob/master/sympy/core/power.py#L1179)).

**Comment by mohitacecode** [comment] 2020-02-20 06:34
I think this issue is resolved in the current master.
IMO it can be closed.

```
>>> var('p_0 p_1 p_2 p_3 b_0 b_1 b_2')
(p_0, p_1, p_2, p_3, b_0, b_1, b_2)
>>> Q = (p_0 + (p_1 + (p_2 + p_3/y)/y)/y)/(1 + ((p_3/(b_0*y) + (b_0*p_2 - b_1*p_3)/b_0**2)/y + (b_0**2*p_1 - b_0*b_1*p_2 - p_3*(b_0*b_2 - b_1**2))/b_0**3)/y)
>>> Q.series(y, n=3)
b_2*y**2 + b_1*y + b_0 + O(y**3)
>>> Q.simplify().series(y, n=3)
b_2*y**2 + b_1*y + b_0 + O(y**3)
>>> Q.diff(y, y).limit(y, 0).simplify()
2*b_2
>>> 
```

**Comment by sachin-4099** [comment] 2020-06-01 15:40
I can confirm @mohitacecode 's results. This only needs a test.

**Comment by Shardul555** [comment] 2020-12-25 17:05
@sachin-4099 can you please guide me where I need to add this testcase.

**Comment by Shardul555** [comment] 2020-12-29 09:41
I run the code for this expression in the terminal having installed sympy version 1.7.1 but here the coefficients of y**2 and y are not simplified to final answer.
``
>>> from sympy import *
>>> from sympy.abc import y
>>> var('p_0 p_1 p_2 p_3 b_0 b_1 b_2')
(p_0, p_1, p_2, p_3, b_0, b_1, b_2)
>>> Q = (p_0 + (p_1 + (p_2 + p_3/y)/y)/y)/(1 + ((p_3/(b_0*y) + (b_0*p_2 - b_1*p_3)/b_0**2)/y + (b_0**2*p_1 - b_0*b_1*p_2 - p_3*(b_0*b_2 - b_1**2))/b_0**3)/y)
>>> Q.series(y, n=3)
y*(b_0*p_2/p_3 + b_0*(-p_2/p_3 + b_1/b_0)) + y**2*(b_0*p_1/p_3 + b_0*p_2*(-p_2/p_3 + b_1/b_0)/p_3 + b_0*(-p_1/p_3 + (p_2/p_3 - b_1/b_0)**2 + b_1*p_2/(b_0*p_3) + b_2/b_0 - b_1**2/b_0**2)) + b_0 + O(y**3)
>>> simplify(y**2*(b_0*p_1/p_3 + b_0*p_2*(-p_2/p_3 + b_1/b_0)/p_3 + b_0*(-p_1/p_3 + (p_2/p_3 - b_1/b_0)**2 + b_1*p_2/(b_0*p_3) + b_2/b_0 - b_1**2/b_0**2)))
b_2*y**2
>>> simplify(y*(b_0*p_2/p_3 + b_0*(-p_2/p_3 + b_1/b_0)))
b_1*y

**Comment by Shardul555** [comment] 2020-12-29 10:08
I run the code for this expression in the terminal having installed sympy version 1.7.1 but here the coefficients of y**2 and y are not simplified to final answer. Anyone guide me regarding this issue.
`
>>> from sympy import *
>>> from sympy.abc import y
>>> var('p_0 p_1 p_2 p_3 b_0 b_1 b_2')
(p_0, p_1, p_2, p_3, b_0, b_1, b_2)
>>> Q = (p_0 + (p_1 + (p_2 + p_3/y)/y)/y)/(1 + ((p_3/(b_0*y) + (b_0*p_2 - b_1*p_3)/b_0**2)/y + (b_0**2*p_1 - b_0*b_1*p_2 - p_3*(b_0*b_2 - b_1**2))/b_0**3)/y)
>>> Q.series(y, n=3)
y*(b_0*p_2/p_3 + b_0*(-p_2/p_3 + b_1/b_0)) + y**2*(b_0*p_1/p_3 + b_0*p_2*(-p_2/p_3 + b_1/b_0)/p_3 + b_0*(-p_1/p_3 + (p_2/p_3 - b_1/b_0)**2 + b_1*p_2/(b_0*p_3) + b_2/b_0 - b_1**2/b_0**2)) + b_0 + O(y**3)
>>> simplify(y*(b_0*p_2/p_3 + b_0*(-p_2/p_3 + b_1/b_0)))
b_1*y
>>> simplify(y**2*(b_0*p_1/p_3 + b_0*p_2*(-p_2/p_3 + b_1/b_0)/p_3 + b_0*(-p_1/p_3 + (p_2/p_3 - b_1/b_0)**2 + b_1*p_2/(b_0*p_3) + b_2/b_0 - b_1**2/b_0**2)))
b_2*y**2
`

**Closed** 2021-02-16 16:22 UTC
Labels: Easy to Fix, series

**Comment by anutosh491** [comment] 2022-06-27 13:55
I came across this issue while trying to address something similar and I realize this now ends up giving an even more complicated result than before and even if we simplify first .... we don't get the correct result which is a worse condition than what we had before !

```
>>> Q = (p_0 + (p_1 + (p_2 + p_3/y)/y)/y)/(1 + ((p_3/(b_0*y) + (b_0*p_2 - b_1*p_3)/b_0**2)/y + (b_0**2*p_1 - b_0*b_1*p_2 - p_3*(b_0*b_2 - b_1**2))/b_0**3)/y)
>>> Q.series(y, n=3)
y*(b_0*p_2/p_3 + b_0*(-p_2/p_3 + b_1/b_0)) + y**2*(b_0*p_1/p_3 + b_0*p_2*(-p_2/p_3 + b_1/b_0)/p_3 + b_0*(-p_1/p_3 + (p_2/p_3 - b_1/b_0)**2 + b_1*p_2/(b_0*p_3) + (b_0*b_2 - b_1**2)/b_0**2)) + b_0 + O(y**3)
>>>
>>> Q.simplify().series(y, n=3)
y*(b_0*p_2/p_3 + b_0*(-p_2/p_3 + b_1/b_0)) + y**2*(b_0*p_1/p_3 + b_0*p_2*(-p_2/p_3 + b_1/b_0)/p_3 + b_0*(-p_1/p_3 + (p_2/p_3 - b_1/b_0)**2 + b_1*p_2/(b_0*p_3) + (b_0*b_2 - b_1**2)/b_0**2)) + b_0 + O(y**3)
>>>
>>> # Expected - b_2*y**2 + b_1*y + b_0 + O(y**3)
>>> 
>>> # Previously gave - y**2*(-b_0*p_2**2/p_3**2 + 2*b_1*p_2/p_3 + b_2 - b_1**2/b_0) + b_1*y + b_0 + O(y**3)
```
I guess this was closed without adding a test hence we haven't come across this before, hence I guess we should reopen this now . Feel free to correct me if I'm missing something here !

**Comment by arhaque09** [comment] 2024-02-04 05:01
I would like to work on this issue! Let me know if its available.

**Comment by arhaque09** [comment] 2024-02-05 20:55
Hi! I am working on adding tests right now!

**Comment by Qaaee123** [comment] 2024-04-23 02:27
Hello, I saw this issue and I checked some of the other linked threads. In particular, I saw that in #20724 the issue was closed because it was solved elsewhere, but when testing locally on versions 1.8+, the issue still persisted. Locally, I edited expr.py to include the same proposed change as #20724, and it seemed to solve the issue. However, it has started to fail testcases and I am unsure about how to proceed. I would greatly appreciate any guidance.

**Comment by Qaaee123** [comment] 2024-04-25 04:37
Hello, I managed to fix this bug by incorporating ratsimp and it passes all of the test_expr test cases. However, when tested with tan(x).series(x, 2, 6, "+"), the output is incorrect. Any guidance would be greatly appreciated. 
````
>>> tan(x).series(x, 2, 6, "+")
-2 + tan(2) + (x - 2)*tan(2)**2 + (x - 2)**2*tan(2) + (x - 2)**2*tan(2)**3 + (x - 2)**3*tan(2)**4 + 4*(x - 2)**3*tan(2)**2/3 + (x - 2)**3/3 + 2*(x - 2)**4*tan(2)/3 + 5*(x - 2)**4*tan(2)**3/3 + (x - 2)**4*tan(2)**5 + (x - 2)**5*tan(2)**6 + 2*(x - 2)**5*tan(2)**4 + 17*(x - 2)**5*tan(2)**2/15 + 2*(x - 2)**5/15 + x + O((x - 2)**6, (x, 2))
>>> # correct output
tan(2) + (1 + tan(2)**2)*(x - 2) + (x - 2)**2*(tan(2)**3 + tan(2)) + (x - 2)**3*(1/3 + 4*tan(2)**2/3 + tan(2)**4) + (x - 2)**4*(tan(2)**5 + 5*tan(2)**3/3 + 2*tan(2)/3) + (x - 2)**5*(2/15 + 17*tan(2)**2/15 + 2*tan(2)**4 + tan(2)**6) + O((x - 2)**6, (x, 2))
````

**Comment by oscarbenjamin** [comment] 2024-04-26 11:19
I'm not sure that there is an issue here. The example comes out more complicated than it needs to but it is correct. If we want to canonicalise the outputs then we should really use ringseries.

**Comment by oscarbenjamin** [comment] 2024-04-26 11:21
I think best thing is just to add some test cases since they were not added before.
