### ISSUE TITLE
isprime can be faster

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#6908] opened 2013-05-08 09:55 UTC
```
See http://www.johndcook.com/blog/2013/01/17/narcissus-prime-in-python/ . The code isprime(int("1808010808"*1560 + "1")) should return within a couple of minutes.
```

Original issue for #6908: http://code.google.com/p/sympy/issues/detail?id=3809
Original author: https://code.google.com/u/asmeurer@gmail.com/

**Comment by Amitjha1412** [comment] 2015-01-11 16:45
Is anybody still working on this bug?

**Comment by skirpichev** [comment] 2015-01-11 17:14
#2209 is still open

**Comment by asmeurer** [comment] 2015-01-11 18:09
But I think it's abandoned. It you want to pick up the work there feel free.

**Comment by danaj** [comment] 2015-01-11 23:46
@Amitjha1412, @skirpichev is correct that this should be fixed by 2209.  I will get that completed in early February.

**Comment by gschintgen** [comment] 2019-07-15 13:03
Could be closed? #2209 superseded by #10943, which has been merged.

**Comment by asmeurer** [comment] 2019-07-15 16:06
I just tested on master and the original `isprime(int("1808010808"*1560 + "1"))` took 28min 41s to finish on my laptop. I don't know how long it took before. Presumably we can get it faster than this still. 

We should also go through the discussion here and see if all the ideas that were discussed were either implemented or decided that they would not actually help the implementation. If someone wants to go through this and write out the list of things that were mentioned, that would be helpful.

**Comment by gschintgen** [comment] 2019-07-22 20:07
> 
> 
> I just tested on master and the original `isprime(int("1808010808"*1560 + "1"))` took 28min 41s to finish on my laptop. I don't know how long it took before. Presumably we can get it faster than this still.
> 
> We should also go through the discussion here and see if all the ideas that were discussed were either implemented or decided that they would not actually help the implementation. If someone wants to go through this and write out the list of things that were mentioned, that would be helpful.

Hi, I may have been a bit hasty in suggesting to close this issue, but only slightly so:
```
>>> start=time.time(); isprime(int("1808010808"*1560 + "1")); end=time.time(); print(end-start)
True
91.85459184646606
```
**but** that's with gmpy2 installed.
Anyway here's the requested summary of the discussion:
- deterministic tests (Agrawal-Kayal-Saxena and variants) have been proposed but in practice they're too slow;
- before the mentioned PR, Sympy used Miller-Rabin Strong Pseudoprime Test;
- a twice as fast pure-python implementation is mentioned https://github.com/sympy/sympy/issues/6908#issuecomment-37008197 but that apparently only uses 20 MR bases whereas Sympy uses 46 https://github.com/sympy/sympy/issues/6908#issuecomment-37008205, so closing the issue is suggested https://github.com/sympy/sympy/issues/6908#issuecomment-37008207;
- according to a detailed writeup by @danaj  https://github.com/sympy/sympy/issues/6908#issuecomment-37008213, BSPW (Baillie-Pomerance-Selfridge-Wagstaff) is state-of-the-art and incidentally it's implemented in gmpy2, but not taken advantage of by SymPy
- complete rewrite by @danaj https://github.com/sympy/sympy/issues/6908#issuecomment-37008217 PR #2209 and later revived, fixed up and merged by @smichr in #10943. Automatically uses gmpy2's BSPW if gmpy2 is available.

So SymPy's pure-python isprime seems to have come down from hours to half an hour (not confirmed personally, may have been on very different hardware), while with gmpy2 installed it's at most a couple of minutes.

IMHO there's only a tiny missing piece: the current `isprime` docstring mentions BSPW, but omits to clarify that this requires gmpy2.

**Comment by asmeurer** [comment] 2019-07-22 21:03
Is BSPW something we can implement in pure Python for when we don't have gmpy2 to speed up that case?

**Comment by gschintgen** [comment] 2019-07-22 21:16
> 
> 
> Is BSPW something we can implement in pure Python for when we don't have gmpy2 to speed up that case?

Hmm, it may well be that the new `isprime` actually implements BSPW as well! Might have missed that.

**Comment by gschintgen** [comment] 2019-07-22 21:24
> 
> 
> Is BSPW something we can implement in pure Python for when we don't have gmpy2 to speed up that case?

Yep, is already implemented:
https://github.com/sympy/sympy/blob/56dceb1974848d97636f2f41c0893c738380e2e2/sympy/ntheory/primetest.py#L628-L641

**Closed** 2019-12-29 21:18 UTC
Labels: Bug, Could Close, Valid, combinatorics, imported, ntheory
