### ISSUE TITLE
support for \[x =  \pm 1\]

### ISSUE THREAD

**Issue by max-yue** [sympy/sympy#12868] opened 2017-07-02 09:25 UTC
I have a latex \[x =  \pm 1\], that means x could be +1 or -1, but I could not find the class MathOr， instead I only find the logic Or class, could you please add support for that?

**Comment by oscargus** [comment] 2019-02-13 19:19
The problem is that while convenient to use it for printing, there is no actual mathematical function that works like that. So the only purpose is really just for printing. It should be possible to just subclass this similar to Approx as in #12875 . Where Approx really has the same problem. It is only useful for printing (at least until some sort of automatic approximation methods are introduced).

**Comment by asmeurer** [comment] 2019-02-13 23:45
Duplicate of #5305

Also I now feel that this most likely not a good idea.

**Closed by asmeurer** 2019-02-13 23:45 UTC
Labels: printing.latex
