### ISSUE TITLE
print fails with MatMul and Expectation.

### ISSUE THREAD

**Issue by JRF-2018** [sympy/sympy#24132] opened 2022-10-11 21:57 UTC
The following code worked in 1.10.1 but not in 1.11.1.

```python
from sympy import *
from sympy.stats import Expectation
from sympy.stats.rv import RandomSymbol

print(RandomSymbol("ve") * Identity(2)) # works
z = Expectation(RandomSymbol("ve")) * Identity(2) # works
print(z) # NotImplementedError

```

I have tracked down this error to the cause that
MatMul.could_extract_minus_sign exists in 1.10.1 but not in 1.11.1 by
the commit below. I don't know previous bugs of the commit.

https://github.com/sympy/sympy/commit/1d3c89501c65e4b6cd3b635be60ba1d2bf003b4d

**Comment by asmeurer** [comment] 2022-10-11 22:36
I can confirm this is still an issue in master. Here's the full traceback:

```
>>> print(z)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/./sympy/core/_print_helpers.py", line 29, in __str__
    return sstr(self, order=None)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/./sympy/printing/printer.py", line 372, in __call__
    return self.__wrapped__(*args, **kwargs)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/./sympy/printing/str.py", line 1000, in sstr
    s = p.doprint(expr)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/./sympy/printing/printer.py", line 292, in doprint
    return self._str(self._print(expr))
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/./sympy/printing/printer.py", line 331, in _print
    return printmethod(expr, **kwargs)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/./sympy/printing/str.py", line 395, in _print_MatMul
    [self.parenthesize(arg, precedence(expr)) for arg in expr.args]
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/./sympy/printing/str.py", line 395, in <listcomp>
    [self.parenthesize(arg, precedence(expr)) for arg in expr.args]
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/./sympy/printing/precedence.py", line 132, in precedence
    return PRECEDENCE_FUNCTIONS[n](item)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/./sympy/printing/precedence.py", line 62, in precedence_Mul
    if item.could_extract_minus_sign():
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/./sympy/core/mul.py", line 177, in could_extract_minus_sign
    if self == (-self):
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/./sympy/matrices/expressions/matexpr.py", line 99, in __neg__
    return MatMul(S.NegativeOne, self).doit()
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/./sympy/matrices/expressions/matmul.py", line 202, in doit
    expr = canonicalize(MatMul(*args))
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/./sympy/strategies/core.py", line 10, in exhaustive_rl
    new, old = rule(new), new
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/./sympy/strategies/core.py", line 92, in switch_rl
    return rl(expr)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/./sympy/strategies/core.py", line 82, in do_one_rl
    result = rl(expr)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/./sympy/matrices/expressions/matmul.py", line 321, in remove_ids
    factor, mmul = mul.as_coeff_mmul()
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/./sympy/matrices/expressions/matmul.py", line 139, in as_coeff_mmul
    coeff, matrices = self.as_coeff_matrices()
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/./sympy/matrices/expressions/matmul.py", line 134, in as_coeff_matrices
    raise NotImplementedError("noncommutative scalars in MatMul are not supported.")
NotImplementedError: noncommutative scalars in MatMul are not supported.
```

**Comment by asmeurer** [comment] 2022-10-11 22:46
The error actually comes from this:

```py
>>> -z
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/./sympy/matrices/expressions/matexpr.py", line 99, in __neg__
    return MatMul(S.NegativeOne, self).doit()
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/./sympy/matrices/expressions/matmul.py", line 202, in doit
    expr = canonicalize(MatMul(*args))
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/./sympy/strategies/core.py", line 10, in exhaustive_rl
    new, old = rule(new), new
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/./sympy/strategies/core.py", line 92, in switch_rl
    return rl(expr)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/./sympy/strategies/core.py", line 82, in do_one_rl
    result = rl(expr)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/./sympy/matrices/expressions/matmul.py", line 321, in remove_ids
    factor, mmul = mul.as_coeff_mmul()
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/./sympy/matrices/expressions/matmul.py", line 139, in as_coeff_mmul
    coeff, matrices = self.as_coeff_matrices()
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/./sympy/matrices/expressions/matmul.py", line 134, in as_coeff_matrices
    raise NotImplementedError("noncommutative scalars in MatMul are not supported.")
NotImplementedError: noncommutative scalars in MatMul are not supported.
```

I expect it's because of this

```py
>>> z.args[0]
Expectation(ve)
>>> print(z.args[0].is_commutative)
None
```

`is_commutative` should really never be `None`. Isn't `Expectation` a complex scalar? The fix for this should be as simple as setting `is_commutative = True` on `Expectation`.

`commutative` is a weird assumption. `None` really means the same thing as `False`. I also wonder if the default in `Expr` shouldn't be `is_commutative=True`. I really doubt most `Expr` subclasses intend to be noncommutative. Thoughts @oscarbenjamin?

**Comment by JRF-2018** [comment] 2022-10-12 05:16
Subs or Derivative has is_communitive but not is_Matrix. This sometimes causes TypeError with matrices. Assuming that is_commutative or is_Matrix are not implemented, I think that at least 'print' should be possible.

**Comment by oscarbenjamin** [comment] 2022-10-20 16:12
I think that `Expectation` should have a `_eval_is_commutative` method that recursively checks if its argument is commutative:
```diff
diff --git a/sympy/stats/symbolic_probability.py b/sympy/stats/symbolic_probability.py
index 64e2872..c29a122 100644
--- a/sympy/stats/symbolic_probability.py
+++ b/sympy/stats/symbolic_probability.py
@@ -216,6 +216,9 @@ def __new__(cls, expr, condition=None, **kwargs):
         obj._condition = condition
         return obj
 
+    def _eval_is_commutative(self):
+        return self.args[0].is_commutative
+
     def expand(self, **hints):
         expr = self.args[0]
         condition = self._condition
```

**Comment by newSid2024** [comment] 2023-01-13 12:39
Is the issue still persists ?

**Comment by chandra20500** [comment] 2023-02-10 18:14
Hi I want to solve this issue please assign it to me.

**Comment by Deep-Rai-08** [comment] 2023-03-15 07:48
hi I want to contribute, I am an absolute beginner. Can anyone please help me?

**Comment by oscarbenjamin** [comment] 2023-03-15 09:22
There already is a PR (gh-24540) for this. If you are interested in fixing an issue then look through the references to any existing PRs and check those PRs to see why they haven't been merged and if you can review or improve on them.

**Comment by harshkasat** [comment] 2023-11-28 10:31
I believe we simply need to set the 'is_commutative' parameter to 'True'. Why has this PR not yet been merged?

**Comment by oscarbenjamin** [comment] 2023-11-28 13:01
> Why has this PR not yet been merged?

See the comments in the PR. It needs tests for `is_commutative`.

**Closed** 2023-11-28 17:07 UTC
Labels: Easy to Fix, printing, matrices, stats, matrices.expressions
