### ISSUE TITLE
Limit changes from simplification of original expression

### ISSUE THREAD

**Issue by B-Lorentz** [sympy/sympy#19453] opened 2020-05-28 09:25 UTC
I have an ugly symbolic expression:
`E = -(-0.375*hbar**3*beta*g*exp(0.5*hbar*beta*omega)/(m**2*omega*(exp(hbar*beta*omega) - 1)) - 0.75*hbar**3*beta*g*exp(0.5*hbar*beta*omega)/(m**2*omega*(exp(hbar*beta*omega) - 1)**2) + 3*hbar**3*beta*g*exp(1.5*hbar*beta*omega)/(4*m**2*omega*(exp(hbar*beta*omega) - 1)**2) - 0.75*hbar**3*beta*g*(exp(hbar*beta*omega) + 1)*exp(0.5*hbar*beta*omega)/(m**2*omega*(exp(hbar*beta*omega) - 1)**3) + 3*hbar**3*beta*g*exp(1.5*hbar*beta*omega)/(2*m**2*omega*(exp(hbar*beta*omega) - 1)**3) + 9*hbar**3*beta*g*(exp(hbar*beta*omega) + 1)*exp(1.5*hbar*beta*omega)/(2*m**2*omega*(exp(hbar*beta*omega) - 1)**4) - 3*hbar**2*g*exp(0.5*hbar*beta*omega)/(4*m**2*omega**2*(exp(hbar*beta*omega) - 1)) - 3*hbar**2*g*exp(0.5*hbar*beta*omega)/(2*m**2*omega**2*(exp(hbar*beta*omega) - 1)**2) - 3*hbar**2*g*(exp(hbar*beta*omega) + 1)*exp(0.5*hbar*beta*omega)/(2*m**2*omega**2*(exp(hbar*beta*omega) - 1)**3) + 0.5*hbar*omega*exp(0.5*hbar*beta*omega)/(exp(hbar*beta*omega) - 1) - hbar*omega*exp(1.5*hbar*beta*omega)/(exp(hbar*beta*omega) - 1)**2)/(-3*hbar**2*beta*g*exp(0.5*hbar*beta*omega)/(4*m**2*omega**2*(exp(hbar*beta*omega) - 1)) - 3*hbar**2*beta*g*exp(0.5*hbar*beta*omega)/(2*m**2*omega**2*(exp(hbar*beta*omega) - 1)**2) - 3*hbar**2*beta*g*(exp(hbar*beta*omega) + 1)*exp(0.5*hbar*beta*omega)/(2*m**2*omega**2*(exp(hbar*beta*omega) - 1)**3) + exp(0.5*hbar*beta*omega)/(exp(hbar*beta*omega) - 1))
`
If I call:
>`limit(E.simplify()-0.5*hbar*w, beta, oo)`

The result is 0
But if I call 
>`limit(E-0.5*hbar*w, beta, oo)`

The result is claimed to be infinity.
I think the two expressions should be equivalent

**Comment by sachin-4099** [comment] 2020-05-29 05:37
Please provide a description of the variables used in the expression.

**Comment by B-Lorentz** [comment] 2020-05-29 12:12
This code (re)produces the issue for me:`from sympy import *
beta = Symbol("beta", real=True, positive=True)
h = Symbol("h", real=True, positive=True)
m = Symbol("m", real=True, positive=True)
w = Symbol("omega", real=True, positive=True)
g = Symbol("g", real=True, positive=True)
e = exp(1)
q = 3*h**2*beta*g*e**(0.5*h*beta*w)
p = m**2*w**2
s = e**(h*beta*w) -1
Z = -q/(4*p*s) - q/(2*p*s**2) - q*(e**(h*beta*w)+1)/(2*p*s**3) + e**(0.5*h*beta*w)/s
E = -diff(log(Z), beta)
limit(E-0.5*h*w, beta, oo), limit(E.simplify()-0.5*h*w, beta, oo)`

**Comment by sidhu1012** [comment] 2020-12-19 08:22
I think expression should be simplified first before evaluating limit, in the example given by @B-Lorentz , using `simplify` before evaluating decreased the run time. I'll give it a try.

**Comment by sidhu1012** [comment] 2020-12-20 08:39
How could `limit` of a function change on simplifying it?

**Comment by 0sidharth** [comment] 2021-02-15 04:46
I think the problem is with `simplify`, not `limit`.
```
In [3]: E_ = E.simplify()

In [4]: E == E_
Out[4]: False
```

**Comment by 0sidharth** [comment] 2021-06-23 07:37
The cause of this is a rounding error. In this block of code https://github.com/sympy/sympy/blob/b4777fdcef467b7132c055f8ac2c9a5059e6a145/sympy/core/mul.py#L1910-L1915 `sum(powers)` returns the sum of `(-0.333333333333333, 0.333333333333333)` as `-5.55111512312578e-17`.

An alternative to get the correct answer is to use exact SymPy numbers, i.e. `S.Half` instead of `0.5`.

```py
In [1]: beta = Symbol("beta", real=True, positive=True)
   ...: h = Symbol("h", real=True, positive=True)
   ...: m = Symbol("m", real=True, positive=True)
   ...: w = Symbol("omega", real=True, positive=True)
   ...: g = Symbol("g", real=True, positive=True)
   ...: 
   ...: e = exp(1)
   ...: q = 3*h**2*beta*g*e**(S.Half*h*beta*w)
   ...: p = m**2*w**2
   ...: s = e**(h*beta*w) - 1
   ...: Z = -q/(4*p*s) - q/(2*p*s**2) - q*(e**(h*beta*w)+1)/(2*p*s**3) + e**(S.Half*h*beta*w)/s
   ...: 
   ...: E = -diff(log(Z), beta)
   ...: limit(E - S.Half*h*w, beta, oo), limit(E.simplify() - S.Half*h*w, beta, oo)
Out[1]: (0, 0)
```

**Comment by 0sidharth** [comment] 2021-10-02 12:08
Marking as Could Close as explained above

**Comment by oscarbenjamin** [comment] 2021-10-02 12:44
I don't see why this should be closed.

**Comment by 0sidharth** [comment] 2021-10-02 12:58
Since the original example uses floating-point numbers like `0.5` instead of `S.Half`, there arises a rounding error.


Due to this rounding error by using floating-point numbers, in the block of `mul.py` that I mentioned above, (-0.33) and (0.33) do not add up to 0 (which is the value of `n`), but rather a small negative rounding error which leads the execution of the block with `power < n` condition.


This error is related to how floating-point numbers work, and how Python works (0.1 + 0.2 - 0.3 does not evaluate to 0 either), so it is not really possible to tackle it (unless we want to consider `|numbers|<10e-16` as rounding errors and hence 0), and I believe this is more of an issue with how Python works rather than SymPy. So unless the example uses exact numbers like `S.Half`, I don't think there is anything to be done.

**Comment by oscarbenjamin** [comment] 2021-10-02 13:00
There are things that can be done. A basic possibility is just to convert the float to rational but there might also be better ways to handle this that don't rely on the floating point calculation.

**Closed** 2021-10-04 14:28 UTC
Labels: series, limits
