### ISSUE TITLE
Control test fails with numpy 2.0

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#26728] opened 2024-06-21 16:03 UTC
CC @akshanshbhatt @faze-geek 

This is the second time I have asked to fix these tests (gh-23128).

This test fails with numpy 2.0:
```console
$ pytest sympy/physics/control/tests/test_control_plots.py::test_pole_zero
================================================================================================ test session starts =================================================================================================
platform darwin -- Python 3.12.2, pytest-8.1.1, pluggy-1.4.0
architecture: 64-bit
cache:        yes
ground types: flint (python-flint==0.6.0)

rootdir: /Users/enojb/work/dev/sympy
configfile: pyproject.toml
plugins: instafail-0.5.0, doctestplus-1.2.2.dev5+g5176f32, hypothesis-6.99.9, xdist-3.5.0, timeout-2.3.1, split-0.8.2
collected 1 item

sympy/physics/control/tests/test_control_plots.py F                                                                                                                                                            [100%]

====================================================================================================== FAILURES ======================================================================================================
___________________________________________________________________________________________________ test_pole_zero ___________________________________________________________________________________________________

    def test_pole_zero():
        if not numpy:
            skip("NumPy is required for this test")

        def pz_tester(sys, expected_value):
            z, p = pole_zero_numerical_data(sys)
            z_check = numpy.allclose(z, expected_value[0])
            p_check = numpy.allclose(p, expected_value[1])
            return p_check and z_check

        exp1 = [[], [-0.24999999999999994+1.3919410907075054j, -0.24999999999999994-1.3919410907075054j]]
        exp2 = [[0.0], [-0.25+0.3227486121839514j, -0.25-0.3227486121839514j]]
        exp3 = [[0.0], [-0.5000000000000004+0.8660254037844395j,
            -0.5000000000000004-0.8660254037844395j, 0.9999999999999998+0j]]
        exp4 = [[], [5.0, 0.0, 0.0, 0.0]]
        exp5 = [[-5.645751311064592, -0.5000000000000008, -0.3542486889354093],
            [-0.24999999999999986+1.3919410907075052j,
            -0.24999999999999986-1.3919410907075052j, -0.2499999999999998+0.32274861218395134j,
            -0.2499999999999998-0.32274861218395134j]]
        exp6 = [[], [-1.1641600331447917-3.545808351896439j,
              -0.8358399668552097+2.5458083518964383j]]

>       assert pz_tester(tf1, exp1)
E       assert False
E        +  where False = <function test_pole_zero.<locals>.pz_tester at 0x1148e6c00>(TransferFunction(1, p**2 + 0.5*p + 2, p), [[], [(-0.24999999999999994+1.3919410907075054j), (-0.24999999999999994-1.3919410907075054j)]])

sympy/physics/control/tests/test_control_plots.py:121: AssertionError
                                                                                                   DO *NOT* COMMIT!
============================================================================================== short test summary info ===============================================================================================
FAILED sympy/physics/control/tests/test_control_plots.py::test_pole_zero - assert False
================================================================================================= 1 failed in 0.29s ==================================================================================================
```

**Comment by akshanshbhatt** [comment] 2024-06-23 07:27
I'm not able to reproduce this locally. Tests seem to pass with `numpy==2.0.0`.

```
$ pytest sympy/physics/control/tests/test_control_plots.py::test_pole_zero
======================== test session starts ========================
platform darwin -- Python 3.12.4, pytest-8.2.2, pluggy-1.5.0
architecture: 64-bit
cache:        yes
ground types: python

rootdir: /Users/akshansh/Documents/GitHub/sympy
configfile: pyproject.toml
plugins: doctestplus-1.2.1, hypothesis-6.103.2, timeout-2.3.1, split-0.8.2, xdist-3.6.1
collected 1 item

sympy/physics/control/tests/test_control_plots.py .           [100%]

========================= 1 passed in 0.16s =========================
```

**Comment by oscarbenjamin** [comment] 2024-06-23 11:13
> I'm not able to reproduce this locally. Tests seem to pass with `numpy==2.0.0`.

I can reproduce this only on MacOS. On Linux it passes.

**Comment by oscarbenjamin** [comment] 2024-06-23 11:15
On MacOS what is returned is:
```
(Pdb) p pole_zero_numerical_data(tf1)
(array([], dtype=float64), array([-0.25-1.39194109j, -0.25+1.39194109j]))
```
The test expects
```
        exp1 = [[], [-0.24999999999999994+1.3919410907075054j, -0.24999999999999994-1.3919410907075054j]]
```
The difference is the ordering of the roots.

**Comment by oscarbenjamin** [comment] 2024-06-23 11:24
The underlying call is to np.roots:
```python
In [1]: np.roots([1. +0.j, 0.5+0.j, 2. +0.j]) # numpy 1.26.4 on MacOS
Out[1]: array([-0.25+1.39194109j, -0.25-1.39194109j])
```
```python
In [1]: np.roots([1. +0.j, 0.5+0.j, 2. +0.j]) # numpy 2.0.0 on MacOS
Out[1]: array([-0.25-1.39194109j, -0.25+1.39194109j])
```
The documentation for np.roots does not say anything about the ordering of the returned roots. It says that they come from computing the eigenvalues of the companion matrix. The eigvals function does say that the roots are not necessarily ordered.

The docs do say:
```
    .. note::
       This forms part of the old polynomial API. Since version 1.4, the
       new polynomial API defined in `numpy.polynomial` is preferred.
       A summary of the differences can be found in the
       :doc:`transition guide </reference/routines.polynomials>`.
```
Really though we should be using sympy routines to find the roots because np.roots can be inaccurate for some roots.

**Comment by oscarbenjamin** [comment] 2024-06-23 11:58
This is the guaranteed accurate way to find numerical approximations of the roots for any polynomial with rational or float coefficients using SymPy's routines:
```python
In [20]: p = x**2 + x/2 + 2

In [21]: [r.evalf() for r in all_roots(p)]
Out[21]: [-0.25 - 1.39194109070751⋅ⅈ, -0.25 + 1.39194109070751⋅ⅈ]
```
This method uses exact arithmetic to isolate the roots, to distinguish real and non-real roots, and to identify complex conjugate pairs. The roots are returned by `all_roots` in a guaranteed order that is real roots followed by non-real roots in pairs ordered first by real parts and then by the magnitudes of the imaginary parts:
```python
In [22]: all_roots((x-1)*(x-I)*(x+I)*(x-2*I)*(x+2*I))
Out[22]: [1, -ⅈ, ⅈ, -2⋅ⅈ, 2⋅ⅈ]
```
The `all_roots` function is not limited by degree because it uses `RootOf`. The call to `evalf` from the exact representation of the roots is guaranteed to give a result that is accurate to the requested precision.

NumPy's `np.roots` function cannot provide similar guarantees because it uses fixed precision floating point.

**Comment by moorepants** [comment] 2024-06-23 12:03
NumPy would ideally be eliminated from `control_plots.py`. This code gets merged without being stricter about eating our own dog food for plotting.

**Comment by akshanshbhatt** [comment] 2024-06-23 15:05
I understand that using numpy is not the most elegant approach to get polynomial root data. Still, I don't think that sympy's built-in polynomial root calculator is fast enough to use it instead. Sure, sympy gives more consistent and precise results, but we don't require low-tolerance data points for plotting purposes. See the time difference using both of these methods:

```python
In [2]: p = x**8 + 9*x**5 + 11*x + 7  # Arbitrary 8-deg polynomial

In [3]: %time [r.evalf() for r in all_roots(p)]
CPU times: user 4.1 s, sys: 5.52 ms, total: 4.11 s
Wall time: 4.11 s
Out[3]:
[-2.10954725209519,
 -0.582637006756454,
 -0.55581013748193 - 0.805706304516959*I,
 -0.55581013748193 + 0.805706304516959*I,
 0.912751454705842 - 0.742665591979299*I,
 0.912751454705842 + 0.742665591979299*I,
 0.98915081220191 - 1.82059670736243*I,
 0.98915081220191 + 1.82059670736243*I]

In [4]: %time np.roots(np.array(Poly(p, x).all_coeffs(), dtype=np.complex128))
CPU times: user 2.41 ms, sys: 5.06 ms, total: 7.47 ms
Wall time: 11.9 ms
Out[4]:
array([ 0.98915081+1.82059671e+00j,  0.98915081-1.82059671e+00j,
       -2.10954725+3.95682719e-16j,  0.91275145+7.42665592e-01j,
        0.91275145-7.42665592e-01j, -0.55581014+8.05706305e-01j,
       -0.55581014-8.05706305e-01j, -0.58263701-2.23618104e-25j])
```

The precision vs calculation-time tradeoff is quite skewed. This is the reason we decided to use numpy in the first place. Sometime in the future, if root-locus plot is added to this module, it will depend on the pz numerical value function for root calculations, which will be called a hundred, perhaps even a thousand times (for sampling loci points). It will only make this time bottleneck worse. I would love to hear if you have any suggestions for solving this.

**Comment by oscarbenjamin** [comment] 2024-06-23 16:54
We can make the SymPy routines faster in various ways including by using better algorithms and/or using python-flint:
```python
In [3]: from flint import *

In [4]: x = fmpz_poly([0, 1])

In [5]: p = x**8 + 9*x**5 + 11*x + 7

In [6]: p
Out[6]: x^8 + 9*x^5 + 11*x + 7

In [7]: %time p.complex_roots()
CPU times: user 6.61 ms, sys: 0 ns, total: 6.61 ms
Wall time: 76.5 ms
Out[7]: 
[([-2.10954725209519 +/- 6.57e-16], 1),
 ([-0.582637006756454 +/- 3.76e-16], 1),
 ([0.912751454705842 +/- 4.04e-16] + [0.742665591979299 +/- 1.98e-16]j, 1),
 ([0.912751454705842 +/- 4.04e-16] + [-0.742665591979299 +/- 1.98e-16]j, 1),
 ([-0.555810137481930 +/- 4.43e-16] + [0.805706304516960 +/- 4.93e-16]j, 1),
 ([-0.555810137481930 +/- 4.43e-16] + [-0.805706304516960 +/- 4.93e-16]j, 1),
 ([0.989150812201910 +/- 4.79e-16] + [1.82059670736243 +/- 1.14e-15]j, 1),
 ([0.989150812201910 +/- 4.79e-16] + [-1.82059670736243 +/- 1.14e-15]j, 1)]
```

> The precision vs calculation-time tradeoff is quite skewed. This is the reason we decided to use numpy in the first place

Why should anyone use SymPy's control module at all?

There are other Python control modules. If someone wants to use numpy to do a root locus plot then they can use the `control` module:
https://python-control.readthedocs.io/en/latest/generated/control.root_locus.html

What purpose is served by SymPy reimplementing things that already exist in other libraries?

Providing more accurate calculations is one possible reason for SymPy to have a control module. Duplicating the features that already exist in other Python libraries is not.

If SymPy's control module plotting functionality is not any better than the other control libraries then I don't think any plotting functionality should be added to SymPy's control module apart from just calling into the other libraries.

**Comment by oscarbenjamin** [comment] 2024-06-23 17:10
> ```python
> In [7]: %time p.complex_roots()
> CPU times: user 6.61 ms, sys: 0 ns, total: 6.61 ms
> Wall time: 76.5 ms
> ```

Note actually that this time was inflated by initialising the printer. Here is the actual time:
```python
In [1]: from flint import *

In [2]: x = fmpz_poly([0, 1])

In [3]: p = x**8 + 9*x**5 + 11*x + 7

In [4]: %time r = p.complex_roots()
CPU times: user 2.19 ms, sys: 0 ns, total: 2.19 ms
Wall time: 2.21 ms
```

**Comment by akshanshbhatt** [comment] 2024-06-24 07:21
If flint is a better alternative to numpy and works reasonably fast, then we should probably use it instead.

**Comment by oscarbenjamin** [comment] 2024-06-24 10:41
SymPy already uses flint for some things as an optional dependency. The point is it can be used to make `all_roots` etc faster. It is also possible to speed up `all_roots` without using flint as well.

The control module should just use the SymPy functions like `all_roots`.

**Comment by akshanshbhatt** [comment] 2024-06-24 12:41
> The control module should just use the SymPy functions like `all_roots`.

I get it now. Should I open a PR?

**Comment by oscarbenjamin** [comment] 2024-06-24 15:25
> Should I open a PR?

Yes.

**Closed** 2024-06-24 15:27 UTC
Labels: physics.control

**Comment by akshanshbhatt** [comment] 2024-06-25 08:11
I'm working on a PR to remove numpy. `all_roots()` function tends to fail for polynomials with complex coefficients:

```py
In [2]: a
Out[2]: Poly(x**2 + (2 + I)*x + 10, x, domain='ZZ_I')

In [3]: a.all_roots()
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-3-732584d46234> in <module>
----> 1 a.all_roots()

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sympy/polys/polytools.py in all_roots(f, multiple, radicals)
   3615
   3616         """
-> 3617         roots = sympy.polys.rootoftools.CRootOf.all_roots(f, radicals=radicals)
   3618
   3619         if multiple:

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sympy/polys/rootoftools.py in all_roots(cls, poly, radicals)
    408     def all_roots(cls, poly, radicals=True):
    409         """Get real and complex roots of a polynomial. """
--> 410         return cls._get_roots("_all_roots", poly, radicals)
    411
    412     @classmethod

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sympy/polys/rootoftools.py in _get_roots(cls, method, poly, radicals)
    748                 poly = poly.xreplace({d: x})
    749                 break
--> 750         coeff, poly = cls._preprocess_roots(poly)
    751         roots = []
    752

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sympy/polys/rootoftools.py in _preprocess_roots(cls, poly)
    716
    717         if not dom.is_ZZ:
--> 718             raise NotImplementedError(
    719                 "sorted roots not supported over %s" % dom)
    720

NotImplementedError: sorted roots not supported over ZZ_I
```

Is there any fix for this since it happens to be one of the test cases?

**Comment by oscarbenjamin** [comment] 2024-06-25 10:17
The `all_roots` function only works for polynomials with rational coefficients at the moment although that can be improved (gh-22943).

For now we can use `nroots`:
```
In [1]: Poly(x**2 + (2 + I)*x + 10, x, domain='ZZ_I').nroots()
Out[1]: [-1.16416003314479 - 3.54580835189644⋅ⅈ, -0.835839966855209 + 2.54580835189644⋅ⅈ]
```
Something like:
```
p = expr.as_poly()
if p.domain in (ZZ, QQ):
    # use all_roots...
else:
    # XXX: Use all_roots for irrational coefficients when possible
    # https://github.com/sympy/sympy/issues/22943
    # use nroots...
```

In general `nroots` is less guaranteed to be accurate and so `all_roots` should still be preferred when possible. It should usually be more accurate than `np.roots` though because it uses higher precision internal arithmetic than numpy does.
