### ISSUE TITLE
Wrong result in LieDerivative

### ISSUE THREAD

**Issue by donielix** [sympy/sympy#17917] opened 2019-11-18 17:53 UTC
I'll reproduce the steps that go to a wrong result:

```python
from sympy.diffgeom import Manifold, Patch, CoordSystem, LieDerivative
M = Manifold('M', 2)
P = Patch('P', M)
coord = CoordSystem("coord", P, ["x", "y"])
dx, dy = coord.base_oneforms()
ex, ey = coord.base_vectors()
x, y = coord.coord_functions()
X = x*ex-y*ey
Y = (x**2+y**2)*ex-x*y*ey
LieDerivative(X, Y)
>> -x*y*ey
```
But this is absolutely wrong, the correct Lie Derivative of Y w.r.t X is (x^2 - 3*y^2)&PartialD;x-xy&PartialD;y as you can easily check. Sympy is omitting the first term

What is happening here?

**Comment by jksuom** [comment] 2019-11-18 18:41
Probably related to https://github.com/sympy/sympy/issues/16752.

**Comment by smichr** [comment] 2021-09-23 00:37
duplicate of #16752

**Closed by smichr** 2021-09-23 00:37 UTC
Labels: diffgeom
