### ISSUE TITLE
Bug in assumption computation of expression with matrix element

### ISSUE THREAD

**Issue by aeflores** [sympy/sympy#21623] opened 2021-06-15 19:11 UTC
The following code throws an exception when trying to compute whether `e` is finite with Sympy 1.8
```
from sympy import *
a = MatrixSymbol("a",5,1)
e = cosh(a[4, 0]**2)
e.is_finite
```

**Comment by oscarbenjamin** [comment] 2021-06-15 19:48
The problem is that the MatrixSymbol name attribute is Str which is a Basic subclass. The Str class has no args and does not satisfy the func-args invariant:
```python
In [13]: M = MatrixSymbol('X', 2, 2)

In [14]: M.args
Out[14]: (X, 2, 2)

In [15]: name = M.args[0]

In [16]: type(name)
Out[16]: sympy.core.symbol.Str

In [17]: name = name.func(*name.args)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-17-4201076f98a7> in <module>
----> 1 name = name.func(*name.args)

TypeError: __new__() missing 1 required positional argument: 'name'
```
We can quick fix this with:
```diff
diff --git a/sympy/core/exprtools.py b/sympy/core/exprtools.py
index 459d896724..05588c51f8 100644
--- a/sympy/core/exprtools.py
+++ b/sympy/core/exprtools.py
@@ -1101,6 +1101,8 @@ def handle(a):
         # don't treat internal args like terms of an Add
         if not isinstance(a, Expr):
             if isinstance(a, Basic):
+                if a.is_Atom:
+                    return a
                 return a.func(*[handle(i) for i in a.args])
             return type(a)([handle(i) for i in a])
         return gcd_terms(a, isprimitive, clear, fraction)
```
A better fix would be ensuring that all Basic instances satisfy the func-args invariant. The problem is wider than just `Str` though as e.g. `Integer` does not satisfy the invariant.

**Comment by oscarbenjamin** [comment] 2021-06-15 19:51
Marking as easy to fix for the diff above along with a test for this which fails on master e.g.:
```python
In [1]: M = MatrixSymbol('X', 2, 2)

In [2]: gcd_terms(M[0,0], 1)
---------------------------------------------------------------------------
TypeError 
```

**Comment by oscarbenjamin** [comment] 2021-06-15 20:11
Actually a better fix might be just checking `if not a.args` rather than `if a.is_Atom`.

**Comment by ArunSanganal** [comment] 2021-06-16 06:50
@oscarbenjamin How do we test the changes in code after they have been made? Like I want to check if a modified method works before making a pr.

**Comment by sidhu1012** [comment] 2021-06-16 06:55
> @oscarbenjamin How do we test the changes in code after they have been made? Like I want to check if a modified method works before making a pr.

Save the changes and run pytest and doctest for directory/file where you want to check.

**Comment by ArunSanganal** [comment] 2021-06-16 07:02
> > @oscarbenjamin How do we test the changes in code after they have been made? Like I want to check if a modified method works before making a pr.
> 
> Save the changes and run pytest and doctest for directory/file where you want to check.

Thanks. Can you give an example for the same, that would make it crystal clear. Sorry for the newbie questions, I am new to this.

**Comment by sidhu1012** [comment] 2021-06-16 10:50
pytest sympy/.../test_file.py for runing tests.
bin/doctest sympy/.../file.py for docstring test, this won't run on windows.

**Comment by ArunSanganal** [comment] 2021-06-16 14:54
okay, one last question. Test file checks if all the assertions in the file are true, right? So, I would have to know the test result beforehand to use `assert` on it. How do I get that result?

**Comment by 0sidharth** [comment] 2021-06-28 06:31
You can run the code by making a python script or running `isympy`, and giving the original expression as an input. This will tell you the output

**Closed** 2021-07-04 21:48 UTC
Labels: Easy to Fix, core
