### ISSUE TITLE
Brackets are off on the website

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [sympy/sympy#16756] opened 2019-04-30 06:04 UTC
![sympy](https://user-images.githubusercontent.com/22630684/56943162-45313b00-6b2f-11e9-8232-3e811c74a959.png)

bit messy

**Comment by asmeurer** [comment] 2019-04-30 09:09
If you install the font DejaVu Sans Mono it should look better. See https://github.com/sympy/sympy/issues/15700 (closing this as a dupe of that).

**Closed by asmeurer** 2019-04-30 09:09 UTC
