### ISSUE TITLE
nonlinsolve raises TypeError

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#17276] opened 2019-07-27 08:21 UTC
`nonlinsolve([Eq(x, 5**(Integer(1)/5)), Eq(x*y, 25*sqrt(5))], x, y)` raises `TypeError: unsupported operand type(s) for ** or pow(): 'Tuple' and 'int'`

**Comment by oscargus** [comment] 2019-07-27 11:03
The problem seems to be that the argument to `_is_sum_surds` (that doesn't have any documentation...) is a `Tuple`. Iterating over the Tuple elements just leads to an error later, where again, the problem seems to be that the argument is Tuple:

```

  File "C:\Users\Oscar\sympy\sympy\polys\numberfields.py", line 569, in _minpoly_compose
    raise NotAlgebraic("%s doesn't seem to be an algebraic element" % ex)

NotAlgebraic: (PurePoly(_x**5 - 5, _x, domain='QQ'), 5**(1/5)) doesn't seem to be an algebraic element
```

So the question is really where and why does it become a Tuple?

It seems like the Tuple, `(PurePoly(_x**5 - 5, _x, domain='QQ'), 5**(1/5))`, contains two possible solutions, where the first one is a polynomial representation of the second (albeit having more solutions than the given one...).

**Comment by jksuom** [comment] 2019-07-27 13:02
It looks like this is caused by the same bug as in https://github.com/sympy/sympy/issues/13230. The fix should check the parameter `ext` of `AlgebraicField`. It is a tuple containing the algebraic generator(s) of the field and sometimes also a precomputed minimal polynomial, saved for efficiency. It seems that the polynomial will be the first item if it is present, and in that case it should be removed before `ext` is substituted to `orig_ext`. So the proper form of `orig_ext` should be a tuple of algebraic numbers, `(5**(1/5),)`, for example.

**Comment by jksuom** [comment] 2019-07-27 14:02
This is the line where the polynomial is introduced:
https://github.com/sympy/sympy/blob/12c50d4004174407a6afc9ab748ba553de42aa07/sympy/polys/constructor.py#L95
So it seems that `ext` will not be a tuple consisting of polynomial and its root but a tuple whose single item is such a tuple (or maybe Tuple, perhaps the test should be `is_sequence`).

**Comment by akhil-dh1** [comment] 2020-01-16 15:37
@jksuom , @gschintgen can I work on this bug? I'm new to the solvers module, so if you could guide me where to start, it would be great!

**Comment by jksuom** [comment] 2020-01-16 17:43
This is the relevant line: https://github.com/sympy/sympy/blob/efdeb1f32d67292531641431bf1517c1bc67b8be/sympy/polys/domains/algebraicfield.py#L30

`ext` is a tuple whose elements are the generators of the algebraic field to be constructed. They are usually expressions like `sqrt(3)`. Sometimes they may be different: tuples that consist of a polynomial and an expression. In those cases the polynomials should be removed and a new tuple consisting of the expressions alone should be assigned to `orig_ext`.

**Comment by mohitacecode** [comment] 2020-02-16 17:05
It will be partially solved by pr(#18669 ) but another issue came up:
I am working on it to identify the problem and soln.
```
  File "/home/mohit/Documents/sympy-master/sympy/sympy/solvers/solveset.py", line 2994, in _solve_using_known_values
    depen = eq2.as_independent(unsolved_syms)[0]
AttributeError: 'Equality' object has no attribute 'as_independent'
```

**Comment by mohitacecode** [comment] 2020-02-16 17:16
This will be solved by adding this  `eq2 = eq2.rewrite(Add)`  before line no. 2994 in solveset.py.
because here for ex:

```
>>>Eq(x, 5**(Integer(1)/5))
```
will return `Equality` class object but it does not have `as_independent` function.
`as_independent` is inside `Expr` class so we have to first convert `Eq(x, 5**(Integer(1)/5))` into `Add` class to call `as_independent` function.

What do you think @jksuom ?

**Comment by jksuom** [comment] 2020-02-16 17:53
> >>>Eq(x, 5**(Integer(1)/5))

Where is this line?

**Comment by mohitacecode** [comment] 2020-02-16 18:04
> `nonlinsolve([Eq(x, 5**(Integer(1)/5)), Eq(x*y, 25*sqrt(5))], x, y)` raises `TypeError: unsupported operand type(s) for ** or pow(): 'Tuple' and 'int'`

I've just taken a example from the given problem.

**Comment by jksuom** [comment] 2020-02-16 18:11
Is that an old problem? Given before `Relational` was made to not derive from `Expr`? Then the example should be fixed.

**Comment by mohitacecode** [comment] 2020-02-16 18:17
yes I think so.because curr

I think we have to add only one line to solve this problem as suggested in the above comments.(https://github.com/sympy/sympy/issues/17276#issuecomment-586730330)

**Comment by jksuom** [comment] 2020-02-16 18:28
That looks like the correct fix.

**Comment by mohitacecode** [comment] 2020-02-16 18:29
Ok I am making a pr for it.

**Closed** 2020-02-28 13:01 UTC
Labels: polys, solvers
