### ISSUE TITLE
isprime gives wrong result on a/b values

### ISSUE THREAD

**Issue by jhanwar** [sympy/sympy#16045] opened 2019-02-22 16:47 UTC
`isprime(14/2)` returns `false`. I think it is because `isinstance(n, (Float, float))` returns `true` when n = 14/2

**Comment by oscargus** [comment] 2019-02-22 17:29
Correct. Try `isprime(14/S(2))` which makes it a `Rational` of integers or `isprime(14//2)` (in Python 3.X) which uses integer division.

This is a Python issue as there is no way for Sympy to avoid evaluation of 14/2 returning a Float.

**Comment by asmeurer** [comment] 2019-02-22 18:16
The logic for this comes from `as_int`, in sympy.core.compatibility. It allows floats to be converted to integers as long as they are equal.  This is somewhat surprising to me. I had thought it failed on floats.

**Comment by smichr** [comment] 2019-02-22 18:31
> This is somewhat surprising to me. I had thought it failed on floats

it could have a strict option or else always reject floats, only allowing int or Integer to pass

**Comment by asmeurer** [comment] 2019-02-22 18:34
I guess accepting floats was intended when it was designed. It's probably fine, although doing so for floats larger than 1e15 is probably a bad idea.

```py
>>> int(1e100)
10000000000000000159028911097599180468360808563945281389781327557747838772170381060813469985856815104
>>> int(1e100) == 1e100
True
>>> as_int(1e100)
10000000000000000159028911097599180468360808563945281389781327557747838772170381060813469985856815104
```

**Comment by smichr** [comment] 2019-02-22 21:42
> is probably a bad idea

whoa...I guess so! Nice catch.

**Comment by oscargus** [comment] 2019-02-22 21:51
Also see #9097

**Comment by XtremeGood** [comment] 2019-02-23 07:02
Does this issue requires works?

**Comment by dandiez** [comment] 2019-02-23 09:01
> This is a Python issue as there is no way for Sympy to avoid evaluation of 14/2 returning a Float.

Has it been considered to accept string inputs which have not been parsed by python?
e.g. to accept something like `isprime('14/2')` ?

**Comment by XtremeGood** [comment] 2019-02-23 10:24
it's a checker why should it?Anyways eval( return x ) should do the job.
>>> isprime("14")
False
>>> isprime(eval("14/2"))
False
>>> isprime(14)
False

I still think you should explicitly check it since it's duty is to check not solve and check.

**Comment by dandiez** [comment] 2019-02-23 11:28
I was trying to think if we could somehow go around the limitation of the python parser (that it evaluates stuff and, by the time it gets to sympy, things like 14/2 have become Floats).
For example, wolfram/alpha manages: https://www.wolframalpha.com/input/?i=isprime(14%2F2)

So I was thinking that if we were to accept strings we could parse them differently in sympy, however that does not go around the fact that the users must put quotes around expressions (and at that point we might as well ask them to wrap things in `S()`, etc.).

Other more radical ideas would probably involve somehow intercepting the python parser and redefining the math operations, such that they use a sympy friendly parser, so 14/2 would return 7 and not 7.0 (not sure if this is even possible, and what undesired consequences it might have...).

For example we could do:
```
with sympy.symbolic_parser():
    # everything within this block would use sympy's parser instead of python's for math operations
    a=14/2
    print(a) # returns 7
    b=15/2
    print(b) # returns 15/2
c=14/2
print(c) # returns 7.0
d=15/2
print(d) # returns 7.5
```

**Comment by XtremeGood** [comment] 2019-02-23 11:31
why not use eval?

**Comment by dandiez** [comment] 2019-02-23 11:35
eval(14/2) would return 7.0, whereas the desired outcome is 7

**Comment by XtremeGood** [comment] 2019-02-23 11:44
Ok you have a point. though it gives true for the above case.

**Comment by XtremeGood** [comment] 2019-02-23 11:53
Ok what should I implement in order to solve it?One think it if it does int division 15/2 is not prime but it is not divisible so what exactly.Another way is split the string at / and check if a%b ==0 return isprime(a//b)
else error or something.

**Comment by oscargus** [comment] 2019-02-23 12:17
I think it works as it is supposed to. Float are not prime.

**Comment by oscarbenjamin** [comment] 2019-02-23 12:49
@jhanwar given the comments above do you think anything should be fixed here or can this issue be closed?

**Comment by jhanwar** [comment] 2019-02-23 17:16
@oscarbenjamin
I think we should fix this because for the user, it seems intuitive that 14/2 should return 'True' 
We can easily fix this issue. We can use the ceiling function and can check if `ceiling(n) == n` and then only we will check that n is prime or not. It seems right to me. What do you say? Should i send a pull request?

**Comment by XtremeGood** [comment] 2019-02-23 19:03
So does this require the fix?If so, then I would like to do it.

**Comment by dandiez** [comment] 2019-02-23 19:20
Since this is very related to the issue mentioned above, should we close this issue and continue the discussion/fix in https://github.com/sympy/sympy/pull/9097 ?

**Comment by jhanwar** [comment] 2019-02-23 19:21
@XtremeGood I am already working on it..

**Comment by XtremeGood** [comment] 2019-02-23 19:25
Ok, but I guess @dandiez referred another post in which the issue is already being worked upon.

**Comment by dandiez** [comment] 2019-02-23 19:33
I think the issue here is in principle the same as the issue in #9097 
If I understood the plan to fix #9097 is to:
- check for floats and return False; this would also return false for isprime(14/2)  (because python parses the 14/2 and converts it to a Float before it gets to sympy)
- add to the documentation that isprime returns False for floats and for anything that returns a float, like 14/2, at least in this way, users that get surprised and check the docs will know what's going on.
If we think is needed to guide the users further, we could add in the docstring as well the "workarounds" metioned before (either wrap the numbers in S() or use the integer division // )

The only difference for this pull request I see is, if we wanted to "fix" python's default behaviour of evaluating math expressions such as integer/integer=float, such that they are not "simplified" before they get to sympy...

**Comment by jhanwar** [comment] 2019-02-23 19:54
@dandiez 
you are right. The principle is same for both the issue. what should `isprime(14/2)` return? 
False or True

**Comment by dandiez** [comment] 2019-02-23 21:10
:D good quesion... without reopening the discussion from #9097 ...
I guess in an ideal world 14/2 should evaluate to 7 (integer) and therefore isprime return True.
Given the current constraints, 14/2 evaluates (evaluated by core python) to 7.0 (Float) and for consistency with any other floats, isprime should return False.
Since the users probably will fall in the pitfall, we can tell them via the docs what the behaviour is and try to keep consistency, which I believe is the conclusion so far in #9097 .

**Comment by XtremeGood** [comment] 2019-02-23 21:23
Why not use 14//2?

**Comment by asmeurer** [comment] 2019-02-24 01:13
`isprime` ought to be using `as_int`. 

If we want to reject float values, that should be done in as_int, so that all number theory functions work the same way. That would need to be discussed first, though.

**Comment by jhanwar** [comment] 2019-02-24 21:08
I am not sure about what should `isprime(7.0)` return?
but if `isprime(7*1)` and `isprime(5+2)` returns `true` then I think, `isprime(7/1)` or `isprime(14/2)` should also return `true`

**Comment by oscarbenjamin** [comment] 2019-02-24 21:42
I think that isprime and all other functions that are supposed to work with exact int/rational inputs should treat floats as being inexact. It does of course make sense that from a purely mathematical perspective that `isprime(7/1)` should return True. However in Python this translates to `isprime(7.0)` and that `7.0` is a float and there's no way for SymPy to tell the difference between `7.0` and `7.0 + 1e-20` which is neither prime nor integer.

I think that SymPy should maintain a clear line between floats and exact inputs with floats being treated as approximate and only leading to approximate outputs (float in, float out). A user who wants to check whether `7.0` is prime should be force to use `nsimplify`, `round` etc so that they can see the approximation being made *in their own code* outside of SymPy.

I think it's unfortunate that their are already cases where `nsimplify` is called implicitly which only leads to suggestions for it to be extended (e.g. #15816 which just got merged).

See also:
#15844 (maybe a better place to discuss the general idea)
#16007 - one of many similar issues raised by different users over time

**Comment by jhanwar** [comment] 2019-02-25 12:28
Python treats `7/1` and `7.0` as exactly same. So, there is no way that we can operate differently `7/1` and `7.0` in sympy. I think that the consensus is that `isprime(7/1)` or `isprime(7.0)` should return `False`. I think that we can close this issue. @oscargus

**Comment by oscargus** [comment] 2019-02-25 16:09
I was of the impression that this was decided earlier, yes. But based on the comment of @asmeurer it may not be like that.

It may clearly be confusing for newer users that `isprime(7/1)` is False, but on the other hand a very good example of what is Python and what is Sympy. Something that they eventually will have to learn anyway, so I guess "saving" them in this (and maybe a few other places) will not really change much and therefore I think that one should already here differ between integer numbers, rational numbers and floats. Still, it is a bit unfortunate that Python returns a float here (C does not). Either way there is a difference in number representations that one eventually will have to understand (or get bitten by), independent of language and package.

**Comment by XtremeGood** [comment] 2019-02-25 17:02
But the implementation shouldnt be hard though. Afterall we can convert the
input to string and solve the input and then use isprime on that argument.
It would be just a simple decorator. Total user friendly.

**Comment by XtremeGood** [comment] 2019-02-25 17:03
Ok?

**Comment by oscargus** [comment] 2019-02-25 17:22
How would you know if 7.0 comes from 7/1 or 14/2 (or 7.0)? Entering it as a string and evaluate it?

And how would you distinguish it from 7+1e-20?

Or am I missing something here?

**Comment by XtremeGood** [comment] 2019-02-25 17:41
Isn't the objective to make 14/2 return as 7 not 7.0?

**Comment by XtremeGood** [comment] 2019-02-25 17:46
```
#example code
def decorate(s):
 a,b =tuple(map(int, s.split("/")))
 if a % b == 0:
   return isprime(str(a//b))
 else raise "Fraction can't be classified Prime or not"

**Comment by oscargus** [comment] 2019-02-25 18:05
It may solve this particular case (not obvious to me, but since I do not know much about decorators I trust you there, `str` doesn't seem required nor the right thing to do though, but that is not part of the issue anyway), but then we just move the barrier slightly, sometimes. What about `isprime((28/2)/(6/3))` ? The actual discussion, I think, is whether floats, which happens to have a zero fractional part should be considered primes or not. Independent of how they where generated.

**Comment by XtremeGood** [comment] 2019-02-25 18:11
I too don't know about decorator. I prefer "outer function" terminology. It's just that people like fancy terms, jargons etc so I used that.No problem. Use a reduce(continuous splitting until no / is left and divisions are associative so it can be done) .I checked that isprime works for both "7/1" and 7/1
i.e. both int and string inputs

**Comment by dandiez** [comment] 2019-02-25 18:15
I think if we go that way we might as well think how we intercept the python parser before it parses the string (or other math operands) and evaluates things like 7/1 to a float

**Comment by XtremeGood** [comment] 2019-02-25 18:17
You can use split at a pattern.I can try making a working code if it closes this issue.

**Comment by dandiez** [comment] 2019-02-25 18:23
I still don't understand the approach you want to use. Can you please put an example?
If the user input is
>> isprime(14/2)

and you add a decorator to isprime(), would the decorator not receive 7.0? I would think that python evaluates 14/2 before passing it on? Or am I missing something?

**Comment by XtremeGood** [comment] 2019-02-25 18:26
Umm, yes true if the user does not enter a string then it would be trouble.So we would have to explicitly take a string argument.Also by python convension 7/1 = 7.0 and 7//1 = 7

**Comment by XtremeGood** [comment] 2019-02-25 18:39
One thing just caught my mind.Sympy is written in python and by default inputs are taken as string in python so why would 7/1 it be computed?

**Comment by asmeurer** [comment] 2019-02-25 21:25
Python is eager evaluated, meaning it is impossible for a function `f` to distinguish between `f(7/1)` and `f(7.0)`, because the interpreter evaluates 7/1 before f is even called (actually with integer literals, it is evaluated when the code is compiled.

If you want an environment where `int/int` produces a rational, you can use `isympy -i` or `init_session(auto_int=True)`. This sort of thing is fine for interactive calculator-like environments where you just want to save some typing and don't care about reusing the code. But SymPy also needs to be usable as a library. In those cases, patching the interpreter to change how integer division works is not an option. It is simply understood that the user knows about Python semantics, and be aware of the gotcha that when working with integers in SymPy, you need to wrap at least one of them with `Integer` before doing division. The [gotchas](https://docs.sympy.org/latest/tutorial/gotchas.html#two-final-notes-and) page on the tutorial explains this, as well as [this one](https://docs.sympy.org/latest/gotchas.html#python-numbers-vs-sympy-numbers). 

> by default inputs are taken as string in python so why would 7/1 it be computed?

This is not correct. `isprime(7/1)` is not the same as `isprime('7/1')`. String inputs do work with some functions in SymPy, but it is generally considered an antipattern, and could be removed in the future. See https://github.com/sympy/sympy/wiki/Idioms-and-Antipatterns#strings-as-input for a discussion on why it is bad. Again, if you want a rational number in SymPy, it is an unfortunate gotcha that you need to wrap at least one integer with a SymPy type.

**Comment by asmeurer** [comment] 2019-02-25 21:26
This issue got somewhat sidetracked, but I think it should be about whether `as_int` should accept floats with zero fractional part. It currently does, but we should consider whether it is better to not to.

**Comment by XtremeGood** [comment] 2019-02-25 21:28
> 
> 
> Python is eager evaluated, meaning it is impossible for a function `f` to distinguish between `f(7/1)` and `f(7.0)`, because the interpreter evaluates 7/1 before f is even called (actually with integer literals, it is evaluated when the code is compiled.
> 
> If you want an environment where `int/int` produces a rational, you can use `isympy -i` or `init_session(auto_int=True)`. This sort of thing is fine for interactive calculator-like environments where you just want to save some typing and don't care about reusing the code. But SymPy also needs to be usable as a library. In those cases, patching the interpreter to change how integer division works is not an option. It is simply understood that the user knows about Python semantics, and be aware of the gotcha that when working with integers in SymPy, you need to wrap at least one of them with `Integer` before doing division. The [gotchas](https://docs.sympy.org/latest/tutorial/gotchas.html#two-final-notes-and) page on the tutorial explains this, as well as [this one](https://docs.sympy.org/latest/gotchas.html#python-numbers-vs-sympy-numbers).
> 
> > by default inputs are taken as string in python so why would 7/1 it be computed?
> 
> This is not correct. `isprime(7/1)` is not the same as `isprime('7/1')`. String inputs do work with some functions in SymPy, but it is generally considered an antipattern, and could be removed in the future. See https://github.com/sympy/sympy/wiki/Idioms-and-Antipatterns#strings-as-input for a discussion on why it is bad. Again, if you want a rational number in SymPy, it is an unfortunate gotcha that you need to wrap at least one integer with a SymPy type.

Thanks for the info.

**Comment by smichr** [comment] 2019-02-25 23:12
> we should consider whether it is better to not to

I think the example of `int(1e23) == 99999999999999991611392 == 1e23 == True` is enough to make me say that it should not allow floats as input. The reason it is being used is to make sure the routine has a Python int to work with instead of a slower class object like Integer. If a routine has `i = as_int(n)` you know that i is an int and is unambiguously so and you know the user will be told if it was not an integer (which is better than silently letting bad input like `n=3.2` be processed as `i = int(n)`).

So I would say that `as_int` should be modified to reject input that does not unambiguously represent an exact integer.

**Closed** 2019-02-28 02:49 UTC
Labels: Needs Decision
