### ISSUE TITLE
ImportError when importing sympy 1.10 with typing.TYPE_CHECKING == True

### ISSUE THREAD

**Issue by dweindl** [sympy/sympy#23216] opened 2022-03-07 14:43 UTC
Hi, since sympy 1.10, `import sympy` results in an `ImportError` if `typing.TYPE_CHECKING` is set to `True`.

* `python -c "import sympy"`: works
* `python -c "import typing; typing.TYPE_CHECKING = True; import sympy"` fails:
  ```
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/lib/python3.9/site-packages/sympy/__init__.py", line 51, in <module>
      from .core import (sympify, SympifyError, cacheit, Basic, Atom,
    File "/lib/python3.9/site-packages/sympy/core/__init__.py", line 4, in <module>
      from .sympify import sympify, SympifyError
    File "/lib/python3.9/site-packages/sympy/core/sympify.py", line 9, in <module>
      from sympy.core.random import choice
    File "/lib/python3.9/site-packages/sympy/core/random.py", line 25, in <module>
      from sympy.utilities.iterables import is_sequence
    File "/lib/python3.9/site-packages/sympy/utilities/__init__.py", line 11, in <module>
      from .lambdify import lambdify
    File "/lib/python3.9/site-packages/sympy/utilities/lambdify.py", line 24, in <module>
      import sympy.core.expr
    File "/lib/python3.9/site-packages/sympy/core/expr.py", line 5, in <module>
      from .sympify import sympify, _sympify
  ImportError: cannot import name 'sympify' from partially initialized module 'sympy.core.sympify' (most likely due to a circular import) (/lib/python3.9/site-packages/sympy/core/sympify.py)
  ```
  
The problem does not occur with sympy 1.9.

**Comment by oscarbenjamin** [comment] 2022-03-07 15:41
Should this even be expected to work? The whole point of setting `TYPE_CHECKING` to true is that the code is not actually being executed and anything in the block is just for static analysis.

**Comment by dweindl** [comment] 2022-03-07 16:13
Okay, according to the cited PEP, this would be a non-issue. My (apparently wrong) understanding was that `TYPE_CHECKING` was rather meant to be used to avoid expensive imports, as shown in the [`typing.TYPE_CHECKING` documentation](https://docs.python.org/3/library/typing.html#typing.TYPE_CHECKING), and that code should still run with `TYPE_CHECKING=True`, although potentially slower. Fine to close then.

To provide some context: This is an issue when using [sphinx-autodoc-typehints](https://github.com/tox-dev/sphinx-autodoc-typehints) on projects using sympy. I just noticed that a simple workaround  is importing sympy in shinx's conf.py before `TYPE_CHECKING` is set to `True`.

**Comment by oscarbenjamin** [comment] 2022-03-07 16:21
> To provide some context: This is an issue when using [sphinx-autodoc-typehints](https://github.com/tox-dev/sphinx-autodoc-typehints) on projects using sympy.

I would say it's a bug in the sphinx extension:
https://github.com/tox-dev/sphinx-autodoc-typehints/issues/22

**Comment by oscargus** [comment] 2022-03-07 17:05
It is a consequence of an attempt to keep the import order of modules somewhat consistent. For example, utilities should not have any imports from core (so that one can always import utilities in core). Enabling TYPE_CHECKING activates this

https://github.com/sympy/sympy/blob/b2ff075530e1340425e1edd203aeb53c081bf9af/sympy/utilities/lambdify.py#L23-L24

So it is in hindsight sort of expected that this will happen. Although I do not think the idea is that it should happen... Probably a left-over after only checking that there were no imports without any indentation.

Not sure if those lines even need to be there.

**Comment by oscarbenjamin** [comment] 2022-03-07 23:06
> For example, utilities should not have any imports from core (so that one can always import utilities in core).

A bit OT but should it be that way round? I see various things in utilities but not many that seem like they should come before core:
```
$ ls sympy/utilities
autowrap.py      decorator.py    iterables.py          mathml          __pycache__  source.py
benchmarking.py  enumerative.py  lambdify.py           memoization.py  pytest.py    tests
codegen.py       exceptions.py   magic.py              misc.py         randtest.py  timeutils.py
_compilation     __init__.py     matchpy_connector.py  pkgdata.py      runtests.py  tmpfiles.py
```
The only one that looks it should be in/before core is `exceptions.py`. I would say that's out of place here in utilities. Or maybe actually the problem is that `lambdify`, `autowrap` etc shouldn't be there.

**Comment by oscarbenjamin** [comment] 2022-06-21 11:50
I'm going to close this. I think that SymPy is using `TYPE_CHECKING` correctly.

The issue with the sphinx type hints extension has a bunch of comments presumably from other people running into the same thing because the extension just isn't using `TYPE_CHECKING` correctly:
https://github.com/tox-dev/sphinx-autodoc-typehints/issues/22

**Closed by oscarbenjamin** 2022-06-21 11:50 UTC
Labels: Uncategorised
