### ISSUE TITLE
Pell equations

### ISSUE THREAD

**Issue by ranea** [sympy/sympy#11486] opened 2016-08-07 18:18 UTC
I'm trying to solve pell equations with sympy.

However, I get some bad results.

For example, let d=2, n=-9.

```
>>> diop_DN(2, -9)
[(3, 3)] 

>>> diop_bf_DN(2, -9)
[(3, 3)] 
```

But (3,3) isn't a solution!

```
3^2 + 9 * 3^2 != 2
```

Is there something about the Diophantine module that I am missing?

Thanks.

**Comment by jksuom** [comment] 2016-08-07 18:26
The equation is `x^2  - d*y^2 = n`, or, explicitly, `x^2 - 2*y^2 = -9`.

**Comment by mzaffalon** [comment] 2016-08-26 04:19
Should this issue not be closed?

**Comment by thilinarmtb** [comment] 2016-11-07 16:10
Since the issue is resolved, I suggest closing this too.

**Closed** 2016-11-09 01:46 UTC

**Comment by thilinarmtb** [comment] 2016-11-10 18:51
Thanks !!
