### ISSUE TITLE
system om 2nd order ode

### ISSUE THREAD

**Issue by drslundberg** [sympy/sympy#22604] opened 2021-12-05 09:14 UTC
I use sympy to solve this problem. MWE:
```python
from sympy import *
import numpy as np
import matplotlib.pyplot as plt
x1,x2=symbols('x1,x2',cls=Function)
t,k1,k2,m1,m2=symbols('t k1 k2 m1 m2',real=True)
k1=1
k2=1
m1=1
m2=1
eq1=Eq(m1*diff(x1(t),t,2)+k1*x1(t)-k2*(x2(t)-x1(t)),0)  
eq2=Eq(m2*diff(x2(t),t,2)+k2*(x2(t)-x1(t)),0)  
eqs=[eq1,eq2]
IC1={x1(0):0,x1(t).diff().subs(t,0):0}
IC2={x2(0):1,x2(t).diff().subs(t,0):0}
[x1sol,x2sol]=dsolve(eqs,[x1(t),x2(t)],ics={x1(0):0,x1(t).diff().subs(t,0):0,x2(0):1,x2(t).diff().subs(t,0):0})
x1sol=simplify(x1sol)
print(x1sol)
x2sol=simplify(x2sol)
print(x2sol)
```
However, the solution for x1 and x2 doesn't fit the initial conditions. Maybe a bug in sympy? I report this as an issue.

**Comment by oscarbenjamin** [comment] 2021-12-05 13:56
There's a bug in `solve_ics`. I'm not entirely sure what the purpose of the changed code is but this example works with this change:
```diff
diff --git a/sympy/solvers/ode/ode.py b/sympy/solvers/ode/ode.py
index 1af7a455f8..c474bab4c5 100644
--- a/sympy/solvers/ode/ode.py
+++ b/sympy/solvers/ode/ode.py
@@ -770,7 +770,7 @@ def solve_ics(sols, funcs, constants, ics):
                 x0 = funcarg.variables[0]
                 variables = (x,)*len(funcarg.variables)
                 matching_func = deriv.subs(x0, x)
-            if variables not in diff_variables:
+            if True:
                 for sol in sols:
                     if sol.has(deriv.expr.func):
                         diff_sols.append(Eq(sol.lhs.diff(*variables), sol.rhs.diff(*variables)))
```
That gives:
```python
In [2]: [x1sol,x2sol]=dsolve(eqs,[x1(t),x2(t)],ics={x1(0):0,x1(t).diff().subs(t,0):0,x2(0):1,x2(t).diff().subs(t,0):0})

In [3]: x1sol
Out[3]: 
                                   ⎛       ________⎞                               ⎛       ________⎞
          ________                 ⎜√2⋅t⋅╲╱ 3 - √5 ⎟                   ________    ⎜√2⋅t⋅╲╱ √5 + 3 ⎟
        ╲╱ 3 - √5 ⋅(√10 + 5⋅√2)⋅cos⎜───────────────⎟   (-5⋅√2 + √10)⋅╲╱ √5 + 3 ⋅cos⎜───────────────⎟
                                   ⎝       2       ⎠                               ⎝       2       ⎠
x₁(t) = ──────────────────────────────────────────── + ─────────────────────────────────────────────
                             20                                              20                     

In [4]: x2sol
Out[4]: 
                    ⎛       ________⎞               ⎛       ________⎞
                    ⎜√2⋅t⋅╲╱ 3 - √5 ⎟               ⎜√2⋅t⋅╲╱ √5 + 3 ⎟
        (√5 + 5)⋅cos⎜───────────────⎟   (5 - √5)⋅cos⎜───────────────⎟
                    ⎝       2       ⎠               ⎝       2       ⎠
x₂(t) = ───────────────────────────── + ─────────────────────────────
                      10                              10  
```

**Comment by oscarbenjamin** [comment] 2021-12-05 14:00
Obviously a better change would be to remove the if:
```diff
diff --git a/sympy/solvers/ode/ode.py b/sympy/solvers/ode/ode.py
index 1af7a455f8..2814ad299a 100644
--- a/sympy/solvers/ode/ode.py
+++ b/sympy/solvers/ode/ode.py
@@ -770,10 +770,9 @@ def solve_ics(sols, funcs, constants, ics):
                 x0 = funcarg.variables[0]
                 variables = (x,)*len(funcarg.variables)
                 matching_func = deriv.subs(x0, x)
-            if variables not in diff_variables:
-                for sol in sols:
-                    if sol.has(deriv.expr.func):
-                        diff_sols.append(Eq(sol.lhs.diff(*variables), sol.rhs.diff(*variables)))
+            for sol in sols:
+                if sol.has(deriv.expr.func):
+                    diff_sols.append(Eq(sol.lhs.diff(*variables), sol.rhs.diff(*variables)))
             diff_variables.add(variables)
             S = diff_sols
         else:
```

**Comment by drslundberg** [comment] 2021-12-05 14:06
Oscar, many thanks. Could you update the sympy code? If so, tell me when I can download and update sympy/Staffan
NB MATLAB’s dsolve routine solves this example without problem

**Comment by oscarbenjamin** [comment] 2021-12-05 14:56
Well first someone would need to submit a pull request and then after that is merged the fix will be included in the next release of sympy.

Anyone is welcome to submit a pull request. Since a fix has already been identified I'm marking this as easy to fix. Someone could open a pull request including something like the diff above and also a regression test based on the example in the OP.

**Comment by drslundberg** [comment] 2021-12-05 19:53
Oscar, many thanks for your kindness , working with the fix on this example.
As I am unsure how to proceed  the process of submitting a pull request, I leave this to someone with greater experience.
Perhaps you could make this request?
Hopefully this sympy update won't take too long. My intention is to replace Matlab asap with Python in my classes.

**Comment by anutosh491** [comment] 2021-12-06 07:12
I'll do this asap . Thanks

**Closed** 2021-12-06 21:38 UTC
Labels: Easy to Fix, solvers.dsolve

**Comment by drslundberg** [comment] 2021-12-07 14:26
Oscar do you have any estimation for launching sympy ver. 1.10, where this issue is fixed?

Skickat från min iPhone

**Comment by oscarbenjamin** [comment] 2021-12-07 18:46
Not right now.
