### ISSUE TITLE
limit on Sum(sin(n).rewrite(exp), (n, 0, k)).doit() is wrong

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#9934] opened 2015-09-28 19:57 UTC
This is related to https://github.com/sympy/sympy/issues/8328, but it's a different code path so it should be a separate issue. 

```
In [16]: limit(simplify(Sum(sin(n).rewrite(exp), (n, 0, k)).doit().rewrite(sin)), k, oo)
Out[16]:
    sin(1)
─────────────
-2⋅cos(1) + 2

In [25]: limit(simplify(Sum(cos(n).rewrite(exp), (n, 0, k)).doit().rewrite(sin)), k, oo)
Out[25]: 1/2
```

According to WolframAlpha, both sums do not converge. I didn't check if the partial sums are correct, but I suspect they are and `limit` is what's wrong here.

**Comment by gxyd** [comment] 2015-09-29 01:37
```
>>> limit(cos(k + 1) - cos(k), k, oo)
0
```
I guess this should not be 0. As [wolfram](http://www.wolframalpha.com/input/?i=limit+%28-cos%28k%29+%2B+cos%28k+%2B+1%29%29+%2C+k%2C+oo) gives the result.
> I didn't check if the partial sums are correct

I guess they are correct.

**Comment by jksuom** [comment] 2015-09-30 09:26
Wolfram's result (-2 to 2) essentially says that the difference of two cosines on the real line is never less than -2 and never more than 2. Those are not even the best limits. The difference
 ```
cos(k + 1) - cos(k) = cos(k + 1/2 + 1/2) - cos(k + 1/2 - 1/2)
```
can be written
```
(cos(k + 1/2)cos(1/2) - sin(k + 1/2)sin(1/2)) - (cos(k + 1/2)cos(1/2) + sin(k + 1/2)sin(1/2))
    = -2sin(k + 1/2)sin(1/2)
```
Hence it lies between ``-2sin(1/2)`` and ``2sin(1/2)`` and has no limit as ``k -> oo``.

**Comment by asmeurer** [comment] 2015-10-01 01:32
The partial sum is just geometric, and it does indeed appear to be correct.

**Comment by gxyd** [comment] 2015-10-01 04:01
The problem is just the same as the issue #5196 . Since we have as @jksuom mentioned that
```
 (cos(k + 1/2)os(1/2) - sin(k + 1/2)sin(1/2)) - (cos(k + 1/2)cos(1/2) + sin(k + 1/2)sin(1/2))
    = -2sin(k + 1/2)sin(1/2)
```

Now I think the solution of the problem could be the introduction of a new `nAn`(different from `nan`) or some alternative name which should be similar to the `S.NaN`(which we have right now). `nAn` should be returned when we know that the result is bounded(or finite), but do not know its value. That way i think we will be able to deal with the problem of `limit(sin(x)/x, x, oo)` which is mentioned in the issue #5196 .

**Comment by asmeurer** [comment] 2015-10-01 05:49
I think these are both reasonable results:

```
In [6]: limit((cos(x + 1) - cos(x)).rewrite(exp), x, oo)
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-6-66fdd8581f62> in <module>()
----> 1 limit((cos(x + 1) - cos(x)).rewrite(exp), x, oo)

/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/series/limits.py in limit(e, z, z0, dir)
     43     """
     44
---> 45     return Limit(e, z, z0, dir).doit(deep=False)
     46
     47

/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/series/limits.py in doit(self, **hints)
    168
    169         try:
--> 170             r = gruntz(e, z, z0, dir)
    171             if r is S.NaN:
    172                 raise PoleError()

/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/series/gruntz.py in gruntz(e, z, z0, dir)
    639     r = None
    640     if z0 == oo:
--> 641         r = limitinf(e, z)
    642     elif z0 == -oo:
    643         r = limitinf(e.subs(z, -z), z)

/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/core/cache.py in wrapper(*args, **kwargs)
     91             def wrapper(*args, **kwargs):
     92                 try:
---> 93                     retval = cfunc(*args, **kwargs)
     94                 except TypeError:
     95                     retval = func(*args, **kwargs)

/Users/aaronmeurer/anaconda3/lib/python3.4/functools.py in wrapper(*args, **kwds)
    470                         hits += 1
    471                         return result
--> 472                 result = user_function(*args, **kwds)
    473                 with lock:
    474                     if key in cache:

/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/series/gruntz.py in limitinf(e, x)
    422         e = e.subs(x, p)
    423         x = p
--> 424     c0, e0 = mrv_leadterm(e, x)
    425     sig = sign(e0, x)
    426     if sig == 1:

/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/core/cache.py in wrapper(*args, **kwargs)
     91             def wrapper(*args, **kwargs):
     92                 try:
---> 93                     retval = cfunc(*args, **kwargs)
     94                 except TypeError:
     95                     retval = func(*args, **kwargs)

/Users/aaronmeurer/anaconda3/lib/python3.4/functools.py in wrapper(*args, **kwds)
    470                         hits += 1
    471                         return result
--> 472                 result = user_function(*args, **kwds)
    473                 with lock:
    474                     if key in cache:

/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/series/gruntz.py in mrv_leadterm(e, x)
    503     #
    504     w = Dummy("w", real=True, positive=True, finite=True)
--> 505     f, logw = rewrite(exps, Omega, x, w)
    506     series = calculate_series(f, w, logx=logw)
    507     return series.leadterm(w)

/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/series/gruntz.py in rewrite(e, Omega, x, wsym)
    575         sig = sign(g.args[0], x)
    576         if sig != 1 and sig != -1:
--> 577             raise NotImplementedError('Result depends on the sign of %s' % sig)
    578     if sig == 1:
    579         wsym = 1/wsym  # if g goes to oo, substitute 1/w

NotImplementedError: Result depends on the sign of I

In [7]: limit(expand_trig(cos(x + 1) - cos(x)), x, oo)
Out[7]: -cos(∞) + cos(1)⋅cos(∞) - sin(1)⋅sin(∞)
```

**Comment by jksuom** [comment] 2015-10-01 05:51
I think the liberal use of expressions like ``cos(oo)`` is part of the problem.

**Comment by jksuom** [comment] 2015-10-01 05:53
Instead, we could have something like what Wolfram gives: upper and lower limits (not necessarily always the best ones).

**Comment by jksuom** [comment] 2015-10-01 05:54
So, instead of the "limit" ``cos(oo)`` we could have ``Limits(-1, 1)``.

**Comment by gxyd** [comment] 2015-10-01 05:54
> I think the liberal use of expressions like cos(oo) is part of the problem.

I too think the same.

**Comment by gxyd** [comment] 2015-10-01 06:43
> Instead, we could have something like what Wolfram gives: upper and lower limits (not necessarily always the best ones).

But since we can not find the `codomain` of such functions. Is not using `nAn` a good way?

**Comment by jksuom** [comment] 2015-10-01 07:23
I am not quite sure I understand the meaning of ``nAn``. Would it just mean that the function or sequence is bounded? We had the deprecated attribute ``is_bounded``, but it was applied to single numbers (or infinities) as essentially a synonym of ``is_finite``. For functions and sequences it could actually be useful.

As to the "codomain", though we may not often find an easy exact description, it can still be possible to find useful upper and lower limits. So, for example, the "codomain"  of ``cos(n)`` for integers ``n`` is hard to describe explicitly (other than it is countable), but we still know that it is a subset of the interval [-1, 1]. (In fact, it is a dense subset of the interval, i.e., every subinterval contains its points.)

**Comment by gxyd** [comment] 2015-10-05 05:58
> I am not quite sure I understand the meaning of nAn

`nAn` would just be the same as `nan` but only difference that it's `is_finite=True`, hence other corresponding operations would follow similar thing. Like
```
>>> (nAn + 1).is_finite    # here (nAn + 1) is nAn
True
>>> (nan + 1).is_finite    # here (nan + 1) is nan
None
```
Also similar other operations will be followed.

Just consider the current criterion
```
>>> cos(oo).is_finite
True
>>> cos(oo).evalf().is_finite
None
```
But after making use of `nAn` the following will be followed
```
>>> cos(oo)
nAn
>>> cos(oo).is_finite
True
>>> cos(oo).evalf().is_finite
True
```

**Comment by jksuom** [comment] 2015-10-05 07:49
> nAn should be returned when we know that the result is bounded(or finite), but do not know its value.

This definition does not apply to the case of ``cos(oo)`` where we actually know that no limit value exists. Instead, we only have a set of *accumulation values*, i.e, values ``a`` such that ``lim cos(x_n) = a`` for some sequence ``(x_n)`` (of real numbers) tending to ``oo``. This *limit set* is the closed interval ``[-1, 1]``.

Therefore I think it would be more useful to express the limit of ``cos(x)`` (as ``x -> oo``) as some structure containing -1 and 1, for example ``Limits(-1, 1)``, instead of the meaningless notation ``cos(oo)``. This limit set concept seems to me more useful than ``nAn`` since it contains more information about the limit values.

**Comment by asmeurer** [comment] 2015-10-06 05:22
I think that goes back to a point from another issue that knowing that a function is bounded is more useful than knowing the exact bounds. So instead of inventing some `Limits` or `Bounds` object we could just as well use `O(1, (x, oo))` to represent this.

I'm not saying necessarily that `limit` should return an order object, I'm just making the point that if we wanted to do something like that that Order is probably the right abstraction for it.  Probably the right fix here is to make it more careful about meaningless expressions with `oo` in them like `cos(oo)` (note that that's better than just making `cos(oo)` return `nan` because other functions will still be unevaluated at `oo`, since that's the default behavior for functions that don't otherwise define an evaluation value at `oo`).

**Comment by jksuom** [comment] 2015-10-06 09:42
I agree that in many cases it would suffice to know that the limit set is bounded. However, I think that in some other cases more exact information could be useful. For example, that all accumulation values of ``cos(x) + 1`` are non-negative. (``Limits(-1, 1) + 1 = Limits(0, 2)``)

It also seems that Wolfram's result for the limit of ``cos(x + 1) - cos(x)`` is based on this type of reasoning: ``Limits(-1, 1) - Limits(-1, 1) = Limits(-2, -2)``.

**Comment by asmeurer** [comment] 2015-10-06 18:16
Maybe. At any rate, I doubt something like that is needed to fix this bug.

**Comment by jksuom** [comment] 2015-10-06 19:22
As I see it, the bug is that SymPy pretends to offer a limit when no limit exists. My thought was that ``limit`` should return something that does not look like a number in such a case.

**Comment by gxyd** [comment] 2015-10-22 10:15
> This limit set concept seems to me more useful than nAn since it contains more information about the limit values.

I agree that it would be useful to have `Limits` concept rather than `nAn`.
@asmeurer  mentioned
> At any rate, I doubt something like that is needed to fix this bug.

But rather to me it seems quite appropriate what jksuom mentioned.

**Comment by jksuom** [comment] 2015-12-19 08:43
It seems that #10051 provides a serviceable solution. I'll close this.

**Closed by jksuom** 2015-12-19 08:43 UTC
Labels: concrete, series, Wrong Result
