### ISSUE TITLE
CI checks failing due to timeout on slow 2 test

### ISSUE THREAD

**Issue by TJStienstra** [sympy/sympy#24005] opened 2022-09-02 11:21 UTC
In the PR #23982 the CI checks failed due to the slow 2 test running for too long, while this test should not have been affected in the PR. The only difference between success or failing of this test seems to be the choice of random seed. The link to the failed test is https://github.com/sympy/sympy/runs/8130779043?check_suite_focus=true

**Comment by oscarbenjamin** [comment] 2022-09-02 11:40
Can you reproduce the problem by setting the random seed?

**Comment by TJStienstra** [comment] 2022-09-02 11:55
@brocksam FYI

**Comment by TJStienstra** [comment] 2022-09-05 15:54
Tried to reproduce it using `PYTHONHASHSEED=391990152 TRAVIS_BUILD_NUMBER=true bin/test --force-colors --slow --timeout=595 --split=2/2 --seed=35447760` in a VM and it passed within the time constraints. The settings also seem to be the same:
```
=========================================================================================== test process starts ===========================================================================================
executable:         /usr/bin/python  (3.10.4-final-0) [CPython]
architecture:       64-bit
cache:              yes
ground types:       python 
numpy:              None
random seed:        35447760
hash randomization: on (PYTHONHASHSEED=391990152)
split:              2/2
```
So the theory that the problem is caused by the choice of random seed, seems less likely. I will re-trigger the CI by force pushing the last commit again and see what is the result.

**Comment by TJStienstra** [comment] 2022-09-05 20:01
After re-triggering the CI the code did pass all tests: https://github.com/sympy/sympy/runs/8193143814?check_suite_focus=true

Shall I close this issue due to failing to reproduce the error and the fact that it can be solved by re-triggering the CI?

**Comment by oscarbenjamin** [comment] 2022-09-05 21:40
Yes, I'll close this. It is probably not useful to have an open issue for something that can't be reproduced.

It could be that the failure is due to an intermittent problem in CI. It might also be a genuine SymPy problem but without any way to investigate the problem the open issue isn't useful.

We can reopen this if it happens again.

**Closed by oscarbenjamin** 2022-09-05 21:40 UTC
