### ISSUE TITLE
Matrix(1, 1) should be treated as scalar

### ISSUE THREAD

**Issue by HDembinski** [sympy/sympy#22570] opened 2021-11-30 14:38 UTC
Expected behavior: Any expression that returns a Matrix(1,1) should automatically return a scalar instead.

Current behavior: Since a Matrix(1, 1) is not converted into a scalar, some expressions fail, like
```py
x = Matrix([1, 2, 3])

1 / (x.T * x)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-bfd55195e184> in <module>
----> 1 1/(x.T * x)

TypeError: unsupported operand type(s) for /: 'int' and 'MutableDenseMatrix'
```

**Comment by oscarbenjamin** [comment] 2021-11-30 15:04
I don't think that a 1x1 matrix should behave as a scalar although maybe there should be a clearer way to convert to a scalar. In issue https://github.com/sympy/sympy/issues/21635 MatrixElement was used but `det` could also be used.

**Comment by oscarbenjamin** [comment] 2021-11-30 23:28
I think it would be better to have an explicit way to say "turn this 1x1 matrix into a scalar". Basically `det` does that but it would be confusing to use `det` in most contexts where this is needed.

**Comment by ThePauliPrinciple** [comment] 2021-12-01 09:41
When you try this with an `ImmutableMatrix` you get:
```python
/usr/local/lib/python3.7/dist-packages/sympy/matrices/expressions/matexpr.py in __rtruediv__(self, other)
    158     @call_highest_priority('__truediv__')
    159     def __rtruediv__(self, other):
--> 160         raise NotImplementedError()
    161         #return MatMul(other, Pow(self, S.NegativeOne))
```
Is there a reason why line 161 doesn't work?

**Comment by oscarbenjamin** [comment] 2021-12-02 22:42
> does dividing by a matrix mean

Usually in a mathematical context "matrix division" is not defined. Matlab provides both left and right division. In SymPy you need to explicitly say that you want the inverse and on which side it should be multiplied.

**Comment by smichr** [comment] 2021-12-03 00:47
Matrix multiplication is only defined when the inner dimensions match. A `1x1` matrix can only multiply a `1xn` but a scalar can mutliply `mxn`. If you convert it to a scalar automatically you change the semantics of what it is and can do. `randMatrix(1,3)*randMatrix(3,1)*randMatrix(3,3)` will not fail if a 1x1 is automatically made a scalar -- is that the right thing to do? @sylee957, do you have any input here?

**Comment by sylee957** [comment] 2021-12-03 10:46
I have seen in many texts that `x.T * x` could have confusing meaning between dot product of vectors and matrix product, but usually it is better to be distinguished.
I think that the correct solution would be using `DotProduct(x, x)`.
Also, `x.T * A * x` often means some dot product than matrix multiplication, but I think that it can also use `DotProduct(x, A*x)`.

**Comment by ThePauliPrinciple** [comment] 2021-12-03 11:32
In python we could distinguish dot product vs matrix multiplication with `*` vs `@`.

**Comment by MishraAditya12126** [comment] 2021-12-08 09:17
i have actually a very easy way to convert it into a scalar and i love to work on this issue 
please allow me to do

**Comment by oscarbenjamin** [comment] 2021-12-08 12:34
I don't think that a 1x1 matrix should be treated implicitly as a scalar. That's an abuse of notation that can be okay in an informal context but a computer algebra system cannot afford to be loose about things like this: it needs to know unambiguously if an object is a matrix or not.

**Comment by MishraAditya12126** [comment] 2021-12-08 12:57
but it will be necessary when we want to explicitly convert our matrix in the form of Equations
like we do in quadratic form of matrix

**Comment by MishraAditya12126** [comment] 2021-12-08 13:00
And i have a way which do not disrespect the notation and still works

**Comment by ThePauliPrinciple** [comment] 2021-12-08 13:03
You can convert it explicitly with `Matrix([[1]])[0,0]`. You can also opt to subclass `Matrix` and change it to behave the way that suits your needs. It should however not be the default behaviour in `SymPy` as explained multiple times in the posts above.

**Comment by MishraAditya12126** [comment] 2021-12-08 13:10
ohk , thanks for explaining

**Comment by asmeurer** [comment] 2021-12-08 23:59
This issue is a duplicate of https://github.com/sympy/sympy/issues/9190. To summarize my views from that issue, I like the current behavior because it keeps a clean type separate between matrices and scalars. That's especially useful since SymPy uses `*` to mean matrix multiplication. Being vague about types leads to situations where you become unable to represent things you want to represent, or unable to detect type errors that you would otherwise want to detect. 

Closing this because it's a duplicate. Please continue the discussion on the other issue.

**Closed by asmeurer** 2021-12-08 23:59 UTC
Labels: matrices
