### ISSUE TITLE
Potential bug in orientation of sympy.physics.mechanics.ReferenceFrame objects

### ISSUE THREAD

**Issue by SavinaRoja** [sympy/sympy#2729] opened 2014-01-03 22:18 UTC
I was doing some experimentation with sympy.physics.mechanics and ran into some unexpected behavior that might be considered a bug. I demonstrated the possible problem in a notebook which can be seen here:

https://github.com/SavinaRoja/biochem-notebooks/blob/master/ReferenceFrame%20Orientation%20Test.ipynb

When a ReferenceFrame is initially oriented to another, it is associatively able to determine its DCM to other ReferenceFrames. However if its orientation is ever redefined within the network of oriented reference frames, it does not update its DCM for each reference frame, but only the one to which it was explicitly oriented.

Perhaps this is behaving as intended (not a bug) for reasons I am not aware of.

**Comment by moorepants** [comment] 2015-06-05 04:58
Closing this as it is intended behavior.

**Closed by moorepants** 2015-06-05 04:58 UTC
Labels: physics.mechanics
