### ISSUE TITLE
collect function bug

### ISSUE THREAD

**Issue by ferymi6041** [sympy/sympy#26676] opened 2024-06-06 01:24 UTC
if you run the code below in python, it can't collect the very simple expr with mv-derivative.

from sympy import Symbol, symbols, collect, expand
x = Symbol("x", real = True)
theta = Symbol("theta", real = True)
t = Symbol("t", real = True)
u = symbols('u', real = True, cls=Function)(x, theta, t)

expr = u.diff(x, x, t) * x + u.diff(x, x, t) * t
expr = collect(expand(expr), u.diff(x, x, t))

**Comment by smichr** [comment] 2024-06-06 03:03
What did you get? After running this code `expr` is `(x+t)*u.diff(x,x,t)` and that is what I would expect.

**Comment by ferymi6041** [comment] 2024-06-06 17:04
but, if you run the code below you get the error this time:

from sympy import Symbol, symbols, collect, expand, Function
x = Symbol("x", real = True)
theta = Symbol("theta", real = True)
t = Symbol("t", real = True)
u = symbols('u', real = True, cls = Function)(x, theta, t)
v = symbols('v', real = True, cls = Function)(x, theta, t)

expr = u.diff(x, x, t) * x + u.diff(x, x, t) * t + x * v.diff(x, t)

expr = collect(expand(expr), u.diff(x, x, t))
print(expr)



when you have two multi-variable like u and v or more in expr collect can't be done but mathematically it should do it very easily

**Comment by oscarbenjamin** [comment] 2024-06-06 18:50
Okay, I can reproduce that now.

**Comment by oscarbenjamin** [comment] 2024-06-06 18:51
Closing as duplicate of gh-26681

**Closed by oscarbenjamin** 2024-06-06 18:51 UTC
