### ISSUE TITLE
limit fails with "maximum recursion depth exceeded" / Python crash

### ISSUE THREAD

**Issue by x-or** [sympy/sympy#9449] opened 2015-05-31 09:50 UTC
SymPy 0.7.6 code:

``` Python
import sys
import sympy as sy

#sys.setrecursionlimit(100000)

x, eps = sy.symbols('x eps', real=True)
e = (sy.Abs(eps + x)-sy.Abs(eps - x))/(2*eps)
print e
print e.limit(eps, 0)
```

fails with exception:

```
Traceback (most recent call last):
  File "issue.py", line 9, in <module>
    print e.limit(eps, 0)
  File "C:\Python27\lib\site-packages\sympy\core\expr.py", line 2662, in limit
    return limit(self, x, xlim, dir)
  File "C:\Python27\lib\site-packages\sympy\series\limits.py", line 42, in limit
    return Limit(e, z, z0, dir).doit(deep=False)
  File "C:\Python27\lib\site-packages\sympy\series\limits.py", line 157, in doit
    r = gruntz(e, z, z0, dir)
  File "C:\Python27\lib\site-packages\sympy\series\gruntz.py", line 651, in gruntz
    r = limitinf(e0, z)
  File "C:\Python27\lib\site-packages\sympy\core\cache.py", line 91, in wrapper
    retval = cfunc(*args, **kwargs)
  File "C:\Python27\lib\site-packages\sympy\core\compatibility.py", line 872, in wrapper
    result = user_function(*args, **kwds)
  File "C:\Python27\lib\site-packages\sympy\series\gruntz.py", line 424, in limitinf
    c0, e0 = mrv_leadterm(e, x)
  File "C:\Python27\lib\site-packages\sympy\core\cache.py", line 91, in wrapper
    retval = cfunc(*args, **kwargs)
  File "C:\Python27\lib\site-packages\sympy\core\compatibility.py", line 872, in wrapper
    result = user_function(*args, **kwds)
  File "C:\Python27\lib\site-packages\sympy\series\gruntz.py", line 507, in mrv_leadterm
    return series.leadterm(w)

  ... skipped ....

  File "C:\Python27\lib\site-packages\sympy\core\basic.py", line 396, in __str__
    return sstr(self, order=None)
  File "C:\Python27\lib\site-packages\sympy\printing\str.py", line 731, in sstr
    s = p.doprint(expr)
  File "C:\Python27\lib\site-packages\sympy\printing\printer.py", line 233, in doprint
    return self._str(self._print(expr))
  File "C:\Python27\lib\site-packages\sympy\printing\printer.py", line 257, in _print
    return getattr(self, printmethod)(expr, *args, **kwargs)
  File "C:\Python27\lib\site-packages\sympy\printing\str.py", line 52, in _print_Add
    terms = self._as_ordered_terms(expr, order=order)
  File "C:\Python27\lib\site-packages\sympy\printing\printer.py", line 271, in _as_ordered_terms
    return expr.as_ordered_terms(order=order)
  File "C:\Python27\lib\site-packages\sympy\core\expr.py", line 853, in as_ordered_terms
    terms, gens = self.as_terms()
  File "C:\Python27\lib\site-packages\sympy\core\expr.py", line 884, in as_terms
    coeff = complex(coeff)
  File "C:\Python27\lib\site-packages\sympy\core\expr.py", line 229, in __complex__
    re, im = result.as_real_imag()
  File "C:\Python27\lib\site-packages\sympy\core\expr.py", line 1614, in as_real_imag
    return (C.re(self), C.im(self))
  File "C:\Python27\lib\site-packages\sympy\core\cache.py", line 91, in wrapper
    retval = cfunc(*args, **kwargs)
  File "C:\Python27\lib\site-packages\sympy\core\compatibility.py", line 854, in wrapper
    key = make_key(args, kwds, typed) if kwds or typed else args
  File "C:\Python27\lib\site-packages\sympy\core\compatibility.py", line 786, in _make_key
    return _HashedSeq(key)
  File "C:\Python27\lib\site-packages\sympy\core\compatibility.py", line 764, in __init__
    self.hashvalue = hash(tup)
  File "C:\Python27\lib\site-packages\sympy\core\numbers.py", line 947, in __hash__
    return super(Float, self).__hash__()
  File "C:\Python27\lib\site-packages\sympy\core\numbers.py", line 413, in __hash__
    return super(Number, self).__hash__()
  File "C:\Python27\lib\site-packages\sympy\core\basic.py", line 107, in __hash__
    h = hash((type(self).__name__,) + self._hashable_content())
RuntimeError: maximum recursion depth exceeded while calling a Python object
```

Uncomment 'setrecursionlimit' line causes Python's crash.

Python 2.7.3 (32bit), Windows 7 x64.

**Comment by sachin-4099** [comment] 2020-05-29 19:57
On the current master it gives: `sign(x)`.
Not sure whether this is the correct answer, but no `RecursionError` perhaps now.

**Comment by gschintgen** [comment] 2020-05-29 20:45
I confirm the `sign(x)` result:
```
In [38]: var('x eps', real=True)
Out[38]: (x, eps)

In [39]: limit((abs(eps+x)-abs(eps-x))/(2*eps), eps, 0)
Out[39]: sign(x)
```
As far as I can tell this result is correct for `x>0`, for `x<0` and for `x==0`, if `sign(x)` is taken to be +1 / -1 / 0. So I'd say this issue only needs a test in order to be closed.

**Comment by 0sidharth** [comment] 2020-12-28 05:03
On current `master`, the `RecursionError` is back

**Comment by oscarbenjamin** [comment] 2020-12-28 10:58
You could use `git bisect` to identify the commit in which it started working and the commit where it broke again.

**Comment by 0sidharth** [comment] 2020-12-29 03:36
What I found is that in commit 5dc58b715362d9332078fd7560b322d7a7eeddd1 , the limit being output has change from `sign(x)` to 
`Limit((-Abs(eps - x) + Abs(eps + x))/(2*eps), eps, 0)`. Is this a desired change, as going over the PR in which this change was introduced, there are other instances in the tests where limits being evaluated to values previously have been changed to just `Limit(...)`.

Regarding the `RecursionError`, `git bisect` returned 14a7d0045f64a29a384ff633e53b1b36e3a96a2d as the first commit where this issue was introduced and I have cross-checked it by comparing results with its previous commit.

I will try to find a fix now.

**Comment by 0sidharth** [comment] 2021-01-01 11:43
If I add `RecursionError` to the `except` statement here, https://github.com/sympy/sympy/blob/92f31c3ff460bddc936b3b39c6d4d9d5ec0c8ece/sympy/series/limits.py#L332 the limit is correctly computed. I believe this is not the method to go about for fixing this issue as I do not see `RecursionError`s being caught anywhere else in the codebase but I am not sure why it is so. Can anyone tell me if they shouldn't be caught and why?

**Comment by sidhu1012** [comment] 2021-01-01 12:04
I think the problem here is with `Gruntz Algo`. The limit is being evaluated correctly by `Heuristics` .

**Comment by sidhu1012** [comment] 2021-01-01 12:06
As per documentation`Heuristics` should be called first as it's fast but the is implied reverse in codebase

A fix might be to call `Heuristics` first and if it fails to compute limit then call `Gruntz`.

**Comment by 0sidharth** [comment] 2021-01-01 12:25
> I think the problem here is with Gruntz Algo

I think so too
> A fix might be to call Heuristics first and if it fails to compute limit then call Gruntz.

I had noticed this in the docs and I had tried simply interchanging `heuristics` and `gruntz` keywords in the try-except block mentioned above, but that led to even more errors and no fixes really. I will look into this again and update if I discover anything new.

**Comment by sidhu1012** [comment] 2021-01-01 12:28
> I had noticed this in the docs and I had tried simply interchanging `heuristics` and `gruntz` keywords in the try-except block mentioned above, but that led to even more errors and no fixes really. I will look into this again and update if I discover anything new.

This isn't the right way , first call `heuristics`, if it fails then it should have `try-except` block for `Gruntz` which should return the unevaluated limit in case of  error.

**Comment by 0sidharth** [comment] 2021-01-01 13:27
Sorry, the issue is not completely fixed by catching `RecursionError` and I also did not completely explain what I tested in the last comment.

So I had tried both ways, the one I outlined and the one @sidhu1012 outlined above. The limit being returned when I catch the `RecursionError` in the current code is simply the unevaluated limit `Limit((-Abs(eps - x) + Abs(eps + x))/(2*eps), eps, 0)`. So I think it can be concluded that a `PoleError` or `ValueError` was being thrown earlier which is not being thrown after the changes in 14a7d00.

Additionally, calling `heuristics` before `gruntz` leads to several other errors like `limit(exp(-x*y), x, oo)`  being evaluated to `exp(-oo*sign(y))` whereas it should raise a `NotImplementedError` (refer `issue_5436` in `test_limits.py`), and even some incorrectly evaluated values from other limits. Now I have no idea whether the documentation, which says `heuristics` should be called before `gruntz`, is wrong or if there is some issue in `heuristics`, or most probably it is an issue with my understanding of the code. Thanks to the discussion the issue has become clearer to me.

**Comment by 0sidharth** [comment] 2021-01-06 15:03
The PR above fixes the `RecursionError`, and the limit currently being output is the unevaluated limit. Is this fine or is it preferable to finally evaluate it to `sign(x)`? If we consider the possibility of x to be imaginary (why not?) https://www.wolframalpha.com/input/?i=lim+%28Abs%28eps+%2B+x%29-Abs%28eps+-+x%29%29%2F%282*eps%29+as+eps-%3E+0 gives a different answer.

**Closed** 2021-02-16 16:22 UTC
Labels: Easy to Fix, functions.elementary.piecewise, limits, series
