### ISSUE TITLE
solveset cannot solve an equation which invert_real can solve

### ISSUE THREAD

**Issue by ducminh-phan** [sympy/sympy#13084] opened 2017-08-03 05:02 UTC
When I tried to solve the equation `sin(2*x + 3) = 1/2` using `solveset`, `TypeError` was raised:
```
>>> eq = sin(2*x + 3) - Rational(1, 2)
>>> solveset_real(eq, x)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\aleph\Python2_with_sympy\lib\site-packages\sympy\solvers\solveset.py", line 925, in solveset_real
    return solveset(f, symbol, S.Reals)
  File "C:\Users\aleph\Python2_with_sympy\lib\site-packages\sympy\solvers\solveset.py", line 921, in solveset
    return _solveset(f, symbol, domain, _check=True)
  File "C:\Users\aleph\Python2_with_sympy\lib\site-packages\sympy\solvers\solveset.py", line 698, in _solveset
    result = _solve_trig(f, symbol, domain)
  File "C:\Users\aleph\Python2_with_sympy\lib\site-packages\sympy\solvers\solveset.py", line 410, in _solve_trig
    solns = solveset_complex(g, y) - solveset_complex(h, y)
  File "C:\Users\aleph\Python2_with_sympy\lib\site-packages\sympy\solvers\solveset.py", line 929, in solveset_complex
    return solveset(f, symbol, S.Complexes)
  File "C:\Users\aleph\Python2_with_sympy\lib\site-packages\sympy\solvers\solveset.py", line 921, in solveset
    return _solveset(f, symbol, domain, _check=True)
  File "C:\Users\aleph\Python2_with_sympy\lib\site-packages\sympy\solvers\solveset.py", line 738, in _solveset
    result += _solve_as_rational(equation, symbol, domain)
  File "C:\Users\aleph\Python2_with_sympy\lib\site-packages\sympy\solvers\solveset.py", line 394, in _solve_as_rational
    return valid_solns - invalid_solns
  File "C:\Users\aleph\Python2_with_sympy\lib\site-packages\sympy\sets\sets.py", line 576, in __sub__
    return Complement(self, other)
  File "C:\Users\aleph\Python2_with_sympy\lib\site-packages\sympy\sets\sets.py", line 1705, in __new__
    return Complement.reduce(a, b)
  File "C:\Users\aleph\Python2_with_sympy\lib\site-packages\sympy\sets\sets.py", line 1715, in reduce
    if B == S.UniversalSet or A.is_subset(B):
  File "C:\Users\aleph\Python2_with_sympy\lib\site-packages\sympy\sets\sets.py", line 330, in is_subset
    return self.intersect(other) == self
  File "C:\Users\aleph\Python2_with_sympy\lib\site-packages\sympy\sets\sets.py", line 108, in intersect
    return Intersection(self, other)
  File "C:\Users\aleph\Python2_with_sympy\lib\site-packages\sympy\sets\sets.py", line 1501, in __new__
    return Intersection.reduce(args)
  File "C:\Users\aleph\Python2_with_sympy\lib\site-packages\sympy\sets\sets.py", line 1625, in reduce
    rv = Intersection._handle_finite_sets(args)
  File "C:\Users\aleph\Python2_with_sympy\lib\site-packages\sympy\sets\sets.py", line 1560, in _handle_finite_sets
    for o in fs_args + other)
  File "C:\Users\aleph\Python2_with_sympy\lib\site-packages\sympy\core\logic.py", line 139, in fuzzy_and
    for ai in args:
  File "C:\Users\aleph\Python2_with_sympy\lib\site-packages\sympy\sets\sets.py", line 1560, in <genexpr>
    for o in fs_args + other)
  File "C:\Users\aleph\Python2_with_sympy\lib\site-packages\sympy\sets\conditionset.py", line 60, in contains
    return And(Lambda(self.sym, self.condition)(other), self.base_set.contains(other))
  File "C:\Users\aleph\Python2_with_sympy\lib\site-packages\sympy\core\function.py", line 1515, in __new__
    raise TypeError('variable is not a symbol: %s' % i)
TypeError: variable is not a symbol: -_y**4*I*exp(6*I) - _y**2*exp(3*I) + I
```

However, the above equation can be solved using `invert_real`:
```
>>> invert_real(eq, 0, x)
(x, ImageSet(Lambda(_n, (-1)**_n*pi/12 + _n*pi/2 - 3/2), S.Integers))
```

Maybe we should try to use invert for equations with a single occurrence of the variable?

**Comment by Yathartha22** [comment] 2017-08-04 07:54
I think the problem is that after converting into `exp` by `_solve_trig`, `_solve_rational` tries to solve it and when evaluating `valid_solns - invalid_solns`, the result is a `CondtionSet` for the former and `FiniteSet` for the latter which gives the `TypeError`.

**Comment by Shekharrajak** [comment] 2017-08-04 10:27
Okay! solveset is not able to solve it right now. So it must have returned `ConditionSet`. But one can try to fix this bug with following approach (with solveset) : 

```
In [43]: from sympy.solvers.decompogen import decompogen

In [44]: eq = sin(2*x + 3) - Rational(1,2)

In [45]: decom = decompogen(eq, x)

In [46]: decom
Out[46]: [x - 1/2, sin(x), 2⋅x + 3]

In [47]: soln = [0]

In [48]: for dec in decom:
    ...:     soln = solve( dec - soln[0] ,x) 
    ...: print soln
    ...:    
[-3/2 + pi/12] 
```
Using solveset we must get ImageSet as the solution.

**Comment by Yathartha22** [comment] 2017-08-04 12:34
@Shekharrajak we can also use `solve_decomposition`, that probably does the work that you said.
```
>>> from sympy.solvers.solveset import solve_decomposition
>>> f = sin(2*x + 3) - Rational(1,2)
>>> pprint(solve_decomposition(f, x, S.Reals))
⎧π⋅(12⋅n + 5)   3        ⎫   ⎧π⋅(12⋅n + 1)   3        ⎫
⎨──────────── - ─ | n ∊ ℤ⎬ ∪ ⎨──────────── - ─ | n ∊ ℤ⎬
⎩     12        2        ⎭   ⎩     12        2        ⎭

```

**Comment by Shekharrajak** [comment] 2017-08-04 12:44
Yes!

**Comment by Yathartha22** [comment] 2017-08-04 12:54
Also, I think this should be done while implementing `transolve`

**Comment by oscarbenjamin** [comment] 2019-03-05 02:28
Now it gives the empty set:
```julia
In [17]: eq = sin(2*x + 3) - Rational(1, 2)                                                                                                                   

In [18]: solveset_real(eq, x)                                                                                                                                 
Out[18]: ∅
```

**Comment by gschintgen** [comment] 2019-12-15 19:45
Current master together with #17838 returns the correct solutions:
```
In [3]: simplify(solveset(sin(2*x + 3) - Rational(1, 2), x))
Out[3]:
⎧      3   17⋅π        ⎫   ⎧          ⎛          1          ⎞            ⎫
⎨n⋅π - ─ + ──── | n ∊ ℤ⎬ ∪ ⎪n⋅π - atan⎜─────────────────────⎟ + π | n ∊ ℤ⎪
⎩      2    12         ⎭   ⎪          ⎜   ⎛    ⎛    1     ⎞⎞⎟            ⎪
                           ⎪          ⎜   ⎜atan⎜──────────⎟⎟⎟            ⎪
                           ⎨          ⎜   ⎜    ⎜   ⎛π    ⎞⎟⎟⎟            ⎬
                           ⎪          ⎜   ⎜    ⎜tan⎜─ + 3⎟⎟⎟⎟            ⎪
                           ⎪          ⎜   ⎜    ⎝   ⎝3    ⎠⎠⎟⎟            ⎪
                           ⎪          ⎜tan⎜────────────────⎟⎟            ⎪
                           ⎩          ⎝   ⎝       2        ⎠⎠            ⎭
In [12]: a = -atan(1/tan(atan(1/tan(pi/3 + 3))/2)) + pi

In [13]: nsimplify(a, [pi])
Out[13]:
  3   13⋅π
- ─ + ────
  2    12
```
*but*, obviously, the used algorithm is completely inadequate for this type of equation. (Especially given the unsimplified result which I didn't reproduce...). So this is just to document current progress.

**Comment by MaqOwais** [comment] 2021-04-09 11:21
I think the current condition is improved without #17838 .

```
>>> bp = solveset(sin(2*x + 3) - Rational(1, 2), x)
Union(
ImageSet(Lambda(_n, -I*(I*(2*_n*pi - pi + atan((cos(3) - sqrt(3)*sin(3))/(sqrt(3)*cos(3) + sin(3)))) + log(sqrt(sin(3)**2 + cos(3)**2)))/2), Integers), 
ImageSet(Lambda(_n, -I*(I*(2*_n*pi + atan((cos(3) + sqrt(3)*sin(3))/(sin(3) - sqrt(3)*cos(3)))) + log(sqrt(sin(3)**2 + cos(3)**2)))/2), Integers)
)

>>> pprint(bp)
⎧   ⎛                                          ⎛   ___________________⎞⎞  │      ⎫   ⎧   ⎛                                              ⎛   ___________________⎞⎞  
⎪   ⎜  ⎛            ⎛cos(3) + √3⋅sin(3)⎞⎞      ⎜  ╱    2         2    ⎟⎟  │      ⎪   ⎪   ⎜  ⎛                ⎛cos(3) - √3⋅sin(3)⎞⎞      ⎜  ╱    2         2    ⎟⎟  
 ⎪-ⅈ⋅⎜ⅈ⋅⎜2⋅n⋅π + atan⎜──────────────────⎟⎟ + log⎝╲╱  sin (3) + cos (3) ⎠⎟  │      ⎪   ⎪-ⅈ⋅⎜ⅈ⋅⎜2⋅n⋅π - π + atan⎜──────────────────⎟⎟ + log⎝╲╱  sin (3) + cos (3) ⎠⎟  
⎨   ⎝  ⎝            ⎝sin(3) - √3⋅cos(3)⎠⎠                              ⎠  │      ⎬   ⎨   ⎝  ⎝                ⎝√3⋅cos(3) + sin(3)⎠⎠                              ⎠  
⎪──────────────────────────────────────────────────────────────────────── │ n ∊ ℤ⎪ ∪ ⎪──────────────────────────────────────────────────────────────────────────── 
⎪                                   2                                     │      ⎪   ⎪                                     2                                       
⎩                                                                         │      ⎭   ⎩                                                                             

│      ⎫
│      ⎪
│      ⎪
│      ⎬
│ n ∊ ℤ⎪
│      ⎪
│      ⎭




>>> br = simplify(solveset(sin(2*x + 3) - Rational(1, 2), x))

>>> pprint(br)
                           ⎧          ⎛    1     ⎞     │      ⎫
                           ⎪      atan⎜──────────⎟     │      ⎪
                           ⎪          ⎜   ⎛π    ⎞⎟     │      ⎪
                           ⎨          ⎜tan⎜─ + 3⎟⎟     │      ⎬
⎧      3   17⋅π │      ⎫   ⎪          ⎝   ⎝3    ⎠⎠   π │      ⎪
⎨n⋅π - ─ + ──── │ n ∊ ℤ⎬ ∪ ⎪n⋅π + ──────────────── + ─ │ n ∊ ℤ⎪
⎩      2    12  │      ⎭   ⎩             2           2 │      ⎭
>>> br
Union(ImageSet(Lambda(_n, _n*pi + atan(1/tan(pi/3 + 3))/2 + pi/2), Integers), ImageSet(Lambda(_n, _n*pi - 3/2 + 17*pi/12), Integers))

```
And 
```
>>> a = -atan(1/tan(atan(1/tan(pi/3 + 3))/2)) + pi
>>> nsimplify(a, [pi])
-3/2 + 13*pi/12
```
So I think that this issue should be closed .

**Comment by smichr** [comment] 2021-04-09 17:19
closing as a duplicate of issues addressed by recent PR; if someone wants to open an issue regarding simplified solutions they can.

**Closed by smichr** 2021-04-09 17:19 UTC
Labels: solvers.solveset
