### ISSUE TITLE
Definite integral variant fails

### ISSUE THREAD

**Issue by JanGoos-Engibex** [sympy/sympy#27231] opened 2024-11-07 20:12 UTC
The live editor (version 1.11.1) computes the following integral correctly
```
import sympy
x = sympy.symbols("x", real=True)
sympy.integrate(sympy.sqrt(1 - x**2),(x,-1/2,1)).evalf()
```
to 1.26370390214271.

However, the equivalent integral
```
sympy.integrate(sympy.sqrt(1 - 0.5625*(x + 0.333333333333333)**2),(x,-1,1))
```
evaluates to -1.8420660794913 10^15

My local sympy (version 1.12) has the same problem. https://github.com/sympy/sympy/issues/27050 provides a workaround by setting heurisch to False. The problem seems similar, but this integrand seems simpler.
```
sympy.integrate(sympy.sqrt(1 - 0.5625*(x + 0.333333333333333)**2),(x,-1,1),heurisch=False)
```

**Comment by oscarbenjamin** [comment] 2024-11-07 20:48
This particular case seems to have been fixed by the recent commit 4f24d1179ab09a6191a6d2a87058363f32fd5ab6 from gh-27195.

> However, the equivalent integral

Are you sure that these are equivalent? This is what I get with current master for symbolic and numeric evaluation of the two integrals:
```python
In [15]: i1 = Integral(sqrt(1 - x**2),(x,-1/2,1))

In [16]: i2 = Integral(sqrt(1 - 0.5625*(x + 0.333333333333333)**2),(x,-1,1))

In [17]: i1.doit().evalf()
Out[17]: 1.26370390214271

In [18]: i1.evalf()
Out[18]: 1.26370390214271

In [19]: i2.doit().evalf()
Out[19]: 1.68493853331720

In [20]: i2.evalf()
Out[20]: 1.68493853619028

In [21]: i1
Out[21]: 
 1                 
 ⌠                 
 ⎮      ________   
 ⎮     ╱      2    
 ⎮   ╲╱  1 - x   dx
 ⌡                 
-0.5               

In [22]: i2
Out[22]: 
1                                             
⌠                                             
⎮     _____________________________________   
⎮    ╱                                   2    
⎮  ╲╱  1 - 0.5625⋅(x + 0.333333333333333)   dx
⌡                                             
-1  
```
The integral `i2` has the sort of expression with a float extracted that was changed in 4f24d1179ab09a6191a6d2a87058363f32fd5ab6. I don't see how that would cause the integral to be evaluated correctly though so presumably there is some bug elsewhere but just it cannot be reproduced for this example after the commit.

**Comment by oscarbenjamin** [comment] 2024-11-07 20:56
With sympy 1.13 the integral is non-deterministic:
```python
In [1]: i2 = Integral(sqrt(1 - 0.5625*(x + 0.333333333333333)**2),(x,-1,1))

In [2]: i2.doit()
Out[2]: -74309154804490.7

In [3]: i2.doit()
Out[3]: 1.09576032168856e+15

In [4]: i2.doit()
Out[4]: -1.20722405389529e+15

In [5]: i2.doit()
Out[5]: 1.09576032168856e+15

In [6]: i2.doit()
Out[6]: -1.20722405389529e+15
```
It works with heurisch=False though:
```python
In [14]: i2.doit(heurisch=False)
Out[14]: 1.68493853331720

In [15]: i2.doit(heurisch=False)
Out[15]: 1.68493853331720
```
So somehow the exact form of expression triggers a bug that results in non-deterministic output from heurisch. The expressions of magnitude 1e15 look like a divide by approximate zero.

The difference with sympy master is that now heurisch fails for this integral so another method is used by default:
```python
In [5]: i2.doit(heurisch=True)
Out[5]: 
                  1                                
                  ⌠                                
                  ⎮     ________________________   
                  ⎮    ╱        2                  
0.968245836551854⋅⎮  ╲╱  - 0.6⋅x  - 0.4⋅x + 1.0  dx
                  ⌡                                
                  -1  
```
Probably heurisch should convert float to rational somewhere e.g. when solving some system of linear equations. Actually it seems that heurisch cannot do this integral with exact rational numbers:
```python
In [11]: nsimplify(i2).doit(heurisch=True)
Out[11]: 
   1                          
   ⌠                          
   ⎮     __________________   
   ⎮    ╱      2              
√3⋅⎮  ╲╱  - 3⋅x  - 2⋅x + 5  dx
   ⌡                          
   -1                         
──────────────────────────────
              4   
```
It should therefore fail with floats as well. I think that some solution of a linear system was misdetected because of rounding errors somewhere.

**Comment by JanGoos-Engibex** [comment] 2024-11-07 21:14
Wow, thanks for the extremely rapid response.
You're correct, seems like the integral variants are not equivalent. Just very similar.
So in conclusion, heurich=False (independent of the sympy version) solves the problem, but it makes it slower to solve.

**Comment by oscarbenjamin** [comment] 2024-11-07 21:32
I think that the conclusion is that heurisch doesn't handle floats very well but it works a bit better after 4f24d1179ab09a6191a6d2a87058363f32fd5ab6. A proper fix for heurisch would under appropriate conditions convert float to rational for solving a system of linear equations.

For now though I think that this issue could be closed if a test was added for the integral that is now fixed:
```python
In [1]: i2 = Integral(sqrt(1 - 0.5625*(x + 0.333333333333333)**2),(x,-1,1))

In [2]: i2.doit()
Out[2]: 1.68493853331720

In [3]: nsimplify(i2).doit()
Out[3]: 
√3   4⋅π
── + ───
6     9 

In [4]: _.n()
Out[4]: 1.68493853619028
```

**Comment by vprayag2005** [comment] 2024-11-08 01:50
@oscarbenjamin @asmeurer 
Hi SymPy Team,

My name is Prayag, and I’m new to open-source contributions, but I’m very excited to learn and contribute to the SymPy project. I came across the issue related to the failure in the definite integral variant, and it caught my interest. I’d love to work on this issue and would appreciate any guidance you could provide.

Could you please explain a bit more about the issue and suggest any initial steps I could take to get started? I’d also be grateful for any tips on navigating SymPy’s codebase to find the relevant parts of the code.

Thank you for your time and consideration, and I look forward to contributing to the project!

Best regards,
Prayag

**Comment by vprayag2005** [comment] 2024-11-09 07:32
Hi @oscarbenjamin, @JanGoos-Engibex,

I'm a beginner in open-source contributions and excited to get involved with SymPy. This issue on the definite integral failure caught my interest, and I'd like to work on it. Could you provide more details on the problem and suggest any initial steps to get started? Any tips on navigating the codebase would also be helpful.

Thanks!

**Comment by oscarbenjamin** [comment] 2024-11-09 11:27
This issue can be closed if a test is added for the integral that previously did not work but now does. The test can be added in `sympy/integrals/tests/test_integrals.py`.

**Comment by vprayag2005** [comment] 2024-11-11 05:52
Hello, I’ve added a test for issue #27231, and I’m preparing to submit it. I understand I need to add my name and email to the AUTHORS file for my first contribution. Could you please confirm if there are any other steps I should follow for submitting my test, or if there’s any specific review process for new contributors? Thank you!

**Closed** 2024-11-14 14:28 UTC
Labels: Easy to Fix, integrals, floats, integrals.definite, Add test to close
