### ISSUE TITLE
Symbolic integral of positive functions return 0

### ISSUE THREAD

**Issue by caiodallecio** [sympy/sympy#12332] opened 2017-03-16 21:04 UTC
The function is `p0**2/(q1**2 + s**2)` `p0` and `q1` was definied as Real. The integral of this function on s returns 0 the result should be `(p0^2 tan^(-1)(s/q1))/q1`

**Comment by jksuom** [comment] 2017-03-17 09:43
Duplicate of #12050.

**Comment by oscarbenjamin** [comment] 2019-03-12 00:47
This seems to be fixed now on master:
```julia
In [28]: p0, q0, q1, s = symbols('p0 q0 q1 s', real=True)                                                                                                     

In [29]: integrate(p0**2/(q1**2 + s**2), s)                                                                                                                   
Out[29]: 
  2     ⎛s ⎞
p₀ ⋅atan⎜──⎟
        ⎝q₁⎠
────────────
     q₁     

```

**Closed** 2019-03-12 00:47 UTC
Labels: integrals
