### ISSUE TITLE
sympy.tensor.Idx used as summed variable in Sum raises an exception

### ISSUE THREAD

**Issue by Upabjojr** [sympy/sympy#9635] opened 2015-07-09 05:49 UTC
To reproduce this bug, type:

```
In [1]: from sympy.tensor import Indexed, IndexedBase, Idx

In [2]: i = Idx('i', range=(1,4))

In [3]: A = IndexedBase('A')
```

This command raises an exception. One would instead expect a _Sum_ object which can be further expanded into _A[1]+A[2]+A[3]+A[4]_, but:
```
In [4]: Sum(A[i], i)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-e1457b871b92> in <module>()
----> 1 Sum (A [i ],i )

/usr/local/lib/python3.4/dist-packages/sympy/concrete/summations.py in __new__(cls, function, *symbols, **assumptions)
    138 
    139     def __new__(cls, function, *symbols, **assumptions):
--> 140         obj = AddWithLimits.__new__(cls, function, *symbols, **assumptions)
    141         if not hasattr(obj, 'limits'):
    142             return obj

/usr/local/lib/python3.4/dist-packages/sympy/concrete/expr_with_limits.py in __new__(cls, function, *symbols, **assumptions)
    351 
    352         if symbols:
--> 353             limits, orientation = _process_limits(*symbols)
    354         else:
    355             # symbol not provided -- we can still try to compute a general form

/usr/local/lib/python3.4/dist-packages/sympy/concrete/expr_with_limits.py in _process_limits(*symbols)
     55                     continue
     56 
---> 57         raise ValueError('Invalid limits given: %s' % str(symbols))
     58 
     59     return limits, orientation

ValueError: Invalid limits given: (i,)
```

**Comment by leosartaj** [comment] 2015-07-09 12:24
Duplicate of #9594

**Comment by leosartaj** [comment] 2015-07-09 12:25
#9599 aims to solve the issue.

**Comment by bjodah** [comment] 2015-07-19 12:53
Since #9599 was merged we can now write:

```
Sum(A[i], (i, i.lower, i.upper))
```

where the summation object may be expanded using its `doit()` method.

Do we want:
```
Sum(A[i], i)
```
to work too (as shorthand version of the previous expression)?
If so:
- I guess we should have a try/except clause in Sum where attributes `lower` and `upper` are looked for.

If not:
- I guess this issue may be closed as "won't fix"?

**Comment by Upabjojr** [comment] 2015-07-19 13:13
If `Idx` contains info about the range, I think we should permit `Sum( ... , i )` to mean a ranged-sum.

**Comment by moorepants** [comment] 2015-07-19 18:23
I agree, it'd be nice if this just worked as expected with the simpler syntax.

**Closed** 2015-07-31 08:28 UTC
