### ISSUE TITLE
Regression: expand fails to multiply float by -1 when calling init_printing in SymPy 0.7.6

### ISSUE THREAD

**Issue by Juanlu001** [sympy/sympy#8912] opened 2015-01-30 10:42 UTC
I found this strange behavior in SymPy 0.7.6, both Python 2 and 3:

```
$ python
Python 2.7.9 |Continuum Analytics, Inc.| (default, Dec 15 2014, 10:33:51) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://binstar.org
>>> from sympy import *
>>> x = symbols('x')
>>> (-x * (1. + x)).expand()
-x**2 - 1.0*x
>>> init_printing()
>>> (-x * (1. + x)).expand()
   2           
- x  - - -1.0⋅x
```

I can confirm this does not occur in SymPy 0.7.5:

```
$ python
Python 2.7.9 |Continuum Analytics, Inc.| (default, Dec 15 2014, 10:33:51) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://binstar.org
>>> from sympy import *
>>> x = symbols('x')
>>> (-x * (1. + x)).expand()
-x**2 - 1.0*x
>>> init_printing()
>>> (-x * (1. + x)).expand()
   2        
- x  - 1.0⋅x
```

**Comment by sahilshekhawat** [comment] 2015-01-30 12:44
I am not able to reproduce the results with the latest master branch.

**Comment by darshanime** [comment] 2015-02-08 11:10
^ +1

**Comment by swenson** [comment] 2015-03-04 00:53
+1. (I was able to reproduce on 0.7.6, but it is fixed on the latest master branch.)

**Comment by moorepants** [comment] 2015-03-04 01:15
I'm closing, but if someone wants to see if a test was written for this and write one if it isn't that would be great.

**Closed** 2015-03-04 01:14 UTC
