### ISSUE TITLE
lambdify: array in scalar out?

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#18347] opened 2020-01-15 21:40 UTC
How can one make a lambdified function that will return an array of constants other than the symbolic trickery shown below?
```python
>>> lambdify(x,1+x)(1)
2
>>> lambdify(x,1)(1)
1
>>> lambdify(x,1+x)(n.array((1,2)))
array([2, 3])
>>> lambdify(x,1)(n.array((1,2)))
1
>>> zero = x*(x+1) - x**2 -x
>>> lambdify(x, zero+1)(n.array((1,2)))
array([1, 1])
```
SO [ref ](https://stackoverflow.com/questions/59757573/sympy-evaluating-a-constant-function-in-a-list-doesnt-give-me-a-list)
```
(Though if one knows they want a constant the same length as the input then just creating it directly makes sense...but is lambdify being too clever to circumvent the array-in/array-out expectation?)

**Comment by sylee957** [comment] 2020-01-15 23:55
I don't think that lambdify is supposed to switch `1` into `array-in/array-out`, according to the input types.

But at least we can try something like getting `OneMatrix` or any equivalent array nodes to work.

**Comment by r-narula** [comment] 2020-11-09 07:06
Hey , I am new to open source can I work on this thing ?

**Comment by asmeurer** [comment] 2020-11-09 07:59
This is a duplicate of https://github.com/sympy/sympy/issues/5642. See the discussion there. In short, it usually isn't actually a problem that lambdify returns a constant because of NumPy broadcasting semantics. But if it actually is, you can make a wrapper that broadcasts automatically. There are also some other problems with matrices, which should be fixed by using `@` instead of `dot`, see https://github.com/sympy/sympy/issues/18824.

**Closed by asmeurer** 2020-11-09 07:59 UTC
Labels: utilities.lambdify
