### ISSUE TITLE
Empty list of solutions returned for equation with cubic roots

### ISSUE THREAD

**Issue by step135** [sympy/sympy#21167] opened 2021-03-25 16:27 UTC
```python
>>> from sympy import *
>>> x=S("x")
>>> solve(cbrt(x-1)+cbrt(x)+cbrt(x+1))
[]
```
<img src="https://render.githubusercontent.com/render/math?math=\sqrt[3]{x-a}%2B\sqrt[3]{x}%2B\sqrt[3]{x%2Bb}=0">
Due to symmetry, this equation has only one root in complex numbers. It is 0. We don't need to compute it considering the symmetry or directly seeing the algebraic solution and knowing that in case of symmetry there is only one solution. Antisymmetric cases when a ≠ b have three roots, mostly one real and two complex.

Algorithmic solution consists of cubing the equation and doing substitution using the original equation and finding roots of either linear (symmetric case) equation or cubic equation.

**Comment by oscarbenjamin** [comment] 2021-03-25 17:31
I think this a duplicate of https://github.com/sympy/sympy/issues/21026

**Comment by smichr** [comment] 2021-03-25 20:06
Yes, this is a problem with checking the solution. Disabling checking will give the solution:
```python
>>> eq = cbrt(x-1)+cbrt(x)+cbrt(x+1); solve(eq, check=0)
[0]
```

**Comment by oscarbenjamin** [comment] 2021-03-25 20:28
Here `0` is not a solution:
```python
In [1]: eq = cbrt(x-1)+cbrt(x)+cbrt(x+1)

In [2]: eq
Out[2]: 
3 ___   3 _______   3 _______
╲╱ x  + ╲╱ x - 1  + ╲╱ x + 1 

In [3]: eq.subs(x, 0)
Out[3]: 
    3 ____
1 + ╲╱ -1 

In [4]: eq.subs(x, 0).n()
Out[4]: 1.5 + 0.866025403784439⋅ⅈ
```
As discussed in the other issue that's because in sympy `cbrt` means the principal root which is not real in the case of negative numbers. If you meant the real root then you need to use `real_root`.

**Comment by oscarbenjamin** [comment] 2021-03-29 00:35
Closing as a duplicate of #21026 (the issue described here is invalid as is the OP in the other issue but the other issue also highlights some things that should work but don't so it's better to keep that one open).

**Closed by oscarbenjamin** 2021-03-29 00:35 UTC
