### ISSUE TITLE
eq1==eq2 but hash(eq1) != hash(eq2)

### ISSUE THREAD

**Issue by BitSecret** [sympy/sympy#25151] opened 2023-05-17 04:52 UTC
I constructed two equations use `Float` and `round`. Then I found `eq1==eq2` but `hash(eq1) != hash(eq2)`. This can cause some counter intuitive things. If `eq1` is added as a key to the dictionary, it will cause `eq2` in `list(dict)` but `eq2` not in `dict`.
The minimum runnable code:
```python
python==3.10.9
sympy==1.10.1
from sympy import symbols, Float


def float_round(n, round_it=True):
    if round_it:
        return n.round(6)
    return n


a = symbols("a")
target = a + float_round(Float(1.1))
target_value = float_round(float_round(Float(1.1)) + 1)

eq1 = target - target_value
eq2 = a - 1.0
print("eq1: {}".format(eq1))
print("eq2: {}".format(eq2))
print("hash(eq1): {}".format(hash(eq1)))
print("hash(eq2): {}".format(hash(eq2)))
print("eq1 is eq2?: {}".format(eq1 is eq2))
print("eq1 == eq2?: {}".format(eq1 == eq2))
print("hash(eq1) == hash(eq2)?: {}".format(hash(eq1) == hash(eq2)))
print()

a_dict = {eq1: 1}
print("a_dict: {}".format(a_dict))
print("eq2 in a_dict?: {}".format(eq2 in a_dict))
print("eq2 in list(a_dict)?: {}".format(eq2 in list(a_dict)))
```
The output:
```none
eq1: a - 1.0
eq2: a - 1.0
hash(eq1): -2414155512303799911
hash(eq2): -7963507767524122385
eq1 is eq2?: False
eq1 == eq2?: True
hash(eq1) == hash(eq2)?: False

a_dict: {a - 1.0: 1}
eq2 in a_dict?: False
eq2 in list(a_dict)?: True
```

**Comment by asmeurer** [comment] 2023-05-17 06:12
This is a duplicate of https://github.com/sympy/sympy/issues/11707. It's a well known issue and the solution hasn't been straightforward for us to figure out.

**Closed by asmeurer** 2023-05-17 06:12 UTC
