### ISSUE TITLE
List of modulo operator  sequence does not work 

### ISSUE THREAD

**Issue by RomanDerzh** [sympy/sympy#12548] opened 2017-04-15 19:23 UTC
List content is not updated and this causes range error 
from sympy.solvers.diophantine import base_solution_math_operators 
from sympy.abc import t
>>> odd = lambda x : bool(x % 2)
>>> numbers = [n for n in range(10)]
>>> for i in range(len(numbers)):
...     if odd(numbers[i]):
...         del numbers[i]  
...
Traceback (most recent call last):
  	  File "<stdin>", line 2, in <module>
IndexError: list index out of range

**Comment by Yerniyaz** [comment] 2017-04-15 20:47
python is organized such, that it does not update value given to range(). In your case, length of the list was changed , however for loop works only with initially given value. In this case, I recomend you to use while loop.

**Comment by adilbeknurmakov** [comment] 2017-04-16 05:34
Ooooh, this is most popular python bug. The problem is that you are trying to delete item from the list while iterating through it. Fortunately, python has ready paradigms to make your code easier and without bugs. Here is ready correct version

>>> odd = lambda x : bool(x % 2)
>>> numbers = [n for n in range(10)]
>>> numbers[:] = [n for n in numbers if not odd(n)]  # ahh, the beauty of it all
>>> numbers
[0, 2, 4, 6, 8]

**Comment by RomanDerzh** [comment] 2017-04-16 08:54
Thanks again, Adilbek.  I did not know that list is not reachable while iteration. Your code compiles

**Comment by oscarbenjamin** [comment] 2019-03-10 22:11
This isn't really a bug report in SymPy so I'm going to close it.

**Closed by oscarbenjamin** 2019-03-10 22:11 UTC
