### ISSUE TITLE
(x*y).evalf(subs={y: sqrt(2)}) returns x*y

### ISSUE THREAD

**Issue by beling** [sympy/sympy#11903] opened 2016-12-04 20:34 UTC
```
var('x y')
(x*y).evalf(subs={y: sqrt(2)})
```
returns `x*y`.

`(x*y).subs(y,sqrt(2)).evalf()` works as expected and gives `1.4142135623731*x`.

**Comment by asmeurer** [comment] 2016-12-04 22:02
Dupe of https://github.com/sympy/sympy/issues/6974

**Closed by asmeurer** 2016-12-04 22:02 UTC
