### ISSUE TITLE
hash(Rational(a, b)) should be equal to hash(S(Floating point number))

### ISSUE THREAD

**Issue by AnishShah** [sympy/sympy#10675] opened 2016-02-24 07:04 UTC
As discussed in PR #10657 
hash of a Rational should equal to hash of it's floating point number.

For example, `hash(Rational(3, 10)) == hash(S(0.3))`

**Comment by rwst** [comment] 2016-02-24 08:33
what precision is 0.3?

**Comment by govindlahoti** [comment] 2016-02-24 10:24
I would like to work on this

**Comment by cbm755** [comment] 2017-03-01 09:23
> hash of a Rational should equal to hash of it's floating point number.

Just FYI, I'm not sure that decision has yet been made, e.g., https://github.com/sympy/sympy/issues/11707#issuecomment-258696173

**Comment by asmeurer** [comment] 2017-03-27 20:49
I don't see any reference to this in #10657.

I don't agree that 0.3 and Rational(3, 10) should has the same, since they are not exactly equal (3/10 is not exactly representable as a floating point number). I would rather see `0.3 == Rational(3, 10)` give False.

**Comment by asmeurer** [comment] 2017-03-27 20:52
Oh I see, it's https://github.com/sympy/sympy/pull/10657#r53846283. I'm closing this issue as a duplicate of https://github.com/sympy/sympy/issues/11707

**Closed by asmeurer** 2017-03-27 20:52 UTC
