### ISSUE TITLE
Strangely behaved gamma_trace (gamma matrix trace)

### ISSUE THREAD

**Issue by sami-b95** [sympy/sympy#13636] opened 2017-11-23 19:19 UTC
I am trying to use the high energy physics module of SymPy to compute traces of gamma matrices using the dedicated function `sympy.physics.hep.gamma_matrices.gamma_trace`.  I have come accross the following strange behaviour: in some cases, the trace of a sum is not computed to be the sum of the traces. Here is an example:

```python
from sympy import Symbol
from sympy.tensor.tensor import tensor_indices, tensorhead
from sympy.physics.hep.gamma_matrices import GammaMatrix as G, gamma_trace, LorentzIndex

pi, ki, pf = tensorhead("pi, ki, pf", [LorentzIndex], [[1]])
i0, i1, i2, i3, i4 = tensor_indices("i0:5", LorentzIndex)
x = Symbol("x")
pis = pi(i2) * G(-i2)
kis = ki(i3) * G(-i3)
pfs = pf(i4) * G(-i4)

# Show the trace of A + B
print gamma_trace(pfs * G(i0) * kis * G(i1) * pis * G(-i1) * kis * G(-i0) + pfs * G(i0) * kis * G(i1) * pis * x * G(-i0) * pi(-i1))
# Show the trace of A
print gamma_trace(pfs * G(i0) * kis * G(i1) * pis * G(-i1) * kis * G(-i0))
# Show the trace of B
print gamma_trace(pfs * G(i0) * kis * G(i1) * pis * x * G(-i0) * pi(-i1))
```

It may be a normal behaviour, but I couldn't find any hint in the docs dedicated to the module.

**Comment by jksuom** [comment] 2017-11-24 12:35
`gamma_trace(B)` differs from that part of `gamma_trace(A + B)` which comes from `B` because it is processed by `_simplify_single_line`. It calls `extract_type_tens` in order to collect all gamma matrices, but only the explicit gamma matrix factors are found, not those embedded in `pis, kis, pfs`. Hence it seems that the result of `gamma_trace(B)` is wrong.

**Comment by sami-b95** [comment] 2017-11-29 16:33
The result of `gamma_trace(B)` is actually right and similarly for `gamma_trace(A)`. Only `gamma_trace(A + B)` is problematic. Also, I am not sure I understand the argument about the "explicit gamma factors". Do you mean there is a problem with using the intermediary variables `pis, kis, pfs` ? Yet, it seems the documentation gives similar examples.

All in all, should this behaviour be considered a bug? And in any case, what is the correct way to compute the trace of a tensor expression involving gamma matrices without worrying too much about this kind of pitfalls?

**Comment by glenn-horton-smith** [comment] 2022-07-07 22:59
Confirmed this is still a bug in sympy 1.10. This should be considered a bug.

**Comment by oscarbenjamin** [comment] 2022-07-08 00:03
The `sympy.physics.hep` module is unmaintained right now. If you want to contribute improvements or take over maintenance then go ahead.

**Comment by glenn-horton-smith** [comment] 2022-07-16 08:34
OK, I'm pretty sure I have now found the right fix for this. Passes all tests including newly added test for this bug. I will try to create a pull request tomorrow after I get some sleep, run flake8 and black, make sure I have set up a branch in my fork correctly, etc.

**Comment by oscarbenjamin** [comment] 2022-07-16 10:30
You don't need to run black. Since black is not currently used if you run it then it will probably rewrite everything so it is best not to do that.

**Comment by glenn-horton-smith** [comment] 2022-07-23 20:05
@sami-b95 (or anyone else following this bug): would you be interested in reviewing the pull request? I have added a test case for the original example, so anyone who can read the code and verify the new test case in sympy/physics/hep/tests/test_gamma_matrices.py is correct would be a good reviewer.

**Comment by oscarbenjamin** [comment] 2022-07-23 20:11
I can't personally confirm the correctness of the test case. I'm happy to merge the PR if someone else can though.

**Closed** 2022-07-29 23:48 UTC
Labels: physics
