### ISSUE TITLE
sympy.init_printing() causes infinite waiting in jupyter notebook

### ISSUE THREAD

**Issue by xiaobanni** [sympy/sympy#20308] opened 2020-10-21 13:17 UTC
When I do not start the `init_printing()` function, I can use sympy normally：

![](https://i.stack.imgur.com/dgxWG.png)

But if i use the `init_printing()` function for the best printing, it will cause infinite waiting in jupyter notebook:

![](https://i.stack.imgur.com/WAwCB.png)

My environment is Win10：

python 3.7.9

jupyter-notebook 6.1.4

sympy 1.6.2

matplotlib 3.3.1

jupyter_contrib_nbextensions 0.5.1

Based on this [#9959](https://github.com/sympy/sympy/pull/9959), I use sympy.init_printing(use_latex='mathjax') and it can work. But I still want to know the cause of the previous error. Thanks in advance.

**Comment by oscarbenjamin** [comment] 2021-08-30 20:16
I can't reproduce this. I tried installing jupyter_contrib_nbextensions 0.5.1 but it still works fine for me.

Can you try creating a virtual environment and installing jupyter and sympy in there to see if you get the same problem without having all the other packages installed?

**Comment by idanpa** [comment] 2024-12-29 14:50
duplicate of #18155.
I still have this problem on windows (dvipng.exe hangs, resolved by adding `-d` 🤷‍♂️)

**Comment by oscarbenjamin** [comment] 2024-12-29 15:09
Yes, closing as duplicate.

**Closed by oscarbenjamin** 2024-12-29 15:09 UTC
Labels: interactive
