### ISSUE TITLE
Bug on lambdify(): unable to plot Si(x)

### ISSUE THREAD

**Issue by cryptogun** [sympy/sympy#24175] opened 2022-10-25 13:20 UTC
Code:
```python
from sympy import *
import numpy as np
import matplotlib.pyplot as pyplot

x = symbols('x')
y = sin(x) / x

Y = integrate(y, x)
Y_func = lambdify(x, Y)

x_dots = np.linspace(0, 10, 100)
Y_dots = Y_func(x_dots)
pyplot.plot(x_dots, Y_dots)
pyplot.show()
```

Also not able to calculate a single value from the lambdified function:
```python
Y_func(1)
```

Issue: both local and live.sympy.org will give this error:
```python
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Cell In [54], line 12
      9 Y_func = lambdify(x, Y)
     11 x_dots = np.linspace(0, 10, 100)
---> 12 Y_dots = Y_func(x_dots)
     13 pyplot.plot(x_dots, Y_dots)
     14 pyplot.show()

File <lambdifygenerated-30>:2, in _lambdifygenerated(x)
      1 def _lambdifygenerated(x):
----> 2     return Si(x)

NameError: name 'Si' is not defined
```

**Comment by ThePauliPrinciple** [comment] 2022-10-26 10:20
The printer clearly indicates that it can not print this term:

```python
>>> from sympy.printing.pycode import SciPyPrinter
>>> printer = SciPyPrinter()
>>> print(printer.doprint(Y))
  # Not supported in Python with SciPy:
  # Si
Si(x)
```
No idea why this doesn't end up in the `lambdify` source (at least then it would be clear from the trace that this is not currently supported).

**Comment by oscarbenjamin** [comment] 2022-10-26 10:55
It looks like scipy does have this:
https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.sici.html

**Comment by oscarbenjamin** [comment] 2022-10-26 10:56
```python
In [5]: from scipy.special import sici

In [6]: sici(1)
Out[6]: (0.9460830703671831, 0.33740392290096816)

In [7]: Si(1)
Out[7]: Si(1)

In [8]: Si(1).evalf()
Out[8]: 0.946083070367183
```

**Comment by ThePauliPrinciple** [comment] 2022-10-26 12:51
Yes, this feature could be added, but I think it is also important that we consider this a bug because it is not clearly indicated as not being implemented (considering it was reported as a bug rather than a feature request). This might also happen for other `Function`s.

Considering it is not simply a name mapping, but instead you would have to do something like `sici(1)[0]`, I think it would require an explicit `_print_Si`/`_print_Ci` method for the `SciPyPrinter`.

**Comment by jksuom** [comment] 2022-10-26 12:57
Maybe `mpmath.si` could be used.

**Comment by asmeurer** [comment] 2022-10-27 07:53
We should automatically include `scipy` in the modules if it's installed.

**Comment by ThePauliPrinciple** [comment] 2022-10-27 10:18
Pretty sure it already is, the problem is that scipy doesn't have `Si` or `Ci`, it has `sici`. `mpmath.si` should not be used unless `lambdify` is told to use `mpmath` specifically.

**Comment by mihir1739** [comment] 2022-12-19 15:35
Hello Sirs,
Is there anything left in this issue that I can work upon.. If there is please assign this issue to me..
Thank You.

**Closed** 2023-01-23 17:06 UTC
Labels: Easy to Fix, printing, utilities.lambdify, codegen
