### ISSUE TITLE
Vector pretty printing can't handle divisions

### ISSUE THREAD

**Issue by moorepants** [sympy/sympy#2863] opened 2014-02-01 22:50 UTC
```
Python 2.7.5+ (default, Sep 19 2013, 13:48:49) 
Type "copyright", "credits" or "license" for more information.

IPython 1.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: from sympy import init_printing

In [2]: from sympy.abc import a, b, c

In [3]: from sympy.physics.vector import ReferenceFrame

In [4]: N = ReferenceFrame('N')

In [5]: v = a / b * N.x + (c + b) / a * N.y + c ** 2 / b * N.z

In [6]: v
Out[6]: a/b*N.x + (b + c)/a*N.y + c**2/b*N.z

In [7]: v._pretty()
Out[7]: <sympy.physics.vector.vector.Fake at 0x203c290>

In [8]: print(v._pretty())
<sympy.physics.vector.vector.Fake object at 0x3266510>

In [9]: init_printing()

In [10]: v
Out[10]: 
a
─
b*n_x + b + c
─────
  a  *n_y +  2
c 
──
b *n_z
```

It likely doesn't work for dyadics either.

**Comment by bluebrook** [comment] 2016-05-12 07:22
What is the expected results?

**Comment by moorepants** [comment] 2016-05-12 22:33
It's hard to type the expected result in unicode, but it the unit vectors should not be in the numerator or denominator of the fractions. The unit vectors should render with subscripts and maybe bold. And everything should be on one line.

**Comment by bluebrook** [comment] 2016-05-16 00:08
I have reproduced this issue on latest Master branch on ipython. I want to fix it. Where should I start?

**Comment by moorepants** [comment] 2016-05-16 00:23
You can start by adding new tests to this file:

https://github.com/sympy/sympy/blob/master/sympy/physics/vector/tests/test_printing.py

Once you have the tests, you can then modify:

https://github.com/sympy/sympy/blob/master/sympy/physics/vector/printing.py

until the tests pass.

**Comment by bluebrook** [comment] 2016-05-16 01:49
Thanks.

**Comment by bluebrook** [comment] 2016-05-18 07:17
The issue is in the Vector._pretty() function. The code doesn't consider the expr strings could have multiple lines.  If we treat the relation between unit vector and component as multiplicity and the relation between x,y,z as addition, we could simplify the code here.

The unicode I got with this approach is 
u'                     2    \na       b + c       c     \n\u2500\u22c5n_x + \u2500\u2500\u2500\u2500\u2500\u22c5n_y + \u2500\u2500\u22c5n_z\nb         a         b     '

**Comment by bluebrook** [comment] 2016-05-20 05:36
submit a pull request
https://github.com/sympy/sympy/pull/11138

**Comment by gxyd** [comment] 2018-01-06 18:53
@moorepants may be forgot to close this? It seems that both Vector division and dyadic division printing was fixed here (atleast the issue in description).
![printing-vector](https://user-images.githubusercontent.com/7712241/34642896-f05d80f0-f340-11e7-9471-71901c901011.png)

May be we can close this issue?

**Closed** 2018-01-06 19:57 UTC
Labels: physics.mechanics, printing, valid

**Comment by gxyd** [comment] 2018-01-06 19:58
Thanks Jason.
