### ISSUE TITLE
Travis test failure

### ISSUE THREAD

**Issue by sayandip18** [sympy/sympy#20276] opened 2020-10-16 19:15 UTC
`sympy/codegen/tests/test_fnode.py` is failing ([here](https://travis-ci.org/github/sympy/sympy/jobs/736456691#L5767) for instance)
```
____________ sympy/codegen/tests/test_fnodes.py:test_ImpliedDoLoop _____________
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/test-environment/lib/python3.7/site-packages/sympy-1.8.dev0-py3.7.egg/sympy/testing/runtests.py", line 1340, in _timeout
    function()
  File "/home/travis/miniconda/envs/test-environment/lib/python3.7/site-packages/sympy-1.8.dev0-py3.7.egg/sympy/codegen/tests/test_fnodes.py", line 73, in test_ImpliedDoLoop
    assert numstr in stdout
AssertionError
________________________________________________________________________________
______________ sympy/codegen/tests/test_fnodes.py:test_Subroutine ______________
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/test-environment/lib/python3.7/site-packages/sympy-1.8.dev0-py3.7.egg/sympy/testing/runtests.py", line 1340, in _timeout
    function()
  File "/home/travis/miniconda/envs/test-environment/lib/python3.7/site-packages/sympy-1.8.dev0-py3.7.egg/sympy/codegen/tests/test_fnodes.py", line 153, in test_Subroutine
    assert str(sum(ref))[:-3] in stdout
AssertionError
 tests finished: 4387 passed, 2 failed, 78 skipped, 84 expected to fail, 
2 expected to fail but passed, in 267.07 seconds 
DO *NOT* COMMIT!
Traceback (most recent call last):
  File "<stdin>", line 93, in <module>
Exception: Tests failed
```

**Comment by oscarbenjamin** [comment] 2020-10-16 23:39
Duplicate of #20265

**Closed by oscarbenjamin** 2020-10-16 23:39 UTC
