### ISSUE TITLE
.is_positive returns None when it should be False

### ISSUE THREAD

**Issue by TiloRC** [sympy/sympy#24948] opened 2023-03-21 03:04 UTC
```
from sympy import acos, sqrt, pi
a = acos(-3*sqrt(10)/10)
b = acos(2*sqrt(5)/5)
( b-a +3*pi/4).is_positive == None  # returns True
```
yet `( b-a +3*pi/4)` should be equal to zero according to wolfram alpha:
https://www.wolframalpha.com/input?i=acos%282*sqrt%285%29%2F5%29-acos%28-3*sqrt%2810%29%2F10%29%2B3*pi%2F4

~~Also, both `a.is_positive` and `b.is_positive` return True.~~ Edit: Note that a and b are real numbers.

**Comment by oscarbenjamin** [comment] 2023-03-21 09:12
> Also, both `a.is_positive` and `b.is_positive` return True.

That is correct:
```python
In [6]: b.evalf()
Out[6]: 0.463647609000806

In [7]: a.evalf()
Out[7]: 2.81984209919315
```

> ( b-a +3*pi/4).is_positive == None  # returns True

It is expected that some assumptions queries will not resolve:
https://docs.sympy.org/latest/guides/assumptions.html#the-old-assumptions-system

Returning None is always consistent so not a bug.

**Comment by TiloRC** [comment] 2023-03-21 16:19
While this might not be a bug, it would be nice to add functionality for dealing with such cases. How hard would it be to do that in a computationally efficient way?

**Comment by smichr** [comment] 2023-03-21 16:23
See https://github.com/sympy/sympy/issues/12327 and referenced #12525. This is something I have not been able to track down.

**Comment by basantbhandari** [comment] 2023-04-01 09:00
can I work on this?

**Comment by basantbhandari** [comment] 2023-04-01 09:09
when I study the problem, @TiloRC and @smichr. I found the is_positive gives None when applied to the expression and it gives the expected result when applied to the value.
`
>>> from sympy import acos, sqrt, pi
>>> a = acos(-3*sqrt(10)/10)
>>> b = acos(2*sqrt(5)/5)
>>> ( b-a +3*pi/4).is_positive == None 
True
>>> print(a)
acos(-3*sqrt(10)/10)
>>> print(b-a +3*pi/4)
-acos(-3*sqrt(10)/10) + acos(2*sqrt(5)/5) + 3*pi/4
>>> print((b-a +3*pi/4).evalf())
-0.e-124
>>> print(( b-a +3*pi/4).is_positive)
None
>>> print(( b-a +3*pi/4).evalf().is_positive)
False
>>> 
`

I think your dought will clear, let me know if you have any other issues.
thankyou

**Comment by basantbhandari** [comment] 2023-04-01 09:12
`>>> print(( b-a +3*pi/4).evalf().is_positive)
False
>>> print(( b-a +3*pi/4).evalf().is_negative)
True
>>> 
`

**Comment by TiloRC** [comment] 2023-04-01 20:46
@basantbhandari as you demonstrate in your second comment `print(( b-a +3pi/4).evalf().is_positive)` correctly returns False for the wrong reasons; it thinks that  `b-a +3pi/4` is a negative number when it is actually equal to 0.

**Comment by oscarbenjamin** [comment] 2023-04-02 16:00
> See #12327 and referenced #12525. This is something I have not been able to track down.

This isn't related to either of those issues. Those are both about `is_real` which works fine in this case:
```python
In [35]: print(expr)
-acos(-3*sqrt(10)/10) + acos(2*sqrt(5)/5) + 3*pi/4

In [36]: print(expr.is_real)
True
```
If you have a reason for reopening this then please explain what that reason is. For now I will close again.

The issue is with `is_positive` etc because the expression is exactly zero but the assumptions system does not know how to prove that:
```python
In [37]: print(expr.is_zero)
None

In [38]: print(expr.is_positive)
None

In [39]: print(expr.evalf())
-0.e-124
```
Proving that an expression is precisely equal to zero is a hard problem and is in fact undecidable in general:
https://en.wikipedia.org/wiki/Richardson%27s_theorem

Robust numerical evaluation like evalf can prove that a positive expression is zero or that a nonzero expression is nonzero but it cannot prove that a zero expression is zero or that its imaginary part is zero if intermediate complex numbers are computed during evaluation.

Ideally perhaps `simplify` would be able to prove that this expression is zero but I'm not sure what general algorithm could be used to do that. Here is one way to prove that the expression is zero:
```python
In [44]: print(sin(expr))
cos(-acos(-3*sqrt(10)/10) + acos(2*sqrt(5)/5) + pi/4)

In [45]: print(sin(expr).expand(trig=True))
0
```
This proves that the expression is some multiple of `pi`. Now numerical evaluation can show what multiple of pi it is:
```python
In [48]: (expr/pi).evalf()
Out[48]: 0.e-141

In [49]: round((expr/pi).evalf())
Out[49]: 0
```
It is way too much to expect that an assumptions query like `is_positive` would process the expression in this way but potentially some sort of simplification routine could be added to simplify. Perhaps there could be an `invtrigsimp` or something.

In any case I think it is fine that `is_positive` gives None here so I'm closing this issue. Feel free to open a new issue describing something else that can be improved but the core assumptions system is behaving as intended here because it is not expected to resolve arbitrarily complex queries.

**Closed by oscarbenjamin** 2023-04-02 16:00 UTC

**Comment by TiloRC** [comment] 2023-04-02 19:07
Thank you for your detailed response Oscar. I learned a lot of new things. I didn't know that this was undecidable in general. I guess it makes sense though.
