### ISSUE TITLE
Docstring for Symbol is very thin

### ISSUE THREAD

**Issue by moorepants** [sympy/sympy#22981] opened 2022-02-01 07:21 UTC
I linked to the docstring of `Symbol`, which is one of the most widely used objects in SymPy and was surprised at how little information was present in the docstring. This is all it is:

```
class Symbol(AtomicExpr, Boolean):
    """
    Assumptions:
       commutative = True
    You can override the default assumptions in the constructor.
    Examples
    ========
    >>> from sympy import symbols
    >>> A,B = symbols('A,B', commutative = False)
    >>> bool(A*B != B*A)
    True
    >>> bool(A*B*2 == 2*A*B) == True # multiplication by scalars is commutative
    True
    """
```

I would expect this to explain quite a bit more: all assumptions, passing in greek letters, or subscripts, and probably more.

**Comment by soma2000-lang** [comment] 2022-02-01 08:47
@moorepants  I want to work on this issue.

**Comment by KuldeepBorkar** [comment] 2022-02-06 12:11
@moorepants I think even the examples used here should not really be used here instead in the documentation we do have symbols and therefore it should be used there.
As a beginner I don't know for sure and it was not mentioned in the documentation but I just think,
`sympy.Symbol` is used to define just a single symbol and for multiple symbols we use `sympy.symbols`
Therefore, while changing the docstring I mentioned this commutative property in `symbols` instead of `Symbol`
and removed Assumptions from `Symbol` do you think it's okay?

**Comment by moorepants** [comment] 2022-02-06 13:12
> do you think it's okay?

No, I don't.

I think the docstrings for any public module/function/class/method/variable should be complete and helpful. The docstring for `Symbol` is very thin and does not explain everything it can do.

**Comment by KuldeepBorkar** [comment] 2022-02-07 04:37
@moorepants I tried updating the docstrings can you please check once?
I don't really know for sure what I should be adding more like what more assumptions are there or are the changes made okay or is there something expect more to be added I will commit more changes then.

**Comment by sarvaSanjay** [comment] 2022-10-29 14:58
Hi is this issue still open? If yes I would like to contribute to it.

**Comment by smichr** [comment] 2022-10-29 19:33
When the issues are closed, the large green Open near the title will be a large purple Closed. And you don't need to ask to contribute. If there is no PR showing as linked to the issue, it should be safe to open one.

**Comment by smichr** [comment] 2022-10-29 19:37
Another thing the docstring should probably contain is a note that Symbols compare equal based on name and assumptions, so `Symbol('x') != Symbol('x', real=True)` even though they both print the same.

**Comment by smichr** [comment] 2022-10-29 19:38
All symbols that look the same can be shown in unambiguous form with `disambiguate`:

![image](https://user-images.githubusercontent.com/90703/198849796-53062295-fc31-43aa-ba00-bc0007cc26ca.png)

**Comment by oscarbenjamin** [comment] 2022-11-02 17:17
Anyone wanting to work on this please look at the docstring style guide:
https://docs.sympy.org/latest/contributing/docstring.html

**Comment by Anant-2005** [comment] 2023-01-27 06:47
I would like to work on this issue, please assign it to me

**Comment by 1e9abhi1e10** [comment] 2023-01-27 07:18
@Anant-2005  you don't need to ask to contribute. If there is no PR showing as linked to the issue, you can open a PR.

**Comment by basantbhandari** [comment] 2023-03-31 17:20
I want to work on this if not resolved already

**Comment by smichr** [comment] 2023-04-01 03:10
> I want to work on this if not resolved already?

If the issue is open and there is no PR referenced therein, the issue is (most likely) unresolved. Anyone is free to work on any issue of interest.  See previous comment by @1e9abhi1e10

**Closed** 2024-01-14 15:56 UTC
Labels: Easy to Fix, Documentation
