### ISSUE TITLE
Cannot pretty print a function named gamma

### ISSUE THREAD

**Issue by moble** [sympy/sympy#13556] opened 2017-11-01 17:22 UTC
When I define a function named `'gamma'`, pretty printing interprets that object as the Gamma function and drops any but the first argument.  This happens in both the notebook and the terminal, though interestingly the notebook capitalizes gamma, whereas the terminal keeps it lowercase.  I can get around this by naming my function `r'\gamma'`, but that prevents pickling the object.  Here's the MWE:

```python
import sympy
gamma = sympy.Function('gamma')
x, y = sympy.symbols('x, y')
sympy.init_printing()
gamma(x, y)
```

And the results:

<img width="427" alt="badprinting" src="https://user-images.githubusercontent.com/1470769/32287188-59504f26-bf06-11e7-863e-88f15ce519e9.png">

<img width="392" alt="badterminal" src="https://user-images.githubusercontent.com/1470769/32287276-a8874a7c-bf06-11e7-9103-1e2f79e6d178.png">

This is related to #9253, but I agree that name collisions are inevitable — we just need to be able to overcome them.  And I suppose this may be related to #9064.  However, I don't find similar behavior with `beta` or `phi`.

**Comment by asmeurer** [comment] 2017-11-01 18:32
This is https://github.com/sympy/sympy/issues/2832. I think gamma is unlike beta or phi because it the SymPy function name is spelled lowercase but it pretty prints as an uppercase letter. 

Duplicates https://github.com/sympy/sympy/issues/2832

**Comment by asmeurer** [comment] 2017-11-01 18:32
Duplicate of #2832

**Comment by asmeurer** [comment] 2017-11-01 18:35
Regarding the behavior you see, it looks like it was fixed in the pretty printer but not the LaTeX printer.

**Closed** 2017-11-01 18:38 UTC

**Comment by moble** [comment] 2017-11-01 18:51
Maybe I'm just confused about what's doing what, but something also appears to be wrong with the pretty printer and `gamma`:

<img width="561" alt="prettyprinting" src="https://user-images.githubusercontent.com/1470769/32291665-1be90bce-bf14-11e7-9b63-3ebc122ff25e.png">

**Comment by jksuom** [comment] 2017-11-01 19:12
Fixed in pretty printer: https://github.com/sympy/sympy/pull/11919

**Comment by asmeurer** [comment] 2017-11-01 19:19
@moble good catch. That's another reason why we should print undefined functions completely separately from the function printers.
