### ISSUE TITLE
Structural equality

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#21099] opened 2021-03-16 09:23 UTC
As expected `cos(x)**2+sin(x)**2==1` returns `False`. But `Rational(3, 4) == Float(0.75)` returns `True`. I thought that equality sign returns `True` only if expressions are structurally equivalent.
If no, is there any operator that check structural equality?

**Comment by oscarbenjamin** [comment] 2021-03-16 09:40
See #20033 and #19915. I'll close this as a duplicate of #19915

**Closed by oscarbenjamin** 2021-03-16 09:40 UTC
