### ISSUE TITLE
tests-slow failing during testing

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#24933] opened 2023-03-18 16:40 UTC
traceback shows potential logical error in pytest:
```
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/site-packages/_pytest/_code/code.py", line 751, in get_source
INTERNALERROR>     lines.append(space_prefix + source.lines[line_index].strip())
INTERNALERROR>                                 ~~~~~~~~~~~~^^^^^^^^^^^^
INTERNALERROR> IndexError: list index out of range
```
My hunch is that the source is not returning anything and line_index is 0 and it is essentially doing `[][0]`; if there is no source, no lines should be appended.

**Comment by oscarbenjamin** [comment] 2023-03-19 10:51
I have made the slow2 tests not required for now so that PRs can be merged anyway.

The test in question is xfail and slow and should not really be run in CI anyway:
https://github.com/sympy/sympy/blob/9b7d671ea15131aab0fe80c8cd73ed8d0cca7be5/sympy/matrices/tests/test_matrices.py#L2651-L2670
As far as I know this test just always times out. There is apparently something not working for the case when a test times out.

**Comment by oscarbenjamin** [comment] 2023-03-19 10:54
In a basic example it works:
```
pip install -U pytest pytest-timeout
```
Then with this file:
```python
import time

def test_slowthing():
    time.sleep(20)
```
Then running pytest:
```console
$ pytest --timeout=1 slowtest.py 
======================================== test session starts ========================================
platform linux -- Python 3.8.9, pytest-7.2.2, pluggy-1.0.0
benchmark: 3.4.1 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: /home/oscar/current/sympy/sympy.git, configfile: pyproject.toml
plugins: cov-4.0.0, benchmark-3.4.1, xdist-3.2.0, forked-1.3.0, doctestplus-0.12.1, timeout-2.1.0, anyio-3.6.2, instafail-0.4.2, xdoctest-1.1.1, typeguard-2.13.3
timeout: 1.0s
timeout method: signal
timeout func_only: False
collected 1 item                                                                                    

slowtest.py F                                                                                 [100%]

============================================= FAILURES ==============================================
__________________________________________ test_slowthing ___________________________________________

    def test_slowthing():
>       time.sleep(20)
E       Failed: Timeout >1.0s

slowtest.py:4: Failed
====================================== short test summary info ======================================
FAILED slowtest.py::test_slowthing - Failed: Timeout >1.0s
========================================= 1 failed in 1.34s =========================================
```

**Comment by oscarbenjamin** [comment] 2023-03-19 11:06
Running the specific test that fails in CI locally seems to be fine:
```console
$ bin/test --slow --timeout 595 sympy/matrices/tests/test_matrices.py 
======================================== test session starts ========================================
platform linux -- Python 3.8.9, pytest-7.2.2, pluggy-1.0.0
benchmark: 3.4.1 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
architecture: 64-bit
cache:        yes
ground types: gmpy 2.1.5

rootdir: /home/oscar/current/sympy/sympy.git, configfile: pyproject.toml
plugins: cov-4.0.0, benchmark-3.4.1, xdist-3.2.0, forked-1.3.0, doctestplus-0.12.1, timeout-2.1.0, anyio-3.6.2, instafail-0.4.2, xdoctest-1.1.1, typeguard-2.13.3
timeout: 595.0s
timeout method: signal
timeout func_only: False
collected 181 items / 180 deselected / 1 selected                                                   

sympy/matrices/tests/test_matrices.py x                                                       [100%]

========================== 180 deselected, 1 xfailed in 225.59s (0:03:45) ===========================
```

**Comment by oscarbenjamin** [comment] 2023-03-19 11:14
Actually it doesn't time out. It is just slow and then fails at the final assert because it is comparing matrices with very large expressions in them.

**Comment by oscarbenjamin** [comment] 2023-03-19 11:25
I can't reproduce the problem locally but I guess it is not deterministic since it sometimes passes in CI:
https://github.com/sympy/sympy/actions/runs/4453458464/jobs/7822088189

**Comment by oscarbenjamin** [comment] 2023-03-19 11:51
I did a full run of the slow test split and it passed:
```console
$ bin/test --slow --timeout 595 --split 2/4

[pytest-split] No test durations found. Pytest-split will split tests evenly when no durations are found. 
[pytest-split] You can expect better results in consequent runs, when test timings have been documented.

======================================== test session starts ========================================
platform linux -- Python 3.8.9, pytest-7.2.2, pluggy-1.0.0
benchmark: 3.4.1 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
architecture: 64-bit
cache:        yes
ground types: gmpy 2.1.5

rootdir: /home/oscar/current/sympy/sympy.git, configfile: pyproject.toml
plugins: cov-4.0.0, split-0.8.0, benchmark-3.4.1, xdist-3.2.0, forked-1.3.0, doctestplus-0.12.1, timeout-2.1.0, anyio-3.6.2, instafail-0.4.2, xdoctest-1.1.1, typeguard-2.13.3
timeout: 595.0s
timeout method: signal
timeout func_only: False
collecting 11202 items                                                                              

[pytest-split] Splitting tests with algorithm: duration_based_chunks
[pytest-split] Running group 2/4 (estimated duration: 49.00s)

collected 11202 items / 11153 deselected / 49 selected                                              

sympy/integrals/tests/test_intpoly.py .                                                       [  2%]
sympy/integrals/tests/test_laplace.py ...                                                     [  8%]
sympy/integrals/tests/test_manual.py .........                                                [ 26%]
sympy/integrals/tests/test_meijerint.py ....                                                  [ 34%]
sympy/integrals/tests/test_transforms.py s...                                                 [ 42%]
sympy/logic/tests/test_boolalg.py .                                                           [ 44%]
sympy/matrices/expressions/tests/test_blockmatrix.py .                                        [ 46%]
sympy/matrices/tests/test_decompositions.py .                                                 [ 48%]
sympy/matrices/tests/test_eigen.py ..                                                         [ 53%]
sympy/matrices/tests/test_matrices.py x                                                       [ 55%]
sympy/ntheory/tests/test_ecm.py .                                                             [ 57%]
sympy/ntheory/tests/test_factor_.py .                                                         [ 59%]
sympy/ntheory/tests/test_primetest.py .                                                       [ 61%]
sympy/ntheory/tests/test_qs.py .                                                              [ 63%]
sympy/physics/mechanics/tests/test_kane3.py s                                                 [ 65%]
sympy/physics/mechanics/tests/test_linearize.py .                                             [ 67%]
sympy/physics/quantum/tests/test_circuitutils.py ..                                           [ 71%]
sympy/physics/quantum/tests/test_spin.py .                                                    [ 73%]
sympy/physics/tests/test_secondquant.py .                                                     [ 75%]
sympy/polys/numberfields/tests/test_minpoly.py .                                              [ 77%]
sympy/polys/tests/test_groebnertools.py .                                                     [ 79%]
sympy/polys/tests/test_polyroots.py .                                                         [ 81%]
sympy/polys/tests/test_ring_series.py .                                                       [ 83%]
sympy/polys/tests/test_rootoftools.py ..                                                      [ 87%]
sympy/series/tests/test_formal.py ..                                                          [ 91%]
sympy/series/tests/test_gruntz.py ..                                                          [ 95%]
sympy/series/tests/test_sequences.py .                                                        [ 97%]
sympy/simplify/tests/test_hyperexpand.py .                                                    [100%]

========================================= warnings summary ==========================================
sympy/printing/tests/test_aesaracode.py:27
  /home/oscar/current/sympy/sympy.git/sympy/printing/tests/test_aesaracode.py:27: DeprecationWarning: `Scalar` is deprecated; use `ScalarType` instead.
    from aesara.scalar.basic import Scalar

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
======== 46 passed, 2 skipped, 11153 deselected, 1 xfailed, 1 warning in 1206.26s (0:20:06) =========
```
That is the exact command that is run in CI although it does not seem to have collected the exact same set of tests. I'm not sure exactly how the splitting is done to know what would make it completely reproducible.

**Comment by oscarbenjamin** [comment] 2023-03-19 11:57
Here is a link to the actual CI failure (since it isn't shown above):
https://github.com/sympy/sympy/actions/runs/4460269754/jobs/7833440685

The full output from CI is:
```console
$ bin/test --slow --timeout 595 --split 2/4

[pytest-split] No test durations found. Pytest-split will split tests evenly when no durations are found. 
[pytest-split] You can expect better results in consequent runs, when test timings have been documented.

============================= test session starts ==============================
platform linux -- Python 3.[11](https://github.com/sympy/sympy/actions/runs/4460269754/jobs/7833440685#step:6:12).2, pytest-7.2.2, pluggy-1.0.0
architecture: 64-bit
cache:        yes
ground types: python 

rootdir: /home/runner/work/sympy/sympy, configfile: pyproject.toml
plugins: split-0.8.0, timeout-2.1.0
timeout: 595.0s
timeout method: signal
timeout func_only: False


[pytest-split] Splitting tests with algorithm: duration_based_chunks
[pytest-split] Running group 2/4 (estimated duration: 49.00s)

collected 11193 items / 11144 deselected / 49 selected

sympy/integrals/tests/test_laplace.py ...                                [  6%]
sympy/integrals/tests/test_manual.py .........                           [ 24%]
sympy/integrals/tests/test_meijerint.py ....                             [ 32%]
sympy/integrals/tests/test_transforms.py s...                            [ 40%]
sympy/logic/tests/test_boolalg.py .                                      [ 42%]
sympy/matrices/expressions/tests/test_blockmatrix.py .                   [ 44%]
sympy/matrices/tests/test_decompositions.py .                            [ 46%]
sympy/matrices/tests/test_eigen.py ..                                    [ 51%]
sympy/matrices/tests/test_matrices.py 
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/site-packages/_pytest/main.py", line 270, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>                          ^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/site-packages/_pytest/main.py", line 324, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/site-packages/pluggy/_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/site-packages/pluggy/_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/site-packages/pluggy/_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/site-packages/pluggy/_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>           ^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/site-packages/_pytest/main.py", line 349, in pytest_runtestloop
INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/site-packages/pluggy/_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/site-packages/pluggy/_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/site-packages/pluggy/_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/site-packages/pluggy/_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>           ^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/site-packages/_pytest/runner.py", line 1[12](https://github.com/sympy/sympy/actions/runs/4460269754/jobs/7833440685#step:6:13), in pytest_runtest_protocol
INTERNALERROR>     runtestprotocol(item, nextitem=nextitem)
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/site-packages/_pytest/runner.py", line [13](https://github.com/sympy/sympy/actions/runs/4460269754/jobs/7833440685#step:6:14)1, in runtestprotocol
INTERNALERROR>     reports.append(call_and_report(item, "call", log))
INTERNALERROR>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/site-packages/_pytest/runner.py", line 222, in call_and_report
INTERNALERROR>     report: TestReport = hook.pytest_runtest_makereport(item=item, call=call)
INTERNALERROR>                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/site-packages/pluggy/_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/site-packages/pluggy/_callers.py", line 55, in _multicall
INTERNALERROR>     gen.send(outcome)
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/site-packages/_pytest/skipping.py", line 265, in pytest_runtest_makereport
INTERNALERROR>     rep = outcome.get_result()
INTERNALERROR>           ^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/site-packages/pluggy/_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/site-packages/pluggy/_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>           ^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/site-packages/_pytest/runner.py", line 366, in pytest_runtest_makereport
INTERNALERROR>     return TestReport.from_item_and_call(item, call)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/site-packages/_pytest/reports.py", line 349, in from_item_and_call
INTERNALERROR>     longrepr = item.repr_failure(excinfo)
INTERNALERROR>                ^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/site-packages/_pytest/python.py", line 1823, in repr_failure
INTERNALERROR>     return self._repr_failure_py(excinfo, style=style)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/site-packages/_pytest/nodes.py", line 484, in _repr_failure_py
INTERNALERROR>     return excinfo.getrepr(
INTERNALERROR>            ^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/site-packages/_pytest/_code/code.py", line 669, in getrepr
INTERNALERROR>     return fmt.repr_excinfo(self)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/site-packages/_pytest/_code/code.py", line 944, in repr_excinfo
INTERNALERROR>     reprtraceback = self.repr_traceback(excinfo_)
INTERNALERROR>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/site-packages/_pytest/_code/code.py", line 871, in repr_traceback
INTERNALERROR>     reprentry = self.repr_traceback_entry(entry, einfo)
INTERNALERROR>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/site-packages/_pytest/_code/code.py", line 822, in repr_traceback_entry
INTERNALERROR>     s = self.get_source(source, line_index, excinfo, short=short)
INTERNALERROR>         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/site-packages/_pytest/_code/code.py", line 751, in get_source
INTERNALERROR>     lines.append(space_prefix + source.lines[line_index].strip())
INTERNALERROR>                                 ~~~~~~~~~~~~^^^^^^^^^^^^
INTERNALERROR> IndexError: list index out of range

========= 24 passed, 1 skipped, 11[14](https://github.com/sympy/sympy/actions/runs/4460269754/jobs/7833440685#step:6:15)4 deselected in 1066.59s (0:[17](https://github.com/sympy/sympy/actions/runs/4460269754/jobs/7833440685#step:6:18):[46](https://github.com/sympy/sympy/actions/runs/4460269754/jobs/7833440685#step:6:47)) =========
Error: Process completed with exit code 3.
```

**Comment by oscarbenjamin** [comment] 2023-03-19 12:13
I really can't reproduce this locally.

I'm not sure from the pytest traceback but it is possible that it is failing because of something to do with getting the repr to make a traceback. This test fails on the final assert and the objects that are being compared for the assert are matrices with huge expressions in them so any repr is unlikely to be useful.

**Comment by oscarbenjamin** [comment] 2023-03-19 12:20
In any case the test is a bad test that should be removed. It is extremely slow and is using a method (diagonalisation) that clearly should not be used for anything more than a 2x2 matrix. The method is based on computing enormous expressions for the eigenvalues and eigenvectors when in fact the rank decomposition method computes the result using only field arithmetic and should clearly be preferred.

As far as I can tell the test only fails because the expressions involved are very complicated but in principle if simplified the test would pass. Actually calling simplify here would be too slow though. Of course we could say that maybe a method should be used that produces simpler output for pinv but that already exists. This test just happens to test a non-default sub-optimal method for computing the pseudoinverse.

**Comment by oscarbenjamin** [comment] 2023-03-19 12:33
This should be more or less an end to end reproduction of what happens in CI:
```bash
#!/usr/bin/env bash

mkdir tmp_slow_test
cd tmp_slow_test
python -m venv venv
source venv/bin/activate
python -m pip install --upgrade pip
pip install mpmath pytest pytest-split pytest-timeout
git clone https://github.com/sympy/sympy.git
cd sympy
bin/test --slow --timeout 595 --split 2/4
```
I've just run that and it passes fine locally. With that it seems to be collecting and running the exact same tests as in CI:
```console
$ ./slow.sh 
Collecting pip
  Using cached pip-23.0.1-py3-none-any.whl (2.1 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 20.2.3
    Uninstalling pip-20.2.3:
      Successfully uninstalled pip-20.2.3
Successfully installed pip-23.0.1
Collecting mpmath
  Using cached mpmath-1.3.0-py3-none-any.whl (536 kB)
Collecting pytest
  Using cached pytest-7.2.2-py3-none-any.whl (317 kB)
Collecting pytest-split
  Using cached pytest_split-0.8.0-py3-none-any.whl (11 kB)
Collecting pytest-timeout
  Using cached pytest_timeout-2.1.0-py3-none-any.whl (12 kB)
Collecting exceptiongroup>=1.0.0rc8
  Downloading exceptiongroup-1.1.1-py3-none-any.whl (14 kB)
Collecting pluggy<2.0,>=0.12
  Using cached pluggy-1.0.0-py2.py3-none-any.whl (13 kB)
Collecting packaging
  Using cached packaging-23.0-py3-none-any.whl (42 kB)
Collecting attrs>=19.2.0
  Using cached attrs-22.2.0-py3-none-any.whl (60 kB)
Collecting tomli>=1.0.0
  Using cached tomli-2.0.1-py3-none-any.whl (12 kB)
Collecting iniconfig
  Using cached iniconfig-2.0.0-py3-none-any.whl (5.9 kB)
Installing collected packages: mpmath, tomli, pluggy, packaging, iniconfig, exceptiongroup, attrs, pytest, pytest-timeout, pytest-split
Successfully installed attrs-22.2.0 exceptiongroup-1.1.1 iniconfig-2.0.0 mpmath-1.3.0 packaging-23.0 pluggy-1.0.0 pytest-7.2.2 pytest-split-0.8.0 pytest-timeout-2.1.0 tomli-2.0.1
Cloning into 'sympy'...
remote: Enumerating objects: 376579, done.
remote: Counting objects: 100% (592/592), done.
remote: Compressing objects: 100% (281/281), done.
remote: Total 376579 (delta 386), reused 471 (delta 311), pack-reused 375987
Receiving objects: 100% (376579/376579), 169.51 MiB | 16.06 MiB/s, done.
Resolving deltas: 100% (302018/302018), done.
Checking connectivity... done.

[pytest-split] No test durations found. Pytest-split will split tests evenly when no durations are found. 
[pytest-split] You can expect better results in consequent runs, when test timings have been documented.

======================================== test session starts ========================================
platform linux -- Python 3.8.9, pytest-7.2.2, pluggy-1.0.0
architecture: 64-bit
cache:        yes
ground types: python 

rootdir: /home/oscar/current/sympy/sympy.git/tmp_slow_test/sympy, configfile: pyproject.toml
plugins: split-0.8.0, timeout-2.1.0
timeout: 595.0s
timeout method: signal
timeout func_only: False
collecting 11193 items                                                                              

[pytest-split] Splitting tests with algorithm: duration_based_chunks
[pytest-split] Running group 2/4 (estimated duration: 49.00s)

collected 11193 items / 11144 deselected / 49 selected                                              

sympy/integrals/tests/test_laplace.py ...                                                     [  6%]
sympy/integrals/tests/test_manual.py .........                                                [ 24%]
sympy/integrals/tests/test_meijerint.py ....                                                  [ 32%]
sympy/integrals/tests/test_transforms.py s...                                                 [ 40%]
sympy/logic/tests/test_boolalg.py .                                                           [ 42%]
sympy/matrices/expressions/tests/test_blockmatrix.py .                                        [ 44%]
sympy/matrices/tests/test_decompositions.py .                                                 [ 46%]
sympy/matrices/tests/test_eigen.py ..                                                         [ 51%]
sympy/matrices/tests/test_matrices.py x                                                       [ 53%]
sympy/ntheory/tests/test_ecm.py .                                                             [ 55%]
sympy/ntheory/tests/test_factor_.py .                                                         [ 57%]
sympy/ntheory/tests/test_primetest.py .                                                       [ 59%]
sympy/ntheory/tests/test_qs.py .                                                              [ 61%]
sympy/physics/mechanics/tests/test_kane3.py s                                                 [ 63%]
sympy/physics/mechanics/tests/test_linearize.py .                                             [ 65%]
sympy/physics/quantum/tests/test_circuitutils.py ..                                           [ 69%]
sympy/physics/quantum/tests/test_spin.py .                                                    [ 71%]
sympy/physics/tests/test_secondquant.py .                                                     [ 73%]
sympy/polys/numberfields/tests/test_minpoly.py .                                              [ 75%]
sympy/polys/tests/test_groebnertools.py .                                                     [ 77%]
sympy/polys/tests/test_polyroots.py .                                                         [ 79%]
sympy/polys/tests/test_ring_series.py .                                                       [ 81%]
sympy/polys/tests/test_rootoftools.py ..                                                      [ 85%]
sympy/series/tests/test_formal.py ..                                                          [ 89%]
sympy/series/tests/test_gruntz.py ..                                                          [ 93%]
sympy/series/tests/test_sequences.py .                                                        [ 95%]
sympy/simplify/tests/test_hyperexpand.py ..                                                   [100%]

============== 46 passed, 2 skipped, 11144 deselected, 1 xfailed in 1251.77s (0:20:51) ==============
```

**Comment by oscarbenjamin** [comment] 2023-03-19 13:21
I think this test used to behave differently before gh-20614 (i.e. before SymPy 1.8) because before it would not have been possible to calculate the diagonalisation before.

**Comment by oscarbenjamin** [comment] 2023-03-19 14:33
Now that I have fixed the test in gh-24938 I can see that it actually only takes about 10 seconds to pass.

It seems that a consequence of gh-24291 is that when the test fails pytest will try to generate a traceback to show and so it tries to compute the repr of the two expressions that are being compared. It is generating that enormous repr that is slow and that obviously shouldn't happen in the case of an xfail test since the traceback is not going to be shown.

Possibly we should use something to prevent such large reprs from being something that pytest tries to show. I'm not sure beyond `--assert=plain` what can be done for that.

I suppose in general it is a problem that sympy generates such absurdly large reprs.

**Comment by oscarbenjamin** [comment] 2023-03-20 21:46
This is sort of fixed for now in that the test is fixed so we don't see this problem any more. I'm going to close this but the problem might come back in future.

**Closed by oscarbenjamin** 2023-03-20 21:46 UTC
Labels: Testing
