### ISSUE TITLE
x**1 == x**1.0 returns False

### ISSUE THREAD

**Issue by ngoldbaum** [sympy/sympy#14580] opened 2018-03-30 19:52 UTC
Under sympy 1.1.1 on Python3.6, I get the following behavior:

```
In [1]: import sympy

In [2]: sympy.__version__
Out[2]: '1.1.1'

In [3]: from sympy.abc import x

In [4]: x**2.0 == x**2
Out[4]: True

In [5]: x**1.0 == x**1
Out[5]: True
```

While with the current git master branch, I get:

```
In [1]: import sympy
In [2]: sympy.__version__
Out[2]: '1.1.2.dev'

In [3]: from sympy.abc import x

In [4]: x**2 == x**2.0
Out[4]: True

In [5]: x**1 == x**1.0
Out[5]: False
```

**Comment by asmeurer** [comment] 2018-03-30 21:09
This was an intentional change. See https://github.com/sympy/sympy/issues/12942. Note that `==` in SymPy means structural, not mathematical equality. 

The case for 2 vs. 2.0 is related to https://github.com/sympy/sympy/issues/11707. 

Closing this as duplicate of those two issues.

**Closed by asmeurer** 2018-03-30 21:09 UTC
