### ISSUE TITLE
What is the result of integrate of a tuple (i.e. integrate((x, x)))?

### ISSUE THREAD

**Issue by ischurov** [sympy/sympy#18038] opened 2019-12-10 20:33 UTC
I just accidently discovered unexpected (at least, for me) behaviour of `integrate` if its first argument is a tuple:

```
In [60]: integrate((x, x))
Out[60]:
 3
x     2
── + x
2

In [61]: integrate((x, x, x))
Out[61]:
 4    3
x    x     2
── + ── + x
3    2

In [62]: integrate((x, 1))
Out[62]:
 3
x
── + x
2
```
It seems to be undocumented and I cannot figure out what does it do. Probably, documentation should be updated to address this.

**Comment by asmeurer** [comment] 2019-12-10 21:44
Looks like this is entirely accidental. It stems from

```
>>> Tuple(x, x).as_poly(x)
Poly(x*x + x, x, domain='ZZ[x]')
```

which doesn't seem like it should be something that works to me.

**Comment by jksuom** [comment] 2019-12-11 08:39
`.as_poly()` should probably reject invalid polynomial representations:
```
--- a/sympy/core/basic.py
+++ b/sympy/core/basic.py
@@ -785,7 +785,7 @@ def as_poly(self, *gens, **args):
         from sympy.polys import Poly, PolynomialError
 
         try:
-            poly = Poly(self, *gens, **args)
+            poly = Poly.new(self, *gens, **args)
 
             if not poly.is_Poly:
                 return None
```

**Comment by dhruvmendiratta6** [comment] 2019-12-12 20:57
I am working on the issue and can't figure out why `Poly.new()` should be preferred and why 
https://github.com/sympy/sympy/blob/52069d42f4d6df1811269f4bf8c00da93e02fae6/sympy/polys/polytools.py#L114-L118

is not working

**Comment by asmeurer** [comment] 2019-12-12 21:52
I agree with @jksuom. There's also a secondary issue here which is that `Poly((x, x), x)` creates a polynomial where x is both a generator and contained in the coefficients. That should give an error IMO.

**Comment by dhruvmendiratta6** [comment] 2019-12-15 20:53
But in the suggested solution `new()` cannot perform the functionalities that `__new__()` can, like constructing polynomials from dictionaries, lists etc. Or am I failing to understand something here.(I am new to open source)

**Comment by jksuom** [comment] 2019-12-16 05:58
> constructing polynomials from dictionaries, lists etc.

These are not SymPy's expressions. Only those have the attribute `.as_poly()`. `__new__()` accepts also those but that is for internal use in the polys module. `.new()` is designed for those cases where the arguments have to be checked for validity. (In fact, I think that it might have been better to have a private method `_new()` for internal use and `__new__()` could have done what `new()` now does.)

**Comment by dhruvmendiratta6** [comment] 2019-12-17 19:44
> In fact, I think that it might have been better to have a private method `_new()` for internal use and `__new__()` could have done what `new()` now does.

I can do that but I have a couple of doubts regarding `new()`, it accepts an object of the class `Basic` and compares it with class `DMP`. Shouldn't it always raise a `PolynomialError` when called from 
`as_poly()` ?https://github.com/sympy/sympy/blob/52069d42f4d6df1811269f4bf8c00da93e02fae6/sympy/polys/polytools.py#L130-L132

and it returns an object of class `Basic`
https://github.com/sympy/sympy/blob/52069d42f4d6df1811269f4bf8c00da93e02fae6/sympy/polys/polytools.py#L136-L141
Souldn't the returned object be of class `Poly`?

**Comment by asmeurer** [comment] 2019-12-17 19:49
I'm also unclear why as_poly exists on Basic instead of just Expr. Are there useful non-Expr classes that can be converted to Poly, especially if we disable it working with Tuple?

**Comment by jksuom** [comment] 2019-12-17 20:03
> Are there useful non-Expr classes that can be converted to Poly,

I cannot think of any.

**Comment by dhruvmendiratta6** [comment] 2019-12-18 10:14
@jksuom I think that in your solution where `new()` is called instead of `__new__()` the result would be a Basic class object compared with the DMP class. And instead of returning a Poly object, a Basic class object would be returned.

**Comment by jksuom** [comment] 2019-12-18 11:36
> And instead of returning a Poly object, a Basic class object would be returned.

That will not be an issue. `Poly.new()` is a classmethod with first argument `cls`. In this case, `cls` will be `Poly` and therefore the new object will be an instance of `Poly`. However, I now see that there is another problem. I had forgotten that the `rep` argument has to be a `DMP` object. Therefore `new()` is only good for internal work (though it appears to be public with no prepended _ in its name).

It looks like `.as_poly()` may continue using `Poly.__new__()` but probably the method should be moved from `Basic` to `Expr`. It would seem logical that only expressions (of a certain kind) can be transformed to `Poly` objects. That would solve this issue as `Tuple` is not a subclass of `Expr`.
 
(It is true that better argument checking should be added to `Poly.__new__()`, but that can be done in another PR.)

**Comment by dhruvmendiratta6** [comment] 2019-12-19 11:37
I implemented the changes and the following test fail message appears when I run the tests using `python bin/test`

`sympy\utilities\tests\test_misc.py[7] ......F                             [FAIL]`
````
 File "c:\users\mendiratta\sympy\sympy\utilities\tests\test_misc.py", line 118, in test_debug_output
    assert expected in err
AssertionError

 tests finished: 8502 passed, 1 failed, 337 skipped, 377 expected to fail,
3 expected to fail but passed, in 2595.89 seconds
DO *NOT* COMMIT!
```

**Comment by jksuom** [comment] 2019-12-19 11:55
> I implemented the changes

What exactly did you change?

**Comment by dhruvmendiratta6** [comment] 2019-12-19 12:18
I moved as_poly() from Basic to Expr
```
$ git diff
warning: LF will be replaced by CRLF in sympy/core/basic.py.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in sympy/core/expr.py.
The file will have its original line endings in your working directory
diff --git a/sympy/core/basic.py b/sympy/core/basic.py
index 79deff1978..a11249c939 100644
--- a/sympy/core/basic.py
+++ b/sympy/core/basic.py
@@ -766,33 +766,7 @@ def _sorted_args(self):
         return self.args


-    def as_poly(self, *gens, **args):
-        """Converts ``self`` to a polynomial or returns ``None``.

-        >>> from sympy import sin
-        >>> from sympy.abc import x, y
-
-        >>> print((x**2 + x*y).as_poly())
-        Poly(x**2 + x*y, x, y, domain='ZZ')
-
-        >>> print((x**2 + x*y).as_poly(x, y))
-        Poly(x**2 + x*y, x, y, domain='ZZ')
-
-        >>> print((x**2 + sin(y)).as_poly(x, y))
-        None
-
-        """
-        from sympy.polys import Poly, PolynomialError
-
-        try:
-            poly = Poly(self, *gens, **args)
-
-            if not poly.is_Poly:
-                return None
-            else:
-                return poly
-        except PolynomialError:
-            return None

     def as_content_primitive(self, radical=False, clear=True):
         """A stub to allow Basic args (like Tuple) to be skipped when computing
diff --git a/sympy/core/expr.py b/sympy/core/expr.py
index b1e85ead5f..edbf84e9c2 100644
--- a/sympy/core/expr.py
+++ b/sympy/core/expr.py
@@ -1076,6 +1076,34 @@ def as_ordered_factors(self, order=None):
         """Return list of ordered factors (if Mul) else [self]."""
         return [self]

+    def as_poly(self, *gens, **args):
+        """Converts ``self`` to a polynomial or returns ``None``.
+
+        >>> from sympy import sin
+        >>> from sympy.abc import x, y
+
+        >>> print((x**2 + x*y).as_poly())
+        Poly(x**2 + x*y, x, y, domain='ZZ')
+
+        >>> print((x**2 + x*y).as_poly(x, y))
+        Poly(x**2 + x*y, x, y, domain='ZZ')
+
+        >>> print((x**2 + sin(y)).as_poly(x, y))
+        None
+
+        """
+        from sympy.polys import Poly, PolynomialError
+
+        try:
+            poly = Poly(self, *gens, **args)
+
+            if not poly.is_Poly:
+                return None
+            else:
+                return poly
+        except PolynomialError:
+            return None
+
     def as_ordered_terms(self, order=None, data=False):
         """
         Transform an expression to an ordered list of terms.

```

**Comment by jksuom** [comment] 2019-12-19 12:36
I think that there are some differences in the debug messages. The test can probably be fixed by minor editing. I'll try to look into it.

**Comment by jksuom** [comment] 2019-12-19 12:45
I cannot reproduce the error. I wonder if it can have anything to do with the CRLF combinations in windows.

**Comment by dhruvmendiratta6** [comment] 2019-12-19 13:28
So should I just commit and make a PR?

**Comment by jksuom** [comment] 2019-12-19 13:38
I think you could do that. It will be easier to analyze the assertion error if it persists. You could also add a test for `integrate((x, x))` (that should raise an error).

**Comment by dhruvmendiratta6** [comment] 2019-12-19 13:49
How can I add a test?  Is it an example of the error output one would get, which would be in the commit message description?

**Comment by jksuom** [comment] 2019-12-19 18:04
You can use `raises` (with the proper error type) as in this example: https://github.com/sympy/sympy/blob/503df9491ed0f2cd30f52590b7f2ceb18ecb410f/sympy/core/tests/test_expr.py#L274

**Comment by dhruvmendiratta6** [comment] 2019-12-20 10:20
Will this be fine:
```
def test_as_poly():
    raises(PolynomialError, lambda: Tuple(x, x).as_poly(x))
    raises(PolynomialError, lambda: Tuple(x**2, x, y).as_poly(x))

```

**Comment by jksuom** [comment] 2019-12-20 11:09
I would expect `AttributeError` instead of `PolynomialError`. There already exists `test_as_poly_as_expr()` in `test_expr`. Maybe these lines could be added there. Then you could add `test_issue_18038()` that would run `lambda: integrate((x, x))` to `test_integrals`. (Probably with `AttributeError` again.)

**Comment by dhruvmendiratta6** [comment] 2019-12-20 20:56
I wanted to ask that the test which would be added in `test_integrals`:
`raises(AttributeError, lambda: integrate((x, x))` would always fail until the issue of adding better argument checking to `Poly.__new__()` is fixed. Am I right?

**Comment by jksuom** [comment] 2019-12-21 07:56
I think that `integrate((x, x))` should fail after `as_poly()` has been moved from `Basic` to `Expr` as `Tuple(x, x)` is not an instance of `Expr`. `raises(AttributeError, lambda: integrate((x, x)))` should then succeed.

**Comment by Saanidhyavats** [comment] 2019-12-24 06:21
I am interested to solve this issue, shall I start contributing on it.

**Closed** 2019-12-24 08:40 UTC
Labels: Easy to Fix

**Comment by dhruvmendiratta6** [comment] 2019-12-27 19:49
@jksuom I am not sure how I can check the changes I made as I switched branches (from the previous version of master to the issue specific branch) and there still is an output for 
`integrate((x, x))` as it gives `x**3/2 + x**2` 
and similarly with `as_poly()`
