### ISSUE TITLE
Buggy kinematics for serial chain manipulators

### ISSUE THREAD

**Issue by ash22194** [sympy/sympy#22956] opened 2022-01-29 22:55 UTC
I am trying out the serial chain manipulator [example](https://docs.sympy.org/latest/modules/physics/mechanics/examples/multi_degree_freedom_holonomic_system.html) in the sympy mechanics docs but am finding out that the kinematics sympy computes in the backend are buggy. I am attaching the file I use to test it. In the [example](https://docs.sympy.org/latest/modules/physics/mechanics/examples/multi_degree_freedom_holonomic_system.html), the velocity of the center of mass of the simple pendulum should be : 

> u1(t)*N_frame.x + l*u2(t)*B_frame.x + l*(u2(t) + u3(t))*C_frame.x

However, sympy returns : 

> u1(t)*N_frame.x + l*u3(t)/3*B_frame.x + l*u3(t)*C_frame.x

I tried to investigate this by looking at the definition of a PinJoint in sympy. It turns out every joint, when initialized calls the `_set_linear_velocity` function. In case of the PinJoint the `_set_linear_velocity` function calls `child.masscenter.v2pt_theory(parent.masscenter, parent.frame, child.frame)` to impose velocity constraints between the child and parent link mass centers. This velocity constraint is valid under the assumption that child and parent mass centers are fixed in the child frame (which is the frame attached to the center of mass of the child). This would hold true if the parent link has mass concentrated at one end (or at the joint i.e. COM and joint location coincide) but not if the joint location is anywhere other than the COM of the parent link.

Is there a way to define a serial chain manipulator in sympy without making such assumptions about the mass distribution of the links? I am attaching the code that I am using to test

```python
from sympy import zeros, symbols
from sympy.physics.mechanics import Body, PinJoint, PrismaticJoint, JointsMethod, inertia
from sympy.physics.mechanics import dynamicsymbols

q1, q2, q3, u1, u2, u3 = dynamicsymbols('q1, q2, q3, u1, u2, u3')
l, k, c, g, kT = symbols('l, k, c, g, kT')
ma, mb, mc, IBzz= symbols('ma, mb, mc, IBzz')

wall = Body('N')
block = Body('A', mass=ma)
IB = inertia(block.frame, 0, 0, IBzz)
compound_pend = Body('B', mass=mb, central_inertia=IB)
simple_pend = Body('C', mass=mc)

bodies = (wall, block, compound_pend, simple_pend)

slider = PrismaticJoint('J1', wall, block, coordinates=q1, speeds=u1)
rev1 = PinJoint('J2', block, compound_pend, coordinates=q2, speeds=u2,
                child_axis=compound_pend.z, child_joint_pos=l*2/3*compound_pend.y,
                parent_axis=block.z)
rev2 = PinJoint('J3', compound_pend, simple_pend, coordinates=q3, speeds=u3,
                child_axis=simple_pend.z, parent_joint_pos=-l/3*compound_pend.y,
                parent_axis=compound_pend.z, child_joint_pos=l*simple_pend.y)

joints = (slider, rev1, rev2)

print(simple_pend.masscenter.vel(wall.frame))
```

**Comment by soma2000-lang** [comment] 2022-01-30 12:51
@oscarbenjamin  I am working on this issue.

**Comment by moorepants** [comment] 2022-02-01 09:46
@sidhu1012 FYI

**Comment by moorepants** [comment] 2022-02-01 09:48
> Is there a way to define a serial chain manipulator in sympy without making such assumptions about the mass distribution of the links? 

The joints features were designed to work with any possible mass distribution (or at least that was the goal).

**Comment by moorepants** [comment] 2022-02-01 09:50
> This velocity constraint is valid under the assumption that child and parent mass centers are fixed in the child frame (which is the frame attached to the center of mass of the child).

It should be that the child mass center is fixed in the child frame and parent mass center is fixed in the parent frame.

> This would hold true if the parent link has mass concentrated at one end (or at the joint i.e. COM and joint location coincide) but not if the joint location is anywhere other than the COM of the parent link.

The joint location is fixed in the respective body and can be anywhere on that body.

**Comment by moorepants** [comment] 2022-02-01 09:52
> which is the frame attached to the center of mass of the child

Reference frames are not "attached" to points.

**Comment by moorepants** [comment] 2022-02-01 09:57
This example was based off of: https://pydy.readthedocs.io/en/latest/examples/multidof-holonomic.html

The velocity of point P_c in the N frame should be (see the above link):

u1*n_x + l*u_2*b_x + l*(u2 + u3)*c_x

which is what you say in the opening statement. If it produces something different, then yes, it is producing the incorrect velocity.

**Comment by moorepants** [comment] 2022-02-01 09:59
I've labeled, this a bug. I agree that it seems incorrect and that the `v2pt_theory` call shown in the opening comment is assuming that the mass centers are both fixed in the child frame. That is an incorrect assumption.

**Comment by TJStienstra** [comment] 2022-04-05 17:38
When checking `PinJoint._set_linear_velocity` I noticed the following:
- I think `self.child_point.set_vel(self.parent.frame, 0)` should actually be `self.child_point.set_vel(self.child.frame, 0)` (same is used in `PrismaticJoint`)
- With defining the `0` distance between `parent_point` and `child_point` and that both of them have `0` velocity in the frame, I would say that the velocity of the joint is defined. This also leads to the desired answer of `u1(t)*N_frame.x + l*u2(t)*B_frame.x + l*(u2(t) + u3(t))*C_frame.x`

Since I was playing around I did also try adding `self.child.masscenter.v2pt_theory(self.child_point, self.parent.frame, self.child.frame)`, which should be a correct replacement. However this results in `u1(t)*N_frame.x + l*u3(t)*C_frame.x`, which is again incorrect. To try traceback what goes wrong I ended up going to `Point.vel` [line 575](https://github.com/sympy/sympy/blob/master/sympy/physics/vector/point.py#L575), where this velocity is determined. Based on the following data the calculation is made:
- `self` is `C_masscenter`, `C_masscenter._vel_dict = {C_frame: 0, B_frame: l*u3(t)*C_frame.x}`
- `neighbor` is `A_masscenter`, `A_masscenter._vel_dict = {A_frame: 0, N_frame: u1(t)*N_frame.x}` and `C_masscenter.pos_from(A_masscenter) = - l*B_frame.y - l*C_frame.y`

This leads to `vel = l*u3(t)*C_frame.x`, which is added to the `neighbor` velocity in the `N_frame`, namely `u1(t)*N_frame.x`. This is obviously not correct. And it seems to be caused by the code implemented in [21730](https://github.com/sympy/sympy/pull/21730) (please correct me if I'm wrong).

**Comment by moorepants** [comment] 2022-04-13 18:29
Here is a figure:
![image](https://user-images.githubusercontent.com/276007/163245962-449aa5ec-123b-40c0-b57e-3a75686c3a14.png)

And these are the current lines:

```python
    def _set_linear_velocity(self):
        self.parent_point.set_vel(self.parent.frame, 0)
        self.child_point.set_vel(self.parent.frame, 0)
        self.child_point.set_pos(self.parent_point, 0)
        self.child.masscenter.v2pt_theory(self.parent.masscenter,
                                          self.parent.frame, self.child.frame)
```

I agree that the last line is incorrect. And should be:

```python
        self.child.masscenter.v2pt_theory(self.parent_point, # or self.child_point,
                                          self.parent.frame, self.child.frame)
```

**Comment by moorepants** [comment] 2022-04-13 18:33
> his is obviously not correct. And it seems to be caused by the code implemented in https://github.com/sympy/sympy/pull/21730 (please correct me if I'm wrong).

If you can make a simple test case based on what you found above, then you should write that test case. Make a PR with it. Then we should correct that automatic velocity calculation code so that it gives the correct result.

**Closed** 2022-04-23 06:04 UTC
Labels: physics.mechanics, Bug
