### ISSUE TITLE
Automatic int sympification with ipython

### ISSUE THREAD

**Issue by skirpichev** [sympy/sympy#2921] opened 2014-02-17 12:45 UTC
TODO from sympy/interactive/session.py (commented out code, deleted in #2219):
```python
# XXX: Something like this might be used, but it only works on single line
# inputs.  See
# http://mail.scipy.org/pipermail/ipython-user/2012-August/010846.html and
# https://github.com/ipython/ipython/issues/1491.  So instead we are forced to
# just monkey-patch run_cell until IPython builds a better API.
 class IntTransformer(object):
     """
     IPython command line transformer that recognizes and replaces int
     literals.

     Based on
     https://bitbucket.org/birkenfeld/ipython-physics/src/71b2d850da00/physics.py.

     """
     priority = 99
     enabled = True
     def transform(self, line, continue_prompt):
         import re
         from tokenize import TokenError
         leading_space = re.compile(' *')
         spaces = re.match(leading_space, line).span()[1]
         try:
             return ' '*spaces + int_to_Integer(line)
         except TokenError:
             return line

 int_transformer = IntTransformer()

 def enable_automatic_int_sympification(app):
     """
     Allow IPython to automatically convert integer literals to Integer.

     This lets things like 1/2 be executed as (essentially) Rational(1, 2).
     """
     app.shell.prefilter_manager.register_transformer(int_transformer)
```

**Comment by jcrist** [comment] 2015-04-21 20:41
Duplicate of #2839, closing.

**Closed by jcrist** 2015-04-21 20:41 UTC
