### ISSUE TITLE
v1.7: solve(set) incorrect for some Piecewise equations

### ISSUE THREAD

**Issue by zachjweiner** [sympy/sympy#20552] opened 2020-12-06 21:56 UTC
The following behavior was introduced in 1.7.

`simplify` in some circumstances transforms `sign(x)` into a `Piecewise` involving `x  / Abs(x)`; somehow this transformed expression can lead to incorrect solutions from `solve` and `solveset`.

Consider, e.g., `f(x) = x * sign(x)`, which has a zero at `x == 0`. After simplifying, even though the `Piecewise` function explicitly states the case `f(x) = 0` for `x = 0`, `solveset` does not find this as a root:

```python
>>> import sympy as sym
>>> x = sym.Symbol("x", real=True)
>>> func = x * sym.sign(x)
>>> sym.solveset(sym.Eq(func, 0), x, sym.S.Reals)
{0}
>>> sym.simplify(func)
Piecewise((0, Eq(x, 0)), (x**2/Abs(x), True))
>>> sym.solveset(sym.Eq(sym.simplify(func), 0), x, sym.S.Reals)
EmptySet
```

and likewise for `solve`. I'm unsure whether the change introduced in 1.7 was `simplify`'s handling of `sign` or something internal to the solvers.

Of course, this isn't the case for all piecewise functions, e.g.,

```python
>>> sym.solveset(sym.Piecewise((0, sym.Eq(x, 0)), (x**2 + 1, sym.Ne(x, 0))), x, sym.Reals)
{0}
```

It seems it could be unique to having the `Abs` in the denominator. To be clear, I don't think it's specific to `sign` - this was just how I encountered the error and it illustrates that solve[set]'s results can change just by simplifying input.

**Comment by oscarbenjamin** [comment] 2020-12-06 22:19
With 1.6.2 I get:
```python
In [9]: x = Symbol('x', real=True)                                                                                                

In [10]: solveset(x * sign(x), x, Reals)                                                                                          
Out[10]: {0}

In [11]: simplify(x*sign(x))                                                                                                      
Out[11]: x⋅sign(x)

In [12]: solveset(Piecewise((0, Eq(x, 0)), (x**2/Abs(x), True)), x, Reals)                                                        
Out[12]: ∅
```
With 1.7 I get:
```python
In [1]: x = Symbol('x', real=True)                                                                                                

In [2]: solveset(x * sign(x), x, Reals)                                                                                           
Out[2]: {0}

In [3]: simplify(x*sign(x))                                                                                                       
Out[3]: 
⎧ 0   for x = 0
⎪              
⎪  2           
⎨ x            
⎪───  otherwise
⎪│x│           
⎩              

In [4]: solveset(Piecewise((0, Eq(x, 0)), (x**2/Abs(x), True)), x, Reals)                                                         
Out[4]: ∅
```
The behaviour of solveset seems to be the same in both versions but the behaviour of simplify has changed.

I've bisected the change in simplify to 7097b50fb410dc4c4fd30b504e861ef10f258447 from #19596.

It's not clear to me that the change in simplify output is an improvement in general but it is not invalid. The failure of `solveset` is a bug in both 1.6.2 and 1.7.

**Comment by oscarbenjamin** [comment] 2020-12-06 23:36
It seems that `solveset` finds the solution `x=0` but then removes it here:
https://github.com/sympy/sympy/blob/425353e982439dc64f3d33876cce291aac628ed8/sympy/solvers/solveset.py#L1101-L1105
The `domain_check` function goes through all args of the expression looking for any possible divide by zero but it does not distinguish the different args of a Piecewise:
https://github.com/sympy/sympy/blob/425353e982439dc64f3d33876cce291aac628ed8/sympy/solvers/solveset.py#L431-L439
The presence of the `1/abs(x)` in the Piecewise fails this test.

We can make a simpler demonstration:
```julia
In [1]: p = Piecewise((0, Eq(x, 0)), (1/x, True))                                                                                 

In [2]: p                                                                                                                         
Out[2]: 
⎧0  for x = 0
⎪            
⎨1           
⎪─  otherwise
⎩x           

In [3]: solveset(p, x, Reals)                                                                                                     
Out[3]: ∅
```

We can work around this with this diff:
```diff
diff --git a/sympy/solvers/solveset.py b/sympy/solvers/solveset.py
index ff0459954e..79ffe9df18 100644
--- a/sympy/solvers/solveset.py
+++ b/sympy/solvers/solveset.py
@@ -436,6 +436,25 @@ def _domain_check(f, symbol, p):
         return True
     elif f.subs(symbol, p).is_infinite:
         return False
+    elif isinstance(f, Piecewise):
+        # Check the cases of the Piecewise in turn. There might be invalid
+        # expressions in later cases that don't apply e.g.
+        #    solveset(Piecewise((0, Eq(x, 0)), (1/x, True)), x)
+        for expr, cond in f.args:
+            condsubs = cond.subs(symbol, p)
+            if condsubs is S.false:
+                continue
+            elif condsubs is S.true:
+                return _domain_check(expr, symbol, p)
+            else:
+                # We don't know which case of the Piecewise holds. On this
+                # basis we cannot decide whether any solution is in or out of
+                # the domain. Ideally this function would allow returning a
+                # symbolic condition for the validity of the solution that
+                # could be handled in the calling code. In the mean time we'll
+                # give this particular solution the benefit of the doubt and
+                # let it pass.
+                return True
     else:
+        # We should not blindly recurse through all args of arbitrary expressions like this:
         return all([_domain_check(g, symbol, p)
                     for g in f.args])
```

Really there needs to be a better way to determine which parts of the expression to check here rather than simply recursing through all args. Perhaps an alternative fix would be to avoid recursing through the args altogether.

With the diff above we have:
```python
In [1]: solveset(Piecewise((0, Eq(x, 0)), (1/x, True)), x, Reals)                                                                 
Out[1]: {0}

In [2]: solveset(x*sign(x), x, Reals)                                                                                             
Out[2]: {0}

In [3]: solveset(simplify(x*sign(x)), x, Reals)                                                                                   
Out[3]: {0}

In [4]: solveset(Piecewise((0, Eq(x, 0)), (x**2/Abs(x), True)), x, Reals)                                                         
Out[4]: {0}
```

I wouldn't count this as a "regression" since 1.6.2 so I don't think the fix needs to go into the 1.7.1 bugfix release.

The diff above passes all tests in `test_solveset.py`. I'm marking this as easy to fix so that someone else can open a PR.

**Comment by zachjweiner** [comment] 2020-12-07 20:10
Thanks for digging into this, @oscarbenjamin!

I encountered a similar (or possibly related) issue (happy to open a new issue if needed), again relating to inconsistency in the results of `solve` and `solveset` just from simplifying input:

```python
In [1]: import sympy as sym

In [2]: x = sym.symbols('x')
   ...: p = sym.symbols('p', positive=True, rational=True)
   ...: func = (1 - x**p) * x**p / x
   ...: func
Out[2]: x**p*(1 - x**p)/x

In [3]: sym.solveset(func, x, sym.Reals)
Out[3]: FiniteSet(1)

In [4]: sym.solve(func, x, sym.Reals)
Out[4]: [(1, Reals)]

In [5]: sym.simplify(func)
Out[5]: x**(p - 1)*(1 - x**p)

In [6]: sym.solveset(sym.simplify(func), x, sym.Reals)
Out[6]: ConditionSet(x, Eq(x**(p - 1)*(1 - x**p), 0), Reals)

In [7]: sym.solve(sym.simplify(func), x, sym.Reals)
Out[7]: [(1, Reals), (0**(1/(p - 1)), Reals)]
```
Certainly `x=1` should be found as a valid root no matter what. And, regardless of the form of the input, `0` is a root for `p > 1`, so one might expect that in some form.

Both this and the original issue vaguely "feel" like some logic that could do a better job synthesizing parts of the input expression, but I am mostly ignorant of the internals here. If a straightforward resolution is apparent, I'd be willing to attempt a PR (but no promises for how quickly). Thanks again!

**Comment by oscarbenjamin** [comment] 2020-12-08 18:30
There is something of a conceptual problem around divide by zero in sympy that is not quite resolved. Both `solve` and `solveset` try to exclude "singularities" from solutions by checking for any zeros of any denominator so e.g.:
```python
In [169]: expr = x**2/(1/x - sqrt(2)/x)                                                                                           

In [170]: expr                                                                                                                    
Out[170]: 
    2   
   x    
────────
  √2   1
- ── + ─
  x    x

In [171]: expr.limit(x, 0, '+-')                                                                                                  
Out[171]: 0

In [172]: solve(expr)                                                                                                             
Out[172]: []

In [173]: solve(expr, check=False)                                                                                                
Out[173]: [0]

In [174]: expr.subs(x, 0)                                                                                                         
Out[174]: nan
```
This example (more or less) comes from the docstring of `solve` which discusses this.

I think the idea is that although the limit is well defined in the neighbourhood of zero the expression is not defined *at zero* and therefore zero is not a true root. A true root should have the property that you can substitute it into the expression and it should evaluate to zero rather than nan. Both `solve` and `solveset` adhere to this convention that if any part of the expression has a singularity at the "root" then it is not a proper root.

However the rest of sympy does not necessarily respect carefully avoiding divide by zero for expressions that might be zero e.g.:
```python
In [176]: x**4 / x                                                                                                                
Out[176]: 
 3
x 
```
Likewise the example you show with `simplify(x**p/x)`. This kind of cancellation is allowed in both automatic evaluation and simplification. We are left with a situation where the roots of an expression depend on the precise form but the manipulation routines do not preserve that form. I guess that means that in some cases `solve(simplify(expr)) != solve(expr)`. We have three choices:

1. Accept that sometimes `solve(simplify(expr)) != solve(expr)`.
2. Limit possible simplifications unless we are sure that we are not multiplying or dividing by zero or infinity.
3. Allow solve to return roots for which the expression might have singularities.

Right now sympy seems to have converged around 1 but elements of 2 and 3 are found in the codebase as well.

> Certainly `x=1` should be found as a valid root no matter what.

In a sense it is:
```python
In [181]: C = ConditionSet(x, Eq(x**(p - 1)*(1 - x**p), 0), Reals)                                                                

In [182]: 1 in C                                                                                                                  
Out[182]: True
```
I'm not sure how solveset ends up with that condition set but it might be possible to get it to return something like
```python
In [196]: FiniteSet(1) | ConditionSet(x, Eq(x**(p-1), 0), FiniteSet(0))                                                           
Out[196]: 
      ⎧              ⎛ p - 1    ⎞⎫
{1} ∪ ⎨x | x ∊ {0} ∧ ⎝x      = 0⎠⎬
      ⎩                          ⎭
```

**Comment by zachjweiner** [comment] 2020-12-09 14:49
> 1. Accept that sometimes solve(simplify(expr)) != solve(expr).
> 2. Limit possible simplifications unless we are sure that we are not multiplying or dividing by zero or infinity.
> 3. Allow solve to return roots for which the expression might have singularities.
>
> Right now sympy seems to have converged around 1 but elements of 2 and 3 are found in the codebase as well.

Are there any relevant discussions/etc you could link me to regarding the choice of 1? Naively, I would strongly oppose 1, but I'm curious about whatever nuances may have lead to this approach.

As a perhaps more robust variant of 3, I would propose that such roots be returned as some conditional object - since 0 given `p > 1` should be a valid solution, I think. (FWIW, this is what Mathematica returns.) At least that way one can iterate over solution sets and handle instances of that conditional type separately.

> I'm not sure how solveset ends up with that condition set 

Well, it's just trivially returning the problem statement, of course (the equality in the `ConditionSet` is identical to the input expression).

While `root in ConditionSet(...)` is quite nice - thanks for pointing that out - one would still like to actual iterate over (a finite set of) solutions, when there is one. My particular use case of `solve` before 1.7 was to do this, and I've had to resort to essentially hacks to have sympy continue to return that particular solution for this expression (as `solvify` cannot handle `ConditionSet`s) in a manner which is consistently iterable for all inputs.

I guess my vote would be for anything that prevents breakage from sympy version to sympy version for "silly" reasons like changes to the behavior of `simplify`. For a user like me (and in principle for hypothetical users of the functionality I've developed), these inconsistencies across versions and forms of expressions can be frustrating, as I'm sure you understand. I'd be happy to discuss this more and/or contribute along these lines, if I can be helpful.

**Comment by oscarbenjamin** [comment] 2020-12-09 18:41
> Are there any relevant discussions/etc you could link me to regarding the choice of 1? Naively, I would strongly oppose 1, but I'm curious about whatever nuances may have lead to this approach.

I don't know of a good place where these things are discussed. I'm not sure of the origin of checking all of the denominators like this. I'm not particularly advocating solution 1 but rather observing the existing codebase.

The other point here is about the conditional existence of solutions which is something that is discussed in #16861

**Comment by oscarbenjamin** [comment] 2020-12-20 13:04
> I guess my vote would be for anything that prevents breakage from sympy version to sympy version for "silly" reasons like changes to the behavior of `simplify`.

I agree but I'm not sure what the right "policy" is. One possibility is to avoid changes to `simplify` but it still has plenty of room for improvement to handle more cases etc so I don't think that's what anyone wants. Another could be to add options for allowing potentially singular solutions e.g. `check=False`. Another could be to add an option to simplify that makes it more strict about e.g. cancelling possibly zero denominators.

My suggestion for a downstream codebase in general is to avoid using the general `simplify` function though. There are many more precise simplification routines (that it also uses internally) which are more efficient and have more precisely defined behaviour e.g. `cancel`, `expand`, `trigsimp`, `factor`, `factor_terms`, `powsimp`. The `simplify` function is intended to be the ultimate DWIM (do what I mean) which makes its semantics not well defined.

**Comment by baekg** [comment] 2020-12-20 13:47
can I work on this issue?

**Comment by oscarbenjamin** [comment] 2020-12-20 14:35
Yes

**Closed** 2020-12-26 15:20 UTC
Labels: Easy to Fix, good first issue, solvers.solveset

**Comment by zachjweiner** [comment] 2020-12-29 19:13
> My suggestion for a downstream codebase in general is to avoid using the general simplify function though.
> 
> The simplify function is intended to be the ultimate DWIM (do what I mean) which makes its semantics not well defined.

This is reasonable. Thanks for sharing your insights on this.

And thanks for the fix, @0sidharth and @oscarbenjamin!

**Comment by oscarbenjamin** [comment] 2021-01-04 18:24
The behaviour of piecewise in simplify was also reported on SO here: https://stackoverflow.com/questions/65563495/in-sympy-how-to-prevent-simplify-from-returning-a-piecewise

I think most users would not think that introducing Piecewise makes the expression "simpler"
