### ISSUE TITLE
No way for rounding an exponent (2 ** Round(a)), that works for constants and Symbols

### ISSUE THREAD

**Issue by ducktalez** [sympy/sympy#27326] opened 2024-11-28 11:35 UTC
Is there a way to cut/round decimals in an exponent?
I tried:
- `N( )`, I guess, the sympiest way
- `Integer( )`
- 'Modulo (%)'
- `round( )`
Is something from the above supposed to work? Some things work for strings, but mostly not for Symbols
I had to write a custom function, which seems a little odd.

```python
class Round_dummy(Function):

    @classmethod
    def eval(cls, a):
        if a.is_symbol:  # !! Must be checked before .is_number, crashes otherwise on symbols!
            return
        elif a.is_number:
            return round(a)

    def _sympy_(self, a):
        return eval(self, a)
```

Complete experiments:

```python
import sympy
from sympy import Function, Symbol


# N( )
a = sympy.sympify('Pow(a, N(1.2341, 1))')   # -> 1
b = sympy.sympify('Pow(2, N(a, 1))')            # -> 2**a
print('N( ):\n', a, b)
# sympy.sympify('Pow(2, N(a, 1))', locals={'a': Symbol('a')})  # -> AttributeError: ->
# # -> AttributeError: 'function' object has no attribute 'evalf'

# Integer(1.234)
a = sympy.sympify('Integer(1.234)')     # -> 1
print('Integer()\n', a)
# sympy.sympify('Integer(a)')         # -> TypeError: Argument of Integer should be of numeric type, got a.
# sympy.sympify('Integer(a)', locals={'a': Symbol('a', numeric=True)})  # -> TypeError ->
# # -> TypeError: int() argument must be a string, a bytes-like object or a real number, not 'Symbol'

# Modulo (%)
a = sympy.sympify('1.234 - (1.234 % 1)')                                  # -> 1
b = sympy.sympify('Pow(2, (a-(a % 1)))', locals={'a': 1.234})             # -> 2
print('Modulo (%)\n', a, b)
# sympy.sympify('Pow(2, (a-(a % 1)))', locals={'a': Symbol('a')})       # -> Typeerror ->
# # -> TypeError: unsupported operand type(s) for %: 'Symbol' and 'One'

# round()
a = sympy.sympify('round(1.234)')             # -> 1
b = sympy.sympify('Pow(2, round(1.234))')     # -> 2
print('round(1.234)\n', a, b)
# c = sympy.sympify('Pow(2, round(a))')         # TypeError: Cannot round symbolic expression

# custom Round_dummy class
class Round_dummy(Function):

    @classmethod
    def eval(cls, a):
        if a.is_symbol:  # !! Must be checked before .is_number, crashes otherwise on symbols!
            return
        elif a.is_number:
            return round(a)

    def _sympy_(self, a):
        return eval(self, a)

a = sympy.sympify('Round_dummy(1.234)', locals={'Round_dummy': Round_dummy})  # -> 1
b = sympy.sympify('2**Round_dummy(1.234)', locals={'Round_dummy': Round_dummy})  # -> 2
c = sympy.sympify('Round_dummy(a)', locals={'Round_dummy': Round_dummy})  # -> Round_dummy(a)
d = sympy.sympify('2**Round_dummy(a)', locals={'Round_dummy': Round_dummy})  # -> 2**Round_dummy(a)
e = sympy.sympify('Round_dummy(a)', locals={'Round_dummy': Round_dummy, 'a': Symbol('a', is_number=True)})
x = sympy.sympify('2**Round_dummy(a)', locals={'Round_dummy': Round_dummy, 'a': Symbol('a', is_number=True)})
final = sympy.sympify('2**Round_dummy(a)', locals={'Round_dummy': Round_dummy, 'a': Symbol('a', is_number=True)})
final = final.evalf(subs={Symbol('a', is_number=True): 1.234})
print('Round_dummy(1.234)\n', a, b, c, d, e, x, final)
```

**Comment by oscarbenjamin** [comment] 2024-11-28 12:43
I think this is a duplicate of gh-23052

**Closed** 2024-12-01 15:11 UTC
