### ISSUE TITLE
Float with replace

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#19976] opened 2020-08-17 12:43 UTC
`(2*x+7).evalf().replace(lambda e: e.is_Float, lambda e: Integer(e))` doesn't give `2x+7`

**Comment by rijusougata13** [comment] 2020-08-20 06:39
can you clarify further .? can you mention the file path to be change

**Comment by oscarbenjamin** [comment] 2020-08-23 17:38
It should be possible to use replace like this to convert Float to Integer. We can e.g. replace the Floats with exp like:
```julia
In [26]: e = (2*x + 7).evalf()                                                                                                                                

In [27]: e                                                                                                                                                    
Out[27]: 2.0⋅x + 7.0

In [28]: e.replace(lambda e: e.is_Float, lambda e: exp(e))                                                                                                    
Out[28]: 7.38905609893065⋅x + 1096.63315842846

In [29]: e.replace(lambda e: e.is_Float, lambda e: exp(Integer(e)))                                                                                           
Out[29]: 
   2    7
x⋅ℯ  + ℯ
```
We want to replace each Float by an Integer having the same value so
```julia
In [30]: e.replace(lambda e: e.is_Float, lambda e: Integer(e))                                                                                                
Out[30]: 2.0⋅x + 7.0
```
The problem is that Float and Integer compare equal:
```julia
In [31]: S(2.0)                                                                                                                                               
Out[31]: 2.00000000000000

In [32]: S(2)                                                                                                                                                 
Out[32]: 2

In [33]: S(2.0) == S(2)                                                                                                                                       
Out[33]: True
```
So `replace` doesn't think that any replacement needs to be made:
https://github.com/sympy/sympy/blob/40be6f58bdc1323310759aa9ab268762ca330cf4/sympy/core/basic.py#L1486
At that line `v` will be `Integer(2)` and `expr` will be `Float(2)`. Since they compare equal no replacement happens.

The root of this is the fact that `Integer(2) == Float(2)` is a violation of the principle of structural equality. Expressions should not compare equal unless they are entirely interchangeable which is never true when comparing a Float and an Integer.

See also #19915, #16924, #11707

**Comment by smichr** [comment] 2021-03-18 23:59
If you don't want to use `nsimplify(expr. rational=True)` then then following safe replacement can be done:
```python
def f2i(e):
     if not isinstance(e, Expr): return e
     mask = {i: Dummy() for i in e.atoms(Symbol) if i.name.isdigit()}  # existing symbols with integer-like name
     ints = {i: Dummy() for i in e.atoms(Float) if i == int(i)}  # {1.0: Dummy()}
     return e.xreplace(mask).xreplace(ints).xreplace({v:int(k) for k,v in ints.items()})
```
For example,
```python
>>> f2i(3.14+3.0*I)
3.14 + 3*I
```

**Comment by smichr** [comment] 2021-03-19 17:33
If, instead of using lambdas in xreplace you build the dictionary of replacements as shown [here](https://stackoverflow.com/questions/59296496/converting-all-redundant-floats-in-a-string-to-integers/59305338#59305338), that works, too:

```python
>>> eq=(3.14+3.*I)
>>> intfloats = lambda x: dict([(i,int(i)) for i in x.atoms(Float) if i==int(i)])
>>> eq.xreplace(intfloats(eq))  # like eq.xreplace{i:int(i) for i in eq.atoms(Float) if i==int(i)})
3.14 + 3*I
```

**Comment by proy87** [comment] 2021-03-21 10:55
@smirch I noticed that `int(Float('2.0'))` returns `int`, not `Integer`. Is this interntiaonal?
If yes, then it is better to write  `intfloats = lambda x: dict([(i,Integer(i)) for i in x.atoms(Float) if i==int(i)])` if one wants to manipulate the expression further.

**Comment by smichr** [comment] 2021-05-26 17:32
`replace` cannot be used to make this change because equality testing of the old and new expression fails to distinguish all floats from their rational counterparts:

```python
>>> assert 0.5 == S.Half
>>> assert 1.0 == S.One
>>> 0.3 == Rational(3, 10)
False
```
So using `xreplace` or subs is the solution until #20033 or similar is committed.

**Closed** 2023-09-10 22:26 UTC
Labels: core, floats
