### ISSUE TITLE
undesired (wrong) substition behavior in sympy? 

### ISSUE THREAD

**Issue by andres-ordonez** [sympy/sympy#11746] opened 2016-10-20 07:46 UTC
I'm getting this undesired behavior in sympy

In [1]: x = sy.var('x', real=True)

In [2]: (1/x).subs(x**2,1)
Out[2]: 1

Clearly, this should not be the case. Out[2] should be 1/x. Am I missing something or is this a bug?

**Comment by khan08** [comment] 2016-10-20 14:51
I think it should be 1 instead of 1/x. The first argument is the variable and the second is the substitution. So your substituting x when x**2=1. If you try (1/x).subs(x**2,4), you will get 1/2.

**Comment by andres-ordonez** [comment] 2016-10-20 15:25
The problem is that when x**2=1 x can be either 1 or -1. The subs method is assuming x is positive.

**Comment by oscarbenjamin** [comment] 2019-03-13 20:06
This seems to be fixed now:
```julia
In [131]: (1/x).subs(x**2,1)                                                                                                                                  
Out[131]: 
1
─
x
```

**Comment by sachin-4099** [comment] 2019-10-07 09:15
Is this fixed? I am not able to understand the output. @oscarbenjamin @smichr

**Comment by oscarbenjamin** [comment] 2019-10-07 10:24
It can be fixed if someone adds a regression test.

**Comment by sachin-4099** [comment] 2019-10-07 10:25
I am ready to work on it. Just guide me as to what to do.

**Comment by namannimmo10** [comment] 2019-12-27 16:54
I'm working on this issue. @oscarbenjamin @smichr 
I'll add a regression test but before that, can you please verify if the output below is the same as expected. 

Input -->  `(1/x).subs(x**2,  1)`
Out --> `1/x`

Input --> `(1/(x**4)).subs(x**2, 1)`
Out --> `1`

Input --> `(1/(x**3)).subs(x**2, 1)`   # this should print 1/x instead. 
Out -->` x**(-3)`

**Comment by oscarbenjamin** [comment] 2019-12-27 19:34
I would prefer it if the middle one didn't substitute but that's apparently deliberate behaviour so I don't suggest changing it.

So yes those three tests are correct.

**Closed** 2019-12-29 00:02 UTC
Labels: Easy to Fix, core, good first issue
