### ISSUE TITLE
resultant failed when complex polynomials

### ISSUE THREAD

**Issue by VegetChick** [sympy/sympy#16646] opened 2019-04-14 08:12 UTC
When I calculate the resultant of (0.000434782608695652*P2 + 0.198325410628019*mC**2 - 1.0, M - mC + 3, mC), the Error was raised:
sympy.polys.polyerrors.PolynomialDivisionFailed: couldn't reduce degree in a polynomial division algorithm when dividing [-1.0, M + 3.0] by [0.198325410628019*M**2 + 1.18995246376812*M + 0.000434782608695652*P2 + 0.784928695652174]. This can happen when it's not possible to detect zero in the coefficient domain. The domain of computation is RR[M,P2]. Zero detection is guaranteed in this coefficient domain. This may indicate a bug in SymPy or the domain is user defined and doesn't implement zero detection properly.
Anybody knows what's wrong with this error? I'm not very good at mathematics. I think this is a bug of sympy because this can be calculated by mathematica.

**Comment by jksuom** [comment] 2019-04-14 09:45
It looks like a rounding error. It may have been fixed in current master.

**Comment by VegetChick** [comment] 2019-04-14 10:18
No, the error will be still raised after upgrade. In fact, I'm confused about why the polynomials division is involved in the process of calculating the resultant. Is the formula of resultant is a symbolic matrix of coefficients in two polynomials?

**Comment by jksuom** [comment] 2019-04-14 11:09
Can you write the polynomials in reproducible form using backquotes? Division is involved because the determinant computation of a big polynomial matrix is very slow.

**Comment by VegetChick** [comment] 2019-04-14 11:29
This is the form i called: `resultant(0.000434782608695652*P2+0.198325410628019*mC**2 - 1.0, M - mC + 3, mC)`

**Comment by jksuom** [comment] 2019-04-14 11:36
This is what I get on current master 1.5.dev:
```
>>> M, P2, mC = symbols('M P2 mC')
>>> resultant(0.000434782608695652*P2+0.198325410628019*mC**2 - 1.0, M - mC + 3, mC)
0.198325410628019*M**2 + 1.18995246376811*M + 0.000434782608695652*P2 + 0.784928695652171
```

**Comment by VegetChick** [comment] 2019-04-14 11:43
Thank you so much!!! One more question. How can I install the Sympy 1.5? There is 1.4 on pypi and there is even 1.3 on Anaconda.

**Comment by jksuom** [comment] 2019-04-14 12:07
SymPy 1.5 has not been released yet but you can install `git` and then clone the development directory by running (in a suitable directory)
`git clone git://github.com/sympy/sympy.git`.

That will create a new subdirectory `sympy`. It is possible to run the master version from that directory. It is also possible to install SymPy elsewhere by `python setup.py install` so it can be used from any location.

**Comment by VegetChick** [comment] 2019-04-14 12:09
Thank you again! It is exactly helpful!

**Comment by oscarbenjamin** [comment] 2019-04-14 23:38
Should this issue be closed?

**Comment by VegetChick** [comment] 2019-04-15 02:57
Yes, the problem has been solved.

**Closed** 2019-04-15 05:24 UTC
Labels: polys
