### ISSUE TITLE
[GSoC] Adding doit method in symbolic Probability

### ISSUE THREAD

**Issue by Smit-create** [sympy/sympy#19267] opened 2020-05-07 17:53 UTC
Currently, in `stats/symbolic_probability.py`, the three classes `Expectation`, `Variance`, and `Covariance` have `doit` method. Therefore, I plan to add a doit method to Probability class.
https://github.com/sympy/sympy/blob/6c4df1745df098821047cd7e389091b545d5829f/sympy/stats/symbolic_probability.py#L37-L54

It would something like,
```python
def doit(self, ** hints):
    expr = self.args[0]
    condition = self._condition
    if not expr.has(RandomSymbol):
        return expr
    if isinstance(expr, And):
        rv_combs = list(itertools.combinations(expr.args , 2))
        if all([not dependent(*rv_pair) for rv_pair in rv_combs]) :
            return Mul(*[Probability(arg, condition).doit() for
                                arg in expr.args])

    if isinstance(expr, Or) :
        return Add(*[Probability(arg, condition) for arg in expr.args]) -
        Probability(And(*expr.args), condition).doit()

    if condition is not None :
        return Probability(And(expr, condition)).doit()
        / Probability(condition).doit()

    return self
```
ping @czgdp1807 @Upabjojr

**Comment by czgdp1807** [comment] 2020-05-07 18:04
As an end user, I would have expected, `Expectation(X + Y).doit()` to give `0` but the following happens,
```python
>>> from sympy.stats import *
>>> X = Normal('X', 0, 1)
>>> Y = Normal('Y', 0, 1)
>>> Expectation(X + Y)
Expectation(X + Y)
>>> Expectation(X + Y).doit()
Expectation(X) + Expectation(Y)
>>> E(X + Y)
0
```
Is this the expected behaviour?

**Comment by Smit-create** [comment] 2020-05-07 18:11
According to me, after reading all the documentation of the file,  the `symbolic_probability.py` was to carry out the symbolic simplification of `stats`. Also, they are only used when we have unevaluated results or symbolic results. So, I think, it is meant for simplification at present and reducing to more simplest form

**Comment by czgdp1807** [comment] 2020-05-07 18:23
The documentation at https://docs.sympy.org/latest/modules/core.html#sympy.core.basic.Basic.doit suggests that `doit` was meant to reduce the expression recursively, if called without any hints, but if arguments like, `deep=False` are passed then the expression is evaluated upto a certain limit. IMHO, once doit is called on any random expression involving, P, E or V, the expression should be processed according to the documentation above for maintaining consistency. 
```python
>>> Expectation(X + Y).doit(deep=False)
Expectation(X) + Expectation(Y) # May be this is a bit correct, though views of someone more experienced with working of `doit` are needed.
```
@asmeurer @smichr  Any thoughts?

**Comment by oscarbenjamin** [comment] 2020-05-07 20:01
The idea is that some objects evaluate automatically (`Pow(2, 2)`) and others do not (`Integral(x, x)`). Those that normally evaluate automatically should check in `__new__` for evaluate=False and global evaluate and return an unevaluated object in some cases.

If the object is unevaluated then `.doit` should do the evaluation. For an object that automatically evaluates the following should be equivalent:
```
Obj(arg) == Obj(arg, evaluate=False).doit(deep=False)
```

If `Expectation` is like `Integral` then `E` is like `integrate`. Ideally `E` should be implemented as `Expectation(...).doit()` (possibly with `deep=False`).

**Comment by Smit-create** [comment] 2020-05-08 04:13
```python
>>> from sympy.stats import *
>>> X = Normal("X", 3, 2)
>>> Y = Normal("Y", 0, 1)
>>> Expectation(X+Y, evaluate=False).doit(deep=False)
Expectation(X) + Expectation(Y)
>>> Expectation(X+Y, evaluate=False).doit(deep=True)
Integral(sqrt(2)*Y*exp(-Y**2/2)/(2*sqrt(pi)), (Y, -oo, oo)) + Integral(sqrt(2)*X*exp(-(X - 3)**2/8)/(4*sqrt(p
i)), (X, -oo, oo))
>>> Expectation(X+Y, evaluate=True).doit() # deep may be True/False 
3
```
How if we implement this way?

**Comment by czgdp1807** [comment] 2020-05-08 15:01
All the outputs are according to intuition in your example. As an end user I would expect such things to happen. The question is should we `deep=True` as default for `.doit()`. I think it should be the case, as the name, `doit` suggests that it will do the whole expression.

**Comment by oscarbenjamin** [comment] 2020-05-08 15:13
With `deep=True` (the default) then `doit` should recursively call doit on all args as well so there should be no unevaluated integrals. It's important that `doit` idempotent: there should never be any need to call it twice.

The point of deep=False is to say I just want this object to evaluate without recursively going through all args and evaluating them e.g.:
```julia
In [9]: I = Integral(x + Integral(y, y), x)                                                                                                    

In [10]: I                                                                                                                                     
Out[10]: 
⌠                
⎮ ⎛    ⌠     ⎞   
⎮ ⎜x + ⎮ y dy⎟ dx
⎮ ⎝    ⌡     ⎠   
⌡                

In [11]: I.doit()                                                                                                                              
Out[11]: 
 2      2
x    x⋅y 
── + ────
2     2  

In [12]: I.doit(deep=False)                                                                                                                    
Out[12]: 
 2           
x      ⌠     
── + x⋅⎮ y dy
2      ⌡   
```

Also I think it's important that evaluation model is understandable so you should ensure that `E(Z)` is always equivalent to `Expectation(Z).doit()` (ideally `E(Z)` should literally be written like that).

**Comment by czgdp1807** [comment] 2020-05-08 15:20
If `deep=False` is the default then, the output will be like, `Out[12]` which is quite unexpected. So, I think `E.doit()` should work like, `I.doit()` because as of now, `E` behaves as `integrate` i.e., both evaluate the expressions completely.

**Comment by oscarbenjamin** [comment] 2020-05-08 15:36
The default for `deep` should be `True`. This is a method on `Basic` and the signature for should be the same for all of `Basic`.

**Comment by Smit-create** [comment] 2020-05-08 15:54
So, if we keep `evaluate=True` and `deep=True` in `doit`, then is [https://github.com/sympy/sympy/issues/19267#issuecomment-625619971](https://github.com/sympy/sympy/issues/19267#issuecomment-625619971) good to be implemented? 
or the other way could remove the `evaluate` option and keep only two possibilities as:
when `deep=False` give unevaluated integrals
when `deep=True` give evaluated result
Which options seems better?
```python
>>> from sympy.stats import *
>>> X = Normal("X", 3, 2)
>>> Y = Normal("Y", 0, 1)
>>> Expectation(X+Y).doit(deep=False)
Integral(sqrt(2)*Y*exp(-Y**2/2)/(2*sqrt(pi)), (Y, -oo, oo)) + Integral(sqrt(2)*X*exp(-(X - 3)**2/8)/(4*sqrt(p
i)), (X, -oo, oo))
>>> Expectation(X+Y).doit(deep=True)
3

```

**Comment by czgdp1807** [comment] 2020-05-09 07:12
`Expectation(X+Y).doit(deep=True/False)` should give the same result as there isn't any nesting of expressions. Value of `deep` will make a difference in cases like, `Expectation(X+Expectation(Y))`.
So, some expected outputs are,
```python
>>> from sympy.stats import *
>>> X = Normal("X", 3, 2)
>>> Y = Normal("Y", 0, 1)
>>> Expectation(X+Y, evaluate=False).doit(deep=False)
Expectation(X + Y)
>>> Expectation(X+Y, evaluate=False).doit(deep=True)
3
>>> Expectation(X+Y, evaluate=True).doit() # deep may be True/False 
3
>>> Expectation(X+Expectation(Y)).doit()
3
>>> Expectation(X+Expectation(Y)).doit(deep=False)
3 + Expectation(Expectation(Y)) # We do not know whether `Expectation(Y)` will be a random expression so Expectation(Expectation(Y)) is left as it is.
```
P.S. Ignore https://github.com/sympy/sympy/issues/19267#issuecomment-625858111 as I earlier agreed to the outputs generated. On thinking carefully, I have concluded that value of `deep` should matter only when there is a nesting of operators like, the case described above.

**Comment by Upabjojr** [comment] 2020-05-10 18:05
```python
>>> Expectation(X + Y).doit()
Expectation(X) + Expectation(Y)
```

This should be the behaviour of `Expectation(X + Y).expand()`.

> If `deep=False` is the default then, the output will be like, `Out[12]` which is quite unexpected. So, I think `Expectation.doit()` should work like, `Integral.doit()` because as of now, `E` behaves as `integrate` i.e., both evaluate the expressions completely.

I would like `E` to return `Expectation`... that is, change its current behaviour. I agree that `Expectation.doit()` should behave like the current `E`.

**Comment by czgdp1807** [comment] 2020-05-10 20:11
> This should be the behaviour of `Expectation(X + Y).expand()`

The current behaviour. This can be fixed in a separate PR other than the `doit` one.
```python
>>> from sympy.stats import *
>>> X = Normal('X', 0, 1)
>>> Y = Normal('Y', 0, 1)
>>> Expectation(X + Y).expand()
Expectation(X + Y)
```

**Comment by Smit-create** [comment] 2020-05-11 02:38
From the above comments this can be summarised as:
```python
>>> from sympy.stats import *
>>> X = Normal('X', 0, 1)
>>> Y = Normal('Y', 0, 1)
>>> Expectation(X + Y).expand()
Expectation(X) + Expectation(Y)
>>> Expectation(X+Y, evaluate=False).doit(deep=False)
Expectation(X + Y)
>>> Expectation(X+Y, evaluate=True).doit() # deep may be True/False 
3
>>> Expectation(X+Expectation(Y)).doit()
3
>>> Expectation(X+Expectation(Y)).doit(deep=False)
3 + Expectation(Expectation(Y)) # We do not know whether `Expectation(Y)` will be a random expression so Expectation(Expectation(Y)) is left as it is.
```

I had only one doubt that should we return unevalated integral with `evaluate=False` and `deep=True`?
i.e,
```python
>>> Expectation(X+Y, evaluate=False).doit(deep=True)
Integral(sqrt(2)*Y*exp(-Y**2/2)/(2*sqrt(pi)), (Y, -oo, oo)) + Integral(sqrt(2)*X*exp(-(X - 3)**2/8)/(4*sqrt(pi)), (X, -oo, oo))
```
or 
```python
>>> Expectation(X+Y, evaluate=False).doit(deep=True)
3
```

If all the above are expected output the, I'll try to fix them opening a PR.

**Comment by czgdp1807** [comment] 2020-05-11 05:03
> ```python
> >>> Expectation(X+Y, evaluate=False).doit(deep=True)
> 3
> ```

I would prefer this one.

**Comment by Upabjojr** [comment] 2020-05-11 06:25
> I had only one doubt that should we return unevalated integral with `evaluate=False` and `deep=True`?

There is also `Expectation(X).rewrite(Integral)`.

What about adding a docstring to `symbolic_probability.py`, so that all these cases are covered in the documentation? (I mean, it's easier to list all these transformation cases in the documentation).

**Comment by Smit-create** [comment] 2020-05-11 06:27
> ``, so that all these cases are covered in the documentation? 

We will need to change the dcoumentation, once we fix this

**Comment by czgdp1807** [comment] 2020-05-25 08:12
This can be closed.

**Closed** 2020-05-25 08:15 UTC
Labels: GSoC, stats
