### ISSUE TITLE
Cannot perform inverse when using elements from a MatrixSymbol

### ISSUE THREAD

**Issue by Djgreene730** [sympy/sympy#19856] opened 2020-07-29 20:36 UTC
_Background: SymPy 1.6.1 (pulled from pip), Python 3.5.2, Ubuntu 16.04.6 LTS_ 

I'm trying to evaluate the matrix inverse of an expression containing elements from a MatrixSymbol; however, I'm getting a TypeError when I do this. The determinant worked fine, so I'm not sure why it's not subscriptable.

```python
a = sym.MatrixSymbol('a',2,2);
A = sym.Matrix([[1/a[2]+1/a[0], 0], [0, 1/a[3]+1/a[1]]]);
A.inv()
>>> TypeError: 'One' object is not subscriptable
A.det()
>>> 1/(a[1, 0]*a[1, 1]) + 1/(a[0, 1]*a[1, 0]) + 1/(a[0, 0]*a[1, 1]) + 1/(a[0, 0]*a[0, 1])
```

Using individual Symbols, the following set of code worked fine,
```python
a0, a1, a2, a3 = sym.var('a{0:4}');
A = sym.Matrix([[1/a1+1/a0, 0], [0, 1/a3+1/a2]])
A.inv()
>> Matrix([[1/(1/a{1} + 1/a{0}), 0], [0, 1/(1/a{3} + 1/a{2})]])
```

I tried using the [m,n] indexing option as well, I get the same result,
```python
a = sym.MatrixSymbol('a',2,2);
A = sym.Matrix([[1/a[1,0]+1/a[0,0], 0], [0, 1/a[1,1]+1/a[0,1]]]);
A.inv()
>>> TypeError: 'One' object is not subscriptable
```

So, I then tried making a Matrix of Symbols...this worked fine!
```python
a = sym.Matrix(2,2,lambda i,j: sym.Symbol('a_{%d,%d}' % (i, j)))
A = sym.Matrix([[1/a[2]+1/a[0], 0], [0, 1/a[3]+1/a[1]]]);
A.inv()
>>> Matrix([[1/(1/a_{1,0} + 1/a_{0,0}), 0], [0, 1/(1/a_{1,1} + 1/a_{0,1})]])
```

Here's the full error...

```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-67-ba976646ae79> in <module>
     25 a = sym.MatrixSymbol('a',2,2);
     26 A = sym.Matrix([[1/a[2]+1/a[0], 0], [0, 1/a[3]+1/a[1]]]);
---> 27 A.inv()

/usr/local/lib/python3.5/dist-packages/sympy/matrices/matrices.py in inv(self, method, iszerofunc, try_block_diag)
   2250     def inv(self, method=None, iszerofunc=_iszero, try_block_diag=False):
   2251         return _inv(self, method=method, iszerofunc=iszerofunc,
-> 2252                 try_block_diag=try_block_diag)
   2253 
   2254     def connected_components(self):

/usr/local/lib/python3.5/dist-packages/sympy/matrices/inverse.py in _inv(M, method, iszerofunc, try_block_diag)
    457 
    458     if method == "GE":
--> 459         rv = M.inverse_GE(iszerofunc=iszerofunc)
    460     elif method == "LU":
    461         rv = M.inverse_LU(iszerofunc=iszerofunc)

/usr/local/lib/python3.5/dist-packages/sympy/matrices/matrices.py in inverse_GE(self, iszerofunc)
   2234 
   2235     def inverse_GE(self, iszerofunc=_iszero):
-> 2236         return _inv_GE(self, iszerofunc=iszerofunc)
   2237 
   2238     def inverse_LU(self, iszerofunc=_iszero):

/usr/local/lib/python3.5/dist-packages/sympy/matrices/inverse.py in _inv_GE(M, iszerofunc)
    240 
    241     big = Matrix.hstack(M.as_mutable(), Matrix.eye(M.rows))
--> 242     red = big.rref(iszerofunc=iszerofunc, simplify=True)[0]
    243 
    244     if any(iszerofunc(red[j, j]) for j in range(red.rows)):

/usr/local/lib/python3.5/dist-packages/sympy/matrices/matrices.py in rref(self, iszerofunc, simplify, pivots, normalize_last)
    162             normalize_last=True):
    163         return _rref(self, iszerofunc=iszerofunc, simplify=simplify,
--> 164             pivots=pivots, normalize_last=normalize_last)
    165 
    166     echelon_form.__doc__ = _echelon_form.__doc__

/usr/local/lib/python3.5/dist-packages/sympy/matrices/reductions.py in _rref(M, iszerofunc, simplify, pivots, normalize_last)
    304 
    305     mat, pivot_cols, _ = _row_reduce(M, iszerofunc, simpfunc,
--> 306             normalize_last, normalize=True, zero_above=True)
    307 
    308     if pivots:

/usr/local/lib/python3.5/dist-packages/sympy/matrices/reductions.py in _row_reduce(M, iszerofunc, simpfunc, normalize_last, normalize, zero_above)
    127     mat, pivot_cols, swaps = _row_reduce_list(list(M), M.rows, M.cols, M.one,
    128             iszerofunc, simpfunc, normalize_last=normalize_last,
--> 129             normalize=normalize, zero_above=zero_above)
    130 
    131     return M._new(M.rows, M.cols, mat), pivot_cols, swaps

/usr/local/lib/python3.5/dist-packages/sympy/matrices/reductions.py in _row_reduce_list(mat, rows, cols, one, iszerofunc, simpfunc, normalize_last, normalize, zero_above)
     67         pivot_offset, pivot_val, \
     68         assumed_nonzero, newly_determined = _find_reasonable_pivot(
---> 69                 get_col(piv_col)[piv_row:], iszerofunc, simpfunc)
     70 
     71         # _find_reasonable_pivot may have simplified some things

/usr/local/lib/python3.5/dist-packages/sympy/matrices/determinant.py in _find_reasonable_pivot(col, iszerofunc, simpfunc)
     99         if possible_zeros[i] is not None:
    100             continue
--> 101         if x.equals(S.Zero):
    102             # ``.iszero`` may return False with
    103             # an implicit assumption (e.g., ``x.equals(0)``

/usr/local/lib/python3.5/dist-packages/sympy/core/expr.py in equals(self, other, failing_expression)
    761             return False
    762 
--> 763         constant = diff.is_constant(simplify=False, failing_number=True)
    764 
    765         if constant is False:

/usr/local/lib/python3.5/dist-packages/sympy/core/expr.py in is_constant(self, *wrt, **flags)
    687                 except ZeroDivisionError:
    688                     b = None
--> 689                 if b is not None and b is not S.NaN and b.equals(a) is False:
    690                     return False
    691                 # try random real

/usr/local/lib/python3.5/dist-packages/sympy/core/expr.py in equals(self, other, failing_expression)
    751         # because if the expression ever goes to 0 then the subsequent
    752         # simplification steps that are done will be very fast.
--> 753         diff = factor_terms(simplify(self - other), radical=True)
    754 
    755         if not diff:

/usr/local/lib/python3.5/dist-packages/sympy/simplify/simplify.py in simplify(expr, ratio, measure, rational, inverse, doit, **kwargs)
    717         expr = nfloat(expr, exponent=False)
    718 
--> 719     return done(expr)
    720 
    721 

/usr/local/lib/python3.5/dist-packages/sympy/simplify/simplify.py in done(e)
    541 
    542     def done(e):
--> 543         rv = e.doit() if doit else e
    544         return shorter(rv, collect_abs(rv))
    545 

/usr/local/lib/python3.5/dist-packages/sympy/core/operations.py in doit(self, **hints)
    376     def doit(self, **hints):
    377         if hints.get('deep', True):
--> 378             terms = [term.doit(**hints) for term in self.args]
    379         else:
    380             terms = self.args

/usr/local/lib/python3.5/dist-packages/sympy/core/operations.py in <listcomp>(.0)
    376     def doit(self, **hints):
    377         if hints.get('deep', True):
--> 378             terms = [term.doit(**hints) for term in self.args]
    379         else:
    380             terms = self.args

/usr/local/lib/python3.5/dist-packages/sympy/core/basic.py in doit(self, **hints)
   1665         if hints.get('deep', True):
   1666             terms = [term.doit(**hints) if isinstance(term, Basic) else term
-> 1667                                          for term in self.args]
   1668             return self.func(*terms)
   1669         else:

/usr/local/lib/python3.5/dist-packages/sympy/core/basic.py in <listcomp>(.0)
   1665         if hints.get('deep', True):
   1666             terms = [term.doit(**hints) if isinstance(term, Basic) else term
-> 1667                                          for term in self.args]
   1668             return self.func(*terms)
   1669         else:

/usr/local/lib/python3.5/dist-packages/sympy/matrices/expressions/matexpr.py in doit(self, **kwargs)
    722         else:
    723             args = self.args
--> 724         return args[0][args[1], args[2]]
    725 
    726     @property

TypeError: 'One' object is not subscriptable
```

**Comment by sylee957** [comment] 2020-07-30 20:08
This was a problem before that ‘equals’ does not work with matrix element symbols

**Comment by oscarbenjamin** [comment] 2020-07-30 23:06
See #19162 and #19217

**Comment by oscarbenjamin** [comment] 2020-07-30 23:07
Closing as a duplicate of #19162

**Closed by oscarbenjamin** 2020-07-30 23:07 UTC
