### ISSUE TITLE
Piecewise simplification (to avoid doit growth)

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#17165] opened 2019-07-08 15:48 UTC
```python
>>> Piecewise((1,x<1),(2,True))
Piecewise((1, x < 1), (2, True))
>>> p1=_
>>> p2 = Piecewise((1,x<1),(p1,True))
Piecewise((1, x < 1), (Piecewise((1, x < 1), (2, True)), True))
>>> piecewise_fold(_)  <-- should this have been necessary?
Piecewise((1, x < 1), (2, True))
```
Perhaps that situation should be recognized during instantiation. Or else `doit` might need to call `piecewise_fold` first to avoid repeating what is known (as was reported [on the mailing list](https://groups.google.com/forum/#!topic/sympy/-39qnrULloM)):
```python
>>> Sum (x**n, (n, -1, oo)).doit () 
Piecewise((1/(x*(1 - x)), Abs(x) < 1), (Sum(x**n, (n, -1, oo)), True))
>>> _.doit()
Piecewise((1/(x*(1 - x)), Abs(x) < 1), (Piecewise((1/(x*(1 - x)), Abs(x) < 1), (Sum(x**n, (n, -1, oo)), True)), True))
```

**Comment by czgdp1807** [comment] 2019-07-08 15:51
Please consider adding the google groups link in the description, https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/sympy/-39qnrULloM/-P_icqyHAgAJ

**Comment by Pristine-Cat** [comment] 2019-07-12 22:19
I have an easy fix for this in Piecewise.doit() which would leave expressions which evaluate to the parent expression in their original form to avoid infinite recursion but would like to add a hint keyword to force this if it is desired. Where would I document this hint and is there a global list of hints which functions take as all these hints are passed on to children and I don't want to cause any unexpected behavior?

**Comment by oscarbenjamin** [comment] 2019-07-13 03:05
@Pristine-Cat probably the best thing is to show your suggested change by opening a PR. We can discuss more then.

It's not clear to me what the best approach is for this yet...

**Comment by Pristine-Cat** [comment] 2019-07-13 17:00
Actually let me potentially reverse myself, it seems the condition in MatrixArithmetic.__pow__() may actually be incorrect as:

Matrix ([[0,1,0],[0,0,1],[0,0,1]])**Symbol('n', nonnegative=True)

raises a

ValueError: Matrix det == 0; not invertible

when it should return a MatPow object instead of trying to evaluate a zero determinant matrix?

**Comment by oscargus** [comment] 2019-07-24 17:29
Here is an example, where the current approach doesn't work:

`(1 - p)**n*Sum(k*p**k*(1 - p)**(-k)*binomial(n, k), (k, 0, n))`

(I'm working a bit on the Summation evaluation and one of the test cases happens to include this. If it was kept in the form from the previous evaluation approach, exactly one simplification lead to a nice looking result...)

**Comment by Pristine-Cat** [comment] 2019-07-24 17:38
Could just change it to a `piecewise_fold()` in the `doit()`.

**Comment by oscargus** [comment] 2019-07-24 17:53
Oh, it is a slightly different case I realize. I'm doing simplify, not doit (but simplify apparently does doit). I have used a similar approach to your in _eval_simplify, but it only seems to work after the first simplification, so I get growth in one stage, but not after that. 

It seems like the problem happens when one multiplies in front of the Sum...

(x*Sum (x**n, (n, -1, oo)).doit()).simplify()

Or worse: piecewise_fold((x*Sum (x**n, (n, -1, oo)).doit()).simplify().simplify().simplify().simplify())

I'll see if I can figure out something, but it seems like your approach is a quite reasonable one, the question is just where to place it?

**Comment by oscargus** [comment] 2019-07-24 17:58
Some of these effects may have to do with my other changes though...

**Comment by Pristine-Cat** [comment] 2019-07-24 18:03
There should be tests for this effect.

**Comment by oscargus** [comment] 2019-07-24 18:19
Definitely.

It seems like if one does `(x*Sum (x**n, (n, -1, oo))).simplify()` there is a doit() involved. However, `Sum(x**n, (n, -1, oo)).simplify()` doesn't have a doit()... (Or there is one, but it is deemed that the doit() result is worse in that case...)

**Comment by Pristine-Cat** [comment] 2019-07-24 18:23
The former calls simplify on a `Mul` object which probably calls the global `simplify()` function which has a default `doit=True`. The second expression calls the `Sum.simplify()` which I am willing to bet does not have a default `doit=True`.

**Comment by oscargus** [comment] 2019-07-24 18:31
I will not bet against. :-)

Another weird thing is that the first simplify does not simplify the Piecewise relations. The original expression after doit is (using my branch, but it is only the Sum.doit that I have changed plus that I have copied your code for checking if the simplify result is the same as the current Piecewise):

![image](https://user-images.githubusercontent.com/8114497/61818510-45e91d00-ae51-11e9-87f6-87af20f882a6.png)

After the first simplify:
![image](https://user-images.githubusercontent.com/8114497/61818575-69ac6300-ae51-11e9-972c-d8515485af60.png)

After the second:
![image](https://user-images.githubusercontent.com/8114497/61818604-7761e880-ae51-11e9-9631-90d713bed3e8.png)

It is only the relation for the first piecewise expression that changes. From here on, the expression explodes with each simplify...

I fully agree with your conclusion that Mul-simplify does something different compared to Piecewise- and Sum-simplify...

**Comment by Pristine-Cat** [comment] 2019-07-24 18:39
Mul does not define `simplify()` so it falls back to `Expr.simplify()` which does call the global `simplify(doit=True)` for each of its `args`.

**Comment by oscargus** [comment] 2019-07-24 20:00
This seems like a tricky thing so solve properly. I have added a fix such that if one of the expressions in a Piecewise is not Piecewise and doit or simplify makes it Piecewise, it uses the previous one. Not an ideal solution since there can be legitimate expressions where this holds...

A problem is that the global simplify always exits with a doit(). Maybe that is the way to go? If any expression in a flattened Piecewise contains the same expression in the resulting Piecewise after doit, then the old expression will be kept? Or maybe one should compare the flattened Piecewises? Another problem here is that the expressions and relations are simplified so it is not the identical expressions that show up for comparison.

**Comment by oscargus** [comment] 2019-07-24 20:04
Good thing is that it isn't really caused by my "improved" summations. It is just that some earlier tests relied on the exact format of the expression...

Here is the test I am talking about anyway. An additional simplify here makes it start to grow.

https://github.com/sympy/sympy/blob/8ca4a683d58ac1f61cfd2e4dacf7f58b9c0fefab/sympy/concrete/tests/test_sums_products.py#L895-L904

**Comment by oscargus** [comment] 2019-07-25 09:06
I think I have fixed it. In the done function in simplify, I included a shorter, so that the doit-result is only used if it is shorter. Not sure how this goes against the original idea of #17164 (and closed issues/PRs), but I guess it makes sense. Only call doit in simplify if it reduces the size of the expression as simplify should, ehm, simplify.

PR on its way.

**Closed** 2019-08-15 00:45 UTC
Labels: functions.elementary.piecewise
