### ISSUE TITLE
init_session(auto_symbols=True) and init_session(auto_int_to_Integer=True) do not work

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#2839] opened 2014-01-26 19:14 UTC
```
In [5]: init_session(auto_int_to_Integer=True, auto_symbols=True)
IPython console for SymPy 0.7.4.1-git (Python 3.3.3-64-bit) (ground types: python)

These commands were executed:
>>> from __future__ import division
>>> from sympy import *
>>> x, y, z, t = symbols('x y z t')
>>> k, m, n = symbols('k m n', integer=True)
>>> f, g, h = symbols('f g h', cls=Function)

Documentation can be found at http://www.sympy.org

In [6]: 1/2
Out[6]: 0.5

In [7]: notdefined
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-7-6ee7e72db811> in <module>()
----> 1 notdefined

NameError: name 'notdefined' is not defined
```

`isympy -I` works.

We need to convert these to use the new IPython ast machinery.

**Comment by jcrist** [comment] 2015-04-21 20:41
Copying this over from #2921, and then closing that issue (duplicate):

Quote:
"TODO from sympy/interactive/session.py (commented out code, deleted in #2219):

```python
# XXX: Something like this might be used, but it only works on single line
# inputs.  See
# http://mail.scipy.org/pipermail/ipython-user/2012-August/010846.html and
# https://github.com/ipython/ipython/issues/1491.  So instead we are forced to
# just monkey-patch run_cell until IPython builds a better API.
 class IntTransformer(object):
     """
     IPython command line transformer that recognizes and replaces int
     literals.

     Based on
     https://bitbucket.org/birkenfeld/ipython-physics/src/71b2d850da00/physics.py.

     """
     priority = 99
     enabled = True
     def transform(self, line, continue_prompt):
         import re
         from tokenize import TokenError
         leading_space = re.compile(' *')
         spaces = re.match(leading_space, line).span()[1]
         try:
             return ' '*spaces + int_to_Integer(line)
         except TokenError:
             return line

 int_transformer = IntTransformer()

 def enable_automatic_int_sympification(app):
     """
     Allow IPython to automatically convert integer literals to Integer.

     This lets things like 1/2 be executed as (essentially) Rational(1, 2).
     """
     app.shell.prefilter_manager.register_transformer(int_transformer)
```
"

**Comment by takluyver** [comment] 2015-04-21 21:01
As described above, we did build a better API - AST transformations. There's an example of how it works in the tests:

https://github.com/ipython/ipython/blob/411cd57051173af49a54f55bfce9c22198bc43e8/IPython/core/tests/test_interactiveshell.py#L616

**Comment by mhlr** [comment] 2017-02-08 05:29
I have found a workaround for this. The problem is that when in an already running IPython session, `init_session` does not call `init_ipython_session` which is responsible for enabling the options as well as starting the session.  That call can be made explicitly first:

```
sympy.interactive import init_session
from sympy.interactive.session import init_ipython_session
init_ipython_session(auto_symbols=True, auto_int_to_Integer=True)
init_session(ipython=None, auto_symbols=True, auto_int_to_Integer=True)
```

See http://stackoverflow.com/a/42105135/843348

**Comment by asmeurer** [comment] 2017-02-08 06:52
@mhlr so I guess the `if ip is None` check before it calls `init_ipython_session` should be removed. Are there downsides to calling it twice? I tested your workaround and it seems to work. Can you send a patch?

**Comment by mhlr** [comment] 2017-02-09 06:00
@ausmerer I do not know if there are downsides. I have not observed any, but this is the first time I have really looked inside sympy source and I have only started using this method.
There is still the problem that the initialization need to be done separately, eg doing `eval-buffer` from emacs does not work.

I am happy to make a patch if you think this is good.

**Comment by asmeurer** [comment] 2017-02-09 06:32
Yes, please send a patch.

**Comment by mhlr** [comment] 2017-02-09 07:14
@asmeurer Ok. So I will just remove the if statement.

Also do you think wrapping the initialization in an IPython magic would fix the problem with needing separate evaluations?

**Comment by asmeurer** [comment] 2017-02-09 22:37
I don't know. Having a magic command sounds useful either way, though.

**Closed** 2017-02-17 15:56 UTC
Labels: IPython
