### ISSUE TITLE
Canonicalisation: eval(repr(obj)) != obj.func(*obj.args)

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#17236] opened 2019-07-20 20:42 UTC
This comes from #17215.

The following expression satisfies `p6 == p6.func(*p6.args)` but not `p6 == eval(repr(p6))` and I can't see why not:
```python
p6 = Add(Mul(Integer(-1), Add(Integer(1), Mul(Integer(-1), KroneckerDelta(Integer(1), Symbol('x')))), Add(Integer(1), Mul(Integer(-1), KroneckerDelta(Integer(4), Symbol('y'))))), Integer(1))                                                    
```
With that object we have:
```julia
In [70]: p6                                                                                                                       
Out[70]: 
- ⎛1 - δ   ⎞⋅⎛1 - δ   ⎞ + 1
  ⎝     1,x⎠ ⎝     4,y⎠    

In [71]: repr(p6)                                                                                                                 
Out[71]: '-(1 - KroneckerDelta(1, x))*(1 - KroneckerDelta(4, y)) + 1'

In [72]: p7 = eval(repr(p6))                                                                                                      

In [73]: p7                                                                                                                       
Out[73]: 
⎛1 - δ   ⎞⋅⎛δ    - 1⎞ + 1
⎝     4,y⎠ ⎝ 1,x    ⎠    
```
So p7 differs from p6 by cancellation of a minus sign.

We have that
```julia
In [74]: p6 == p7                                                                                                                 
Out[74]: False

In [75]: p6.expand() == p7.expand()                                                                                               
Out[75]: True

In [76]: p6 == p6.func(*p6.args)                                                                                                  
Out[76]: True
```
What I can't quite understand is that the repr evaluates into a different form (p7) that I can't get from calling func with args. There must be some canonicalisation routines that regard each form as a local minimum somehow.

**Comment by smichr** [comment] 2019-07-20 21:00
Whereas Mul can keep the Rational in front of multiple factors, sympification cannot unless evaluate is False:
```python
>>> Mul(2,1+y,1+z)
2*(y + 1)*(z + 1)
>>> eq = _
>>> S(repr(eq))
(2*y + 2)*(z + 1)
>>> S(repr(eq), evaluate=False)
2*(y + 1)*(z + 1)
```

**Comment by oscarbenjamin** [comment] 2019-07-20 21:13
It seems to be to different depending on whether I do 1-a or -a+1:
```julia
In [140]: 1 - (1 - KroneckerDelta(1, x))*(1 - KroneckerDelta(4, y))                                                               
Out[140]: 
- ⎛1 - δ   ⎞⋅⎛1 - δ   ⎞ + 1
  ⎝     1,x⎠ ⎝     4,y⎠    

In [141]: - (1 - KroneckerDelta(1, x))*(1 - KroneckerDelta(4, y)) + 1                                                             
Out[141]: 
⎛1 - δ   ⎞⋅⎛δ    - 1⎞ + 1
⎝     4,y⎠ ⎝ 1,x    ⎠
```
However if I actually extract the expression and call it a then it doesn't happen:
```julia
In [142]: a = (1 - KroneckerDelta(1, x))*(1 - KroneckerDelta(4, y))                                                               

In [143]: 1 - a                                                                                                                   
Out[143]: 
- ⎛1 - δ   ⎞⋅⎛1 - δ   ⎞ + 1
  ⎝     1,x⎠ ⎝     4,y⎠    

In [144]: -a + 1                                                                                                                  
Out[144]: 
- ⎛1 - δ   ⎞⋅⎛1 - δ   ⎞ + 1
  ⎝     1,x⎠ ⎝     4,y⎠ 
```

**Comment by oscarbenjamin** [comment] 2019-07-20 21:20
Okay got it:
```julia
In [145]: b = (1 - KroneckerDelta(1, x))                                                                                          

In [146]: c = (1 - KroneckerDelta(4, y))                                                                                          

In [147]: 1 - b*c                                                                                                                 
Out[147]: 
- ⎛1 - δ   ⎞⋅⎛1 - δ   ⎞ + 1
  ⎝     1,x⎠ ⎝     4,y⎠    

In [148]: -b*c + 1                                                                                                                
Out[148]: 
⎛1 - δ   ⎞⋅⎛δ    - 1⎞ + 1
⎝     4,y⎠ ⎝ 1,x    ⎠
```
I think that Python's evaluation order is different for these two since - is unary in one and binary in the other. Unary minus has a higher precedence than multiplication whereas binary minus has a lower precedence so
```
1 - b*c     ->    1 - (b*c)
-b*c + 1    ->    ((-b)*c) + 1
```
Is it reasonable to expect that SymPy would canonicalise these to the same somehow?

**Comment by smichr** [comment] 2019-07-20 21:21
`-(1+x)*y` will distribute the -1 as a Mul on Add since the args are handled 1 at a time; perhaps in the subtraction the -1 is applied to the product `(1 + x)*y` and does not distribute the Rational (-1 in this case):
```python

**Comment by oscarbenjamin** [comment] 2019-07-20 21:37
> a stated objective is to get rid of the 2-arg distribution.

What does that mean?

This is the most I can reduce it to:
```julia
In [155]: -(1+x)*y                                                                                                                
Out[155]: y⋅(-x - 1)

In [156]: -((1+x)*y)                                                                                                              
Out[156]: -y⋅(x + 1)
```
Is the first example what you mean by 2-arg distribution?

**Comment by smichr** [comment] 2019-07-20 22:50
> What does that mean?

cf #4596

Both examples demonstrate what I am talking about. In the first, the -1 encounters, next, the `1 + x` and the Mul.flatten (I think it's there) distributes the -1; this is a result of Python parsing of the expression. In the second case the -1 encounters a Mul, not an Add, so it is not distributed. The same result could be obtained with `(1+x)*y*-1` since Python will parse the first 2 args (creating a SymPy Mul) and then multiply this by -1 and there is no SymPy code that automatically distributes the Rational in such a case.

**Comment by oscarbenjamin** [comment] 2019-07-21 02:08
Thanks. I now understand. I imagine that it wouldn't be easy to fix

**Comment by smichr** [comment] 2019-07-21 12:28
Duplicate of #4596

**Closed by smichr** 2019-07-21 12:28 UTC
