### ISSUE TITLE
problem with _linear_2eq_order1_type4

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#18562] opened 2020-02-03 21:13 UTC
The following system of ODEs with variable coefficients gives the wrong answer. In particular, it is the case for when `elif r['d'] == -r['a']:` that the error occurs:
```
eqs = [
Eq(f(x).diff(x), f(x) + y*g(x)), 
Eq(g(x).diff(x), f(x)*y - g(x))]
ans=dsolve(eqs)
[i.subs([i.args for i in ans]).doit().expand()==0 for i in eqs] # -> [False, False]
```
In #18553 @oscarbenjamin noted that:
____
 "it would be better just to delete this particular solver. The code is broken and it is a special case of something more general. We can have a system of ODEs:
```
X(t).diff(t) = A(t)*X(t)
```
where X is a column matrix and A is a square matrix. If the matrix A(t) is symmetric and its integral is B(t) (also symmetric) then the solution is X(t) = exp(B(t)). This makes a solver that can work for any number of equations rather than just two. The condition can be further generalised by saying that we require only that A and B commute (they don't need to be symmetric necessarily).

**Comment by oscarbenjamin** [comment] 2020-02-03 23:47
The description above applies to many of the dsolve for systems solvers unfortunately. I've specified a GSOC project to fix this but maybe the spec should be improved:
https://github.com/sympy/sympy/wiki/GSoC-2020-Ideas#systems-of-ordinary-differential-equations

**Comment by Saanidhyavats** [comment] 2020-03-02 15:05
I want to contribute on this issue. How shall I start with it @oscarbenjamin ?

**Comment by mijo2** [comment] 2020-05-12 07:11
@smichr @oscarbenjamin PR #19185 solves this issue. I would add a regression test case for the same.

**Comment by mijo2** [comment] 2020-06-21 09:52
Can this issue be closed now, since the solver is removed from the library.

**Comment by oscarbenjamin** [comment] 2020-06-21 10:57
Yes, if the example is fixed and a regression test has been added.

**Comment by mijo2** [comment] 2020-06-21 11:25
https://github.com/sympy/sympy/blob/fb8cdf07ef1144a90b6f1a12a1fe315245bfbed7/sympy/solvers/ode/tests/test_systems.py#L429-L435

The regression test case has already been added and merged.

**Comment by naveensaigit** [comment] 2020-12-25 12:28
This issue is fixed and can be closed. I get the following on current master -
``` python
>>> from sympy import *
>>> x,y=symbols('x y')
>>> f=Function('f')
>>> g=Function('g')
>>> eqs = [
... Eq(f(x).diff(x), f(x) + y*g(x)),
... Eq(g(x).diff(x), f(x)*y - g(x))]
>>> ans=dsolve(eqs)
>>> ans
[Eq(f(x), C1*y*exp(x*sqrt(y**2 + 1))/(sqrt(y**2 + 1) - 1) - C2*y*exp(-x*sqrt(y**2 + 1))/(sqrt(y**2 + 1) + 1)), 
Eq(g(x), C1*exp(x*sqrt(y**2 + 1)) + C2*exp(-x*sqrt(y**2 + 1)))]
```

**Comment by oscarbenjamin** [comment] 2020-12-26 01:47
It looks like this is fixed but the OP test of `== 0` is inadequate and `simplify` should be used instead:
```python
eqs = [
Eq(f(x).diff(x), f(x) + y*g(x)), 
Eq(g(x).diff(x), f(x)*y - g(x))]
ans=dsolve(eqs)
```
Then:
```python
In [186]: [i.subs([i.args for i in ans]).doit().expand().simplify() for i in eqs]
Out[186]: [True, True]

In [187]: [i.subs([i.args for i in ans]).doit().expand()==0 for i in eqs]
Out[187]: [False, False]
```

**Closed by oscarbenjamin** 2020-12-26 01:47 UTC
Labels: solvers.dsolve, solvers.dsolve.system
