### ISSUE TITLE
Incorrect indefinite integral involving inverse trig

### ISSUE THREAD

**Issue by timmythetiny** [sympy/sympy#12050] opened 2017-01-16 22:18 UTC
Not sure if I'm using the software incorrectly or if this is a bug, but I was trying to check my solution to ∫(1/(a^2 + x^2))dx, where a is a constant value.  Longhand, I found that the solution should be (arctan(x/a))/a, but Sympy was advising otherwise.  From my Jupyter session:

![real false](https://cloud.githubusercontent.com/assets/13814470/22000836/5b3eaede-dbf6-11e6-83a5-c82e44235aee.jpg)

I also tried telling the system that 'a' was a member of the reals:

![real true](https://cloud.githubusercontent.com/assets/13814470/22000855/7206fcd4-dbf6-11e6-81ec-bacff67ec6d8.jpg)

Neither of these solutions is correct.  Can anyone advise?  Many thanks.

**Comment by jksuom** [comment] 2017-01-17 06:36
The first solution (with `log`) is not incorrect. It is a complex form representation of atan. However, SymPy does currently not rewrite it as atan, and that is a known issue. The second result looks like a bug.

**Comment by mohit-raj** [comment] 2017-01-17 14:33
@jksuom How can i reduce the complex form representation of atan, to obtain the arctan(x/a)*1/a.?

**Comment by jksuom** [comment] 2017-01-17 14:48
SymPy fails when the sign of `a` is indeterminate. (This should be fixed.) As a workaround, the sign can be given.
```
>>> x = symbols('x')
>>> a = symbols('a', real=True, positive=True)
>>> integrate(1/(a**2 + x**2), x)
atan(x/a)/a
```

**Comment by mzaffalon** [comment] 2017-01-19 04:57
Is there also a workaround for `integrate(1 / (1 + x**2*y**2), x, y)`?

**Comment by asmeurer** [comment] 2017-10-23 21:03
The problem seems to be the line that gets the roots https://github.com/sympy/sympy/blob/6d5fb9ebcb4c54b1c2f321a4c9082a215f4b25dc/sympy/integrals/rationaltools.py#L377. It doesn't get the imaginary roots with `a`, but then the `count_roots` guard below https://github.com/sympy/sympy/blob/6d5fb9ebcb4c54b1c2f321a4c9082a215f4b25dc/sympy/integrals/rationaltools.py#L379 fails (it returns 2 for `4*_u**4 + a**(-2)*_u**2`). I think instead of count_roots it should just check against the degree of the polynomial.

**Comment by jksuom** [comment] 2017-10-24 16:20
I don't think that is the problem. `count_roots()`, with no parameters, defaults to `count_real_roots`. It returns the number of distinct real roots that is also the value of `len(R_q)`.

The algorithm works by replacing the logarithms corresponding to each pair of complex conjugate roots by an `atan` and a real logarithm. For this purpose it selects the roots with [positive imaginary part](https://github.com/sympy/sympy/blob/master/sympy/integrals/rationaltools.py#L362) and derives the output from their real and imaginary parts. The issue is that if it cannot decide which one of the imaginary parts is positive, the pair of roots will be ignored. That can probably be fixed by collecting the roots in pairs of opposite sign, even if the sign is unknown, and then continuing formally with one of the roots in the same way as if it were known to be positive.

**Closed** 2018-02-05 17:43 UTC
Labels: integrals
