### ISSUE TITLE
copy.deepcopy(3.7*meter) raises an Exception

### ISSUE THREAD

**Issue by Volker-Weissmann** [sympy/sympy#19690] opened 2020-07-03 00:31 UTC
```
import sympy.physics
from sympy.physics.units import meter
import copy
copy.deepcopy(3.7*meter)
```
The program above outputs:
> Traceback (most recent call last):
>   File "./bugsympy.py", line 6, in <module>
>     copy.deepcopy(3.7*meter)
>   File "/usr/lib/python3.8/copy.py", line 172, in deepcopy
>     y = _reconstruct(x, memo, *rv)
>   File "/usr/lib/python3.8/copy.py", line 264, in _reconstruct
>     y = func(*args)
>   File "/usr/lib/python3.8/copy.py", line 263, in <genexpr>
>     args = (deepcopy(arg, memo) for arg in args)
>   File "/usr/lib/python3.8/copy.py", line 172, in deepcopy
>     y = _reconstruct(x, memo, *rv)
>   File "/usr/lib/python3.8/copy.py", line 264, in _reconstruct
>     y = func(*args)
>   File "/home/volker/.local/lib/python3.8/site-packages/sympy/core/numbers.py", line 1165, in __new__
>     num[1] = MPZ(num[1], 16)
>   File "sage/rings/integer.pyx", line 720, in sage.rings.integer.Integer.__init__ (build/cythonized/sage/rings/integer
> .c:6575)                                                                                                             
>   File "sage/rings/integer.pyx", line 7143, in sage.rings.integer.mpz_set_str_python (build/cythonized/sage/rings/inte
> ger.c:43554)                                                                                                         
> TypeError: unable to convert '0xecccccccccccd' to an integer

Probably because of the same bug, the following program:
```
import sympy.physics
from sympy.physics.units import meter
import copy
from multiprocessing import Pool
def func(x):
	print(x)
with Pool(4) as p:
	p.apply(func, 3.7*meter)
```
prints out:
> Traceback (most recent call last):
>   File "./bugsympy.py", line 6, in <module>
>     copy.deepcopy(3.7*meter)
>   File "/usr/lib/python3.8/copy.py", line 172, in deepcopy
>     y = _reconstruct(x, memo, *rv)
>   File "/usr/lib/python3.8/copy.py", line 264, in _reconstruct
>     y = func(*args)
>   File "/usr/lib/python3.8/copy.py", line 263, in <genexpr>
>     args = (deepcopy(arg, memo) for arg in args)
>   File "/usr/lib/python3.8/copy.py", line 172, in deepcopy
>     y = _reconstruct(x, memo, *rv)
>   File "/usr/lib/python3.8/copy.py", line 264, in _reconstruct
>     y = func(*args)
>   File "/home/volker/.local/lib/python3.8/site-packages/sympy/core/numbers.py", line 1165, in __new__
>     num[1] = MPZ(num[1], 16)
>   File "sage/rings/integer.pyx", line 720, in sage.rings.integer.Integer.__init__ (build/cythonized/sage/rings/integer
> .c:6575)                                                                                                             
>   File "sage/rings/integer.pyx", line 7143, in sage.rings.integer.mpz_set_str_python (build/cythonized/sage/rings/inte
> ger.c:43554)                                                                                                         
> TypeError: unable to convert '0xecccccccccccd' to an integer

**Comment by mkoeppe** [comment] 2021-08-31 22:10
This is caused by mpmath/Sage interfacing; I have added this issue to https://trac.sagemath.org/ticket/25445

**Comment by asmeurer** [comment] 2021-08-31 22:27
This works for me with normal SymPy (not in Sage). It looks like a Sage issue, so I'm closing this issue in favor of the upstream Sage issue.

**Closed by asmeurer** 2021-08-31 22:27 UTC
Labels: physics.units

**Comment by mkoeppe** [comment] 2021-08-31 23:04
Yes, I agree.

**Comment by mkoeppe** [comment] 2021-09-01 00:56
Actually, I tracked this down to an incorrect use of the `gmpy2` API in SymPy, fixed in #21996

**Comment by Volker-Weissmann** [comment] 2021-09-01 01:06
Wow, fixing something after one year of silence.
Thank you, this does not happen often

**Comment by oscarbenjamin** [comment] 2021-09-01 01:11
Yes, thanks @mkoeppe 

Although I see sage in the traceback the OP doesn't say anything about sage. It's possible that this was overlooked because it wasn't obvious how to reproduce it.
