### ISSUE TITLE
Lambdifying a piecewise function doesn't work with numba due to select/reduce functions in numpy

### ISSUE THREAD

**Issue by theDDA** [sympy/sympy#26032] opened 2024-01-01 17:14 UTC
Basically the title. I have a function that is defined on a particular domain and should be zero outside of it.  In actuality, this is a long and computationally expensive function, which is tedious to type out manually, and which would benefit from being accelerated with numba. I'd like to be able to do my theoretical work in sympy, but also be able to get reasonable speed when going to numeric computation. As a comparison, manually written and njited code is around 30x faster than what sympy generates without numba. 

I've tried two approaches, one using Piecewise, and another using Heaviside, but with no success. I'm not aware of other alternatives, but even if there are some, I suspect the issue would persist.

MWE:

```py
import sympy as smp
import numpy as np
from numba import njit

x, t = smp.symbols("x t")
f, g, h = smp.symbols("f g h", cls=smp.Function)
f, g, h = f(x), g(x), h(x)
h = smp.sin(x)

# Alternative definitions of sin(x), x\in[0,2pi], one with Piecewise and another with Heaviside theta function
f = smp.Piecewise((0, smp.re(x) > 2 * smp.pi), (0, smp.re(x) < 0), (h, True))
g = h * smp.Heaviside(smp.re(x)) * smp.Heaviside(2 * smp.pi - smp.re(x))

# Fails to work because numba doesn't play well with select/reduce
f_num_njit, g_num_njit = njit(smp.lambdify(x, f)), njit(smp.lambdify(x, g))
# f_num_njit(1 + 2j) # Fails
# g_num_njit(1 + 2j) # Fails

# Works, but loses all numpy functionality just to avoid select/reduce
f_num_njit = njit(smp.lambdify(x, f, modules=[{"re": np.real, "sin": np.sin}, "math"]))
g_num_njit = njit(smp.lambdify(x, g, modules=[{"re": np.real, "sin": np.sin}, "math"]))
# f_num_njit(1 + 2j) # Works
# g_num_njit(1 + 2j) # Works

# As an example, this fails as well
F, G = smp.symbols("F G", cls=smp.Function)
F, G = F(t), G(t)
F = smp.integrate(f, (x, 0, t))
G = smp.integrate(g, (x, 0, t))

F_num_njit = njit(smp.lambdify(t, F))
# F_num_njit(1 + 2j) # Fails
G_num_njit = njit(smp.lambdify(t, G))
# G_num_njit(1 + 2j) # Fails
```

All lines tagged with `# Fails` produce some variant of the following error:

```
TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Unknown attribute 'reduce' of type Function(<ufunc 'logical_or'>)

File "<lambdifygenerated-268>", line 2:
def _lambdifygenerated(x):
    return select([logical_or.reduce((less(real(x), 0),greater(real(x), 2*pi))),True], [0,sin(x)], default=nan)
    ^
```

I can force it to work using `modules=[{'re':np.real,'sin':np.sin}, 'math'])` which forces lambdify to use if-else logic, but at the expense of all numpy functionality just to avoid select and reduce. From what I can see in the docs, there aren't any flags I can pass to sympy itself to make it consider numba.

I've searched the previous issues (some dating back *years*), but I've found no satisfactory way to solve this issue in a more permanent way.  From what I've seen, all I can do is rewrite the offending numpy functions myself and replace them manually. This seems like a very poor and labor intensive workaround.

**Comment by oscarbenjamin** [comment] 2024-01-01 18:56
What would the manually written code look like if not using select or reduce?

**Comment by theDDA** [comment] 2024-01-01 23:38
Hi, I'm not entirely sure what you mean. In the context of this MWE, it would just be if-else logic, something like

```py
import numpy as np

def f_manual(x):
    if 0 < np.real(x) < 2 * np.pi:
        return np.sin(x)
    else:
        return 0
```

Inspecting the source of the function obtained with `smp.lambdify(x, f, modules=[{"re": np.real, "sin": np.sin}, "math"])` we get something functionally identical to manually written code.

```py
def _lambdifygenerated(x):
    return ((0) if (re(x) > 2*pi) or (re(x) < 0) else (sin(x)))
```

If we inspect the code generated by straightforward `smp.lambdify(x, f)` we get  

```py
def _lambdifygenerated(x):
    return select([logical_or.reduce((less(real(x), 0),greater(real(x), 2*pi))),True], [0,sin(x)], default=nan)
```

Code that uses select is not compatible with numba. Furthermore, profiling the code on my machine shows that the code generated with select is significantly slower than the effectively identical manual code I posted as an example (1 vs 15 µs). For comparison, @njit-ed manual code runs in 100 ns, so over 10 times faster than the workable lambdify output, showing how useful it is to have compatibility. Just to clarify, I understand that manually written code will often be superior to anything automatically generated, but here it seems like SymPy *can* output both faster and more compatible code if forced to.

I'm sure there are reasons to use select and reduce like this (having a huge amount of cases?)  but it seems like it both breaks compatibility with numba in the simplest of cases and is slower overall.

**Comment by oscarbenjamin** [comment] 2024-01-02 00:40
> I'm sure there are reasons to use select and reduce like this (having a huge amount of cases?) but it seems like it both breaks compatibility with numba in the simplest of cases and is slower overall.

I'm not sure when anyone last did proper timings/benchmarks but the reason is vectorisation. If you pass numpy arrays (rather than single numbers) into the lambdified function then `if x < 2` won't work. Unfortunately there is not a clear way to distinguish when vectorisation is or is not wanted.

**Comment by oscarbenjamin** [comment] 2024-01-02 01:51
There are alternatives to select/reduce that preserve vectorisation but may or may not work with numba e.g.:
```
def f(x):
    out = zeros_like(x)
    x_real = np.real(x)
    x_real_2pi = (0 < x_real) & (x_real < 2 * np.pi):
    out[x_real_2pi] = np.sin(x[x_real_2pi])
    return out
```
This approach has the advantage of not attempting to compute anything for the cases that are not of interest. If there are a large number of cases or if one case is much more common than the others then this might be more efficient.

**Comment by asmeurer** [comment] 2024-01-02 22:31
Unless I'm mistaken, this issue can be closed as a duplicate of https://github.com/sympy/sympy/issues/15014. The discussion on issue goes into this in much more detail and the possible solutions.

**Closed by asmeurer** 2024-01-02 22:31 UTC
Labels: utilities.lambdify
