### ISSUE TITLE
sympy/plotting/tests/test_plot.py matplotlib failures on Travis

### ISSUE THREAD

**Issue by gxyd** [sympy/sympy#13730] opened 2017-12-12 06:53 UTC
```python
sympy/plotting/tests/test_plot.py[3] E..                                  [FAIL]

______________ sympy/plotting/tests/test_plot.py:test_matplotlib _______________

  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/sympy-1.1.2.dev0-py2.7.egg/sympy/utilities/runtests.py", line 1267, in _timeout

    function()

  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/sympy-1.1.2.dev0-py2.7.egg/sympy/plotting/tests/test_plot.py", line 265, in test_matplotlib

    TmpFileManager.cleanup()

  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/sympy-1.1.2.dev0-py2.7.egg/sympy/plotting/tests/test_plot.py", line 32, in cleanup

    map(os.remove, cls.tmp_files)

OSError: [Errno 2] No such file or directory: '/tmp/test_basic_options_and_colorsMlZaYa.png'

```

Affected PR's https://github.com/sympy/sympy/pull/13728, https://github.com/sympy/sympy/pull/13726

**See this**: https://travis-ci.org/sympy/sympy/jobs/315158559 for seeing complete error

**Comment by gxyd** [comment] 2017-12-12 07:23
Current configuration uses v2.1.1 of matplotlib, released a few days ago.

**Comment by ylemkimon** [comment] 2017-12-12 09:12
Also #13725, #13539, #13708.

I think we should fix(lock) dependencies' versions and update them by a PR.

**Comment by gxyd** [comment] 2017-12-12 09:51
Also: https://github.com/sympy/sympy/pull/13708

**Comment by ArighnaIITG** [comment] 2017-12-12 10:05
Ok, Now I see the problem. What do I do now?

**Comment by jksuom** [comment] 2017-12-12 11:40
I suspect that there is a bug in matplotlib-2.1.1, and that we should temporarily use an older version. It seems that the file is not created because of an internal error.
```
  File "/home/jks/test/sympy/sympy/plotting/tests/test_plot.py", line 56, in plot_and_save
    p.save(tmp_file('%s_basic_options_and_colors' % name))
  File "/home/jks/test/sympy/sympy/plotting/plot.py", line 202, in save
    self._backend.save(path)
  File "/home/jks/test/sympy/sympy/plotting/plot.py", line 1036, in save
    self.process_series()
  File "/home/jks/test/sympy/sympy/plotting/plot.py", line 1015, in process_series
    if self.ax.legend():
  File "/home/jks/miniconda3/envs/python2/lib/python2.7/site-packages/matplotlib/axes/_axes.py", line 497, in legend
    **kwargs)
  File "/home/jks/miniconda3/envs/python2/lib/python2.7/site-packages/matplotlib/legend.py", line 1402, in _parse_legend_args
    handles, labels = _get_legend_handles_labels(axs, handlers)
  File "/home/jks/miniconda3/envs/python2/lib/python2.7/site-packages/matplotlib/legend.py", line 1360, in _get_legend_handles_labels
    and not _in_handles(handle, label)):
  File "/home/jks/miniconda3/envs/python2/lib/python2.7/site-packages/matplotlib/legend.py", line 1339, in _in_handles
    if f_h.get_color() != h.get_color():
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```
The line 1339 was introduced quite recently (https://github.com/matplotlib/matplotlib/pull/9324) and apparently colors were not tested. `get_color` now returns a list, not a single color. (It seems that there used to be another method for that: https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/collections.py#L1334.)
```
(Pdb) p f_h.get_color()
array([[ 0.12156863,  0.46666667,  0.70588235,  1.        ]])
(Pdb) p h.get_color()
array([[ 0.12156863,  0.46666667,  0.70588235,  1.        ]])
(Pdb) p f_h.get_color() != h.get_color()
array([[False, False, False, False]], dtype=bool)
```

**Comment by jklymak** [comment] 2017-12-17 16:28
Figure legend argument handling was made more parallel to axes handling https://github.com/matplotlib/matplotlib/pull/9324.  Sorry something broke for you.  Can you isolate the use case so we can debug and add to our tests on matplotlib Thanks.

**Comment by ylemkimon** [comment] 2017-12-18 17:41
@jklymak 

```python
In [3]: import matplotlib

In [4]: from matplotlib import pyplot

In [6]: fig = pyplot.figure()

In [7]: ax = fig.add_subplot(111)

In [11]: collection = matplotlib.collections.LineCollection(s)

In [15]: collection.set_array(color_array)

In [16]: ax.add_collection(collection)

In [17]: pyplot.show()
```

where `s` is:

```python
In [1]: from sympy import *

In [2]: from sympy.plotting.plot import LineOver1DRangeSeries

In [8]: x = Symbol('x')

In [9]: s = LineOver1DRangeSeries(x, (x, -10, 10)).get_segments()

In [10]: s
Out[10]:
[[[-10.0, -10.0], array([-9.65148387, -9.65148387])],
 [array([-9.65148387, -9.65148387]), array([-9.34473344, -9.34473344])],
 [array([-9.34473344, -9.34473344]), array([-9.08533804, -9.08533804])],
 [array([-9.08533804, -9.08533804]), array([-8.78815481, -8.78815481])],
 [array([-8.78815481, -8.78815481]), array([-8.41350281, -8.41350281])],
 [array([-8.41350281, -8.41350281]), array([-8.0986569, -8.0986569])],
 [array([-8.0986569, -8.0986569]), array([-7.77530757, -7.77530757])],
 [array([-7.77530757, -7.77530757]), array([-7.43117965, -7.43117965])],
 [array([-7.43117965, -7.43117965]), array([-7.16706867, -7.16706867])],
 [array([-7.16706867, -7.16706867]), array([-6.87147071, -6.87147071])],
 [array([-6.87147071, -6.87147071]), array([-6.53912957, -6.53912957])],
 [array([-6.53912957, -6.53912957]), array([-6.23612107, -6.23612107])],
 [array([-6.23612107, -6.23612107]), array([-5.85278512, -5.85278512])],
 [array([-5.85278512, -5.85278512]), array([-5.50764763, -5.50764763])],
 [array([-5.50764763, -5.50764763]), array([-5.16760455, -5.16760455])],
 [array([-5.16760455, -5.16760455]), array([-4.86774328, -4.86774328])],
 [array([-4.86774328, -4.86774328]), array([-4.54825552, -4.54825552])],
 [array([-4.54825552, -4.54825552]), array([-4.25463023, -4.25463023])],
 [array([-4.25463023, -4.25463023]), array([-3.94053317, -3.94053317])],
 [array([-3.94053317, -3.94053317]), array([-3.65798015, -3.65798015])],
 [array([-3.65798015, -3.65798015]), array([-3.35836977, -3.35836977])],
 [array([-3.35836977, -3.35836977]), array([-3.10372546, -3.10372546])],
 [array([-3.10372546, -3.10372546]), array([-2.80542543, -2.80542543])],
 [array([-2.80542543, -2.80542543]), array([-2.47836557, -2.47836557])],
 [array([-2.47836557, -2.47836557]), array([-2.22938119, -2.22938119])],
 [array([-2.22938119, -2.22938119]), array([-1.93664621, -1.93664621])],
 [array([-1.93664621, -1.93664621]), array([-1.60697986, -1.60697986])],
 [array([-1.60697986, -1.60697986]), array([-1.28785188, -1.28785188])],
 [array([-1.28785188, -1.28785188]), array([-1.00263591, -1.00263591])],
 [array([-1.00263591, -1.00263591]), array([-0.68647064, -0.68647064])],
 [array([-0.68647064, -0.68647064]), array([-0.34813222, -0.34813222])],
 [array([-0.34813222, -0.34813222]), array([-0.04767241, -0.04767241])],
 [array([-0.04767241, -0.04767241]), array([ 0.27910902,  0.27910902])],
 [array([ 0.27910902,  0.27910902]), array([ 0.63809008,  0.63809008])],
 [array([ 0.63809008,  0.63809008]), array([ 1.00507266,  1.00507266])],
 [array([ 1.00507266,  1.00507266]), array([ 1.44780174,  1.44780174])],
 [array([ 1.44780174,  1.44780174]), array([ 1.83518299,  1.83518299])],
 [array([ 1.83518299,  1.83518299]), array([ 2.15765404,  2.15765404])],
 [array([ 2.15765404,  2.15765404]), array([ 2.5547699,  2.5547699])],
 [array([ 2.5547699,  2.5547699]), array([ 2.94069359,  2.94069359])],
 [array([ 2.94069359,  2.94069359]), array([ 3.20748345,  3.20748345])],
 [array([ 3.20748345,  3.20748345]), array([ 3.5292468,  3.5292468])],
 [array([ 3.5292468,  3.5292468]), array([ 3.84734642,  3.84734642])],
 [array([ 3.84734642,  3.84734642]), array([ 4.13949728,  4.13949728])],
 [array([ 4.13949728,  4.13949728]), array([ 4.47815915,  4.47815915])],
 [array([ 4.47815915,  4.47815915]), array([ 4.8437196,  4.8437196])],
 [array([ 4.8437196,  4.8437196]), array([ 5.16412818,  5.16412818])],
 [array([ 5.16412818,  5.16412818]), array([ 5.43602813,  5.43602813])],
 [array([ 5.43602813,  5.43602813]), array([ 5.70492577,  5.70492577])],
 [array([ 5.70492577,  5.70492577]), array([ 5.97586883,  5.97586883])],
 [array([ 5.97586883,  5.97586883]), array([ 6.20456883,  6.20456883])],
 [array([ 6.20456883,  6.20456883]), array([ 6.45552362,  6.45552362])],
 [array([ 6.45552362,  6.45552362]), array([ 6.74449331,  6.74449331])],
 [array([ 6.74449331,  6.74449331]), array([ 7.04019852,  7.04019852])],
 [array([ 7.04019852,  7.04019852]), array([ 7.36169831,  7.36169831])],
 [array([ 7.36169831,  7.36169831]), array([ 7.64859046,  7.64859046])],
 [array([ 7.64859046,  7.64859046]), array([ 7.9229868,  7.9229868])],
 [array([ 7.9229868,  7.9229868]), array([ 8.25519441,  8.25519441])],
 [array([ 8.25519441,  8.25519441]), array([ 8.48854087,  8.48854087])],
 [array([ 8.48854087,  8.48854087]), array([ 8.76599252,  8.76599252])],
 [array([ 8.76599252,  8.76599252]), array([ 9.11941641,  9.11941641])],
 [array([ 9.11941641,  9.11941641]), array([ 9.42341015,  9.42341015])],
 [array([ 9.42341015,  9.42341015]), array([ 9.70900433,  9.70900433])],
 [array([ 9.70900433,  9.70900433]), [10.0, 10.0]]]
```

and `color_array` is:
```python
In [5]: import numpy

In [12]: p = LineOver1DRangeSeries(x, (x, -10, 10)).get_points()

In [13]: color_array = numpy.mean(numpy.vstack((p[0][:-1], p[0][1:])), 0)

In [14]: color_array
Out[14]:
array([-9.96655518, -9.89966555, -9.83277592, -9.76588629, -9.69899666,
       -9.63210702, -9.56521739, -9.49832776, -9.43143813, -9.36454849,
       -9.29765886, -9.23076923, -9.1638796 , -9.09698997, -9.03010033,
       -8.9632107 , -8.89632107, -8.82943144, -8.76254181, -8.69565217,
       -8.62876254, -8.56187291, -8.49498328, -8.42809365, -8.36120401,
       -8.29431438, -8.22742475, -8.16053512, -8.09364548, -8.02675585,
       -7.95986622, -7.89297659, -7.82608696, -7.75919732, -7.69230769,
       -7.62541806, -7.55852843, -7.4916388 , -7.42474916, -7.35785953,
       -7.2909699 , -7.22408027, -7.15719064, -7.090301  , -7.02341137,
       -6.95652174, -6.88963211, -6.82274247, -6.75585284, -6.68896321,
       -6.62207358, -6.55518395, -6.48829431, -6.42140468, -6.35451505,
       -6.28762542, -6.22073579, -6.15384615, -6.08695652, -6.02006689,
       -5.95317726, -5.88628763, -5.81939799, -5.75250836, -5.68561873,
       -5.6187291 , -5.55183946, -5.48494983, -5.4180602 , -5.35117057,
       -5.28428094, -5.2173913 , -5.15050167, -5.08361204, -5.01672241,
       -4.94983278, -4.88294314, -4.81605351, -4.74916388, -4.68227425,
       -4.61538462, -4.54849498, -4.48160535, -4.41471572, -4.34782609,
       -4.28093645, -4.21404682, -4.14715719, -4.08026756, -4.01337793,
       -3.94648829, -3.87959866, -3.81270903, -3.7458194 , -3.67892977,
       -3.61204013, -3.5451505 , -3.47826087, -3.41137124, -3.34448161,
       -3.27759197, -3.21070234, -3.14381271, -3.07692308, -3.01003344,
       -2.94314381, -2.87625418, -2.80936455, -2.74247492, -2.67558528,
       -2.60869565, -2.54180602, -2.47491639, -2.40802676, -2.34113712,
       -2.27424749, -2.20735786, -2.14046823, -2.0735786 , -2.00668896,
       -1.93979933, -1.8729097 , -1.80602007, -1.73913043, -1.6722408 ,
       -1.60535117, -1.53846154, -1.47157191, -1.40468227, -1.33779264,
       -1.27090301, -1.20401338, -1.13712375, -1.07023411, -1.00334448,
       -0.93645485, -0.86956522, -0.80267559, -0.73578595, -0.66889632,
       -0.60200669, -0.53511706, -0.46822742, -0.40133779, -0.33444816,
       -0.26755853, -0.2006689 , -0.13377926, -0.06688963,  0.        ,
        0.06688963,  0.13377926,  0.2006689 ,  0.26755853,  0.33444816,
        0.40133779,  0.46822742,  0.53511706,  0.60200669,  0.66889632,
        0.73578595,  0.80267559,  0.86956522,  0.93645485,  1.00334448,
        1.07023411,  1.13712375,  1.20401338,  1.27090301,  1.33779264,
        1.40468227,  1.47157191,  1.53846154,  1.60535117,  1.6722408 ,
        1.73913043,  1.80602007,  1.8729097 ,  1.93979933,  2.00668896,
        2.0735786 ,  2.14046823,  2.20735786,  2.27424749,  2.34113712,
        2.40802676,  2.47491639,  2.54180602,  2.60869565,  2.67558528,
        2.74247492,  2.80936455,  2.87625418,  2.94314381,  3.01003344,
        3.07692308,  3.14381271,  3.21070234,  3.27759197,  3.34448161,
        3.41137124,  3.47826087,  3.5451505 ,  3.61204013,  3.67892977,
        3.7458194 ,  3.81270903,  3.87959866,  3.94648829,  4.01337793,
        4.08026756,  4.14715719,  4.21404682,  4.28093645,  4.34782609,
        4.41471572,  4.48160535,  4.54849498,  4.61538462,  4.68227425,
        4.74916388,  4.81605351,  4.88294314,  4.94983278,  5.01672241,
        5.08361204,  5.15050167,  5.2173913 ,  5.28428094,  5.35117057,
        5.4180602 ,  5.48494983,  5.55183946,  5.6187291 ,  5.68561873,
        5.75250836,  5.81939799,  5.88628763,  5.95317726,  6.02006689,
        6.08695652,  6.15384615,  6.22073579,  6.28762542,  6.35451505,
        6.42140468,  6.48829431,  6.55518395,  6.62207358,  6.68896321,
        6.75585284,  6.82274247,  6.88963211,  6.95652174,  7.02341137,
        7.090301  ,  7.15719064,  7.22408027,  7.2909699 ,  7.35785953,
        7.42474916,  7.4916388 ,  7.55852843,  7.62541806,  7.69230769,
        7.75919732,  7.82608696,  7.89297659,  7.95986622,  8.02675585,
        8.09364548,  8.16053512,  8.22742475,  8.29431438,  8.36120401,
        8.42809365,  8.49498328,  8.56187291,  8.62876254,  8.69565217,
        8.76254181,  8.82943144,  8.89632107,  8.9632107 ,  9.03010033,
        9.09698997,  9.1638796 ,  9.23076923,  9.29765886,  9.36454849,
        9.43143813,  9.49832776,  9.56521739,  9.63210702,  9.69899666,
        9.76588629,  9.83277592,  9.89966555,  9.96655518])
```

**Comment by jklymak** [comment] 2017-12-18 20:10
Got an email about this w what I assume was a removed comment.  If at all possible a use case that doesn’t use sympy or other external dependencies beyond numpy would be appreciated.

**Comment by gxyd** [comment] 2017-12-18 20:11
Yes, I'm just looking into it.

**Comment by moorepants** [comment] 2017-12-18 20:57
I like @ylemkimon suggestion:

> I think we should fix(lock) dependencies' versions and update them by a PR.

but I think we should support a range of dependencies. Maybe support all versions of dependencies that are available since the last SymPy release was made (or something similar). This would tie dependency version support to real time.

**Comment by ylemkimon** [comment] 2017-12-19 04:40
@jklymak Sorry, I thought I've isolated its use case, but it didn't reproduce the problem.

**Comment by gxyd** [comment] 2017-12-19 16:14
@jklymak I can't seem to figure out a use case not using sympy.

**Comment by jklymak** [comment] 2017-12-19 16:25
@dstansby do you know what the use case is hat fails?  

@gxyd we have a fix on our end.  It’d just be nice to know why it was failing.

**Comment by jksuom** [comment] 2017-12-20 11:13
This a simplified version the code in SymPy:
```
>>> from matplotlib import pyplot
>>> from matplotlib.collections import LineCollection
>>> fig = pyplot.figure()
GLib-GIO-Message: 13:00:46.624: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
>>> ax = fig.add_subplot(111)
>>> list = [[[0, 0], [1, 1]]]
>>> coll = LineCollection(list)
>>> coll.set_label("line")
>>> ax.add_collection(coll)
<matplotlib.collections.LineCollection object at 0x7fe2d005f150>
>>> coll = LineCollection(list)
>>> coll.set_label("line")
>>> ax.add_collection(coll)
<matplotlib.collections.LineCollection object at 0x7fe2d005f6d0>
>>> ax.legend()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jks/miniconda3/envs/python2/lib/python2.7/site-packages/matplotlib/axes/_axes.py", line 497, in legend
    **kwargs)
  File "/home/jks/miniconda3/envs/python2/lib/python2.7/site-packages/matplotlib/legend.py", line 1402, in _parse_legend_args
    handles, labels = _get_legend_handles_labels(axs, handlers)
  File "/home/jks/miniconda3/envs/python2/lib/python2.7/site-packages/matplotlib/legend.py", line 1360, in _get_legend_handles_labels
    and not _in_handles(handle, label)):
  File "/home/jks/miniconda3/envs/python2/lib/python2.7/site-packages/matplotlib/legend.py", line 1339, in _in_handles
    if f_h.get_color() != h.get_color():
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
>>> 
```

**Comment by jklymak** [comment] 2017-12-20 20:47
Thanks so much for the re-producible example.  We've had a few more good examples as well.

This is definitely a bug, caused by rolling buggy code from one part of the code-base to another.  Locking out 2.1.1 is reasonable.  I hope this will be fixed soon on 2.1.2.  My apologies for the inconvenience 

https://github.com/matplotlib/matplotlib/pull/10064 I think is the proper solution.  But see also 
https://github.com/matplotlib/matplotlib/pull/10031 which will fix your particular bug (but not others)

**Comment by jklymak** [comment] 2017-12-21 16:10
matplotlib/matplotlib#10064 was merged, so this bug should be fixed in Matplotlib 2.1.2.

**Comment by ylemkimon** [comment] 2017-12-21 18:32
@jklymak Thank you!

Will close this issue when matplotlib 2.1.2 is released and #13740 is reverted.

**Comment by jklymak** [comment] 2017-12-21 18:39
If you just changed #13740 to `matplotlib!=2.1.1` would that not work?  Then you’d just automatically get 2.1.2 when that comes out (though of course we hope that doesn’t break anything ;-)

**Comment by asmeurer** [comment] 2017-12-21 23:20
I think it's better to test against the latest matplotlib. That way these issues get caught and fixed right away, before any SymPy releases are made, rather than remaining latent and only being noticed after we make a SymPy release. 

In other words, the fact that we caught this is a good thing.

**Comment by asmeurer** [comment] 2017-12-22 00:08
With that being said, the current workaround is fine. But we should definitely remove it before we do any SymPy release (I'm assuming/hoping that matplotlib has a faster release cycle than we do).

**Closed** 2018-01-23 13:50 UTC
