### ISSUE TITLE
RisingFactorial cannot do numerical (floating point) evaluations

### ISSUE THREAD

**Issue by cbm755** [sympy/sympy#14822] opened 2018-06-22 06:02 UTC
```
>>> x = Float(S(2)/3, 32)
>>> RisingFactorial(18, x)
RisingFactorial(18, 0.66666666666666666666666666666667)
>>> N(_)
RisingFactorial(18, 0.66666666666666666666666666666667)
>>> _.doit()
RisingFactorial(18, 0.66666666666666666666666666666667)
```

Expected result: something like `6.82615401311257` (but with 32 digits).

- - - - -

There is an `mpmath.rf` and it works fine.  I think its just not "connected" to sympy, perhaps because the names `rf` and `RisingFactorial` are different.

So probably this is an easy fix: find out how other special functions talk to `mpmath` and make it work for `RisingFactorial` (and `FallingFactorial` while you're at it).

**Comment by avishrivastava11** [comment] 2018-06-22 07:28
@cbm755 I would like to work on this.
Please provide me with a few hints as well.
(I'm a newbie so pls bear with me. :)

**Comment by cbm755** [comment] 2018-06-22 07:59
I already gave my suggestions about first steps...  In a bit more detail:

1.  convince yourself that `mpmath.rf` does the right thing.
2.  Pick another function (`factorial`, `besseli`, `beta`, `bernoulli`, etc).  Check if they work (they do) and if they call `mpmath.something`.
3.  Dig into code to see *how* they call mpmath.
4.  Dig into `RisingFactorial` to see what is different.

Please note: if I could really give step-by-step hints I would know how to fix it myself right? ;-)

**Comment by avishrivastava11** [comment] 2018-06-22 09:43
@cbm755  I got into the code and it turns out that `RisingFactorial` is actually assigned to `rf` later-on.
So the issue is not because of that ( as you commented above ) 

>There is an `mpmath.rf` and it works fine. I think its just not "connected" to sympy, perhaps because the names `rf` and `RisingFactorial` are different.

It also turns out that the issue is only occurring when there's a floating point number as an argument.

Also, other functions (`factorial`, `besseli`, `beta`, `bernoulli`, etc)  aren't calling `mpmath.something` at all.(according to the code)
PS. Pls Correct me if i'm wrong here.

But I couldn't figure out that how you are getting `mpmath.rf` to do the right thing. Could you pls elaborate a bit on this?

**Comment by avishrivastava11** [comment] 2018-06-22 17:07
Almost done..
Waiting for completion of tests.

**Comment by avishrivastava11** [comment] 2018-06-23 06:54
@cbm755 
It's working now. :) 
I'll submit a PR once I finish remodelling the assertions

**Comment by avishrivastava11** [comment] 2018-06-24 05:30
@cbm755  I am currently working on another solution which will fill the discrepancies in this one and also make the results symbolic.
I'll be submitting another PR soon.

**Comment by cbm755** [comment] 2018-06-24 05:42
You should use the same PR.

**Comment by avishrivastava11** [comment] 2018-06-24 06:41
@cbm755   @asmeurer 
Also, 
once the code starts working,
I'm getting the following assertion error (which is no surprise)
`assert rf(n, m).is_integer is True
AssertionError
`
since the resultant will not necessarily be an integer.
So should I change the assertion ?
I mean modify the test file containing that (and a couple of other assertions) ?

**Comment by avishrivastava11** [comment] 2018-06-24 08:49
@cbm755 @asmeurer
I have made another PR. (implementing changes a bit differently)
( @cbm755 Sorry I didn't read your message earlier, or I would've made changes in the same PR)
Pls do give me a feedback on the new PR. :)
Thanks.

**Comment by asmeurer** [comment] 2018-06-24 20:36
If mpmath already has a function for it then you should be able to just add it to the evalf_table.

**Comment by avishrivastava11** [comment] 2018-06-25 05:35
@asmeurer where can i find the evalf table?

**Comment by jksuom** [comment] 2018-06-25 07:41
`sympy.core.evalf`, in `_create_evalf_table()`.

**Comment by avishrivastava11** [comment] 2018-07-11 06:29
@asmeurer @jksuom  
>If mpmath already has a function for it then you should be able to just add it to the evalf_table.

When I add it to the evalf_table, I would also be required to add the method corresponding to `rf` and `ff`, (as done with `bernoulli`, there is a method `evalf_bernoulli` added) ?
Or should I just somehow direct it to the class `RisingFactorial` (and `FallingFactorial`) present in `factorials.py` ?

**Comment by ramvenkat98** [comment] 2018-07-22 07:15
Hi,

I've tried to fix this issue by adding _eval_evalf methods to the RisingFactorial and FallingFactorial classes. I added test cases and created a pull request referencing this issue. This is my first time contributing, so please let me know how I should proceed.

Thank you!

**Closed** 2018-07-24 03:46 UTC
Labels: Easy to Fix, floats, functions
