### ISSUE TITLE
lambdifying with numpy module does not give an adequate traceback when arguments are missing

### ISSUE THREAD

**Issue by fccoelho** [sympy/sympy#9122] opened 2015-03-11 21:20 UTC
Hi I am experiencing a Bug when evaluating a lambdified matrix

``` python
B = sympy.lambdify(vsymbols, B, "numpy")
```

B is a large sparse matrix with a few non-zero elements which are square roots of symbolic variables.

I lambdify it to substitute numerical values a do some numeric computations more efficiently that with evalf. but I keep geting the error.

any ideas?

**Comment by moorepants** [comment] 2015-03-11 21:49
Can you provide us with a minimal example of what `B` looks like?

I'm not sure lambdify can even handle sparse sympy matrices.

**Comment by fccoelho** [comment] 2015-03-12 14:19
FYI, lambdfy sems to work fine with sparse matrices I tested with a symbolic identity matrix:
```python
m = eye(50)*-sqrt(x*y)
M=lambdify((x,y), m, "numpy")
```
lambdify works just fine with this matrix. 

I found that the issue was a missing symbol in the call to lambdify. So, my mistake. However, the stack trace was missing in "numpy" mode. When I called without specifying the mode, I finally got the stack trace showing me the missing symbolic variable.

**Comment by meghana1995** [comment] 2015-03-19 12:38
Hey! I took a look at this and it seems to me that you got the 'missing argument' error when you did not specify the mode because you had only one argument (which is less than the required 2 arguments). However, when you specified the mode, it took the string "numpy" as the required expression (the second argument) hence printing an irrelevant error. One way to fix this is by raising an exception if the second argument is a string. Is there a better way to fix this? Or should I go ahead with raising the exception?

**Comment by toolforger** [comment] 2015-03-19 13:25
If the code can't fulfil its purpose because the caller had an error, raising an exception is pretty much the only thing it can do, so I'm +1 with that plan.
If you're going to touch that code anyway, can you check that the requirements on the parameters are clearly documented in the docstring? (No sweat if you can't, it would just be a nice follow-up.)

**Comment by moorepants** [comment] 2015-03-19 16:30
I just tried to reproduce @fccoelho's issue but was not able to do so:

```
In [1]: import sympy as sm

In [2]: x, y = sm.symbols('x, y')

In [3]: f = sm.lambdify((x, y), x + y)

In [4]: f(1.0, 2.0)
Out[4]: 3.0

In [5]: f = sm.lambdify((x, y), x + y, 'numpy')

In [6]: f(1.0, 2.0)
Out[6]: 3.0

In [7]: f = sm.lambdify((x), x + y)

In [8]: f(1.0, 2.0)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-8-1cd56e3fb848> in <module>()
----> 1 f(1.0, 2.0)

TypeError: <lambda>() takes exactly 1 argument (2 given)

In [9]: f = sm.lambdify((x), x + y, 'numpy')

In [10]: f(1.0, 2.0)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-10-1cd56e3fb848> in <module>()
----> 1 f(1.0, 2.0)

TypeError: <lambda>() takes exactly 1 argument (2 given)
```

So things seem to work consistently with and without the module specification. But I now question why we don't raise an error in the lambdify call. I guess we don't raise an error in lambdify because we have a "sympy" module backend that allows this:

```
In [11]: f = sm.lambdify((x), x + y, 'sympy')

In [12]: f(1.0, 2.0)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-12-1cd56e3fb848> in <module>()
----> 1 f(1.0, 2.0)

TypeError: <lambda>() takes exactly 1 argument (2 given)

In [13]: f(1.0)
Out[13]: y + 1.0
```

@fccoelho Can you clarify what the error was here? I don't think we understand what the issue is. If you could paste in a python session like I have above that shows your error, that would help.

**Comment by moorepants** [comment] 2015-03-19 16:36
Here is one error I was able to raise:

```
In [30]: m = sm.SparseMatrix([x, y, 0, 0, 0])

In [31]: f = sm.lambdify((x, y), m, 'numpy')

In [32]: f(1.0, 2.0)
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-32-1cd56e3fb848> in <module>()
----> 1 f(1.0, 2.0)

/home/moorepants/anaconda/lib/python2.7/site-packages/numpy/__init__.pyc in <lambda>(_Dummy_29, _Dummy_30)

NameError: global name 'ImmutableSparseMatrix' is not defined
```

I don't think sparse matrices are supported by lambdifying with numpy, as numpy doesn't even have sparse matrices. It would be nice to support the sparse matrices in SciPy. Maybe this is the error that @fccoelho hit?

**Comment by jcrist** [comment] 2015-03-19 18:24
So, how lambdify works is that it prints most things the same way they'd be printed for SymPy, but then "injects" the desired functions into the namespace when the code string is evaluated. So in this case, `ImmutableSparseMatrix` is printed as `ImmutableSparseMatrix`, but has nothing in the namespace dict to associate it to a numeric function. If there is one in the scipy/numpy ecosystem with the same call signature as SymPy's sparse matrices, then this is an easy fix (just add it to the modules system), otherwise the printer itself will have to be modified.

**Comment by moorepants** [comment] 2015-03-19 18:30
@jcrist Yes!

The main thing here is we don't actually know what error is being reported in this issue. We should just close it if @fccoelho doesn't clarify.

**Comment by meghana1995** [comment] 2015-03-19 18:45
What I understood of the error is that is that fccoelho forgot to include one parameter (The symbols (x,y) ) when calling the lambdify function. The issue is that the error was an incoherent message. So I suggested raising an exception whenever the actual parameter types don't match with the function parameter. This is an easy error/fix and I can fix it if necessary within a day or so. 
Basically, he ran it as M=lambdify( m,"numpy" ) instead of M=lambdify((x,y), m,"numpy" ) and got     func = eval(lstr, namespace)
  File "<string>", line 1
    lambda -sqrt(x*y),0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-sqrt(x*y),0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-sqrt(x*y),0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-sqrt(x*y),0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-sqrt(x*y),0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-sqrt(x*y),0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-sqrt(x*y),0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-sqrt(x*y),0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-sqrt(x*y),0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-sqrt(x*y),0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-sqrt(x*y),0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-sqrt(x*y),0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-sqrt(x*y),0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-sqrt(x*y),0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-sqrt(x*y),0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-sqrt(x*y),0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-sqrt(x*y),0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-sqrt(x*y),0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-sqrt(x*y),0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-sqrt(x*y),0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-sqrt(x*y),0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-sqrt(x*y),0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-sqrt(x*y),0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-sqrt(x*y),0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-sqrt(x*y),0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-sqrt(x*y),0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-sqrt(x*y),0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-sqrt(x*y),0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-sqrt(x*y),0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-sqrt(x*y),0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-sqrt(x*y),0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-sqrt(x*y),0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-sqrt(x*y),0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-sqrt(x*y),0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-sqrt(x*y),0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-sqrt(x*y),0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-sqrt(x*y),0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-sqrt(x*y),0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-sqrt(x*y),0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-sqrt(x*y),0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-sqrt(x*y),0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-sqrt(x*y),0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-sqrt(x*y),0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-sqrt(x*y),0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-sqrt(x*y),0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-sqrt(x*y),0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-sqrt(x*y),0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-sqrt(x*y),0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-sqrt(x*y),0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-sqrt(x*y): (numpy)
           ^
SyntaxError: invalid syntax 
as the error message.

**Comment by debugger22** [comment] 2015-03-19 18:50
IMO he's trying to say that he didn't get good stack trace for the obvious error when he used "numpy" argument.

**Comment by jcrist** [comment] 2015-03-19 18:57
Ah, I see. A simple

```
if not isinstance(expr, (Basic, MatrixBase)):
    raise TypeError("expr must be a valid sympy expression")
```

on is really all that's needed then.

**Comment by moorepants** [comment] 2015-03-19 18:59
This is what @fccoelho writes: "I found that the issue was a missing symbol in the call to lambdify." he doesn't say missing "all symbols" or "missing the first argument to lambdify". So from what he writes I assumed he forgot one of the symbols in the arg sequence passed to lambdify.

But @meghana1995 thinks he forgot the whole first argument to lambdify, i.e. the list of the arguments. Which may be true. If it is, then this may be one of the times to default to "garbage in, garbage out". If you don't give the correct # or type of arguments specified in the docstring, then you get garbage out.

But we can certainly add some input checks. The first argument to lambdify should be a sequence and the second should be some type of expression. Nothing else should be allowed. So that's a reasonable check to add.

**Comment by meghana1995** [comment] 2015-03-19 19:13
Will adding
    if not isinstance(expr, (Basic, MatrixBase)):
	raise TypeError("expr must be a valid sympy expression")
    if not ((isinstance(args, list))  or  (isinstance(args, Symbol)) or (isinstance(args, tuple))):
	raise TypeError("args must be a symbol or a tuple of symbols")
suffice?
If so, ill send a pull request. (I'm new to open source and this is one of my first few bugs so I would just like to confirm)

**Comment by moorepants** [comment] 2015-03-19 19:22
That's seems like a good start. Make a pull request and we can discuss further there.

**Comment by meghana1995** [comment] 2015-03-19 20:43
Ok, Im getting an error 403 while trying to push my branch. There seems to be a problem so it may take me a couple of days. Once thats resolved, I'll make a pull request. Sorry for the delay.

**Comment by debugger22** [comment] 2015-03-19 20:44
Are you pushing directly to origin?

**Comment by meghana1995** [comment] 2015-03-19 20:47
yes, I am

**Comment by debugger22** [comment] 2015-03-19 20:55
Since you don't have push access now, you should push it to your fork and then make a pull request.

**Comment by meghana1995** [comment] 2015-03-19 21:04
Ok I'll try that out. Thank you !

**Comment by rahilhastu** [comment] 2018-02-18 08:12
can I implement what @megh1241 is trying to do?
or the issue already has a PR?

**Comment by czgdp1807** [comment] 2020-04-15 07:40
@moorepants The following works fine on `master`,
```python
>>> m = SparseMatrix([x, y, 0, 0, 0])
>>> f = lambdify((x, y), m, 'numpy')
>>> f(1.0, 2.0)
[[1.] 
 [2.] 
 [0.] 
 [0.] 
 [0.]]
>>> import numpy
>>> numpy.__version__
1.18.1
```
May be we can close this.

**Comment by moorepants** [comment] 2020-04-15 16:34
Sure.

**Closed by moorepants** 2020-04-15 16:34 UTC
Labels: Could Close, Easy to Fix, printing, utilities.codegen
