### ISSUE TITLE
subs into equality on same equation but different variable treat's differently.

### ISSUE THREAD

**Issue by tyagi-prashant** [sympy/sympy#10106] opened 2015-11-03 19:35 UTC
```
>>> from sympy import *
>>> var('x')
x
>>> eq=RootOf(x**3 - 17*x**2 + 81*x - 118, 0)
>>> (x<eq).subs(x,eq)

This is the error that came:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tyagi221295/miniconda/envs/sympy-dev-py27/lib/python2.7/site-packages/sympy-0.7.7.dev0-py2.7.egg/sympy/core/basic.py", line 895, in subs
    rv = rv._subs(old, new, **kwargs)
  File "/home/tyagi221295/miniconda/envs/sympy-dev-py27/lib/python2.7/site-packages/sympy-0.7.7.dev0-py2.7.egg/sympy/core/cache.py", line 93, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/home/tyagi221295/miniconda/envs/sympy-dev-py27/lib/python2.7/site-packages/sympy-0.7.7.dev0-py2.7.egg/sympy/core/compatibility.py", line 880, in wrapper
    result = user_function(*args, **kwds)
  File "/home/tyagi221295/miniconda/envs/sympy-dev-py27/lib/python2.7/site-packages/sympy-0.7.7.dev0-py2.7.egg/sympy/core/basic.py", line 1009, in _subs
    rv = fallback(self, old, new)
  File "/home/tyagi221295/miniconda/envs/sympy-dev-py27/lib/python2.7/site-packages/sympy-0.7.7.dev0-py2.7.egg/sympy/core/basic.py", line 981, in fallback
    arg = arg._subs(old, new, **hints)
  File "/home/tyagi221295/miniconda/envs/sympy-dev-py27/lib/python2.7/site-packages/sympy-0.7.7.dev0-py2.7.egg/sympy/core/cache.py", line 93, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/home/tyagi221295/miniconda/envs/sympy-dev-py27/lib/python2.7/site-packages/sympy-0.7.7.dev0-py2.7.egg/sympy/core/compatibility.py", line 880, in wrapper
    result = user_function(*args, **kwds)
  File "/home/tyagi221295/miniconda/envs/sympy-dev-py27/lib/python2.7/site-packages/sympy-0.7.7.dev0-py2.7.egg/sympy/core/basic.py", line 1009, in _subs
    rv = fallback(self, old, new)
  File "/home/tyagi221295/miniconda/envs/sympy-dev-py27/lib/python2.7/site-packages/sympy-0.7.7.dev0-py2.7.egg/sympy/core/basic.py", line 986, in fallback
    rv = self.func(*args)
  File "/home/tyagi221295/miniconda/envs/sympy-dev-py27/lib/python2.7/site-packages/sympy-0.7.7.dev0-py2.7.egg/sympy/polys/rootoftools.py", line 68, in __new__
    poly = PurePoly(f, x, greedy=False, expand=expand)
  File "/home/tyagi221295/miniconda/envs/sympy-dev-py27/lib/python2.7/site-packages/sympy-0.7.7.dev0-py2.7.egg/sympy/polys/polytools.py", line 89, in __new__
    return cls._from_expr(rep, opt)
  File "/home/tyagi221295/miniconda/envs/sympy-dev-py27/lib/python2.7/site-packa
ges/sympy-0.7.7.dev0-py2.7.egg/sympy/polys/polytools.py", line 199, in _from_expr
    rep, opt = _dict_from_expr(rep, opt)
  File "/home/tyagi221295/miniconda/envs/sympy-dev-py27/lib/python2.7/site-packages/sympy-0.7.7.dev0-py2.7.egg/sympy/polys/polyutils.py", line 366, in _dict_from_expr
    rep, gens = _dict_from_expr_no_gens(expr, opt)
  File "/home/tyagi221295/miniconda/envs/sympy-dev-py27/lib/python2.7/site-packages/sympy-0.7.7.dev0-py2.7.egg/sympy/polys/polyutils.py", line 311, in _dict_from_expr_no_gens
    (poly,), gens = _parallel_dict_from_expr_no_gens((expr,), opt)
  File "/home/tyagi221295/miniconda/envs/sympy-dev-py27/lib/python2.7/site-packages/sympy-0.7.7.dev0-py2.7.egg/sympy/polys/polyutils.py", line 272, in _parallel_dict_from_expr_no_gens
    raise GeneratorsNeeded("specify generators to give %s a meaning" % arg)
sympy.polys.polyerrors.GeneratorsNeeded: specify generators to give -17*RootOf(x**3 - 17*x**2 + 81*x - 118, 0)**2 - 118 + RootOf(x**3 - 17*x**2 + 81*x - 118, 0)**3 + 81*RootOf(x**3 - 17*x**2 + 81*x - 118, 0) a meaning

But when same thing is done with y as a variable:


>>> var('y')
y
>>> eq1=RootOf(y**3 - 17*y**2 + 81*y - 118, 0)
>>> (y<eq1).subs(y,eq1)
False
>>> 

```
@asmeurer please verify the issue

**Comment by VinaySingh035** [comment] 2015-11-03 20:02
@tyagi-prashant  it seems to me that here the error is only in the case when the variable is "x".

For other variables it works fine.
I will be happy to work on.

Regards,
Vinay

**Comment by smichr** [comment] 2015-11-04 17:41
duplicate of #10092; conversation continue there.

**Closed by smichr** 2015-11-04 17:41 UTC
Labels: duplicate
