### ISSUE TITLE
Ensuring that sympy is importable on Python 2

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#16257] opened 2019-03-14 13:31 UTC
#16254 shows that it's possible to pass the Travis tests even if sympy cannot be imported under Python 2. See [https://github.com/sympy/sympy/issues/16254#issuecomment-472813993](https://github.com/sympy/sympy/issues/16254#issuecomment-472813993)

**Comment by asmeurer** [comment] 2019-03-14 21:45
It looks like it works after SymPy is installed. I don't know why. Somehow when Python 2 compiles the pyc during the setup phase, the coding is fine. I tested installing SymPy into an empty Python 2 conda environment in the branch from https://github.com/sympy/sympy/pull/16221 and it imports. If I delete the installed pyc file for sympy/printing/mathematica.pyc, I get the import error.

**Comment by asmeurer** [comment] 2019-03-14 21:47
You can also run `python2 -m compileall sympy/` and it will compile the mathematica.pyc file, and become importable.

**Comment by asmeurer** [comment] 2019-03-14 22:05
I guess the `py_compile` module in Python 2 doesn't try to reproduce encoding errors that the importer would give. I'm not sure if there is a simple fix for this. We could add a test that every file with a non-ASCII character has a [PEP 263](https://www.python.org/dev/peps/pep-0263/) coding line. 

It's a non-issue in Python 3, since the default encoding there is UTF-8, so `coding` lines aren't necessary. Unless somehow a non-UTF-8 byte sequence can make its way into a file and produce the same issue. We have had issues where files had BOM characters in them, which Python ignores (https://github.com/sympy/sympy/issues/10974).

**Comment by asmeurer** [comment] 2019-03-14 23:03
According to https://stackoverflow.com/questions/1301402/example-invalid-utf8-string, the string "\xc3\x28" is invalid UTF-8. 

I did

```py
with open('test.py', 'wb') as f:
    f.write(b'"')
    f.write(b"\xc3\x28")
    f.write(b'"\n')
```

The `python3 test.py` and `python3 -m compileall test.py` both produce a SyntaxError. So unless there are other corner cases I'm not aware of, this issue shouldn't exist in Python 3.

**Comment by asmeurer** [comment] 2019-03-14 23:08
Also confirmed the same test.py exhibits the same behavior in Python 2. If you import it or run it, it fails, but if you compile it to pyc first with `compileall`, it works just fine.

Unless someone wants to code up a test for this, I would suggest leaving it as won't fix. It will become a nonissue after we drop Python 2 support later this year, and it seems too difficult to fully correct. And one can always detect it manually by trying to import sympy from a clean git clone in Python 2. Anyway, I don't plan on fixing it, but if someone else wants to go ahead.

**Comment by oscarbenjamin** [comment] 2019-03-14 23:13
Maybe we could add something to the quality tests that checks for non-ascii characters (with a whitelist for some files).

Do we generally want to reject non-ASCII in the code (after Py2 is dropped)? Python 3 handles unicode in the actual code quite nicely and on the face of it SymPy should be a prime beneficiary of that.

**Comment by sylee957** [comment] 2019-03-15 07:23
From the comment in #16255
> make non-ASCII characters work in strings by adding # -*- coding: utf-8 -*- to the top of the file.

I guess this would the reason that some files have those statement.
Then, would it be better to add

```python
# -*- coding: utf-8 -*-
``` 
to every files we have,
like we already have 
```python
from __future__ import print_function, division
```
If there is no harm of doing so?

**Comment by oscarbenjamin** [comment] 2019-03-15 15:18
>  Then, would it be better to add

Adding the encoding cookie would mean that ASCII characters don't lead to errors. However I don't think we want to generally allow non-ASCII characters in the code. They cause other problems like not displaying in editors etc.

Under Python 3 utf-8 is the default encoding always so this would only be needed as long as Python 2 is around. I still think that this will be a code quality issue once Python 2 is dropped.

As for this issue though there are other reasons why a file might become unimportable. We should have some kind of test that properly imports modules to check for this and it should run on all Python versions.

**Comment by asmeurer** [comment] 2019-03-15 20:46
This is the only issue I know of where unimportable code will pass through the checks that are already there. The problem is that `compileall` doesn't raise the error. 

The test for this is not too complicated actually. Just check each file and if it has non-ASCII characters and doesn't have a coding line, it fails the check. 

We could add the coding line to each file, but that's probably unnecessary.  Most files shouldn't be using Unicode characters, unless we want to move to using more Unicode pretty printing in docstrings (related: https://github.com/sympy/sympy/issues/15700), and inline math should generally use latex instead of Unicode characters. It is also necessary if a string uses an accented character. In the case above, there was a `…` instead of `...`, which is actually better to avoid.

**Comment by oscarbenjamin** [comment] 2019-03-16 00:56
To be clear I don't know of another instance where unimportable code will pass through all the checks but I also didn't know about this one before it happened :)

**Comment by oscargus** [comment] 2022-01-05 17:17
Since we have dropped Python 2 support, I close this.

**Closed by oscargus** 2022-01-05 17:17 UTC
Labels: Testing, Travis
