### ISSUE TITLE
Performance regression in lu_solve

### ISSUE THREAD

**Issue by moorepants** [sympy/sympy#14673] opened 2018-04-29 14:45 UTC
Offending PR:

https://github.com/sympy/sympy/pull/12521

Benchmarks:

http://www.moorepants.info/misc/sympy-asv/#solve.TimeMatrixSolve2.time_lusolve

**Comment by oscarbenjamin** [comment] 2019-10-26 18:58
I tried with this script that represents the benchmark:
```python
from sympy import *
import sympy

n = 3

A = sympy.Matrix(n, n, lambda i, j: sympy.Symbol('a{}{}'.format(i, j)))
b = sympy.Matrix(n, 1, lambda i, j: sympy.Symbol('b{}{}'.format(i, j)))
A_sym = sympy.Matrix(n, n, lambda i, j:
                     sympy.Symbol('a{}{}'.format(*sorted((i, j)))))

import time
for n in range(3):
    t = time.time()
    A_sym.solve(b)
    print('%.3g seconds' % (time.time() - t))
```
On master I get this:
```
$ python t.py 
1.27 seconds
0.689 seconds
0.746 seconds
```
On SymPy 1.1 I get:
```
$ python t.py 
0.66 seconds
0.558 seconds
0.558 seconds
```
So the slowdown is most prominent on the first run. Bisecting that leads to #14286. In particular I suspect these two lines:
https://github.com/sympy/sympy/blob/d85c30ef80cb6a4b9c53250bf4f549c8759b1141/sympy/simplify/simplify.py#L676-L677

If I add `import sympy.physics.units` at the top of the script above then the first run is not much slower than the others when running on master:
```
$ python t.py 
0.711 seconds
0.598 seconds
0.594 seconds
```

The slow down here just comes from importing `units`. I think that units import should be made faster. In fact it just got slower (#17766). The slowdown here though is just the fact that it gets imported at all.

**Comment by oscarbenjamin** [comment] 2019-11-20 00:18
I think that in this case the benchmarks did not pick up on a genuine performance regression. I think that importing units is slow but that is not a significant performance regression in lu_solve since it is a once per process problem. I might have misunderstood that and maybe there should be an issue for slow import of units.

For now I am closing this issue until someone can clarify what is to be fixed.

**Closed by oscarbenjamin** 2019-11-20 00:18 UTC
Labels: Performance, matrices
