### ISSUE TITLE
diff don't works correctly in sums

### ISSUE THREAD

**Issue by latot** [sympy/sympy#11762] opened 2016-10-24 23:03 UTC
Hi all, well here is:

```
>>> f=Function("f")(x)
>>> Sum(diff(f, x, k), (k, 0, oo))
  ∞    
 ___   
 ╲     
  ╲   0
  ╱    
 ╱     
 ‾‾‾   
k = 0 
```

Thx. Cya.

**Comment by cbm755** [comment] 2016-11-01 17:44
I don't think `diff(f, x, k)` is correct syntax for what you are trying to do:
````
>>> diff(f,x,k)
0
````

**Comment by cbm755** [comment] 2016-11-01 17:47
Oh wait, I thought you were trying to get `f'(k)`.  To clarify, @latot is wanting:

````
f(x) + f'(x) + f''(x) + f'''(x) + ...
````

But my comment probably indicates why your approach won't work: `diff(f, x, k)` is the 2nd partial derivative `f_{xk}`.

**Comment by cbm755** [comment] 2016-11-01 17:48
I think this bug should really be "how to represent the `k`th derivative where `k` is a Symbol?"

**Comment by asmeurer** [comment] 2016-11-01 18:22
Here's the issue for that https://github.com/sympy/sympy/issues/5575. Closing this as a dupe of that issue. The current behavior is correct (`diff(f, x, k)` represents `d^2/dxdk f(x)` which is indeed 0).

**Closed by asmeurer** 2016-11-01 18:22 UTC

**Comment by latot** [comment] 2016-11-02 22:33
Hi, i'm confused, following the expression i found in the wiki:
```Derivative(F, x, k) == d**k(F)/(dx)**k```
i don't understand very well your expression, because if we replace k in 2 we don't get the second derivative, while in the function we get it....
Can you explain a little more please?

Thx. Cya.

**Comment by asmeurer** [comment] 2016-11-02 22:40
That works only if `k` is an explicit integer value. Otherwise, it takes a derivative with respect to k. So: 

```
diff(f, x, 2) # Second derivative with respect to x
diff(f, x, y) # Derivative with respect to x and y
```

**Comment by latot** [comment] 2016-11-02 22:54
mm, Thx, when they improve the n° derivative, it will be accessible from Derivative in that format?, or we will have a new Derivative expression (like DerivativeN, ex)?

**Comment by asmeurer** [comment] 2016-11-03 00:42
The suggestion at #5575 is to use `diff(f, (x, k))`.

**Comment by latot** [comment] 2016-11-03 00:59
Why don't keep the actual format???, or that will be next format for derivatives?

**Comment by asmeurer** [comment] 2016-11-03 17:37
We can't use diff(f, x, k) because that's ambiguous if k is a symbol.

**Comment by latot** [comment] 2016-11-05 22:51
Hi, i think that is more a develop perspective, for the user, diff is derivative and only that, users don't know if you are using various class in that or something similar, so for the user don't is ambiguous that expression.
In some way can be ambiguous in the sense both are symbols, but the difference is when the expression enter to the diff don't is a symbol is a number. If we use a matrix with a collection of symbols and we use it in the sum there the symbol contain a symbol and should use it:
```
a=Matrix(['x', 'y'])
sum(f.diff(a[g(i)]), i, 0, oo)
```
