### ISSUE TITLE
problem in integration

### ISSUE THREAD

**Issue by mvanda** [sympy/sympy#12568] opened 2017-04-20 07:12 UTC
I input this simple code:

x=Symbol("x",real=True)
y=Symbol("y",real=True)
y0=Symbol("y0",positive=True)
print integrate(1/(1+y**2),(y,0,y0))   # correct result: atan(y0)
print integrate(1/(1+(x*y)**2),(y,0,y0))  # incorrect result: 0

I am using sympy 0.7.5 but I tried this code with sympy 1.0 on the web sympy live
with the same output.

The second integration is correct when x is defined as
x=Symbol("x",positive=True)

**Comment by jksuom** [comment] 2017-04-20 07:34
Essentially a duplicate of https://github.com/sympy/sympy/issues/12050. Closing.

**Closed by jksuom** 2017-04-20 07:34 UTC
