### ISSUE TITLE
Use of n(refractive index) in waves

### ISSUE THREAD

**Issue by 1e9abhi1e10** [sympy/sympy#24487] opened 2023-01-09 18:23 UTC
### Discussed in https://github.com/sympy/sympy/discussions/24479

<div type='discussions-op-text'>

<sup>Originally posted by **1e9abhi1e10** January  8, 2023</sup>
```python 
from sympy import symbols
from sympy.physics.optics import TWave
A, phi, f = symbols('A, phi, f')
w = TWave(A, f, phi)
print(w.speed)
```
Output `299792458*meter/(second*n)`
Here n is the refractive index, but in what way value of n is taken? if n is not given, then why is n=1 default not used for calculations?
why n=1 is not used for default conditions?
</div>

**Comment by ThePauliPrinciple** [comment] 2023-01-09 18:31
It's not clear to me what the issue is. What is wrong with `n` being a symbolic value here?

**Comment by 1e9abhi1e10** [comment] 2023-01-10 00:48
yeah, how should you calculate `n`?

**Comment by ThePauliPrinciple** [comment] 2023-01-10 08:50
SymPy is returning a formula for how to compute the speed for arbitrary `n`. If you don't have `n`, you can't compute the speed. The default value of `n` is `n`.

**Comment by abhishek-kuma** [comment] 2023-03-26 07:27
Yes symbolic mathematics works in this way only it does not take default value but works in variables for calculation.I guess you should now close the issue .

**Closed** 2023-04-01 03:11 UTC
