### ISSUE TITLE
Test failure in Python 3.11 alpha

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#23789] opened 2022-07-16 21:17 UTC
This test fails in Python 3.11 alpha:

```
_______________________________________________________ sympy/core/tests/test_function.py:test_subs_in_derivative _______________________________________________________
Traceback (most recent call last):
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/core/tests/test_function.py", line 746, in test_subs_in_derivative
    assert (abstract.subs(f, F).doit() - concrete).simplify() == 0
            ^^^^^^^^^^^^^^^^^^^
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/core/basic.py", line 997, in subs
    rv = rv._subs(old, new, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/core/cache.py", line 70, in wrapper
    retval = cfunc(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/core/basic.py", line 1111, in _subs
    rv = fallback(self, old, new)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/core/basic.py", line 1083, in fallback
    arg = arg._subs(old, new, **hints)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/core/cache.py", line 70, in wrapper
    retval = cfunc(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/core/basic.py", line 1111, in _subs
    rv = fallback(self, old, new)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/core/basic.py", line 1083, in fallback
    arg = arg._subs(old, new, **hints)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/core/cache.py", line 70, in wrapper
    retval = cfunc(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/core/basic.py", line 1109, in _subs
    rv = self._eval_subs(old, new)
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/core/function.py", line 2366, in _eval_subs
    expr = self.expr._subs(old, new)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/core/cache.py", line 70, in wrapper
    retval = cfunc(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/core/basic.py", line 1109, in _subs
    rv = self._eval_subs(old, new)
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/core/function.py", line 1738, in _eval_subs
    ofree = old.xreplace(syms).free_symbols
            ^^^^^^^^^^^^^^^^^^
TypeError: Basic.xreplace() missing 1 required positional argument: 'rule'
```

**Comment by oscarbenjamin** [comment] 2022-07-16 21:18
Duplicate of #23774

**Closed by oscarbenjamin** 2022-07-16 21:18 UTC
