### ISSUE TITLE
`linear_eq_to_matrix()` does not work with undefined functions

### ISSUE THREAD

**Issue by moorepants** [sympy/sympy#23459] opened 2022-05-03 11:30 UTC
```python
Python 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:04:10) 
Type 'copyright', 'credits' or 'license' for more information
IPython 8.3.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import sympy as sm

In [2]: sm.__version__
Out[2]: '1.11.dev'

In [3]: t, a, b = sm.symbols('t, a, b')

In [4]: f = sm.Function('f')(t)

In [5]: g = sm.Function('g')(t)

In [6]: eqs = [f.diff(t)*a + g.diff()*b, f.diff()*b**2 + g.diff()*a**2]

In [7]: sm.linear_eq_to_matrix(eqs, f.diff(), g.diff())
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Input In [7], in <cell line: 1>()
----> 1 sm.linear_eq_to_matrix(eqs, f.diff(), g.diff())

File ~/src/sympy/sympy/solvers/solveset.py:2575, in linear_eq_to_matrix(equations, *symbols)
   2573 for i in symbols:
   2574     if not isinstance(i, Symbol):
-> 2575         raise ValueError(filldedent('''
   2576         Expecting a Symbol but got %s
   2577         ''' % i))
   2579 if has_dups(symbols):
   2580     raise ValueError('Symbols must be unique')

ValueError: 
Expecting a Symbol but got Derivative(f(t), t)
```

This function is a bit too restrictive with the `isinstance()` check. anything that is symbol-like would ideally work. This works fine as an alternative:

```python
In [8]: sm.Matrix(eqs).jacobian([f.diff(), g.diff()])
Out[8]: 
Matrix([
[   a,    b],
[b**2, a**2]])
```

**Comment by moorepants** [comment] 2022-05-03 11:41
Related or same: https://github.com/sympy/sympy/issues/22372

**Comment by ThePauliPrinciple** [comment] 2022-05-03 19:55
What objects should not work? And why is this check here? Would it be appropriate to always replace any `i in symbols` that is not a `Symbol` with a `Dummy` (instead of throwing the error) and then substitute back at the end?

**Comment by moorepants** [comment] 2022-05-03 20:06
> What objects should not work?

I'd suggest any that can work.

> And why is this check here?

No idea. The function that extracts linear coefficients may have some limitations, but it could raise the errors.

> Would it be appropriate to always replace any i in symbols that is not a Symbol with a Dummy (instead of throwing the error) and then substitute back at the end?

That's a practical solution that is probably an appropriate fix.

**Comment by oscarbenjamin** [comment] 2022-05-03 23:11
Allowing more than just symbols is desirable but some thought needs to be given to define the expected behaviour in general. Restricting use to symbols avoids more complicated questions that should be answered. What if the equations involve both `f` and `f.diff()`? What other kinds of expressions could be given as the symbols e.g. could `exp(x)` and `sin(t)` be unknowns?What if `exp(x)` is a given symbol but the equation also involves `x`? Is it okay for `exp(x)` and `x` to be both listed as symbols?

**Comment by moorepants** [comment] 2022-05-04 07:18
For all of those examples, I think it is appropriate/ok to do the simplest solution, just give the linear coefficient of whatever expression is provided as a "symbol" and don't look into the mathematical form of the terms that end up in A and b. If the documentation says that is what it does, then there are no surprises.

**Comment by oscarbenjamin** [comment] 2022-05-04 11:16
The docstring for `linear_eq_to_matrix` says that it raises `NonlinearError` if the equations contain a nonlinear term e.g.:
```python
In [3]: linear_eq_to_matrix([x**2 + y], [x, y])
---------------------------------------------------------------------------
NonlinearError
```
The question is how you define what constitutes a nonlinear term if the symbols are more complicated than just symbols e.g.:
```python
linear_eq_to_matrix([Derivative(f(x), x) + f(x)], [f(x)])
```
Here you probably want the `Derivative(f(x), x)` to be treated as "independent" of `f(x)` but it clearly contains `f(x)`. Although differentiation is "linear" in some senses this equation is not *algebraically* linear in `f(x)`. What should be the rule in general?

If the unknown is `exp(x)` then what should happen if the equation has something like `exp(x+1)`? You could also have something like:
```python
In [9]: sin(x+1).expand(trig=True)
Out[9]: sin(x)⋅cos(1) + sin(1)⋅cos(x)

In [10]: linear_eq_to_matrix([sin(x+1)], [sin(x), cos(x)])
```

**Comment by moorepants** [comment] 2022-05-04 11:26
I'm personally a fan of garbage in, garbage out. I'm not sure we need to do all these checks for the user. It's nice if we can cover error checks for all possible inconsistencies, but I don't think we have to. I guess we could have a flag `dont_check_for_garbage=True`.

This is the case we need regularly in the results generated from the mechanics package:

```
linear_eq_to_matrix([Derivative(f(x), x) + f(x)], [Derivative(f(x), x)])
```

```
[1], [-f(x)]
```

**Comment by moorepants** [comment] 2022-05-04 11:29
If a user wants to know if an equation is linear, shouldn't we have a `is_equation_linear()` function? Then, this function could be relieved of checking if it is nonlinear. For my use case, I know the equations I'm working with are linear in certain terms and I only need a function like this to extract A and b. I'm not interested in the check for nonlinearity. So maybe a flag `check_for_nonlinearity=True/False` could be beneficial.

**Comment by oscarbenjamin** [comment] 2022-05-04 11:44
Note that there is also a function specifically designed for linear ODEs:
https://github.com/sympy/sympy/blob/21b3279c10d5fcd08879f8251ec4d04fab4a78dc/sympy/solvers/ode/systems.py#L343-L354

> If a user wants to know if an equation is linear, shouldn't we have a `is_equation_linear()` function?

It's not just about checking linearity but about having well-defined output. If there are no constraints on what can go into the matrices `A` and `b` then you can end up with cases where it isn't clear what the output should be e.g.:
```
In [1]: linear_eq_to_matrix([x*(x+1)], [x])
```
Here we could view the `x+1` as a coefficient or we could view the `x` as a coefficient so the output could be `[x+1], [0]` or it could be `[x], [-x]`. Right now this gives `NonlinearError` so only well defined results are returned.

I think it's fine to change `linear_eq_to_matrix` to handle the cases you are interested in but the expected behaviour should be specified clearly in a way that is generally applicable. The current limitation to symbols avoids needing to think through the corner cases. If we want to lift that limitation then we need to think those through.

**Comment by moorepants** [comment] 2022-05-04 11:50
For `linear_eq_to_matrix([x*(x+1)], [x])` I guess I would assume that the expression would be expanded always and thus return `0` for `A` here.

**Comment by moorepants** [comment] 2022-05-04 11:51
> Note that there is also a function specifically designed for linear ODEs:

Thanks, I didn't know about. I actually haven't used either of these functions. I just has students in class try to use it and they were confused by the results.

**Comment by oscarbenjamin** [comment] 2022-05-04 12:11
The `solve` function has some code to handle this sort of thing but I'm not sure how to define exactly how it works:
https://github.com/sympy/sympy/blob/21b3279c10d5fcd08879f8251ec4d04fab4a78dc/sympy/solvers/solvers.py#L1058-L1088

**Comment by moorepants** [comment] 2022-05-04 13:51
Yes, solve does seem to work for these types of symbols.

**Comment by ThePauliPrinciple** [comment] 2022-05-04 18:17
I don't think `f(x)` and `f'(x)` are non-linear in general. e.g. if `f(x) = e^x` then `f(x) = f'(x)`. SymPy should not make the assumption that this is not the case. Similarly, `f(x) = a*x` would be linear with `x`. This then also means that it could be that `g(x) = b*x` such that `f(x)` and `g(x)` are linearly dependent. I don't feel this is garbage in - garbage out, but rather an incorrect assumption on SymPy's end if this were allowed. 

Perhaps there can be a 'strictly_linear` flag, since clearly it would also be convenient if we could use `Function`s as symbols for the `linear_eq_to_matrix` function.

**Comment by oscarbenjamin** [comment] 2022-05-04 21:11
What would the strictly `linear_flag` do?

The issue is not so much whether things are actually linear or not but how you interpret the output of either `linear_eq_to_matrix` or `linsolve`. Clearly if `linear_eq_to_matrix` returns `A, b` then the basic requirement is that the original system of equations should be equivalent to the matrix equation `A*x = b` where `x` is the matrix of unknowns.

What can we say about solutions to those equations for `x` though? For example if `x` is just a matrix of symbols and `A` and `b` don't contain those symbols then we can say that if `A` is invertible then the original system of equations has a unique solution for `x` given by `A**-1 * b`. If instead `x` is something like `[cos(x), sin(x)]` and `A` and `b` might also contain expressions involving `x` then we can't interpret the properties of the solutions from the matrix in the same way: even if the equations `A**-1 * b = x` are valid they might only implicitly specify the solutions for `x` and they might not even have any actual solutions.

The same thing applies to something like `f(x) - Derivative(f(x), x)` where solving here for `f(x)` gives `Derivative(f(x), x)` but that's really just giving us an ODE for `f(x)` rather than an explicit solution.

Perhaps `linear_eq_to_matrix` should be treated differently here from `linsolve` etc since it is just giving the matrix rather than claiming anything about solutions. It would be useful to have linsolve do this though for the same reasons that you would want to do it with `linear_eq_to_matrix`.

What we want to avoid though is making special cases for `Function`, `Derivative` etc because the list of special cases would never be complete. Perhaps then another way to look at this is to say that `linear_eq_to_matrix` should only need to understand `Add` and `Mul` and should just treat anything else as part of the coefficients or the rhs. I made a more efficient version of `linear_eq_to_matrix` for use in `linsolve` here:
https://github.com/sympy/sympy/blob/086b014b18efce103f61ad3fa38d3421d58d8bc9/sympy/polys/matrices/linsolve.py#L171-L209
The way that works is that it recurses into `Add` and `Mul` but treats everything else as nonlinear. The key part is the final else:
https://github.com/sympy/sympy/blob/086b014b18efce103f61ad3fa38d3421d58d8bc9/sympy/polys/matrices/linsolve.py#L206-L209
That could be changed to unconditionally return what it finds just treating any other expression involving the unknowns as simply being part of the coefficients. The diff is just:
```diff
diff --git a/sympy/polys/matrices/linsolve.py b/sympy/polys/matrices/linsolve.py
index 75ae26d..64b93cb 100644
--- a/sympy/polys/matrices/linsolve.py
+++ b/sympy/polys/matrices/linsolve.py
@@ -203,7 +203,5 @@ def _lin_eq2dict(a, symset):
             return  coeff * terms_coeff, terms
     elif a.is_Equality:
         return _lin_eq2dict(a.lhs - a.rhs, symset)
-    elif not a.has_free(*symset):
-        return a, {}
     else:
-        raise PolyNonlinearError
+        return a, {}
```
Then you can have e.g.:
```python
In [1]: eqs = [f(x).diff(x) - f(x), cos(x) + sin(x) - exp(x), cos(x) - sin(x) + 2*exp(x)]

In [2]: linsolve(eqs, [f(x), cos(x), sin(x)])
Out[2]: 
⎧⎛            x      x⎞⎫
⎪⎜d         -ℯ    3⋅ℯ ⎟⎪
⎨⎜──(f(x)), ────, ────⎟⎬
⎪⎝dx         2     2  ⎠⎪
⎩                      ⎭
```
But you don't get an error for polynomial nonlinearity:
```python
In [1]: linsolve([x**2 - y], [x, y])
---------------------------------------------------------------------------
PolyNonlinearError
```
I guess another special case could be added for `Pow` so only `Add`, `Mul` and `Pow` would be special cases.

The rule then is that any functions of the unknowns are just treated as being independent expressions for the purposes of constructing the matrix. The result from `linsolve` itself just represents a rearrangement of the equations rather than necessarily an explicit solution for the unknowns.

**Comment by smichr** [comment] 2022-05-05 01:31
I am really not a fan of handling all the "not a symbol but treat it like a symbol" objects in functions. The way `solve` works is to disambiguate the system by masking off the non-literal objects that were requested. But this function (and others) could behave like Poly which will make anything(?) a generator, e.g. `Poly(sin(x)-1).is_linear` and `roots` of the same is `{1: 1}` -- user beware: the generator is `sin(x)` and an implicit change of variables is active. It would be nice to have a standard interface to recast an equation set to symbolic form if possible. But that requires a well-defined way to query for all objects that can contain objects as free-structural elements. `g(f(x))` vs `f(x)`, `f(x).diff(x)` vs `x` or `f(x)`, `x**2` or `exp(x + 1)` vs `x` etc...

**Comment by smichr** [comment] 2022-07-09 03:19
git blame gives the commit in which the rationale for not handling non-symbols was given: https://github.com/sympy/sympy/commit/2f0ad7de6fac8beb0836f781453df86d0dbb89c8

```
Note: the requirement that symbols be Symbols
is made to avoid problems like finding the
coefficients of x in `x + f(x)`. `as_coeff_mul(x)`
will treat both terms as x-dependent and will not
return f(x) as a constant and 1 as the coefficient.
```

If one wants to do this without errors reported, the following could be offered directly (or called when a keyword like `raw=True`):
```python
def coeff_mat(eqs, v):
    # garbage-in-garbage out coefficients of items in v as they appear in each expression of eqs
    return [[e.coeff(vi) for vi in v] for e in eqs]

>>> coeff_mat([f(x).diff(x)+f(x)-x, f(f(x))+2*f(x)+y],[f(x),y])
[[1, 0], [2, 1]]
>>> coeff_mat([x*y+2*x,y-x],[x,y])
[[y + 2, x], [-1, 1]]
```
```

**Comment by smichr** [comment] 2022-07-09 16:09
> What can we say about solutions to those equations for `x` though?

The A and b would be in a form that might be appropriate for an iterative solution, wouldn't they? (Jacobi, Gauss-Seidel, etc..)

**Comment by smichr** [comment] 2022-07-15 16:44
> For my use case, I know the equations I'm working with are linear in certain terms and I only need a function like this to extract A and b. I'm not interested in the check for nonlinearity. So maybe a flag `check_for_nonlinearity=True/False` could be beneficial.

Now having worked on this for the past week I offer these observations:

1. the expectation with `linear_coeffs` is that the coefficient will be the coefficient of a symbol that is *linearly* appearing in the expression and the expression need not be expanded in order to give you that coefficient (but it does need to be expanded in order to know if the result is non-zero or not)
2. the expectation of `Expr.coeff` is that the naive coefficient of a symbol will be returned - no recursion to determine it will occur.
3. the modified `linear_coeffs` (and the `linear_eq_to_matrix` which calls it) will soon have the ability to ignore dependent generators/symbols while still detecting cross terms.
4. to tell if an eq is linear in syms, it must pass `linear_coeffs(eq, *syms)` and to know if there are no cross-terms of possibly dependent syms it must pass `linear_coeffs(eq, *syms, strict=False)`. To know whether the system is fully expanded wrt to syms in either case it would be sufficient (I think) to `assert all(eq.coeff(s) == c for s,c in zip(syms, linear_coeffs(eq, *syms, strict=strict_setting)))`

**Comment by oscarbenjamin** [comment] 2023-04-21 10:11
I think that this is fixed now:
```python
In [1]: eqs = [f(t) - g(t), f(t) + g(t)]

In [2]: linear_eq_to_matrix(eqs, [f(t), g(t)])
Out[2]: 
⎛⎡1  -1⎤  ⎡0⎤⎞
⎜⎢     ⎥, ⎢ ⎥⎟
⎝⎣1  1 ⎦  ⎣0⎦⎠
```
The fix was gh-23821 which uses `has_xfree` instead of `free_symbols` or `has`.

**Closed by oscarbenjamin** 2023-04-21 10:11 UTC
Labels: solvers.solveset
