### ISSUE TITLE
Code printer for Sum

### ISSUE THREAD

**Issue by Upabjojr** [sympy/sympy#12313] opened 2017-03-15 05:10 UTC
Verify that Sum (and by extension also Product) can be printed by the code generators (C, Fortran, Julia, etc...).

Verify that Indexed objects are supported and add some tests for them. Like

```Sum(a[i], i)```

to give (for example)

```python
n, m = symbols('n m', integer=True)
A = IndexedBase('A')
x = IndexedBase('x')
y = IndexedBase('y')
i = Idx('i', m)
j = Idx('j', n)
print(ccode(A[i, j]*x[j], j, assign_to=y[i]))
```

The last line gives
```c
for (int i=0; i<m; i++){
   y[i] = 0;
}
for (int i=0; i<m; i++){
   for (int j=0; j<n; j++){
      y[i] = A[n*i + j]*x[j] + y[i];
   }
}
```

If you wrap the expression with a `Sum` object, you get an exception:

```
>>> ccode(Sum(A[i, j]*x[j], j), assign_to=y[i])
NotImplementedError: FIXME: No specialized handling of type <class 'sympy.concrete.summations.Sum'>
```

and so on.

Need to add a `_print_Sum` method either in

https://github.com/sympy/sympy/blob/49b4fa8e40379f4956db0cd2605972b5d8baa8c2/sympy/printing/ccode.py#L107

or in 

https://github.com/sympy/sympy/blob/b3b8bcf648863ebb76ef507fc55cccc0a3c18577/sympy/printing/codeprinter.py#L23

(it's probably the second one, as we need to print `Sum` objects for all code printers).

**Comment by Upabjojr** [comment] 2017-03-15 05:11
```ccode(Sum(a[i], i))```

**Comment by pradeep8093** [comment] 2017-03-15 05:27
@Upabjojr I would like to work on this issue.
Where should I start

**Comment by SatyaPrakashDwibedi** [comment] 2017-03-15 05:29
@Upabjojr I would like to work on this issue.
How should I proceed

**Comment by Upabjojr** [comment] 2017-03-15 12:48
@SatyaPrakashDwibedi the idea is that the _Sum_ should be converted to a _for_-loop. There are some examples in

https://github.com/sympy/sympy/blob/master/sympy/printing/tests/test_ccode.py#L99

They all used `Indexed` objects. I would like `Sum` to be able to generate something similar (even without the presence of `Indexed` objects).

**Comment by Upabjojr** [comment] 2017-03-15 12:51
Warning: needs some manipulation in the code printers.

**Comment by SaiHarsh** [comment] 2017-03-15 16:45
@Upabjojr  Can you explain little more.

**Comment by SatyaPrakashDwibedi** [comment] 2017-03-15 18:03
@Upabjojr 
as you mentioned `Sum(a[i],i)` but Sum in sympy takes two arguments.
Do you want something like
```>>>ccode(Sum(i,(i,0,9)),assign_to=s)
for (i=0;i<9;i++)
{
  s=s+i;
}```

**Comment by Upabjojr** [comment] 2017-03-15 21:17
I believe the last example should be evaluated directly and return s=45.

It should return a for loop when Sum cannot be evaluated (like presence of undefined functions or indexed objects).

There is also an idea to remove the implicit summation for repeated indices in indexed objects. For loops should be generated by Sum objects.

We need to make sure that the unevaluateable summations generate a for loop.

**Comment by SatyaPrakashDwibedi** [comment] 2017-03-16 17:49
@Upabjojr  I'm not getting your idea please show the code which you want to generate.

**Comment by Upabjojr** [comment] 2017-03-16 20:05
Sorry I don't have a computer right now. Cannot really write the code.

https://github.com/sympy/sympy/blob/master/sympy/printing/tests/test_ccode.py

There are examples here generating for loops.

For example

ccode(A[i, j]*x[j], assign_to=y[i])

I want to make sure that something like

ccode(Sum(A[i, j]*x[j], j), assign_to=y[i])

generates the same code.

In the future I'd like to deprecate the previous way and make Sum mandatory (no implicit summation for repeated indices, this has been discussed in the past somewhere).

**Comment by Upabjojr** [comment] 2017-03-19 13:53
@SatyaPrakashDwibedi I updated this issue with an example.

**Comment by SatyaPrakashDwibedi** [comment] 2017-03-19 14:45
@Upabjojr 
```
>>> n, m = symbols('n m', integer=True)
>>> A = IndexedBase('A')
>>> x = IndexedBase('x')
>>> y = IndexedBase('y')
>>> i = Idx('i', m)
>>> j = Idx('j', n)
>>> print(ccode(A[i, j]*x[j], j, assign_to=y[i]))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: ccode() got multiple values for keyword argument 'assign_to'
```
have a look at #12356 is this what you want?

**Comment by Upabjojr** [comment] 2017-03-19 16:41
> have a look at #12356 is this what you want?

It's related but different. Here it's about allowing the explicit summation of indexed objects (that is, mark which indices are summed over).

I'd recommend not to try to fix both issues at the same time (one at a time sounds OK).

**Comment by asmeurer** [comment] 2017-03-22 20:05
Closing this as a dupe of https://github.com/sympy/sympy/issues/10194. Let's continue the discussion over there.

**Closed by asmeurer** 2017-03-22 20:05 UTC
