### ISSUE TITLE
Physics vectors are raising printing errors

### ISSUE THREAD

**Issue by moorepants** [sympy/sympy#13354] opened 2017-09-27 04:33 UTC
In the Jupyter notebook:
```python
import sympy as sm
import sympy.physics.mechanics as me
sm.init_printing()
a, b, c = sm.symbols('a, b, c')
A = me.ReferenceFrame('A')
v = a * A.x + b * A.y + c * A.z
w = b * A.x + c * A.y + a * A.z
w + v
```

gives:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/opt/conda/lib/python3.6/site-packages/IPython/core/formatters.py in __call__(self, obj)
    691                 type_pprinters=self.type_printers,
    692                 deferred_pprinters=self.deferred_printers)
--> 693             printer.pretty(obj)
    694             printer.flush()
    695             return stream.getvalue()

/opt/conda/lib/python3.6/site-packages/IPython/lib/pretty.py in pretty(self, obj)
    363                 if cls in self.type_pprinters:
    364                     # printer registered in self.type_pprinters
--> 365                     return self.type_pprinters[cls](obj, self, cycle)
    366                 else:
    367                     # deferred printer

/opt/conda/lib/python3.6/site-packages/sympy/interactive/printing.py in _print_plain(arg, p, cycle)
     66         """caller for pretty, for use in IPython 0.11"""
     67         if _can_print_latex(arg):
---> 68             p.text(stringify_func(arg))
     69         else:
     70             p.text(IPython.lib.pretty.pretty(arg))

/opt/conda/lib/python3.6/site-packages/sympy/physics/vector/printing.py in vpprint(expr, **settings)
    336 
    337     try:
--> 338         return pp.doprint(expr)
    339     finally:
    340         pretty_use_unicode(uflag)

/opt/conda/lib/python3.6/site-packages/sympy/printing/pretty/pretty.py in doprint(self, expr)
     60 
     61     def doprint(self, expr):
---> 62         return self._print(expr).render(**self._settings)
     63 
     64     # empty op so _print(stringPict) returns the same

/opt/conda/lib/python3.6/site-packages/sympy/physics/vector/vector.py in render(self, *args, **kwargs)
    283                                 pform = vp._print(
    284                                     ar[i][0][j])
--> 285                             pform = prettyForm(*pform.right(" ",
    286                                                 ar[i][1].pretty_vecs[j]))
    287                         else:

AttributeError: 'tuple' object has no attribute 'right'
```

**Comment by tosalonijain** [comment] 2017-11-16 15:40
@moorepants can I work on this issue?

**Comment by moorepants** [comment] 2017-11-16 15:50
Absolutely, I've been having to show a work around in my class and would love to see it fixed.

**Comment by dsavransky** [comment] 2018-05-11 15:18
@moorepants I have a trivial fix for this on my local fork (it was driving me nuts) that I can do a pull for.  However, if @tosalonijain is working on a more extensive fix, I'll hold off.  Please let me know.

Another issue with using the prettyForm.parens() function at all (which is the cause of this bug) is that it brute-force adds simple parentheses, which are then always simple parentheses is TeX mode (instead of \left(... \right)).  Not sure whether anyone has looked into that.

**Comment by Juanlu001** [comment] 2018-05-13 06:46
It's been 6 months, so I for one would love to have such trivial fix...

**Closed** 2018-05-15 22:09 UTC
Labels: physics.mechanics, printing
