### ISSUE TITLE
Wrong result of the sympy.inverse_laplace_transform

### ISSUE THREAD

**Issue by bb1gfd** [sympy/sympy#25352] opened 2023-07-10 23:45 UTC
The attached .txt file is actually .py file with changed extension as .py file cannot be attached here. 
It computes inverse Laplace transform in two ways:
1) immediately applying sympy.inverse_laplace_transform to the ratio of two polynomials. This gives wrong result, adding value of 2 to correct result.
2) manually finding poles and residues of the expression to be transformed, and then applying sympy.inverse_laplace_transform to sum of single pole functions. This approach produces correct result.

[bugInInverseLaplaceTransform.txt](https://github.com/sympy/sympy/files/12009303/bugInInverseLaplaceTransform.txt)

**Comment by oscarbenjamin** [comment] 2023-07-11 00:19
You can just paste the code in with triple backticks like
```
    ```
    f = g()
    ```
```

**Comment by hanspi42** [comment] 2023-07-18 11:59
This is interesting, thanks. I reproduced the behaviour with code like

```python
functions = [
    (3 + exp(-8*t)/2 - 2*exp(-2*t) + exp(-t/2)/2),
    (
     3.0 + 0.588011818675852*exp(-7.75369726666486*t) -
     2.02785302197208*exp(-2.3742367045415*t) +
     0.439841203296232*exp(-0.580521886159003*t))
    ]

for f1 in functions:
    print('\n\n\nChecking:')
    display(f1)
    F1 = (LT(f1)[0]).simplify()
    display(F1)
    n, d = fraction(F1.together())
    F1x = n.expand()/d.expand()
    display(F1x)
    print('Poles F1x:', solve(d, s))
    f2 = ILT(F1x).subs(Heaviside(t), 1)
    display(f2)
    print('Should be zero:', (f2-f1).simplify())
```

which shows me that the problem is only there if the polynomial coefficients are floating-point numbers. Very curious.

I will debug and solve this as soon as #24847 has been reviewed and merged, since that is also about the inverse Laplace transform.

**Comment by oscarbenjamin** [comment] 2023-07-18 12:55
Is this what the issue is:
```python
In [5]: s, t = symbols('s, t')

In [6]: f1 = (3.0 + 0.588011818675852*exp(-7.75369726666486*t) - 2.02785302197208*exp(-2.3742367045415*t)
   ...:  + 0.439841203296232*exp(-0.580521886159003*t))

In [7]: print(f1)
3.0 + 0.588011818675852*exp(-7.75369726666486*t) - 2.02785302197208*exp(-2.3742367045415*t) + 0.439841203296232*exp(-0.580521886159003*t)

In [8]: F1 = laplace_transform(f1, t, s)[0]

In [9]: print(F1)
0.588011818675852/(s + 7.75369726666486) - 2.02785302197208/(s + 2.3742367045415) + 0.439841203296232/(s + 0.580521886159003) + 3.0/s

In [10]: f2 = inverse_laplace_transform(F1, s, t).subs(Heaviside(t), 1)

In [12]: print(f1 - f2)
-0.588011818675852*exp(-7.75369726666486*t) + 0.588011818675852*exp(-7.75369726666486*t)
```
That final expression is essentially zero. Small floating point errors mean that it is not recognised as such. In particular the exponents might look identical but their exact internal representations are unequal:
```python
In [15]: srepr(f1 - f2)
Out[15]: "Add(Mul(Integer(-1), Float('0.58801181867585195', precision=53), exp(Mul(Integer(-1), Float('7.7536972666648607', precision=53), Symbol('t')))), Mul(Float('0.58801181867585195', precision=53), exp(Mul(Integer(-1), Float('7.7536972666648598', precision=53), Symbol('t')))))"

In [16]: for n in sorted((f1 - f2).atoms(Float)): print(srepr(n))
Float('-7.7536972666648607', precision=53)
Float('-7.7536972666648598', precision=53)
Float('-0.58801181867585195', precision=53)
Float('0.58801181867585195', precision=53)
```
The different coefficients in the exp prevent the terms from being collected: otherwise they would cancel to zero.

Since the expression uses floats it is only approximate and approximate simplification can be used:
```python
In [13]: nsimplify(f1 - f2)
Out[13]: 0
```

**Comment by hanspi42** [comment] 2023-07-18 13:14
I wish you were right, but:

```python
functions = [
    (
     3.0 + 0.5*exp(-8.01*t) - 2.0*exp(-2.0*t) + 0.4*exp(-0.6*t)),
    (
     3.0 + 0.5*exp(-8.00*t) - 2.0*exp(-2.0*t) + 0.4*exp(-0.6*t)),
    (
     3.0 + 0.5*exp(-7.99*t) - 2.0*exp(-2.0*t) + 0.4*exp(-0.6*t))
    ]

for f1 in functions:
    print('\n\n\nChecking:')
    F1 = (LT(f1)[0]).simplify()
    n, d = fraction(F1.together())
    F1x = n.expand()/d.expand()
    print('Poles F1x:', solve(d, s))
    f2 = ILT(F1x).subs(Heaviside(t), 1)
    print('Should be zero:', nsimplify(f2-f1))
    print('Should be zero:', (f2-f1).subs(t, 0))
```

results in 

```
Checking:
Poles F1x: [-8.01000000000000, -2.00000000000000, -0.600000000000000, 0.0]
Should be zero: 6 + 333066907387547*exp(-3*t/5)/500000000000000000000000000000
Should be zero: 5.99999999999999



Checking:
Poles F1x: [-8.00000000000000, -2.00000000000000, -0.600000000000000, 0.0]
Should be zero: 7105427357601/8000000000000000000000000000 + 444089209850063*exp(-2*t)/1000000000000000000000000000000 - 133226762955019*exp(-3*t/5)/100000000000000000000000000000
Should be zero: 0



Checking:
Poles F1x: [-7.99000000000000, -2.00000000000000, -0.600000000000000, 0.0]
Should be zero: 6
Should be zero: 6.00000000000001
```

**Comment by hanspi42** [comment] 2023-07-18 13:18
Ah yes, and

```    (
     3 + 5*exp(-799*t/100)/10 - 2*exp(-2*t) + 4*exp(-6*t/10)/10)
```

results in

```
Checking:
Poles F1x: [-799/100, -2, -3/5, 0]
Should be zero: 0
Should be zero: 0
```

**Comment by oscarbenjamin** [comment] 2023-07-18 14:48
Okay, I see:
```python
In [40]: s, t = symbols('s, t')

In [41]: F1 = (1.9*s**3 + 19.886*s**2 + 63.326*s + 28.764)/(s**4 + 10.59*s**3 + 21.974*s**2 + 9.588*s)

In [42]: F1
Out[42]: 
     3           2                    
1.9⋅s  + 19.886⋅s  + 63.326⋅s + 28.764
──────────────────────────────────────
  4          3           2            
 s  + 10.59⋅s  + 21.974⋅s  + 9.588⋅s  

In [43]: inverse_laplace_transform(F1, s, t).subs(Heaviside(t), 1)
Out[43]: 
                         -7.99⋅t        -2.0⋅t        -0.6⋅t
9.0 + 0.500000000000008⋅ℯ        - 2.0⋅ℯ       + 0.4⋅ℯ      

In [44]: inverse_laplace_transform(nsimplify(F1), s, t).subs(Heaviside(t), 1)
Out[44]: 
                 -3⋅t     -799⋅t 
                 ─────    ───────
                   5        100  
       -2⋅t   2⋅ℯ        ℯ       
3 - 2⋅ℯ     + ──────── + ────────
                 5          2 
```
The difference is `9.0` vs `3`.

The float case is a lot slower than the rational case which suggests that a different code path might be taken. Probably there is a bug in that code path.

The reason for taking a different code path is most likely that floats and polynomials often don't play nicely e.g.:
```python
In [49]: nsimplify(F1).factor()
Out[49]: 
     3         2                  
950⋅s  + 9943⋅s  + 31663⋅s + 14382
──────────────────────────────────
s⋅(s + 2)⋅(5⋅s + 3)⋅(100⋅s + 799) 

In [50]: F1.factor()
Out[50]: 
                 ⎛                    3                      2                            ⎞
2.88186038044962⋅⎝0.0300034740864732⋅s  + 0.314025834570319⋅s  + 1.0⋅s + 0.454221015064902⎠
───────────────────────────────────────────────────────────────────────────────────────────
          ⎛                    3                      2                            ⎞       
        s⋅⎝0.0455083280240284⋅s  + 0.481933193774461⋅s  + 1.0⋅s + 0.436333849094384⎠  
```
I think we discussed elsewhere that perhaps `factor` over `RR` or `CC` should compute approximate roots numerically rather than using typical factorisation algorithms. Alternatively perhaps it should use nsimplify instead of QQ when preparing for `factor`:
```python
In [66]: mapping1 = {n: Rational(n) for n in F1.atoms(Float)}

In [67]: mapping2 = {n: nsimplify(n) for n in F1.atoms(Float)}

In [68]: print(mapping1)
{10.5900000000000: 2980820003365847/281474976710656, 63.3260000000000: 8912342187589501/140737488355328, 1.90000000000000: 4278419646001971/2251799813685248, 9.58800000000000: 5397564153403539/562949953421312, 19.8860000000000: 5597411386868105/281474976710656, 28.7640000000000: 8096346230105309/281474976710656, 21.9740000000000: 6185131138239955/281474976710656}

In [69]: print(mapping2)
{10.5900000000000: 1059/100, 63.3260000000000: 31663/500, 1.90000000000000: 19/10, 9.58800000000000: 2397/250, 19.8860000000000: 9943/500, 28.7640000000000: 7191/250, 21.9740000000000: 10987/500}

In [70]: print(F1.subs(mapping1).factor())
(4278419646001971*s**3 + 44779291094944840*s**2 + 142597475001432016*s + 64770769840842472)/(4*s*(562949953421312*s**3 + 5961640006731694*s**2 + 12370262276479910*s + 5397564153403539))

In [71]: print(F1.subs(mapping2).factor())
(950*s**3 + 9943*s**2 + 31663*s + 14382)/(s*(s + 2)*(5*s + 3)*(100*s + 799))
```
Computing approximate roots instead gives:
```python
In [84]: n, d = F1.as_numer_denom()

In [85]: print(n)
1.9*s**3 + 19.886*s**2 + 63.326*s + 28.764

In [86]: print(d)
s**4 + 10.59*s**3 + 21.974*s**2 + 9.588*s

In [87]: nr = LC(n)*prod((s - r)**i for r, i in roots(n).items())

In [88]: nd = LC(d)*prod((s - r)**i for r, i in roots(d).items())

In [89]: print(nr)
1.9*(s + 0.541553082257882)*(s + 4.9623813536079 - 1.824680561305*I)*(s + 4.9623813536079 + 1.824680561305*I)

In [90]: print(nd)
1.0*s*(s + 0.6)*(s + 2.0)*(s + 7.99)

In [91]: inverse_laplace_transform(nr/nd, s, t).subs(Heaviside(t), 1)
Out[91]: 
                                      -7.99⋅t        -2.0⋅t        -0.6⋅t
9.00000000000001 + 0.500000000000007⋅ℯ        - 2.0⋅ℯ       + 0.4⋅ℯ 
```
For factorisation over RR we would want to combine the complex conjugate root pairs so it is a little more involved than what I showed above.

The factorisation is better but ILT is still wrong. My guess is that something expands the denominator again.

I note that `apart` fails even with a factorised denominator:
```python
In [92]: apart(nr/nd)
Out[92]: 
                     ⎛                    2                            ⎞        
   0.540820970237553⋅⎝0.0925614271289128⋅s  + 1.0⋅s + 0.218444968024234⎠     3.0
- ──────────────────────────────────────────────────────────────────────── + ───
                      3                      2                                s 
  0.0455083280240284⋅s  + 0.481933193774461⋅s  + 1.0⋅s + 0.436333849094384      

In [93]: nr/nd
Out[93]: 
1.9⋅(s + 0.541553082257882)⋅(s + 4.9623813536079 - 1.824680561305⋅ⅈ)⋅(s + 4.9623813536079 + 1.824680561
───────────────────────────────────────────────────────────────────────────────────────────────────────
                                       s⋅(s + 0.6)⋅(s + 2.0)⋅(s + 7.99)                                

305⋅ⅈ)
──────
     
```
That is because `apart` will begin by expanding everything in the conversion to `Poly` and once it is expanded it can no longer be factorised.

**Comment by hanspi42** [comment] 2023-07-18 17:27
> The float case is a lot slower than the rational case which suggests that a different code path might be taken. Probably there is a bug in that code path.

Yes, this must be the case. I'll be travelling for three weeks now, and then I will look at it in depth. I have already know that this example does not integrate, so the bug is one I have placed myself ;)

**Comment by hanspi42** [comment] 2023-07-18 17:29
However, as I said, I'd very much prefer to conclude #24847 first.

**Comment by oscarbenjamin** [comment] 2023-07-18 19:07
> However, as I said, I'd very much prefer to conclude #24847 first.

To be clear I have been meaning to review this and it is still on my todo list but I just haven't got time right now.

**Comment by hanspi42** [comment] 2023-07-18 19:18
Thanks! Don't hurry. I'm not in a hurry either, I won't be able to continue working on this anyway before Mid August.

**Comment by oscarbenjamin** [comment] 2023-07-18 21:33
I doubt that I will find time before mid August.

**Closed** 2023-09-07 09:01 UTC
Labels: integrals.transforms
