### ISSUE TITLE
Fourier transform not returning DiracDelta

### ISSUE THREAD

**Issue by tedtss** [sympy/sympy#10299] opened 2015-12-22 00:59 UTC
Fourier transform is returning 0 intead of a DiracDelta. As a simple example, fourier_transform(1, x, y) returns zero, not DiracDelta(0).

**Comment by jksuom** [comment] 2015-12-22 08:37
This is a well known issue. SymPy's integrator (used for transforms) can not currently handle generalized functions such as Dirac delta.

**Comment by asmeurer** [comment] 2017-11-02 04:27
Duplicate of

**Closed by asmeurer** 2017-11-02 04:27 UTC
