### ISSUE TITLE
Recursion solver fails

### ISSUE THREAD

**Issue by vassbu** [sympy/sympy#11260] opened 2016-06-20 11:03 UTC
The solution to the following recursion equation is wrong,
>>>tja = rsolve(y(n)-y(n-1)-2*y(n-2)-2*n, y(n), {y(0):-1, y(1):1})
>>> tja
-3*(-1)**n/5 + 2*2**n - 6*n/5 - 12/5

Correct solution:  2**(n+1) - (-1)**n/2 - n - 5/2

**Comment by Sumith1896** [comment] 2016-06-22 10:12
Duplicate of https://github.com/sympy/sympy/issues/11261
Needs to be closed

**Closed** 2016-06-22 10:59 UTC
