### ISSUE TITLE
Trouble with lambdify Piecewise

### ISSUE THREAD

**Issue by cholmcc** [sympy/sympy#19441] opened 2020-05-27 09:22 UTC
Hi, 

There seems to be a problem with how `Piecewise` is `lambdify`'d.  As an example we integrate 

    f(x) = sin(a x)+cos(b x)

over 0 to 2pi, which evaluates to 

    sin(2 pi b) / b - cos(2 pi a) / a + 1 / a   for a != 0 and b != 0 
    2 pi            - cos(2 pi a) / a + 1 / a   for a != 0 
    sin(2 pi b) / b                             for b != 0 
    2 pi                                        otherwise 
 
The code 

```python
a, b, x = symbols('a b x',real=True)
f = sin(a * x) + cos(b * x)
F = f.integrate((x, 0, 2 * pi))
print(F)
    
N = lambdify((a,b),F)
print('Trying to evaluate integral numerically for a=0, b=1')
N(0,1)
```

executed in the `isympy` shell yields 

```python
Piecewise((sin(2*pi*b)/b - cos(2*pi*a)/a + 1/a, Ne(a, 0) & Ne(b, 0)), (2*pi - cos(2*pi*a)/a + 1/a, Ne(a, 0)), (sin(2*pi*b)/b, Ne(b, 0)), (2*pi, True))
Trying to evaluate integral numerically for a=0, b=1
<lambdifygenerated-1>:2: RuntimeWarning: divide by zero encountered in double_scalars
  return (select([logical_and.reduce((not_equal(a, 0),not_equal(b, 0))),not_equal(a, 0),not_equal(b, 0),True], [sin(2*pi*b)/b - cos(2*pi*a)/a + a**(-1.0),2*pi - cos(2*pi*a)/a + a**(-1.0),sin(2*pi*b)/b,2*pi], default=nan))
---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
<ipython-input-4-9d66225ea059> in <module>
      7 N = lambdify((a,b),F)
      8 print('Trying to evaluate integral numerically for a=0, b=1')
----> 9 N(0,1)
     10 
    
<lambdifygenerated-1> in _lambdifygenerated(a, b)
      1 def _lambdifygenerated(a, b):
----> 2     return (select([logical_and.reduce((not_equal(a, 0),not_equal(b, 0))),not_equal(a, 0),not_equal(b, 0),True], [sin(2*pi*b)/b - cos(2*pi*a)/a + a**(-1.0),2*pi - cos(2*pi*a)/a + a**(-1.0),sin(2*pi*b)/b,2*pi], default=nan))
```

The trouble lies in the generated code for `N` - in particular the use of `numpy.select`.  Although not clear, from the [documentation](https://numpy.org/doc/stable/reference/generated/numpy.select.html) of that function, all arguments are actually evaluated _irrespective_ of the truth values of the conditions.  That is, in the generated code 

```python
from numpy import select, logical_and, not_equal, sin, cos, pi, nan
a, b = 1, 0 

select([logical_and.reduce((not_equal(a, 0),not_equal(b, 0))),
        not_equal(a, 0),
        not_equal(b, 0),
        True],
       [sin(2*pi*b)/b - cos(2*pi*a)/a + a**(-1.0),
        2*pi - cos(2*pi*a)/a + a**(-1.0),
        sin(2*pi*b)/b,
        2*pi],
       default=nan)
```

_all_ of the expression are evaluated _including_ 

```python
sin(2*pi*b)/b - cos(2*pi*a)/a + a**(-1.0)
2*pi - cos(2*pi*a)/a + a**(-1.0)
```

which _both_ results in the `ZeroDivisionError` being raised.  The solution seems to be _deferred_ evaluation of the choice list elements via e.g., `lambda`s 

```python
select([logical_and.reduce((not_equal(a, 0),not_equal(b, 0))),
        not_equal(a, 0),
        not_equal(b, 0),
       True],
       [lambda: sin(2*pi*b)/b - cos(2*pi*a)/a + a**(-1.0),
        lambda: 2*pi - cos(2*pi*a)/a + a**(-1.0),
        lambda: sin(2*pi*b)/b,
        lambda: 2*pi],
      default=lambda:nan).item()()
```

The code that generates the `lambdify`'d function seems to be [here](https://github.com/sympy/sympy/blob/b92b971eb4712e9ccfbdae993c42b3563ce8f86d/sympy/printing/pycode.py#L716)

```python
    def _print_Piecewise(self, expr):
        "Piecewise function printer"
        exprs = '[{0}]'.format(','.join(self._print(arg.expr) for arg in expr.args))
        conds = '[{0}]'.format(','.join(self._print(arg.cond) for arg in expr.args))
        # If [default_value, True] is a (expr, cond) sequence in a Piecewise object
        #     it will behave the same as passing the 'default' kwarg to select()
        #     *as long as* it is the last element in expr.args.
        # If this is not the case, it may be triggered prematurely.
        return '{0}({1}, {2}, default={3})'.format(
            self._module_format('numpy.select'), conds, exprs,
            self._print(S.NaN))
```

which could be 

```python
    def _print_Piecewise(self, expr):
        "Piecewise function printer"
        exprs = '[{0}]'.format(','.join(self._print(arg.expr) for arg in expr.args))
        conds = '[{0}]'.format(','.join('lambda:'+self._print(arg.cond) for arg in expr.args))
        # If [default_value, True] is a (expr, cond) sequence in a Piecewise object
        #     it will behave the same as passing the 'default' kwarg to select()
        #     *as long as* it is the last element in expr.args.
        # If this is not the case, it may be triggered prematurely.
        return '{0}({1}, {2}, default={3}).item()()'.format(
            self._module_format('numpy.select'), conds, exprs,
            'lambda:'+self._print(S.NaN))
``` 

(not tested). How this works for vector arguments is not addressed but should be. 

Kudos to a student of mine to find this bug. 

Yours, 

Christian

**Comment by cholmcc** [comment] 2020-05-27 22:29
Hmm, the above suggestion won't work for array inputs.  Working from the code generated from the above example 

```python
def N(a,b):
    from numpy import select, logical_and, not_equal, sin, cos, nan, pi
    return (select([logical_and.reduce((not_equal(a, 0), 
                                        not_equal(b, 0))), 
                    not_equal(a, 0), 
                    not_equal(b, 0), 
                    True],  
                   [sin(2*pi*b)/b - cos(2*pi*a)/a + a**(-1.0), 
                    2*pi - cos(2*pi*a)/a + a**(-1.0), 
                    sin(2*pi*b)/b, 
                    2*pi],  
                   default=nan))
```
the most straight forward way to get it to work with arrays is 

```python
def N(a,b): 
    from numpy import select, logical_and, not_equal, sin, cos, nan, pi, ndim, array, diagonal
    r = (select([logical_and.reduce((not_equal(a, 0), 
                                     not_equal(b, 0))), 
                 not_equal(a, 0), 
                 not_equal(b, 0), 
                 True],  
                [lambda: sin(2*pi*b)/b - cos(2*pi*a)/a + a**(-1.0), 
                 lambda: 2*pi - cos(2*pi*a)/a + a**(-1.0), 
                 lambda: sin(2*pi*b)/b, 
                 lambda: 2*pi],  
                default=lambda:nan))
    return r.item()() if ndim(r) == 0 else diagonal(array([rr() for rr in r]))
``` 
However, that will still result in various exceptions being raised because we still evaluate for invalid arguments (e.g., `a=0`).   To fix that, we can do 

```python 
def NNN(a,b): 
    from numpy import select, logical_and, not_equal, sin, cos, nan, pi, ndim, array, diagonal
    r = (select([logical_and.reduce((not_equal(a, 0), 
                                     not_equal(b, 0))), 
                 not_equal(a, 0), 
                 not_equal(b, 0), 
                 True],  
                [lambda a,b: sin(2*pi*b)/b - cos(2*pi*a)/a + a**(-1.0), 
                 lambda a,b: 2*pi - cos(2*pi*a)/a + a**(-1.0), 
                 lambda a,b: sin(2*pi*b)/b, 
                 lambda a,b: 2*pi],  
                default=lambda a,b:nan))
    return r.item()() if ndim(r) == 0 else array([rr(aa,bb)
                                                  for rr,aa,bb in zip(r,a,b)])
```
which unfortunately assumes that arguments `a` and `b` are of equal shape.  However, that is already implicitly assumed in 

```python
logical_and.reduce((not_equal(a, 0), not_equal(b, 0)))
```
since that will only work for if `a` and `b` can be broadcast together.  So, perhaps the solution is to generate code like the above.  That would however drastically change how `_print_Piecewise` should be coded since we then need to know the arguments to evaluate on in the generated function.  Perhaps a simpler solution is to do explicit loops and `if` like in the plain Python printer.

Just my 2¢

**Comment by asmeurer** [comment] 2022-04-15 08:29
Hadn't seen this issue before. It's basically a duplicate of https://github.com/sympy/sympy/issues/15014. If you have any suggestions for a fix please comment them over there.

**Closed by asmeurer** 2022-04-15 08:29 UTC
Labels: utilities.lambdify
