### ISSUE TITLE
10**1000000 takes a long time to evaluate

### ISSUE THREAD

**Issue by jrmuizel** [sympy/sympy#19562] opened 2020-06-15 21:02 UTC
I did not wait for it to finish.

STR:
```
(SymPyConsole)
>>> 10**1000000
```

For comparison: `10^1000000` evaluates very quickly on Wolfram Cloud

**Comment by oscarbenjamin** [comment] 2020-06-15 21:15
There is no sympy involved in that operation. You are typing Python code and so `int**int` evaluate to an `int`. In this case it's a very large int taking ~0.5MB of memory.

For me the operation completes in 0.5 seconds if I don't print it:
```
In [5]: %time x = 10**1000000                                                                                                                  
CPU times: user 496 ms, sys: 3.22 ms, total: 499 ms
Wall time: 509 ms
```
Attempting to print the result is slower due to converting from binary to decimal:
```
In [6]: %time _=str(x)                                                                                                                         
CPU times: user 26.1 s, sys: 136 ms, total: 26.2 s
Wall time: 26.7 s
```

**Comment by oscarbenjamin** [comment] 2020-06-15 21:33
Which environment did you run that command in?

**Comment by jrmuizel** [comment] 2020-06-15 22:21
I was just running it in `isympy`. Does sympy have a way to represent the 10**1000000 symbolically instead of expanding it?

**Comment by oscarbenjamin** [comment] 2020-06-15 22:32
In isympy it is very slow to print this result. It seems that the pretty printer is slow for this.

Yes, there is a way to represent the result symbolically but you might find that various operations will cause it to evaluate:
```julia
In [1]: Pow(10, 10**6, evaluate=False)                                                                                                                        
Out[1]: 
  1000000
10
```

**Comment by asmeurer** [comment] 2020-06-16 00:16
This is a duplicate of https://github.com/sympy/sympy/issues/6835. Currently to represent arithmetical expressions that result in very large numbers, you need to create the expressions manually with evaluate=False. Even if that issue were fixed, there would be no way for SymPy to bypass things like `10**1000000` because Python evaluates numbers automatically (see https://docs.sympy.org/latest/tutorial/gotchas.html#two-final-notes-and). So you would have to do something like `sympify("10**1000000", evaluate=False)`.

**Closed by asmeurer** 2020-06-16 00:16 UTC

**Comment by oscarbenjamin** [comment] 2020-06-16 00:57
There is also the issue that pretty printing is very slow in this case. This example only takes 0.5 seconds to evaluate in my computer and 25 seconds with str but a longer (not sure how long) time to print in isympy because the code for checking for combining characters in the pretty printer is slow.
