### ISSUE TITLE
series expansion of 1/x ignores order parameter

### ISSUE THREAD

**Issue by rwst** [sympy/sympy#8804] opened 2015-01-11 17:29 UTC
This should yield `1/x+O(x^8)`:

```
In [4]: series(1/x, n=8)
Out[4]: 
1
─
x
```

**Comment by skirpichev** [comment] 2015-01-11 17:51
That's not a bug, maybe documentation issue.

**Comment by sachin-4099** [comment] 2020-06-01 15:14
I believe this a bug of `Pow._eval_nseries()`.

**Comment by gschintgen** [comment] 2020-06-01 15:48
> 
> 
> I believe this a bug of `Pow._eval_nseries()`.

Why would this be a bug? The order term represents the error of approximating a function by its series. Here the error is identically zero, so adding the `O(x**8)` would only render the result less precise. Why not properly document the current behavior? (Which for me is the expected behavior.)

**Comment by sachin-4099** [comment] 2020-06-01 16:16
You are absolutely correct on your part, but see, for a testcase like this:
```
In [3]: y=sin(x)**5

In [4]: y._eval_nseries(x,10,None)
Out[4]:
        7       9        11        13
 5   5*x    23*x    227*x     631*x      / 14\
x  - ---- + ----- - ------- + ------- + O\x  /
      6       72      3024     51840
```
The above was the output on the current master.

Expected:
```
         7       9     
 5   5*x    23*x      / 10\
x  - ---- + ----- +  O\x  /
      6       72      
```

This error is due to the fact that `Pow._eval_nseries()` is not written correctly.

So, basically when we would have corrected these things, the output of the expression in the issue will have the `O(x**8)` term. That's why, I think this is a `Pow._eval_nseries()` bug.

**Comment by gschintgen** [comment] 2020-06-01 16:37
> 
> 
> You are absolutely correct on your part, but see, for a testcase like this:
> 
> ```
> In [3]: y=sin(x)**5
> 
> In [4]: y._eval_nseries(x,10,None)
> Out[4]:
>         7       9        11        13
>  5   5*x    23*x    227*x     631*x      / 14\
> x  - ---- + ----- - ------- + ------- + O\x  /
>       6       72      3024     51840
> ```
> 
> The above is the output on the current master.

I see, that's unexpected and should be fixed. But it's unrelated to this issue insofar as `sin` is neither polynomial nor rational so that its series expansion can't be equal to the function itself.

> 
> Expected:
> 
> ```
>          7       9     
>  5   5*x    23*x      / 10\
> x  - ---- + ----- +  O\x  /
>       6       72      
> ```

I'd rather have expected `O(x**11)`! (Which itself is also of order `O(x**10)` so the user input is scrupulously respected and the answer is as precise as possible. That's how it should be, IMO.) I do admit though that I'm not that familiar with the series code, so this is just my point of view as a user. And these are just technicalities.

While we're at it, the `series` docstring is also suboptimal: it states that `n` is `The number of terms upto which the series is to be expanded`, but that is only true if all terms actually have a non-zero coefficient. For functions like `sin`, `cos` where there are "missing" terms, `n` seems to specify the order of the expansion and not the number of terms in the output. That's incoherent and should also be amended.

**Comment by sachin-4099** [comment] 2020-06-01 16:58
On the current master:
```
In [42]: y=(x+a)**7

In [43]: y._eval_nseries(x,5,None)
Out[43]:
 7      6         5  2       4  3       3  4       2  5        6    7
a  + 7*a *x + 21*a *x  + 35*a *x  + 35*a *x  + 21*a *x  + 7*a*x  + x
```
Expected: 
```
 7      6         5  2       4  3       3  4       
a  + 7*a *x + 21*a *x  + 35*a *x  + 35*a *x + O(x**5)
```

I think this is a good polynomial example to describe the situation.

> While we're at it, the series docstring is also suboptimal: it states that n is The number of terms upto which the series is to be expanded, but that is only true if all terms actually have a non-zero coefficient. For functions like sin, cos where there are "missing" terms, n seems to specify the order of the expansion and not the number of terms in the output. That's incoherent and should also be amended.

Yeah, I totally agree with you, it should be amended.

**Comment by anutosh491** [comment] 2022-01-11 03:42
Well the above arguments have been addressed as to what I can see on master and `_eval_nseries()` method in `power.py` but still 
we don't add the order term for expansion of polynomials like `1/x`

**Closed** 2022-05-04 22:27 UTC
Labels: Documentation, series
