### ISSUE TITLE
On expression "1/x", evalf(subs={'x':0}) evaluates to 0 (zero) instead of some infinite or undeterminate

### ISSUE THREAD

**Issue by alf63** [sympy/sympy#24919] opened 2023-03-16 08:50 UTC
Hello,

I am new to SymPy, so maybe used it incorrectly -- please tell me if this is the case.
(I am interested in any workaround that could help me make the example work).

Here is a minimalist program that demonstrates the problem :

```
#!/usr/bin/env python3
from sympy.parsing.sympy_parser import parse_expr
formula_sympy = parse_expr("1/x")
result = formula_sympy.evalf(subs={'x':0})
print("result =", result)
```

As a division by zero, it should return some kind of infinite (or undeterminate).
But it returns zero.

Problem reproduced with sympy-1.11.1 on several version of Python, including python 3.10.6, 3.8.10, and 3.7.4.

Strangely **not** reproductible on [https://live.sympy.org/](https://live.sympy.org/) (returns a seemingly correct answer, **zoo**).

Please note that formula_sympy = parse_expr("1/**0**") returns a seemingly correct answer, **zoo**.

Thanks for investigating

**Comment by oscarbenjamin** [comment] 2023-03-16 11:00
I can't reproduce this with 1.11.1 or master:
```python
In [1]: from sympy.parsing.sympy_parser import parse_expr
   ...: formula_sympy = parse_expr("1/x")
   ...: result = formula_sympy.evalf(subs={'x':0})
   ...: print("result =", result)
result = zoo
```

**Comment by AtriChatterjee1** [comment] 2023-03-16 13:53
The limit 1/x as x tends to zero does not exist, for LHL, 1/x tends to -oo and for RHL 1/x tends to oo. So it returns zoo, as it is an oscillating limit. More about this you can read in this [thread ](https://github.com/sympy/sympy/issues/5195)

**Comment by hanspi42** [comment] 2023-03-16 19:03
> Problem reproduced with sympy-1.11.1 on several version of Python, including python 3.10.6, 3.8.10, and 3.7.4.

Could you add

```
import sympy
print(sympy.__version__)
```

to your program to make sure you are using the sympy version you think you are using?

**Comment by oscarbenjamin** [comment] 2023-03-17 11:39
I'm going to close this for now because it seems to work fine as far as I can tell. We can always reopen if this is confirmed and with more information to reproduce.

**Closed by oscarbenjamin** 2023-03-17 11:39 UTC
