### ISSUE TITLE
integral of 1/cos(x)**2 is wrong

### ISSUE THREAD

**Issue by sn6uv** [sympy/sympy#11079] opened 2016-05-05 19:19 UTC
The definite integral
`integrate(1 / cos(x)**2, (x, 0, 2 * pi))`
returns 0 when it should be infinite.

The indefinite integral is correct `sin(x) / cos(x)`. My guess is that the limits are being blindly substituted while ignoring the discontinuities of tan(x).

`sympy.__version__ == '1.0'`

**Comment by asmeurer** [comment] 2016-05-05 19:27
Yep, this is a known issue. Even `integrate(1/x**2, (x, -1, 1))` is wrong. This likely should be closed as a duplicate of https://github.com/sympy/sympy/issues/4215.

Now that SymPy has a `singularities` function, we should integrate it into `integrate`. However, currently it only works with rational functions. 

Beyond this, I don't know if there's a better way to avoid these issues.

**Closed** 2016-05-05 19:28 UTC
Labels: duplicate
