### ISSUE TITLE
SymPy unable to solve super simple equation directly

### ISSUE THREAD

**Issue by Inmortak** [sympy/sympy#25978] opened 2023-12-11 17:31 UTC
Hello guys! Here, reporting some [undesirable] behavior from SymPy

I have the following expression: 

$$
-\alpha*n/\beta + \sum{x(i)/\beta^2} = 0
$$

And I want to solve for $\beta$, which clearly is both inside and outside the sum. SymPy is solving only for the $\beta$ outside the sum, ignoring the one inside and, consequently, gives the incorrect answer:

$$
\beta  =  \frac{\alpha n}{\sum_{i=1} \frac{x{\left(i \right)}}{\beta^{2}}}
$$

I am getting this error when using _sympy.solve(expression, param)_ where param is the variable associated to $\beta$ and expression holds the left hand side of the initial equation.

 Here is the actual code, the error occurs in the last 3 lines:
```
import sympy as sy
x, y, y_i, a, b, L, al, be, ga, Ga, la, th, sigma,  = sy.symbols('x y y_i a b L alpha beta gamma Gamma lambda theta sigma', real=True)
n = sy.symbols('n', integer=True, positive=True)
i = sy.symbols('i', integer=True, positive=True)
j = sy.symbols('j', integer=True, positive=True)

Gam = sy.Function('Gamma')(al)
f = x**(al-1)*sy.exp((-x)/be)/(be**al * Gam)
param = be
var = x
var_func = sy.Function(var.name)(i)
f = f.subs(var, var_func)
L_exp = sy.Product(f,(i, 1,n))

log_L = sy.log(L_exp)
log_L = sy.expand_log(log_L, force=True)

d_log_L = sy.Derivative(log_L, param, evaluate=True)
d_log_L = d_log_L.expand()
d_log_L = d_log_L.doit()

param_exp = sy.solve(d_log_L, param)

param_exp[0]
```

Thank you all!

**Comment by gschintgen** [comment] 2023-12-11 17:42
You might want to post your actual (copy&pastable) code. That's always good practice.

**Comment by PascalGitz** [comment] 2023-12-11 21:03
`sy.solve(d_log_L.simplify(), param)[0]`

results in 

$$\frac{\sum_{i=1}^{n} x{\left(i \right)}}{\alpha n}$$

**Comment by Inmortak** [comment] 2023-12-11 21:41
> `sy.solve(d_log_L.simplify(), param)[0]`
> 
> results in
> 
> ∑i=1nx(i)αn

Thank you, I also managed to get the right answer by doing some further manipulation. Still, that is exactly part of the problem: __solve__ should be able to do this right from the start. Otherwise, how can I know when further manipulation is needed?

**Comment by oscarbenjamin** [comment] 2023-12-11 22:30
The Sum is masked off with a dummy symbol here:
https://github.com/sympy/sympy/blob/1051690df26b46431235939931fcffb628279451/sympy/solvers/solvers.py#L1084-L1114
Maybe that should be changed but it is intentional because it means that you can do things like:
```python
In [2]: eq = f(x)**2 - f(x).diff(x)**2

In [3]: eq
Out[3]: 
                  2
 2      ⎛d       ⎞ 
f (x) - ⎜──(f(x))⎟ 
        ⎝dx      ⎠ 

In [4]: solve(eq, f(x), dict=True)
Out[4]: 
⎡⎧       d       ⎫  ⎧      d       ⎫⎤
⎢⎨f(x): -──(f(x))⎬, ⎨f(x): ──(f(x))⎬⎥
⎣⎩       dx      ⎭  ⎩      dx      ⎭⎦
```
If you wanted to solve the differential equation then you should use `dsolve`:
```python
In [18]: dsolve(eq, f(x))
Out[18]: 
⎡           x             -x⎤
⎣f(x) = C₁⋅ℯ , f(x) = C₁⋅ℯ  ⎦
```
The intention of solve is to solve algebraic equations rather than to evaluate things like summations, integrals, derivatives etc.

Possibly the `implicit` flag should prevent this or the checking should be better.

**Comment by Inmortak** [comment] 2023-12-11 22:46
Great answers, thank you all. 

One additional thing, that may be desirable, is to have methods to explicitly pull/push constants in/out to/of sums.

**Comment by smichr** [comment] 2023-12-11 22:54
duplicate of #15865

**Closed** 2023-12-11 22:54 UTC
Labels: solvers.solve
