### ISSUE TITLE
Integrate freezes

### ISSUE THREAD

**Issue by simamura87** [sympy/sympy#8970] opened 2015-02-08 13:08 UTC
Integrate freezes on integral (b-a*x^2)*sqrt(4*x^2+1) dx

**Comment by darshanime** [comment] 2015-02-10 17:52
I am not able to reproduce the freeze. 

```python
>>> integrate((b-a*x**2)*sqrt(4*x**2+1),x)
-a*x**5/sqrt(4*x**2 + 1) - 3*a*x**3/(8*sqrt(4*x**2 + 1)) - a*x/(32*sqrt(4*x**2 + 1)) + a*asinh(2*x)/64 + b*x*sqrt(4*x**2 + 1)/2 + b*asinh(2*x)/4
```
Try again maybe ?

**Comment by simamura87** [comment] 2015-02-10 18:10
It is on live.sympy.org

**Comment by pelegm** [comment] 2015-02-11 19:18
`live.sympy.org` doesn't always hold the newest version. If this is not a bug in master, I suggest to close this issue.

**Closed** 2015-02-12 23:16 UTC
