### ISSUE TITLE
limit value calculation limit((-1)**n*1/n,n,oo) does not seem to work

### ISSUE THREAD

**Issue by joergbalzer** [sympy/sympy#21363] opened 2021-04-21 12:21 UTC
In version 1.8 (and also 1.5.1) the limit value calculation limit((-1)**n*1/n,n,oo)
does not seem to work.

![grafik](https://user-images.githubusercontent.com/82948526/115552621-cf3eb500-a2ac-11eb-891f-fcc6a30a7607.png)

![grafik](https://user-images.githubusercontent.com/82948526/115552484-adddc900-a2ac-11eb-859d-496397852dc9.png)

**Comment by 0sidharth** [comment] 2021-04-21 14:00
Duplicate of #19823

**Closed** 2021-05-19 22:38 UTC
