### ISSUE TITLE
TypeError in evalf

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#19623] opened 2020-06-23 08:49 UTC
```
a=log(1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000/Integer(44589945167844524634267255070920293323559080906299000117979030887504947174045222662602817919518108792210124719977899913547365769171988444516003084243514534243843066470538798646640748073849662493526145083047722649))/log(Integer(10)/13)
a.evalf(chop=True)
```
gives `TypeError: 'NoneType' object is not iterable`. Without `chop=True` works fine.

**Comment by gschintgen** [comment] 2020-06-23 10:58
duplicate of #18516?

**Closed** 2021-03-13 23:59 UTC
Labels: core.evalf
