### ISSUE TITLE
crash in parser with sympify called from Sage

### ISSUE THREAD

**Issue by rwst** [sympy/sympy#10795] opened 2016-03-11 16:14 UTC
This is FYI, as it happens with input in Sage and I haven't found a Sympy-only trigger, but if you have any idea?

```
sage: import sympy      
sage: u = sympy.Function('u'); n = sympy.Symbol('n', integer=True)      
sage: sympy.sympify(3*u(n))      
3*u(n)
sage: sympy.sympify(3*u(n), evaluate=False)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-20ad7c52b198> in <module>()
----> 1 sympy.sympify(Integer(3)*u(n), evaluate=False)

/home/ralf/sage/local/lib/python2.7/site-packages/sympy-1.0-py2.7.egg/sympy/core/sympify.pyc in sympify(a, locals, convert_xor, strict, rational, evaluate)
    320     try:
    321         a = a.replace('\n', '')
--> 322         expr = parse_expr(a, local_dict=locals, transformations=transformations, evaluate=evaluate)
    323     except (TokenError, SyntaxError) as exc:
    324         raise SympifyError('could not parse %r' % a, exc)

/home/ralf/sage/local/lib/python2.7/site-packages/sympy-1.0-py2.7.egg/sympy/parsing/sympy_parser.pyc in parse_expr(s, local_dict, transformations, global_dict, evaluate)                                                                                
    890 
    891     if not evaluate:
--> 892         code = compile(evaluateFalse(code), '<string>', 'eval')
    893 
    894     return eval_expr(code, local_dict, global_dict)

/home/ralf/sage/local/lib/python2.7/site-packages/sympy-1.0-py2.7.egg/sympy/parsing/sympy_parser.pyc in evaluateFalse(s)
    900     """
    901     node = ast.parse(s)
--> 902     node = EvaluateFalseTransformer().visit(node)
    903     # node is a Module, we want an Expression
    904     node = ast.Expression(node.body[0].value)

/home/ralf/sage/local/lib/python/ast.pyc in visit(self, node)
    239         method = 'visit_' + node.__class__.__name__
    240         visitor = getattr(self, method, self.generic_visit)
--> 241         return visitor(node)
    242 
    243     def generic_visit(self, node):

/home/ralf/sage/local/lib/python/ast.pyc in generic_visit(self, node)
    295                 for value in old_value:
    296                     if isinstance(value, AST):
--> 297                         value = self.visit(value)
    298                         if value is None:
    299                             continue

/home/ralf/sage/local/lib/python/ast.pyc in visit(self, node)
    239         method = 'visit_' + node.__class__.__name__
    240         visitor = getattr(self, method, self.generic_visit)
--> 241         return visitor(node)
    242 
    243     def generic_visit(self, node):

/home/ralf/sage/local/lib/python/ast.pyc in generic_visit(self, node)
    304                 old_value[:] = new_values
    305             elif isinstance(old_value, AST):
--> 306                 new_node = self.visit(old_value)
    307                 if new_node is None:
    308                     delattr(node, field)

/home/ralf/sage/local/lib/python/ast.pyc in visit(self, node)
    239         method = 'visit_' + node.__class__.__name__
    240         visitor = getattr(self, method, self.generic_visit)
--> 241         return visitor(node)
    242 
    243     def generic_visit(self, node):

/home/ralf/sage/local/lib/python2.7/site-packages/sympy-1.0-py2.7.egg/sympy/parsing/sympy_parser.pyc in visit_BinOp(self, node)
    954             if sympy_class in ('Add', 'Mul'):
    955                 # Denest Add or Mul as appropriate
--> 956                 new_node.args = self.flatten(new_node.args, sympy_class)
    957 
    958             return new_node

/home/ralf/sage/local/lib/python2.7/site-packages/sympy-1.0-py2.7.egg/sympy/parsing/sympy_parser.pyc in flatten(self, args, func)
    922         result = []
    923         for arg in args:
--> 924             if isinstance(arg, ast.Call) and arg.func.id == func:
    925                 result.extend(self.flatten(arg.args, func))
    926             else:

AttributeError: 'Call' object has no attribute 'id'
```

**Comment by mkoeppe** [comment] 2021-08-31 21:30
I think this issue can be closed as outdated. I cannot reproduce this error in current Sage.

**Comment by oscarbenjamin** [comment] 2021-08-31 23:21
Thanks

**Closed by oscarbenjamin** 2021-08-31 23:21 UTC
Labels: parsing, external
