### ISSUE TITLE
sympy.Symbol does not catch undefined keyword argument

### ISSUE THREAD

**Issue by leowerneck** [sympy/sympy#23939] opened 2022-08-16 19:16 UTC
I have encountered the following issue while using `sympy.Symbol`:
```py
>>> from sympy import Symbol, Abs, simplify
>>> r = Symbol("r",postive=True)
>>> print(simplify(Abs(r)))
Abs(r)
```
Notice that there was a typo in the "positive" keyword argument that was not caught by the `sympy.Symbol` function. Of course, once the typo is fixed it works:
```py
>>> from sympy import Symbol, Abs, simplify
>>> r = Symbol("r",positive=True)
>>> print(simplify(Abs(r)))
r
```
Shouldn't the typo have been caught by `sympy.Symbol`?

Thanks!
Leo

**Comment by asmeurer** [comment] 2022-08-16 21:58
This is a duplicate of https://github.com/sympy/sympy/issues/21416. See also https://github.com/sympy/sympy/pull/21417. The problem is that defining custom assumptions attributes like this is technically supported, so removing it would probably break someone's code. 

Personally I think we should at least make this issue a warning.

**Closed by asmeurer** 2022-08-16 21:58 UTC

**Comment by asmeurer** [comment] 2022-08-16 22:00
If you are interested in implementing said warning, I don't think it would be very difficult (basically just https://github.com/sympy/sympy/pull/21417/files except with `warnings.warn(...)` instead of `raise ValueError(...)`).
