### ISSUE TITLE
Give users more knobs to twist in integrate

### ISSUE THREAD

**Issue by normalhuman** [sympy/sympy#13876] opened 2018-01-09 17:53 UTC
When `integrate(f(x), (x, 0, oo))` does not work as well as one hoped, an experienced SymPy user knows to try a few things: 

1. `x = symbols('x', nonnegative=True)` may help; after all, x is nonnegative here. Sometimes it hurts, however: instead of quickly failing with one method, the integrator persists for a long time and returns something incomprehensible. For more, see my sketch #13858 where I attempted to infer assumptions automatically and was not satisfied with the result. 

2. `x = symbols('x', positive=True)` helps even more often, even though it's not strictly true. One point 0 is probably negligible... unless DiracDelta is involved... or the integrator will put an antiderivative in a form where plugging x = 0  will result in nan. This is a double-edge sword.  #13792 is an example where this assumption is necessary to get anything from `integrate`. 

3. Simplifying the antiderivative before passing to the limit at infinity. We don't want [automatic simplification](https://github.com/sympy/sympy/wiki/Automatic-Simplification) but sometimes the antiderivative is sufficiently complicated to confuse the limit-finding routine. An example is #13733. 

### Suggestion

Expose these techniques in the `integrate` method by means of keywords such as:

- infer_assumptions = None (default), 'normal' (method 1 above), 'strict' (method 2 above)
- simplify_antider = False (default), or True (method 3 above).

Better ideas for parameter names are welcome. 

Also, the [API reference for integrate](http://docs.sympy.org/latest/modules/integrals/integrals.html#api-reference)  should list all available options upfront instead of scattering them in a long discussion as it does now.

**Comment by jashan498** [comment] 2018-01-10 07:08
I want to work on it, if someone else is not working on it :)

**Comment by vishalg2235** [comment] 2018-01-10 08:54
I'am also working on this!

**Comment by jashan498** [comment] 2018-01-10 10:17
No problem, you carry on this issue!  :)

**Comment by asmeurer** [comment] 2018-01-10 14:26
Point 3 should be fixed in `limit` itself. But be careful with limit heuristics in general, as they can lead to a lot of problems if not done carefully. 

I would rather look into the root causes here for all of these before adding new APIs (especially the second API suggestion, which I'm not a fan of). https://github.com/sympy/sympy/issues/13792 looks like a bug, which happens to go away when you have an assumption.

**Comment by vishalg2235** [comment] 2018-01-10 15:11
For point 1 should I start from https://github.com/sympy/sympy/pull/13858 ?

**Comment by vishalg2235** [comment] 2018-01-10 15:51
@asmeurer Will it work if I add `e = simplify(e)` [here](https://github.com/sympy/sympy/blob/master/sympy/series/limits.py#L186) ? can you brief me how to proceed for `limit heuristics` ?

**Closed** 2018-01-10 16:52 UTC
