### ISSUE TITLE
Binomial for -ve values

### ISSUE THREAD

**Issue by iammosespaulr** [sympy/sympy#19000] opened 2020-03-28 21:04 UTC
here are some series inconsistencies in the binomial class ... like
```python
>>> binomial(-1,-4)
0
```
[but it actually is -1](http://www.wolframalpha.com/input/?i=binomial(-1%2C-4))
and
```python
>>> binomial(-5,-40)
0
```
[but it actually is -82251](http://www.wolframalpha.com/input/?i=binomial(-5%2C-40))

The thing with sympy's documentation is ... 
```
Implementation of the binomial coefficient. It can be defined
in two ways depending on its desired interpretation:

    C(n,k) = n!/(k!(n-k)!)   or   C(n, k) = ff(n, k)/k!

First, in a strict combinatorial sense it defines the
number of ways we can choose 'k' elements from a set of
'n' elements. In this case both arguments are nonnegative
integers and binomial is computed using an efficient
algorithm based on prime factorization.

The other definition is generalization for arbitrary 'n',
however 'k' must also be nonnegative. 
```  
This part is kinda incorrect mathematically ... isn't it. cause it should only return 0 if n < k ... no matter the kind of n & k
```
This case is very
useful when evaluating summations.

For the sake of convenience for negative integer 'k' this function
will return zero no matter what valued is the other argument.
```
this will cause sympy to loose a lot of mathematical functionality ... like in the case of inverse expansions ...

@sylee957 @czgdp1807 @smichr 
not satisfied with the outcome of [#14577](https://github.com/sympy/sympy/issues/14577)
and this PR [#14557](https://github.com/sympy/sympy/pull/14557)

**Comment by iammosespaulr** [comment] 2020-03-28 21:05
p.s I'm up for redefinition et.al

**Comment by smichr** [comment] 2020-03-29 16:14
A recent paper about dealing with and interpreting negative arguments is [here](https://arxiv.org/pdf/1802.02684.pdf). I think it would be worth allowing `binomial` to return values for all arbitrary arguments. (And perhaps doing so before committing #18960.)

**Comment by asmeurer** [comment] 2020-03-31 19:50
This is a duplicate of https://github.com/sympy/sympy/issues/14577. I don't know if we reached a full consensus, but I think the general agreement was to use our current definition, rather than the alternate one. But we still need to document this. It may also be useful to document an expression that gives the alternate definition if people prefer to use it.

**Closed by asmeurer** 2020-03-31 19:50 UTC
Labels: functions

**Comment by iammosespaulr** [comment] 2020-03-31 19:57
@asmeurer I plan to work on the alternate definition that supports -ve integers, if successful won't it be more versatile than our current definition ?

**Comment by asmeurer** [comment] 2020-03-31 20:27
It depends on what you mean by "versatile". 

In the other issue, we discussed certain binomial identities that hold for others that don't, and the set of identities depends on which definition you use (my understanding was that you can't have all identities at once, but I could be misremembering). For the sake of SymPy, this means that we shouldn't really perform such identities unless they hold, i.e., we know that the arguments are part of the restricted domain. So for instance, we shouldn't *really* simplify some expression with binomials unless it is actually valid. 

But let's move the discussion over to the other issue, because it has already been happening there.
