### ISSUE TITLE
Sympy Refuses to Integrate Absolute Values

### ISSUE THREAD

**Issue by cgbsu** [sympy/sympy#23397] opened 2022-04-19 18:25 UTC
[I have been trying to take integrals involving absolute values using sympy](https://postimg.cc/hJ1RCtNS) (the code is here [here [look on commit 14535a6 if in the future]](https://github.com/cgbsu/ResearchSpring2022SymbolicNotebooks0/blob/borked/work/stairwell_symbolic_solution/1d/uniform_case_attempt_2.ipynb)) but it does not seem to want to accept them, it just spits them back at me :(

This seems to have been an issue in the past [13312](https://github.com/sympy/sympy/issues/13312), [15749](https://github.com/sympy/sympy/issues/15749) [19320](https://github.com/sympy/sympy/issues/19320)

Also I have noticed that sympy has a lot of trouble simplifying complex conjugates and getting values "out of" them, even if you tell it the value is real or (conj(a)=a).

Thank you
 - Chris

**Comment by oscarbenjamin** [comment] 2022-05-07 11:39
Can you include code with a minimal reproducer for the issue(s) you refer to? I looked at the links but there's far too much to wade through there.

I'm going to close this for now because there is not enough information here for it to be a useful issue to fix but it can be reopened if there is a MWE.

**Closed by oscarbenjamin** 2022-05-07 11:39 UTC
Labels: integrals
