### ISSUE TITLE
Can't solve sin(x + a) - sin(x) (for a)

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#10426] opened 2016-01-19 16:25 UTC
```
In [9]: solveset(sin(x + a) - sin(x), a)
Out[9]: {a | a ∊ ℂ ∧ -sin(x) + sin(a + x) = 0}

In [10]: solveset(sin(x + a) - sin(x), a, domain=S.Reals)
Out[10]:
⎧              ⎛  ⎛   ⅈ⋅(-a - x)    ⅈ⋅(a + x)⎞  ⅈ⋅x    2⋅ⅈ⋅x    ⎞  -ⅈ⋅x    ⎫
⎪            ⅈ⋅⎝- ⎝- ℯ           + ℯ         ⎠⋅ℯ    + ℯ      - 1⎠⋅ℯ        ⎪
⎨a | a ∊ ℝ ∧ ────────────────────────────────────────────────────────── = 0⎬
⎪                                        2                                 ⎪
⎩                                                                          ⎭

In [11]: solve(sin(x + a) - sin(x), a)
Out[11]: [-x + asin(sin(x)), -x - asin(sin(x)) + π]

```

The solution should be `a=2*pi*n`. I believe the first solution from solve is equivalent to that.

**Comment by MSeeker** [comment] 2016-01-20 04:46
For a start, `a = 2*pi*n` is not the complete solution to the equation. Since `sin(x+a) - sin(x) = 2*cos(x+a/2)*sin(a/2)`, `a = 2*pi*n` corresponds only to the part of solution where `sin(a/2) = 0`, whereas `cos(x + a/2) = 0` gives `a = (2*n + 1) * pi - 2*x`.
SymPy seems to give the correct answer if we assume `x` to be real, but fails if it is a general complex variable. Perhaps this is due to the different implementation of `solveset_real` and `solveset_complex`?
```Python
>>> x = symbols('x', real=True)
... z = symbols('z')
... a = Dummy('a')
...
>>> solveset(sin(x + a) - sin(x), a, domain=S.Reals)
                  ⎧           ⎛  -2⋅ⅈ⋅x⎞        ⎫
{2⋅n⋅π | n ∊ ℤ} ∪ ⎨2⋅n⋅π + arg⎝-ℯ      ⎠ | n ∊ ℤ⎬
                  ⎩                             ⎭
>>> solveset(sin(z + a) - sin(z), a, domain=S.Reals)
⎧              ⎛  ⎛   ⅈ⋅(-a - z)    ⅈ⋅(a + z)⎞  ⅈ⋅z    2⋅ⅈ⋅z    ⎞  -ⅈ⋅z    ⎫
⎪            ⅈ⋅⎝- ⎝- ℯ           + ℯ         ⎠⋅ℯ    + ℯ      - 1⎠⋅ℯ        ⎪
⎨a | a ∊ ℝ ∧ ────────────────────────────────────────────────────────── = 0⎬
⎪                                        2                                 ⎪
⎩                                                                          ⎭
```
Having said that, I believe `solveset` does needs improvement regarding trigonometric equations. For instance it doesn't know how to solve `sin(a/2) = 0`:
```Python
>>> solveset(sin(a/2), a, domain=S.Reals)
⎧                           -a⋅ⅈ      ⎫
⎪                           ─────     ⎪
⎪               ⎛ a⋅ⅈ    ⎞    2       ⎪
⎨            -ⅈ⋅⎝ℯ    - 1⎠⋅ℯ          ⎬
⎪a | a ∊ ℝ ∧ ───────────────────── = 0⎪
⎪                      2              ⎪
⎩                                     ⎭
```

**Comment by asmeurer** [comment] 2016-01-20 14:25
I think you are right. My goal here is specifically to find a solution that does not depend on x, so as to show that sine is periodic. Hence, although the solutions from solve are probably correct (plus `2*pi*n`) the second one is not useful as written because it is not easy to see that it doesn't depend on x.

**Comment by Shekharrajak** [comment] 2016-01-27 11:22
solution should be : 
`a = 4πn, a = 4πn + 2π, a = 4πn + π − 2x, a = 4πn + 3π − 2x`
because using this formula : 
`sin s − sin t = 2cos((s+t)/2)sin((s-t)/2)`
we get this `2cos((2x+a)/2)sin(a/2) = 0`

**Comment by asmeurer** [comment] 2016-01-27 15:15
Getting the solution to reduce to just `2*pi*n` would also be helpful (since that would be the period of sine). This is just a matter of getting `solveset(sin(x))` to give `pi*n` instead of `2*pi*n` and `2*pi*n + pi`.

**Comment by oscarbenjamin** [comment] 2020-03-08 21:45
Currently solveset gives
```
In [62]: solveset(sin(x + a) - sin(x), a)                                                                                                                     
Out[62]: 
                  ⎧   ⎛  ⎛           ⎛  -2⋅ⅈ⋅x⎞⎞          ⎞        ⎫
{2⋅n⋅π | n ∊ ℤ} ∪ ⎨-ⅈ⋅⎝ⅈ⋅⎝2⋅n⋅π + arg⎝-ℯ      ⎠⎠ + 2⋅im(x)⎠ | n ∊ ℤ⎬
                  ⎩                                                
```
The first part of that is that the `2*n*pi` as requested. I guess that the other part shows that the solution depends on x in some way. For example if x is zero then we should have:
```
In [63]: solveset(sin(0 + a) - sin(0), a)                                                                                                                     
Out[63]: {2⋅n⋅π | n ∊ ℤ} ∪ {2⋅n⋅π + π | n ∊ ℤ}
```
which gives `a = n*pi`. The solutions from solveset matches up with this for zero x
```
In [64]: solveset(sin(x + a) - sin(x), a).subs(x, 0)                                                                                                          
Out[64]: {2⋅n⋅π | n ∊ ℤ} ∪ {2⋅n⋅π + π | n ∊ ℤ}
```
It also works for some other values:
```
In [67]: solveset(sin(1 + a) - sin(1), a).simplify()                                                                                                          
Out[67]: {2⋅n⋅π | n ∊ ℤ} ∪ {2⋅n⋅π - 2 + π | n ∊ ℤ}

In [68]: solveset(sin(x + a) - sin(x), a).subs(x, 1).simplify()                                                                                               
Out[68]: {2⋅n⋅π | n ∊ ℤ} ∪ {2⋅n⋅π - 2 + π | n ∊ ℤ}
```
I think this is correct so closing.

This can be closed if a test is added for solveset to prevent future regressions.

**Comment by oscarbenjamin** [comment] 2020-03-08 21:47
A test should also be added for solve

**Comment by asmeurer** [comment] 2020-03-09 18:46
The original motivation for this was for the `periodicity` function. It looks like `periodicity` currently works without making use of solve.

**Comment by hyadav2k** [comment] 2020-12-09 14:40
Hi @asmeurer @oscarbenjamin, I would like to know if this issue is resolved or I can add test cases for solveset. Kindly guide me through the process if it's still open.

**Comment by oscarbenjamin** [comment] 2020-12-09 18:23
I think that the solution is correct although potentially it could be simplified. This issue could be closed if the tests were added.

**Closed** 2020-12-24 12:24 UTC
Labels: Easy to Fix, solvers.solveset
