### ISSUE TITLE
Inspect error

### ISSUE THREAD

**Issue by evgeniy97** [sympy/sympy#14935] opened 2018-07-17 09:59 UTC
Hello! It's look like  sympy magic and inspect magic break each other.

When we want to get the source of the lambda function, declared in another python file, in a dictionary, we get unexpected behavior - instead of got the function code we got all dictionary. Please, check the problem in attached files.

Thaks!

[Inspect_error.zip](https://github.com/sympy/sympy/files/2201139/Inspect_error.zip)

**Comment by sidhantnagpal** [comment] 2018-08-10 03:28
It would be better if you can include the code or exact problem in the description itself.

**Comment by moorepants** [comment] 2018-08-10 03:39
Yes, please paste a code snippet of a minimal example. Here is a nice guidline: https://stackoverflow.com/help/mcve

**Comment by oscarbenjamin** [comment] 2019-02-09 01:31
Closing as incomplete

**Closed by oscarbenjamin** 2019-02-09 01:31 UTC

**Comment by asmeurer** [comment] 2019-02-09 03:13
The code was uploaded as a zip file. In the future, it would be helpful to paste at least the error message or incorrect code to the issue itself, so that people don't have to download a zip file to see what is going on. 

However, this doesn't look like an issue with SymPy. `inspect` works by searching the source code for the function source, based on the filename and line number that are in the definition. It is limited in how well it works with lambdas. The issue is with Python's `inspect`. You would get the same issue even not using SymPy at all.
