### ISSUE TITLE
Convert_to in physics.unit does not work as expected for self-defined dimension.

### ISSUE THREAD

**Issue by szsdk** [sympy/sympy#13044] opened 2017-07-26 03:19 UTC
```python
from sympy.physics.units import s, minute, h, day
from sympy.physics.units import convert_to, Quantity, Dimension 

information = Dimension('information')
bit = Quantity('bit', information, 1) 
byte = Quantity('byte', information, 8*bit) 
kB = Quantity('kilobyte', information, 1024*byte) 

a = 10 * kB * h
print(a)
print(convert_to(a, byte))
print(convert_to(a, minute))
print(convert_to(a, [byte, minute]))
```
The output is
```
10*hour*kilobyte
10240*byte*hour
4915200*minute
4915200*minute
```
But the expected output is
```
10*hour*kilobyte
10240*byte*hour
600*minute*kilobyte
614400*minute*byte
```

System information
conda 4.3.23
python 3.6.1
sympy 1.1

PS: I think the unit for information is extremely useful. Maybe you guys could add those units into the lib.

**Comment by Upabjojr** [comment] 2017-07-26 21:30
Hi, thanks for reporting. Yes, your units could be useful.

**Comment by Upabjojr** [comment] 2017-07-26 21:34
By the way... isn't a kibibyte = 1024*bytes? Kilobyte is 1000 bytes, despite many systems using 1024.

**Comment by Upabjojr** [comment] 2017-07-26 21:38
https://github.com/sympy/sympy/pull/13048

**Comment by Upabjojr** [comment] 2017-07-26 22:28
@szsdk the problem is that your new dimension is not registered in the dimensional dependency tree.

**Comment by szsdk** [comment] 2017-07-26 23:18
```phython
from sympy.physics.units import s, minute, h, day
from sympy.physics.units import convert_to, Quantity, Dimension 

information = Dimension('information')
information._register_as_base_dim()
bit = Quantity('bit', information, 1) 
byte = Quantity('byte', information, 8*bit) 
kB = Quantity('kilobyte', information, 1024*byte) 

a = 10 * kB * h
print(a)
print(convert_to(a, byte))
print(convert_to(a, minute))
print(convert_to(a, [byte, minute]))
```
@Upabjojr You mean like this? It still does not work.

**Comment by Upabjojr** [comment] 2017-07-26 23:28
I've noticed that. If you put that in `sympy/physics/units/dimensions.py`, apparently it works.

The best is to debug `convert_to`.

**Comment by szsdk** [comment] 2017-07-26 23:34
@Upabjojr By the way, it this a typo in abbrev?
```python
kg = kilogram = kilograms = Quantity("kilogram", mass, kilo, abbrev="g")
```

**Comment by Upabjojr** [comment] 2017-07-26 23:49
It looks like a typo.

**Comment by Upabjojr** [comment] 2017-07-26 23:50
But don't know, if I remember correctly there could be some way to add the k

**Comment by oscarbenjamin** [comment] 2019-03-05 02:52
Running the code from above now gives the expected output:
```
10*hour*kilobyte
10240*byte*hour
600*kilobyte*minute
614400*byte*minute
```
However it also gives deprecation warnings. Since this code is deprecated and seems to work anyway I'll closing this. Please take a look at the new units system.

**Closed by oscarbenjamin** 2019-03-05 02:52 UTC
