### ISSUE TITLE
Poly(E**100000000) is slow to create

### ISSUE THREAD

**Issue by pragyanmehrotra** [sympy/sympy#16222] opened 2019-03-10 09:30 UTC
```python
>>>from sympy import *
>>>x = symbols('x')
>>>limit(E**x,x,10000000) # takes about 8 seconds to return
exp(10000000)
>>>limit(E**x,x,100000000) # takes about 80 seconds to return
exp(100000000)
```

**Comment by oscarbenjamin** [comment] 2019-03-10 09:40
I've edited your description so it uses markdown backticks to render the code properly. Can you do that yourself in future?

**Comment by pragyanmehrotra** [comment] 2019-03-10 09:41
yes definitely, sorry about that

**Comment by pragyanmehrotra** [comment] 2019-03-12 21:10
One way I thought we could do to solve this issue may be that we could use the substitution method
It'd trace as follows

```python
t = x + 10000000 # a dummy variable t is introduced
E**x = (E**10000000)*(E**t)
# hence we can then call
limit((E**10000000)*(E**t),t,0)
```
However, this approach also takes the same amount of time, does this imply that the term E\**10000000 is getting evaluated somewhere in the function like is it calculating the value of E\**10000000 somewhere in the middle but returning exp(100000000) finally?

just to note-

```python
>>> E**10000000000000000000000
exp(10000000000000000000000) # returns in under a second
```

**Comment by asmeurer** [comment] 2019-03-12 21:27
Looks like in part of the calculation it tries to create a degree 100000000 polynomial, which is slow because it uses a dense representation. `simplify(E**100000000)` also has the same problem.

**Comment by asmeurer** [comment] 2019-03-12 21:28
I guess specifically the problem is `Poly(E**100000000)`. All other functions that are slow with it stem from that.

**Comment by asmeurer** [comment] 2019-03-12 21:31
I don't know if this will be easy to fix. We really need to phase out the dense polynomial representation as the default. It should only be used when it is actually faster, which is certainly not the case for polynomials of very large degree or with many variables.

**Comment by sachin-4099** [comment] 2020-06-01 16:47
In the current master, it takes no time to evaluate the result:
```
In [31]: %time limit(E**x,x,100000000)
Wall time: 0 ns
Out[31]:
 100000000
e

from timeit import default_timer as clock
t1 = clock()
limit(E**x,x,100000000)
t2 = clock()

Out[34]:
 100000000
e

In [36]: t2 - t1
Out[36]: 0.5928887999999688

```

So, this now takes approx. 0.6 secs as compared to 80 secs previously.

**Comment by sachin-4099** [comment] 2020-06-05 13:11
Only requires a test in order to be closed.

**Comment by sachin-4099** [comment] 2020-06-29 17:39
I think this is no longer related to the `limit` issue.

On master:
```
In [1]: %time Poly(E**100000000)
Wall time: 22 s
Out[1]: Poly(E**100000000, E, domain='ZZ')

In [1]: %time Poly(E**1000000000)
Takes too much time
```

Therefore, `Poly(E**100000000)` is still slow to create.

**Comment by sachin-4099** [comment] 2020-06-29 17:43
I will open a new issue after the PR adding those `limit` testcases get merged.

**Closed** 2020-06-29 17:53 UTC
Labels: Easy to Fix, polys, series, simplify
