### ISSUE TITLE
trigsimp fails when trig terms are multiplied by Integral but not Function

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#16835] opened 2019-05-14 13:24 UTC
As [reported](https://stackoverflow.com/questions/55808780/issues-with-sympy-simplify-factor-collect/56104541#56104541), `trigsimp` succeeds for something like this
```python
>>> f = Function('f')
>>> expr = sin(theta)**2*f(z) + cos(theta)**2*f(z)
>>> trigsimp(expr) == f(z)
True
```
But fails with this
```python
>>> expr.subs(f(z),Integral(z))
sin(theta)**2*Integral(z, z) + cos(theta)**2*Integral(z, z)
>>> trigsimp(_)==_  # i.e. unchanged
True
```

**Comment by oscarbenjamin** [comment] 2019-05-14 14:08
This is a duplicate of #16705 (which seems to have been opened by the same author as the SO question).

**Closed by oscarbenjamin** 2019-05-14 14:08 UTC
