### ISSUE TITLE
AttributeError: 'Subs' object has no attribute 'variable_count'

### ISSUE THREAD

**Issue by willt-pearson** [sympy/sympy#20037] opened 2020-09-02 19:25 UTC
Problem:
Nested Subs objects are not playing nicely with other objects when doit() method is invoked. This is causing problems, since I often use Subs() when I am trying to construct an unevaluated representation of my object, and different subexpressions may sometimes need different substitutions.

In your terminal:
```
In: from sympy import *
In: Mul(Add(Subs(Derivative(Integer(1), Tuple(Symbol('x', real=True), Integer(1))), Tuple(Symbol('x', real=True)), Tuple(Float('9.9999999999999995e-7', precision=53))), Subs(Derivative(Mul(Integer(-1), log(Symbol('x', real=True))), Tuple(Symbol('x', real=True), Integer(1))), Tuple(Symbol('x', real=True)), Tuple(Float('9.9999999999999995e-7', precision=53)))), Pow(Subs(Derivative(Add(log(Symbol('x', real=True)), Integer(1)), Tuple(Symbol('x', real=True), Integer(1))), Tuple(Symbol('x', real=True)), Tuple(Float('9.9999999999999995e-7', precision=53))), Integer(-1))).doit()

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/utollwi/.pyenv/versions/3.6.10/lib/python3.6/site-packages/sympy/core/basic.py", line 1630, in doit
    for term in self.args]
  File "/Users/utollwi/.pyenv/versions/3.6.10/lib/python3.6/site-packages/sympy/core/basic.py", line 1630, in <listcomp>
    for term in self.args]
  File "/Users/utollwi/.pyenv/versions/3.6.10/lib/python3.6/site-packages/sympy/core/basic.py", line 1630, in doit
    for term in self.args]
  File "/Users/utollwi/.pyenv/versions/3.6.10/lib/python3.6/site-packages/sympy/core/basic.py", line 1630, in <listcomp>
    for term in self.args]
  File "/Users/utollwi/.pyenv/versions/3.6.10/lib/python3.6/site-packages/sympy/core/function.py", line 2113, in doit
    for vi, ci in e.variable_count:
AttributeError: 'Subs' object has no attribute 'variable_count'
```

**Comment by oscarbenjamin** [comment] 2021-01-10 15:00
A simpler reproducer of this is:
```python
In [22]: Subs(Derivative(1, x), x, 1.0e-6)
Out[22]: 
⎛d    ⎞│        
⎜──(1)⎟│        
⎝dx   ⎠│x=1.0e-6

In [23]: Subs(Derivative(1, x), x, 1.0e-6).doit()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-23-833ee96076db> in <module>
----> 1 Subs(Derivative(1, x), x, 1.0e-6).doit()

~/current/sympy/sympy/sympy/core/function.py in doit(self, **hints)
   2288                 expr = e.expr
   2289                 free = expr.free_symbols
-> 2290                 for vi, ci in e.variable_count:
   2291                     if isinstance(vi, Symbol) and vi in free:
   2292                         expr = expr.diff((vi, ci))

AttributeError: 'Subs' object has no attribute 'variable_count'
> /Users/enojb/current/sympy/sympy/sympy/core/function.py(2290)doit()
   2288                 expr = e.expr
   2289                 free = expr.free_symbols
-> 2290                 for vi, ci in e.variable_count:
   2291                     if isinstance(vi, Symbol) and vi in free:
   2292                         expr = expr.diff((vi, ci))
```
The error arises from here:
https://github.com/sympy/sympy/blob/ab39cbb48e23284889ca851c35845ec9b66a37c9/sympy/core/function.py#L2275-L2292
It is tested that `e` is a `Derivative` for this block to run. However line 2283 calls `e.subs()` which turns `e` into a `Subs`:
```python
In [25]: Derivative(1, x)
Out[25]: 
d    
──(1)
dx   

In [26]: Derivative(1, x).subs(x, 1)
Out[26]: 
⎛d    ⎞│   
⎜──(1)⎟│   
⎝dx   ⎠│x=1

In [27]: type(_)
Out[27]: sympy.core.function.Subs
```
I think that the purpose of the `for vi, pi in undone:` loop is to substitute in symbols unrelated to the differentiation e.g.:
```python
In [31]: Derivative(y, x).subs(y, 1)
Out[31]: 
d    
──(1)
dx  
```
However the check fails because:
```
In [32]: Derivative(1, x)
Out[32]: 
d    
──(1)
dx   

In [33]: Derivative(1, x).free_symbols
Out[33]: set()
```
I think maybe `Derivative.free_symbols` should include the symbols being differentiated with respect to.

**Comment by hyadav2k** [comment] 2021-01-12 15:15
@oscarbenjamin This error does not come in my local for the test case `Subs(Derivative(1, x), x, 1.0e-6).doit()`. Isn't this issue was fixed by #20684.
Kindly provide your feedback
Thanks.

**Comment by oscarbenjamin** [comment] 2021-01-12 15:40
Yes, it looks like it was fixed. I must have been testing with an out of date master. Thanks!

**Closed by oscarbenjamin** 2021-01-12 15:40 UTC
Labels: functions

**Comment by pneudecorb** [comment] 2021-02-16 18:19
This issue was not fixed and still occurs as of Sympy 1.7.1

**Comment by oscarbenjamin** [comment] 2021-02-16 18:23
Have you tested with the master branch?

**Comment by pneudecorb** [comment] 2021-02-16 18:32
I just realized that 1.7.1 was released before this fix was committed.  I'll re-evaluate on master.

**Comment by pneudecorb** [comment] 2021-02-16 18:39
Definitely works on master.  Sorry about the confusion.
