### ISSUE TITLE
solve((2*sqrt(x)/(x + 1)**2 - 1/(sqrt(x)*(x + 1)) - 1/(4*x**(3/2)))/(x + 1), x) has raised IndexError

### ISSUE THREAD

**Issue by satels** [sympy/sympy#18226] opened 2020-01-04 15:43 UTC
```python
Python console for SymPy 1.5 (Python 2.7.12)

These commands were executed:
>>> from __future__ import division
>>> from sympy import *
>>> x, y, z, t = symbols('x y z t')
>>> k, m, n = symbols('k m n', integer=True)
>>> f, g, h = symbols('f g h', cls=Function)
>>> eq = Eq((2*sqrt(x)/(x + 1)**2 - 1/(sqrt(x)*(x + 1)) - 1/(4*x**(3/2)))/(x + 1), 0)
>>> solve(eq, x)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/base/data/home/apps/s~sympy-live-hrd/20191227t021942.423433632413966915/sympy/sympy/solvers/solvers.py", line 1174, in solve
    solution = _solve(f[0], *symbols, **flags)
  File "/base/data/home/apps/s~sympy-live-hrd/20191227t021942.423433632413966915/sympy/sympy/solvers/solvers.py", line 1766, in _solve
    checksol(f_num, {symbol: r}, **flags) is not False]
  File "/base/data/home/apps/s~sympy-live-hrd/20191227t021942.423433632413966915/sympy/sympy/solvers/solvers.py", line 285, in checksol
    val = f.subs(sol)
  File "/base/data/home/apps/s~sympy-live-hrd/20191227t021942.423433632413966915/sympy/sympy/core/basic.py", line 1002, in subs
    rv = rv._subs(old, new, **kwargs)
  File "/base/data/home/apps/s~sympy-live-hrd/20191227t021942.423433632413966915/sympy/sympy/core/cache.py", line 94, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/base/data/home/apps/s~sympy-live-hrd/20191227t021942.423433632413966915/sympy/sympy/core/compatibility.py", line 897, in wrapper
    result = user_function(*args, **kwds)
  File "/base/data/home/apps/s~sympy-live-hrd/20191227t021942.423433632413966915/sympy/sympy/core/basic.py", line 1116, in _subs
    rv = fallback(self, old, new)
  File "/base/data/home/apps/s~sympy-live-hrd/20191227t021942.423433632413966915/sympy/sympy/core/basic.py", line 1088, in fallback
    arg = arg._subs(old, new, **hints)
  File "/base/data/home/apps/s~sympy-live-hrd/20191227t021942.423433632413966915/sympy/sympy/core/cache.py", line 94, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/base/data/home/apps/s~sympy-live-hrd/20191227t021942.423433632413966915/sympy/sympy/core/compatibility.py", line 897, in wrapper
    result = user_function(*args, **kwds)
  File "/base/data/home/apps/s~sympy-live-hrd/20191227t021942.423433632413966915/sympy/sympy/core/basic.py", line 1116, in _subs
    rv = fallback(self, old, new)
  File "/base/data/home/apps/s~sympy-live-hrd/20191227t021942.423433632413966915/sympy/sympy/core/basic.py", line 1088, in fallback
    arg = arg._subs(old, new, **hints)
  File "/base/data/home/apps/s~sympy-live-hrd/20191227t021942.423433632413966915/sympy/sympy/core/cache.py", line 94, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/base/data/home/apps/s~sympy-live-hrd/20191227t021942.423433632413966915/sympy/sympy/core/compatibility.py", line 897, in wrapper
    result = user_function(*args, **kwds)
  File "/base/data/home/apps/s~sympy-live-hrd/20191227t021942.423433632413966915/sympy/sympy/core/basic.py", line 1114, in _subs
    rv = self._eval_subs(old, new)
  File "/base/data/home/apps/s~sympy-live-hrd/20191227t021942.423433632413966915/sympy/sympy/core/power.py", line 778, in _eval_subs
    return new**self.exp._subs(old, new)
  File "/base/data/home/apps/s~sympy-live-hrd/20191227t021942.423433632413966915/sympy/sympy/core/expr.py", line 210, in __pow__
    return self._pow(other)
  File "/base/data/home/apps/s~sympy-live-hrd/20191227t021942.423433632413966915/sympy/sympy/core/decorators.py", line 91, in __sympifyit_wrapper
    return func(a, b)
  File "/base/data/home/apps/s~sympy-live-hrd/20191227t021942.423433632413966915/sympy/sympy/core/decorators.py", line 129, in binary_op_wrapper
    return func(self, other)
  File "/base/data/home/apps/s~sympy-live-hrd/20191227t021942.423433632413966915/sympy/sympy/core/expr.py", line 206, in _pow
    return Pow(self, other)
  File "/base/data/home/apps/s~sympy-live-hrd/20191227t021942.423433632413966915/sympy/sympy/core/cache.py", line 94, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/base/data/home/apps/s~sympy-live-hrd/20191227t021942.423433632413966915/sympy/sympy/core/compatibility.py", line 897, in wrapper
    result = user_function(*args, **kwds)
  File "/base/data/home/apps/s~sympy-live-hrd/20191227t021942.423433632413966915/sympy/sympy/core/power.py", line 301, in __new__
    obj = b._eval_power(e)
  File "/base/data/home/apps/s~sympy-live-hrd/20191227t021942.423433632413966915/sympy/sympy/core/power.py", line 379, in _eval_power
    b = abs(im(b))*S.ImaginaryUnit
  File "/base/data/home/apps/s~sympy-live-hrd/20191227t021942.423433632413966915/sympy/sympy/core/expr.py", line 171, in __abs__
    return Abs(self)
  File "/base/data/home/apps/s~sympy-live-hrd/20191227t021942.423433632413966915/sympy/sympy/core/cache.py", line 94, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/base/data/home/apps/s~sympy-live-hrd/20191227t021942.423433632413966915/sympy/sympy/core/compatibility.py", line 897, in wrapper
    result = user_function(*args, **kwds)
  File "/base/data/home/apps/s~sympy-live-hrd/20191227t021942.423433632413966915/sympy/sympy/core/function.py", line 473, in __new__
    result = super(Function, cls).__new__(cls, *args, **options)
  File "/base/data/home/apps/s~sympy-live-hrd/20191227t021942.423433632413966915/sympy/sympy/core/cache.py", line 94, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/base/data/home/apps/s~sympy-live-hrd/20191227t021942.423433632413966915/sympy/sympy/core/compatibility.py", line 897, in wrapper
    result = user_function(*args, **kwds)
  File "/base/data/home/apps/s~sympy-live-hrd/20191227t021942.423433632413966915/sympy/sympy/core/function.py", line 288, in __new__
    evaluated = cls.eval(*args)
  File "/base/data/home/apps/s~sympy-live-hrd/20191227t021942.423433632413966915/sympy/sympy/functions/elementary/complexes.py", line 473, in eval
    arg = signsimp(arg, evaluate=False)
  File "/base/data/home/apps/s~sympy-live-hrd/20191227t021942.423433632413966915/sympy/sympy/simplify/simplify.py", line 383, in signsimp
    e = sub_post(sub_pre(expr))
  File "/base/data/home/apps/s~sympy-live-hrd/20191227t021942.423433632413966915/sympy/sympy/simplify/cse_opts.py", line 18, in sub_pre
    e = e.xreplace(reps)
  File "/base/data/home/apps/s~sympy-live-hrd/20191227t021942.423433632413966915/sympy/sympy/core/basic.py", line 1192, in xreplace
    value, _ = self._xreplace(rule)
  File "/base/data/home/apps/s~sympy-live-hrd/20191227t021942.423433632413966915/sympy/sympy/core/basic.py", line 1207, in _xreplace
    a_xr = _xreplace(rule)
  File "/base/data/home/apps/s~sympy-live-hrd/20191227t021942.423433632413966915/sympy/sympy/core/basic.py", line 1214, in _xreplace
    return self.func(*args), True
  File "/base/data/home/apps/s~sympy-live-hrd/20191227t021942.423433632413966915/sympy/sympy/polys/rootoftools.py", line 331, in __new__
    (-degree, degree - 1, index))
IndexError: root index out of [-2, 1] range, got 2

```

**Comment by ethankward** [comment] 2020-01-04 17:23
See also #18203.

**Comment by jksuom** [comment] 2020-01-05 11:22
The offending complex root is `CRootOf(3*x**2 - 6*x - 1, 2), 2)`, where the index 2 is expected to be in `range(2)` as the degree of the polynomial seems to be 2. However, the polynomial really is `PurePoly(3*(sqrt(x))**4 - 6*(sqrt(x))**2 - 1, sqrt(x), domain='ZZ')` that is of degree 4 in its generator `sqrt(x)`. The error shows up when the polynomial is temporarily converted to an expression and the generator is lost.

This is an issue that the docstring of `CRootOf` points out: https://github.com/sympy/sympy/blob/79d03d39c7d7786a98eeb983b5f6c3ec2a77a2ac/sympy/polys/rootoftools.py#L267-L269

The obvious fix would be to use only symbols as generators in polynomials whose roots are to be computed, but that may be hard to arrange. An easier solution is making `PurePoly` always use only symbolic generators. It is permissible to change the generators as a pure polynomial is conceptually a collection of coefficients, a generator is only needed for representing it as an expression. This is one way of changing the generator:
```
--- a/sympy/polys/polytools.py
+++ b/sympy/polys/polytools.py
@@ -4165,6 +4165,9 @@ def _strict_eq(f, g):
 class PurePoly(Poly):
     """Class for representing pure polynomials. """
 
+    def __init__(self, rep, *gens, **args):
+        self.gens = (Symbol('x'),)
+
     def _hashable_content(self):
         """Allow SymPy to hash Poly instances. """
         return (self.rep,)
```

**Comment by oscarbenjamin** [comment] 2020-02-08 11:30
I would say that the ultimate source of the problem here is the fact that Poly is all mixed up with Expr. It would be better if Poly was a Basic subclass and needed to be explicitly converted to Expr any time it should be used as one rather than passed around getting mixed up as different types in different calculations.

Having PurePoly use a uniform symbol seems like a good idea anyway though. The code would need to take care of multivariate polynomials:
```
In [3]: PurePoly(x*y, (x, y)).gens                                                                                                             
Out[3]: (x, y)
```
Also I think it should be handled in `__new__`. PurePoly needs a `__new__` method that intercepts the arguments and canonicalises all of the symbols before passing them to `Poly.__new__`. The change needs to be to the internal expressions, the generators and also the domain since a symbol can be part of that:
```
In [9]: PurePoly(x*y, (x,)).domain                                                                                                             
Out[9]: ZZ[y]
```
The best way to achieve the change in all 3 places is by doing it before calling `Poly.__new__` which means that it can not be done in an `__init__` method.

Canonicalising the symbols at construction is a better approach that defining custom `__eq__/__hash__`. We should follow the same approach in `Lambda`.

**Comment by jksuom** [comment] 2020-02-08 12:40
> the problem here is the fact that Poly is all mixed up with Expr.

I agree. It is my understanding that the Expr class was created for objects that have common arithmetic operations: addition, multiplication etc. Matrices have those operations but they cannot be freely combined with arbitrary expressions, so they must have their own methods. The same is true of polynomials. I think that neither matrices nor polynomials should derive from Expr.

> PurePoly needs a `__new__` method that intercepts the arguments and canonicalises all of the symbols before passing them to `Poly.__new__`.

I think that it would suffice to canonicalise the generator(s) after `Poly.__new__`. They are only place-holders in `PurePoly`. It looks like any dummies could be used.

> The code would need to take care of multivariate polynomials:

This is currently not necessary. Pure polynomials are only used in `RootOf` that deals with univariate polynomials. Of course, it wouldn't hurt if multivariate polynomials can be handled.

**Comment by czgdp1807** [comment] 2020-05-05 18:38
The issue is fixed on `master`,
```python
>>> eq = Eq((2*sqrt(x)/(x + 1)**2 - 1/(sqrt(x)*(x + 1)) - 1/(4*x**(3/2)))/(x + 1), 0)
>>> solve(eq, x)
[-0.154700538379252, -0.154700538379252, 2.15470053837925, 2.15470053837925]
```
Though it was a bit slow but a separate performance related issue can be opened for the same.

**Closed by czgdp1807** 2020-05-05 18:38 UTC
Labels: solvers.solve
