### ISSUE TITLE
Limit function fails

### ISSUE THREAD

**Issue by vassbu** [sympy/sympy#11262] opened 2016-06-20 11:10 UTC
The limit of the following ratio should be 1/3, not 1:

> > > n = symbols('n', integer=True)
> > > a = n**2/3**n
> > > a1 = a.subs(n, n+1)
> > > r = a1/a
> > > limit(r, n, oo)
> > > 1

**Comment by jksuom** [comment] 2016-06-20 11:54
Looks like a duplicate of #10610.

**Comment by oscarbenjamin** [comment] 2019-03-16 01:25
Seems to work now in master:
```julia
In [11]: n = symbols('n', integer=True)                                                                                                                       

In [12]: a = n**2/3**n                                                                                                                                        

In [13]: a                                                                                                                                                    
Out[13]: 
 -n  2
3  ⋅n 

In [14]: a1 = a.subs(n, n+1)                                                                                                                                  

In [15]: a1                                                                                                                                                   
Out[15]: 
 -n - 1        2
3      ⋅(n + 1) 

In [16]: r = a1/a                                                                                                                                             

In [17]: r                                                                                                                                                    
Out[17]: 
 n  -n - 1        2
3 ⋅3      ⋅(n + 1) 
───────────────────
          2        
         n         

In [18]: limit(r, n, oo)                                                                                                                                      
Out[18]: 1/3
```

**Closed** 2019-04-26 09:04 UTC
Labels: Could Close, series
