### ISSUE TITLE
preview() invalid keyword argument

### ISSUE THREAD

**Issue by atreyv** [sympy/sympy#9755] opened 2015-07-29 10:20 UTC
from sympy import *
    x = symbols('x')
    preview(x+x)

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-06affd9b6d42> in <module>()
----> 1 preview(x+x)

/dev/sympy/sympy/printing/preview.pyc in preview(expr, output, viewer, euler, packages, filename, outputbuffer, preamble, dvioptions, outputTexFile, **latex_settings)
      184         workdir = tempfile.mkdtemp()
      185 
--> 186         with open(join(workdir, 'texput.tex'), 'w', encoding='utf-8') as fh:
      187             fh.write(latex_main % latex_string)
      188 

TypeError: 'encoding' is an invalid keyword argument for this function

**Comment by bsdz** [comment] 2015-07-30 14:28
This looks like a duplicate of https://github.com/sympy/sympy/pull/9692.

**Comment by bjodah** [comment] 2015-09-06 17:01
Yes, this was fixed in #9692 and #9801

**Closed by bjodah** 2015-09-06 17:01 UTC
