### ISSUE TITLE
RR.parent returns CC

### ISSUE THREAD

**Issue by sylee957** [sympy/sympy#18278] opened 2020-01-09 19:26 UTC
```python3
>>> from sympy import *
>>> from sympy.polys import *

>>> RR(2).parent()
CC
>>> CC(2).parent()
CC
```
Should `RR.parent` be returning `RR`?

**Comment by V1krant** [comment] 2020-01-10 10:55
I think it may have something to do with mpmath and mpelements.py, because  QQ(2).parent() prints QQ (as expected) and QQ is not used in mpelements.py. Please correct me if I am wrong.

**Comment by jksuom** [comment] 2020-01-10 13:34
`RR` and `CC` both define their own multiprecision context instances.
```
>>> from sympy import *
>>> RR._context
<sympy.polys.domains.mpelements.MPContext object at 0x7f1067739da0>
>>> CC._context
<sympy.polys.domains.mpelements.MPContext object at 0x7f1067743438>
```
This context is assigned to the data types, `RealElement` and `ComplexElement`, when the `MPContext` is initialized: https://github.com/sympy/sympy/blob/df38ad11d3f3ab5b94c878346fe8bfcf40fa6027/sympy/polys/domains/mpelements.py#L57-L62
The problem is that the same code is used to initialize both real and complex contexts. It seems that currently `RR` is created first and, when `CC` is initialized, its context will override the original context of `RealElement` on line 61.

To fix this, there should probably be a keyword argument to separate the two cases from each other.

**Comment by V1krant** [comment] 2020-01-10 13:46
> It seems that currently `RR` is created first and, when `CC` is initialized, its context will override the original context of `RealElement` on line 61.

I think there might be another problem because reversing the order of declaration, i.e., interchanging line 61,62 and even 57,58 and 59,60 give the same result as CC for RR(2).parent().

**Comment by V1krant** [comment] 2020-01-12 14:37
> To fix this, there should probably be a keyword argument to separate the two cases from each other.

You were right :). I misunderstood your explanation. Adding a keyword argument, to prevent from overriding fixes this issue.

**Closed** 2020-01-13 12:51 UTC
Labels: polys
