### ISSUE TITLE
dsolve fail with Bessel equation when division appears

### ISSUE THREAD

**Issue by nicoguaro** [sympy/sympy#19317] opened 2020-05-15 01:19 UTC
When we solve the Bessel differential equation

```python
from sympy import symbols, dsolve, Function
x = symbols("x")
f = symbols("f", cls=Function)
a, b, c = symbols("a b c", positive=True)
ode = x**2*f(x).diff(x, 2) + x*f(x).diff(x) + (a**2*x**2 - b**2)*f(x)
dsolve(ode)
```

we get 

> f(x) = C₁⋅besselj(b, a⋅x) + C₂⋅bessely(b, a⋅x)

But, if we replace a² by a²/c²

```python
from sympy import symbols, dsolve, Function
x = symbols("x")
f = symbols("f", cls=Function)
a, b, c = symbols("a b c", positive=True)
ode = x**2*f(x).diff(x, 2) + x*f(x).diff(x) + (a**2*x**2/c**2 - b**2)*f(x)
sol = dsolve(ode)
```

we get the following error

```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-8-15fc749c4263> in <module>
      4 a, b, c = symbols("a b c", positive=True)
      5 ode = x**2*f(x).diff(x, 2) + x*f(x).diff(x) + (a**2*x**2/c**2 - b**2)*f(x)
----> 6 sol = dsolve(ode)

C:\ProgramData\Anaconda3\lib\site-packages\sympy\solvers\ode.py in dsolve(eq, func, hint, simplify, ics, xi, eta, x0, n, **kwargs)
    677             # The key 'hint' stores the hint needed to be solved for.
    678             hint = hints['hint']
--> 679             return _helper_simplify(eq, hint, hints, simplify, ics=ics)
    680 
    681 def _helper_simplify(eq, hint, match, simplify=True, ics=None, **kwargs):

C:\ProgramData\Anaconda3\lib\site-packages\sympy\solvers\ode.py in _helper_simplify(eq, hint, match, simplify, ics, **kwargs)
    702         # attempt to solve for func, and apply any other hint specific
    703         # simplifications
--> 704         sols = solvefunc(eq, func, order, match)
    705         if isinstance(sols, Expr):
    706             rv =  odesimp(eq, sols, func, hint)

C:\ProgramData\Anaconda3\lib\site-packages\sympy\solvers\ode.py in ode_2nd_power_series_regular(eq, func, order, match)
   4338             indicial.append(term)
   4339         else:
-> 4340             term = series(term, n=1, x0=x0)
   4341             if isinstance(term, Order):
   4342                 indicial.append(S.Zero)

C:\ProgramData\Anaconda3\lib\site-packages\sympy\series\series.py in series(expr, x, x0, n, dir)
     63     """
     64     expr = sympify(expr)
---> 65     return expr.series(x, x0, n, dir)

C:\ProgramData\Anaconda3\lib\site-packages\sympy\core\expr.py in series(self, x, x0, n, dir, logx)
   2789                 return self
   2790             elif len(syms) > 1:
-> 2791                 raise ValueError('x must be given for multivariate functions.')
   2792             x = syms.pop()
   2793 

ValueError: x must be given for multivariate functions.
``` 

I understand that the solver might fail to classify the equation and returns that it is ``Not Implemented`` but this seems like a bug to me

**Comment by asmeurer** [comment] 2020-05-15 05:15
Looks like this is fixed in 1.6 because bessel solvers are implemented. However, if you manually pass `hint='2nd_power_series_regular'` the bug is still there with that solver. 

Also, I don't know if this has been fixed, but I don't think series solutions should be returned by default without the user explicitly passing a flag (perhaps a message about it can be added to the NotImplementedError).

**Comment by nathanielatom** [comment] 2023-11-10 21:51
Is it possible to pass a flag to to `dsolve` to indicate the bessel solver should be used?

**Comment by oscarbenjamin** [comment] 2023-11-10 22:04
The Bessel solver should just be improved to handle this case:
https://github.com/sympy/sympy/blob/7319239ec8d75d01a3ce37e2599c1965fcb3a38a/sympy/solvers/ode/single.py#L2669-L2773

**Comment by asmeurer** [comment] 2023-11-10 22:44
You can pass the `hint` flag to dsolve, but it won't help here because it still needs to be able to match the ODE in order to extract the coefficients for the solver. You could manually call the internal bessel solver function with the corresponding coefficients. That would involve calling the internal solver functions. As Oscar notes, it would be best to just fix the bessel matcher. A good start would be to run through the code that Oscar linked to see where the match fails.

**Comment by asmeurer** [comment] 2023-11-10 22:53
The problem is here https://github.com/sympy/sympy/blob/7319239ec8d75d01a3ce37e2599c1965fcb3a38a/sympy/solvers/ode/single.py#L2756-L2762

`r[c3]` is `(a**2*x**2 - b**2*c**2)/c**2`. The match against `a - b` just makes the `b = 0`. It isn't recognizing it as a subtraction because of the `c**2` in the denominator. Probably the simplest fix would be to add an `expand` call to `r[c3]` before calling `match` (or maybe more conservatively `expand_mul`).

```diff
/keywords.html#keyword-namespace-packages
diff --git a/sympy/solvers/ode/single.py b/sympy/solvers/ode/single.py
index f0ca40a927..7d46931122 100644
--- a/sympy/solvers/ode/single.py
+++ b/sympy/solvers/ode/single.py
@@ -2753,7 +2753,7 @@ def _matches(self):
             # c3 maybe of very complex form so I am simply checking (a - b) form
             # if yes later I will match with the standerd form of bessel in a and b
             # a, b are wild variable defined above.
-            _coeff2 = r[c3].match(a - b)
+            _coeff2 = expand(r[c3]).match(a - b)
             if _coeff2 is None:
                 return False
             # matching with standerd form for c3
```

Ideally these sorts of things would be handled by the pattern matcher so we don't have to call `expand` and `factor` all over the place in matching code. But improving SymPy's pattern matching is a much more involved problem.

**Comment by sancho-s** [comment] 2024-01-25 10:02
This appears solved in https://github.com/sympy/sympy/pull/21241

**Comment by oscarbenjamin** [comment] 2024-01-25 10:25
Current error:
```
In [1]: from sympy import symbols, dsolve, Function
   ...: x = symbols("x")
   ...: f = symbols("f", cls=Function)
   ...: a, b, c = symbols("a b c", positive=True)
   ...: ode = x**2*f(x).diff(x, 2) + x*f(x).diff(x) + (a**2*x**2/c**2 - b**2)*f(x)
   ...: sol = dsolve(ode)
---------------------------------------------------------------------------
TypeError
...
File ~/current/active/sympy/sympy/solvers/ode/ode.py:2530, in ode_2nd_power_series_regular(eq, func, order, match)
   2527     m1, m2 = m2, m1
   2528 # Irrespective of whether m1 - m2 is an integer or not, one
   2529 # Frobenius series solution exists.
-> 2530 serdict1 = _frobenius(terms-m1-1, m1, p0, q0, p, q, x0, x, C0)
   2531 if not (m1 - m2).is_integer:
   2532     # Second frobenius series solution exists.
   2533     serdict2 = _frobenius(terms-m2-1, m2, p0, q0, p, q, x0, x, C1)

File ~/current/active/sympy/sympy/solvers/ode/ode.py:2559, in _frobenius(n, m, p0, q0, p, q, x0, x, c, check)
   2555 def _frobenius(n, m, p0, q0, p, q, x0, x, c, check=None):
   2556     r"""
   2557     Returns a dict with keys as coefficients and values as their values in terms of C0
   2558     """
-> 2559     n = int(n)
   2560     # In cases where m1 - m2 is not an integer
   2561     m2 = check

File ~/current/active/sympy/sympy/core/expr.py:307, in Expr.__int__(self)
    305 def __int__(self):
    306     if not self.is_number:
--> 307         raise TypeError("Cannot convert symbols to int")
    308     r = self.round(2)
    309     if not r.is_Number:

TypeError: Cannot convert symbols to int
```
The error comes from power series solver. We should change `dsolve` so that it does not fall back to power series solutions (gh-15916).

Also there seem to be a bug in the power series solver in that it is trying to convert a symbol to an int.

The original problem though is just that the Bessel solver fails to match the ODE. The diff as shown by Aaron above seems to fix that:
```python
In [1]: from sympy import symbols, dsolve, Function
   ...: x = symbols("x")
   ...: f = symbols("f", cls=Function)
   ...: a, b, c = symbols("a b c", positive=True)
   ...: ode = x**2*f(x).diff(x, 2) + x*f(x).diff(x) + (a**2*x**2/c**2 - b**2)*f(x)
   ...: sol = dsolve(ode)

In [2]: sol
Out[2]: 
                 ⎛   a⋅x⎞             ⎛   a⋅x⎞
f(x) = C₁⋅besselj⎜b, ───⎟ + C₂⋅bessely⎜b, ───⎟
                 ⎝    c ⎠             ⎝    c ⎠

In [3]: ode
Out[3]: 
    2                       ⎛ 2  2     ⎞     
 2 d             d          ⎜a ⋅x     2⎟     
x ⋅───(f(x)) + x⋅──(f(x)) + ⎜───── - b ⎟⋅f(x)
     2           dx         ⎜  2       ⎟     
   dx                       ⎝ c        ⎠     

In [4]: checkodesol(ode, sol)
Out[4]: (True, 0)
```

The diff above plus a tet can fix this issue.

**Closed** 2024-02-03 11:17 UTC
Labels: Easy to Fix, solvers.dsolve

**Comment by oscarbenjamin** [comment] 2024-02-03 11:21
The example is fixed now but I still don't like the expressions produced when the symbols are not declared positive:
```python
In [1]: from sympy import symbols, dsolve, Function
   ...: x = symbols("x")
   ...: f = symbols("f", cls=Function)
   ...: a, b, c = symbols("a b c")
   ...: ode = x**2*f(x).diff(x, 2) + x*f(x).diff(x) + (a**2*x**2/c**2 - b**2)*f(x)
   ...: dsolve(ode)
Out[1]: 
                 ⎛                 ____⎞             ⎛                 ____⎞
                 ⎜   ____         ╱  2 ⎟             ⎜   ____         ╱  2 ⎟
                 ⎜  ╱  2         ╱  a  ⎟             ⎜  ╱  2         ╱  a  ⎟
f(x) = C₁⋅besselj⎜╲╱  b  , x⋅   ╱   ── ⎟ + C₂⋅bessely⎜╲╱  b  , x⋅   ╱   ── ⎟
                 ⎜             ╱     2 ⎟             ⎜             ╱     2 ⎟
                 ⎝           ╲╱     c  ⎠             ⎝           ╲╱     c  ⎠
```
I think that e.g. `sqrt(b**2)` can just be `b` in the solution which would be a lot better.

Wikipedia gives this as the standard form for the Bessel ODE:
```python
In [2]: alpha = symbols('alpha')

In [3]: eq = x**2*f(x).diff(x, 2) + x*f(x).diff(x) + (x**2 - alpha**2)*f(x)

In [4]: eq
Out[4]: 
    2                                       
 2 d             d          ⎛   2    2⎞     
x ⋅───(f(x)) + x⋅──(f(x)) + ⎝- α  + x ⎠⋅f(x)
     2           dx                         
   dx                                       

In [5]: dsolve(eq)
Out[5]: 
                 ⎛   ____   ⎞             ⎛   ____   ⎞
                 ⎜  ╱  2    ⎟             ⎜  ╱  2    ⎟
f(x) = C₁⋅besselj⎝╲╱  α  , x⎠ + C₂⋅bessely⎝╲╱  α  , x⎠
```
Although in general `sqrt(a**2)` is not necessarily `a` I think that in the context of generating the solution to the Bessel equation it would be valid to use `a` instead of `sqrt(a**2)`. Probably both general solutions represent the same set of functions but I might be wrong.
