### ISSUE TITLE
TypeError in evalf with chop=True

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#18516] opened 2020-01-30 07:56 UTC
`log(3273390607896141870013189696827599152216642046043064789483291368096133796404674554883270092325904157150886684127560071009217256545885393053328527589376/36360291795869936842385267079543319118023385026001623040346035832580600191583895484198508262979388783308179702534403855752855931517013066142992430916562025780021771247847643450125342836565813209972590371590152578728008385990139795377610001).evalf(chop=True, n=15)` raises `TypeError`. Without `chop` it works.

**Comment by sylee957** [comment] 2020-01-30 08:26
It works in my computer.

**Comment by smichr** [comment] 2020-01-30 19:56
Yes. Fails at live.sympy.org (running an older version of SymPy) but passes at repl.it running Python3 and SymPy 1.5.1.

**Comment by gschintgen** [comment] 2020-01-30 19:56
I can't reproduce this either, neither with 1.5, nor master.
I'm closing this issue; feel free to re-open if you think there's more to it.

In that case, **please** copy & paste the exact input and output, including the traceback.
```
In [10]: log(327339060789614187001318969682759915221664204604306478948329136809613379640467455488327009232590415715088668412756007100921725
6545885393053328527589376/36360291795869936842385267079543319118023385026001623040346035832580600191583895484198508262979388783308
1797025344038557528559315170130661429924309165620257800217712478476434501253428365658132099725903715901525787280083859901397953776
10001).evalf(chop=True, n=15)
Out[10]: -202.732554054082
```

**Comment by asmeurer** [comment] 2020-01-30 20:08
SymPy Live converts Python integers to SymPy integers automatically. This issue appears on SymPy master.

```py
>>> log(S(3273390607896141870013189696827599152216642046043064789483291368096133796404674554883270092325904157150886684127560071009217256545885393053328527589376)/363602
... 917958699368423852670795433191180233850260016230403460358325806001915838954841985082629793887833081797025344038557528559315170130661429924309165620257800217712478476
... 43450125342836565813209972590371590152578728008385990139795377610001).evalf(15, chop=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "./sympy/core/evalf.py", line 1447, in evalf
    result = evalf(self, prec + 4, options)
  File "./sympy/core/evalf.py", line 1314, in evalf
    r = rf(x, prec, options)
  File "./sympy/core/evalf.py", line 850, in evalf_log
    imaginary_term = (mpf_cmp(xre, fzero) < 0)
  File "/Users/aaronmeurer/anaconda3/lib/python3.7/site-packages/mpmath/libmp/libmpf.py", line 581, in mpf_cmp
    ssign, sman, sexp, sbc = s
TypeError: cannot unpack non-iterable NoneType object
```

**Comment by gschintgen** [comment] 2020-01-30 20:26
My message must have crossed @smichr 's comment. I didn't check SymPy Live.

**Closed** 2021-03-13 23:59 UTC
Labels: core.evalf
