### ISSUE TITLE
def __nonzero__(self): raise TypeError("cannot determine truth value of Relational")

### ISSUE THREAD

**Issue by monacv** [sympy/sympy#20690] opened 2020-12-28 22:20 UTC
I am running a piece of code in Jupyter notebook and got the following error (even after changing `and` to `&` and `or` to `|`). So I decided to print the values of x2D and y2D but the error now shows right on the print statement. 

Could you please guide how to fix this issue?
```
    if radius is not None:
        value = {t1: _t1, t2: _t2, t3: _t3, x_mid: _x_mid, theta: _theta, focal_length: _focal_length, vec_20: vec_2[0],
                 vec_21: vec_2[1], vec_22: vec_2[2], r: radius}
        for i in range(4):
            ansx = root1[i][0].evalf(subs=value)
            ansy = root1[i][1].evalf(subs=value)
            ansz = root1[i][2].evalf(subs=value)
            y2D = (-ansy + _t2) / (ansz + _t3) * _focal_length
            x2D = (-ansx + _t1) / (ansz + _t3) * _focal_length
            print('y2D is: ', y2D)
            print('x2D is: ', x2D)
            if (((y2D >= obox[1]) & (y2D <= obox[3])) | ((y2D <= obox[1]) & (y2D >= obox[3]))):
                idx = i

```

Previously this is the line that threw an error (same as title): 
`            if (((y2D >= obox[1]) and (y2D <= obox[3])) or ((y2D <= obox[1]) and (y2D >= obox[3]))):`

Then following [this Stackoverflow answer](https://stackoverflow.com/a/61240409) by @sylee957 , I changed it to the following but no solution:
`            if (((y2D >= obox[1]) & (y2D <= obox[3])) | ((y2D <= obox[1]) & (y2D >= obox[3]))):`

After adding the print statements, seems the problem is coming from elsewhere.
```
            print('y2D is: ', y2D)
            print('x2D is: ', x2D)
```

The cell that I am running:
```

list_hoi, order_obj_list, obj_para_dict = get_order_obj()
htri       = trimesh.load(mesh)
vertice    = np.array(htri.vertices,dtype=np.float32)
joints     = get_joints(args, torch.FloatTensor(torch.from_numpy(vertice.reshape(1,-1,3))))
shoulder_len = np.linalg.norm(joints[16] - joints[17])
radius    = obj_para_dict[obj_name]['ratio'] * shoulder_len
gamma_min = obj_para_dict[obj_name]['gamma_min']
gamma_max = obj_para_dict[obj_name]['gamma_max']
otri, _   = get_param(result, hbox, obox, htri, img, radius, gamma_min, gamma_max)
config    = htri + otri
ansp = rotate(joints - joints[0])
vertices = np.array(config.vertices)
vertices = vertices - joints[0]
vertices = rotate_mul(vertices, ansp)
config = trimesh.Trimesh(vertices=vertices, faces=config.faces)
_ = config.export('demo/config.obj')


```

Here's the error I get after running the cell:
```

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-1f1789b8332d> in <module>
      7 gamma_min = obj_para_dict[obj_name]['gamma_min']
      8 gamma_max = obj_para_dict[obj_name]['gamma_max']
----> 9 otri, _   = get_param(result, hbox, obox, htri, img, radius, gamma_min, gamma_max)
     10 config    = htri + otri
     11 ansp = rotate(joints - joints[0])

~/research/code/DJ-RN/script/generate_utils.py in get_param(result, hbox, obox, htri, img, radius, gamma_min, gamma_max)
    246             y2D = (-ansy + _t2) / (ansz + _t3) * _focal_length
    247             x2D = (-ansx + _t1) / (ansz + _t3) * _focal_length
--> 248             print('y2D is: ', y2D)
    249             print('x2D is: ', x2D)
    250             if (((y2D >= obox[1]) & (y2D <= obox[3])) | ((y2D <= obox[1]) & (y2D >= obox[3]))):

~/anaconda3/lib/python3.8/site-packages/sympy/core/relational.py in __nonzero__(self)
    382 
    383     def __nonzero__(self):
--> 384         raise TypeError("cannot determine truth value of Relational")
    385 
    386     __bool__ = __nonzero__

TypeError: cannot determine truth value of Relational

```
![Screenshot from 2020-12-28 17-19-59](https://user-images.githubusercontent.com/76495162/103246283-ed189080-4930-11eb-9833-5159973ac797.png)

I also created an issue for the original code I ran from this repo: https://github.com/DirtyHarryLYL/DJ-RN/issues/16 

Also, 

```
[13037:2264 0:878] 05:23:50 Mon Dec 28 [mona@goku:pts/1 +1] ~/research/code/DJ-RN
$ rg sympy
script/generate_utils.py
8:import sympy, math
221:    x = sympy.Symbol('x', real=True)
222:    y = sympy.Symbol('y', real=True)
223:    z = sympy.Symbol('z', real=True)
224:    t1 = sympy.Symbol('t1', real=True)
225:    t2 = sympy.Symbol('t2', real=True)
226:    t3 = sympy.Symbol('t3', real=True)
227:    x_mid = sympy.Symbol('x_mid', real=True)
228:    theta = sympy.Symbol('theta', real=True)
229:    focal_length = sympy.Symbol('focal_length', real=True)
230:    vec_20 = sympy.Symbol('vec_20', real=True)
231:    vec_21 = sympy.Symbol('vec_21', real=True)
232:    vec_22 = sympy.Symbol('vec_22', real=True)
233:    r = sympy.Symbol('r', real=True)

script/Demo.ipynb
88:      "\u001b[0;32m~/anaconda3/lib/python3.8/site-packages/sympy/core/relational.py\u001b[0m in \u001b[0;36m__nonzero__\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    382\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    383\u001b[0m     \u001b[0;32mdef\u001b[0m \u001b[0m__nonzero__\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 384\u001b[0;31m         \u001b[0;32mraise\u001b[0m \u001b[0mTypeError\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"cannot determine truth value of Relational\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    385\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    386\u001b[0m     \u001b[0m__bool__\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0m__nonzero__\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",

requirements_data.txt
132:sympy=1.4=py37_0

```

Here's my sympy version:

```
$ python
Python 3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sympy
>>> sympy.__version__
'1.6.2'
```

**Comment by monacv** [comment] 2020-12-28 22:52
I create a Python script to run this:

```
[13037:2264 0:910] 05:51:47 Mon Dec 28 [mona@goku:pts/1 +1] ~/research/code/DJ-RN/script
$ cat test.py 
import os
import os.path as osp
import numpy as np
import pickle
import trimesh
import torch
from generate_utils import get_order_obj, get_joints, get_param, point_align_vis, rotate, rotate_mul

class Arguments():
    def __init__(self, gender, smplx_path):
        self.gender     = gender
        self.smplx_path = smplx_path


args     = Arguments(gender='male', smplx_path='/home/mona/research/code/DJ-RN/models/smplx/')
obj_name = 'keyboard'
result   = pickle.load(open('demo/result.pkl', 'rb'))
hbox     = pickle.load(open('demo/hbox.pkl', 'rb'))
obox     = pickle.load(open('demo/obox.pkl', 'rb'))
mesh       = 'demo/human.obj'
img        = 'demo/sample.jpg'


list_hoi, order_obj_list, obj_para_dict = get_order_obj()
htri       = trimesh.load(mesh)
vertice    = np.array(htri.vertices,dtype=np.float32)
joints     = get_joints(args, torch.FloatTensor(torch.from_numpy(vertice.reshape(1,-1,3))))
shoulder_len = np.linalg.norm(joints[16] - joints[17])
radius    = obj_para_dict[obj_name]['ratio'] * shoulder_len
gamma_min = obj_para_dict[obj_name]['gamma_min']
gamma_max = obj_para_dict[obj_name]['gamma_max']
otri, _   = get_param(result, hbox, obox, htri, img, radius, gamma_min, gamma_max)
config    = htri + otri
ansp = rotate(joints - joints[0])
vertices = np.array(config.vertices)
vertices = vertices - joints[0]
vertices = rotate_mul(vertices, ansp)
config = trimesh.Trimesh(vertices=vertices, faces=config.faces)
_ = config.export('demo/config.obj')


point_align_vis(result, hbox, 'demo/human.obj', img)
point_align_vis(result, obox, 'demo/object.obj', img)
```



Here's the updated error:
```

y2D is:  5000*(0.321072 - (focal_length*t2*sin(theta/2)*Abs(focal_length**2*vec_21**2 + focal_length**2*vec_22**2 + 2*focal_length*vec_20*vec_22*x_mid + vec_20**2*x_mid**2 + vec_21**2*x_mid**2) + ((-2.0*t3*(focal_length**2 + x_mid**2)*(focal_length**2*vec_22*(vec_20**2 + vec_21**2 + vec_22**2)**0.5*cos(theta/2)*Abs(r) + 1.4142135623731*focal_length*r*vec_21*(0.5*focal_length**2*vec_20**2*sin(theta/2)**2 - 0.5*focal_length**2*vec_20**2 + 0.5*focal_length**2*vec_21**2*sin(theta/2)**2 + 0.5*focal_length**2*vec_22**2*sin(theta/2)**2 + focal_length*vec_20*vec_22*x_mid + 0.5*vec_20**2*x_mid**2*sin(theta/2)**2 + 0.5*vec_21**2*x_mid**2*sin(theta/2)**2 + 0.5*vec_22**2*x_mid**2*sin(theta/2)**2 - 0.5*vec_22**2*x_mid**2)**0.5 + focal_length*vec_20*x_mid*(vec_20**2 + vec_21**2 + vec_22**2)**0.5*cos(theta/2)*Abs(r) - t3*(focal_length**2*vec_21**2 + focal_length**2*vec_22**2 + 2.0*focal_length*vec_20*vec_22*x_mid + vec_20**2*x_mid**2 + vec_21**2*x_mid**2)*Abs(sin(theta/2)))*(focal_length**2*vec_21**2 + focal_length**2*vec_22**2 + 2.0*focal_length*vec_20*vec_22*x_mid + vec_20**2*x_mid**2 + vec_21**2*x_mid**2)*sin(theta/2)**2 - 2.0*(focal_length**2 + x_mid**2)*(0.707106781186547*focal_length**2*vec_22*(vec_20**2 + vec_21**2 + vec_22**2)**0.5*cos(theta/2)*Abs(r) + focal_length*r*vec_21*(0.5*focal_length**2*vec_20**2*sin(theta/2)**2 - 0.5*focal_length**2*vec_20**2 + 0.5*focal_length**2*vec_21**2*sin(theta/2)**2 + 0.5*focal_length**2*vec_22**2*sin(theta/2)**2 + focal_length*vec_20*vec_22*x_mid + 0.5*vec_20**2*x_mid**2*sin(theta/2)**2 + 0.5*vec_21**2*x_mid**2*sin(theta/2)**2 + 0.5*vec_22**2*x_mid**2*sin(theta/2)**2 - 0.5*vec_22**2*x_mid**2)**0.5 + 0.707106781186547*focal_length*vec_20*x_mid*(vec_20**2 + vec_21**2 + vec_22**2)**0.5*cos(theta/2)*Abs(r) - 0.707106781186547*t3*(focal_length**2*vec_21**2 + focal_length**2*vec_22**2 + 2.0*focal_length*vec_20*vec_22*x_mid + vec_20**2*x_mid**2 + vec_21**2*x_mid**2)*Abs(sin(theta/2)))**2*Abs(sin(theta/2)) + 4.0*(focal_length**2*r**2 - focal_length**2*t3**2*sin(theta/2)**2 - t3**2*x_mid**2*sin(theta/2)**2)*(0.5*focal_length**2*vec_21**2 + 0.5*focal_length**2*vec_22**2 + focal_length*vec_20*vec_22*x_mid + 0.5*vec_20**2*x_mid**2 + 0.5*vec_21**2*x_mid**2)**2*Abs(sin(theta/2)))/Abs(sin(theta/2)))**0.5)/(focal_length*sin(theta/2)*Abs(focal_length**2*vec_21**2 + focal_length**2*vec_22**2 + 2*focal_length*vec_20*vec_22*x_mid + vec_20**2*x_mid**2 + vec_21**2*x_mid**2)))/((focal_length**2*vec_22*(vec_20**2 + vec_21**2 + vec_22**2)**0.5*cos(theta/2)*Abs(r) + 1.4142135623731*focal_length*r*vec_21*(0.5*focal_length**2*vec_20**2*sin(theta/2)**2 - 0.5*focal_length**2*vec_20**2 + 0.5*focal_length**2*vec_21**2*sin(theta/2)**2 + 0.5*focal_length**2*vec_22**2*sin(theta/2)**2 + focal_length*vec_20*vec_22*x_mid + 0.5*vec_20**2*x_mid**2*sin(theta/2)**2 + 0.5*vec_21**2*x_mid**2*sin(theta/2)**2 + 0.5*vec_22**2*x_mid**2*sin(theta/2)**2 - 0.5*vec_22**2*x_mid**2)**0.5 + focal_length*vec_20*x_mid*(vec_20**2 + vec_21**2 + vec_22**2)**0.5*cos(theta/2)*Abs(r) - t3*(focal_length**2*vec_21**2 + focal_length**2*vec_22**2 + 2.0*focal_length*vec_20*vec_22*x_mid + vec_20**2*x_mid**2 + vec_21**2*x_mid**2)*Abs(sin(theta/2)))/((focal_length**2*vec_21**2 + focal_length**2*vec_22**2 + 2.0*focal_length*vec_20*vec_22*x_mid + vec_20**2*x_mid**2 + vec_21**2*x_mid**2)*Abs(sin(theta/2))) + 23.578)
x2D is:  5000*(0.477802 - (-focal_length**2*t1*vec_21**2 - focal_length**2*t1*vec_22**2 - 2.0*focal_length*t1*vec_20*vec_22*x_mid + focal_length*vec_22*x_mid*(vec_20**2 + vec_21**2 + vec_22**2)**0.5*cos(theta/2)*Abs(r)/Abs(sin(theta/2)) + 1.4142135623731*r*vec_21*x_mid*(0.5*focal_length**2*vec_20**2*sin(theta/2)**2 - 0.5*focal_length**2*vec_20**2 + 0.5*focal_length**2*vec_21**2*sin(theta/2)**2 + 0.5*focal_length**2*vec_22**2*sin(theta/2)**2 + focal_length*vec_20*vec_22*x_mid + 0.5*vec_20**2*x_mid**2*sin(theta/2)**2 + 0.5*vec_21**2*x_mid**2*sin(theta/2)**2 + 0.5*vec_22**2*x_mid**2*sin(theta/2)**2 - 0.5*vec_22**2*x_mid**2)**0.5/Abs(sin(theta/2)) - t1*vec_20**2*x_mid**2 - t1*vec_21**2*x_mid**2 + vec_20*x_mid**2*(vec_20**2 + vec_21**2 + vec_22**2)**0.5*cos(theta/2)*Abs(r)/Abs(sin(theta/2)))/(focal_length**2*vec_21**2 + focal_length**2*vec_22**2 + 2.0*focal_length*vec_20*vec_22*x_mid + vec_20**2*x_mid**2 + vec_21**2*x_mid**2))/((focal_length**2*vec_22*(vec_20**2 + vec_21**2 + vec_22**2)**0.5*cos(theta/2)*Abs(r) + 1.4142135623731*focal_length*r*vec_21*(0.5*focal_length**2*vec_20**2*sin(theta/2)**2 - 0.5*focal_length**2*vec_20**2 + 0.5*focal_length**2*vec_21**2*sin(theta/2)**2 + 0.5*focal_length**2*vec_22**2*sin(theta/2)**2 + focal_length*vec_20*vec_22*x_mid + 0.5*vec_20**2*x_mid**2*sin(theta/2)**2 + 0.5*vec_21**2*x_mid**2*sin(theta/2)**2 + 0.5*vec_22**2*x_mid**2*sin(theta/2)**2 - 0.5*vec_22**2*x_mid**2)**0.5 + focal_length*vec_20*x_mid*(vec_20**2 + vec_21**2 + vec_22**2)**0.5*cos(theta/2)*Abs(r) - t3*(focal_length**2*vec_21**2 + focal_length**2*vec_22**2 + 2.0*focal_length*vec_20*vec_22*x_mid + vec_20**2*x_mid**2 + vec_21**2*x_mid**2)*Abs(sin(theta/2)))/((focal_length**2*vec_21**2 + focal_length**2*vec_22**2 + 2.0*focal_length*vec_20*vec_22*x_mid + vec_20**2*x_mid**2 + vec_21**2*x_mid**2)*Abs(sin(theta/2))) + 23.578)
Traceback (most recent call last):
  File "test.py", line 32, in <module>
    otri, _   = get_param(result, hbox, obox, htri, img, radius, gamma_min, gamma_max)
  File "/home/mona/research/code/DJ-RN/script/generate_utils.py", line 259, in get_param
    if (ansz > maxz or ansz < minz):          
  File "/home/mona/anaconda3/lib/python3.8/site-packages/sympy/core/relational.py", line 384, in __nonzero__
    raise TypeError("cannot determine truth value of Relational")
TypeError: cannot determine truth value of Relational

```

Also, 
```
$ vi /home/mona/research/code/DJ-RN/script/generate_utils.py


    if radius is not None:
        value = {t1: _t1, t2: _t2, t3: _t3, x_mid: _x_mid, theta: _theta, focal_length: _focal_length, vec_20: vec_2[0],
                 vec_21: vec_2[1], vec_22: vec_2[2], r: radius}
        for i in range(4):
            ansx = root1[i][0].evalf(subs=value)
            ansy = root1[i][1].evalf(subs=value)
            ansz = root1[i][2].evalf(subs=value)
            print('ansx is {}, ansy is {}, ansz is {}'.format(ansx, ansy, ansz))
            print(' _t1 is {}, _t2 is {}, _t3 is {}, and _focal_length is {}'.format(_t1, _t2, _t3, _focal_length))
            y2D = (-ansy + _t2) / (ansz + _t3) * _focal_length
            x2D = (-ansx + _t1) / (ansz + _t3) * _focal_length
            print('y2D is: ', y2D)
            print('x2D is: ', x2D)
            if (((y2D >= obox[1]) & (y2D <= obox[3])) | ((y2D <= obox[1]) & (y2D >= obox[3]))):
                idx = i

```

**Comment by oscarbenjamin** [comment] 2020-12-29 00:33
>     if (ansz > maxz or ansz < minz):

This will raise an error if the expressions have symbols in such that it isn't possible to determine the result e.g.:
```
In [13]: x = Symbol('x')

In [14]: x > 2
Out[14]: x > 2

In [15]: if x > 2: pass
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-15-ca9f57ba56b3> in <module>
----> 1 if x > 2: pass

~/current/sympy/sympy/sympy/core/relational.py in __bool__(self)
    393 
    394     def __bool__(self):
--> 395         raise TypeError("cannot determine truth value of Relational")
    396 
    397     def _eval_as_set(self):

TypeError: cannot determine truth value of Relational
```
You should inspect those variables to see what they are in order to debug this further.

Github issues are for reporting bugs with sympy. It's possible that your problem is caused by a bug in sympy but this description of the problem so far is not helpful for identifying or fixing that bug so I'm going to close this issue.

To ask for help with using sympy please use the mailing list: https://groups.google.com/g/sympy or otherwise stackoverflow.

**Closed by oscarbenjamin** 2020-12-29 00:33 UTC

**Comment by asmeurer** [comment] 2020-12-29 03:49
We can turn non-issue issues like this into discussions. I've done that. 

The error means that the inequality is indeterminate because one of the sides of it is symbolic. So it can't do anything with something like `if x > y:` when `x` and `y` are symbolic variables, because `x` could be greater than or not greater than `y`. 

The solution really depends on what you are trying to do. If you want the `if` block to not run when the inequality is indeterminate you can use something like `if (x > y) is True` (this would be more complicated for your example, but the idea is the same). Another option is to reframe what is in the `if` block symbolically using `Piecewise` (https://docs.sympy.org/latest/modules/functions/elementary.html#sympy.functions.elementary.piecewise.Piecewise), so that you have an expression that works symbolically for both cases (I can't understand your example well enough to say if this would work for it). For example, something like 

```py
if x > y:
    result = 1
else:
    result = 0
```

would be

```py
result = Piecewise((1, x > y), (0, True))
```
