### ISSUE TITLE
summation: Wrong out for non-integral range

### ISSUE THREAD

**Issue by hargup** [sympy/sympy#9358] opened 2015-04-30 13:14 UTC
```python
summation(1, (i, 1, Rational(5, 2)))
Out[9]: 5/2
```

The documentation says:
> ``Sum`` represents a finite or infinite series, with the first argument
being the general form of terms in the series, and the second argument
being ``(dummy_variable, start, end)``, with ``dummy_variable`` taking
all integer values from ``start`` through ``end``.

Hence, the output should be 2.

**Comment by leosartaj** [comment] 2015-05-01 13:12
I guess in this case, maybe sum should be returned unevaluated. I think it will be more consistent, if we do not automatically change the limits. @hargup

**Comment by asmeurer** [comment] 2015-05-02 20:25
There's been quite a bit of discussion about this sort of thing before. I think this is a dupe of https://github.com/sympy/sympy/issues/6756.

**Closed by asmeurer** 2015-05-02 20:25 UTC
Labels: concrete
