### ISSUE TITLE
sympy 1.6.1 ?

### ISSUE THREAD

**Issue by FabioLuporini** [sympy/sympy#19557] opened 2020-06-15 06:43 UTC
Hi, is there any plan on releasing 1.6.1, just like we had 1.5.1 shortly after 1.5? [We're unfortunately stuck with 1.5.1](https://github.com/devitocodes/devito/blob/master/requirements.txt#L3), but the patches we've submitted have already been merged into SymPy master, and we're looking forward to jump to 1.6. Thanks!

**Comment by oscarbenjamin** [comment] 2020-06-15 10:20
Which patches are you referring to?

**Comment by FabioLuporini** [comment] 2020-06-15 12:07
Strictly speaking, the only one we actually need is #19431 . #15933 is the other one (though this one is more of a "I'd really like to have it, but I can survive without for the time being)

**Comment by FabioLuporini** [comment] 2020-06-15 12:11
Note: edited my previous reply (wrong PR numbers before, now it should be fine)

**Comment by oscarbenjamin** [comment] 2020-06-15 12:30
The normal plan is we would only make a bugfix release (i.e. 1.6.1) if regressions were identified in 1.6 (relative to 1.5.1). Also 1.6.1 would be based off the 1.6 branch rather than master so any fixes need to be cherry-picked to that branch. It's important to say when opening an issue that represents a regression that it is a regression so that any fix could be included in a bugfix release.

Until now the only regression I knew of was #19532.

**Comment by FabioLuporini** [comment] 2020-06-15 12:45
#19431 was a regression AFAICT? apologies if it wasn't made clear in the PR description. Looping in @mloubout (who wrote the actual patch)

**Comment by mloubout** [comment] 2020-06-15 13:04
Yes this was a regression, I apologize if I haven't tagged it correctly, I tried to follow the guidelines but was the first time I PRed into sympy so I may have missed some parts.
As @FabioLuporini this is somethign that forces us to be fixed at `1.5.1` as this is an issue that make ``1.6` unusable for us due to the presence of the `Dummy` object after collection.

**Comment by oscarbenjamin** [comment] 2020-06-15 18:12
No need to apologise. It's just best to explicitly say if something is a regression and since what version.

We can do a 1.6.1 release but I think we need a fix for #19532 first.

**Comment by oscarbenjamin** [comment] 2020-06-20 11:17
I've start preparing for the release (#19598). The issue tracking the release is #19599

**Comment by oscarbenjamin** [comment] 2020-06-20 11:23
#19601 applies #19431 to the 1.6 branch for release in 1.6.1 and will close this issue.

**Closed** 2020-06-20 14:20 UTC
