### ISSUE TITLE
help(latex()) - Wrong docstring

### ISSUE THREAD

**Issue by Davide-sd** [sympy/sympy#20231] opened 2020-10-09 10:47 UTC
I'm trying Sympy v1.7.0 dev. If I use:

```
help(latex)
```

I get the docstring of the `_PrintFunction` class. To see the actual docstring I have to use `latex?`. This is quite inconvenient.

**Comment by oscarbenjamin** [comment] 2020-10-09 11:11
I tried `help(latex)` and got:
```
Help on _PrintFunction in module sympy.printing.latex:

latex = <function latex>
    Convert the given expression to LaTeX string representation.
    
    Parameters
    ==========
    full_prec: boolean, optional
        If set to True, a floating point number is printed with full precision.
    fold_frac_powers : boolean, optional
        Emit ``^{p/q}`` instead of ``^{\frac{p}{q}}`` for fractional powers.
    fold_func_brackets : boolean, optional
    ...
```
So the first line says "help on _PrintFunction..." but the rest is the docstring.

I think maybe there should be `@wraps` here:
https://github.com/sympy/sympy/blob/f03e8d2bde363a3351bd55d02f6a7cb51fe179e9/sympy/printing/printer.py#L381-L385

**Comment by Davide-sd** [comment] 2020-10-09 11:14
This is my output to `help(latex)`:

```
Help on _PrintFunction in module sympy.printing.latex object:

latex = class _PrintFunction(builtins.object)
 |  Function wrapper to replace ``**settings`` in the signature with printer defaults
 |  
 |  Methods defined here:
 |  
 |  __call__(self, *args, **kwargs)
 |      Call self as a function.
 |  
 |  __init__(self, f, print_cls: Type[sympy.printing.printer.Printer])
 |      Initialize self.  See help(type(self)) for accurate signature.
 |  
 |  __repr__(self) -> str
 |      Return repr(self).
 |  
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |  
 |  __dict__
 |      dictionary for instance variables (if defined)
 |  
 |  __signature__
 |  
 |  __weakref__
 |      list of weak references to the object (if defined)
```

**Comment by oscarbenjamin** [comment] 2020-10-09 11:21
What environment are you using?

I tried with isympy and in the plan Python repl and got the same result I showed above both times.

**Comment by Davide-sd** [comment] 2020-10-09 11:23
Standard Jupyter notebook on an environment created with venv.

**Comment by asmeurer** [comment] 2020-10-09 17:12
I get the same thing as @Davide-sd. I think the print_function decorator needs to use functools.wraps so that it can inherit things like the docstring.

**Comment by asmeurer** [comment] 2020-10-09 17:38
Though _PrintFunction is defining things like `__signature__`, which functools.wraps also overrides. So it may have to be done manually.

**Comment by sayandip18** [comment] 2020-10-09 21:51
In `latex.py` we have
https://github.com/sympy/sympy/blob/524fa229306898fded1d477017e0a88048d88c6b/sympy/printing/latex.py#L2711-L2712
 
This probably means the function is called like this(?) `latex = (print_function(LatexPrinter))(latex)`

So, `LatexPrinter` is assigned to `print_cls`  and `latex` to `f`, am I right? 
https://github.com/sympy/sympy/blob/524fa229306898fded1d477017e0a88048d88c6b/sympy/printing/printer.py#L381-L385

**Comment by asmeurer** [comment] 2020-10-23 21:20
So it is using `update_wrapper`. The problem is that `latex` is the update_wrapper puts `__doc__` as an instance variable, whereas it is usually a class variable, which `help()` expects. The same problem occurs with 

```py
>>> class Test:
...     def __init__(self):
...         self.__doc__ = 'docstring'
>>> help(Test())
```

**Comment by asmeurer** [comment] 2020-10-23 21:56
Fix at https://github.com/sympy/sympy/pull/20328.

**Comment by eric-wieser** [comment] 2020-10-23 23:11
Note that this is exactly the same behavior as `help(np.sin)`, which also does not emit useful help.

**Comment by oscarbenjamin** [comment] 2020-10-23 23:31
Why doesn't help work with e.g. `np.sin`. I see that `__doc__` is there and is informative.

**Comment by eric-wieser** [comment] 2020-10-23 23:34
It's exactly the same problem - it's not a true function, but a class instance that defines `__call__`

**Comment by oscarbenjamin** [comment] 2020-10-24 00:12
I thought help just looked up the `__doc__` attribute. Looking here
https://docs.python.org/3/library/functions.html#help
I see that the description is quite vague...

**Comment by asmeurer** [comment] 2020-10-24 01:24
I only found out that that's the behavior by stepping through help() with a debugger. It would be better if it did work on instance `__doc__`. I guess that's an upstream cpython issue. At any rate, that's how it works and the fix here is simple enough to avoid breaking things. And even if it wasn't, would rather have working help() than signature information.

**Comment by eric-wieser** [comment] 2020-10-24 05:54
I'll review your patch shortly.

> would rather have working help() than signature information.

I actually disagree with this. Signature information means that both Sphinx and IPython are as useful as possible. As someone who never uses `help` and always uses Google or `?`, this issue doesn't impact me at all. I don't know how typical a user I am though.

**Comment by eric-wieser** [comment] 2020-10-24 05:57
> I tried with isympy and in the plan Python repl and got the same result I showed above both times.

@oscarbenjamin, are you perhaps on a Python 3.9 prerelease?

**Comment by oscarbenjamin** [comment] 2020-10-24 10:42
I guess I was using 3.9. I have several Python's installed and switch between them so I'm not sure what I was using then. In Python 3.9.0 (not a prerelease) this issue doesn't appear.

**Comment by eric-wieser** [comment] 2020-10-24 10:48
https://bugs.python.org/issue40257 I think tracks the change here.

**Comment by eric-wieser** [comment] 2020-10-24 10:56
Sure enough, it's a 3.9 feature: https://docs.python.org/3/whatsnew/3.9.html#pydoc

**Closed** 2021-09-06 20:02 UTC
Labels: printing
