### ISSUE TITLE
binomial(-1, -1) returns 0, should return 1

### ISSUE THREAD

**Issue by agryman** [sympy/sympy#23497] opened 2022-05-14 20:49 UTC
I am in the process of converting some nuclear physics code from Maple to SymPy and I ran into a bug which I traced to the behaviour of the binomial coefficient function. Specifically:

Maple: binomial(-1, -1) = 1
SymPy: binomial(-1, -1) = 0

The SymPy docs for binomial(n, k) state: For the sake of convenience for negative integer k this function will return zero no matter what valued is the other argument.
See https://docs.sympy.org/latest/modules/functions/combinatorial.html#binomial

Therefore, the code is working as described. However, it is not mathematically correct. The Maple result is correct. Here's the reasoning.

For all n, k, we must have:
binomial(n, k) = binomial(n, n - k)

Therefore:
binomial(-1, -1) = binomial(-1, -1 - (-1)) = binomial(-1, 0)

The generalized definition for binomial(n, k) given in in the SymPy docs uses the falling factorial function, ff(n, k):
binomial(n, k) = ff(n, k)/k!

By definition of ff(n, k) we have ff(n, 0) = 1 for all n.
Therefore binomial(-1, 0) = ff(-1, 0)/0! = 1/1 = 1.

I think it is appropriate to correct this behavior for integer arguments. I understand that this changes the behaviour and could potentially break existing code, but that is probably doubtful. However, if you really want to preserve this behaviour, perhaps you could create a new function that handles the case of negative k "correctly"?

fyi, the Maple docs explain how binomial(n, k) should be extended to complex arguments. I'd be happy to share that if there is interest.

**Comment by oscarbenjamin** [comment] 2022-05-14 21:52
The numeric evaluation of binomial already seems to behave the way that you suggest so there is an immediate inconsistency:
```python
In [4]: b = binomial(-1, -1, evaluate=False)

In [5]: b
Out[5]: 
⎛-1⎞
⎜  ⎟
⎝-1⎠

In [6]: b.evalf()
Out[6]: 1.00000000000000

In [7]: b.doit()
Out[7]: 0
```

**Comment by agryman** [comment] 2022-05-15 16:16
@oscarbenjamin @praneethratna Thanks for the quick resolution.

**Comment by oscarbenjamin** [comment] 2022-05-15 17:28
I don't think this is resolved yet. There needs to be come discussion about changing this. I vaguely remember extensive discussions already happened. Probably in #18960 if anyone can find the time to read through that...

**Comment by asmeurer** [comment] 2022-05-15 19:11
To summarize that PR, there are two different ways to extend the binomial function to negative arguments. SymPy chooses a different convention from the one you are expecting. I believe the current consensus in that PR was to add a separate class that allows you to use the other convention. We also need to document the two conventions so that people understand what is going on. There are more details in https://github.com/sympy/sympy/issues/14577. This issue is effectively a duplicate of that one, so I'm going to close it. 

I agree that the numerical evaluation should be fixed so that it is consistent.

**Closed by asmeurer** 2022-05-15 19:11 UTC
Labels: functions
