### ISSUE TITLE
Simplifying And boolean operation removes a condition

### ISSUE THREAD

**Issue by Teskann** [sympy/sympy#25603] opened 2023-08-29 12:01 UTC
Hi,

Simplifying a Piecewise with boolean operations results in the wrong simplification:

Here is what I get from Sympy live shell entering

```python
parse_expr("Piecewise((log(x), (x <= 5) & (x > 3)), (x, True))")
```
 vs 
```python
parse_expr("Piecewise((log(x), (x <= 5) & (x > 3)), (x, True))").simplify()
```

![image](https://github.com/sympy/sympy/assets/47865674/ae40c955-d41b-415f-8296-21e2d1a56d0a)

As you can see, the simplified expression removes a condition on `x`: `x>3` has disappeared despite it's not implied by `x <= 5` (e.g., 0 is less than 5 but not greater than 3).

**Comment by oscarbenjamin** [comment] 2023-08-30 18:09
This is a regression that I have bisected to 3dae580d4df6991fa2962efe11dfec8ec786c55f from gh-22751

**Comment by oscarbenjamin** [comment] 2023-08-30 18:10
I have not further investigated the causes. Someone would need to either study the code identified in that commit or follow through in a debugger to see what is happening.

**Comment by oscarbenjamin** [comment] 2023-08-30 18:51
Actually this is a straight-forward bug that is easy to fix. The `incl_b`  case here does not use `And`:
https://github.com/sympy/sympy/blob/aaf4a74e9fbe4ba6f3263840286c95bb98438e13/sympy/functions/elementary/piecewise.py#L1175-L1198
The fix is just:
```diff
diff --git a/sympy/functions/elementary/piecewise.py b/sympy/functions/elementary/piecewise.py
index 629f59ec38..18b1cfcc9b 100644
--- a/sympy/functions/elementary/piecewise.py
+++ b/sympy/functions/elementary/piecewise.py
@@ -1190,7 +1190,7 @@ def include(c, x, a):
                     if b.is_infinite:
                         c = (x > a)
                     else:
-                        c = (x <= b)
+                        c = And(a < x, x <= b)
                 else:
                     if a in covered:
                         c = (x < b)
```
I'm marking this as easy to fix. A PR with the change shown and also a test added in `sympy/functions/elementary/tests/test_piecewise.py` can fix this.

**Comment by geetHonve** [comment] 2023-08-31 05:34
I am working on it

**Closed** 2023-08-31 20:54 UTC
Labels: Easy to Fix, simplify, good first issue, functions.elementary.piecewise
