### ISSUE TITLE
Error in handling reciprocal square root in integral containing Fresnel functions

### ISSUE THREAD

**Issue by sebtiburzio** [sympy/sympy#25093] opened 2023-04-27 15:13 UTC
Transferring this from my [stackoverflow question](https://stackoverflow.com/questions/76114428/handling-reciprocals-of-negative-square-roots-in-sympy), as I was informed it is indeed a SymPy bug.

**Issue:** When performing the below integration, the result has a factor of `1/sqrt(b)` instead of `sqrt(1/b)` in the Fresnel integral arguments, which results in an additional factor of -1 when b < 0.
```
import sympy as sm
a,b,x = sm.symbols('a b x')
f = sm.integrate(sm.cos(a*x + 0.5*b*x**2),(x,0,1))

f.subs([(a,1),(b,1e-9)]).evalf()
# =0.84147
f.subs([(a,1),(b,-1e-9)]).evalf()
# =−0.84147
```

**Cause:** I am not familiar enough to know myself, but appears to be a problem with how the expression is constructed in the integration rule, or a simplification applied to it. As mentioned by SO users, these substitutions result in an expression with the expected behaviour:
```
f.subs(1/sqrt(b),sqrt(1/b))
f.subs(sqrt(1/b),1/sqrt(b))
```

(Python 3.11.2, SymPy 1.11.1)

**Comment by oscarbenjamin** [comment] 2023-04-27 15:50
The problem is the integration rules in manual integrate which use factors of `sqrt(pi/a)` rather than `sqrt(pi)/sqrt(a)`. To some extent it can be valid either way but it needs to be consistent e.g.:
```python
In [1]: a, b, c = symbols('a, b, c')

In [2]: integrate(cos(a*x**2 + b), x, manual=True)
Out[2]: 
                                                    ___
      ⎛          ⎛√2⋅√a⋅x⎞           ⎛√2⋅√a⋅x⎞⎞    ╱ 1 
√2⋅√π⋅⎜- sin(b)⋅S⎜───────⎟ + cos(b)⋅C⎜───────⎟⎟⋅  ╱  ─ 
      ⎝          ⎝   √π  ⎠           ⎝   √π  ⎠⎠ ╲╱   a 
───────────────────────────────────────────────────────
                           2                           

In [3]: integrate(sin(a*x**2 + b), x, manual=True)
Out[3]: 
                                                  ___
      ⎛        ⎛√2⋅√a⋅x⎞           ⎛√2⋅√a⋅x⎞⎞    ╱ 1 
√2⋅√π⋅⎜sin(b)⋅C⎜───────⎟ + cos(b)⋅S⎜───────⎟⎟⋅  ╱  ─ 
      ⎝        ⎝   √π  ⎠           ⎝   √π  ⎠⎠ ╲╱   a 
─────────────────────────────────────────────────────
                          2                          

In [4]: integrate(exp(a*x**2 + b), x, manual=True)
Out[4]: 
       ___              
      ╱ 1   b           
√π⋅  ╱  ─ ⋅ℯ ⋅erfi(√a⋅x)
   ╲╱   a               
────────────────────────
           2  
```
The expressions `1/sqrt(a)` and `sqrt(1/a)` are equivalent for almost all complex numbers but not if `a` is a negative real:
```python
In [5]: 1/sqrt(-1)
Out[5]: -ⅈ

In [6]: sqrt(S(1)/-1)
Out[6]: ⅈ
```
So if we have `sqrt(a)` inside the argument to the function then when differentiating we will get a factor of `sqrt(a)` which can cancel with `1/sqrt(a)` but not `sqrt(1/a)` if `a` is possibly negative.

The fix is to correct the formulae used in manual integrate:
```diff
diff --git a/sympy/integrals/manualintegrate.py b/sympy/integrals/manualintegrate.py
index b555352776..f0fa768b0e 100644
--- a/sympy/integrals/manualintegrate.py
+++ b/sympy/integrals/manualintegrate.py
@@ -659,11 +659,11 @@ def eval(self) -> Expr:
         a, b, c, x = self.a, self.b, self.c, self.variable
         if a.is_extended_real:
             return Piecewise(
-                (sqrt(S.Pi/(-a))/2 * exp(c - b**2/(4*a)) *
+                (sqrt(S.Pi)/sqrt(-a)/2 * exp(c - b**2/(4*a)) *
                     erf((-2*a*x - b)/(2*sqrt(-a))), a < 0),
-                (sqrt(S.Pi/a)/2 * exp(c - b**2/(4*a)) *
+                (sqrt(S.Pi)/sqrt(a)/2 * exp(c - b**2/(4*a)) *
                     erfi((2*a*x + b)/(2*sqrt(a))), True))
-        return sqrt(S.Pi/a)/2 * exp(c - b**2/(4*a)) * \
+        return sqrt(S.Pi)/sqrt(a)/2 * exp(c - b**2/(4*a)) * \
                 erfi((2*a*x + b)/(2*sqrt(a)))
 
 
@@ -675,7 +675,7 @@ class FresnelCRule(AtomicRule):
 
     def eval(self) -> Expr:
         a, b, c, x = self.a, self.b, self.c, self.variable
-        return sqrt(S.Pi/(2*a)) * (
+        return sqrt(S.Pi)/sqrt(2*a) * (
             cos(b**2/(4*a) - c)*fresnelc((2*a*x + b)/sqrt(2*a*S.Pi)) +
             sin(b**2/(4*a) - c)*fresnels((2*a*x + b)/sqrt(2*a*S.Pi)))
 
@@ -688,7 +688,7 @@ class FresnelSRule(AtomicRule):
 
     def eval(self) -> Expr:
         a, b, c, x = self.a, self.b, self.c, self.variable
-        return sqrt(S.Pi/(2*a)) * (
+        return sqrt(S.Pi)/sqrt(2*a) * (
             cos(b**2/(4*a) - c)*fresnels((2*a*x + b)/sqrt(2*a*S.Pi)) -
             sin(b**2/(4*a) - c)*fresnelc((2*a*x + b)/sqrt(2*a*S.Pi)))
```
I think that causes one test in integrals to fail but it is likely that the test can just be changed because it is probably just using a similar incorrect formula.

With the diff above we have:
```python
In [1]: a, b, c = symbols('a, b, c')

In [2]: integrate(exp(a*x**2 + b), x, manual=True)
Out[2]: 
    b           
√π⋅ℯ ⋅erfi(√a⋅x)
────────────────
      2⋅√a      

In [3]: integrate(sin(a*x**2 + b), x, manual=True)
Out[3]: 
      ⎛        ⎛√2⋅√a⋅x⎞           ⎛√2⋅√a⋅x⎞⎞
√2⋅√π⋅⎜sin(b)⋅C⎜───────⎟ + cos(b)⋅S⎜───────⎟⎟
      ⎝        ⎝   √π  ⎠           ⎝   √π  ⎠⎠
─────────────────────────────────────────────
                     2⋅√a                    

In [4]: integrate(cos(a*x**2 + b), x, manual=True)
Out[4]: 
      ⎛          ⎛√2⋅√a⋅x⎞           ⎛√2⋅√a⋅x⎞⎞
√2⋅√π⋅⎜- sin(b)⋅S⎜───────⎟ + cos(b)⋅C⎜───────⎟⎟
      ⎝          ⎝   √π  ⎠           ⎝   √π  ⎠⎠
───────────────────────────────────────────────
                      2⋅√a                     

In [5]: integrate(exp(a*x**2 + b), x, manual=True).diff(x).simplify()
Out[5]: 
    2    
 a⋅x  + b
ℯ        

In [6]: integrate(cos(a*x**2 + b), x, manual=True).diff(x).simplify()
Out[6]: 
   ⎛   2    ⎞
cos⎝a⋅x  + b⎠

In [7]: integrate(sin(a*x**2 + b), x, manual=True).diff(x).simplify()
Out[7]: 
   ⎛   2    ⎞
sin⎝a⋅x  + b⎠
```
I'm marking this as easy to fix. If someone wants to fix this then these three things should be done:

1. Apply the diff shown above.
2. Add a test function in `sympy/integrals/tests/test_manualintegrate.py` with 5 test cases (corresponding to the 5 cases where the formula was changed). Two of the cases need something like `Symbol('a', positive=True)` or with `negative=True`.
3. Fix the other test failure most likely by changing the test (you should check if the test case seems correct).

**Comment by oscarbenjamin** [comment] 2023-04-27 16:41
This is the failing test:
https://github.com/sympy/sympy/blob/008694a57162c69bc9d646ae68ebab8ba2b8618a/sympy/integrals/tests/test_integrals.py#L1660-L1666
That's just a change in the form of the output between these two equivalent expressions:
```python
In [29]: e1
Out[29]: 
        2                    
    -ⅈ⋅m                     
    ──────                   
     4⋅K       ⎛-2⋅ⅈ⋅K⋅x + m⎞
√π⋅ℯ      ⋅erfi⎜────────────⎟
               ⎜       ____ ⎟
               ⎝2⋅√K⋅╲╱ -ⅈ  ⎠
─────────────────────────────
                ____         
         2⋅√K⋅╲╱ -ⅈ          

In [30]: e2
Out[30]: 
           2                    
       -ⅈ⋅m                     
       ──────                   
        4⋅K       ⎛-2⋅ⅈ⋅K⋅x + m⎞
√ⅈ⋅√π⋅ℯ      ⋅erfi⎜────────────⎟
                  ⎜       ____ ⎟
                  ⎝2⋅√K⋅╲╱ -ⅈ  ⎠
────────────────────────────────
              2⋅√K              

In [31]: N(e1/e2)
Out[31]: 1.00000000000000
```
The test could just be changed.

**Comment by sebtiburzio** [comment] 2023-04-27 19:19
Thanks very much. I'd be interested to give it a shot myself based on your instructions, if I can figure it all out (the fix and the process in general - haven't made a pull request before).

I'll look into it over the weekend, unless someone gets to it first.

**Comment by oscarbenjamin** [comment] 2023-04-27 21:08
Feel free to have a go. Issues marked as "easy to fix" are intended to be suitable for new contributors to get used to the process of submitting a pull request. It is also fine for anyone else to attempt a pull request. (It should not be seen as a competition and it is fine for multiple contributors to attempt a fix.)

There is a recently added updated guide for new contributors here:
https://docs.sympy.org/dev/contributing/new-contributors-guide/index.html

Any feedback or questions on the contributor guide itself are also welcome.

**Comment by Sbhat92** [comment] 2023-05-01 03:34
Quick question about the 5 test cases for the five changes:

>  Add a test function in sympy/integrals/tests/test_manualintegrate.py with 5 test cases (corresponding to the 5 cases where the formula was changed). Two of the cases need something like Symbol('a', positive=True) or with negative=True.

Would you like to add the test cases in the sympy/integrals/tests/test_manual.py file, or create a new test_manualintegrate.py file?

**Comment by sebtiburzio** [comment] 2023-05-01 08:52
@oscarbenjamin I'm not sure if I defined the new regression tests in `test_manual.py` correctly, as you mentioned 5 cases, however I have 6. Please let me know if I've missed the idea of what these tests are supposed to check.

```
def test_issue_25090():
    a, b, x = symbols('a b x')
    assert manualintegrate(exp(a*x**2 + b), x) == sqrt(pi)*exp(b)*erfi(sqrt(a)*x)/(2*sqrt(a))
    assert manualintegrate(sin(a*x**2 + b), x) == \
        sqrt(2)*sqrt(pi)*(sin(b)*fresnelc(sqrt(2)*sqrt(a)*x/sqrt(pi)) + cos(b)*fresnels(sqrt(2)*sqrt(a)*x/sqrt(pi)))/(2*sqrt(a))
    assert manualintegrate(cos(a*x**2 + b), x) == \
        sqrt(2)*sqrt(pi)*(-sin(b)*fresnels(sqrt(2)*sqrt(a)*x/sqrt(pi)) + cos(b)*fresnelc(sqrt(2)*sqrt(a)*x/sqrt(pi)))/(2*sqrt(a))
    a = Symbol('a', negative=True)
    assert manualintegrate(exp(a*x**2 + b), x) == -sqrt(pi)*exp(b)*erf(a*x/sqrt(-a))/(2*sqrt(-a))
    assert manualintegrate(sin(a*x**2 + b), x) == \
        sqrt(2)*sqrt(pi)*(sin(b)*fresnelc(sqrt(2)*sqrt(a)*x/sqrt(pi)) + cos(b)*fresnels(sqrt(2)*sqrt(a)*x/sqrt(pi)))/(2*sqrt(a))
    assert manualintegrate(cos(a*x**2 + b), x) == \
        sqrt(2)*sqrt(pi)*(-sin(b)*fresnels(sqrt(2)*sqrt(a)*x/sqrt(pi)) + cos(b)*fresnelc(sqrt(2)*sqrt(a)*x/sqrt(pi)))/(2*sqrt(a))
```

**Comment by oscarbenjamin** [comment] 2023-05-01 15:14
> Would you like to add the test cases in the `sympy/integrals/tests/test_manual.py` file

Yes

**Closed** 2023-05-02 10:29 UTC
Labels: Easy to Fix, integrals, integrals.manualintegrate
