### ISSUE TITLE
limit(sign(sin(x)), x, 0, '+')) = 0 (which is wrong)

### ISSUE THREAD

**Issue by JulianWgs** [sympy/sympy#18118] opened 2019-12-24 14:06 UTC
Putting a sine inside a sign operation results in wrong solution.

Here is a code example:

```python
from sympy import *

x = symbols("x")
print("limit(sign(x), x, 0, '+') =", limit(sign(x), x, 0, "+")) # correct
print("limit(sign(sin(x)), x, 0, '+')) =", limit(sign(sin(x)), x, 0, "+")) # wrong
```

Also Wolfram Alpha has a different solution:

https://www.wolframalpha.com/input/?i=limit+sign%28sin%28x%29%29+for+x-%3E0%2B

Im using sympy 1.5 and mpmath 1.1.0.

**Comment by hyadav2k** [comment] 2020-12-12 12:27
Hi @sylee957 @sachin-4099, I would like to contribute to this issue. I have doubt in approaching the Issue, Can you please guide me.

**Comment by hyadav2k** [comment] 2020-12-13 06:15
After adding test case for the **limit(sign(sin(x)), x, 0, "+")**, it gives AttributeError as, **AttributeError: 'Subs' object has no attribute 'variable_count'** at line 2290, in doit for vi, ci in e.variable_count, at sympy\core\function.py.
I would like to know whether we should construct an extra case in order to solve this limit correctly. Kindly, guide me to fix this issue.

**Comment by hyadav2k** [comment] 2020-12-24 11:02
Can someone guide me in fixing this issue, I would really like to solve it.

**Comment by JulianWgs** [comment] 2020-12-24 12:22
I would start by looking at the stack trace

**Comment by hyadav2k** [comment] 2020-12-25 08:30
I added test cases inorder to traceback:

def test_issue_18118():
    x=Symbol('x')
    assert limit(sign(sin(x)), x, 0, "+") == +1
    assert limit(sign(sin(x)), x, 0, "-") == -1



Then I ran this particular file using bin/test sympy/series/tests/test_limits.py, later I got:  

Traceback (most recent call last):
  File "c:\users\harshit yadav\sympy\sympy\series\tests\test_limits.py", line 901, in test_issue_18118
    assert limit(sign(sin(x)), x, 0, "+") == +1
  File "c:\users\harshit yadav\sympy\sympy\series\limits.py", line 63, in limit
    return Limit(e, z, z0, dir).doit(deep=False)
  File "c:\users\harshit yadav\sympy\sympy\series\limits.py", line 329, in doit
    r = gruntz(e, z, z0, dir)
  File "c:\users\harshit yadav\sympy\sympy\series\gruntz.py", line 670, in gruntz
    r = limitinf(e0, z)
  File "c:\users\harshit yadav\sympy\sympy\core\cache.py", line 72, in wrapper
    retval = cfunc(*args, **kwargs)
  File "c:\users\harshit yadav\sympy\sympy\series\gruntz.py", line 438, in limitinf
    c0, e0 = mrv_leadterm(e, x)
  File "c:\users\harshit yadav\sympy\sympy\core\cache.py", line 72, in wrapper
    retval = cfunc(*args, **kwargs)
  File "c:\users\harshit yadav\sympy\sympy\series\gruntz.py", line 523, in mrv_leadterm
    series = calculate_series(f, w, logx=logw)
  File "c:\users\harshit yadav\sympy\sympy\series\gruntz.py", line 486, in calculate_series
    if t.simplify():
  File "c:\users\harshit yadav\sympy\sympy\core\basic.py", line 1671, in simplify
    return simplify(self, **kwargs)
  File "c:\users\harshit yadav\sympy\sympy\simplify\simplify.py", line 648, in simplify
    expr = done(expr)
  File "c:\users\harshit yadav\sympy\sympy\simplify\simplify.py", line 562, in done
    rv = e.doit() if doit else e
  File "c:\users\harshit yadav\sympy\sympy\functions\elementary\piecewise.py", line 310, in doit
    newe = e.doit(**hints)
  File "c:\users\harshit yadav\sympy\sympy\core\operations.py", line 432, in doit
    terms = [term.doit(**hints) for term in self.args]
  File "c:\users\harshit yadav\sympy\sympy\core\operations.py", line 432, in <listcomp>
    terms = [term.doit(**hints) for term in self.args]
  File "c:\users\harshit yadav\sympy\sympy\core\function.py", line 2290, in doit
    for vi, ci in e.variable_count:
AttributeError: 'Subs' object has no attribute 'variable_count'

@JulianWgs, I searched for the attribute variable_count in the docs, but there is no such attribute. What should be done next?

**Comment by JulianWgs** [comment] 2020-12-25 09:30
I'm just an occasional user of sympy, so I'm not familiar with the implementation. The sympy project has too many issue, and too few people fixing them. I would not expect too much help fixing the issue, because of that. Sorry :)

Why do you get an AttributeError? The code should execute properly and raise an AssertionError.

**Comment by oscarbenjamin** [comment] 2020-12-25 11:05
It looks like you've hit a different bug in `Subs.doit`:
```python
In [4]: e = Derivative(0, x).subs(x, 0)

In [5]: e
Out[5]: 
⎛d    ⎞│   
⎜──(0)⎟│   
⎝dx   ⎠│x=0

In [6]: e.doit()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-7139a477de25> in <module>
----> 1 e.doit()

~/current/sympy/sympy/sympy/core/function.py in doit(self, **hints)
   2288                 expr = e.expr
   2289                 free = expr.free_symbols
-> 2290                 for vi, ci in e.variable_count:
   2291                     if isinstance(vi, Symbol) and vi in free:
   2292                         expr = expr.diff((vi, ci))

AttributeError: 'Subs' object has no attribute 'variable_count'
```

**Comment by jksuom** [comment] 2020-12-25 13:48
Functions like `sign`, with discontinuities, need a special implementation for series and limits. I would try something like this (among the `_eval_` metrhods of `class sign`).

    def _eval_nseries(self, x, n, logx, cdir=0):
        arg0 = self.args[0]
        x0 = arg0.subs(x, 0)
        if x0 != 0:
            return self.func(x0)
        if cdir != 0:
            cdir = arg0.dir(x, cdir)
        return -S.One if re(cdir) < 0 else S.One

**Comment by hyadav2k** [comment] 2020-12-26 07:26
Indeed, it occurs when we use the subs method on the unevaluated object and the object's argument i.e. the expression is independent w.r.t the differentiating variable (**x** in this case)
For e.g.
y=Derivative(t,x).subs(x,0)
y.doit()

In the above example, it will give us the same attribute error, but if we substitute **t** with some constant value or function of **x**, then there is no error and the o/p comes out to be correct.
@oscarbenjamin, How would you suggest to go further in the problem, whether we check if the expression is independent of **x**, then we can directly use doit(), without using subs method, or any other interesting idea to implement.

**Comment by oscarbenjamin** [comment] 2020-12-26 15:12
Well the bug in `Subs.doit` should be fixed in any case.

**Comment by hyadav2k** [comment] 2020-12-27 16:45
@oscarbenjamin, I have fixed the **Subs.doit** issue, how should I push my changes, either to make a new issue and add PR to it or should add PR to this issue only for Subs.doit?

Secondly, for the original issue of limit, assertion error is coming now as I have added test cases for this issue and the limit comes 0 instead of +1. How would you suggest, what could be the problem behind the wrong result?

**Comment by JulianWgs** [comment] 2020-12-27 16:57
I‘d suggest to create a new issue with a detailed description of the issue and reference this issue. Then create a PR which closes the new issue.

With this you have clear distinction between the two issues and their implementations.

**Comment by hyadav2k** [comment] 2020-12-30 08:34
@oscarbenjamin @JulianWgs @jksuom, What should be the approach to solve this issue.
Should we handle this case of limit of **sign** function separately?

**Comment by hyadav2k** [comment] 2020-12-31 12:24
Found the issue for the incorrect o/p, it is related to gruntz algorithm, the problem is that after calling gruntz, it recursively calls **Subs(Derivative(sign(_x), _x), _x, 0)**, and it remains unevaluted, actually, the derivative of sign function is not defined in sympy,  thus, the recursive calls go to waste as it remains unevaluted, but I don't know why it gives 0. We will have the derivative of sign(x) as it is 2*dirac delta function of x. I used  **SYMPY_DEBUG=True ./bin/isympy**, which helped in tracing the gruntz recursive calls, but I have doubt that in the mrv set of sign(sin(x)) only x will be there, so x is the w(omega), but clearly w is not any exp/log function as specified in the gruntz algorithm, thus rewrite function raises ValueError, when folloing commands are inputed manually:

**from sympy import *
from sympy.series.gruntz import mrv, rewrite
x=Symbol('x')
m=mrv(sign(sin(x)),x)
w = Symbol('w')
rewrite(m[1], m[0], x, w)[0]**

**Comment by jksuom** [comment] 2021-01-01 12:35
I would start by adding nseries support to sign. That is needed for most limits.

**Comment by hyadav2k** [comment] 2021-01-02 08:33
> I would start by adding nseries support to sign. That is needed for most limits.

Can you please elaborate on it, I am not able to co-relate how nseries may help in this case, since gruntz works for limits involving exp-log functions, and calling gruntz for this case is wrong and it should have been returning NotImplementedError.

Secondly, especially for this issue, we can try a simple approach like to check for the argument inside sign function(sin(x) in this case), and we need to find it's behaviour for the limit, i.e. either it is approaching from left or right for 0, i.e. 0+ or 0-, and thus simply we can use sign function to store the result and thus directly using the limit(sign(x), x, 0, '+' or '-')), dir will be set according to the result of the stored value. 
Kindly share your opinion on it.
Thanks

**Closed** 2021-01-11 17:02 UTC
Labels: calculus, limits, series
