### ISSUE TITLE
Two tests fail even for Python 3.9 while packaging for openSUSE

### ISSUE THREAD

**Issue by mcepl** [sympy/sympy#23533] opened 2022-05-21 21:25 UTC
While packaging for openSUSE/Factory I got these errors:
```
[ 2870s] ________________________________________________________________________________
[ 2870s] ___________________ sympy.tensor.indexed.IndexedBase.offset ____________________
[ 2870s] File "/home/abuild/rpmbuild/BUILD/sympy-1.10.1/sympy/tensor/indexed.py", line 559, in sympy.tensor.indexed.IndexedBase.offset
[ 2870s] Failed example:
[ 2870s]     ccode(A[i, j, k])
[ 2870s] Exception raised:
[ 2870s]     Traceback (most recent call last):
[ 2870s]       File "/usr/lib64/python3.9/doctest.py", line 1334, in __run
[ 2870s]         exec(compile(example.source, filename, "single",
[ 2870s]       File "<doctest sympy.tensor.indexed.IndexedBase.offset[6]>", line 1, in <module>
[ 2870s]         ccode(A[i, j, k])
[ 2870s]     TypeError: 'module' object is not callable
[ 2870s]
[ 2870s] ===== tests finished: 4185 passed, 1 failed, 15 skipped, in 321.43 seconds =====
[ 2870s] DO *NOT* COMMIT!
```
and
```
[ 2971s] **********************************************************************
[ 2971s] File "/home/abuild/rpmbuild/BUILD/sympy-1.10.1/doc/src/modules/printing.rst", line
 107, in printing.rst
[ 2971s] Failed example:
[ 2971s]     print(cxxcode(Min(gamma(x) - 1, x), standard='C++11'))
[ 2971s] Exception raised:
[ 2971s]     Traceback (most recent call last):
[ 2971s]       File "/usr/lib64/python3.9/doctest.py", line 1334, in __run
[ 2971s]         exec(compile(example.source, filename, "single",
[ 2971s]       File "<doctest printing.rst[10]>", line 1, in <module>
[ 2971s]         print(cxxcode(Min(gamma(x) - 1, x), standard='C++11'))
[ 2971s]     TypeError: 'module' object is not callable
[ 2971s] **********************************************************************
[ 2971s] 1 items had failures:
[ 2971s]    1 of  45 in printing.rst
```
I am not exactly sure whether these are the same errors.

[Complete build log](https://github.com/sympy/sympy/files/8748364/_log.txt) with all details: used packages and steps taken to reproduce the problem.

**Comment by oscarbenjamin** [comment] 2022-05-21 22:45
I don't understand the build log. What version or commit of SymPy are you using?

**Comment by mcepl** [comment] 2022-05-23 06:36
> I don't understand the build log. What version or commit of SymPy are you using?

1.10.1 tarball from https://files.pythonhosted.org/packages/source/s/sympy/sympy-1.10.1.tar.gz

**Comment by oscarbenjamin** [comment] 2022-05-23 11:01
I can't tell what command is being used to run the tests. Is it using pytest?

The errors come from doctests. There are two ways to run the doctests (with `bin/doctest` or with `pytest --doctest-plus`):
```console
$ bin/doctest sympy/tensor/indexed.py 
========================================== test process starts ==========================================
executable:         /space/enojb/miniconda3/envs/sympy.git/bin/python  (3.9.7-final-0) [CPython]
architecture:       64-bit
cache:              yes
ground types:       gmpy 2.1.2
numpy:              1.21.2
hash randomization: on (PYTHONHASHSEED=3345591144)

sympy/tensor/indexed.py[15] ...............                                                          [OK]

============================== tests finished: 15 passed, in 0.08 seconds ===============================
$ pytest --doctest-plus sympy/tensor/indexed.py 
========================================== test session starts ==========================================
platform linux -- Python 3.9.7, pytest-7.0.1, pluggy-1.0.0
architecture: 64-bit
cache:        yes
ground types: gmpy 2.1.2

rootdir: /space/enojb/sympy/sympy.git, configfile: pytest.ini
plugins: xdist-2.5.0, forked-1.4.0, doctestplus-0.12.0
collected 15 items                                                                                      

sympy/tensor/indexed.py ...............                                                           [100%]

========================================== 15 passed in 0.11s ===========================================
```

**Comment by mcepl** [comment] 2022-05-23 20:53
> I can't tell what command is being used to run the tests. Is it using pytest?
```
[  118s] + export PYTHONPATH=/home/abuild/rpmbuild/BUILDROOT/python-sympy-1.10.1-0.x86_64/usr/lib/python3.9/site-packages PYTHONDONTWRITEBYTECODE=1
[  118s] + python3.9 setup.py test
```

**Comment by oscarbenjamin** [comment] 2022-05-23 22:40
There is a `sympy.printing.ccode` module and there is a `ccode` function that is importable from `sympy.printing`. Somehow this is getting confused and importing the wrong one:
https://github.com/sympy/sympy/blob/6ea48db2bd108a0c5b3c53aa2f1ef9e5d617bf3c/sympy/tensor/indexed.py#L553-L560
I think that's maybe because of this line here:
https://github.com/sympy/sympy/blob/6ea48db2bd108a0c5b3c53aa2f1ef9e5d617bf3c/sympy/printing/tests/test_c.py#L853-L856
After that the ccode module will be installed as an attribute in the printing module:
```python
In [4]: from sympy.printing import ccode

In [5]: ccode
Out[5]: <function sympy.printing.codeprinter.ccode(expr, assign_to=None, standard='c99', **settings)>

In [6]: import sympy.printing.ccode
<ipython-input-6-23dbbffc44fc>:1: SymPyDeprecationWarning: 

The sympy.printing.ccode submodule is deprecated. It has been renamed to
sympy.printing.c.

See https://docs.sympy.org/latest/explanation/active-deprecations.html#deprecated-printing-code-submodules
for details.

This has been deprecated since SymPy version 1.7. It
will be removed in a future version of SymPy.

  import sympy.printing.ccode

In [7]: from sympy.printing import ccode

In [8]: ccode
Out[8]: <module 'sympy.printing.ccode' from '/home/oscar/current/sympy/sympy.git/sympy/printing/ccode.py'>
```
I guess if one test is run after the other in the same process then it can cause the doctest to fail. Probably the same is true for cxxcode.

**Comment by mcepl** [comment] 2022-05-23 23:26
So, do you want to say that instead of `import sympy.printing.code` there should be `import sympy.printing.c`?

**Comment by oscarbenjamin** [comment] 2022-05-23 23:38
The ccode module was recently renamed by @asmeurer. It still exists under the ccode name only as a deprecated module for backwards compatibility. The problem is just the test that still tests the deprecated functionality since it can mess up the behaviour of other tests. I think that the test should be changed to restore the import of the ccode function or maybe the ccode module should just be completely removed.

**Comment by asmeurer** [comment] 2022-05-24 00:59
This sort of thing is why the deprecation was out there in the first place. We can do a full removal if it's causing problems. 1.7 was released in November 2020 and our policy is to wait at least 1 year.

**Comment by mcepl** [comment] 2022-05-25 06:19
This [patch](https://github.com/sympy/sympy/files/8768407/sympy_printing_ccode.patch.txt) makes the test suite pass. Whether it is a good idea or not, I will leave as an excercise for you. I withdraw any rights to it, do with it as you wish (and no, I cannot do PR for each of 2000+ Python packages I maintain).

**Comment by oscarbenjamin** [comment] 2022-05-25 10:07
That patch is basically what I was thinking.

**Closed** 2022-06-22 22:12 UTC
