### ISSUE TITLE
The docs page has older versions in the sidebar

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#19839] opened 2020-07-25 08:02 UTC
See https://docs.sympy.org/latest/index.html. We removed the older versions from the sidebar, but the most recent releases added them back. There should only be "latest" and "dev". The version number on "latest" is also wrong.

**Comment by Raghibshams456** [comment] 2020-07-29 15:04
working on it..

**Comment by Raghibshams456** [comment] 2020-07-29 17:16
I have created pull request in sympy_doc..where I have made changes in index.html....

**Comment by Raghibshams456** [comment] 2020-07-29 17:22
https://github.com/sympy/sympy_doc/pull/39

**Comment by asmeurer** [comment] 2020-07-29 18:36
We also need to update the SymPy release script so this stops happening.

**Comment by Raghibshams456** [comment] 2020-07-29 18:53
Ok..I will do that .. thanx...

**Comment by oscarbenjamin** [comment] 2020-07-31 18:49
I guess that the root cause here is this:
https://github.com/sympy/sympy/blob/39785ea55d0a459912c19780653f7e7cb6884820/release/update_docs.py#L118-L124

**Comment by asmeurer** [comment] 2020-07-31 19:10
Yep, it should be something like

```py
def update_releases_txt(sympy_doc_git, dev_version, release_version):
    """Add line to the releases.txt file"""

    print()
    print("Updating releases.txt")
    print()

    with open(releases_txt_path, "w") as fout:
        fout.writelines(f"""\
latest:SymPy {release_version} (latest release)
dev:SymPy {dev_version} (development version)
""")
```

And the code that updates the docs should be updated to just remove the old `latest` and copy the new docs into `latest` (no generating version directories).

**Comment by asmeurer** [comment] 2020-08-06 20:32
@oscarbenjamin can you make sure the above is done in the release script before you do 1.6.2.

**Comment by oscarbenjamin** [comment] 2020-08-07 15:20
I can but this isn't yet fixed in the docs repo is it?

We need it fixed in the docs repo and the README for the docs repo needs to explain how this stuff is supposed to work in sufficient low-level detail that the release script can be written to perform the update action.

It's just as easy to do that before or after releasing 1.6.2 but as yet it hasn't been done: https://github.com/sympy/sympy_doc/pull/42

**Comment by asmeurer** [comment] 2020-08-10 19:11
I fixed the issue in the docs. We should make sure the release script is updated before we do another release so this doesn't happen again.

**Comment by oscarbenjamin** [comment] 2020-08-10 21:17
It looks like the description in the README has been updated:
https://github.com/sympy/sympy_doc#release-docs

If that's correct then I can fix the script.

**Closed** 2020-08-11 08:42 UTC
Labels: Documentation
