### ISSUE TITLE
Intersection of sets with symbolic elements could be empty

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#16953] opened 2019-06-03 18:01 UTC
We have
```julia
In [4]: FiniteSet(1+x-y) & FiniteSet(1)
Out[4]: {1} ∩ {x - y + 1}

In [5]: FiniteSet(1) & FiniteSet(1+x-y)
Out[5]: {1}
```
Clearly the two expressions should give the same result. The first result is correct since if x!=y then the result is the empty set:
```julia
In [6]: FiniteSet(1) & FiniteSet(1+x-y).subs(x, y+1)
Out[6]: ∅
```

**Comment by smichr** [comment] 2019-06-03 19:36
This could stem from the fact that `Intersection()` gives UniversalSet. Is that right?

**Comment by gschintgen** [comment] 2019-08-27 08:11
This reads like a duplicate of https://github.com/sympy/sympy/issues/16342. Could be closed? Note that according to a comment in the mentioned PR#16342, this could be a subtle issue to fix.

**Comment by oscarbenjamin** [comment] 2019-08-27 11:14
They are very much related. I don't see the need to close this one now though as it has a different example and also illustrates another failing of the algorithm (order dependence). I expect that both issues will be fixed at the same time.

Here's an even simpler example:
```julia
In [1]: FiniteSet(x) & FiniteSet(1)                                                                                               
Out[1]: {1}

In [2]: FiniteSet(1) & FiniteSet(x)                                                                                               
Out[2]: {1}
```
I'm not sure that the algorithm will be subtle to fix but having looked at it I think if I was to try and fix it I might start from scratch.

1. Collect the input sets as fs_args.
2. Go through removing any elements that are definitely not in all of fs_args
3. Return `Intersection(*fs_args, evaluate=False)`

The existing code also has a bunch of extra stuff for handling symbolic elements but clearly it doesn't work so we might be better off with something that is simpler but correct.

**Comment by oscarbenjamin** [comment] 2019-08-27 16:53
I have a PR coming soon

**Closed** 2019-09-02 00:46 UTC
Labels: sets
