### ISSUE TITLE
SymPy Deprecation Warning when running init_session()

### ISSUE THREAD

**Issue by Honigmelone** [sympy/sympy#20764] opened 2021-01-08 13:50 UTC
# Description

When running sympy.init_session() a deprecation Warning pops up. 
I think this is related to #9371

# setup
Run the following code in an IPython console
( I ran it inside spyder 4.2)

Despite my efforts with the warnings lib, I could not generate a stack trace.

````
import warnings
warnings.filterwarnings("error", message=('SymPyDeprecationWarning'))

import sympy as sp
import sys

sp.init_session()
````
# Expected Output
````
Python 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 7.19.0 -- An enhanced Interactive Python.

In [1]: runfile('...test_sympy_warning.py', wdir=.')
IPython console for SymPy 1.7.1 (Python 3.8.5-64-bit) (ground types: python)

These commands were executed:
>>> from __future__ import division
>>> from sympy import *
>>> x, y, z, t = symbols('x y z t')
>>> k, m, n = symbols('k m n', integer=True)
>>> f, g, h = symbols('f g h', cls=Function)
>>> init_printing()


In [2]: 
````
# Observed Output
````
Python 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 7.19.0 -- An enhanced Interactive Python.

In [1]: runfile('...test_sympy_warning.py', wdir=.')
IPython console for SymPy 1.7.1 (Python 3.8.5-64-bit) (ground types: python)

These commands were executed:
>>> from __future__ import division
>>> from sympy import *
>>> x, y, z, t = symbols('x y z t')
>>> k, m, n = symbols('k m n', integer=True)
>>> f, g, h = symbols('f g h', cls=Function)
>>> init_printing()

Documentation can be found at https://docs.sympy.org/1.7.1/

<USER>\Programs\Anacoda3\envs\py38\lib\site-packages\sympy\deprecated\class_registry.py:33: SymPyDeprecationWarning: 

C, including its class ClassRegistry, has been deprecated since SymPy
1.0. It will be last supported in SymPy version 1.0. Use direct
imports from the defining module instead. See
https://github.com/sympy/sympy/issues/9371 for more info.

  SymPyDeprecationWarning(

In [2]: 
````

**Comment by oscarbenjamin** [comment] 2021-01-08 18:43
Duplicate of #9371. I'll reply there.

**Closed by oscarbenjamin** 2021-01-08 18:43 UTC
