### ISSUE TITLE
integrate() does not work with multivariable function that is solved by simple substitution. DomainError: there is no ring associated with CC

### ISSUE THREAD

**Issue by LuisMi1245** [sympy/sympy#21741] opened 2021-07-14 04:40 UTC
`>> x, y, z, t = symbols('x y z t')`
`>> fun = E ** (
    (-2*I*pi*
     (z*x+t*y)
    /
     (500*(10**(-9)))
    )
   )`
returns the following:
![image](https://user-images.githubusercontent.com/35621197/125561393-ef9fc234-b58b-4351-9a70-40d040665e80.png)

Now I try to integrate with respect to z:
`>> integrate(fun, z)`
And the output is an error raised by the get_ring() method of the Domain class (I think) that says:

_**DomainError: there is no ring associated with CC**_

However, if I rewrite the function obtained by python **fun**, but in this case, removing the decimal point and the leftover zero in a new sympy variable **fun2**, then the integral solves beautifully. I mean this:

`>> fun2 = E**(
-4000000*I*pi*(t*y+x*z)
)`
`>> integrate(fun2,z)`
returns the following:
![image](https://user-images.githubusercontent.com/35621197/125562188-3a213dfd-4e60-4f85-8ae0-792d337353b9.png)

And this is correct. Anyway, I had to spend hours trying to understand the reason for the error, although I honestly don't know the reason.  I can only conclude that the integration system might have some internal bug.

**Comment by oscarbenjamin** [comment] 2021-07-14 11:35
I see this error with sympy 1.8 but it is already fixed on master. I've bisected the fix to b963ae372e46a02cf30682ff927c4683dcceaee6 from #21337.

I'm marking this as easy to fix. This issue can be closed if a test is added for the two examples above in `sympy/integrals/tests/test_integrals.py`.

**Comment by praneethratna** [comment] 2021-07-14 12:05
@oscarbenjamin Hi , I'm kinda new to open source contribution and would like to work on fixing this issue , can i be assigned this issue?

**Comment by oscarbenjamin** [comment] 2021-07-14 12:16
Issues are not assigned to anyone. I have marked it as easy to fix in order to invite someone to contribute a PR that fixes this so go ahead. There is a guide to the workflow here:
https://github.com/sympy/sympy/wiki/Development-workflow

**Comment by praneethratna** [comment] 2021-07-14 18:38
@oscarbenjamin Hey , I'm kinda struck on how to write the test case for this issue , could you please give a headstart on how to  write?

**Comment by LuisMi1245** [comment] 2021-07-14 19:32
@praneethratna I think what Oscar is saying is that you need to add in the integral test method stack (sympy/integrals/tests/test_integrals.py), the two forms of the integral that I mention here with the correct solutions, using the assert function to throw exceptions in case the condition is not met due to problems with the integration algorithm.

**Comment by LuisMi1245** [comment] 2021-07-14 23:32
@oscarbenjamin The error has not yet been resolved. I added the two integrals to the *test_integrals.py* file following the examples in that file. On the other hand, when running:

`>> ./bin/test sympy/integrals/tests/test_integrals.py`

The test fails as shown in the image. I use the most recent version (from 2 hours ago) from the sympy repository on Github.
![image](https://user-images.githubusercontent.com/35621197/125705298-1afff6a6-c767-4a5c-90cc-ceb085c3b5a9.png)

**What else do you recommend doing?**

**Comment by LuisMi1245** [comment] 2021-07-14 23:38
This is the same code. And the bin/test suggests me: "DO NOT COMMIT".

![image](https://user-images.githubusercontent.com/35621197/125705872-4f4adab2-ec4b-4b3b-876e-387b5a8d6bb0.png)

**Comment by oscarbenjamin** [comment] 2021-07-14 23:39
Not sure what the problem is but try running that code directly outside of the test suite and see what the output is for both lhs and rhs.

Note that `10**-9` will create a float rather than Rational

**Comment by LuisMi1245** [comment] 2021-07-14 23:44
> Not sure what the problem is but try running that code directly outside of the test suite and see what the output is for both lhs and rhs.
> 
> Note that `10**-9` will create a float rather than Rational

But the integration method should support the coefficient being of rational or float type, right?

**Comment by LuisMi1245** [comment] 2021-07-14 23:57
You are right, now it does work and performs the integral without problems, however the results are not the same even though the expressions to integrate are the same in the mathematical context. I think it has to do with what you mention about the 10**(-9).

![image](https://user-images.githubusercontent.com/35621197/125707197-21c96507-f758-45a1-89ca-6ce772bc8e80.png)

I will close the comment when I understand why the results are different for two mathematically equal expressions.

**Comment by praneethratna** [comment] 2021-07-15 04:04
@LuisMi1245 i got the same error that you got while adding the test case , well as also mentioned this seems to be a problem with 10**(-9) being a float but how can that be fixed?

**Comment by LuisMi1245** [comment] 2021-07-15 04:20
@praneethratna
```python
def test_issue_21741():
    x,y,z,t = symbols('x y z t', positive=True)
    #Both integrals are exactly the same. 
    assert integrate(E ** ((-2*I*pi*(z*x+t*y))/((500*(Rational(1,10**9))))), z).simplify() - (I*E**(-4000000*I*pi*(t*y+x*z)))/(4000000*pi*x).simplify() == 0
    assert integrate((E ** (-4000000*I*pi*(z*x+t*y))), z).simplify() - (I*E**(-4000000*I*pi*(t*y+x*z)))/(4000000*pi*x).simplify() == 0
```
You just need to understand that 10**-9 is a division that will first be captured and evaluated by python as a floating point expression. In that case, you must indicate that the expression is of type sympy using simpify() or Rational(a,b) so that it retains the fraction. You can find this at: 
[Sympy: Simbolic-Expressions](https://docs.sympy.org/dev/gotchas.html#symbolic-expressions)

**Comment by oscarbenjamin** [comment] 2021-07-15 09:35
The floating point numbers need to match exactly for the test to succeed:
```python
In [45]: a = Float('3999999.9999999995', precision=53)                                                                                                        

In [46]: b = Float('2.5000000000000004e-7', precision=53)                                                                                                     

In [47]: r = Piecewise((b*I*exp(-a*I*pi*t*y)*exp(-a*I*pi*x*z)/(pi*x), Ne(1.0*pi*x*exp(a*I*pi*t*y), 0)), (z*exp(-a*I*pi*t*y), True))                           

In [48]: integrate(fun, z) == r                                                                                                                               
Out[48]: True
```
You can see the internal representation of the expressions in full detail using `srepr`:
```python
In [49]: srepr(integrate(fun, z))                                                                                                                             
Out[49]: "Piecewise(ExprCondPair(Mul(Float('2.5000000000000004e-7', precision=53), I, Pow(pi, Integer(-1)), Pow(Symbol('x'), Integer(-1)), exp(Mul(Integer(-1), Float('3999999.9999999995', precision=53), I, pi, Symbol('t'), Symbol('y'))), exp(Mul(Integer(-1), Float('3999999.9999999995', precision=53), I, pi, Symbol('x'), Symbol('z')))), Unequality(Mul(Float('1.0', precision=53), pi, Symbol('x'), exp(Mul(Float('3999999.9999999995', precision=53), I, pi, Symbol('t'), Symbol('y')))), Integer(0))), ExprCondPair(Mul(Symbol('z'), exp(Mul(Integer(-1), Float('3999999.9999999995', precision=53), I, pi, Symbol('t'), Symbol('y')))), true))"
```
There should probably be a helper function for tests that can check whether two expressions are almost equal wrt floating point numbers.

**Comment by smichr** [comment] 2021-07-15 15:55
> should probably be a helper function for tests that can check whether two expressions are almost equal wrt floating point

```python
>>> a = Float(4*10**6)
>>> b = Float(2.5e-7)
>>> r = Piecewise((b*I*exp(-a*I*pi*t*y)*exp(-a*I*pi*x*z)/(pi*x), Ne(1.0*pi*x*exp
(a*I*pi*t*y), 0)), (z*exp(-a*I*pi*t*y), True))
>>> ans = integrate(fun,z)
>>> r==ans
False
>>> str(r)==str(ans)
True
>>> dif = ans - r
>>> dif.xreplace({i:Float(str(i)) for i in dif.atoms(Float)})
0
```

**Closed** 2021-07-15 17:11 UTC
Labels: Easy to Fix, integrals, integrals.risch

**Comment by LuisMi1245** [comment] 2021-07-15 17:24
> The floating point numbers need to match exactly for the test to succeed:
> 
> ```python
> In [45]: a = Float('3999999.9999999995', precision=53)                                                                                                        
> 
> In [46]: b = Float('2.5000000000000004e-7', precision=53)                                                                                                     
> 
> In [47]: r = Piecewise((b*I*exp(-a*I*pi*t*y)*exp(-a*I*pi*x*z)/(pi*x), Ne(1.0*pi*x*exp(a*I*pi*t*y), 0)), (z*exp(-a*I*pi*t*y), True))                           
> 
> In [48]: integrate(fun, z) == r                                                                                                                               
> Out[48]: True
> ```
> 
> You can see the internal representation of the expressions in full detail using `srepr`:
> 
> ```python
> In [49]: srepr(integrate(fun, z))                                                                                                                             
> Out[49]: "Piecewise(ExprCondPair(Mul(Float('2.5000000000000004e-7', precision=53), I, Pow(pi, Integer(-1)), Pow(Symbol('x'), Integer(-1)), exp(Mul(Integer(-1), Float('3999999.9999999995', precision=53), I, pi, Symbol('t'), Symbol('y'))), exp(Mul(Integer(-1), Float('3999999.9999999995', precision=53), I, pi, Symbol('x'), Symbol('z')))), Unequality(Mul(Float('1.0', precision=53), pi, Symbol('x'), exp(Mul(Float('3999999.9999999995', precision=53), I, pi, Symbol('t'), Symbol('y')))), Integer(0))), ExprCondPair(Mul(Symbol('z'), exp(Mul(Integer(-1), Float('3999999.9999999995', precision=53), I, pi, Symbol('t'), Symbol('y')))), true))"
> ```
> 
> There should probably be a helper function for tests that can check whether two expressions are almost equal wrt floating point numbers.

Yes, I gave up trying a PR due to ignorance. I am glad I understood.
