### ISSUE TITLE
HadamardPower.doit() should do it

### ISSUE THREAD

**Issue by cbm755** [sympy/sympy#16485] opened 2019-03-29 04:24 UTC
```python
>>> A = Matrix(2, 3, [1,2,3,4,5,6])
>>> A
⎡1  2  3⎤
⎢       ⎥
⎣4  5  6⎦

>>> HadamardPower(A, 2)
    Matrix([   
   [1, 2, 3],  
[4, 5, 6]]).**2

>>> _.doit()     # but it doesn't
    Matrix([   
   [1, 2, 3],  
[4, 5, 6]]).**2

>>> HadamardPower(A, A)
       Matrix([       
      [1, 2, 3],      
[4, 5, 6]]).**Matrix([
      [1, 2, 3],      
     [4, 5, 6]])      

>>> _.doit()     # nor here
       Matrix([       
      [1, 2, 3],      
[4, 5, 6]]).**Matrix([
      [1, 2, 3],      
     [4, 5, 6]])     
```
(printing is poor but that is getting fixed elsewhere)

See also #8557.

Also, consider having it evaluate by default and respect `evaluate=False`, see #16484.

**Comment by oscarbenjamin** [comment] 2019-10-26 20:13
Removing the 1.5 milestone. I think it is reasonable to improve this but it's not clear to me why this should hold up the 1.5 release.

**Comment by moorepants** [comment] 2019-10-27 15:16
This is a duplicate of https://github.com/sympy/sympy/issues/8557.

**Closed by moorepants** 2019-10-27 15:16 UTC
Labels: matrices.expressions
