### ISSUE TITLE
factor() returns incomplete factorization

### ISSUE THREAD

**Issue by schymans** [sympy/sympy#14744] opened 2018-05-25 08:31 UTC
Here is a very simple example, were I was hoping that `factor()` would return `x*(y + z) + z` but it does not:
```python
x, y, z = symbols("x y z")
print factor(x*y + x*z)
print factor(z + x*y + x*z)
```
returns:
> x*(y + z)
> x*y + x*z + z
Why does the factorization work in the first case but not in the second?

**Comment by jksuom** [comment] 2018-05-25 09:04
`factor` tries to find the irreducible factors of a polynomial. `z + x*y + x*z` is returned as such because it is irreducible.

**Comment by schymans** [comment] 2018-05-25 09:17
Is it possible then to sub-divide a polynomial into parts?

**Comment by asmeurer** [comment] 2018-05-25 19:57
See also https://github.com/sympy/sympy/issues/11869. Closing this as a duplicate of that.

**Closed by asmeurer** 2018-05-25 19:57 UTC
