### ISSUE TITLE
Why Function(u'f') raise exception?

### ISSUE THREAD

**Issue by satels** [sympy/sympy#8960] opened 2015-02-06 18:33 UTC
``` python
In [1]: from sympy import *

In [2]: Symbol(u'x')
Out[2]: x

In [3]: Function(u'f')
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-8fff946617db> in <module>()
----> 1 Function(u'f')

sympy/core/cache.pyc in wrapper(*args, **kwargs)
     91                     retval = cfunc(*args, **kwargs)
     92                 except TypeError:
---> 93                     retval = func(*args, **kwargs)
     94                 return retval
     95

sympy/core/function.pyc in __new__(cls, *args, **options)
    354         # Handle calls like Function('f')
    355         if cls is Function:
--> 356             return UndefinedFunction(*args, **options)
    357
    358         n = len(args)

sympy/core/function.pyc in __new__(mcl, name, **kwargs)
    708     """
    709     def __new__(mcl, name, **kwargs):
--> 710         ret = BasicMeta.__new__(mcl, name, (AppliedUndef,), kwargs)
    711         ret.__module__ = None
    712         return ret

TypeError: type() argument 1 must be string, not unicode

```

**Comment by maniteja123** [comment] 2015-02-07 20:00
I think it is due to the argument ``name`` passed in [here](https://github.com/sympy/sympy/blob/master/sympy/core/function.py#L710)

Making it

   ret = BasicMeta.__new__(mcl, str(name), (AppliedUndef,), kwargs)

instead of

   ret = BasicMeta.__new__(mcl, name, (AppliedUndef,), kwargs)

should probably work, since an ``unicode`` argument is causing the exception., whilst a ``str`` isn't.

I am new to sympy, but as I was just looking at the issues, saw this come up and answered. Please do mention if there is a reason why ``unicode`` causes an exception to be raised.

**Comment by pelegm** [comment] 2015-02-11 17:21
Is this not a duplicate of #8312?

**Comment by AadityaNair** [comment] 2015-02-13 19:31
I would like to work on this issue.
will encoding `name` to UTF8 be enough ?

**Comment by asmeurer** [comment] 2015-02-13 21:48
Effectively, this is correct, though. Undefined functions are classes and in Python 2, classes have to be ASCII strings.

**Comment by asmeurer** [comment] 2015-02-13 21:49
What is the behavior of `name.encode('ascii','ignore')` if `name` is non-ASCII?

**Comment by AadityaNair** [comment] 2015-02-14 11:10
I have generated a PR. Please review.

**Comment by ronanpaixao** [comment] 2016-01-09 17:06
Just a note: this is specially annoying if using:

    from __future__ import unicode_literals

which is common enough to be included in my default headers.

**Comment by namannimmo10** [comment] 2020-02-09 10:46
@oscarbenjamin @asmeurer, this issue can be closed now. 
```
>>> from sympy import Symbol, Function
>>> Symbol(u'x')
x
>>> Function(u'f')
f
>>> from __future__ import unicode_literals
>>> Function('f')
f
```
Along with [#8312](https://github.com/sympy/sympy/issues/8312)... both are duplicates.

**Comment by oscarbenjamin** [comment] 2020-02-09 11:13
Python 2 support is dropped so this can be closed now

**Closed by oscarbenjamin** 2020-02-09 11:13 UTC
Labels: Dropping Python 2, core
