### ISSUE TITLE
CodeGen : Implementing for Sum()

### ISSUE THREAD

**Issue by SatyaPrakashDwibedi** [sympy/sympy#12356] opened 2017-03-19 14:43 UTC
For e.g consider:
```
>>> k=symbols('k')
>>> Sum(k,(k,0,9))
Sum(k, (k, 0, 9))
>>> print ccode(Sum(k,(k,0,9)))
// Not supported in C:
// tuple
Sum(k, (k, 0, 9))
>>> print fcode(Sum(k,(k,0,9)))
C     Not supported in Fortran:
C     tuple
      Sum(k, (k, 0, 9))
>>> print rcode(Sum(k,(k,0,9)))
// Not supported in R:
// tuple
Sum(k, (k, 0, 9))
```
but if I do:
```
>>> print ccode(Sum(k,(k,0,9)).doit())
45
>>> print rcode(Sum(k,(k,0,9)).doit())
45
```
I think it would be nice if
```
 >>>print ccode(Sum(k**2,(k,0,9)),assign_to="var")
var=0;
for ( k=0 ; k<=9 ; k++)
var=var+k**2;
```
and similarly for `fcode` ,`rcode`,`jscode` etc.

**Comment by Upabjojr** [comment] 2017-03-19 16:39
> `ccode(Sum(k**2,(k,0,9)),assign_to="var")`

Oh, yeah. This could help for extremely large numbers for which python is too slow.

**Comment by Upabjojr** [comment] 2017-03-19 16:43
There are already methods to generate for-loops in the code printer. I think this could be solved by adding a few lines to the `CodePrinter` class.

**Comment by SatyaPrakashDwibedi** [comment] 2017-03-19 16:53
@Upabjojr yes I think you are right.

**Comment by bjodah** [comment] 2017-03-19 20:04
Doing the summation in C makes sense when we don't know the limits beforehand. e.g.
```
>>> x = IndexedBase('x')
>>> l, u = symbols('l u', integer=True)
>>> i = Idx('i', (l, u))
>>> s = Sum(x[i], i)
>>> ccode(s)
'// Not supported in C:\n// tuple\nSum(x[i], (i, l, u))'
```
or
```
>>> ccode(s, assign_to='tot')
...
NotImplementedError: FIXME: No specialized handling of type <class 'sympy.concrete.summations.Sum'>
```

**Comment by SatyaPrakashDwibedi** [comment] 2017-03-20 02:03
@bjodah yes you are right but I this is regarding #12313 what about this one?
I am thinking of adding `isinstance(rhs,Sum)` to `_print_Assignment ` in base class `codeprinter` as this can be used by all code generators because I think the fix is needed to be done for every language

**Comment by asmeurer** [comment] 2017-03-20 03:59
Dupe of https://github.com/sympy/sympy/issues/10194

**Comment by SatyaPrakashDwibedi** [comment] 2017-03-20 05:32
@asmeurer Ok. 
But is my approach for solving it is correct?
I have solved for `ccode`,`fcode`,`jscode`,`rcode` and only some is left when it will be complete I will refer there and will close this.

**Comment by asmeurer** [comment] 2017-03-20 18:48
The issue is handling Sums as part of larger expressions. As far as I know, you can't have a loop inside an expression in C (don't know about the other languages). That's why I started working on the ast objects in sympy.codegen, so we can start to represent non-expression code objects for printing. But the For object was never finished (in particular, https://github.com/sympy/sympy/pull/11278 needs to be finished to be able to represent symbolic limits, if you want to pick up the work and finish that PR, go ahead).

**Comment by asmeurer** [comment] 2017-03-20 18:51
And we really should think about clean ways to separate expression and non-expresssion printing in the code printers. If someone writes a C template, and has `f({code})` and replaces `{code}` with `ccode(expr)`, that will be invalid C if `ccode` for `expr` happens to return a non-expression (like a for loop). So I think all the code printers need some `expression=True` flag, and there needs to be a clean separation between the two in the printers.

**Comment by bjodah** [comment] 2017-03-20 19:21
`expression=True` is what `assign_to=None` does right now or am I missing someting?
Perhaps we should even deprecate the `assign_to` kwarg once we have some other printer-like class that can handle a proper ast.

**Comment by SatyaPrakashDwibedi** [comment] 2017-03-20 19:24
@bjodah I agree with you.
Won't it be nice if we implement using `Eq()`.

**Comment by asmeurer** [comment] 2017-03-20 19:31
Yes, I would deprecate (eventually) assign_to in favor of using an Assignment. 

Setting assign_to requires that the expression be a value. You can break certain non-expressions up across assignments like if/else chains, but consider something like a for loop or a code block. It isn't an expression, but also doesn't really have a value to assign to. So I think there is some confusion. assign_to='x' (almost always) requires an expression. Most non-expressions can't be assigned because they don't really have a value. But on the other hand, if you are inserting your expression inside something else (`f({code})`) you don't want to add an assignment. 

Perhaps also muddling the discussion is the fact that in C, assignments are expressions (but that certainly isn't the case in all languages, e.g., Python).

**Comment by SatyaPrakashDwibedi** [comment] 2017-03-20 19:36
@asmeurer I think setting a default flag in `settings` and overriding that in `ccode` will work.

**Comment by SatyaPrakashDwibedi** [comment] 2017-03-20 21:06
@asmeurer can we do like this:
```
>>>ccode(sin(Sum(x,(x,y,z))), assign_to='var')
'for (x=y ; x<=z ; x++)
var = var+x;
var = sin(var);'
```
Will it work this way

**Comment by asmeurer** [comment] 2017-03-20 21:27
That works, yes, but the point is that that code cannot be inserted arbitrarily into some other C code. So if someone writes some C boilerplate, with something like

```C
double x;
x = {{{code}}};
```

and replaces `{{{code}}}` with `ccode(expr)`, it won't work (in general, the boilerplate would be more complicated than that). So you can only print something like that if you know the code is going to be inserted into somewhere in the code where a block of statements can go.

There was also some discussion of using blocks in C (statements surrounded by curly braces) to keep things clean when doing this (i.e., put the loop in a block, so that you can initialize the temporary variables).

**Comment by SatyaPrakashDwibedi** [comment] 2017-03-21 18:29
@asmeurer Can we do this :
say for `Sum()`:
```
>>>ccode(sin(Sum(x,(x,y,z))), assign_to='var')
```
we can run `Sum(x,(x,y,z)).doit()` on background and return
```
var = sin(-1.0L/2.0L*pow(y, 2) + (1.0L/2.0L)*y + (1.0L/2.0L)*pow(z, 2) + (1.0L/2
.0L)*z);
```
Will this work? I mean here we have no loop inside an expression.

**Comment by asmeurer** [comment] 2017-03-21 19:00
That certainly works when the sum has a closed form. The use-case I am interested in is computing dot products (https://github.com/sympy/sympy/issues/10163), which is basically `Sum(x[i]*y[i], (i, 0, n-1))`. If `n` is known ahead of time, you can expand the sum, but if it isn't, you have to codegen a loop.

**Comment by SatyaPrakashDwibedi** [comment] 2017-03-21 19:10
@asmeurer can't we do that using a function to return the value.

**Comment by asmeurer** [comment] 2017-03-21 19:13
Yes, that is a workable solution. The end-goal is for SymPy to be able to code generate as much as possible, so that you have to write minimal boilerplate.

**Comment by SatyaPrakashDwibedi** [comment] 2017-03-21 19:14
@asmeurer ok

**Comment by SatyaPrakashDwibedi** [comment] 2017-03-21 19:28
@asmeurer `x` and `y` are vectors right?? :-P I am not going to delete this like last one.

**Comment by asmeurer** [comment] 2017-03-21 20:06
Yes, they would be either Indexed objects or MatrixSymbol objects (probably the latter, as we now have `DotProduct`). They would codegen to "x[i]", that is, arrays in C.

**Comment by SatyaPrakashDwibedi** [comment] 2017-03-21 22:05
I think this might work:
1.make a `cfunctions` module as @bjodah done in #12357 
2.In that add a `Sum` defined by us.
3.While generating code we can display `Sum` function which will be used as some kind of generalised function generated when Sum encountered.
else:
have a look at `qsort` in C. For this a new header file is to be added not in `math.h`

**Comment by SatyaPrakashDwibedi** [comment] 2017-03-22 05:14
I mean include all loop returning strings from `ccode` in a headerfile

**Comment by asmeurer** [comment] 2017-03-22 18:00
I believe this is how Mathematica handles this.

**Comment by SatyaPrakashDwibedi** [comment] 2017-03-22 18:08
@asmeurer How should We add that feature in `sympy` or is there any other way to solve this .

**Comment by asmeurer** [comment] 2017-03-22 20:08
The other way to solve it is the way I discussed at https://github.com/sympy/sympy/issues/10194 (by the way, I'm going to go ahead and close this as a duplicate of that issue, to keep the issues clean, but feel free to continue discussing here or over on that issue). Basically by being able to print loops, and having some way print larger, non-expression blocks of code.

Whichever way we solve this (and there could be multiple ways), we should think about the architecture of the codegen module. We've already been adding ad hoc solutions to the various printers for some time, and it's becoming less and less clear what they do and what they should do, especially with respect to printing expressions vs. non-expressions.

**Closed** 2017-03-22 20:07 UTC
Labels: duplicate

**Comment by SatyaPrakashDwibedi** [comment] 2017-03-24 00:40
@asmeurer As you have stated the use of `mdefs.h` can't it be done?
I mean in that way we can do the mapping from `//Not Supported in C` to the header files they are in and add them when encountered.

**Comment by SatyaPrakashDwibedi** [comment] 2017-03-24 00:56
Reg. header file approach:

- Define a C header file say`pythonc.h`

- Include all the nonsupported `Sympy` functions and implementation in `C`; basically, we should write a C header file for python's functions.

**Comment by SatyaPrakashDwibedi** [comment] 2017-03-24 17:45
@asmeurer we can't add loop inside an expression in C but we can add recursive function returning result in c. Won't that work?

**Comment by asmeurer** [comment] 2017-03-24 18:05
How would you do it recursively?

**Comment by SatyaPrakashDwibedi** [comment] 2017-03-25 05:06
Consider:
`>>>ccode(Sum(i,(i,0,9)))` should generate
```
inline int Sum(int start,int stop)
{
    static int i=0,var=0;
    if (i<=stop)
    {
        var+=i;
        i++;
        Sum(start,stop);
    }
    return var;
}
```
