### ISSUE TITLE
evaluate_pauli_product breaks commutation rules

### ISSUE THREAD

**Issue by heikoburau** [sympy/sympy#14135] opened 2018-02-09 19:22 UTC
In:
```
evaluate_pauli_product(
    (J1 * Pauli(3) + J2 * Pauli(3)) * Pauli(2)
)
```

Out:
```
sigma2*(J1*sigma3 + J2*sigma3)
```
`J1` and `J2` are scalar symbols.

**Comment by davidboden** [comment] 2024-12-30 08:59
```
from sympy import Symbol, expand
from sympy.physics.paulialgebra import Pauli, evaluate_pauli_product

J1 = Symbol("J1")
J2 = Symbol("J2")

# Without expand
print(evaluate_pauli_product(
    (J1 * Pauli(3) + J2 * Pauli(3)) * Pauli(2)
))

# With expand
print(evaluate_pauli_product(expand(
    (J1 * Pauli(3) + J2 * Pauli(3)) * Pauli(2)
)))
```

Output is:

```
(J1*sigma3 + J2*sigma3)*sigma2
-I*J1*sigma1 - I*J2*sigma1
```

The outputs look correct to me. Perhaps something relevant has changed in `evaluate_pauli_product` since the issue was opened. Might be worth closing this issue?

**Comment by oscarbenjamin** [comment] 2024-12-30 12:15
I went back to sympy 1.1 which is as far as I can go and could not reproduce the output shown in the OP. If that was the output at one time then it was changed a long time ago.

Yes, let's close this.

**Closed by oscarbenjamin** 2024-12-30 12:15 UTC
Labels: physics.quantum
