### ISSUE TITLE
refine should simplify symmetric matrix element

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#16234] opened 2019-03-11 19:29 UTC
`refine` already works on Transpose for symmetric matrices:

```py
>>> X = MatrixSymbol('X', n, m)
>>> refine(Transpose(X), Q.symmetric(X))
X
```

It should also work on MatrixElement

```py
>>> refine(X[0, 1], Q.symmetric(X))
X[0, 1]
>>> refine(X[1, 0], Q.symmetric(X))
X[1, 0]
```

Something like `if (i - j).could_extract_minus_sign()` then reverse i and j should work.

**Comment by Mohitbalwani26** [comment] 2019-03-12 11:59
i would like to work on this issue. so can you please guide me about it?

**Comment by ShubhamKJha** [comment] 2019-03-12 15:17
@asmeurer I tried to duplicate the above code segment
I suppose the the matrix symbol should be
`X = MatrixSymbol('X',n,n)`

**Comment by arooshiverma** [comment] 2019-03-13 04:13
@ShubhamKJha  is correct. 

@asmeurer what do we actually need as an output? Something like:

`
>>> refine(X[0, 1], Q.symmetric(X))
X[0, 1]
>>> refine(X[1, 0], Q.symmetric(X))
X[0,1]
`
Or something like:

`>>> refine(X[0, 1], Q.symmetric(X))
X[0, 1]=X[1,0]
>>> refine(X[1, 0], Q.symmetric(X))
X[1, 0]=X=[0,1]`

Or we can define a new function like `could_extract_minus_sign()` which will return True if we get equal value else False:

`>>>X.can_interchange(i,j)
True`

What are your thoughts about this? Please help me with further work.

**Comment by asmeurer** [comment] 2019-03-13 05:14
`refine` should return the expression simplified, like you do in your first example.

**Comment by ShubhamKJha** [comment] 2019-03-13 05:27
@asmeurer so refine should return the upper triangular matrix.

**Comment by arooshiverma** [comment] 2019-03-13 09:58
Hey @asmeurer ,
What does the following function do?
```expr = expr.func(*args)```

**Comment by asmeurer** [comment] 2019-03-13 18:50
It makes a new expression with the same type as `expr` with arguments `args`. If `args` is `expr.args` it rebuilds the expression (in other words, there is no change).

**Comment by asmeurer** [comment] 2019-03-13 18:51
> @asmeurer so refine should return the upper triangular matrix.

I wouldn't say that. Upper triangular matrices aren't symmetric. Instead, it should canonicalize the indices of a MatrixElement if the matrix is symmetric.

**Comment by ShubhamKJha** [comment] 2019-03-13 19:03
@asmeurer I meant for a symmetric matrix `refine` should return a `MatrixElement` with indices from the Upper triangular part (equivalent to the given element).

**Comment by ShubhamKJha** [comment] 2019-03-13 19:08
Also when we use the following code:
```py
>>> from sympy import *
>>> n,m = symbols('n,m')
>>> X = MatrixSymbol('X',n,m)
>>> refine(Transpose(X), Q.symmetric(X))
X.T
>>>
```
Aren't we imposing the predicate of`Q.symmetric(X)` since `n`,`m` aren't having other assumptions (I believe they shouldn't). Our assumption should infer `n == m` hence we should get `X` instead of `X.T`. Shouldn't this be the expected behaviour?

**Comment by asmeurer** [comment] 2019-03-13 19:14
Yes, I agree that Q.symmetric(X) should force it to deduce that n == m. One could even have a deduction in the assumption system along these lines (although I don't know how well the assumptions can handle == style predicates at this point in time). Or rather, symmetric should imply square, and Q.square(X) should imply that X's rows and columns are equal.  

For your case, it should just return X, but if n and m were instead things that could not be equal, like explicit numbers, the deductions, if implemented properly, would lead to an error due to unsatisfiability.

**Comment by ShubhamKJha** [comment] 2019-03-13 19:17
I believe when someone defines symbols, they should not be provided with any predefined assumptions. So they may be equal (unless specified). I see I can replicate this behaviour if it seems right.

**Comment by arooshiverma** [comment] 2019-03-13 19:19
I have written the code which gives the follows:

```
>>>x=MatrixSymbol('x',4,4)
>>>refine(x[1,0],Q.symmetric(x))
x[0,1]
```

Should I also add conditions of anti-symmetry?Which will give something like:

```
>>>refine(x[1,0],Q.symmetric(x))
-x[0,1]
```
Or should I open  new issue?
How do we take the assumption of anti-symmetry in sympy?

**Comment by Saanidhyavats** [comment] 2020-02-13 01:02
I am contributing on this issue. Will send a pr by today

**Comment by Saanidhyavats** [comment] 2020-02-13 02:06
@asmeurer I have a doubt 
In the code below :
>>> `refine(X[0, 1], Q.symmetric(X))`
>>> `X[0, 1] `
here answer could be `X[1,0]` as well . Why we are choosing ` X[0,1]` over `X[1,0]`.

**Comment by asmeurer** [comment] 2020-02-13 18:22
It just needs to pick one or the other consistently so they cancel. That's what `could_extract_minus_sign` does.

**Comment by progmatic-99** [comment] 2020-03-22 05:05
is there any more work that needs to be done?

**Comment by naveensaigit** [comment] 2021-04-11 03:57
The merged PR seems to have fixed this. On current master, I get
``` python
>>> from sympy import *
>>> m, n = symbols('m n')
>>> X = MatrixSymbol('X', n, m)
>>> refine(X[0, 1], Q.symmetric(X))
X[0, 1]
>>> refine(X[1, 0], Q.symmetric(X))
X[0, 1]
```

**Closed** 2021-04-11 09:38 UTC
Labels: Easy to Fix, assumptions, matrices.expressions
