### ISSUE TITLE
Solve: Output format don't consistent with ineq

### ISSUE THREAD

**Issue by latot** [sympy/sympy#11661] opened 2016-09-26 12:51 UTC
Hi, well this is very confuse, when we solve ineq or ineq + eq the output don't is consistent with the normal output:

```
>>> solve([Eq(x**2-1,0), x>0])
Eq(x, 1)
>>> solve([Eq(x**2-1,0), x>0], set=True)
Eq(x, 1)
>>> solve([Eq(x**2-1,0), x>0], dict=True)
Eq(x, 1)
>>> solve([Eq((x-1)*(x-2)*(x-3),0), x>0], dict=True)
Or(Eq(x, 1), Eq(x, 2), Eq(x, 3))
```

expected of the first expression:

```
>>> solve([Eq(x**2-1,0), x>0], dict=True)
{x: 1}
```

Thx. Cya.

**Comment by cbm755** [comment] 2019-11-19 05:14
Just tested with the 1.5b1, got this:
```
>>> solve([Eq(x**2-1,0), x>0], dict=True)                                            
[{x: 1}]
```
which I guess is good (not sure about the list).

But there is a regression
```
# good
>>> solve([Eq((x-1)*(x-2)*(x-3),0), x>0])
Or(Eq(x, 1), Eq(x, 2), Eq(x, 3))

# bad
>>> solve([Eq((x-1)*(x-2)*(x-3),0), x>0], dict=True)                                 
[{x: 3}]
```

**Comment by cbm755** [comment] 2019-11-19 06:29
@czgdp1807 and #17723, see this.  The early returns eat the other solutions (I guess)

**Comment by czgdp1807** [comment] 2019-11-19 06:33
Yes it looks like that.
So, I think we should revert #17723 
I will open a PR to do so, if you say.

**Comment by czgdp1807** [comment] 2019-11-19 06:47
I think we need to revert it from `1.5` branch.

**Comment by czgdp1807** [comment] 2019-11-19 06:55
I will open two PRs shortly, one to revert #17723 with `1.5` as base and another for `master` to fix the original issue. Please let me know if any other thing is needed. Apologies for inconvenience.

**Comment by cbm755** [comment] 2019-11-19 20:41
Closing as dupe of #13534.

**Closed by cbm755** 2019-11-19 20:41 UTC
Labels: solvers.solve

**Comment by latot** [comment] 2019-11-19 21:16
D:

Its not a dupe of that issue, that issue is dupe of this :3 

This is a older issue.

Anyway is good have only one.

Thx.

**Comment by cbm755** [comment] 2019-11-19 23:18
You're right ;-)  important thing is get your three-root test in (if this change is made) b/c the previous (reverted) change broke that.
