### ISSUE TITLE
Replace weirdness

### ISSUE THREAD

**Issue by username27** [sympy/sympy#21841] opened 2021-08-08 17:29 UTC
Consider the following code snippet wherein i try to replace a product of two binomial coefficients

```
from sympy import *
from sympy.abc import k, x
a = Wild('a')
b = Wild('b')

pattern = binomial(k,a)*binomial(k,b)
replacement = x

original= binomial(k, 1, evaluate=False)*binomial(k, 1, evaluate=False)
original.replace(pattern , replacement)
```

This returns

![](https://i.stack.imgur.com/zf9CU.png)

The replacement did not work. However if either one of the binomial coefficients has a different number than 1 it does work! For example, the following code
```
a = Wild('a')
b = Wild('b')

pattern = binomial(k,a)*binomial(k,b)
replacement = x

original= binomial(k, 1, evaluate=False)*binomial(k, 2, evaluate=False)
original.replace(pattern , replacement)
```
Returns

![](https://i.stack.imgur.com/Racas.png)

Is this a bug or did i do something wrong?

For clarity: i know that the first binomial coefficients are simply equal to k, i want to keep them in this form however so i can replace them together with a bunch of other coefiicients. See also [my post on stackoverflow](https://stackoverflow.com/questions/68702235/need-help-understanding-weird-replace-behaviour). Thanks in advance!

**Comment by username27** [comment] 2021-08-08 17:33
Using sympy version 1.8 btw

**Comment by oscarbenjamin** [comment] 2021-08-08 23:24
Thanks for reporting this. I saw this on SO and opened a separate issue #21842 before seeing this one. Since #21842 explains what the problem is I'll close this one as a duplicate.

**Closed by oscarbenjamin** 2021-08-08 23:24 UTC
