### ISSUE TITLE
Check what Wolfram alpha gives for minimal_polynomial(1/(2**(Rational(1,3)) + 2**(Rational(1,4))), x), compare this to SymPy

### ISSUE THREAD

**Issue by Roland-Sands** [sympy/sympy#14228] opened 2018-02-16 00:51 UTC
I raised this as a bug, and it was closed
I am extremely unhappy with this, highly disrespectful

If Sympy says that min poly is f, where f has degree n, then the correct min poly is `f(1/x)*x**n`

**Comment by skirpichev** [comment] 2018-02-16 01:13
Hmm, Mathematica 7 give me same output as Sympy (or Diofant):
```
In [1]: minimal_polynomial(1/(2**(Rational(1,3)) + 2**(Rational(1,4))), x)
Out[1]: 
   12       11        10       9       8        7       6      4      3    
8⋅x   - 96⋅x   - 240⋅x   - 32⋅x  + 12⋅x  - 192⋅x  + 24⋅x  - 6⋅x  - 8⋅x  + 1
```

Mathematica:
```
In[1]:= MinimalPolynomial[(2^(1/4) + 2^(1/3))^(-1)]

Out[1]= 1 - 8 #1^3 - 6 #1^4 + 24 #1^6 - 192 #1^7 + 12 #1^8 - 
  32 #1^9 - 240 #1^10 - 96 #1^11 + 8 #1^12 &
```

Why do you think it's wrong?

**Comment by skirpichev** [comment] 2018-02-16 01:15
btw, WA thinks [same](http://www.wolframalpha.com/input/?i=minimal+polynomial+(2%5E(1%2F4)+%2B+2%5E(1%2F3))%5E(-1)).

**Comment by asmeurer** [comment] 2018-02-16 01:57
@Roland-Sands if you think the bug was closed incorrectly, please comment such on the issue. An issue being closed isn't a final thing, and most definitely shouldn't be taken as a personal thing. I described in the issue (https://github.com/sympy/sympy/issues/14227 for reference) why I believe the bug was invalid. If you disagree, just leave a comment about why, and we can discuss it, and if you are right, we will reopen the issue. Issues can always be reopened, and you can always continue the discussion on a closed issue. 

I closed the issue because as I saw it, the bug being reported was not really a bug, due to a mistake on your part. As you can see, we currently have over 2000 open issues, so whenever I see something that can help triage them, such as closing issues that I believe are invalid, I do so. But if the person who opens the issue wants to reopen it, we can discuss whether or not the issue is valid, and it can be reopened. But please don't open a new issue for the same thing. This fractures the discussion, and makes our open issues problem worse. 

I am closing this issue as a duplicate of https://github.com/sympy/sympy/issues/14227. It can be reopened if that will make you feel better, but I really do believe that there is no bug (as I outlined over there).

**Closed by asmeurer** 2018-02-16 01:57 UTC

**Comment by Roland-Sands** [comment] 2018-02-16 03:43
In a calculation, I confused the minimal polynomial of 1/x with the minimal polynomial of x, and I reacted badly when that issue was closed

I'm sorry
