### ISSUE TITLE
Document how to access the solutions from solve

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#7615] opened 2014-06-19 03:20 UTC
We have to keep in mind with SymPy that some users are really new to Python. They don't necessarily know how lists and dictionaries work. Consider http://stackoverflow.com/q/24281298/161801 and http://stackoverflow.com/q/21371093/161801. Both questions boil down to the person not knowing how to access an element of a dictionary. 

We should document this better, probably in the tutorial.

**Comment by mjeromin** [comment] 2016-11-14 19:51
@asmeurer Is the point here is that we could be alienating users by not providing this example? Would it be more appropriate to add it to the [FAQ wiki](https://github.com/sympy/sympy/wiki/Faq)?

**Comment by asmeurer** [comment] 2016-11-14 21:42
The tutorial is what people read the most of. Probably the solve docstring is common as well.  Note that since this issue was opened the tutorial has been changed to use solveset. However, I don't see obvious examples of how to access solutions. With solveset it's even worse because people don't realize how to access the solutions from sets.

**Comment by Yathartha22** [comment] 2017-02-09 04:57
@asmeurer please have look at the PR and review it.

**Comment by ishanaj** [comment] 2017-07-15 08:10
@asmeurer Is there anything else that needs to be done in this issue. If so I would like to take this up.

**Comment by Yathartha22** [comment] 2017-07-16 06:39
I think the purpose of the issue is being solved. @asmeurer It would be better if we close the issue, what do you suggest?

**Comment by oscarbenjamin** [comment] 2020-03-08 00:21
Closing as fixed in #12141

**Closed by oscarbenjamin** 2020-03-08 00:21 UTC
Labels: Documentation, Easy to Fix, solvers, solvers.solve, solvers.solveset
