### ISSUE TITLE
Simplification gives wrong results

### ISSUE THREAD

**Issue by HerpDerpongton** [sympy/sympy#19407] opened 2020-05-23 00:16 UTC
I am trying to simplify a simple equation:

```
import sympy

q, r = sympy.symbols("q r")
equation = (((-q + r) - (q - r)) <= 0).simplify()
print(equation) # q >= r

equation = ((sympy.sqrt(2) * (-q + r) - sympy.sqrt(2) * (q - r)) <= 0).simplify()
print(equation) # q <= r
```

As you can see from the comments, the results differ; but they should not, if I see that correctly. I am using Sympy version 1.5.1 and this happens on either Python 3.6.6 and 3.7.7. See also [this SO question](https://stackoverflow.com/questions/61965660/does-sympy-give-errorneous-simplifications). As was pointed out in the comments, this also happens for other coefficients other thant `sympy.sqrt(2)`.

**Comment by smichr** [comment] 2020-05-23 11:57
Line 362 of https://github.com/sympy/sympy/blob/master/sympy/core/relational.py (now blank) should read
```python
        if scale.is_negative:
            r = r.reversed.func(*r.args)
```
In context, it is
```python
        if constant != 0:
            # lhs: expression, rhs: constant
            newexpr = Add(*[i*j for i, j in nzm])
            r = r.func(newexpr, -constant/scale)
        else:
            # keep first term on lhs
            lhsterm = nzm[0][0]*nzm[0][1]
            del nzm[0]
            newexpr = Add(*[i*j for i, j in nzm])
            r = r.func(lhsterm, -newexpr)
        if scale.is_negative:
            r = r.reversed.func(*r.args)
```

**Comment by smichr** [comment] 2020-05-23 12:00
good tests:
```python
assert simplify(sqrt(2)*(-2*q+2*r)<=-1) == q - r >= sqrt(2)/4
assert simplify(sqrt(2)*(-2*q+2*r)<=0) == q >= r
```

**Comment by smichr** [comment] 2020-05-23 12:06
On second thought, perhaps it is `gcd` that should be fixed to always give a positive constant?
```
>>> gcd((2,4))
2
>>> gcd((-2,-4))
2
>>> gcd((sqrt(2),sqrt(2)))
sqrt(2)
>>> gcd((-sqrt(2),-sqrt(2)))
-sqrt(2)
```

**Comment by oscarbenjamin** [comment] 2020-05-23 12:15
I'm unable to reproduce the problem here.

**Comment by smichr** [comment] 2020-05-23 14:22
Did you check the `gcd` results? I confirmed with Python on `repl.it`.

**Comment by HerpDerpongton** [comment] 2020-05-23 14:44
I should add that this only happens from version 1.5 onward. I reproduced it with all following versions up to 1.6rc2.

**Comment by oscarbenjamin** [comment] 2020-05-23 14:49
I can see the gcd result but I can't reproduce the simplify result from the OP except in sympy 1.4.

**Comment by smichr** [comment] 2020-05-23 19:10
Try print out the scale value. I confirmed the OP issue using 1.5.1.

**Comment by KaustubhDamania** [comment] 2020-06-10 10:39
Hey, is this issue open? I'd like to solve this issue.

**Comment by KaustubhDamania** [comment] 2020-06-11 13:26
> On second thought, perhaps it is `gcd` that should be fixed to always give a positive constant?
> 
> ```
> >>> gcd((2,4))
> 2
> >>> gcd((-2,-4))
> 2
> >>> gcd((sqrt(2),sqrt(2)))
> sqrt(2)
> >>> gcd((-sqrt(2),-sqrt(2)))
> -sqrt(2)
> ```

@smichr I think fixing the GCD as a non-negative integer would be a proper solution to this problem

**Closed** 2020-06-17 15:20 UTC
Labels: Easy to Fix, Wrong Result, simplify
