### ISSUE TITLE
solveset returns an unevaluated ConditionSet for solvable equation

### ISSUE THREAD

**Issue by kshitij10496** [sympy/sympy#10807] opened 2016-03-12 19:27 UTC
In the latest master, 
```python
In []: x = symbols('x')

In []: f = 1/(Abs(x+1)) - 1

In []: solveset(f, x, S.Reals)
Out[]: ConditionSet(x, Eq((-Abs(x + 1) + 1)/Abs(x + 1), 0), (-oo, oo))
```

Clearly, the solutions should are `{-2, 0}`. 
I think the issue here lies with solving `f` after using `together` [here](https://github.com/sympy/sympy/blob/master/sympy/solvers/solveset.py#L544).
This changes the property of `f` from an `is_Add` to `is_Mul`, which in turn gives a different result.

**Comment by smichr** [comment] 2016-03-13 12:48
essentially a duplicate of #10023

**Closed by smichr** 2016-03-13 12:48 UTC
