### ISSUE TITLE
Puiseux polynomials does not work with algebraic extensions

### ISSUE THREAD

**Issue by galvinograd** [sympy/sympy#24395] opened 2022-12-16 07:25 UTC
Hey,

I'm having trouble defining Puiseux polynomials over algebraic extensions of QQ.
I think it has something to do with sympy misidentifying "x" as not monomial.

Succeed:
```python
import sympy as sp
from sympy.abc import x

D = sp.QQ[x]
f = D(x) ** sp.QQ(1, 2)
```

Failed:
```python
import sympy as sp
from sympy.abc import x

D = sp.QQ.algebraic_field(sp.sqrt(2))[x]
f = D(x) ** sp.QQ(1, 2)
```

**Comment by oscarbenjamin** [comment] 2022-12-16 10:35
It's not really clear to me if Puiseux polynomials should be considered a supported case or not. You can see some discussion of why it works at all here:
https://docs.sympy.org/latest/modules/polys/ringseries.html

**Comment by oscarbenjamin** [comment] 2022-12-16 11:19
The problem is here:
https://github.com/sympy/sympy/blob/4801871259a1a8db27bae99f5ea4db109bb1320a/sympy/polys/rings.py#L1175-L1178
```
ipdb> p coeff
ANP([mpq(1,1)], [mpq(1,1), mpq(0,1), mpq(-2,1)], QQ)
ipdb> p coeff == 1
False
ipdb> p ring.domain.one
ANP([mpq(1,1)], [mpq(1,1), mpq(0,1), mpq(-2,1)], QQ)
ipdb> p coeff == ring.domain.one
True
```
The fix is
```diff
diff --git a/sympy/polys/rings.py b/sympy/polys/rings.py
index 994cc57..12bd2fc 100644
--- a/sympy/polys/rings.py
+++ b/sympy/polys/rings.py
@@ -1172,7 +1172,7 @@ def __pow__(self, n):
         elif len(self) == 1:
             monom, coeff = list(self.items())[0]
             p = ring.zero
-            if coeff == 1:
+            if coeff == ring.domain.one:
                 p[ring.monomial_pow(monom, n)] = coeff
             else:
                 p[ring.monomial_pow(monom, n)] = coeff**n
```

**Comment by galvinograd** [comment] 2022-12-17 05:54
Will the patch be merged, or should I patch it locally?

**Comment by oscarbenjamin** [comment] 2022-12-17 11:06
The patch needs a test but then it can be merged.

**Closed** 2022-12-20 22:35 UTC
Labels: polys
