### ISSUE TITLE
OverflowError when calling subsn on certain power expressions

### ISSUE THREAD

**Issue by DRMacIver** [sympy/sympy#14704] opened 2018-05-09 09:37 UTC
Running the following code produces an `OverflowError`:

```python
from sympy.abc import a


if __name__ == '__main__':
    b = a ** a
    c = b ** b
    c.subs({a: -144})
```
When running current master (14307a995e3c5c967b53201977dcd10de3004911) on Python 3.6.0 I see the following:

```
Traceback (most recent call last):
  File "/home/david/scratch/sympy/sympy/core/power.py", line 74, in integer_nthroot
    guess = int(y**(1./n) + 0.5)
OverflowError: int too large to convert to float

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/david/projects/shrink-evaluation/sympy/bug1.py", line 7, in <module>
    c.subs({a: -144})
  File "/home/david/scratch/sympy/sympy/core/basic.py", line 919, in subs
    rv = rv._subs(old, new, **kwargs)
  File "/home/david/scratch/sympy/sympy/core/cache.py", line 93, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/home/david/scratch/sympy/sympy/core/basic.py", line 1033, in _subs
    rv = fallback(self, old, new)
  File "/home/david/scratch/sympy/sympy/core/basic.py", line 1010, in fallback
    rv = self.func(*args)
  File "/home/david/scratch/sympy/sympy/core/cache.py", line 93, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/home/david/scratch/sympy/sympy/core/power.py", line 286, in __new__
    obj = b._eval_power(e)
  File "/home/david/scratch/sympy/sympy/core/numbers.py", line 1714, in _eval_power
    expt.p*(expt.q - 1), expt.q) / \
  File "/home/david/scratch/sympy/sympy/core/expr.py", line 154, in __pow__
    return self._pow(other)
  File "/home/david/scratch/sympy/sympy/core/decorators.py", line 91, in __sympifyit_wrapper
    return func(a, b)
  File "/home/david/scratch/sympy/sympy/core/decorators.py", line 132, in binary_op_wrapper
    return func(self, other)
  File "/home/david/scratch/sympy/sympy/core/expr.py", line 150, in _pow
    return Pow(self, other)
  File "/home/david/scratch/sympy/sympy/core/cache.py", line 93, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/home/david/scratch/sympy/sympy/core/power.py", line 286, in __new__
    obj = b._eval_power(e)
  File "/home/david/scratch/sympy/sympy/core/numbers.py", line 2264, in _eval_power
    x, xexact = integer_nthroot(abs(self.p), expt.q)
  File "/home/david/scratch/sympy/sympy/core/power.py", line 76, in integer_nthroot
    exp = _log(y, 2)/n
OverflowError: int too large to convert to float
```

I get similar behaviour on sympy 1.1.1.

**Comment by jksuom** [comment] 2018-05-09 11:46
`exp = _log(y, 2)/n` will fail when `n` is huge because `_log(y, 2)` is a float and Python tries to convert `n` to the same type. The error can be avoided by rounding the logarithm to an integer: `exp = int(_log(y, 2))/n`

**Comment by htrivedi04** [comment] 2018-05-16 08:40
Easy fix. I'm working on this! :+1: Waiting for completion of tests.

**Comment by iwhiz** [comment] 2018-05-18 08:49
@htrivedi04 Are all the tests successful at your side??

**Comment by m-agboola** [comment] 2018-12-27 06:50
Is this issue still opened?

**Comment by aaselvam** [comment] 2020-10-27 06:15
It seems that no one has fixed this issue as it is still reproducible, I will work on it.

**Comment by ayushbisht2001** [comment] 2021-02-10 11:39
I would like to work  on this issues

**Comment by abhik-123** [comment] 2022-01-10 16:12
i would like to work on this issue, i am a beginner to open source contribution

**Comment by Sushmita10062002** [comment] 2022-02-06 07:25
I would like to work on this issue

**Comment by oscarbenjamin** [comment] 2022-02-06 12:04
Anyone is welcome to work on this. I'm not sure why so many people have said that they wanted to work on this but it remains unfixed. Looking at the discussion in #17636 it seems that it somehow got sidetracked by a different more complicated problem which is to do with not wanting extremely large powers to evaluate automatically.

The basic issue here is just that Overflow error should not be raised in this:
```python
In [1]: a = 63708717381247861841182616291356534373711642773756847120291210786024386828110496195538408
   ...: 541399667331347621162040492392564612493395424177880628868686935437933360262424507198720775910
   ...: 419712130236624297480419399634557904200517799815616339247475658150180595343449836054056764117
   ...: 784476948835303036764959289320144896

In [2]: integer_nthroot(a, a)
---------------------------------------------------------------------------
...
File ~/current/sympy/sympy.git/sympy/core/power.py:103, in _integer_nthroot_python(y, n)
    101     guess = int(y**(1./n) + 0.5)
    102 except OverflowError:
--> 103     exp = _log(y, 2)/n
    104     if exp > 53:
    105         shift = int(exp - 53)

OverflowError: int too large to convert to float
```
That can be fixed as noted above by converting the output of `log` with `int`. Doing that we then find that the function hangs here:
https://github.com/sympy/sympy/blob/3b96442d2d72d3fe3243788372898898bad72280/sympy/core/power.py#L120-L123
It hangs while trying to compute `2**a` which would is clearly not going to succeed because the result requires `a` bit of memory and no real computer has that much RAM.

There should probably be some better checking to see that it clearly isn't possible to have an nth root of n except when n is equal to 1 because if `n >= 2` then `n < 2**n` so `n**(1/n) < 2`.

There could maybe be some other way to verify that in `integer_nthroot(x, n)` we have an `n` that is clearly too large. For large enough `n` the answer will always just be `(1,False)`. The least possible nth root greater than 1 is 2. An obvious check would be something to do with the number of bits in the two numbers. Clearly `2**n` has `n` bits so if `x` has fewer than `n` bits them `integer_nthroot(x, n)` should just return `(1,False)`:
```python
In [6]: a = 63708717381247861841182616291356534373711642773756847120291210786024386828110496195538408
   ...: 541399667331347621162040492392564612493395424177880628868686935437933360262424507198720775910
   ...: 419712130236624297480419399634557904200517799815616339247475658150180595343449836054056764117
   ...: 784476948835303036764959289320144896

In [7]: a.bit_length()
Out[7]: 1033

In [8]: a.bit_length() < a
Out[8]: True
```

The other question is whether `integer_nthroot` should be called by `_eval_power` when such large integers are involved. There should be some limit on these things. That's the harder part that has been discussed in #17636.

I suggest to fix this particular issue just by improving `integer_nthroot` with something like:
```diff
diff --git a/sympy/core/power.py b/sympy/core/power.py
index 9b6a527..0ae8d6b 100644
--- a/sympy/core/power.py
+++ b/sympy/core/power.py
@@ -93,7 +93,7 @@ def _integer_nthroot_python(y, n):
     if n == 2:
         x, rem = mpmath_sqrtrem(y)
         return int(x), not rem
-    if n > y:
+    if n > y.bit_length():
         return 1, False
     # Get initial estimate for Newton's method. Care must be taken to
     # avoid overflow
```
(I haven't thought through all corner cases carefully so this should be checked in detail.)

With that change the original problem of overflow when n is converted to float should not be able to happen any more because `y.bit_length()` cannot possibly be much larger than `10**10` so `n` should always be small enough to convert to a float.

With the diff I just showed the output is:
```python
In [1]: from sympy.abc import a

In [2]: b = a ** a
   ...: c = b ** b
   ...: %time d = c.subs({a: -144})
CPU times: user 8 ms, sys: 0 ns, total: 8 ms
Wall time: 4.73 ms

In [3]: d
Out[3]:
 
 110605412120221982363164264394716205509916046482216748472727796503514560465469611450587514828818866894700731184098077070424674467700389197709425119248151801967639344486991664445791511145333559438583849792394791032218583681454513568778366749089684288507978026822632038292993260042494702839067772161387655069695  221210824240443964726328528789432411019832092964433496945455593007029120930939222901175029657637733789401462368196154140849348935400778395418850238496303603935278688973983328891583022290667118877167699584789582064437167362909027137556733498179368577015956053645264076585986520084989405678135544322775
 ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────  ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 110605412120221982363164264394716205509916046482216748472727796503514560465469611450587514828818866894700731184098077070424674467700389197709425119248151801967639344486991664445791511145333559438583849792394791032218583681454513568778366749089684288507978026822632038292993260042494702839067772161387655069696  221210824240443964726328528789432411019832092964433496945455593007029120930939222901175029657637733789401462368196154140849348935400778395418850238496303603935278688973983328891583022290667118877167699584789582064437167362909027137556733498179368577015956053645264076585986520084989405678135544322775
2                                                                                                                                                                                                                                                                                                                     ⋅3                                                                                                                                                                                                                                                                                                            
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                                                                                                                                                                                                                                      6                                                                                                                                                                                                                                                                                                             

310139391
─────────
310139392
         
─────────
         
```

**Comment by gjain-7** [comment] 2022-03-12 09:55
@oscarbenjamin 
> There should probably be some better checking to see that it clearly isn't possible to have an nth root of n except when n is equal to 1 because if `n >= 2` then `n < 2**n` so `n**(1/n) < 2`.
> 
> There could maybe be some other way to verify that in `integer_nthroot(x, n)` we have an `n` that is clearly too large. For large enough `n` the answer will always just be `(1,False)`. 

Note that `integer_nthroot(y, n)` is `(1,False)` iff  `y**(1/n) < 2`.

 `y**(1/n) < 2`  <=> `lg(y)/n < 1` <=> `lg(y) < n` (where `lg` is log2)

Apparently, `lg(y) < n` <=> `floor(lg(y)) < n`

Also, `floor(lg(y)) = y.bit_length() -1`

Therefore, `y.bit_length() -1 < n` <=> `n >= y.bit_length()`, should be the appropiate condtion.

### Corner case (not really)
Therorically, there must be an Overflow when 
- `y.bit_length()==n` and it misses the if condition and
-  `n` is too large to be converted into float.

Minimum value to `n` to be overflowed is `2**1025` (hope this is correct). so `y.bit_length()` will be `2**2025`, which is practically impossible to store.

Therefore as you stated `n > y.bit_length()`, would work just as fine.
All cases covered. This is my analysis.
So I guess this issue can be closed now ? should i make a PR ?

**Comment by oscarbenjamin** [comment] 2022-03-13 19:13
> should i make a PR ?

Yes, go ahead.

**Closed** 2022-03-23 18:17 UTC
Labels: Easy to Fix
