### ISSUE TITLE
constantsimp(C0*C1*x + C1**2,x,2) should simplify things!

### ISSUE THREAD

**Issue by skirpichev** [sympy/sympy#7006] opened 2013-06-27 21:08 UTC
```
Prehaps, C0*x + C1 could be a bit better.
```

Original issue for #7006: http://code.google.com/p/sympy/issues/detail?id=3907
Original author: https://code.google.com/u/113518207426301808764/

**Comment by oscarbenjamin** [comment] 2020-03-04 23:47
It would be nice of constantsimp could do this. I think that constantsimp should be made more generically useful and exposed at top-level in sympy.

**Comment by oscarbenjamin** [comment] 2020-03-05 00:07
Closing as a duplicate of #7247 which links to a paper providing an algorithm for this

**Closed by oscarbenjamin** 2020-03-05 00:07 UTC
Labels: simplify, solvers, solvers.dsolve
