### ISSUE TITLE
Assertion error using integrate in sympy 1.10.1, Python 3.10.5

### ISSUE THREAD

**Issue by nasser1** [sympy/sympy#23948] opened 2022-08-18 20:11 UTC
I am getting this error

```
>python
Python 3.10.5 (main, Jun  6 2022, 18:49:26) [GCC 12.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from sympy import *
>>>F, G, H, a, b, c, d, e, f, g, h, i, k, m, n, p, r, s, t, x=symbols('F G H a b c d e f g h i k m n p r s t x')
>>>integrand=((2*x*exp(x)**2+(2*x**2-2)*exp(x)-2*x)*exp(exp(x))**2*ln(2*exp(x)+2*x)**2+((2*exp(x)*x+2*x)*exp(exp(x))**2+(-6*exp(x)**2*x**2+(-6*x**3+6*x)*exp(x)+6*x**2)*exp(exp(x)))*ln(2*exp(x)+2*x)+(-6*exp(x)*x**2-6*x**2)*exp(exp(x))+exp(x)*x**3+x**4)/(exp(x)*x**3+x**4)
>>>integrate(integrand,x)
```
gives

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.10/site-packages/sympy/integrals/integrals.py", line 1566, in integrate
    return integral.doit(**doit_flags)
  File "/usr/lib/python3.10/site-packages/sympy/integrals/integrals.py", line 613, in doit
    antideriv = self._eval_integral(
  File "/usr/lib/python3.10/site-packages/sympy/integrals/integrals.py", line 956, in _eval_integral
    result, i = risch_integrate(f, x, separate_integral=True,
  File "/usr/lib/python3.10/site-packages/sympy/integrals/risch.py", line 1831, in risch_integrate
    ans, i, b = integrate_primitive(fa, fd, DE)
  File "/usr/lib/python3.10/site-packages/sympy/integrals/risch.py", line 1460, in integrate_primitive
    q, i, b = integrate_primitive_polynomial(p, DE)
  File "/usr/lib/python3.10/site-packages/sympy/integrals/risch.py", line 1409, in integrate_primitive_polynomial
    rv = limited_integrate(aa, ad, [(Dta, Dtb)], DE)
  File "/usr/lib/python3.10/site-packages/sympy/integrals/prde.py", line 837, in limited_integrate
    h, A = param_rischDE(Fa, Fd, G, DE)
  File "/usr/lib/python3.10/site-packages/sympy/integrals/prde.py", line 734, in param_rischDE
    h, B = param_poly_rischDE(a, b, r, n, DE)
  File "/usr/lib/python3.10/site-packages/sympy/integrals/prde.py", line 559, in param_poly_rischDE
    return prde_cancel_liouvillian(b, q, n, DE)
  File "/usr/lib/python3.10/site-packages/sympy/integrals/prde.py", line 481, in prde_cancel_liouvillian
    fi, Ai = param_rischDE(ba, bd, Qy, DE)
  File "/usr/lib/python3.10/site-packages/sympy/integrals/prde.py", line 734, in param_rischDE
    h, B = param_poly_rischDE(a, b, r, n, DE)
  File "/usr/lib/python3.10/site-packages/sympy/integrals/prde.py", line 559, in param_poly_rischDE
    return prde_cancel_liouvillian(b, q, n, DE)
  File "/usr/lib/python3.10/site-packages/sympy/integrals/prde.py", line 481, in prde_cancel_liouvillian
    fi, Ai = param_rischDE(ba, bd, Qy, DE)
  File "/usr/lib/python3.10/site-packages/sympy/integrals/prde.py", line 734, in param_rischDE
    h, B = param_poly_rischDE(a, b, r, n, DE)
  File "/usr/lib/python3.10/site-packages/sympy/integrals/prde.py", line 544, in param_poly_rischDE
    return prde_no_cancel_b_large(b, q, n, DE)
  File "/usr/lib/python3.10/site-packages/sympy/integrals/prde.py", line 355, in prde_no_cancel_b_large
    A = A.row_join(zeros(A.rows, m, DE.t)).col_join(c.row_join(-c))
  File "/usr/lib/python3.10/site-packages/sympy/polys/polymatrix.py", line 253, in col_join
    dm = DomainMatrix.vstack(self._dm, other._dm)
  File "/usr/lib/python3.10/site-packages/sympy/polys/matrices/domainmatrix.py", line 788, in vstack
    return DomainMatrix.from_rep(A.rep.vstack(*(Bk.rep for Bk in B)))
  File "/usr/lib/python3.10/site-packages/sympy/polys/matrices/sdm.py", line 794, in vstack
    assert Bkcols == cols
AssertionError

```

Versions

```
>which python
/usr/bin/python
>python --version
Python 3.10.5
>python
Python 3.10.5 (main, Jun  6 2022, 18:49:26) [GCC 12.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sympy 
>>> sympy.__version__
'1.10.1'
>>> 


```

On Linux Manjaro

**Comment by oscarbenjamin** [comment] 2022-08-18 21:23
The error comes from here in `risch`:
https://github.com/sympy/sympy/blob/f0154339c0b4d2602f0f4a6db4488d572b40e16f/sympy/integrals/prde.py#L353
It's trying to join the matrices horizontally but they need to have the same number of rows. Here the matrices are:
```python
(Pdb) p A
Matrix(0, 2, [])
(Pdb) p c
Matrix([[1]])
(Pdb) p A.row_join(zeros(A.rows, m))
Matrix(0, 3, [])
(Pdb) p c.row_join(-c)
Matrix([[1, -1]])
```
In SymPy 1.8 this "succeeded" because the `0x3` matrix and the `1x2` matrix can apparently be joined into a `1x2` matrix:
```
(Pdb) p A.row_join(zeros(A.rows, m)).col_join(c.row_join(-c))
Matrix([[1, -1]])
```
Note that in SymPy 1.8 `risch` doesn't succeed in evaluating the integral but it doesn't raise an error.

I don't know well enough what this function (`prde_no_cancel_b_large`) is supposed to do to be able to identify the problem further. Presumably either `A` or `c` is already wrong before we get to this line.

**Comment by nasser1** [comment] 2022-08-19 08:24
Fyi, The following example produce similar errors in 1.10.1. I am assuming it is due to same problem.

```
>>> from sympy import *
>>>F, G, H, a, b, c, d, e, f, g, h, i, k, m, n, p, r, s, t, x=symbols('F G H a b c d e f g h i k m n p r s t x')
>>> integrand=(((-2*x**5+28*x**4-144*x**3+324*x**2-270*x)*ln(x)**2+(-4*x**6+56*x**5-288*x**4+648*x**3-540*x**2)*ln(x)+(2*x**5-28*x**4+144*x**3-324*x**2+270*x)*exp(x)+(2*x**5-28*x**4+144*x**3-324*x**2+270*x)*ln(5)-2*x**7+26*x**6-116*x**5+180*x**4+54*x**3-270*x**2)*ln(-ln(x)**2-2*x*ln(x)+exp(x)+ln(5)-x**2-x)**2+((4*x**5-44*x**4+168*x**3-216*x**2-108*x+324)*ln(x)+(-2*x**5+24*x**4-108*x**3+216*x**2-162*x)*exp(x)+4*x**6-42*x**5+144*x**4-108*x**3-324*x**2+486*x)*ln(-ln(x)**2-2*x*ln(x)+exp(x)+ln(5)-x**2-x))/(x*exp(x)**2*ln(x)**2+2*x**2*exp(x)**2*ln(x)-x*exp(x)**3+(-x*ln(5)+x**3+x**2)*exp(x)**2)
>>> integrate(integrand,x)

....

File "/usr/lib/python3.10/site-packages/sympy/polys/matrices/domainmatrix.py", line 788, in vstack
    return DomainMatrix.from_rep(A.rep.vstack(*(Bk.rep for Bk in B)))
  File "/usr/lib/python3.10/site-packages/sympy/polys/matrices/sdm.py", line 794, in vstack
    assert Bkcols == cols
AssertionError

```

**Comment by oscarbenjamin** [comment] 2022-08-19 15:17
Yes, that's the same problem.

I tried this diff:
```diff
diff --git a/sympy/integrals/prde.py b/sympy/integrals/prde.py
index d818215..09ffaa7 100644
--- a/sympy/integrals/prde.py
+++ b/sympy/integrals/prde.py
@@ -350,7 +350,10 @@ def prde_no_cancel_b_large(b, Q, n, DE):
         M = Matrix(dc + 1, m, lambda i, j: Q[j].nth(i), DE.t)
     A, u = constant_system(M, zeros(dc + 1, 1, DE.t), DE)
     c = eye(m, DE.t)
-    A = A.row_join(zeros(A.rows, m, DE.t)).col_join(c.row_join(-c))
+    if A.rows != 0:
+        A = A.row_join(zeros(A.rows, m, DE.t)).col_join(c.row_join(-c))
+    else:
+        A = c.row_join(-c)
 
     return (H, A)
```
I don't know if that's really mathematically valid or just covering up a bug but it basically reproduces what used to happen SymPy 1.8 before PolyMatrix was reimplemented using DomainMatrix.

With that diff the second example produces an answer:
```python
In [1]: >>> from sympy import *
   ...: >>> F, G, H, a, b, c, d, e, f, g, h, i, k, m, n, p, r, s, t, x=symbols('F G H a b c d e f g h
   ...:  i k m n p r s t x')
   ...: >>> integrand=(((-2*x**5+28*x**4-144*x**3+324*x**2-270*x)*ln(x)**2+(-4*x**6+56*x**5-288*x**4+
   ...: 648*x**3-540*x**2)*ln(x)+(2*x**5-28*x**4+144*x**3-324*x**2+270*x)*exp(x)+(2*x**5-28*x**4+144*
   ...: x**3-324*x**2+270*x)*ln(5)-2*x**7+26*x**6-116*x**5+180*x**4+54*x**3-270*x**2)*ln(-ln(x)**2-2*
   ...: x*ln(x)+exp(x)+ln(5)-x**2-x)**2+((4*x**5-44*x**4+168*x**3-216*x**2-108*x+324)*ln(x)+(-2*x**5+
   ...: 24*x**4-108*x**3+216*x**2-162*x)*exp(x)+4*x**6-42*x**5+144*x**4-108*x**3-324*x**2+486*x)*ln(-
   ...: ln(x)**2-2*x*ln(x)+exp(x)+ln(5)-x**2-x))/(x*exp(x)**2*ln(x)**2+2*x**2*exp(x)**2*ln(x)-x*exp(x
   ...: )**3+(-x*ln(5)+x**3+x**2)*exp(x)**2)
   ...: >>> integrate(integrand,x)
Out[1]: 
⎛ 4       3       2             ⎞  -2⋅x    2⎛   2                     x      2            ⎞
⎝x  - 12⋅x  + 54⋅x  - 108⋅x + 81⎠⋅ℯ    ⋅log ⎝- x  - 2⋅x⋅log(x) - x + ℯ  - log (x) + log(5)⎠
```
Also with the diff the first example doesn't raise an error but seems to just hang instead.

**Comment by oscarbenjamin** [comment] 2022-08-19 21:45
@asmeurer do you know how to diagnose this further?

**Comment by jksuom** [comment] 2022-08-21 08:15
I think that your diff does what should be done.

The code creates an nxm -matrix A where n may be zero, which means that each one of the (non-parametric) Risch differential equations `Dq + b*q == qi` is solvable so that there will be no constraints on the ci's.

The method is then expected to output an (n+m)x2m -matrix that consists of four blocks: A at upper left corner, an nxm zero matrix at upper right, mxm identity matrix at lower left and minus mxm identity at lower right.

The original code does exactly that. The problem seems to be that the new matrix code cannot handle the case n == 0 in the same way.

**Comment by oscarbenjamin** [comment] 2022-08-21 21:53
If I understand that correctly then the shape of `A` should be n x m. However this contradicts the value of the local variable `m`:
```python
> /home/oscar/current/sympy/sympy.git/sympy/integrals/prde.py(353)prde_no_cancel_b_large()
    351     A, u = constant_system(M, zeros(dc + 1, 1, DE.t), DE)
    352     c = eye(m, DE.t)
--> 353     A = A.row_join(zeros(A.rows, m, DE.t)).col_join(c.row_join(-c))
    354 
    355     return (H, A)

ipdb> p m
1
ipdb> p A.shape
(0, 2)
```
If `m` was equal to `2` then the shapes would all match.

It seems like the variables `A` and `m` are inconsistent somehow:
https://github.com/sympy/sympy/blob/f0154339c0b4d2602f0f4a6db4488d572b40e16f/sympy/integrals/prde.py#L335-L353

**Comment by jksuom** [comment] 2022-08-22 05:33
The wrong shape (0, 2) looks like a bug. It seems to be coming from this line: https://github.com/sympy/sympy/blob/88664e6e0b781d0a8b5347896af74b555e92891e/sympy/integrals/prde.py#L347
where  M should have shape (0, m) (instead of (0, 2) that is probably a typo). Would that suffice to fix the column error?

**Comment by oscarbenjamin** [comment] 2022-08-22 10:25
Yes, that seems like the proper fix. I didn't spot the `2` there but now it seems obvious that that is the mistake. I guess that the previous matrix code was more forgiving about this shape mismatch so the typo went unnoticed. The fix is:
```diff
diff --git a/sympy/integrals/prde.py b/sympy/integrals/prde.py
index d818215..6f9d429 100644
--- a/sympy/integrals/prde.py
+++ b/sympy/integrals/prde.py
@@ -344,7 +344,7 @@ def prde_no_cancel_b_large(b, Q, n, DE):
 
     if all(qi.is_zero for qi in Q):
         dc = -1
-        M = zeros(0, 2, DE.t)
+        M = zeros(0, m, DE.t)
     else:
         dc = max([qi.degree(DE.t) for qi in Q])
         M = Matrix(dc + 1, m, lambda i, j: Q[j].nth(i), DE.t)
```
With that neither example leads to the exception shown in the OP. The first example hangs but the second example gives what looks like a correct antiderivative:
```python
In [1]: >>> from sympy import *
   ...: >>> F, G, H, a, b, c, d, e, f, g, h, i, k, m, n, p, r, s, t, x=symbols('F G H a b c d e f g h
   ...:  i k m n p r s t x')
   ...: >>> integrand=(((-2*x**5+28*x**4-144*x**3+324*x**2-270*x)*ln(x)**2+(-4*x**6+56*x**5-288*x**4+
   ...: 648*x**3-540*x**2)*ln(x)+(2*x**5-28*x**4+144*x**3-324*x**2+270*x)*exp(x)+(2*x**5-28*x**4+144*
   ...: x**3-324*x**2+270*x)*ln(5)-2*x**7+26*x**6-116*x**5+180*x**4+54*x**3-270*x**2)*ln(-ln(x)**2-2*
   ...: x*ln(x)+exp(x)+ln(5)-x**2-x)**2+((4*x**5-44*x**4+168*x**3-216*x**2-108*x+324)*ln(x)+(-2*x**5+
   ...: 24*x**4-108*x**3+216*x**2-162*x)*exp(x)+4*x**6-42*x**5+144*x**4-108*x**3-324*x**2+486*x)*ln(-
   ...: ln(x)**2-2*x*ln(x)+exp(x)+ln(5)-x**2-x))/(x*exp(x)**2*ln(x)**2+2*x**2*exp(x)**2*ln(x)-x*exp(x
   ...: )**3+(-x*ln(5)+x**3+x**2)*exp(x)**2)

In [2]: f = integrand

In [3]: F = integrate(f, x)

In [4]: F
Out[4]: 
⎛ 4       3       2             ⎞  -2⋅x    2⎛   2                     x      2            ⎞
⎝x  - 12⋅x  + 54⋅x  - 108⋅x + 81⎠⋅ℯ    ⋅log ⎝- x  - 2⋅x⋅log(x) - x + ℯ  - log (x) + log(5)⎠

In [5]: factor(F.diff(x) - f)
Out[5]: 0
```

**Comment by oscarbenjamin** [comment] 2022-08-22 19:34
I've opened #23959 to fix this. The OP example should be added to #23949 as another example of a slow integral and then this issue can be closed when the PR is merged.

**Closed** 2022-09-02 05:55 UTC
Labels: integrals, integrals.risch
