### ISSUE TITLE
Can sympy induce the assumptions?

### ISSUE THREAD

**Issue by JSS95** [sympy/sympy#17977] opened 2019-11-29 02:05 UTC
I'm happy with `refine` that it can take assumptions to refine the expressions.  
```
>>> from sympy import refine, sqrt, Q
>>> from sympy.abc import x
>>> refine(sqrt((x-1)**2),Q.positive(x-1))
x-1
```

However, it seems that sympy cannot induce x>1 from x>2...
```
>>> refine(sqrt((x-1)**2),Q.positive(x-2))
sqrt((x-1)**2)
```

Is this a bug, or yet-unsupported feature?

**Comment by asmeurer** [comment] 2019-11-29 18:51
This is a yet-unsupported feature. Inequality assumptions don't work very well yet. I'm closing this as it's a duplicate of https://github.com/sympy/sympy/issues/14993 and probably others.

**Closed by asmeurer** 2019-11-29 18:51 UTC
