### ISSUE TITLE
Support symbolic order of derivative

### ISSUE THREAD

**Issue by Upabjojr** [sympy/sympy#12484] opened 2017-04-03 08:47 UTC
Loosely based on:
http://stackoverflow.com/questions/43142568/use-index-of-summation-as-the-order-of-derivation

Suppose we want to derive a function `f(x)` by `x` at `n` number of times (where `n` is symbolic), how can we represent this?

Currently we have:

```python
In [5]: Derivative(f(x), x)
Out[5]: 
d       
──(f(x))
dx      

In [6]: Derivative(f(x), x, 2)
Out[6]: 
  2      
 d       
───(f(x))
  2      
dx       

In [7]: Derivative(f(x), x, n)
Out[7]: 
   2       
  d        
─────(f(x))
dn dx      

In [8]: Derivative(f(x), (x, 2))
---------------------------------------------------------------------------
AttributeError
```

**Comment by mohit3011** [comment] 2017-04-05 21:13
@Upabjojr , I looked into the question on stackoverflow. It seems that even the derivative with for loop also doesn't work. In this issue are we looking into the printing part or the actual solving part for n times ? Please explain

**Comment by bjodah** [comment] 2017-04-05 22:25
Duplicate of #5575?

**Closed** 2017-04-06 08:34 UTC
