### ISSUE TITLE
Lambdify matrix element gives infinite recursion

### ISSUE THREAD

**Issue by Zaharid** [sympy/sympy#8512] opened 2014-11-24 09:22 UTC
This snippet:

````python
import sympy
X = sympy.MatrixSymbol('X',3,1)
sympy.lambdify(X,X[0,0])
````

Causes does not work and causes an infinite recursion error.

**Comment by jcrist** [comment] 2015-04-17 03:18
Closing, is a duplicate of #8280

**Closed by jcrist** 2015-04-17 03:18 UTC
Labels: duplicate
