### ISSUE TITLE
Incorrect result from `manualintegrate` for definite integral

### ISSUE THREAD

**Issue by calcpage** [sympy/sympy#21671] opened 2021-06-27 05:07 UTC
sympy vs sagecell error with triple integral?

I'm teaching a course in Multivariate Calculus and decided to convert my notes from Sage to Jupyter using SymPy. I have rewritten nearly all my notes as Jupyter Notebooks and am very impressed how I can use multiple cells like Mathematica and I can use MarkDown cells with LaTEX as well as all the great features of matplotlib, NumPy and SymPy.

I'm nearly done converting my segelets to python scripts on Colab and found a discrepency,

This Sage code:

`show(integral(integral(integral(1,z,x^2+y^2,2-x^2-y^2),y,-sqrt(1-x^2),sqrt(1-x^2)),x,-1,1))`

resolves as pi.

This SymPy code:

`display(Integral(1,(z,x**2+y**2,2-x**2-y**2),(y,-sqrt(1-x**2),sqrt(1-x**2)),(x,-1,1)).doit())`

resolves as -pi/2.

See #3 in this Jupyter Notebook:

[https://colab.research.google.com/drive/1OlT9nfPG8TzoR_WpDavx-SAa07HLg3hV?usp=sharing](https://colab.research.google.com/drive/1OlT9nfPG8TzoR_WpDavx-SAa07HLg3hV?usp=sharing)

Shouldn't these be equal? What am I missing? Any help would be greatly appreciated as I've done A LOT of work on this course using sympy and woud like to use it in class this summer session!

Please help,

A. Jorge Garcia

Applied Math & CS

Nassau Community College

http://shadowfaxrant.blogspot.com

PS: Here's the SAGECELL version,

[https://sagecell.sagemath.org/?z=eJzFk8FuwjAMhu9IvIMFB9qRTk1A07TrtE07cNuuSBkEGlGS4qRA-_RLQ1uQuDCGtlMsx_ns_5fTn-AbsJg-3scPoxg-J89sDB8os1TAu7JiiTw13U6fhvCy5WnOrQCu5v4OMxT2CWRdFpwHlJQkJiwkhTtGIdm7Yxx2OybRu6B3U2jPYbccg0FBykHT4seUdrYK52SzX0xIo-KArZvQo_DbYnsXyz1_e5A5unqe_ZQNiykjLHJR5KIKHJkN2oBWqZCcxFXviJ4a8deNL7XqOvrBzHEIr9JpsYmANTcG9MLHuZIWZvmXcNJ8YiHRWNAzy5WFXSIUYKJBGshQZxqt1IqnYLUvNpuco2hYc2ncq5ljoF77jEa5lKo19j-HaL_i6pKPuLoLareHZWWs39NmPf2yOmO_Adu6eJ4=&lang=sage](https://sagecell.sagemath.org/?z=eJzFk8FuwjAMhu9IvIMFB9qRTk1A07TrtE07cNuuSBkEGlGS4qRA-_RLQ1uQuDCGtlMsx_ns_5fTn-AbsJg-3scPoxg-J89sDB8os1TAu7JiiTw13U6fhvCy5WnOrQCu5v4OMxT2CWRdFpwHlJQkJiwkhTtGIdm7Yxx2OybRu6B3U2jPYbccg0FBykHT4seUdrYK52SzX0xIo-KArZvQo_DbYnsXyz1_e5A5unqe_ZQNiykjLHJR5KIKHJkN2oBWqZCcxFXviJ4a8deNL7XqOvrBzHEIr9JpsYmANTcG9MLHuZIWZvmXcNJ8YiHRWNAzy5WFXSIUYKJBGshQZxqt1IqnYLUvNpuco2hYc2ncq5ljoF77jEa5lKo19j-HaL_i6pKPuLoLareHZWWs39NmPf2yOmO_Adu6eJ4=&lang=sage)

**Comment by oscarbenjamin** [comment] 2021-06-27 10:47
I'll close #21665 as a duplicate of this. Moving my comment over from there:

From SO:
https://stackoverflow.com/questions/68138204/problem-evaluating-iterated-integral-in-sympy
```python
In [13]: I = Integral(-4*(1 - x**2)**(S(3)/2)/3 + 2*sqrt(1 - x**2)*(2 - 2*x**2), (x, -1, 1))

In [14]: I
Out[14]: 
1                                                 
⌠                                                 
⎮  ⎛            3/2                           ⎞   
⎮  ⎜    ⎛     2⎞           ________           ⎟   
⎮  ⎜  4⋅⎝1 - x ⎠          ╱      2  ⎛       2⎞⎟   
⎮  ⎜- ───────────── + 2⋅╲╱  1 - x  ⋅⎝2 - 2⋅x ⎠⎟ dx
⎮  ⎝        3                                 ⎠   
⌡                                                 
-1                                                

In [15]: I.n()
Out[15]: 3.14159265358979

In [16]: I.doit()
Out[16]: 
-π 
───
 2 
```
That leads to an incorrect result for the triple integral:
```python
In [17]: I2 = Integral(1,(z,x**2+y**2,2-x**2-y**2),(y,-sqrt(1-x**2),sqrt(1-x**2)),(x,-1,1))

In [18]: I2
Out[18]: 
      ________                          
     ╱      2      2    2               
1  ╲╱  1 - x    - x  - y  + 2           
⌠       ⌠             ⌠                 
⎮       ⎮             ⎮       1 dz dy dx
⌡       ⌡             ⌡                 
-1     ________     2    2              
      ╱      2     x  + y               
   -╲╱  1 - x                           

In [19]: I2.doit()
Out[19]: 
-π 
───
 2 
```

**Comment by jksuom** [comment] 2021-06-27 15:53
It seems that manualintegrate can compute the integral if the integration variable is not declared real as is done in Integral.doit:
```
In [1]: from sympy.integrals.manualintegrate import *                           

In [2]: f = -4*(1 - x**2)**(S(3)/2)/3 + 2*sqrt(1 - x**2)*(2 - 2*x**2)           

In [3]: F = manualintegrate(f, x)                                               

In [4]: F                                                                       
Out[4]: 
  ⎛⎧     ________                              ⎞     ⎛⎧                  _____
  ⎜⎪    ╱      2                               ⎟     ⎜⎪    ⎛       2⎞   ╱     
8⋅⎜⎨x⋅╲╱  1 - x     asin(x)                    ⎟   8⋅⎜⎨  x⋅⎝1 - 2⋅x ⎠⋅╲╱  1 - 
  ⎜⎪───────────── + ───────  for x > -1 ∧ x < 1⎟     ⎜⎪- ─────────────────────
  ⎝⎩      2            2                       ⎠     ⎝⎩             8         
──────────────────────────────────────────────── - ───────────────────────────
                       3                                                      

___                              ⎞
 2                               ⎟
x     asin(x)                    ⎟
─── + ───────  for x > -1 ∧ x < 1⎟
         8                       ⎠
──────────────────────────────────
   3                              

In [5]: piecewise_fold(F)._eval_interval(x, -1, 1)                              
Out[5]: π

In [6]: xr = symbols('xr', real=True)                                           

In [7]: fr = f.subs(x, xr)                                                      

In [8]: Fr = manualintegrate(fr, xr)                                            
n [9]: Fr                                                                      
Out[9]: 
    ⎛⎧      _________                                 ⎞     ⎛⎧                
    ⎜⎪     ╱       2                                  ⎟     ⎜⎪     ⎛        2⎞
  4⋅⎜⎨xr⋅╲╱  1 - xr     asin(xr)                      ⎟   4⋅⎜⎨  xr⋅⎝1 - 2⋅xr ⎠
    ⎜⎪─────────────── + ────────  for xr > -1 ∧ xr < 1⎟     ⎜⎪- ──────────────
    ⎝⎩       2             2                          ⎠     ⎝⎩               8
- ───────────────────────────────────────────────────── + ────────────────────
                            3                                                 
                                                                              

    _________                                 ⎞                               
   ╱       2                                  ⎟                               
⋅╲╱  1 - xr     asin(xr)                      ⎟                               
───────────── + ────────  for xr > -1 ∧ xr < 1⎟     ⎛⎧   _________            
                   8                          ⎠     ⎜⎪  ╱       2  ⎛    2    ⎞
─────────────────────────────────────────────── - 4⋅⎜⎨╲╱  1 - xr  ⋅⎝2⋅xr  - 1⎠
             3                                      ⎜⎪────────────────────────
                                                    ⎝⎩              8         

                                                                              
                                                                              
                                                                              
           _________              ⎛   _________⎞                              
          ╱       2               ⎜  ╱       2 ⎟                              
⋅│xr│   ╲╱  1 - xr  ⋅│xr│   3⋅asin⎝╲╱  1 - xr  ⎠                              
───── - ───────────────── + ────────────────────  for xr > -1 ∧ xr < 1 ∧ xr ≠ 
                2                    8                                        

  
  
  
 ⎞
 ⎟
 ⎟
0⎟
 ⎠

In [10]: piecewise_fold(Fr)._eval_interval(xr, -1, 1)                           
Out[10]: 
-π 
───
 2 
```
For a real variable `xr`, manualintegrate finds an alternate form where the last Piecewise term is an even function of `xr` and yields nothing to the integral. The absolute value `|xr|` comes from a partial inversion of the substitution `u <- xr**2` :
```
In [16]: u = symbols('u')                                                       

In [17]: sqrt(u).subs(u, xr**2)                                                 
Out[17]: │xr│

```
For a general (non-real) variable, the alternate form is discarded by manualintegrate.

**Comment by calcpage** [comment] 2021-06-27 16:47
Thanx for the input, guys! Very interesting. SO this behavior is inconsistent. What can be done to remedy this?

**Comment by oscarbenjamin** [comment] 2021-06-27 22:29
I'm not sure what can be done. Maybe a substitution like `u <- x**2` should be avoided in general. Maybe there is an incorrect simplification somewhere...

**Comment by calcpage** [comment] 2021-06-28 00:20
This is a shame. I was so excited to teach my students about Jupyter Notebooks in general and symbolics in particular. I have taught several levels of Calculus and PreCalculus for well over a decade using Sage without a hitch. But I found NumPy and SymPy to be much more consistent and pythonic. 

I think I will still use SymPy in class this semester. But I am a bit disapointed as I have done tons of code samples for my students using matplotlib for 2d and 3d graphing, NumPy and SymPy for vector and matrix algebra as well as SymPy for ordinary derivatives, partial derivatives, second partials, single and double integrals no problem. 

Then I stumble upon these 2 triple integrals that fail? This is very strange as it's not the fact that these are triple integrals that make them fail. I've done several triple integration examples; whether they be cartesian,cylindrical or spherical; without any issue using SymPy. Also, these triple integrals fail even if you break them up step by step as 3 single integrals, the last one still fails. I don't think it has to do with the -x^2 exponents either as I've done other integrals involving exponents like those without an issue. Maybe changing the order of integration might help? IDK, haven't tried that yet.
Be Well,
A. Jorge Garcia

**Comment by calcpage** [comment] 2021-06-28 04:54
For example, everything's fine with this Jupyter Notebook,
<https://colab.research.google.com/drive/1dWT90dH9Tdbso6YQibNizdGpiiWk2JVk?usp=sharing>
Be well,
A. Jorge Garcia

**Comment by jksuom** [comment] 2021-06-28 06:35
This piece of code https://github.com/sympy/sympy/blob/2bbb4a1faca9b09247cd36be76b0676a4f5d3f9d/sympy/integrals/integrals.py#L466-L483 is a relatively new addition. Most integrators are independent of the assumptions on integration variables, and it looks like it may be harmful for manualintegrate. I would try removing these substitutions.

**Comment by oscarbenjamin** [comment] 2021-06-28 11:54
> Most integrators are independent of the assumptions on integration variables, and it looks like it may be harmful for manualintegrate. I would try removing these substitutions.

That might work but I think that there must be a bug somewhere in manual integrate that leads to this.

The correct result `pi` was returned in sympy 1.4 and the integral computed more quickly then. The commit that broke this is the change you've shown a8e23375f817258981ff29bb69cf62f2651ab4f5 from #17093

**Comment by calcpage** [comment] 2021-06-28 13:53
That's encouraging! You have found a version of SymPy that did not have this issue. Anyway to revert to this version?
TIA.
AJG

**Comment by jksuom** [comment] 2021-06-28 14:06
> there must be a bug somewhere in manual integrate that leads to this.

It seems that manualintegrate cannot check that a substitution is invertible as it has no knowledge of the integration domain.

**Comment by oscarbenjamin** [comment] 2021-06-28 14:21
This diff leads to the correct result:
```diff
diff --git a/sympy/integrals/integrals.py b/sympy/integrals/integrals.py
index 8ec4076673..96f8e2a0bd 100644
--- a/sympy/integrals/integrals.py
+++ b/sympy/integrals/integrals.py
@@ -481,7 +481,7 @@ def doit(self, **hints):
                 d = None
             if d:
                 reps[x] = d
-        if reps:
+        if False:
             undo = {v: k for k, v in reps.items()}
             did = self.xreplace(reps).doit(**hints)
             if type(did) is tuple:  # when separate=True
```
That gives:
```python
In [1]: Integral(-4*(1 - x**2)**(S(3)/2)/3 + 2*sqrt(1 - x**2)*(2 - 2*x**2), (x, -1, 1)).doit()
Out[1]: π

In [2]: Integral(1,(z,x**2+y**2,2-x**2-y**2),(y,-sqrt(1-x**2),sqrt(1-x**2)),(x,-1,1)).doit()
Out[2]: π
```

> > there must be a bug somewhere in manual integrate that leads to this.
> 
> It seems that manualintegrate cannot check that a substitution is invertible as it has no knowledge of the integration domain.

Then it shouldn't attempt a substitution like `u <- x**2`. I think I've seen heurisch have problems with this kind of substitution as well because it can lead to things like `sqrt(a**2)`.

Does manual integrate only handle indefinite integrals?

**Comment by oscargus** [comment] 2021-08-11 16:58
I've been encouraging that type of substitutions (the integration variable is indeed real, so it should work _better_ if it is defined like that). So I agree that there is something strange (and unfortunate) here.

**Comment by calcpage** [comment] 2021-08-11 17:28
I taught my class without any major issues using sympy. Thanx for a great package! Keep up the good work. This is from a professor who's been teaching computer science since the 1970s and math since the 1980s and physics since the 1990s, FYI.

**Comment by oscarbenjamin** [comment] 2021-08-11 18:49
@calcpage glad to hear that it worked out.

**Closed** 2021-11-20 07:48 UTC
Labels: integrals, integrals.definite, integrals.manualintegrate
