### ISSUE TITLE
Numerical error in sympy.physics.units conversion

### ISSUE THREAD

**Issue by kpaHTbI** [sympy/sympy#24281] opened 2022-11-19 20:48 UTC
Conversion from Ohm to CGS units of resistance (sec/cm) is 4 orders of magnitude off 

``` import sympy as sy
from sympy.physics.units import convert_to
from sympy.physics.units.systems.cgs import cgs_gauss
from sympy.physics.units import ohm, centimeter as cm, second as sec

convert_to(1*ohm, sec/cm, unit_system='cgs_gauss').n()
```

The output is $1.11265005605362\cdot 10^{−8} cm/sec$
It must be $1.11265005605362\cdot 10^{−12} cm/sec$

**Comment by kpaHTbI** [comment] 2022-11-20 14:32
I think the problem comes from the elementary charge value in CGS units of statcoulomb:
```
from sympy.physics.units import elementary_charge as e
from sympy.physics.units import convert_to
from sympy.physics.units.systems.cgs import cgs_gauss
from sympy.physics.units import coulomb as C
from sympy.physics.units.definitions.unit_definitions import statcoulomb as esu

e_si = convert_to(e, C)
e_si
```

This gives the correct value in SI units $1.602176634 \cdot 10^{−19}C$. The following lines convert this value to statcoulombs:
```
e_cgs = convert_to(e_si, esu, unit_system='cgs_gauss')
e_cgs
```
The output is $4.80320471257026 \cdot 10^{−12}statC$, while it should be $4.80320471257026 \cdot 10^{−10}statC$. Conductivity is proportional to $e^2$, therefore all related units will be $10^4$ off.

**Comment by 1e9abhi1e10** [comment] 2022-11-23 10:21
Is the issue is still open?

**Comment by oscarbenjamin** [comment] 2022-11-23 17:49
There is already a PR open for this (#24286). Maybe you could offer a suggestion there to help finish that PR.

**Comment by kpaHTbI** [comment] 2022-11-23 23:12
I did more tests and found more wrong conversions. I am using sympy 1.10.1 to test. I am taking numbers from textbooks, but the same numbers appear in [Wikipedia](https://en.wikipedia.org/wiki/Gaussian_units) (Table 1: Common electromagnetism units in SI vs Gaussian).
```
from sympy.physics.units import convert_to
from sympy.physics.units.systems.cgs import cgs_gauss
from sympy.physics.units import coulomb, ampere, second as sec, centimeter as cm
from sympy.physics.units.definitions.unit_definitions import statcoulomb as esu, statvolt, erg, dyne
from sympy.physics.units import farad, henry, ohm, volt, newton, joule, meter
```
### The main problem is probably in definition of charge in CGS units, it's $10^2$ off
```
convert_to(coulomb, esu, unit_system='cgs_gauss').n() 
```
-> 29979245.8statC, must be x100 that.
As the result current has the same problem:
```
convert_to(ampere, esu/sec, unit_system='cgs_gauss').n()
```
-> $\frac{29979245.8statC}{s}$, must be x100 that.

Other electrical units are proportianal to $charge^2$ and are $10^4$ off.
Correct numbers:
* Capacitance: $1\ farad \approx$ $9 \cdot 10^{11}cm$
* Inductance: $1\ henry \approx$ $1.113 \cdot 10^{-12} sec^2/cm$
* Resistance: $1\ ohm \approx$ $1.113 \cdot 10^{-12} sec/cm$

Sympy:
```
convert_to(farad, cm, unit_system='cgs_gauss').n()
```
-> 89875517.8736818cm, must be that x10000
```
convert_to(henry, sec**2/cm, unit_system='cgs_gauss').n()
```
-> $\frac{1.11265005605362\cdot 10^{−8}s^2}{cm}$, exponent must be $10^{-12}$
```
convert_to(ohm, sec/cm, unit_system='cgs_gauss').n()
```
-> $\frac{1.11265005605362\cdot 10^{−8}s}{cm}$, exponent must be $10^{-12}$

I don't know where the source of this problem.

### Unrelated problem is in potential (voltage) conversion

We know that 300 V $\approx$ 1 statvolt, but sympy give opposite 1 V $\approx$ 300 statvolt
```
convert_to(300*volt, statvolt, unit_system='cgs_gauss').n()
```
-> 89937.7374statvolt, must be $\approx 1$
```
convert_to(statvolt, volt, unit_system='cgs_gauss').n()
```
-> 0.00333564095198152V, must be $\approx 300$

I am not a programmer, but it looks like this problem came from sympy/sympy/physics/units/systems/cgs.py line 61:
```
gs_gauss.set_quantity_scale_factor(volt, speed_of_light*statvolt/10**6)
```
I would try to change it to 
```
gs_gauss.set_quantity_scale_factor(volt, 10**6*statvolt/speed_of_light)
```
### Another unrelated problem

* **Votage/potential:**  SI: volt is the same as joule/coulomb; CGS: statvolt is the same as erg/statcoulomb

* **Electric field:** SI: volt/meter is the same as newton/coulomb; CGS: statvolt/cm is the same as dyne/statcoulomb
```
convert_to(volt, joule/coulomb) # this works -> J/C
convert_to(statvolt, erg/esu, unit_system='cgs_gauss') # this does not work -> statvolt
convert_to(volt/meter, newton/coulomb) # this works -> N/C
convert_to(statvolt/cm, dyne/esu, unit_system='cgs_gauss') # this does not work -> dyne/100cm statC
```

**Comment by Vaani-pathariya** [comment] 2022-11-25 19:19
I referenced Electromagnetic unit names section of wikipedia (https://en.wikipedia.org/wiki/Gaussian_units)  for the above PR

**Comment by 1e9abhi1e10** [comment] 2022-12-17 13:13
@kpaHTbI  this issue is fixed by [PR](https://github.com/sympy/sympy/pull/24325), you may close it.
Thank you!

**Comment by kpaHTbI** [comment] 2022-12-17 16:19
Great! Thank you.

**Closed** 2022-12-17 16:18 UTC
Labels: physics.units
