### ISSUE TITLE
Wrong computation of periodic integral

### ISSUE THREAD

**Issue by Trollipop42** [sympy/sympy#17791] opened 2019-10-24 13:01 UTC
Set
`g=Abs(sin(x))`
The integral
`integrate(g,(x,0,4))`
is `cos(4)+3`. 
For
`integrate(g,(x,0,4+2*pi))`
sympy also returns `cos(4)+3`, but it should be `cos(4)+5`.

Sympy version 1.4

**Comment by jksuom** [comment] 2019-10-24 16:03
Duplicate of https://github.com/sympy/sympy/issues/15402. Closing.

**Closed by jksuom** 2019-10-24 16:03 UTC
