### ISSUE TITLE
Maximum recursion depth when using sympy.simplify

### ISSUE THREAD

**Issue by yxwangcs** [sympy/sympy#17631] opened 2019-09-19 03:04 UTC
Hi sympy developers,

I'm using `sympy` to simplify some expressions in my field of study, but I encountered a RecursionError when trying to simplify a simple expression.

```
import sympy as sp
sp.simplify('((-1/2)*Boole(True)*Boole(False)-1)*Boole(True)')
```

and the error message is 
```
Traceback (most recent call last):
  File "/python3.7/site-packages/sympy/polys/polytools.py", line 5272, in gcd
    (F, G), opt = parallel_poly_from_expr((f, g), *gens, **args)
  File "/python3.7/site-packages/sympy/polys/polytools.py", line 4309, in parallel_poly_from_expr
    return _parallel_poly_from_expr(exprs, opt)
  File "/python3.7/site-packages/sympy/polys/polytools.py", line 4364, in _parallel_poly_from_expr
    raise PolificationFailed(opt, origs, exprs, True)
sympy.polys.polyerrors.PolificationFailed: can't construct polynomials from -1, -1/2
....
....
    return sympify(a, strict=True)
  File "/Users/ryan/anaconda3/lib/python3.7/site-packages/sympy/core/sympify.py", line 268, in sympify
    if a in sympy_classes:
  File "/Users/ryan/anaconda3/lib/python3.7/site-packages/sympy/core/numbers.py", line 3178, in __hash__
    return super(NaN, self).__hash__()
  File "/Users/ryan/anaconda3/lib/python3.7/site-packages/sympy/core/numbers.py", line 716, in __hash__
    return super(Number, self).__hash__()
RecursionError: maximum recursion depth exceeded while calling a Python object
```

where `sp.cancel()` works great and returns the expected result. Also, I found out we won't have the errors if the last `*Boole(True)` is dropped.

**Comment by asmeurer** [comment] 2019-09-19 03:30
I can reproduce the error in 1.4, but it seems to be fixed in master.

**Comment by asmeurer** [comment] 2019-09-19 03:35
I bisected it to 5c32dd5b0033ae9b1469354ca0e2f571a330f9e6. It seems the fix was accidental, so we should make sure it is tested.

**Closed** 2019-10-04 19:39 UTC
Labels: simplify
