### ISSUE TITLE
Assertion error in isympy terminal for test_ode.py code

### ISSUE THREAD

**Issue by sudz123** [sympy/sympy#15161] opened 2018-08-28 20:09 UTC
Running the code for `test_linear_2eq_order1` in `test_ode.py` in `solvers` module, in an isympy terminal gives an assertion error for the following lines : 

```
eq10 = (Eq(diff(x(t),t), 5*t*x(t) + t**2*y(t)), Eq(diff(y(t),t), (1-t**2)*x(t) + (5*t+9*t**2)*y(t)))
    sol10 = [Eq(x(t), C1*x0(t) + C2*x0(t)*Integral(t**2*exp(Integral(5*t, t))*exp(Integral(9*t**2 + 5*t, t))/x0(t)**2, t)), \
    Eq(y(t), C1*y0(t) + C2*(y0(t)*Integral(t**2*exp(Integral(5*t, t))*exp(Integral(9*t**2 + 5*t, t))/x0(t)**2, t) + \
    exp(Integral(5*t, t))*exp(Integral(9*t**2 + 5*t, t))/x0(t)))]
    s = dsolve(eq10)
    assert s == sol10 
```
However, the `./bin/test` runs fine.  Also refers to #15097

**Comment by cbm755** [comment] 2018-08-29 15:41
I cannot reproduce by just pasting that code into `isympy`:

```py
>>> sympy.__version__
1.2.1.dev
>>> x = Function('x'); y = Function('y'); x0 = Function('x0'); y0 = Function('y0')
>>> C1, C2 = symbols('C1, C2')
>>> eq10 = (Eq(diff(x(t),t), 5*t*x(t) + t**2*y(t)), Eq(diff(y(t),t), (1-t**2)*x(t) + (5*t+9*t**2)*y(t)))
>>> sol10 = [Eq(x(t), C1*x0(t) + C2*x0(t)*Integral(t**2*exp(Integral(5*t, t))*exp(Integral(9*t**2 + 5*t, t))/x0(t)**2, t)), \
...     Eq(y(t), C1*y0(t) + C2*(y0(t)*Integral(t**2*exp(Integral(5*t, t))*exp(Integral(9*t**2 + 5*t, t))/x0(t)**2, t) + \
...     exp(Integral(5*t, t))*exp(Integral(9*t**2 + 5*t, t))/x0(t)))]
>>> s = dsolve(eq10)
>>> sol10 == s
True
```

But I never used `isympy` before.  Can you tell me exactly what to type to run `test_ode.py`?  I tried this
```py
>>> run -i sympy/solvers/test/test_ode.py
  File "<console>", line 1
    run -i sympy/solvers/test/test_ode.py
               ^
SyntaxError: invalid syntax
```

**Comment by sudz123** [comment] 2018-09-08 14:56
Hi, by running test_ode.py I meant running the `./bin/test` and other tests on test_ode.py. test_ode.py looks like a python script which does not initialise the functions in it. Also my sympy version is 1.1.1 , does that make a difference?

**Comment by jksuom** [comment] 2018-09-08 15:17
The test seems to pass on current master:
```
In [1]: from sympy.solvers.tests.test_ode import *

In [2]: test_linear_2eq_order1()

```
 
```

**Comment by sudz123** [comment] 2018-09-09 00:14
Yes, when I run the code that way I too do not get any explicit error. But when I run it like [this](https://github.com/sympy/sympy/issues/15161#issuecomment-417000421). I get : 
```
In [3]: x = Function('x'); y = Function('y'); x0 = Function('x0'); y0 = Function('y0')

In [4]: C1, C2 = symbols('C1, C2')

In [5]: eq10 = (Eq(diff(x(t),t), 5*t*x(t) + t**2*y(t)), Eq(diff(y(t),t), (1-t**2)*x(t) + (5*t+9*t**2)*y(t)))

In [6]: sol10 = [Eq(x(t), C1*x0(t) + C2*x0(t)*Integral(t**2*exp(Integral(5*t, t))*exp(Integral(9*t**2 + 5*t, t))/x0(t)**2, t)), \
   ...: ...     Eq(y(t), C1*y0(t) + C2*(y0(t)*Integral(t**2*exp(Integral(5*t, t))*exp(Integral(9*t**2 + 5*t, t))/x0(t)**2, t) + \
   ...: ...     exp(Integral(5*t, t))*exp(Integral(9*t**2 + 5*t, t))/x0(t)))]

In [7]: s = dsolve(eq10)

In [8]: sol10 == s
Out[8]: False
```

**Comment by asmeurer** [comment] 2018-09-09 04:01
1.1.1 is an old version of SymPy. Can you try it again in the git master, or the 1.3rc1 release candidate.

**Comment by sudz123** [comment] 2018-09-09 04:33
I tried with `IPython console for SymPy 1.2 (Python 3.6.3-64-bit) (ground types: gmpy)` . Still getting `False`

**Comment by cbm755** [comment] 2018-09-09 06:45
Am I write that you are typing in test code that came from git master so maybe its ok if it fails on *any* old SymPy?

**Comment by sudz123** [comment] 2018-09-09 06:49
But I recently updated Sympy. Isn't 1.2 the latest edition? 1.3 is yet to be released right?

**Comment by cbm755** [comment] 2018-09-09 07:42
I think the point is if its already fixed in git master (or on the soon-to-be-released 1.3) then its not worth worrying to much about what happens on 1.2.

OTOH, if you can reproduce it on git master or 1.3rc1...

**Comment by jksuom** [comment] 2018-09-09 07:43
Running the code in isympy (on current master) does not seem to break the test:
```
In [1]: x = Function('x'); y = Function('y'); x0 = Function('x0'); y0 = Function('y0')

In [2]: C1, C2 = symbols('C1, C2')

In [3]: eq10 = (Eq(diff(x(t),t), 5*t*x(t) + t**2*y(t)), Eq(diff(y(t),t), (1-t**2)*x(t) + (5*t+9*t**2)*y(t)))

In [4]: s = dsolve(eq10)

In [6]: print(s)
[Eq(x(t), C1*x0(t) + C2*x0(t)*Integral(t**2*exp(Integral(5*t, t))*exp(Integral(9*t**2 + 5*t, t))/x0(t)**2, t)), Eq(y(t), C1*y0(t) + C2*(y0(t)*Integral(t**2*exp(Integral(5*t, t))*exp(Integral(9*t**2 + 5*t, t))/x0(t)**2, t) + exp(Integral(5*t, t))*exp(Integral(9*t**2 + 5*t, t))/x0(t)))]

In [7]: sol10 = [Eq(x(t), C1*x0(t) + C2*x0(t)*Integral(t**2*exp(Integral(5*t, t))*exp(Integral(9*t**2 + 5*t, t))/x0(t)**2, t)), Eq(y(t), C1*y0(t) + C2*(y0(t)*Integral(t**2*exp(Integral(5*t, t))*exp(Integral(9*t**2 + 5*t, t))/x0(t)**2, t) + exp(Integral(5*t, t))*exp(Integral(9*t**2 + 5*t, t))/x0(t)))]

In [8]: s == sol10
Out[8]: True
```

**Comment by cbm755** [comment] 2018-09-09 07:44
yes, as I said in the first comment.

@sudz123 maybe if you can reproduce, please show what `s - sol10` and `simplify(s-sol10)` gives.

**Comment by sudz123** [comment] 2018-09-09 09:37
I will try to install version 1.3 and reproduce the error. In my local machine: 
`In [13]: print(s)
[Eq(x(t), C1*x0 + C2*x0*Integral(t**2*exp(Integral(5*t, t))*exp(Integral(9*t**2 + 5*t, t))/x0**2, t)), Eq(y(t), C1*y0 + C2(y0*Integral(t**2*exp(Integral(5*t, t))*exp(Integral(9*t**2 + 5*t, t))/x0**2, t) + exp(Integral(5*t, t))*exp(Integral(9*t**2 + 5*t, t))/x0))]
`
Here I see that its just `x0` and not `x0(t)`. Maybe that's the reason..

**Comment by cbm755** [comment] 2018-09-09 21:43
So this is probably related to the symbol `x0` not becoming the function when called as `x0(t)`, #9064.  That is, the test was changed in 1.3 because of that change.

As I said, you are pasting in an example from the git master test and expecting it to pass on older sympy.

**Comment by oscarbenjamin** [comment] 2019-02-08 23:11
This issue is a result of a mixup. Closing as nothing to fix.

**Closed by oscarbenjamin** 2019-02-08 23:11 UTC
Labels: solvers.dsolve
