### ISSUE TITLE
An unspecified power of x is reported to be `O(log(x)**6)`

### ISSUE THREAD

**Issue by normalhuman** [sympy/sympy#14384] opened 2018-03-04 17:30 UTC
```
>>> var('x a')
>>> series(x**a, x, 0)
O(log(x)**6)
```
This should probably return the expression `x**a` itself, as `x**a` is not `O(log(x)**6)` when a is negative.

**Comment by ArighnaIITG** [comment] 2018-03-07 05:03
@normalhuman ,
I was trying to decipher the `series` function in `sympy.core.expr` in order to solve this issue.
Some questions are coming up ::

I believe this particular function call goes to the `n-series` handling part of the function -
In that , we have 
```
if n is not None:  # nseries handling
       s1 = self._eval_nseries(x, n=n, logx=logx)
        o = s1.getO() or S.Zero
```
Is the `_eval_nseries` here being called from the `Pow` class in `sympy.core.power`? 
And what checkpoints do we provide? Like when `a` is not explicitly specified, we return the `sympified` expression, without any order evaluation.
Is `Pow` the only case?

**Comment by normalhuman** [comment] 2018-03-07 05:28
It's not about adding a checkpoint like "if the expression is Pow, and the exponent is a symbol, and the sign of symbol is unknown, then..." The goal isn't to special-case this particular function; it is to understand and improve the algorithm for computation of power series.

**Comment by ArighnaIITG** [comment] 2018-03-07 05:53
Can you guide where the change should take place? Or where the problem is actually originating from?

**Comment by anutosh491** [comment] 2022-01-15 03:48
Should we expect a  `NotImplementedError: Result depends on the sign of a` type output cause the answer seems correct for whenever `a>=0` . @oscarbenjamin 
If we have some clarity on the expected output , I could get started and fix this !

**Comment by oscarbenjamin** [comment] 2022-01-15 10:39
As state in the OP it would be better to return the input unchanged. For concrete real values this already happens:
```
In [14]: vals = [-2, -S.Half, -sqrt(2), -1, 0, 1, sqrt(2), S.Half, 2, pi, E, 3.1, -1.1]

In [15]: all(e == series(e, x) for e in vals)
Out[15]: True
```
These look like they should be fixed:
```python
In [16]: series(x**I, x)
Out[16]: nan

In [17]: series(x**(1+I), x)
Out[17]: 
 ⎛   6   ⎞
O⎝log (x)⎠

In [18]: series(x**y, x)
Out[18]: 
 ⎛   6   ⎞
O⎝log (x)⎠

In [19]: yr = Symbol('yr', real=True)

In [20]: series(x**y, x)
Out[20]: 
 ⎛   6   ⎞
O⎝log (x)⎠
```

**Comment by anutosh491** [comment] 2022-01-17 02:36
> As state in the OP it would be better to return the input unchanged. For concrete real values this already happens:
> These look like they should be fixed:

Thanks for the insights , I will make a Pr soon on this . Another thing I noticed while debugging which I am sort of doubtful of is the following. @oscarbenjamin 

```
# The first one seems to be correct .Goes through gruntz.py and returns a NotImplementedError.
>>> x**a + O(x**4)
NotImplementedError: Result depends on the sign of sign(a - 4)

# Why shouldn't we expect a similar output in this case ?
>>> x**4 + O(x**a)
O(1, a, x)
```

**Closed** 2022-02-03 13:36 UTC
Labels: series
