### ISSUE TITLE
Assumptions in dsolve

### ISSUE THREAD

**Issue by parnmatt** [sympy/sympy#9423] opened 2015-05-25 10:20 UTC
When I use `dsolve`, a lot of the time it returns a `Piecewise`, I have to use `refine` to remove it based on the assumptions I give it, or using the `global_assumptions`.

It would be nice if you could pass a set of (new) assumptions, or an `AssumptionContext` (I think is what you call it) to the ODE, if none is given the global one should be used, or at least a flag to use it.

This would not only help with the piecewise issue, but could help with the migration to new assumptions. Currently I am using a quick wrapper to add a new assumption into `global_assumptions`.

```
from sympy import symbols, Q
from sympy.assumptions.assume import global_assumptions

def add_assumption(predicate, *symbols):
    global global_assumptions
    for symbol in symbols:
        global_assumptions.add(predicate(symbol))

x, y, z = symbols('x, y, z', positive=True)
add_assumption(Q.positive, x, y, z)
```

Currently to solve ODEs I need to use the old assumptions, the new ones aren't used internally.
Thus, something that could take ~4mins takes ~25mins, and returns a piecewise with things it should already know.

If this is the case than the old style can be fairly easily converted.

```
x = Symbol('x', positive=True)
```

Should be the same as:

```
x = Symbol('x')
add_assumption(Q.positive, x)
```

This is a pain, as old assumptions are lost when using `srepr`, which is the only way I can safely store the equations for later use.

I have also noticed that `Q.positive(x)` doesn't seem to remove the piecewise condition `x = 0`, among other things. I have added permutations eg., `Q.is_true(Eq(x, y))` and `Q.is_true(Eq(y,x))`, which get more complicated when we have more complicated equalities; they show the same relations just in different orders, and there is no way we know which order sympy will choose.

**Comment by oscarbenjamin** [comment] 2019-03-22 00:29
Can you give an example of the kind of ODEs you are trying to solve?

Piecewise solutions are only returned by the 2 equation homogeneous constant coefficient solver as far as I know. I think the PIecewise solutions are badly implemented and should be removed in the first instance...

**Comment by parnmatt** [comment] 2019-04-05 11:22
I'm sorry, this was almost 4 years ago. I honestly do not have the code that pertains to any more. It was the solutions to some multi-factor and multi-source radioactive decay chains.
I ended up just solving them by hand. and manually coding the solutions.

**Comment by oscarbenjamin** [comment] 2019-04-05 13:35
Okay thanks. Out of interest were the piecewise solutions themselves useful or would it be better just to return a generic solution?

What happens here is that for a 2x2 linear constant coefficient equation with symbolic coefficients the solver returns a piecewise solution for the different possibilities such as `A*sin(b*t) + B*cos(b*t)` or `A*exp(c*t) + B*exp(d*t)` etc.  There are a number of open issues about this e.g. #16125 #15474.

I think that really the problem is that these piecewise solutions should not be generated. For a 2x2 system all solutions will be of the exponential form unless the matrix is defective. So at worst there could be a Piecewise with two conditions. It's probably reasonable though to assume the generic case. Clearly for larger systems with symbolic matrices it's not reasonable to generate a Piecewise for every possibly Jordan form.

**Comment by oscarbenjamin** [comment] 2020-03-05 00:34
I'm closing this in favour of #16125 or #15474

**Closed** 2020-03-05 00:34 UTC
Labels: assumptions, solvers.dsolve
