### ISSUE TITLE
integrate(1 / (1 - x**3), x) incorrect

### ISSUE THREAD

**Issue by sn6uv** [sympy/sympy#11622] opened 2016-09-17 03:23 UTC
Incorrect results from integrate:
```
sympy.integrate(1 / (1 - x**3), x)
-log(x - 1)/3 + log(x**2 + x + 1)/6 + sqrt(3)*atan(2*sqrt(3)*x/3 + sqrt(3)/3)/3
```

The `log(x-1)` teem should be `log(1-x)`.

Originally reported as https://github.com/mathics/Mathics/issues/551

**Comment by asmeurer** [comment] 2016-09-17 03:58
Dupe of https://github.com/sympy/sympy/issues/11017. Note that the integral is correct (`log(x - 1)` equals `log(1 - x)` up to a constant), but it would be nice to return the "nicer" answer when possible.

**Closed by asmeurer** 2016-09-17 03:58 UTC
