### ISSUE TITLE
Eq(RootOf(), y) evaluates as False

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#15920] opened 2019-02-04 12:01 UTC
Creating an Eq with a `RootOf` evaluates as False.
```julia
In [20]: x = Symbol('x')                                                                                                          

In [21]: y = Symbol('y')                                                                                                          

In [22]: r = RootOf(x**5 - x + 1, 0)                                                                                              

In [23]: Eq(r, y)                                                                                                                 
Out[23]: False
```
Since `y` is Symbol there is no way to know that it isn't equal to `r` so this should do the same as
```julia
In [24]: Eq(1, y)                                                                                                                 
Out[24]: 1 = y
```

**Comment by oscargus** [comment] 2019-02-04 13:53
This is where it becomes false:

https://github.com/sympy/sympy/blob/27f2f10b965f912ea38bb189e6b498ec00efdb08/sympy/polys/rootoftools.py#L964-L965

```
In [10]: y.has(AppliedUndef)
Out[10]: False

In [11]: y.is_number
Out[11]: False
```

**Comment by RituRajSingh878** [comment] 2019-02-04 14:53
@oscarbenjamin  insted of `False`. What should be the output .
I think we can raise `ValueError`.

**Comment by oscarbenjamin** [comment] 2019-02-04 18:06
The result should be `Eq(RootOf(x**5 - x + 1, 0), y)`.

**Comment by XtremeGood** [comment] 2019-02-16 19:25
Does this error guarantees merge if the problem is solved?

**Comment by oscargus** [comment] 2019-02-16 20:34
Not sure if I understand the questions, but if I do: most solutions are merged. Sometimes the solutions are too focused (like making sure that only this particular polynomial works correctly), but general solutions not breaking anything else are more or less guaranteed to be merged.

For this particular problem there is an ongoing PR which seems to progress so there may be better ones to spend effort.

**Comment by XtremeGood** [comment] 2019-02-16 20:39
Well, I wanted to get my my pull merged.Oscar Benjamin said me to solve some error and I fixed it.Then some person named Christopher Smith says it won't be merged.I asked repeatedly what else does he wants more more my solver should do.I asked what further should I do but he seemed to be too confused and asked to close the request without telling me what else to do and when I had solved the problem.Is this fair?

**Comment by oscargus** [comment] 2019-02-16 22:09
Without knowing the details in your case, it is quite common that issues are fixed in a very specific way and therefore not merged. Where that line is drawn is hard to in general. On one hand one can think that it is better to have a very specific fix than none and that someone else will fix it later. However, that rarely happens.

It takes a few attempts to get to know the code base and provide a good fix, so keep going! Personally, I have spent quite some time to improve the code quality without really adding any new functionality. In that way one gets to see lots of code and know Sympy a little bit better. There are still many things to clean up and improve from a coding perspective.

**Comment by XtremeGood** [comment] 2019-02-16 22:12
https://github.com/sympy/sympy/pull/15964

But what did I get after spending hours awaken?

**Comment by oscarbenjamin** [comment] 2019-02-16 23:55
@XtremeGood This issue is not the right place to discuss this (although I don't know what is the right place) but I will say this here: I think that your work in #15694 will get merged. Currently the code you wrote is in the first commit of #15992 as you can see here: [https://github.com/sympy/sympy/pull/15992/commits](https://github.com/sympy/sympy/pull/15992/commits)
I can't say exactly when that will be merged because there are other problems to solve before that PR is ready.

**Comment by XtremeGood** [comment] 2019-02-17 04:20
Well then please tell me what to do.I have been asking you this.Do you want to solve d(x*f(x))/dx ..... = 0 type of equation?
Last comment I won't create any more mess here and should I delete my messages from here?

**Comment by oscarbenjamin** [comment] 2019-02-18 10:18
Actually it looks to me like #15923 has stalled. The proper fix is probably as described in [this comment](https://github.com/sympy/sympy/pull/15923#issuecomment-463236979) although it would need more tests to see that it does the right thing in different cases.

**Closed** 2019-03-04 18:26 UTC
Labels: core, polys
