### ISSUE TITLE
integrate(abs(x+1), (x, 0, 1)) raises gamma function pole error

### ISSUE THREAD

**Issue by pelegm** [sympy/sympy#8733] opened 2015-01-02 12:51 UTC
I've tried this:

``` python
>>> x = Symbol('x', real=True)
>>> integrate(abs(x+1), (x, 0, 1))
```

and got

``` pytb
Traceback (most recent call last):
  File "<ipython-input-39-374e774b613d>", line 1, in <module>
    integrate(abs(x+1), (x, 0, 1))
  File "sympy/utilities/decorator.py", line 35, in threaded_func
    return func(expr, *args, **kwargs)
  File "sympy/integrals/integrals.py", line 1232, in integrate
    risch=risch, manual=manual)
  File "sympy/integrals/integrals.py", line 487, in doit
    conds=conds)
  File "sympy/integrals/integrals.py", line 876, in _eval_integral
    h = meijerint_indefinite(g, x)
  File "sympy/integrals/meijerint.py", line 1596, in meijerint_indefinite
    res = _meijerint_indefinite_1(f.subs(x, x + a), x)
  File "sympy/integrals/meijerint.py", line 1650, in _meijerint_indefinite_1
    res += powdenest(fac_*r, polar=True)
  File "sympy/simplify/simplify.py", line 2440, in powdenest
    eq, rep = polarify(eq)
  File "sympy/simplify/simplify.py", line 2164, in polarify
    eq = _polarify(sympify(eq), lift)
  File "sympy/simplify/simplify.py", line 2122, in _polarify
    if isinstance(arg, Expr) else arg for arg in eq.args])
  File "sympy/simplify/simplify.py", line 2099, in _polarify
    return polar_lift(eq)
  File "sympy/core/compatibility.py", line 872, in wrapper
    result = user_function(*args, **kwds)
  File "sympy/core/function.py", line 375, in __new__
    result = super(Function, cls).__new__(cls, *args, **options)
  File "sympy/core/cache.py", line 91, in wrapper
    retval = cfunc(*args, **kwargs)
  File "sympy/core/compatibility.py", line 872, in wrapper
    result = user_function(*args, **kwds)
  File "sympy/core/function.py", line 199, in __new__
    evaluated = cls.eval(*args)
  File "sympy/functions/elementary/complexes.py", line 743, in eval
    ar = argument(arg)
  File "sympy/core/cache.py", line 91, in wrapper
    retval = cfunc(*args, **kwargs)
  File "sympy/core/compatibility.py", line 872, in wrapper
    result = user_function(*args, **kwds)
  File "sympy/core/function.py", line 375, in __new__
    result = super(Function, cls).__new__(cls, *args, **options)
  File "sympy/core/cache.py", line 91, in wrapper
    retval = cfunc(*args, **kwargs)
  File "sympy/core/compatibility.py", line 872, in wrapper
    result = user_function(*args, **kwds)
  File "sympy/core/function.py", line 199, in __new__
    evaluated = cls.eval(*args)
  File "sympy/functions/elementary/complexes.py", line 580, in eval
    x, y = re(arg_), im(arg_)
  File "sympy/core/cache.py", line 91, in wrapper
    retval = cfunc(*args, **kwargs)
  File "sympy/core/compatibility.py", line 872, in wrapper
    result = user_function(*args, **kwds)
  File "sympy/core/function.py", line 375, in __new__
    result = super(Function, cls).__new__(cls, *args, **options)
  File "sympy/core/cache.py", line 91, in wrapper
    retval = cfunc(*args, **kwargs)
  File "sympy/core/compatibility.py", line 872, in wrapper
    result = user_function(*args, **kwds)
  File "sympy/core/function.py", line 199, in __new__
    evaluated = cls.eval(*args)
  File "sympy/functions/elementary/complexes.py", line 77, in eval
    real_imag = term.as_real_imag(ignore=arg)
  File "sympy/core/power.py", line 901, in as_real_imag
    return (re_part.subs({a: re, b: S.ImaginaryUnit*im}),
  File "sympy/core/basic.py", line 871, in subs
    key=default_sort_key)
  File "sympy/core/compatibility.py", line 518, in default_sort_key
    args = [default_sort_key(arg, order=order) for arg in args]
  File "sympy/core/compatibility.py", line 504, in default_sort_key
    return item.sort_key(order=order)
  File "sympy/core/cache.py", line 91, in wrapper
    retval = cfunc(*args, **kwargs)
  File "sympy/core/compatibility.py", line 872, in wrapper
    result = user_function(*args, **kwds)
  File "sympy/core/expr.py", line 82, in sort_key
    args = expr.as_ordered_factors(order=order)
  File "sympy/core/mul.py", line 1515, in as_ordered_factors
    cpart.sort(key=lambda expr: expr.sort_key(order=order))
  File "sympy/core/mul.py", line 1515, in <lambda>
    cpart.sort(key=lambda expr: expr.sort_key(order=order))
  File "sympy/core/cache.py", line 91, in wrapper
    retval = cfunc(*args, **kwargs)
  File "sympy/core/compatibility.py", line 872, in wrapper
    result = user_function(*args, **kwds)
  File "sympy/core/expr.py", line 80, in sort_key
    args = expr.as_ordered_terms(order=order)
  File "sympy/core/expr.py", line 866, in as_ordered_terms
    terms, gens = self.as_terms()
  File "sympy/core/expr.py", line 904, in as_terms
    coeff *= complex(factor)
  File "sympy/core/expr.py", line 228, in __complex__
    result = self.evalf()
  File "sympy/core/evalf.py", line 1331, in evalf
    result = evalf(self, prec + 4, options)
  File "sympy/core/evalf.py", line 1225, in evalf
    r = rf(x, prec, options)
  File "sympy/core/evalf.py", line 620, in evalf_pow
    re, im, re_acc, im_acc = evalf(base, prec + 5, options)
  File "sympy/core/evalf.py", line 1225, in evalf
    r = rf(x, prec, options)
  File "sympy/core/evalf.py", line 238, in evalf_im
    return get_complex_part(expr.args[0], 1, prec, options)
  File "sympy/core/evalf.py", line 220, in get_complex_part
    res = evalf(expr, workprec, options)
  File "sympy/core/evalf.py", line 1231, in evalf
    re, im = x._eval_evalf(prec).as_real_imag()
  File "sympy/core/function.py", line 486, in _eval_evalf
    v = func(*args)
  File "sympy/mpmath/ctx_mp_python.py", line 993, in f
    return ctx.make_mpf(mpf_f(x._mpf_, prec, rounding))
  File "sympy/mpmath/libmp/gammazeta.py", line 1947, in mpf_gamma
    raise ValueError("gamma function pole")
ValueError: gamma function pole
```

I have a reason to believe that this is a new bug, replacing previous bug that has appeared in a comment in #8430.

**Comment by pelegm** [comment] 2015-01-02 13:00
Perhaps we can "inject" some assumptions to the integrand's symbols from the integration interval? For example, in that case the integration interval is `[0,1]`, thus we may assume `x` is nonnegative, thus removing the `abs` before resuming to calculate the integral.

**Comment by hacman** [comment] 2015-04-27 04:39
is this a dupe of #7165 (or at least related)? Either way, this looks like a simpler triggering case, since it is a single-variable integral.

**Comment by smichr** [comment] 2017-05-05 08:11
cf #8461

**Closed** 2018-01-16 08:16 UTC
