### ISSUE TITLE
Incorrect residue for `cot(pi*x)/(x**2 - 3*x + 3)`

### ISSUE THREAD

**Issue by sylee957** [sympy/sympy#21177] opened 2021-03-27 16:44 UTC
```
>>> residue(cot(pi*x)/((x - 1)*(x - 2) + 1), x, S(3)/2 - sqrt(3)*I/2)
-sqrt(3)*tanh(sqrt(3)*pi/2)/3
>>> residue(cot(pi*x)/(x**2 - 3*x + 3), x, S(3)/2 - sqrt(3)*I/2)
0
```
The latter one is incorrect with same expression.

**Comment by akshanshbhatt** [comment] 2021-03-29 13:34
The wrong result is due to error in value returned by the `leadterm()` function.

https://github.com/sympy/sympy/blob/bba9ad1e3c769fc283f610eecfe8069be2786142/sympy/core/mul.py#L1881-L1887

The value of variable `ords` (refer to line 1885 of the snippet attached) in 1st (correct) case is,

`ords= [(1/((x - 1/2 - sqrt(3)*I/2)*(x + 1/2 - sqrt(3)*I/2) + 1), -1), (cot(pi*(x + 3/2 - sqrt(3)*I/2)), 0)]`

while in second case,

`ords = [(1/(-3*x + (x + 3/2 - sqrt(3)*I/2)**2 - 3/2 + 3*sqrt(3)*I/2), 0), (cot(pi*(x + 3/2 - sqrt(3)*I/2)), 0)]`

The second tuple is identical in both cases. The error is in the first tuple. Verifying that there was an issue with the `leadterm()`  function.

```python
In [1]: from sympy import *
        from sympy import __version__ as ver
        x = Symbol('x')
        ver
Out[1]: '1.8.dev'

In [2]: exp1 = cot(pi*(x + 3/2 - sqrt(3)*I/2))/((x - 1/2 - sqrt(3)*I/2)*(x + 1/2 - sqrt(3)*I/2) + 1) # 1 (Correct Output)
        print(exp1)
Out[2]: cot(pi*(x + 1.5 - sqrt(3)*I/2))/((x - 0.5 - sqrt(3)*I/2)*(x + 0.5 - sqrt(3)*I/2) + 1)

In [3]: print(exp1.leadterm(x))
Out[3]: (sqrt(3)*I*cot(pi*(1.5 - sqrt(3)*I/2))/3, -1)

In [4]: exp2 = cot(pi*(x + 3/2 - sqrt(3)*I/2))/(-3*x + (x + 3/2 - sqrt(3)*I/2)**2 - 3/2 + 3*sqrt(3)*I/2) # 2 (Incorrect Output)
        print(exp2)
Out[4]: cot(pi*(x + 1.5 - sqrt(3)*I/2))/(-3*x + 2.25*(0.666666666666667*x + 1 - 0.333333333333333*sqrt(3)*I)**2 - 1.5 + 3*sqrt(3)*I/2)

In [5]: print(exp2.leadterm(x))
Out[5]: (cot(pi*(1.5 - sqrt(3)*I/2))/(-1.5 + 2.25*(1 - 0.333333333333333*sqrt(3)*I)**2 + 3*sqrt(3)*I/2), 0)
```

`exp2` is not sympified and due to this, the fractions behave as float values. On sympifying `exp2` we get,

```python
In [6]: exp2 = sympify("cot(pi*(x + 3/2 - sqrt(3)*I/2))/(-3*x + (x + 3/2 - sqrt(3)*I/2)**2 - 3/2 + 3*sqrt(3)*I/2)") #2
        exp2
Out[6]: cot(pi*(x + 3/2 - sqrt(3)*I/2))/(-3*x + (x + 3/2 - sqrt(3)*I/2)**2 - 3/2 + 3*sqrt(3)*I/2)
```

But the problem is not solved yet. `leadterm()` still returns the same output for some reason

```python
In [7]: print(exp2.leadterm(x))
Out[7]: (cot(pi*(3/2 - sqrt(3)*I/2))/(-3/2 + (3 - sqrt(3)*I)**2/4 + 3*sqrt(3)*I/2), 0)
```
However, now that the expression is in its symbolic form, `simplify()` will simplify and return equal results for both exp1 and exp2.

```python
In [8]: print(exp2.simplify().leadterm(x))
Out[8]: (-sqrt(3)*tanh(sqrt(3)*pi/2)/3, -1)

In [9]: print(exp1.simplify().leadterm(x))
Out[9]: (-sqrt(3)*tanh(sqrt(3)*pi/2)/3, -1)
```

I tried implementing this change in my fork,

```diff
$ git diff
diff --git a/sympy/core/mul.py b/sympy/core/mul.py
index db84a3a62e..60dc8c17fd 100644
--- a/sympy/core/mul.py
         try:
             for t in self.args:
+                t = sympify("%s" % (t)).simplify()
                 coeff, exp = t.leadterm(x)
                 if not coeff.has(x):
                     ords.append((t, exp))
```

And it worked fine.

```python
In [10]: print(residue(cot(pi*x)/((x - 1)*(x - 2) + 1), x, S(3)/2 - sqrt(3)*I/2))
Out[10]: -sqrt(3)*tanh(sqrt(3)*pi/2)/3

In [11]: print(residue(cot(pi*x)/(x**2 - 3*x + 3), x, S(3)/2 - sqrt(3)*I/2))
Out[11]: -sqrt(3)*tanh(sqrt(3)*pi/2)/3
```
I have not run the tests yet. If all the tests will pass I may open a PR. Suggestions are welcome in case I am doing something wrong.

**Comment by ebab** [comment] 2021-04-02 15:07
The leading term method does not really make sense for `cot`, as the series expansion is only locally unique.

**Comment by ebab** [comment] 2021-04-02 15:16
What is _the_ leading term supposed to be if the leading term of the series expansion of a function varies from point to point?

**Comment by 0sidharth** [comment] 2021-04-02 18:27
The leading term computation could be fixed by something like - 
```py
    def _eval_as_leading_term(self, x, cdir=0):                                 
        arg = self.args[0]                                                      
        x0 = arg.subs(x, 0)                                                     
        n = x0/S.Pi                                                             
        if n.is_integer:                                                        
            lt = (arg - n*S.Pi).as_leading_term(x)                              
            print(lt, -1/lt)                                                    
            return -lt if n.is_odd else 1/lt                                    
        if not x0.is_finite:                                                    
            return self                                                         
        return self.func(x0)
```
but the residue still outputs 0.

**Comment by jksuom** [comment] 2021-04-02 18:35
I think that the zeroes of cot are at half-integer multiples of pi.

**Comment by 0sidharth** [comment] 2021-04-02 20:04
Well, that was a silly mistake. I fixed that, but I think I found another bug -
```py
In [25]: a
Out[25]: 
                  1                  
─────────────────────────────────────
⎛          √3⋅ⅈ⎞ ⎛          √3⋅ⅈ⎞    
⎜x - 0.5 - ────⎟⋅⎜x + 0.5 - ────⎟ + 1
⎝           2  ⎠ ⎝           2  ⎠    

In [26]: b
Out[26]: 
                 1                 
───────────────────────────────────
                     2             
       ⎛    3   √3⋅ⅈ⎞    3   3⋅√3⋅ⅈ
-3⋅x + ⎜x + ─ - ────⎟  - ─ + ──────
       ⎝    2    2  ⎠    2     2   

In [27]: print(a)
1/((x - 0.5 - sqrt(3)*I/2)*(x + 0.5 - sqrt(3)*I/2) + 1)

In [28]: print(b)
1/(-3*x + (x + 3/2 - sqrt(3)*I/2)**2 - 3/2 + 3*sqrt(3)*I/2)

In [29]: a.as_leading_term(x)
Out[29]: 
√3⋅ⅈ
────
3⋅x 

In [30]: b.as_leading_term(x)
Out[30]: 
            1             
──────────────────────────
                2         
  3   (3 - √3⋅ⅈ)    3⋅√3⋅ⅈ
- ─ + ─────────── + ──────
  2        4          2   

```
Both expressions a and b are equivalent but their leading terms are very different. Due to this, the leading term of the cot part is not even being calculated in Mul._as_eval_leading_term, in the case of exp2.

**Comment by 0sidharth** [comment] 2021-04-03 05:42
The issue seems to be with the _eval_as_leading_term method of Add (and Pow, probably).
```py
In [11]: g
Out[11]: 
                     2             
       ⎛    3   √3⋅ⅈ⎞    3   3⋅√3⋅ⅈ
-3⋅x + ⎜x + ─ - ────⎟  - ─ + ──────
       ⎝    2    2  ⎠    2     2   

In [12]: [a.as_leading_term(x) for a in g.args]
Out[12]: 
⎡                 2               ⎤
⎢      -(√3 + 3⋅ⅈ)          3⋅√3⋅ⅈ⎥
⎢-3/2, ─────────────, -3⋅x, ──────⎥
⎣            4                2   ⎦

In [13]: g.expand()
Out[13]: 
 2         
x  - √3⋅ⅈ⋅x

In [14]: g.as_leading_term(x)
Out[14]: 
                2         
  3   (3 - √3⋅ⅈ)    3⋅√3⋅ⅈ
- ─ + ─────────── + ──────
  2        4          2   


```

AFAICT, the issue is that `together` here cannot simplify irrational or imaginary expressions. Further, it converts them into `Mul` many times, so `simplify` is not called.
https://github.com/sympy/sympy/blob/c80194d7a9bdace718a40147af6e2b5e45630d59/sympy/core/add.py#L1007-L1009

```py
In [12]: a
Out[12]: 
                2         
  3   (3 - √3⋅ⅈ)    3⋅√3⋅ⅈ
- ─ + ─────────── + ──────
  2        4          2   

In [13]: print(a)
-3/2 + (3 - sqrt(3)*I)**2/4 + 3*sqrt(3)*I/2

In [14]: a.together()
Out[14]: 
               2         
-6 + (3 - √3⋅ⅈ)  + 6⋅√3⋅ⅈ
─────────────────────────
            4            

In [15]: type(_)
Out[15]: sympy.core.mul.Mul

In [16]: a.cancel()
Out[16]: 0
```

The code for _eval_as_leading_term, however, is very sensitive it seems. If we change `together` to `cancel` or `simplify`, the original issue is fixed but a few other limits from the tests become unevaluated or even start raising errors. I also tried changing `expand_mul` to `_mexpand`, but again a few other limits started failing.
https://github.com/sympy/sympy/blob/c80194d7a9bdace718a40147af6e2b5e45630d59/sympy/core/add.py#L985 The issue probably requires changing quite a few leading term methods.

**Comment by jksuom** [comment] 2021-04-03 07:40
> The code for _eval_as_leading_term, however, is very sensitive it seems. If we change together to cancel or simplify, the original issue is fixed but a few other limits from the tests become unevaluated or even start raising errors. I also tried changing expand_mul to _mexpand, but again a few other limits started failing.

This is typical. Fortunately, it is possible to edit tests if they are failing only formally, not mathematically.

**Closed** 2021-06-01 05:44 UTC
Labels: Wrong Result, series
