### ISSUE TITLE
Crash when calculating density of sum of normal and normal to the 5:th power

### ISSUE THREAD

**Issue by rikardn** [sympy/sympy#24915] opened 2023-03-15 13:14 UTC
Calculating the density of the sum of the fifth power of a normal distributed random variable and the random variable raises. Lower powers seems to work, but not higher. I think, although I am not sure, that the calculations are correct. It is just that the calculation at some point leads to a `ConditionSet` perhaps via a `Piecewise`.

```python

import sympy.stats as stats

# Crashes
X = stats.Normal('X', 0, sympy.Symbol("sigma")**2)
stats.density(X**5 + X)

# Works
X = stats.Normal('X', 0, sympy.Symbol("sigma")**2)
stats.density(X**3 + X)
```

```
Traceback (most recent call last):

  File "/tmp/ipykernel_17323/2537738759.py", line 1, in <module>
    stats.density(X**5 + X)

  File "/usr/lib/python3/dist-packages/sympy/stats/rv.py", line 922, in density
    return Density(expr, condition).doit(evaluate=evaluate, **kwargs)

  File "/usr/lib/python3/dist-packages/sympy/stats/rv.py", line 869, in doit
    result = pspace(expr).compute_density(expr, **kwargs)

  File "/usr/lib/python3/dist-packages/sympy/stats/crv.py", line 529, in compute_density
    fy = sum(fx(g) * abs(g.diff(y)) for g in gs)

TypeError: 'ConditionSet' object is not iterable
```

**Comment by oscarbenjamin** [comment] 2023-03-15 16:42
The problem is here:
https://github.com/sympy/sympy/blob/372a8161f96771bfed84f9e1562dc6acb6849634/sympy/stats/crv.py#L530-L540
It is assumed that solveset will always return a FiniteSet or EmptySet. The check should be like:
```diff
diff --git a/sympy/stats/crv.py b/sympy/stats/crv.py
index 36e1a26..7ca940a 100644
--- a/sympy/stats/crv.py
+++ b/sympy/stats/crv.py
@@ -531,11 +531,13 @@ def compute_density(self, expr, **kwargs):
 
         gs = solveset(expr - y, self.value, S.Reals)
 
-        if isinstance(gs, Intersection) and S.Reals in gs.args:
-            gs = list(gs.args[1])
+        if isinstance(gs, Intersection):
+            if len(gs.args) == 2 and gs.args[0] is S.Reals:
+                gs = gs.args[1]
+
+        if not gs.is_FiniteSet:
+            raise ValueError("Can not solve %s for %s" % (expr, self.value))
 
-        if not gs:
-            raise ValueError("Can not solve %s for %s"%(expr, self.value))
         fx = self.compute_density(self.value)
         fy = sum(fx(g) * abs(g.diff(y)) for g in gs)
         return Lambda(y, fy)
```
Then it gives:
```python
ValueError: Can not solve -_y + X**5 + X for X
```
The equation is not solvable per Abel-Ruffini so this error message should be given. I'm going to mark this as easy to fix based on applying the diff above and a test for ValueError.

It is possible to express a result here using RootSum but that is a bigger change:
```python
In [54]: expr = x**5 + x

In [55]: f = sqrt(2)*exp(x**2/(2*sigma**4))/(2*sqrt(pi)*sigma**2)

In [56]: dxdy = idiff(expr - y, x, y)

In [57]: RootSum(expr, Lambda(x, f*abs(dxdy)))
Out[57]: 
   ⎛       ⎛                 2    ⎞    ⎞
   ⎜       ⎜                x     ⎟    ⎟
   ⎜       ⎜               ────   ⎟    ⎟
   ⎜       ⎜                  4   ⎟    ⎟
   ⎜       ⎜               2⋅σ    ⎟    ⎟
   ⎜       ⎜ 4            ℯ       ⎟    ⎟
√2⋅⎜RootSum⎜x  + 1, x ↦ ──────────⎟ + 1⎟
   ⎜       ⎜            │   4    │⎟    ⎟
   ⎝       ⎝            │5⋅x  + 1│⎠    ⎠
────────────────────────────────────────
                      2                 
                2⋅√π⋅σ                  

In [58]: RootSum(expr, Lambda(x, f*abs(dxdy))).doit().rewrite(sin).factor()
Out[58]: 
   ⎛   ⎛ 1  ⎞    ⎞
√2⋅⎜cos⎜────⎟ + 1⎟
   ⎜   ⎜   4⎟    ⎟
   ⎝   ⎝2⋅σ ⎠    ⎠
──────────────────
           2      
     2⋅√π⋅σ 
```
(I'm not sure if that's correct)

**Comment by rikardn** [comment] 2023-03-16 07:24
Thanks for digging into this. This means that I was trying to find an explicit solution that couldn't be found.

**Comment by oscarbenjamin** [comment] 2023-03-16 10:56
> This means that I was trying to find an explicit solution that couldn't be found.

The calculation was trying to find an explicit intermediate solution that cannot be found. The end result that you want can be found semi-explicitly using Rootsum. My previous calculation was incorrect though so here is a better one:
```python
In [66]: px = x**5 + x - y

In [67]: fx = stats.density(X)

In [68]: fx
Out[68]: NormalDistribution(0, sigma**2)

In [69]: dxdy = idiff(px, x, y)

In [70]: dxdy
Out[70]: 
   1    
────────
   4    
5⋅x  + 1

In [71]: d = RootSum(px, Lambda(x, fx(x)*abs(dxdy)), x)

In [72]: d
Out[72]: 
          ⎛                     2    ⎞
          ⎜                   -x     ⎟
          ⎜                   ────   ⎟
          ⎜                      4   ⎟
          ⎜                   2⋅σ    ⎟
          ⎜ 5                ℯ       ⎟
√2⋅RootSum⎜x  + x - y, x ↦ ──────────⎟
          ⎜                │   4    │⎟
          ⎝                │5⋅x  + 1│⎠
──────────────────────────────────────
                     2                
               2⋅√π⋅σ                 

In [73]: d.doit() == d  # does not evaluate further
Out[73]: True
```
RootSum looks like a strange object but understand that it is not actually a function of x which is a bound variable. We can substitute values for y and sigma and evaluate:
```python
In [82]: d.subs({y:0, sigma:1}).evalf()
Out[82]: 0.749047068882509 + 1.63576953967719e-143⋅ⅈ
```
You can even plot this if you pick a value for sigma although it is slow to evaluate numerically:
```python
In [83]: plot(d.subs(sigma, 1))
```
It is possible to do some symbolic manipulation with RootOf although support for that can certainly be improved.

**Comment by rikardn** [comment] 2023-03-16 12:08
Thanks for the thorough walk through. My goal was actually to substitute values for all parameters and to plot the derived density function.

**Comment by Jay-Lokhande** [comment] 2023-07-14 14:26
import sympy as sp

mu = 0
sigma = sp.Symbol("sigma")
x = sp.Symbol("x")

# Define the density of the normal distribution
normal_density = 1 / (sp.sqrt(2 * sp.pi * sigma**2)) * sp.exp(-(x - mu)**2 / (2 * sigma**2))

# Compute the transformed random variable
transformed_rv = x**5 + x

# Substitute the transformed random variable into the density expression
density = normal_density.subs(x, transformed_rv)

# Display the density expression
print(density)

**Comment by geetHonve** [comment] 2023-10-01 14:05
What sort of test is expected for the ValueError?

**Comment by arhaque09** [comment] 2024-02-02 04:53
I would like to contribute to this issue. How should I start?

**Comment by oscarbenjamin** [comment] 2024-02-02 12:03
This is fixed now by gh-26095

**Closed** 2024-02-02 12:03 UTC
Labels: Easy to Fix, stats
