### ISSUE TITLE
regression: solve "Ignoring dict=True due to incompatible type"

### ISSUE THREAD

**Issue by cbm755** [sympy/sympy#17920] opened 2019-11-18 21:38 UTC
`solve` gives me a warning it didn't before (in SymPy 1.4).

This is mentioned here https://github.com/sympy/sympy/issues/17877#issuecomment-553602177 by @oscarbenjamin but I'm filing this explicit issue so its not lost.

```python
>>> x = Symbol('x')
>>> solve([x**2 - 1 > 0, x < 10], dict=True)                                   
/home/cbm/work/octsympy/octsympy.git/inst/sympy/solvers/solvers.py:998: UserWarning: 
Warning: Ignoring dict=True due to incompatible type of (-oo < x) & (x
< -1).
  incompatible type of %s.''' % sol))

((-oo < x) & (x < -1)) | ((1 < x) & (x < 10))


>>> # same without dict=True
>>> solve([x**2 - 1 > 0, x < 10])                                             
((-oo < x) & (x < -1)) | ((1 < x) & (x < 10))
```

I could bisect this later if needed.

**Comment by oscarbenjamin** [comment] 2019-11-18 21:46
Thanks @cbm755 

Is this actually a regression though?

The parameter dict=True doesn't have a meaningful interpretation when used with the inequality solver. What should the return value be if it somehow involved a dict?

I think it's just an error to use dict=True in this situation which is why the warning has been added.

Since this comes from the test script the question is why it hasn't been picked up in Travis and I think it's because it emits UserWarning rather than SympyDeprecationWarning (which would be turned into an error by the test runner). So maybe this should be fixed to use SympyDeprecationWarning instead and the test that generates this shouldn't use dict=True.

**Comment by oscarbenjamin** [comment] 2019-11-18 21:49
This comes from #17723

**Comment by asmeurer** [comment] 2019-11-19 01:02
I think UserWarning makes more sense than a deprecation warning.

**Comment by oscarbenjamin** [comment] 2019-11-19 01:20
Looking closer at it I see that nothing is actually deprecated but maybe it should be...

There isn't any general way to provide inequality output in dict format. The PR #17723 attempts to do that where possible and otherwise gives a warning. That defeats the point of dict=True though which is precisely to have a predictable output format.

Probably attempting to support dict=True when there are inequalities is a mistake. The PR #17723 seems misguided.

**Comment by cbm755** [comment] 2019-11-19 05:53
I see what you mean about it not being meaningful.

I'm unsure about SympyDeprecationWarning...  There do seem to be other places in the the code where regular `warnings.warn("foo")` is called...

I took me like 30 mins to get `warnings.warnfilters` to turn it into an error: I finally figured out the warning message that PR added *starts with  a newline*.  That's unpleasant: I'm not a fan of that `filldedent` thing...

**Comment by cbm755** [comment] 2019-11-19 05:55
In case someone needs it:
```python
>>> warnings.filterwarnings('error', message='\nWarning: Ignoring dict=True due to incompatible type')
```
Then I get a traceback and whatnot.

**Comment by cbm755** [comment] 2019-11-19 05:58
oops, didn't refresh page and missed some intermediate discussion, sorry.

Should we revert #17723?

Maybe for 1.5 we should SympyDeprecationWarning when `dict=True` is passed an there is at least one inequality in the input list?  Then later we can raise some exception?

**Closed** 2019-11-19 20:17 UTC
