### ISSUE TITLE
Issue #11230 in python3 with particular random seeds

### ISSUE THREAD

**Issue by siefkenj** [sympy/sympy#12046] opened 2017-01-14 17:20 UTC
The test for cse issue #11230 fails for particular random seed values in python 3.

Taken from the unit tests, the following code fails on my machine

```
import itertools

from sympy import (Add, Pow, Symbol, exp, sqrt, symbols, sympify, cse,
                   Matrix, S, cos, sin, Eq, Function, Tuple, CRootOf,
                   IndexedBase, Idx, Piecewise, O, Mul)
from sympy.simplify.cse_opts import sub_pre, sub_post
from sympy.functions.special.hyper import meijerg
from sympy.simplify import cse_main, cse_opts
from sympy.utilities.iterables import subsets
from sympy.utilities.pytest import XFAIL, raises
from sympy.matrices import (eye, SparseMatrix, MutableDenseMatrix,
    MutableSparseMatrix, ImmutableDenseMatrix, ImmutableSparseMatrix)
from sympy.matrices.expressions import MatrixSymbol

from sympy.core.compatibility import range

import random
random.seed(66251600)

def test_issue_11230():
    from random import choice
    from sympy.core.function import expand_mul
    s = symbols('a:m')
    # 35 Mul tests, none of which should ever fail
    ex = [Mul(*[choice(s) for i in range(5)]) for i in range(7)]
    print(list(subsets(ex,3)))
    for p in subsets(ex, 3):
        p = list(p)
        R, C = cse(p)
        print( [(i,i.is_Mul) for a in C for i in a.args])
        assert not any(i.is_Mul for a in C for i in a.args)

test_issue_11230()
```

with python3 but not with python2.

The python3 output is

```
[(a*c*e*h*i, a*b*j**2*k, b*f*i*k**2), (a*c*e*h*i, a*b*j**2*k, i**2*j**2*k), (a*c*e*h*i, a*b*j**2*k, a*f*g*j*l), (a*c*e*h*i, a*b*j**2*k, a*b*g*j**2), (a*c*e*h*i, a*b*j**2*k, a*c*h*j*l), (a*c*e*h*i, b*f*i*k**2, i**2*j**2*k), (a*c*e*h*i, b*f*i*k**2, a*f*g*j*l), (a*c*e*h*i, b*f*i*k**2, a*b*g*j**2), (a*c*e*h*i, b*f*i*k**2, a*c*h*j*l), (a*c*e*h*i, i**2*j**2*k, a*f*g*j*l), (a*c*e*h*i, i**2*j**2*k, a*b*g*j**2), (a*c*e*h*i, i**2*j**2*k, a*c*h*j*l), (a*c*e*h*i, a*f*g*j*l, a*b*g*j**2), (a*c*e*h*i, a*f*g*j*l, a*c*h*j*l), (a*c*e*h*i, a*b*g*j**2, a*c*h*j*l), (a*b*j**2*k, b*f*i*k**2, i**2*j**2*k), (a*b*j**2*k, b*f*i*k**2, a*f*g*j*l), (a*b*j**2*k, b*f*i*k**2, a*b*g*j**2), (a*b*j**2*k, b*f*i*k**2, a*c*h*j*l), (a*b*j**2*k, i**2*j**2*k, a*f*g*j*l), (a*b*j**2*k, i**2*j**2*k, a*b*g*j**2), (a*b*j**2*k, i**2*j**2*k, a*c*h*j*l), (a*b*j**2*k, a*f*g*j*l, a*b*g*j**2), (a*b*j**2*k, a*f*g*j*l, a*c*h*j*l), (a*b*j**2*k, a*b*g*j**2, a*c*h*j*l), (b*f*i*k**2, i**2*j**2*k, a*f*g*j*l), (b*f*i*k**2, i**2*j**2*k, a*b*g*j**2), (b*f*i*k**2, i**2*j**2*k, a*c*h*j*l), (b*f*i*k**2, a*f*g*j*l, a*b*g*j**2), (b*f*i*k**2, a*f*g*j*l, a*c*h*j*l), (b*f*i*k**2, a*b*g*j**2, a*c*h*j*l), (i**2*j**2*k, a*f*g*j*l, a*b*g*j**2), (i**2*j**2*k, a*f*g*j*l, a*c*h*j*l), (i**2*j**2*k, a*b*g*j**2, a*c*h*j*l), (a*f*g*j*l, a*b*g*j**2, a*c*h*j*l)]
[(a, False), (c, False), (e, False), (h, False), (i, False), (a, False), (x0, False), (j**2, False), (f, False), (i, False), (k, False), (x0, False)]
[(a, False), (c, False), (e, False), (h, False), (i, False), (a, False), (b, False), (j, False), (x0, False), (j, False), (x0, False), (i**2, False)]
[(a, False), (c, False), (e, False), (h, False), (i, False), (b, False), (j, False), (k, False), (x0, False), (f, False), (g, False), (l, False), (x0, False)]
[(a, False), (c, False), (e, False), (h, False), (i, False), (j, False), (k, False), (x0, False), (g, False), (j, False), (x0, False)]
[(e, False), (i, False), (x0, False), (a, False), (b, False), (k, False), (j**2, False), (j, False), (l, False), (x0, False)]
[(a, False), (c, False), (e, False), (h, False), (i, False), (b, False), (f, False), (k, False), (x0, False), (i, False), (x0, False), (j**2, False)]
[(a, False), (c, False), (e, False), (h, False), (i, False), (b, False), (f, False), (i, False), (k**2, False), (a, False), (f, False), (g, False), (j, False), (l, False)]
[(a, False), (c, False), (e, False), (h, False), (i, False), (b, False), (f, False), (i, False), (k**2, False), (a, False), (b, False), (g, False), (j**2, False)]
[(e, False), (i, False), (x0, False), (b, False), (f, False), (i, False), (k**2, False), (j, False), (l, False), (x0, False)]
[(a, False), (c, False), (e, False), (h, False), (i, False), (k, False), (i**2, False), (j**2, False), (a, False), (f, False), (g, False), (j, False), (l, False)]
[(a, False), (c, False), (e, False), (h, False), (i, False), (k, False), (x0, False), (i**2, False), (a, False), (b, False), (g, False), (x0, False)]
[(e, False), (i, False), (x0, False), (k, False), (i**2, False), (j**2, False), (j, False), (l, False), (x0, False)]
[(a, False), (c, False), (e, False), (h, False), (i, False), (f, False), (l, False), (x0, False), (b, False), (j, False), (x0, False)]
[(e, False), (i, False), (x0, False), (a, False), (f, False), (g, False), (x1, False), (x0, False), (x1, False)]
[(e, False), (i, False), (x0, False), (a, False), (b, False), (g, False), (j**2, False), (j, False), (l, False), (x0, False)]
[(a, False), (x0, False), (x1, False), (f, False), (x1, False), (x2, False), (i, False), (x0, False), (x2, False)]
[(j, False), (x0, False), (x1, False), (f, False), (i, False), (k, False), (x0, False), (f, False), (g, False), (l, False), (x1, False)]
[(j, False), (k, False), (x0, False), (b, False), (f, False), (i, False), (k**2, False), (g, False), (j, False), (x0, False)]
[(j, False), (x0, False), (x1, False), (f, False), (i, False), (k, False), (x0, False), (c, False), (h, False), (l, False), (x1, False)]
[(b, False), (x0, False), (x1, False), (j, False), (x1, False), (i**2, False), (f, False), (g, False), (l, False), (x0, False)]
[(x0, False), (x1, False), (j, False), (x1, False), (i**2, False), (g, False), (j, False), (x0, False)]
[(b, False), (x0, False), (x1, False), (j, False), (x1, False), (i**2, False), (c, False), (h, False), (l, False), (x0, False)]
[(k, False), (x0, False), (x1, False), (f, False), (l, False), (a*g*j, True), (g, False), (x0, False), (x1, False)]
Traceback (most recent call last):
  File "csetest.py", line 33, in <module>
    test_issue_11230()
  File "csetest.py", line 31, in test_issue_11230
    assert not any(i.is_Mul for a in C for i in a.args)
AssertionError
```

while the python2 output is

```
[(a*c*i*l*m, b*g*i**2*l, g*i*j*l*m), (a*c*i*l*m, b*g*i**2*l, a*f*g*h**2), (a*c*i*l*m, b*g*i**2*l, b**2*e*i*m), (a*c*i*l*m, b*g*i**2*l, c*e*h*l*m), (a*c*i*l*m, b*g*i**2*l, a*b*g*j*l), (a*c*i*l*m, g*i*j*l*m, a*f*g*h**2), (a*c*i*l*m, g*i*j*l*m, b**2*e*i*m), (a*c*i*l*m, g*i*j*l*m, c*e*h*l*m), (a*c*i*l*m, g*i*j*l*m, a*b*g*j*l), (a*c*i*l*m, a*f*g*h**2, b**2*e*i*m), (a*c*i*l*m, a*f*g*h**2, c*e*h*l*m), (a*c*i*l*m, a*f*g*h**2, a*b*g*j*l), (a*c*i*l*m, b**2*e*i*m, c*e*h*l*m), (a*c*i*l*m, b**2*e*i*m, a*b*g*j*l), (a*c*i*l*m, c*e*h*l*m, a*b*g*j*l), (b*g*i**2*l, g*i*j*l*m, a*f*g*h**2), (b*g*i**2*l, g*i*j*l*m, b**2*e*i*m), (b*g*i**2*l, g*i*j*l*m, c*e*h*l*m), (b*g*i**2*l, g*i*j*l*m, a*b*g*j*l), (b*g*i**2*l, a*f*g*h**2, b**2*e*i*m), (b*g*i**2*l, a*f*g*h**2, c*e*h*l*m), (b*g*i**2*l, a*f*g*h**2, a*b*g*j*l), (b*g*i**2*l, b**2*e*i*m, c*e*h*l*m), (b*g*i**2*l, b**2*e*i*m, a*b*g*j*l), (b*g*i**2*l, c*e*h*l*m, a*b*g*j*l), (g*i*j*l*m, a*f*g*h**2, b**2*e*i*m), (g*i*j*l*m, a*f*g*h**2, c*e*h*l*m), (g*i*j*l*m, a*f*g*h**2, a*b*g*j*l), (g*i*j*l*m, b**2*e*i*m, c*e*h*l*m), (g*i*j*l*m, b**2*e*i*m, a*b*g*j*l), (g*i*j*l*m, c*e*h*l*m, a*b*g*j*l), (a*f*g*h**2, b**2*e*i*m, c*e*h*l*m), (a*f*g*h**2, b**2*e*i*m, a*b*g*j*l), (a*f*g*h**2, c*e*h*l*m, a*b*g*j*l), (b**2*e*i*m, c*e*h*l*m, a*b*g*j*l)]
[(a, False), (c, False), (x0, False), (b, False), (g, False), (l, False), (i**2, False), (g, False), (j, False), (x0, False)]
[(a, False), (c, False), (m, False), (x0, False), (b, False), (g, False), (i, False), (x0, False), (a, False), (f, False), (g, False), (h**2, False)]
[(a, False), (c, False), (m, False), (x0, False), (g, False), (x0, False), (x1, False), (b, False), (e, False), (m, False), (x1, False)]
[(a, False), (i, False), (x0, False), (b, False), (g, False), (l, False), (i**2, False), (e, False), (h, False), (x0, False)]
[(a, False), (c, False), (i, False), (l, False), (m, False), (x0, False), (i**2, False), (a, False), (j, False), (x0, False)]
[(a, False), (c, False), (x0, False), (g, False), (j, False), (x0, False), (a, False), (f, False), (g, False), (h**2, False)]
[(a, False), (c, False), (x0, False), (g, False), (j, False), (x0, False), (e, False), (i, False), (m, False), (b**2, False)]
[(a, False), (i, False), (x0, False), (g, False), (i, False), (j, False), (l, False), (m, False), (e, False), (h, False), (x0, False)]
[(a, False), (c, False), (l, False), (x0, False), (x0, False), (x1, False), (a, False), (b, False), (x1, False)]
[(a, False), (c, False), (l, False), (x0, False), (a, False), (f, False), (g, False), (h**2, False), (e, False), (x0, False), (b**2, False)]
[(a, False), (i, False), (x0, False), (a, False), (f, False), (g, False), (h**2, False), (e, False), (h, False), (x0, False)]
[(c, False), (i, False), (m, False), (x0, False), (a, False), (f, False), (g, False), (h**2, False), (b, False), (g, False), (j, False), (x0, False)]
[(a, False), (i, False), (x0, False), (e, False), (i, False), (m, False), (b**2, False), (e, False), (h, False), (x0, False)]
[(c, False), (x0, False), (x1, False), (e, False), (x1, False), (b**2, False), (b, False), (g, False), (j, False), (x0, False)]
[(a, False), (i, False), (x0, False), (e, False), (h, False), (x0, False), (a, False), (b, False), (g, False), (j, False), (l, False)]
[(b, False), (i, False), (x0, False), (j, False), (m, False), (x0, False), (a, False), (f, False), (g, False), (h**2, False)]
[(x0, False), (x1, False), (j, False), (m, False), (x0, False), (b, False), (e, False), (m, False), (x1, False)]
[(b, False), (i, False), (x0, False), (j, False), (m, False), (x0, False), (c, False), (e, False), (h, False), (l, False), (m, False)]
[(b, False), (g, False), (l, False), (i**2, False), (i, False), (m, False), (x0, False), (a, False), (b, False), (x0, False)]
[(g, False), (i, False), (l, False), (x0, False), (a, False), (f, False), (g, False), (h**2, False), (b, False), (e, False), (m, False), (x0, False)]
[(b, False), (g, False), (l, False), (i**2, False), (a, False), (f, False), (g, False), (h**2, False), (c, False), (e, False), (h, False), (l, False), (m, False)]
[(x0, False), (i**2, False), (a, False), (f, False), (g, False), (h**2, False), (a, False), (j, False), (x0, False)]
[(g, False), (i, False), (l, False), (x0, False), (b, False), (x0, False), (x1, False), (c, False), (h, False), (l, False), (x1, False)]
[(x0, False), (i**2, False), (e, False), (i, False), (m, False), (b**2, False), (a, False), (j, False), (x0, False)]
[(x0, False), (i**2, False), (c, False), (e, False), (h, False), (l, False), (m, False), (a, False), (j, False), (x0, False)]
[(g, False), (j, False), (l, False), (x0, False), (a, False), (f, False), (g, False), (h**2, False), (e, False), (x0, False), (b**2, False)]
[(g, False), (i, False), (j, False), (x0, False), (a, False), (f, False), (g, False), (h**2, False), (c, False), (e, False), (h, False), (x0, False)]
[(i, False), (m, False), (x0, False), (a, False), (f, False), (g, False), (h**2, False), (a, False), (b, False), (x0, False)]
[(g, False), (i, False), (j, False), (x0, False), (e, False), (i, False), (m, False), (b**2, False), (c, False), (e, False), (h, False), (x0, False)]
[(x0, False), (x1, False), (e, False), (x1, False), (b**2, False), (a, False), (b, False), (x0, False)]
[(i, False), (m, False), (x0, False), (c, False), (e, False), (h, False), (l, False), (m, False), (a, False), (b, False), (x0, False)]
[(a, False), (f, False), (g, False), (h**2, False), (i, False), (x0, False), (b**2, False), (c, False), (h, False), (l, False), (x0, False)]
[(f, False), (x0, False), (h**2, False), (e, False), (i, False), (m, False), (b**2, False), (b, False), (j, False), (l, False), (x0, False)]
[(f, False), (x0, False), (h**2, False), (c, False), (e, False), (h, False), (l, False), (m, False), (b, False), (j, False), (l, False), (x0, False)]
[(i, False), (x0, False), (b**2, False), (c, False), (h, False), (l, False), (x0, False), (a, False), (b, False), (g, False), (j, False), (l, False)]
```

**Comment by isuruf** [comment] 2017-01-18 14:34
Duplicate of https://github.com/sympy/sympy/issues/11684

**Closed** 2017-01-18 15:45 UTC
