### ISSUE TITLE
Comparing Float Infinity with Core Infinity

### ISSUE THREAD

**Issue by kevinventullo** [sympy/sympy#8910] opened 2015-01-30 05:04 UTC
So while looking at Issue #8906 I came across a possibly related issue.

```
>>> from sympy.stats import *
>>> from sympy import Symbol
>>> x = Symbol("x")
>>> X = Uniform("u", 0, 1)
>>> P(X<.5)
Traceback (most recent call last):
  ...
    raise TypeError("cannot determine truth value of\n%s" % self)
TypeError: cannot determine truth value of
-oo < -inf
```

The Traceback involved intersecting some sets to figure out the domain of X, which is where the comparison `-oo < -inf` arose. I'll try to fix it quickly.

**Comment by kevinventullo** [comment] 2015-02-02 03:25
So I guess I have a more general question. Should it be the case that `oo == Float("inf")` evaluates to `True`?

**Comment by asmeurer** [comment] 2015-02-04 17:57
This is probably a dupe of https://github.com/sympy/sympy/issues/8451.

**Comment by kevinventullo** [comment] 2015-02-04 19:03
Would it be okay to alter the comparison methods (e.g. `__le__`) of `core.Infinity` so that `-oo < -Float("inf")` evaluates to false?

**Comment by emilienkofman** [comment] 2015-07-23 10:25
Hi,
I think it's related with your issue, and probably with #7765: I noticed that the expressions which involve +inf still return inconsistent results. For instance I get: 
    
    >>> nsimplify(float("inf"))
    zoo

and 

    >>> Rational(float("inf"))
    ...
    OverflowError: Cannot pass infinity to float.as_integer_ratio.

 Even if I admin that `float("inf") != oo` because the first one is inexact and the second one is exact, maybe `Rational(float("inf"))` should return oo? For instance 

    >>> Rational(1.5)
    3/2

(example of inexact to exact representation ?)

**Comment by oscarbenjamin** [comment] 2019-03-22 22:13
Seems to work fine now:
```
from sympy.stats import *
from sympy import Symbol
x = Symbol("x")
X = Uniform("u", 0, 1)
pprint(P(X<0.5))
```
Output:
```
0.500000000000000
```

**Closed** 2019-04-27 10:33 UTC
Labels: stats
