### ISSUE TITLE
solveset(I*cot(8*x - 8*E), x) inconsistent results based on keyboard interrupt

### ISSUE THREAD

**Issue by ethankward** [sympy/sympy#17543] opened 2019-08-29 16:39 UTC
`solveset(I*cot(8*x - 8*E), x)` takes a few seconds to run on my computer. If I interrupt the calculation by pressing ctrl+c, something catches the interrupt and I get a simple result:

```
>>> from sympy import *
>>> x = Symbol('x')
>>> solveset(I*cot(8*x - 8*E), x)
(pressing ctrl c before completion)
Union(ImageSet(Lambda(_n, _n*pi/4 + atan(tan(8*E) + sqrt(tan(8*E)**2 + 1))/4), Integers), ImageSet(Lambda(_n, _n*pi/4 - atan(-tan(8*E) + sqrt(tan(8*E)**2 + 1))/4 + pi/4), Integers))
```

 If I let the calculation run I get a much longer expression:

```
>>> solveset(I*cot(8*x - 8*E), x)
Union(Intersection(Complexes(ProductSet(Reals, Reals), False), ImageSet(Lambda(_n, -I*(I*(2*_n*pi + atan((sin(E)*sin(pi/16) - cos(E)*cos(pi/16))/(sin(pi/16)*cos(E) + sin(E)*cos(pi/16)))) + log(sqrt(sin(E)**2*sin(pi/16)**2 + sin(pi/16)**2*cos(E)**2 + sin(E)**2*cos(pi/16)**2 + cos(E)**2*cos(pi/16)**2)))), Integers)), Intersection(Complexes(ProductSet(Reals, Reals), False), ImageSet(Lambda(_n, -I*(I*(2*_n*pi + atan((sin(pi/16)*cos(E) + sin(E)*cos(pi/16))/(cos(E)*cos(pi/16) - sin(E)*sin(pi/16))) + pi) + log(sqrt(sin(E)**2*sin(pi/16)**2 + sin(pi/16)**2*cos(E)**2 + sin(E)**2*cos(pi/16)**2 + cos(E)**2*cos(pi/16)**2)))), Integers)), Intersection(Complexes(ProductSet(Reals, Reals), False), ImageSet(Lambda(_n, -I*(I*(2*_n*pi + atan((-sin(E)*cos(pi/16) - sin(pi/16)*cos(E))/(sin(E)*sin(pi/16) - cos(E)*cos(pi/16)))) + log(sqrt(sin(E)**2*sin(pi/16)**2 + sin(pi/16)**2*cos(E)**2 + sin(E)**2*cos(pi/16)**2 + cos(E)**2*cos(pi/16)**2)))), Integers)), Intersection(Complexes(ProductSet(Reals, Reals), False), ImageSet(Lambda(_n, -I*(I*(2*_n*pi - pi + atan((cos(E)*cos(pi/16) - sin(E)*sin(pi/16))/(-sin(E)*cos(pi/16) - sin(pi/16)*cos(E)))) + log(sqrt(sin(E)**2*sin(pi/16)**2 + sin(pi/16)**2*cos(E)**2 + sin(E)**2*cos(pi/16)**2 + cos(E)**2*cos(pi/16)**2)))), Integers)), Intersection(Complexes(ProductSet(Reals, Reals), False), ImageSet(Lambda(_n, -I*(I*(2*_n*pi + atan(((-sin(pi/16) + cos(pi/16))*cos(E) - (sin(pi/16) + cos(pi/16))*sin(E))/(-(-sin(pi/16) + cos(pi/16))*sin(E) - (sin(pi/16) + cos(pi/16))*cos(E)))) + log(sqrt(sin(E)**2*sin(pi/16)**2 + sin(pi/16)**2*cos(E)**2 + sin(E)**2*cos(pi/16)**2 + cos(E)**2*cos(pi/16)**2)))), Integers)), Intersection(Complexes(ProductSet(Reals, Reals), False), ImageSet(Lambda(_n, -I*(I*(2*_n*pi - pi + atan(((sin(pi/16) + cos(pi/16))*cos(E) + (-sin(pi/16) + cos(pi/16))*sin(E))/((-sin(pi/16) + cos(pi/16))*cos(E) - (sin(pi/16) + cos(pi/16))*sin(E)))) + log(sqrt(sin(E)**2*sin(pi/16)**2 + sin(pi/16)**2*cos(E)**2 + sin(E)**2*cos(pi/16)**2 + cos(E)**2*cos(pi/16)**2)))), Integers)), Intersection(Complexes(ProductSet(Reals, Reals), False), ImageSet(Lambda(_n, -I*(I*(2*_n*pi + atan(((sin(pi/16) + cos(pi/16))*sin(E) + (-cos(pi/16) + sin(pi/16))*cos(E))/((sin(pi/16) + cos(pi/16))*cos(E) - (-cos(pi/16) + sin(pi/16))*sin(E))) + pi) + log(sqrt(sin(E)**2*sin(pi/16)**2 + sin(pi/16)**2*cos(E)**2 + sin(E)**2*cos(pi/16)**2 + cos(E)**2*cos(pi/16)**2)))), Integers)), Intersection(Complexes(ProductSet(Reals, Reals), False), ImageSet(Lambda(_n, -I*(I*(2*_n*pi + atan(((-cos(pi/16) + sin(pi/16))*sin(E) - (sin(pi/16) + cos(pi/16))*cos(E))/((sin(pi/16) + cos(pi/16))*sin(E) + (-cos(pi/16) + sin(pi/16))*cos(E)))) + log(sqrt(sin(E)**2*sin(pi/16)**2 + sin(pi/16)**2*cos(E)**2 + sin(E)**2*cos(pi/16)**2 + cos(E)**2*cos(pi/16)**2)))), Integers)), Intersection(Complexes(ProductSet(Reals, Reals), False), ImageSet(Lambda(_n, -I*(I*(2*_n*pi - pi + atan(((sqrt(sqrt(2) + 2)*sin(pi/16) + sqrt(2 - sqrt(2))*cos(pi/16))*cos(E) + (-sqrt(2 - sqrt(2))*sin(pi/16) + sqrt(sqrt(2) + 2)*cos(pi/16))*sin(E))/((-sqrt(2 - sqrt(2))*sin(pi/16) + sqrt(sqrt(2) + 2)*cos(pi/16))*cos(E) - (sqrt(sqrt(2) + 2)*sin(pi/16) + sqrt(2 - sqrt(2))*cos(pi/16))*sin(E)))) + log(sqrt(sin(E)**2*sin(pi/16)**2 + sin(pi/16)**2*cos(E)**2 + sin(E)**2*cos(pi/16)**2 + cos(E)**2*cos(pi/16)**2)))), Integers)), Intersection(Complexes(ProductSet(Reals, Reals), False), ImageSet(Lambda(_n, -I*(I*(2*_n*pi - pi + atan(((sqrt(2 - sqrt(2))*sin(pi/16) + sqrt(sqrt(2) + 2)*cos(pi/16))*cos(E) + (-sqrt(sqrt(2) + 2)*sin(pi/16) + sqrt(2 - sqrt(2))*cos(pi/16))*sin(E))/(-(sqrt(2 - sqrt(2))*sin(pi/16) + sqrt(sqrt(2) + 2)*cos(pi/16))*sin(E) + (-sqrt(sqrt(2) + 2)*sin(pi/16) + sqrt(2 - sqrt(2))*cos(pi/16))*cos(E)))) + log(sqrt(sin(E)**2*sin(pi/16)**2 + sin(pi/16)**2*cos(E)**2 + sin(E)**2*cos(pi/16)**2 + cos(E)**2*cos(pi/16)**2)))), Integers)), Intersection(Complexes(ProductSet(Reals, Reals), False), ImageSet(Lambda(_n, -I*(I*(2*_n*pi + atan(((-sqrt(2 - sqrt(2))*cos(pi/16) + sqrt(sqrt(2) + 2)*sin(pi/16))*cos(E) + (sqrt(2 - sqrt(2))*sin(pi/16) + sqrt(sqrt(2) + 2)*cos(pi/16))*sin(E))/((sqrt(2 - sqrt(2))*sin(pi/16) + sqrt(sqrt(2) + 2)*cos(pi/16))*cos(E) - (-sqrt(2 - sqrt(2))*cos(pi/16) + sqrt(sqrt(2) + 2)*sin(pi/16))*sin(E))) + pi) + log(sqrt(sin(E)**2*sin(pi/16)**2 + sin(pi/16)**2*cos(E)**2 + sin(E)**2*cos(pi/16)**2 + cos(E)**2*cos(pi/16)**2)))), Integers)), Intersection(Complexes(ProductSet(Reals, Reals), False), ImageSet(Lambda(_n, -I*(I*(2*_n*pi + atan(((sqrt(sqrt(2) + 2)*sin(pi/16) + sqrt(2 - sqrt(2))*cos(pi/16))*sin(E) + (-sqrt(sqrt(2) + 2)*cos(pi/16) + sqrt(2 - sqrt(2))*sin(pi/16))*cos(E))/((sqrt(sqrt(2) + 2)*sin(pi/16) + sqrt(2 - sqrt(2))*cos(pi/16))*cos(E) - (-sqrt(sqrt(2) + 2)*cos(pi/16) + sqrt(2 - sqrt(2))*sin(pi/16))*sin(E))) + pi) + log(sqrt(sin(E)**2*sin(pi/16)**2 + sin(pi/16)**2*cos(E)**2 + sin(E)**2*cos(pi/16)**2 + cos(E)**2*cos(pi/16)**2)))), Integers)), Intersection(Complexes(ProductSet(Reals, Reals), False), ImageSet(Lambda(_n, -I*(I*(2*_n*pi + atan(((-sqrt(2 - sqrt(2))*sin(pi/16) + sqrt(sqrt(2) + 2)*cos(pi/16))*cos(E) - (sqrt(sqrt(2) + 2)*sin(pi/16) + sqrt(2 - sqrt(2))*cos(pi/16))*sin(E))/(-(-sqrt(2 - sqrt(2))*sin(pi/16) + sqrt(sqrt(2) + 2)*cos(pi/16))*sin(E) - (sqrt(sqrt(2) + 2)*sin(pi/16) + sqrt(2 - sqrt(2))*cos(pi/16))*cos(E)))) + log(sqrt(sin(E)**2*sin(pi/16)**2 + sin(pi/16)**2*cos(E)**2 + sin(E)**2*cos(pi/16)**2 + cos(E)**2*cos(pi/16)**2)))), Integers)), Intersection(Complexes(ProductSet(Reals, Reals), False), ImageSet(Lambda(_n, -I*(I*(2*_n*pi + atan(((-sqrt(sqrt(2) + 2)*cos(pi/16) + sqrt(2 - sqrt(2))*sin(pi/16))*sin(E) - (sqrt(sqrt(2) + 2)*sin(pi/16) + sqrt(2 - sqrt(2))*cos(pi/16))*cos(E))/((sqrt(sqrt(2) + 2)*sin(pi/16) + sqrt(2 - sqrt(2))*cos(pi/16))*sin(E) + (-sqrt(sqrt(2) + 2)*cos(pi/16) + sqrt(2 - sqrt(2))*sin(pi/16))*cos(E)))) + log(sqrt(sin(E)**2*sin(pi/16)**2 + sin(pi/16)**2*cos(E)**2 + sin(E)**2*cos(pi/16)**2 + cos(E)**2*cos(pi/16)**2)))), Integers)), Intersection(Complexes(ProductSet(Reals, Reals), False), ImageSet(Lambda(_n, -I*(I*(2*_n*pi + atan(((-sqrt(2 - sqrt(2))*cos(pi/16) + sqrt(sqrt(2) + 2)*sin(pi/16))*sin(E) - (sqrt(2 - sqrt(2))*sin(pi/16) + sqrt(sqrt(2) + 2)*cos(pi/16))*cos(E))/((-sqrt(2 - sqrt(2))*cos(pi/16) + sqrt(sqrt(2) + 2)*sin(pi/16))*cos(E) + (sqrt(2 - sqrt(2))*sin(pi/16) + sqrt(sqrt(2) + 2)*cos(pi/16))*sin(E)))) + log(sqrt(sin(E)**2*sin(pi/16)**2 + sin(pi/16)**2*cos(E)**2 + sin(E)**2*cos(pi/16)**2 + cos(E)**2*cos(pi/16)**2)))), Integers)), Intersection(Complexes(ProductSet(Reals, Reals), False), ImageSet(Lambda(_n, -I*(I*(2*_n*pi + atan((-(sqrt(2 - sqrt(2))*sin(pi/16) + sqrt(sqrt(2) + 2)*cos(pi/16))*sin(E) + (-sqrt(sqrt(2) + 2)*sin(pi/16) + sqrt(2 - sqrt(2))*cos(pi/16))*cos(E))/(-(-sqrt(sqrt(2) + 2)*sin(pi/16) + sqrt(2 - sqrt(2))*cos(pi/16))*sin(E) - (sqrt(2 - sqrt(2))*sin(pi/16) + sqrt(sqrt(2) + 2)*cos(pi/16))*cos(E)))) + log(sqrt(sin(E)**2*sin(pi/16)**2 + sin(pi/16)**2*cos(E)**2 + sin(E)**2*cos(pi/16)**2 + cos(E)**2*cos(pi/16)**2)))), Integers)))
```

**Comment by oscarbenjamin** [comment] 2019-08-29 16:48
This is why bare except is bad!

**Comment by gschintgen** [comment] 2019-08-29 16:48
I did not look at the details, but given my knowledge of solveset something like this *may* be the cause:

- `solve_trig` is called since the equation involves a trig function. The equation is rewritten to use exponentials and then passed to a poly/rational solver. This is slow and often suboptimal. There are issues filed.
- If you cancel, solveset seems to progress to other solvers. In this case it may end up in some of the other solvers, e.g. the regular polynomial solver which then proceeds to a change of variable. (Though, I'd rather expect `acot` in the solution in that case. Maybe it just "jumped" from `_solve_trig1` to `solve_trig2`. Both usually end up with `atan` solutions.)

If I find the time I'll file PRs to improve trig solving, notably by calling `_invert` from inside `solve_trig` if the equation only involves a single trig instance.

**Comment by oscarbenjamin** [comment] 2019-08-29 16:50
Maybe one of these is the culprit:
```console
$ git grep 'except:'
.ci/parse_durations_log.py:            except:
examples/all.py:    except:
sympy/core/basic.py:                except:
sympy/core/sympify.py:        except:  # the kern might cause unknown errors, so use bare except
sympy/geometry/ellipse.py:                except:
sympy/integrals/rubi/parsetools/parse.py:        except:
sympy/integrals/rubi/parsetools/parse.py:        except: #when s has no attribute args (like `bool`)
sympy/integrals/rubi/utility_function.py:        except:
sympy/integrals/rubi/utility_function.py:        except:
sympy/integrals/rubi/utility_function.py:        except:
sympy/integrals/rubi/utility_function.py:        except:
sympy/integrals/rubi/utility_function.py:            except:
sympy/integrals/rubi/utility_function.py:    except:
sympy/integrals/rubi/utility_function.py:    except:
sympy/integrals/rubi/utility_function.py:        except:
sympy/integrals/rubi/utility_function.py:        except:
sympy/integrals/rubi/utility_function.py:    except:
sympy/integrals/rubi/utility_function.py:    except:
sympy/utilities/tests/test_lambdify.py:            except:
sympy/utilities/tests/test_wester.py:    except:
sympy/vector/coordsysrect.py:        except:
sympy/vector/vector.py:        except:
sympy/vector/vector.py:        except:
```
We should *never* use bare except in SymPy.

**Comment by gschintgen** [comment] 2019-08-29 16:54
There are two instances of `except BaseException as error` right in `solve_trig`. Execution probably passed from `_solve_trig1` to `_solve_trig2`. (Which instead of rewrite-as-exp does rewrite-using-tangent-half-angle.)

**Comment by ethankward** [comment] 2019-08-29 16:57
Maybe something to add in the code quality check, once the uses are cleaned up.

**Comment by gschintgen** [comment] 2020-06-08 19:40
I think the bare or almost bare excepts in `solveset` have all been taken out by an earlier PR. #19507 adds a test for the equation and will close this issue.

**Closed** 2020-06-10 10:01 UTC
Labels: solvers.solveset
