### ISSUE TITLE
Interval.is_EmptySet not defined.

### ISSUE THREAD

**Issue by vahlkar** [sympy/sympy#11442] opened 2016-07-28 16:40 UTC
It seems that the field **is_EmptySet** from the class **Interval** is not assigned and therefore equal to `None` which is problematic if we want to use its value in Boolean expressions.

``` python
from sympy import Interval

i = Interval(2, 7)
if i.is_EmptySet == False:
    print("No bug !")
else:
    print("i.is_EmptySet =", i.is_EmptySet, "instead of False !")

# If is_EmptySet == None and not False or True, it can't be used in boolean expressions:
try:
    if not(i.is_EmptySet | False):
        print("No bug !")
except TypeError as e:
    print(e)
```

**Comment by rpisarev** [comment] 2016-07-30 20:54
If SymPy knows the fact about a thing, it will return in is_* True or False. But there are cases when SymPy doesn't know. 

We can (and have to probably) use `i.is_EmptySet is True`. 

If Interval() is valid (Interval(2, 7)) we won't get  empty set and in this case `Interval(2, 7).is_Empty is True` will give False.

If begin and end of Interval equal (Interval(2, 2)) we will get FiniteSet ({2}), that isn't empty, so `Interval(2, 2).is_Empty is True` will give False.

If end is less as begin (Interval(2, 1)), we will get EmptySet and `Interval(2, 1).is_Empty is True` will give True.

But, if SymPy doesn't know everything about begin and end, we won't get an accurate answer. E.g. 
`In [26]: a = Symbol('a', real=True)

In [27]: b = Symbol('b', real=True)

In [28]: I = Interval(a, b)

In [29]: a < b
Out[29]: a < b

In [30]: b < a
Out[30]: b < a`

We don't know, a < b or b < a.
So, I think we haven't to change this behavior.

**Comment by vahlkar** [comment] 2016-08-03 10:15
Thank you for the answer.

I understand why `is_EmptySet` would be equal to `None` in case of symbolic begin and end, but in the case I exposed above, it was known float values, so `is_EmptySet` should not be equal to `None` but initialised with `True` or `False` depending on the values (as you exposed in your comment).
In my example above we have `Interval(2,7).is_EmptySet` equal to `None` and in this case I found that a bit odd.

We can workaround this by using `is_EmptySet == True` or `is_EmptySet is True` but as it is supposed to be Boolean we shouldn't have to do that.
Besides when `is_EmptySet` is equal to `None`, `is_EmptySet is False` and `is_EmptySet is True` would gave the same result (False), so I think it is not consistent.

If I may suggest, I think that something like that would be more accurate:
- `is_EmptySet` equals to `True` or `False` whenever it is possible to know.
- In case it is not possible to know, a **custom exception could be raised** by Sympy when trying to access to the attribute value.
This way the programmer would be well aware when the `is_EmptySet` information is not available.

**Comment by rpisarev** [comment] 2016-08-03 14:33
I can add method about "is Empty?" in PR, but again this method can know nothing and return None. I think, it is by design SymPy.

**Comment by vahlkar** [comment] 2016-08-04 13:45
I was more thinking about customizing the actual `is_EmptySet` attribute by using the python `@property` feature, rather than adding a method.

But if you think the current behaviour is better then leave it this way. I just thought it could be more explicit with some exception but it may not correspond with Sympy's design.

But even with your previous explanation, I still don't understand **why** `Interval(2,7).is_EmptySet` is **equal to None** and not to False.

**Comment by rpisarev** [comment] 2016-08-06 18:27
@vahlkar Can you try this branch? #11483

**Comment by vahlkar** [comment] 2016-08-08 13:40
I ran your test and It seems to work fine.

Thank you for that !

**Comment by rpisarev** [comment] 2016-08-08 14:58
Ok. I'll fix some test and hope for merge :)

**Comment by gxyd** [comment] 2016-08-15 09:58
The issue has not been fixed in the master9(that PR has not been merged), so I am reopening this issue.

**Comment by smichr** [comment] 2019-06-02 17:49
`Interval(x,y).is_EmptySet -> None` so I am closing this issue and related PRs

**Closed by smichr** 2019-06-02 17:49 UTC
Labels: sets
