### ISSUE TITLE
doit does nothing on a hadamard_product

### ISSUE THREAD

**Issue by moorepants** [sympy/sympy#8557] opened 2014-12-03 21:27 UTC
I would expect `doit()` to do the elementwise multiplication and return a single matrix:

```
In [15]: h = sympy.hadamard_product(sympy.Matrix([1, 1]), sympy.Matrix([2, 2]))

In [16]: h
Out[16]: 
Matrix([
[1],
[1]]).*Matrix([
[2],
[2]])

In [17]: h.doit()
Out[17]: 
Matrix([
[1],
[1]]).*Matrix([
[2],
[2]])

In [18]: sympy.__version__
Out[18]: '0.7.6-git'

```

**Comment by kshitij10496** [comment] 2015-12-21 17:23
I would like to work on this if #8604 doesn't fix this completely

**Comment by moorepants** [comment] 2015-12-22 01:50
This hasn't been worked on for a while, so you are welcome to jump in on it.

**Comment by codesep** [comment] 2017-02-14 07:37
@moorepants I would like to work on this issue.

**Comment by moorepants** [comment] 2017-02-14 16:15
Go for it.

**Comment by oscarbenjamin** [comment] 2019-10-31 23:55
I'm removing the 1.5 milestone from this issue because I don't see any particular reason for this to hold up the 1.5 release.

**Comment by czgdp1807** [comment] 2019-11-17 06:30
```python
Python 3.6.8 (default, Oct  7 2019, 12:59:55) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from sympy import *
>>> a = Matrix([1, 1])
>>> b = Matrix([2, 2])
>>> h = hadamard_product(a, b)
>>> h
Matrix([
[2],
[2]])
>>> X = MatrixSymbol('X', 2, 1)
>>> Y = MatrixSymbol('Y', 2, 1)
>>> hadamard_product(X, Y)
HadamardProduct(X, Y)
>>> hadamard_product(a, X, b, Y)
HadamardProduct(Matrix([
[2],
[2]]), X, Y)
>>> hadamard_product(X, Y).doit()
HadamardProduct(X, Y)
>>> hadamard_product(a, X, b, Y).doit()
HadamardProduct(Matrix([
[2],
[2]]), X, Y)
>>> hadamard_product(Matrix([1, 1]), Matrix([2, 2])).doit()
Matrix([
[2],
[2]])
>>> 
```
It looks like the issue is resolved. Though the session [here](https://github.com/sympy/sympy/pull/8604#issue-25955766) depicts a little bit different outputs but I the ones on the master are also fine and interpret-able. So probably we can close this.

**Comment by czgdp1807** [comment] 2019-12-13 06:46
@oscarbenjamin @moorepants So, can we close this?

**Comment by czgdp1807** [comment] 2020-03-09 18:12
Closing this in reference to above comments. Feel free to re-open it if there is a need or let us know if you are unable to that. Thanks for the contributions.

**Closed by czgdp1807** 2020-03-09 18:12 UTC
Labels: Could Close, Easy to Fix, matrices
