### ISSUE TITLE
SymPy Deprecation Warning

### ISSUE THREAD

**Issue by skeshvar** [sympy/sympy#20878] opened 2021-01-30 15:53 UTC
I'm using Spyder version 4.2.2 on windows 10. Since the last update, even by pressing the enter in Console, I get the following:

SymPyDeprecationWarning: 

C, including its class ClassRegistry, has been deprecated since SymPy
1.0. It will be last supported in SymPy version 1.0. Use direct
imports from the defining module instead. See
https://github.com/sympy/sympy/issues/9371 for more info.

  deprecated_since_version='1.0').warn(stacklevel=2)

I have noticed that if I'm using the Sympy library directly by importing it then there is no problem but using other libraries like numpy or matpltlib triggers this waring. If any one can help?

**Comment by oscarbenjamin** [comment] 2021-01-30 16:49
This is a duplicate of #9371. The class registry just needs to be deleted.

**Closed** 2021-01-30 16:49 UTC

**Comment by skeshvar** [comment] 2021-01-30 16:57
So how can I delete this registry? I only know python in form of data analysis. I'm not a programmer.

**Comment by oscarbenjamin** [comment] 2021-01-30 17:13
See the other issue
