### ISSUE TITLE
Extra space when printing latex using `sympy.physics.quantum.innerproduct` 

### ISSUE THREAD

**Issue by alex180500** [sympy/sympy#25979] opened 2023-12-12 14:15 UTC
When using `sympy.physics.quantum.innerproduct` with the latex printing an additional space is present inside the Bra. This is due to the `InnerProduct._latex()` method that returns something which has in the middle `\right. {\left|`.
This should be modified and changed into something that has `\left\langle` then `\middle|` and then `\right\rangle`.

<img width="459" alt="image" src="https://github.com/sympy/sympy/assets/30732244/3a2b48ce-cf68-47ff-a762-1a7373ec001a">

**Comment by abhiphile** [comment] 2023-12-20 21:17
I guess you are using VS Code to run this code . There is no problem with the sympy code here because it gives correct output on using Jupyter Lab . I have also checked the cell output using another website and it shows the correct result without any extra space. 
The problem is with VS Code mathjax printing
``` $\displaystyle \left\langle A^{2} \right. {\left|A^{2}\right\rangle }$ ```
![image](https://github.com/sympy/sympy/assets/140839576/fd8ae72d-9a0c-49bf-8a77-9561cdbf3e42)
![image](https://github.com/sympy/sympy/assets/140839576/72d333d8-4ea4-40a3-b437-7253fd68a9eb)

**Comment by alex180500** [comment] 2023-12-21 10:34
Okay I have opened the issue on https://github.com/microsoft/vscode-jupyter/issues/14948.

**Comment by oscarbenjamin** [comment] 2023-12-21 12:35
Unless there is something wrong with the LaTeX output by SymPy this is not a SymPy issue. I'm going to close this.

**Closed by oscarbenjamin** 2023-12-21 12:35 UTC
