### ISSUE TITLE
test_comb_factorials failing

### ISSUE THREAD

**Issue by sylee957** [sympy/sympy#16288] opened 2019-03-17 09:24 UTC
from https://travis-ci.org/sympy/sympy/jobs/507420319
```
________________________________________________________________________________
 sympy/functions/combinatorial/tests/test_comb_factorials.py:test_ff_eval_apply 
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/sympy-1.4.dev0-py3.7.egg/sympy/utilities/runtests.py", line 1306, in _timeout
    function()
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/sympy-1.4.dev0-py3.7.egg/sympy/functions/combinatorial/tests/test_comb_factorials.py", line 134, in test_ff_eval_apply
    assert (abs(mpmath_ff(x, k) - ff(x, k)) < 10**(-15))
AssertionError
```

I believe that the test is a random test

```
random seed:        55760217
hash randomization: on (PYTHONHASHSEED=268721948)
```

**Comment by sylee957** [comment] 2019-10-04 11:19
I see it fails again today
https://travis-ci.org/sympy/sympy/jobs/593376436
Maybe the tolerance should be raised.

**Comment by sylee957** [comment] 2019-10-13 09:04
Okay, I have concluded that the tolerance should be raised because of the spurious failings related to the difference of the outputs than the mpmath function, due the the automatic precision controls in #17697 
If anyone takes up this issue, I'd expect to raise the tolerance, and also to make the error message more descriptive about the test failing,

**Comment by oscarbenjamin** [comment] 2019-10-13 11:14
A previous issue like this #15575 turned out to be a problem in mpmath that I raised as https://github.com/fredrik-johansson/mpmath/issues/421 which was then fixed in https://github.com/fredrik-johansson/mpmath/commit/4d1e5b691f1285e00334f7d4f8b64cc9588355bf

Maybe this is also due to an inaccurate result from mpmath that should be reported upstream.

**Comment by Psycho-Pirate** [comment] 2019-10-14 23:55
I would like to work on this issue, please guide me through!

**Comment by oscarbenjamin** [comment] 2019-10-15 00:01
The first thing is to try and reproduce the failure and then figure out what the inputs to ff are when it fails. I guess that means you run with Python 3.7 and the same seed and hash-seed reported above.

**Comment by oscarbenjamin** [comment] 2019-10-15 01:37
@sylee957 are you able to reproduce this? I tried
```
$ SPLIT=1/2 PYTHONHASHSEED=268721948 bin/test --seed=55760217
```
with Python 3.8 but the test passed.

**Comment by sylee957** [comment] 2019-10-15 02:06
I have this example failing in `10^-15` tolerance
`
x =  -0.9910348979719856
k =  -2.026640039881954

abs(mpmath_ff(x, k) - ff(x, k))
`

**Comment by sylee957** [comment] 2019-10-15 08:56
I guess that we should not use the tolerance like `10**(-15)`

I see that mpmath only guarantees the precision based on the significant digits.
```python
from mpmath import *

x = mpf('-0.9910348979719856')
k = mpf('-2.026640039881954')

with workdps(15):
    print(ff(x, k))

with workdps(16):
    print(ff(x, k))
    
with workdps(17):
    print(ff(x, k))
    
with workdps(18):
    print(ff(x, k))
```
```
109.272823454199
109.2728234541985
109.27282345419854
109.272823454198537
```
So the tolerance should also be based scaled based on the magnitude the result. 
In this case, it should be `10**-12`

As you can see in this plot, there are some outrageously large values when `x` is nearly an integer.
![1](https://user-images.githubusercontent.com/34944973/66816127-7e8e2380-ef74-11e9-8314-45c3b06ae3e4.png)
Probably, this can give a clue why some luckily picked random numbers had given test failings.

**Comment by oscarbenjamin** [comment] 2019-10-15 12:35
We should have something like the allclose function from numpy:
```
def numerically_close(a, b, atol=1e-15, rtol=1e-15):
    return abs(a - b) <= (atol + rtol * abs(b))
```

**Comment by Anjali167-sopho** [comment] 2020-01-05 18:57
If no one is working on this issue and the issue is still open. Can I start working on it?
Also, it would be great, if anyone could guide me as to where to start from

**Comment by sylee957** [comment] 2020-01-05 22:00
I’d expect that changing to a relative tolerance like abs(a-b) < abs(a) * 1e-12 can make it work.
But you should be running the test with customized 10000 iterations to see if this doesn’t fail randomly.

**Comment by mijo2** [comment] 2020-01-25 08:39
@sylee957 Has this issue been fixed? If not then I would like to work on it.

**Comment by mijo2** [comment] 2020-01-25 09:17
@sylee957 I ran the tests. With the following
```
x =  -0.9910348979719856
k =  -2.026640039881954
``` 
and with tolerance ```10**-15``` the assertion error was raised but with tolerance 10**-12 and running it for 10000 times with both the same ```x```, ```k``` given above and random ```x```, ```k```, the tests passed
![github_16_issue1](https://user-images.githubusercontent.com/25644913/73118976-8b61e080-3f81-11ea-8a27-6d1fb78f4e35.png)
![github_isse_16_2](https://user-images.githubusercontent.com/25644913/73118980-93218500-3f81-11ea-8c02-8f7719683142.png)

**Comment by sylee957** [comment] 2020-01-25 09:31
No, actually, I’m thinking of setting the tolerance like abs(a)*10**-15

We need to be careful about the one in mpmath because it guarantees some tolerance. And what I read from the theory of ‘significant digits’ it should be correct that the absolute tolerance scales with the magnitude.

For other numeric libraries like scipy or tensorflow, they can give a lot of low-precision results, so downright raising the tolerance can be a good idea

**Comment by mijo2** [comment] 2020-01-25 09:34
Ok will try some tests with abs(a) * 10**-15 then.

**Comment by mijo2** [comment] 2020-01-25 09:36
The tests didn't give an assertion error this time as well.
![github_issue_16_3](https://user-images.githubusercontent.com/25644913/73119196-4f7c4a80-3f84-11ea-8548-3c408cd1ccaf.png)

**Comment by sylee957** [comment] 2020-01-25 10:55
Okay, then I’d suggest to go for using the scaled tolerance

**Comment by mijo2** [comment] 2020-01-25 10:56
Ok @sylee957 sure thing, I would create a PR and change the tolerance for ```ff``` tests.

**Closed** 2020-01-25 12:42 UTC
Labels: Easy to Fix, Testing, combinatorics, functions
