### ISSUE TITLE
Comparing micrometers to kilometers

### ISSUE THREAD

**Issue by angstr0m** [sympy/sympy#24089] opened 2022-09-27 14:08 UTC
First I would like to say that Sympy is the best CAS system I have used by far :). I'm very happy with it in general. However there is one small issue:

I just had a use case, where I needed to convert metric length units. This works fine, except when trying to compare micrometers to kilometers.

I have a Python Shell with the following imports (and only those):
`from sympy import *`
`from sympy.physics.units import *`

Converting works as expected:
`>>> convert_to(1.6*um, km)`
`1.6e-9*kilometer`

Comparing micrometers to meters works as expected:
`>>> simplify(Eq(1.6e-6*m, 1.6*um))`
`True`

Comparing micrometers to kilometers fails (this should be true):
`>>> simplify(Eq(1.6e-9*km, 1.6*um))`
`Eq(1.6e-9*kilometer, 1.6*micrometer)`

Is this a bug or am I overlooking something?

I'm using Python 3.10.2 with Sympy 1.11.1 in a Poetry virtual environment.

**Comment by smichr** [comment] 2022-09-27 15:04
If you work with exact numbers, not float, it works and `simplify(Eq(1.6e-9*km, 1.6*um)) -> True`. What appears to be trivially true in decimal may not be true (enough) in float to make it work.

    
![image](https://user-images.githubusercontent.com/90703/192563348-4b085386-6eb4-40f5-adc4-87d7cb61c555.png)

**Comment by anurag629** [comment] 2022-09-27 19:06
I want to work on this @smichr can you assign me

**Comment by smichr** [comment] 2022-09-27 22:49
@anurag629, we don't assign PRs. You can talk about possible solutions here and if it sounds like you've got a good direction, feel free to open a PR. If you think you know what the issue is and what the solution should be, then just go ahead and open a PR. I am skeptical that there is a nice solution -- when someone uses floats they automatically run into issues with precision. This has nothing to do with units, per se, as I *think* my example above shows.

**Comment by cocolato** [comment] 2022-09-28 06:26
You should set `rational=True` to avoid lose float precision.
```python
>>> from sympy import simplify, Eq
>>> from sympy.physics.units import km, um, kilometer, micrometer, m
>>> simplify(Eq(1.6e-9*km, 1.6*um))
Eq(1.6e-9*kilometer, 1.6*micrometer)
>>> simplify(Eq(1.6e-9*km, 1.6*um), rational=True)
True
```

**Comment by smichr** [comment] 2022-09-28 17:26
I think it's ok to close. We wouldn't use `nsimplify` internally without some way to test that it satisfied the original equality (of units).

**Comment by oscarbenjamin** [comment] 2022-09-28 21:19
Yes, I think it's fine to close this.

**Closed by oscarbenjamin** 2022-09-28 21:19 UTC
Labels: simplify, floats, physics.units
