### ISSUE TITLE
problem in "factor" function

### ISSUE THREAD

**Issue by Hakim777** [sympy/sympy#23713] opened 2022-06-30 22:56 UTC
I'm trying to use the function "factor" to a list of expressions (long expressions). But when I run the code it works for first hundreds  elements of the list and then it freezes, so I have to re-run it again to complete factoring the rest of the expressions. It seems that the function: "factor" doesn't work with some of the expressions from first time. 
I'm using sympy 1.9

Could you help me with this issue.

**Comment by smichr** [comment] 2022-06-30 23:21
Do you want to factor or just remove common sub-expressions? In either case it will be easier to help if you post the code.

**Comment by oscarbenjamin** [comment] 2022-07-01 12:07
Factorisation can be a slow operation in general but it's possible that this is due to a bug. You haven't provided any information that anyone else could use to diagnose that though.

GitHub issues are for reporting bugs or suggesting improvements to SymPy (use the mailing list to get help with using SymPy). This issue does not contain any information that would make it useful for making any improvements to SymPy I recommend closing.

**Comment by Hakim777** [comment] 2022-07-01 19:12
This is an example:

`expr = '8*e^6*i^2*(12*m_e^10 + 6*m_e^8*s_12 - 6*m_e^8*s_13 - 6*m_e^8*s_15 + 2*m_e^8*s_22 + 38*m_e^8*s_33 + 72*m_e^8*s_35 - m_e^6*s_12*s_22 + 4*m_e^6*s_12*s_23 + 4*m_e^6*s_12*s_25 + 17*m_e^6*s_12*s_33 + 32*m_e^6*s_12*s_35 + 2*m_e^6*s_13*s_22 - 6*m_e^6*s_13*s_23 - 6*m_e^6*s_13*s_25 - 16*m_e^6*s_13*s_33 - 30*m_e^6*s_13*s_35 + 2*m_e^6*s_15*s_22 - 6*m_e^6*s_15*s_23 - 6*m_e^6*s_15*s_25 - 16*m_e^6*s_15*s_33 - 30*m_e^6*s_15*s_35 + 10*m_e^6*s_22*s_35 + 8*m_e^6*s_23^2 - 16*m_e^6*s_23*s_25 - 8*m_e^6*s_25^2 + 36*m_e^6*s_33^2 + 150*m_e^6*s_33*s_35 + 148*m_e^6*s_35^2 - 4*m_e^4*s_12*s_22*s_33 - 5*m_e^4*s_12*s_22*s_35 + 4*m_e^4*s_12*s_23^2 - 8*m_e^4*s_12*s_23*s_25 + 8*m_e^4*s_12*s_23*s_33 + 20*m_e^4*s_12*s_23*s_35 - 4*m_e^4*s_12*s_25^2 + 8*m_e^4*s_12*s_25*s_33 + 20*m_e^4*s_12*s_25*s_35 + 14*m_e^4*s_12*s_33^2 + 57*m_e^4*s_12*s_33*s_35 + 54*m_e^4*s_12*s_35^2 - 2*m_e^4*s_13*s_22*s_23 + 2*m_e^4*s_13*s_22*s_25 + 8*m_e^4*s_13*s_22*s_33 + 10*m_e^4*s_13*s_22*s_35 + 8*m_e^4*s_13*s_23*s_25 - 18*m_e^4*s_13*s_23*s_33 - 34*m_e^4*s_13*s_23*s_35 - 14*m_e^4*s_13*s_25*s_33 - 26*m_e^4*s_13*s_25*s_35 - 10*m_e^4*s_13*s_33^2 - 44*m_e^4*s_13*s_33*s_35 - 44*m_e^4*s_13*s_35^2 + 2*m_e^4*s_15*s_22*s_23 + 2*m_e^4*s_15*s_22*s_25 + 8*m_e^4*s_15*s_22*s_33 + 10*m_e^4*s_15*s_22*s_35 - 8*m_e^4*s_15*s_23^2 - 14*m_e^4*s_15*s_23*s_33 - 26*m_e^4*s_15*s_23*s_35 - 14*m_e^4*s_15*s_25*s_33 - 26*m_e^4*s_15*s_25*s_35 - 10*m_e^4*s_15*s_33^2 - 44*m_e^4*s_15*s_33*s_35 - 44*m_e^4*s_15*s_35^2 - 2*m_e^4*s_22*s_33^2 + 4*m_e^4*s_22*s_33*s_35 + 20*m_e^4*s_22*s_35^2 - 8*m_e^4*s_23^2*s_33 + 8*m_e^4*s_23^2*s_35 - 48*m_e^4*s_23*s_25*s_33 - 80*m_e^4*s_23*s_25*s_35 - 8*m_e^4*s_25^2*s_33 - 24*m_e^4*s_25^2*s_35 + 10*m_e^4*s_33^3 + 76*m_e^4*s_33^2*s_35 + 172*m_e^4*s_33*s_35^2 + 120*m_e^4*s_35^3 - 3*m_e^2*s_12*s_22*s_33^2 - 10*m_e^2*s_12*s_22*s_33*s_35 - 6*m_e^2*s_12*s_22*s_35^2 - 4*m_e^2*s_12*s_23^2*s_33 + 4*m_e^2*s_12*s_23^2*s_35 - 24*m_e^2*s_12*s_23*s_25*s_33 - 40*m_e^2*s_12*s_23*s_25*s_35 + 4*m_e^2*s_12*s_23*s_33^2 + 24*m_e^2*s_12*s_23*s_33*s_35 + 32*m_e^2*s_12*s_23*s_35^2 - 4*m_e^2*s_12*s_25^2*s_33 - 12*m_e^2*s_12*s_25^2*s_35 + 4*m_e^2*s_12*s_25*s_33^2 + 24*m_e^2*s_12*s_25*s_33*s_35 + 32*m_e^2*s_12*s_25*s_35^2 + 3*m_e^2*s_12*s_33^3 + 22*m_e^2*s_12*s_33^2*s_35 + 46*m_e^2*s_12*s_33*s_35^2 + 28*m_e^2*s_12*s_35^3 + 2*m_e^2*s_13*s_22*s_23*s_33 - 2*m_e^2*s_13*s_22*s_23*s_35 + 6*m_e^2*s_13*s_22*s_25*s_33 + 10*m_e^2*s_13*s_22*s_25*s_35 + 6*m_e^2*s_13*s_22*s_33^2 + 20*m_e^2*s_13*s_22*s_33*s_35 + 12*m_e^2*s_13*s_22*s_35^2 + 8*m_e^2*s_13*s_23*s_25*s_33 + 24*m_e^2*s_13*s_23*s_25*s_35 - 8*m_e^2*s_13*s_23*s_33^2 - 42*m_e^2*s_13*s_23*s_33*s_35 - 48*m_e^2*s_13*s_23*s_35^2 - 8*m_e^2*s_13*s_25^2*s_33 - 8*m_e^2*s_13*s_25^2*s_35 - 4*m_e^2*s_13*s_25*s_33^2 - 22*m_e^2*s_13*s_25*s_33*s_35 - 24*m_e^2*s_13*s_25*s_35^2 - 6*m_e^2*s_13*s_33^2*s_35 - 20*m_e^2*s_13*s_33*s_35^2 - 16*m_e^2*s_13*s_35^3 + 6*m_e^2*s_15*s_22*s_23*s_33 + 10*m_e^2*s_15*s_22*s_23*s_35 + 2*m_e^2*s_15*s_22*s_25*s_33 + 6*m_e^2*s_15*s_22*s_25*s_35 + 6*m_e^2*s_15*s_22*s_33^2 + 20*m_e^2*s_15*s_22*s_33*s_35 + 12*m_e^2*s_15*s_22*s_35^2 - 8*m_e^2*s_15*s_23^2*s_33 - 24*m_e^2*s_15*s_23^2*s_35 + 8*m_e^2*s_15*s_23*s_25*s_33 + 8*m_e^2*s_15*s_23*s_25*s_35 - 4*m_e^2*s_15*s_23*s_33^2 - 22*m_e^2*s_15*s_23*s_33*s_35 - 24*m_e^2*s_15*s_23*s_35^2 - 8*m_e^2*s_15*s_25*s_33^2 - 34*m_e^2*s_15*s_25*s_33*s_35 - 32*m_e^2*s_15*s_25*s_35^2 - 6*m_e^2*s_15*s_33^2*s_35 - 20*m_e^2*s_15*s_33*s_35^2 - 16*m_e^2*s_15*s_35^3 + 2*m_e^2*s_22*s_33^2*s_35 + 12*m_e^2*s_22*s_33*s_35^2 + 16*m_e^2*s_22*s_35^3 - 8*m_e^2*s_23^2*s_33*s_35 - 48*m_e^2*s_23*s_25*s_33*s_35 - 64*m_e^2*s_23*s_25*s_35^2 + 16*m_e^2*s_25^2*s_33^2 + 24*m_e^2*s_25^2*s_33*s_35 + 6*m_e^2*s_33^3*s_35 + 32*m_e^2*s_33^2*s_35^2 + 56*m_e^2*s_33*s_35^3 + 32*m_e^2*s_35^4 - s_12*s_22*s_33^2*s_35 - 2*s_12*s_22*s_33*s_35^2 - 4*s_12*s_23^2*s_33*s_35 - 24*s_12*s_23*s_25*s_33*s_35 - 32*s_12*s_23*s_25*s_35^2 + 4*s_12*s_23*s_33^2*s_35 + 16*s_12*s_23*s_33*s_35^2 + 16*s_12*s_23*s_35^3 + 8*s_12*s_25^2*s_33^2 + 12*s_12*s_25^2*s_33*s_35 + 4*s_12*s_25*s_33^2*s_35 + 16*s_12*s_25*s_33*s_35^2 + 16*s_12*s_25*s_35^3 + s_12*s_33^3*s_35 + 4*s_12*s_33^2*s_35^2 + 4*s_12*s_33*s_35^3 + 2*s_13*s_22*s_23*s_33*s_35 + 6*s_13*s_22*s_25*s_33*s_35 + 8*s_13*s_22*s_25*s_35^2 + 2*s_13*s_22*s_33^2*s_35 + 4*s_13*s_22*s_33*s_35^2 + 8*s_13*s_23*s_25*s_33*s_35 + 16*s_13*s_23*s_25*s_35^2 - 4*s_13*s_23*s_33^2*s_35 - 16*s_13*s_23*s_33*s_35^2 - 16*s_13*s_23*s_35^3 - 8*s_13*s_25^2*s_33^2 - 24*s_13*s_25^2*s_33*s_35 - 16*s_13*s_25^2*s_35^2 + 6*s_15*s_22*s_23*s_33*s_35 + 8*s_15*s_22*s_23*s_35^2 - 4*s_15*s_22*s_25*s_33^2 - 6*s_15*s_22*s_25*s_33*s_35 + 2*s_15*s_22*s_33^2*s_35 + 4*s_15*s_22*s_33*s_35^2 - 8*s_15*s_23^2*s_33*s_35 - 16*s_15*s_23^2*s_35^2 + 8*s_15*s_23*s_25*s_33^2 + 24*s_15*s_23*s_25*s_33*s_35 + 16*s_15*s_23*s_25*s_35^2 - 4*s_15*s_25*s_33^3 - 20*s_15*s_25*s_33^2*s_35 - 32*s_15*s_25*s_33*s_35^2 - 16*s_15*s_25*s_35^3)/(4*m_e^8*s_14^2 - 4*m_e^8*s_14*s_44 + m_e^8*s_44^2 + 16*m_e^6*s_14^2*s_33 + 32*m_e^6*s_14^2*s_35 - 16*m_e^6*s_14*s_33*s_44 - 32*m_e^6*s_14*s_35*s_44 + 4*m_e^6*s_33*s_44^2 + 8*m_e^6*s_35*s_44^2 + 24*m_e^4*s_14^2*s_33^2 + 96*m_e^4*s_14^2*s_33*s_35 + 96*m_e^4*s_14^2*s_35^2 - 24*m_e^4*s_14*s_33^2*s_44 - 96*m_e^4*s_14*s_33*s_35*s_44 - 96*m_e^4*s_14*s_35^2*s_44 + 6*m_e^4*s_33^2*s_44^2 + 24*m_e^4*s_33*s_35*s_44^2 + 24*m_e^4*s_35^2*s_44^2 + 16*m_e^2*s_14^2*s_33^3 + 96*m_e^2*s_14^2*s_33^2*s_35 + 192*m_e^2*s_14^2*s_33*s_35^2 + 128*m_e^2*s_14^2*s_35^3 - 16*m_e^2*s_14*s_33^3*s_44 - 96*m_e^2*s_14*s_33^2*s_35*s_44 - 192*m_e^2*s_14*s_33*s_35^2*s_44 - 128*m_e^2*s_14*s_35^3*s_44 + 4*m_e^2*s_33^3*s_44^2 + 24*m_e^2*s_33^2*s_35*s_44^2 + 48*m_e^2*s_33*s_35^2*s_44^2 + 32*m_e^2*s_35^3*s_44^2 + 4*s_14^2*s_33^4 + 32*s_14^2*s_33^3*s_35 + 96*s_14^2*s_33^2*s_35^2 + 128*s_14^2*s_33*s_35^3 + 64*s_14^2*s_35^4 - 4*s_14*s_33^4*s_44 - 32*s_14*s_33^3*s_35*s_44 - 96*s_14*s_33^2*s_35^2*s_44 - 128*s_14*s_33*s_35^3*s_44 - 64*s_14*s_35^4*s_44 + s_33^4*s_44^2 + 8*s_33^3*s_35*s_44^2 + 24*s_33^2*s_35^2*s_44^2 + 32*s_33*s_35^3*s_44^2 + 16*s_35^4*s_44^2)'

e,i , m_e ,m_mu, m_t, m_u, m_d, m_s, m_c, m_tt, m_b, s_11, s_12, s_13, s_14, s_15, s_22, s_23, s_24, s_25, s_33, s_34, s_35, s_44,s_45 ,s_55 = sp.symbols('e, i ,m_e, m_mu, m_t, m_u, m_d, m_s, m_c, m_tt, m_b, s_11, s_12, s_13, s_14, s_15, s_22, s_23, s_24, s_25, s_33, s_34, s_35, s_44,s_45 ,s_55')


sp.factor(expr, m_e) `



If you run this code, you will find that it works sometimes and sometimes it doesn't (freeze)

**Comment by oscarbenjamin** [comment] 2022-07-01 20:12
I think this is a duplicate of #20456

**Closed** 2022-07-02 21:33 UTC
Labels: Could Close
