### ISSUE TITLE
Cannot use typing.Generic[T] with Symbol

### ISSUE THREAD

**Issue by TrakJohnson** [sympy/sympy#25399] opened 2023-07-19 12:13 UTC
I'm trying to subclass `Symbol` generically, but I cannot:

```python
In [35]: from typing import Generic, TypeVar

In [36]: T = TypeVar("T")

In [37]: class A(Symbol, Generic[T]):
    ...:     pass
    ...: 

In [38]: class B(A[T]):
    ...:     pass
    ...: 
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[38], line 1
----> 1 class B(A[T]):
      2     pass

File /usr/lib/python3.10/typing.py:309, in _tp_cache.<locals>.decorator.<locals>.inner(*args, **kwds)
    306 @functools.wraps(func)
    307 def inner(*args, **kwds):
    308     try:
--> 309         return cached(*args, **kwds)
    310     except TypeError:
    311         pass  # All real errors (not unhashable args) are raised below.

File /usr/lib/python3.10/typing.py:1342, in Generic.__class_getitem__(cls, params)
   1338         raise TypeError(
   1339             f"Parameters to {cls.__name__}[...] must all be unique")
   1340 else:
   1341     # Subscripting a regular Generic subclass.
-> 1342     if any(isinstance(t, ParamSpec) for t in cls.__parameters__):
   1343         params = _prepare_paramspec_params(cls, params)
   1344     else:

AttributeError: type object 'A' has no attribute '__parameters__'
```

This is linked to `sympy.Symbol`, because subclassing from anything else works (here with an empty class, but I tried with other classes not linked to Sympy and couldn't reproduce):

```python
In [40]: class K():
    ...:     pass
    ...: 

In [41]: class A(K, Generic[T]):
    ...:     pass
    ...: 

In [42]: class B(A[T]):
    ...:     pass
    ...: 
# no exception
```

I'm not sure if all classes are supposed to support this or not. Does the `Symbol` class modify/delete `__parameters__` ? `typing.Generics` work with multiple inheritance, is there something in `Symbol` which is uncompatible ?

Thank you for the help!

---

python: 3.10
sympy: 1.12

**Comment by oscarbenjamin** [comment] 2023-07-20 11:33
Basic uses `__init_subclass__`. I guess it needs to call `super().__init_subclass__` so that `Generic[T].__init_subclass__` can initialise `__parameters__` on the class object:
https://github.com/sympy/sympy/blob/12d7761b5033628cc12dc2f3b3df9546c2378086/sympy/core/basic.py#L116-L121

I don't know why you want to subclass Symbol but to be clear classes like Symbol are not designed to be subclassed. I can imagine things that might go wrong unless it is done very carefully. Probably a better approach is to subclass `Expr` and define a class separate from `Symbol` (`Expr` is designed to be subclassed).

**Comment by TrakJohnson** [comment] 2023-07-20 16:33
Fair, I guess there is always an alternate solution. 

However, in applications where the goal is for the end user (the person using my code) to declare equations easily without knowing much Python (think physics DSL, Modelica-style, ...), it's really nice interface-wise to be able to not have extra constructs on the side that have to be stored statefully, to be able to store additional information in an `Eq`, etc. Using composition also doesn't work, because I need to get the data by reading through the `Eq`.

Also, this is what I meant by not being able to use solve:

```
In [1]: from sympy import AtomicExpr, solve

In [2]: class MySym(AtomicExpr):
   ...:     def __init__(self, name):
   ...:         self.name = name

In [3]: x = MySym("x")

In [5]: solve(x, x)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
.../python3.10/site-packages/sympy/core/basic.py:528, in <listcomp>(.0)
    515 @property
    516 def free_symbols(self):
    517     """Return from the atoms of self those which are free symbols.
    518 
    519     For most expressions, all symbols are free symbols. For some classes
   (...)
    526     Any other method that uses bound variables should implement a
    527     free_symbols method."""
--> 528     return set().union(*[a.free_symbols for a in self.args])

AttributeError: 'str' object has no attribute 'free_symbols'
```
If I make `free_symbols` to be the set `{self}` like in `Symbol`, I get another missing property, etc. which leads me to kind of rebuild `Symbol`.

Anyways, I get it, no subclassing :) From what I understand I was trying to stretch sympy beyond what it's supposed to do for not much, so I'll stick to more conventional solutions, thanks for the help!

**Comment by oscarbenjamin** [comment] 2023-07-20 17:32
```
 In [2]: class MySym(AtomicExpr):
    ...:     def __init__(self, name):
    ...:         self.name = name
```
It is obvious to me why this does not work but I am not surprised if it is not obvious to you. The problem is that you are using `__init__` rather than `__new__` and then allowing the arg `name` which is a string to be stored (by `Basic.__new__` in the args).

Subclasses of Basic must not define `__init__` and also must not define attributes that are not part of the args without much extra machinery. This is specific to SymPy's `Basic`.

What this shows is that you have to know something about a class to be able to subclass it: it is not enough just to walk up to any random class and presume that you can subclass it and start changing its methods. Needing to use `__new__` rather than `__init__` is a SymPy quirk but you cannot in general think that it would be okay to subclass a random class, change the `__init__` and then *not* call `super().__init__`.

Classes should only ever be subclassed if they are designed to allow unknown subclasses which means that there should be a clear documented contract for how you should subclass them and what methods to define or not define and so on. Otherwise subclassing is just monkeypatching: no one can stop you from doing it but that does not mean it is a good idea.

> because I need to get the data by reading through the `Eq`.

Again you do not "need" to do this. There is some reason why this approach makes sense to you but I am sure that there are more straight-forward ways to do this. I don't know enough about your application to say exactly what those are but the simplest and most robust solutions definitely do not involve making custom classes to put inside the expressions.

**Comment by asmeurer** [comment] 2023-07-20 23:38
I guess you are trying to do this https://docs.python.org/3/library/typing.html#user-defined-generic-types

It's not completely clear to me what exactly you gain from subclassing Generic[T]. Is it just that you get `__class_getitem__`, and it does something with mypy? 

> Regarding subclassing in general, my goal is to give some metadata to Symbol: a type, some properties, and potentially a generic type annotation.

It would help to understand just what sort of state you're wanting to add to Symbols, and how Generic[T] would (theoretically) let you do this. As far as I can tell, Generic[T] subclasses lose any typing information as soon as you instantiate them:

```py
>>> class Test(Generic[T]):
...     def __init__(self, x):
...         self.x = x
>>> Test[int](1)
<__main__.Test object at 0x108d59350>
>>> Test[list](1)
<__main__.Test object at 0x1087b5d50>
>>> type(Test[int](1))
<class '__main__.Test'>
>>> type(Test[int](1)) is type(Test[list](1))
True
```

If you want to have a bunch of separate expression *classes* you should subclass `Function`, not `Symbol` (or instantiate `Function(...)`). See https://docs.sympy.org/latest/guides/custom-functions.html.

**Comment by asmeurer** [comment] 2023-07-20 23:44
By the way, people wanting to subclass Symbol to store extra data on it comes up a lot. I do have a section in my upcoming best practices document (https://github.com/sympy/sympy/issues/24597) about some of the better alternatives for this, but I wonder if we shouldn't just make a Symbol subclass that actually just lets people do this, since subclassing Symbol and doing it correctly is so fraught and difficult to actually do correctly.

**Comment by TrakJohnson** [comment] 2023-07-21 08:37
@oscarbenjamin Sorry for wasting your time with my last message :( it was nonsense, I meant to write:

```python
class MySym(AtomicExpr):
    def __new__(cls, name, *args):
        res = super().__new__(cls, *args)
        res.name = name
        return res
````
but that's still flawed, because it considers that MySym("x") is the same as MySym("y").

> Classes should only ever be subclassed if they are designed to allow unknown subclasses which means that there should be a clear documented contract for how you should subclass them and what methods to define or not define and so on. Otherwise subclassing is just monkeypatching: no one can stop you from doing it but that does not mean it is a good idea.

Ok, I see. I had initially assumed that "if it wasn't explicitely written in the docs that it can't be subclassed then it can". But given everything that you've explained this is obviously a very wrong assumption, I'll keep that in mind :)

@asmeurer That's indeed what I was trying to do, but using generics and adding properties are separate. 

To be more clear, I had something like this before posting the issue, which only involved additional properties and changing `__new__`, and worked (seemingly) fine:
```python
class Var(Symbol):
    prefix = ""
    def __new__(cls, dim: dimension.DimType, name: str):
        full_name = ...
        return super().__new__(cls, full_name, real=True)
    # ...

class Parameter(Var):
    prefix = "PARAM"

# ... other subclasses of var
```

and then I had believed making it generic would be useful, because the end user can define [dataclasses](https://docs.python.org/3/library/dataclasses.html) like this:
```python
@dataclass
class Container:
    temperature: Var[TEMPERATURE_TYPE]
    volume: Parameter[VOLUME_TYPE]
    # ...
```
and with type annotations:
1. There is no need for a separate data structure to store the physical dimensions of each variable: `{"temperature": TEMPERATURE_TYPE, ...}`, I can parse them directly from the container class object with either `dataclasses.fields(Container)` or [`get_type_hints`](https://docs.python.org/3/library/typing.html#typing.get_type_hints)
2. mypy (not the runtime) will statically tell the user if they're instantiating the container with the wrong type of variable

However, as you noted, it doesn't actually make any difference when working with instances - it's only the annotations that are a declarative way to add more "information" to a field.

Also, regarding your comment on this coming up a lot, I initially got this idea from https://stackoverflow.com/questions/46021227/possible-to-add-descriptions-to-symbols-in-sympy.

I hope this makes sense. Even if my wording wasn't clear before, nothing exposed here is actually required, and given the feedback it's probably not a good idea either, so I'll look at `Function` or do something else. This is just the reasoning that led me to opening this issue.

**Comment by oscarbenjamin** [comment] 2023-07-21 09:24
> I wonder if we shouldn't just make a Symbol subclass that actually just lets people do this

I was thinking the same thing although I was imagining a general Expr subclass. Probably though you are right that it is symbols that most users would want to do this with and since symbols are special cased in many places a general Expr subclass might not work for many things.

Making a Symbol subclass is a bit harder though. A first attempt looks like:
```python
from typing import Hashable


class DataSymbol(Symbol):
    """
    A Symbol subclass that carries some data attached to the symbol.
    """

    __slots__ = ('_data',)

    def __new__(cls, name: str, data: Hashable, **assumptions):
        # Use __xnew__ instead of __new__ to bypass the cache. Otherwise the
        # cache would not know about data so DataSymbol('x', 1) and
        # DataSymbol('x', 2) would return the same instance (with whichever
        # data value was passed last).
        obj = super().__xnew__(cls, name, **assumptions)
        obj._data = data
        return obj

    @property
    def data(self):
        return self._data

    # This is what makes __eq__ work.
    def _hashable_content(self):
        return super()._hashable_content() + (self.data,)

    # Actually the printers should be changed rather than defining __repr__ or
    # __str__. If we want to allow DataSymbol to be subclassed in user code
    # then the printer methods should be defined to call methods on the
    # instance that can be overridden in subclasses (and this should be
    # documented and tested).
    def __repr__(self):
        clsname = self.__class__.__name__
        assumptions = self._assumptions_orig
        if not assumptions:
            return f'{clsname}({self.name}, {self.data})'
        else:
            kwargs = ', '.join(f'{k}={v}' for k, v in assumptions.items())
            return f'{clsname}({self.name}, {self.data}, {kwargs})'
```
I am certain that there are problems with this though although I can't immediately think what they are.

> I had initially assumed that "if it wasn't explicitely written in the docs that it can't be subclassed then it can". But given everything that you've explained this is obviously a very wrong assumption, I'll keep that in mind :) I do agree that it would be great if there was a warning in the docs, for newbies like me :)

Firstly I think that this is more of a general Python thing rather than a SymPy-specific thing. The fact that Python the language allows subclassing any class does not mean that any given class is *designed* to be subclassed. Rather the presumption should be that by default all classes are *not* designed to be subclassed. If there is no documentation for subclassing a class then its author most likely did not consider the idea that someone would try to subclass it and therefore did not design it with that case in mind.

The part of this that is SymPy specific is just how different SymPy's `Basic` class is compared to the way that most classes are usually written. Part of the issue is actually that classes like `Expr/Basic` *are* designed to be subclassed but that means you have to know what that design is and you have to follow its rules. The other part of the issue is that concrete `Expr` subclasses like `Symbol` are definitely *not* designed to be subclassed.

**Comment by sylee957** [comment] 2023-07-24 00:44
PEP-591 allows to add `final` to classes such that it can lint classes that are not obvious to subclass, not to be subclassed
https://peps.python.org/pep-0591/

I'm not sure if that makes some users more unhappy, 
users or even contributors shouldn't follow some anti-patterns of subclassing or overriding wrong things.

**Comment by oscarbenjamin** [comment] 2023-07-24 08:28
The original issue prevents using `Generic[T]` while subclassing `Basic` and `Basic` is intended to be subclassed. It could be fixed by calling `super().__init_subclass__()` in `Basic.__init_subclass__` as mentioned above.

**Comment by sylee957** [comment] 2023-08-19 06:41
> It could be fixed by calling super().__init_subclass__() in Basic.__init_subclass__ as mentioned above.

Although this can fix the issue, I really can't understand it step-by-step why that works

**Comment by oscarbenjamin** [comment] 2023-08-20 20:01
The reason calling `__init_subclass__` fixes this is because `Generic.__init_subclass__` will set the `__parameters__` attribute.
https://github.com/python/cpython/blob/6323bc33ff9f445a947adf4af42b8be7e44c730c/Lib/typing.py#L1068-L1103

**Comment by sylee957** [comment] 2023-08-20 20:09
I see, but the thing I had wondered is that
super() should only visit superclass of Basic, and Generic isn’t superclass of Basic. 
Maybe I have some misunderstanding how super() visits classes.

**Comment by sylee957** [comment] 2023-08-20 20:29
There is ‘cooperative inheritance’ I read.

**Comment by oscarbenjamin** [comment] 2023-08-20 20:38
> Maybe I have some misunderstanding how super() visits classes.

Probably. The full syntax for super is like:
```python
class Basic:
    def __init_subclass__(cls):
        super(Basic, cls).__init_subclass__()
```
Here `super(Basic, cls)` means "get the superclass of `Basic` in the MRO of `cls`":
```python
In [57]: from typing import TypeVar, Generic

In [58]: T = TypeVar("T")

In [59]: class A(Symbol, Generic[T]):
    ...:     pass
    ...: 

In [60]: A.mro()
Out[60]: 
[__main__.A,
 sympy.core.symbol.Symbol,
 sympy.core.expr.AtomicExpr,
 sympy.core.basic.Atom,
 sympy.core.expr.Expr,
 sympy.logic.boolalg.Boolean,
 sympy.core.basic.Basic,
 sympy.printing.defaults.Printable,
 sympy.core.evalf.EvalfMixin,
 typing.Generic,
 object]

In [61]: super(Basic, A).__init_subclass__
Out[61]: <bound method Generic.__init_subclass__ of <class '__main__.A'>>
```

> There is ‘cooperative inheritance’ I read.

Yes, and people who do multiple inheritance suggest that `super` should be used everywhere because of this.

Personally I think that multiple inheritance is usually a bad idea. The situation where it can be okay is with a mixin but the idea there is that the two parent classes do not share any methods so there is no need for `super`.

In this case we just want typing and not multiple inheritance which is understandable. I don't know whether PEP 695 solves this problem so that generics do not need to use multiple inheritance:
https://peps.python.org/pep-0695/

**Closed** 2023-08-21 19:53 UTC
