### ISSUE TITLE
PermutationGroup fails to detect contention

### ISSUE THREAD

**Issue by Pragabhava** [sympy/sympy#20388] opened 2020-11-06 14:46 UTC
Here are the steps to reproduce it:

    from sympy.combinatorics import Cycle
    from sympy.combinatorics.perm_groups import PermutationGroup

    perm_group = PermutationGroup(Cycle(2, 3)(4, 5), Cycle(1, 2, 3, 4, 5))

    [Cycle(perm) for perm in perm_group.elements]
    >>> [
            ...
            Cycle(1, 2, 3),
            ...
            Cycle(2, 5, 3),
            ...
        ]

    perm_group.contains(Permutation(Cycle(2, 5, 3)))
    >>> True

    perm_group.contains(Permutation(Cycle(1, 2, 3)))
    >>> False

**Comment by wsdookadr** [comment] 2020-11-17 19:08
Hi @Pragabhava,

## approach 1

From [the docs](https://docs.sympy.org/latest/modules/combinatorics/permutations.html#sympy.combinatorics.permutations.Cycle):

> If a larger (or smaller) range is desired use the list method and provide the desired size

This quote doesn't explicitly say what happens when the size passed is greater than the current size, [but the code does](https://github.com/sympy/sympy/blob/e61427098bedab2b6bbeb778f7910144a0ea9fd6/sympy/combinatorics/permutations.py#L1036):

>            if size > self.size:
>                rv.extend(list(range(self.size, size)))

See the example with `a1` below

## approach 2

Quote [from the docs](https://docs.sympy.org/latest/modules/combinatorics/permutations.html#sympy.combinatorics.permutations.Permutation):

> Entering a singleton in a permutation is a way to indicate the size of the permutation. The size keyword can also be used.

Using a singleton, see `a2` below

## approach 3

In the case of a3 you can use the  "size" parameter to the constructor to [explicitly mention the size to SymPy](https://github.com/sympy/sympy/blob/e61427098bedab2b6bbeb778f7910144a0ea9fd6/sympy/combinatorics/permutations.py#L831)

Code:

```python
from sympy.combinatorics import Cycle, Permutation
from sympy.combinatorics.perm_groups import PermutationGroup

perm_group = PermutationGroup(Cycle(2, 3)(4, 5), Cycle(1, 2, 3, 4, 5))

p1 =Permutation(Cycle(2, 5, 3))
p2 =Permutation(Cycle(1, 2, 3))
a1 = Permutation(Cycle(1, 2, 3).list(6))
a2 = Permutation(Cycle(1, 2, 3)(5))
a3 = Permutation(Cycle(1, 2, 3),size=6)

for p in [p1,p2,a1,a2,a3]:
    print(p)
    print(perm_group.contains(p))
```

Output:

```
(2 5 3)
True
(1 2 3)
False
(5)(1 2 3)
True
(5)(1 2 3)
True
(5)(1 2 3)
True
```

**Comment by wsdookadr** [comment] 2020-11-23 07:09
@oscarbenjamin can this issue be closed as it's not a bug? Thanks

**Comment by oscarbenjamin** [comment] 2020-11-23 12:54
Is it worth adding anything to the docs?

**Comment by Pragabhava** [comment] 2020-11-24 04:31
Thank you very much for the reply.

I'm not sure what etiquette is to be followed. Should I close the issue? Feel free to close if it's the proper way.

**Comment by wsdookadr** [comment] 2020-11-24 07:15
> Is it worth adding anything to the docs?

Ok, just made the PR #20480 for this

**Closed** 2020-12-16 00:03 UTC
Labels: combinatorics
