### ISSUE TITLE
simplify of cosh(1/2) returns float

### ISSUE THREAD

**Issue by ogauthe** [sympy/sympy#21594] opened 2021-06-10 10:27 UTC
Hello,

`simplify` fails to recognize `cosh(1/2)` when given in `exp` form and returns a float, which is clearly a wrong answer. I tried several 
other fractions, only exp(1/2) + exp(-1/2) seems to suffer the issue.

```
In [1]: import sympy as sp

In [2]: sp.simplify(2 * sp.cosh(sp.Rational(1,2)))
Out[2]: 2*cosh(1/2)

In [3]: sp.simplify(sp.exp(sp.Rational(1,3)) + sp.exp(sp.Rational(-1,3)))
Out[3]: 2*cosh(1/3)

In [4]: sp.simplify(sp.exp(sp.Rational(1,2)) + sp.exp(sp.Rational(-1,2)))
Out[4]: 2.25525193041276

In [5]: sp.__version__
Out[5]: '1.8'
```

**Comment by oscarbenjamin** [comment] 2021-06-10 11:37
This is caused by mixing plain Python ints along with sympy expressions. Somewhere an `int/int` division leads to `float`. The diff below fixes the issue:
```diff
diff --git a/sympy/simplify/trigsimp.py b/sympy/simplify/trigsimp.py
index da40be8521..ca43a63b0b 100644
--- a/sympy/simplify/trigsimp.py
+++ b/sympy/simplify/trigsimp.py
@@ -550,13 +550,13 @@ def f(rv):
         rvd = rv.as_powers_dict()
         newd = rvd.copy()
 
-        def signlog(expr, sign=1):
+        def signlog(expr, sign=S.One):
             if expr is S.Exp1:
-                return sign, 1
+                return sign, S.One
             elif isinstance(expr, exp) or (expr.is_Pow and expr.base == S.Exp1):
                 return sign, expr.exp
-            elif sign == 1:
-                return signlog(-expr, sign=-1)
+            elif sign is S.One:
+                return signlog(-expr, sign=-S.One)
             else:
                 return None, None
 
```
Marking as easy to fix if someone wants to apply the diff along with a test.

**Comment by smichr** [comment] 2021-06-10 12:13
It is sufficient to change only the first `return sign, 1` to `return sign, S.One` since it is the returned value that is causing the issue. That return value is used to recompute an expression here, for example:
```python
                sign, x = signlog(k.args[1]/c)
                if not x:
                    continue
                m = rvd[k]
                newd[k] -= m
                if ee == -x*m/2:  <-----------------
                    # sinh and cosh
                    newd[S.Exp1] -= ee
                    ee = 0
                    if sign == 1:
                        newd[2*c*cosh(x/2)] += m  <-----------------
                    else:
                        newd[-2*c*sinh(x/2)] += m  <-----------------
```
so if it is S.One then a float will not be created.

**Comment by mostlyaman** [comment] 2021-06-10 12:41
Thanks for explaining the fix! May I work on this issue?

**Comment by oscarbenjamin** [comment] 2021-06-10 14:11
> It is sufficient to change only the first `return sign, 1` to `return sign, S.One` since it is the returned value that is causing the issue.

Since the calling code expects to treat the result as Expr it seems safer to me to make the function always return Expr to avoid bugs like this in future if the code were changed at all.

**Comment by smichr** [comment] 2021-06-10 14:36
> make the function always return Expr

I see, now, that the actual value of `sign` is being returned in the first case. Since that is always multiplied by something (that is a SymPy object if `sign, S.One` is returns) then it gets auto-cast to `+/-S.One`...that's why the minimal change is sufficient. But what we don't forsee today could become a corner-case tomorrow, and @oscarbenjamin has the best solution.

That `tanh` is not recognized is a consequence of not working with numerator and denominator separately. It is a separate issue.

**Closed** 2021-06-11 18:29 UTC
Labels: Easy to Fix, simplify
