### ISSUE TITLE
A non-terminating limit

### ISSUE THREAD

**Issue by EmmanuelCharpentier** [sympy/sympy#24276] opened 2022-11-18 19:12 UTC
Inspired by [this `ask.sagemath.org` question](https://ask.sagemath.org/question/64794/inconsistentincorrect-value-of-limit-involving-tan-and-tanh/) : 

```python
>>> from sympy import *
>>> x=symbols("x")
>>> f=Lambda((x), log(tan(pi/2*tanh(x))).diff(x)) ; f(x)
pi*(1 - tanh(x)**2)*(tan(pi*tanh(x)/2)**2 + 1)/(2*tan(pi*tanh(x)/2))
>>> # f(x).limit(x, oo) : doesn't return after > 5 minutes
>>> # f(x).simplify().limit(x, oo) : doesn't return after > 5 minutes
>>> # f(x).rewrite(sin).limit(x, oo) : doesn't return after > 5 minutes ; BUT !
>>> f(x).rewrite(sin).simplify().limit(x, oo)
2
```

This last result is obtained in 12-15 seconds... Comments on the motivating post hint that this result is correct.

HTH,

**Comment by oscarbenjamin** [comment] 2022-11-18 20:38
Thanks for the report.

What version of SymPy are you using?

I just tried these with SymPy master and all returned within a few seconds:
```python
In [1]: >>> from sympy import *
   ...: >>> x=symbols("x")
   ...: >>> f=Lambda((x), log(tan(pi/2*tanh(x))).diff(x)) ; f(x)
Out[1]: 
  ⎛        2   ⎞ ⎛   2⎛π⋅tanh(x)⎞    ⎞
π⋅⎝1 - tanh (x)⎠⋅⎜tan ⎜─────────⎟ + 1⎟
                 ⎝    ⎝    2    ⎠    ⎠
──────────────────────────────────────
                ⎛π⋅tanh(x)⎞           
           2⋅tan⎜─────────⎟           
                ⎝    2    ⎠           

In [2]: %time f(x).limit(x, oo)
CPU times: user 5.47 s, sys: 8 ms, total: 5.48 s
Wall time: 5.48 s
Out[2]: 2

In [3]: %time f(x).simplify().limit(x, oo)
CPU times: user 820 ms, sys: 4 ms, total: 824 ms
Wall time: 823 ms
Out[3]: 2

In [4]: %time f(x).rewrite(sin).limit(x, oo)
CPU times: user 5.64 s, sys: 4 ms, total: 5.65 s
Wall time: 5.81 s
Out[4]: 2

In [5]: %time f(x).rewrite(sin).simplify().limit(x, oo)
CPU times: user 2.67 s, sys: 4 ms, total: 2.68 s
Wall time: 2.68 s
Out[5]: 2
```
I don't have a particularly powerful computer here but I do have gmpy2 installed which could potentially affect the timings.

**Comment by EmmanuelCharpentier** [comment] 2022-11-18 22:57
Ipython session transcript (with comments)

```python
charpent@zen-book-flip:~$ ipython
Python 3.10.8 (main, Nov  4 2022, 09:21:25) [GCC 12.2.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.6.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from sympy import *

In [2]: x=symbols("x")

In [3]: f=Lambda((x), log(tan(pi/2*tanh(x))).diff(x)) ; f(x)
Out[3]: pi*(1 - tanh(x)**2)*(tan(pi*tanh(x)/2)**2 + 1)/(2*tan(pi*tanh(x)/2))

In [4]: %time f(x).limit(x, oo)
# couple minutes wait, then
^C^C
KeyboardInterrupt


In [5]: %time f(x).rewrite(sin).limit(x, oo)
## ditto
^C^C
KeyboardInterrupt


In [6]: %time f(x).simplify().limit(x, oo)
CPU times: user 1.71 s, sys: 1 µs, total: 1.71 s
Wall time: 1.7 s
Out[6]: Limit(pi/(sin(pi*tanh(x))*cosh(x)**2), x, oo, dir='-')
## The result is *different*. gmpy2 *may* have more effect than "just speed"...

In [7]: %time f(x).rewrite(sin).simplify().limit(x, oo)
CPU times: user 19.3 s, sys: 4 ms, total: 19.3 s
Wall time: 19.3 s
Out[7]: 2
## Identical but damn slower...

In [8]: quit()
```

And this happens on : 
```
charpent@zen-book-flip:~$ pip3 list | grep sympy
sympy                             1.11.1
```

HTH,

**Comment by oscarbenjamin** [comment] 2022-11-18 23:25
I've bisected the change since 1.11.1 to current master to this 00d793f04386b516f823f3e55fc27e60ce33184b from gh-23844

**Comment by oscarbenjamin** [comment] 2022-11-18 23:26
I think this is fixed on current master.

**Comment by EmmanuelCharpentier** [comment] 2022-11-19 00:03
BTW, could you check on this incoming master one of my favourite gripes ? 

```python
In [1]: from sympy import *

In [2]: x, a, b = symbols("x, a, b")

In [3]: dbeta=Lambda((x, a, b),x**(a-1)*(1-x)**(b-1)/beta(a,b))

In [4]: dbeta(x, a+1, b+1).integrate((x, 0, 1))
Out[4]: gamma(a + 1)*hyper((-b, a + 1), (a + 2,), 1)/(beta(a + 1, b + 1)*gamma(a + 2))

In [5]: dbeta(x, a+1, b+1).integrate((x, 0, 1)).simplify()
Out[5]: 1
# Correct

In [6]: dbeta(x, a, b).integrate((x, 0, 1)).simplify()
^C^C # "never" returns
KeyboardInterrupt
```

Any better ?

**Comment by oscarbenjamin** [comment] 2022-11-19 01:32
This is what I get. It takes one minute:
```python
In [1]: In [1]: from sympy import *
   ...: 
   ...: In [2]: x, a, b = symbols("x, a, b")
   ...: 
   ...: In [3]: dbeta=Lambda((x, a, b),x**(a-1)*(1-x)**(b-1)/beta(a,b))
   ...: 
   ...: In [4]: dbeta(x, a+1, b+1).integrate((x, 0, 1))
Out[1]: 
          ┌─  ⎛-b, a + 1 │  ⎞
Γ(a + 1)⋅ ├─  ⎜          │ 1⎟
         2╵ 1 ⎝  a + 2   │  ⎠
─────────────────────────────
   Β(a + 1, b + 1)⋅Γ(a + 2)  

In [2]: %time dbeta(x, a, b).integrate((x, 0, 1)).simplify()
CPU times: user 54.4 s, sys: 16 ms, total: 54.5 s
Wall time: 54.5 s
Out[2]: 
   a                                                 
- 0 ⋅Γ(a + b + 1) + a⋅Γ(b)⋅Γ(a + 1) + b⋅Γ(b)⋅Γ(a + 1)
─────────────────────────────────────────────────────
                (a + b)⋅Γ(b)⋅Γ(a + 1) 
```
I don't know if that's correct...

**Comment by EmmanuelCharpentier** [comment] 2022-11-19 08:12
> I don't know if that's correct...

Both simplify to 1 : the second simplification can be done by Sympy 1.11.1 : 

```python
In [10]: (gamma(a+1)*hyper([-b, a+1], [a+2], 1)/(beta(a+1, b+1)*gamma(a+2))).sim
    ...: plify()
Out[10]: 1
```

the first one cannot (at least no longer...) : 

```python
In [14]: ((-(0**a)*gamma(a+b+1)+a*gamma(b)*gamma(a+1)+b*gamma(b)*gamma(a+1))/((a
    ...: +b)*gamma(b)*gamma(a+1))).simplify()
Out[14]: 
   a                                                 
- 0 ⋅Γ(a + b + 1) + a⋅Γ(b)⋅Γ(a + 1) + b⋅Γ(b)⋅Γ(a + 1)
─────────────────────────────────────────────────────
                (a + b)⋅Γ(b)⋅Γ(a + 1)                
```

but can be done by Sage's `simplify_full()` : 

```python
sage: ((-(0^a)*gamma(a+b+1)+a*gamma(b)*gamma(a+1)+b*gamma(b)*gamma(a+1))/((a+b)*
....: gamma(b)*gamma(a+1))).simplify_full()
1
```



 The crux of the matter may be : 

```python
In [12]: (0**a).simplify()
Out[12]: 
 a
0 
```

whereas : 

```python
sage: (0^a).simplify()
0
```

HTH,

**Comment by oscarbenjamin** [comment] 2022-11-19 11:32
> The crux of the matter may be :
> 
> ```python
> In [12]: (0**a).simplify()
> Out[12]: 
>  a
> 0 
> ```
> 
> whereas :
> 
> ```python
> sage: (0^a).simplify()
> 0
> ```

With no assumptions on `a` that is not a valid simplification:
```python
In [1]: a = symbols('a', positive=True)

In [2]: 0**a
Out[2]: 0
```

**Comment by EmmanuelCharpentier** [comment] 2022-11-19 17:09
> With no assumptions on a that is not a valid simplification:

You're right...

**Comment by EmmanuelCharpentier** [comment] 2022-11-19 17:15
The first simplification *can* be done by 1.11.1 with the "right" assumptions : 

```python
In [16]: a, b=symbols("a, b", positive=True)

In [17]: ((-(0**a)*gamma(a+b+1)+a*gamma(b)*gamma(a+1)+b*gamma(b)*gamma(a+1))/((a
    ...: +b)*gamma(b)*gamma(a+1))).simplify()
Out[17]: 1
```

**Comment by oscarbenjamin** [comment] 2022-11-19 18:08
I've lost track with all of the different examples above. Is there something to be fixed in current (i.e. master) SymPy here?

**Comment by EmmanuelCharpentier** [comment] 2022-11-19 18:42
> I've lost track with all of the different examples above. Is there something to be fixed in current (i.e. master) SymPy here?

You tell me ;-)... Given : 

```python
In [10]: from sympy import *

In [11]: x=symbols("x")

In [12]: a, b=symbols("a, b", positive=True)

In [13]: dbeta=Lambda((x, a, b),x**(a-1)*(1-x)**(b-1)/beta(a,b))
```

does `master` get `1` when asked : 

```python
In [14]: dbeta(x, a+1, b+1).integrate((x, 0, 1)).simplify()
Out[14]: 1 ## Already works in 1.11.1. Does master simplify its integration result ?
In [15]: dbeta(x, a, b).integrate((x, 0, 1)).simplify()
## in 1.11.1, the integration never returns, so the simplification of what you got with master hasn't been tested.
```
?

HTH,

**Comment by oscarbenjamin** [comment] 2022-11-19 19:09
So with current master we have:
```python
In [1]: from sympy import *

In [2]: x=symbols("x")

In [3]: a, b=symbols("a, b", positive=True)

In [4]: dbeta=Lambda((x, a, b),x**(a-1)*(1-x)**(b-1)/beta(a,b))

In [5]: %time dbeta(x, a+1, b+1).integrate((x, 0, 1)).simplify()
CPU times: user 5.11 s, sys: 4 ms, total: 5.12 s
Wall time: 5.12 s
Out[5]: 1

In [6]: %time dbeta(x, a, b).integrate((x, 0, 1)).simplify()
CPU times: user 44.4 s, sys: 28 ms, total: 44.4 s
Wall time: 44.4 s
Out[6]: 1
```
Both of these are slow which is something that could be improved but both do give `1`.

**Comment by EmmanuelCharpentier** [comment] 2022-11-19 19:34
>Both of these are slow which is something that could be improved 

I have no opinion wrt speed (= performance), but

> but both do give 1.

getting 1 demonstrate competence. Which we didn't have previously. Therefore, a net gain.

BTW : 

  - Are such reports useful ? If so, I may report such quirks as I find them...

  - I have also from time to time numerical issues (e. g. ill(conditionned expressions). Are they of interest ?

Sincerely.

**Comment by oscarbenjamin** [comment] 2022-11-20 11:00
> * Are such reports useful ?

Yes absolutely. If the examples from the OP weren't already fixed then we would want to fix them. Even though they are already fixed on master we would want to add those examples as regression tests anyway: if they previously didn't work then they are probably a good thing to test for the future.

What I would say though is that it's better to keep each GitHub issue focused on a single topic. Here the original examples in the OP are a good case for an issue. Since those are fixed what I would say is that this issue could be closed when tests are added for those cases and then I could add the "easy to fix" label which is an invitation for a new contributor to work on this issue. Adding in different examples afterwards and then our subsequent dialogue complicates the issue for anyone reading it. That makes it harder for someone reading this page to know exactly what it is that should be fixed or what regression tests to add.

> * I have also from time to time numerical issues (e. g. ill(conditionned expressions). Are they of interest ?

Probably. I'm not sure exactly what you mean but I would say just  open an issue with it. If you mean that for example `evalf` gives incorrect answers in some  cases then that's definitely something to be fixed.

**Comment by oscarbenjamin** [comment] 2022-11-20 11:02
I am marking this issue as easy to fix. What should be done to close this is to add tests for the 4 limits shown in the first post of this issue. The problem with those limits was fixed in #23844 but it doesn't look as though any regression tests for something similar to those 4 limits were added in that pull request.

**Comment by asmeurer** [comment] 2022-11-21 08:56
CC @anutosh491

**Comment by victorchrollo14** [comment] 2022-11-28 15:52
`def test_issue_24276():
    f = Lambda((x), log(tan(pi/2*tanh(x))).diff(x)) ; f(x)
    assert f(x).limit(x, oo) == 2
    assert f(x).simplify().limit(x, oo) == 2
    assert f(x).rewrite(sin).limit(x, oo) == 2
    assert f(x).rewrite(sin).simplify().limit(x, oo) == 2`

Hi, I'm Victor, new to sympy. 
Is the above code correct or should I be implementing something completely different.

**Comment by oscarbenjamin** [comment] 2022-11-28 16:02
Yes, that looks reasonable.

**Comment by victorchrollo14** [comment] 2022-11-29 12:46
So, Can I commit it and create a pull request.

**Comment by oscarbenjamin** [comment] 2022-11-29 13:59
Yes

**Comment by oscarbenjamin** [comment] 2022-12-06 13:52
Another example from the SAGE mailing list that was also fixed by the same PR:
```
In [1]: %time log(tan(pi/2*tanh(x))).diff(x).limit(x, oo)
CPU times: user 5.76 s, sys: 12 ms, total: 5.78 s
Wall time: 5.78 s
Out[1]: 2
```
https://groups.google.com/g/sage-support/c/3mWL0my0IQg

**Comment by oscarbenjamin** [comment] 2022-12-06 13:54
I should pay more attention to what I'm doing: that's exactly the same example.

**Closed** 2022-12-11 16:58 UTC
Labels: Easy to Fix, Performance, limits
