### ISSUE TITLE
pickle representation randomly changes

### ISSUE THREAD

**Issue by cknoll** [sympy/sympy#14835] opened 2018-06-24 19:49 UTC
I aim for reproducible pickle representations of sympy-objects (see #14808 for motivation).

I found out that sometimes `pickle.dump(expr)` is reproducible and sometimes not. Consider the following code

    import sympy as sp, hashlib, pickle
    import sys
    
    x1 = sp.symbols("x1")
    e1 =  sp.exp(x1)
    
    if len(sys.argv) > 1:
        sp.sin(x1)  # has a side-effect on the pickle representation
    
    print(hashlib.sha256(pickle.dumps(e1)).hexdigest())

if this script is called without arguments the hash and thus the pickle representation is always the same.
If it is called with arguments (i.e., `sp.sin(x1)` is called) then on 100 runs I get 25 different hashes (some more often then others).

Is this intended?
If not: How could it be fixed?

If intended or fix too complicated: Is there a different manner to get a fast and reproducible hash from (possibly very large) sympy expressions?

**Comment by cknoll** [comment] 2018-06-24 19:54
Interesting: If I run `export PYTHONHASHSEED=0`([background](https://jimmycallin.github.io/2016/01/03/make-your-python3-code-reproducible/)) before my evaluation script 

    from plumbum import local
    from collections import Counter
    
    py = local["python3"]
    
    N = 100
    
    c1 = Counter()
    c2 = Counter()
    
    for i in range(N):
        print(i)
        r2 = py["sympy_pickle_question.py", "1"]()[:5]
        c2.update([r2])
    
    print(c2)

 then I still get two different pickle representations. So pythons internal hash()-randomization has to do with this but does not seem to be the only reason.

**Comment by asmeurer** [comment] 2018-06-24 22:32
This is just how pickle dumps dictionaries. 

```py
>>> # Session 1
>>> import pickle
>>> pickle.dumps({'key1': 1, 'key2': 2})
b'\x80\x03}q\x00(X\x04\x00\x00\x00key2q\x01K\x02X\x04\x00\x00\x00key1q\x02K\x01u.'
```

```py
>>> # Session 2
>>> import pickle
>>> pickle.dumps({'key1': 1, 'key2': 2})
b'\x80\x03}q\x00(X\x04\x00\x00\x00key1q\x01K\x01X\x04\x00\x00\x00key2q\x02K\x02u.'
```


If you use Python 3.6 or greater, you might get a more reproducible representation due to the consistent ordering of dictionaries, but even then, the order that the dictionary representation is created could depend on what you do with the expression (the dictionary here is the assumptions dictionary, which is built on-demand as the assumptions are requested). 

See also the discussion at  #14808. I'm closing this as won't fix, because this is just how pickle works. I think what you are trying to do with pickle (hashing the pickle representation) just isn't going to work. I would try to find a better way to hash the expression instead, preferably using something like `expr._hashable_content()` which is explicitly designed to be hashed.

**Closed by asmeurer** 2018-06-24 22:32 UTC

**Comment by cknoll** [comment] 2018-06-27 19:52
Just if anyone has similar problem: for my purpose it helped to convert every (writeable) dict-attribute of the involved objects (Expression and its Symbols) to `OrderedDict`. This (for me) results in reproducible pickle-dumps and thus in reproducible hashes. For Matrices using  `ImmutableDenseMatrix` was also necessary.

This workarround was inspired by @asmeurer's hint that with Python 3.6 dict ordering is consistent. But I want to support older versions too.
