### ISSUE TITLE
Error in factor method

### ISSUE THREAD

**Issue by piedenis** [sympy/sympy#14550] opened 2018-03-24 12:16 UTC
I'm using SymPy 0.7.6.1 on Python 3.5.1. I found out that the `factor` method returns wrong results on several specific expressions that contain floating-point numbers. Here is a session sample:
```
>>> p = sympy.Symbol('p')
>>> f = (p-1)**4 - 4*p*(p-1)**3 + 6*p**2*(p-1)**2 - 4*p**3*(p-1) + p**4
>>> f.factor()
1
>>> (f/6).factor()
1/6
>>> (f/6.0).factor()
1.00000000000000
```
The first two results are correct ; the last one is (consequently) wrong: it should be `0.166666666666667`.
Note that `(f/6.0)` builds the right expression and note also that the `simplify` method works correctly:
```
>>> (f/6.0).simplify()
0.166666666666667
```
Even stranger, you can easily check that the bug occurs only for specific divisors (`6.0` in the case shown above), e.g.
- the bug _occurs_ for divisors: `3.0`, `5.0`, `6.0`, `10.0`, `11.0`, `12.0`, `15.0`, `17.0`, ...
- the bug _does not occur_ for divisors:  `2.0`, `4.0`, `7.0`, `8.0`, `9.0`, `13.0`, `14.0`, `16.0`, ...

I don't see any simple pattern however.

**Comment by jksuom** [comment] 2018-03-24 13:19
Duplicate of https://github.com/sympy/sympy/issues/13149. Fixed in https://github.com/sympy/sympy/pull/13198.

**Comment by piedenis** [comment] 2018-03-24 13:30
OK, great! Sorry if I missed that one.

**Comment by jksuom** [comment] 2018-03-24 13:35
The bug appears when the polynomial with floating point coefficients does not simplify to a constant because of rounding errors. Those errors depend on the divisor in a fairly random way.

**Comment by oscarbenjamin** [comment] 2019-02-26 01:19
I get a different result now. These are the same:
```julia
In [10]: import sympy                                                                                                             

In [11]: p = sympy.Symbol('p')                                                                                                    

In [12]: f = (p-1)**4 - 4*p*(p-1)**3 + 6*p**2*(p-1)**2 - 4*p**3*(p-1) + p**4                                                      

In [13]: f.factor()                                                                                                               
Out[13]: 1

In [14]: (f/6).factor()                                                                                                           
Out[14]: 1/6
```
This one is different:
```
In [15]: (f/6.0).factor()                                                                                                         
Out[15]: 
                  ⎛                      3      ⎞
0.166666666666667⋅⎝6.66133814775094e-16⋅p  + 1.0⎠

**Comment by piedenis** [comment] 2019-02-26 18:47
@oscarbenjamin: I interpret this last result as a rounding-error due to floating-point number representation. I'm not a Sympy developer but I presume such oddity cannot be avoided. From my point of view, the result is acceptable. Sympy offers rationals (e.g. `f/6` ) to avoid such annoying phenomenon.

**Comment by oscarbenjamin** [comment] 2019-02-26 22:02
@piedenis so should we close this?

**Comment by piedenis** [comment] 2019-02-26 22:20
@oscarbenjamin: Yes, I think so. I'll do that if it's fine for you.

**Comment by oscarbenjamin** [comment] 2019-02-26 22:23
Yeah it's fine. Closing. Thanks for the report!

**Closed by oscarbenjamin** 2019-02-26 22:23 UTC
Labels: polys
