### ISSUE TITLE
solveset fails with a solvable Abs

### ISSUE THREAD

**Issue by hargup** [sympy/sympy#10023] opened 2015-10-22 19:03 UTC
``` python
In [9]: solveset(-1 + 1/Abs(x - 1), x, domain=S.Reals)
Out[9]: ConditionSet(x, Eq((-Abs(x - 1) + 1)/Abs(x - 1), 0), (-oo, oo))
```

The answer should be `{0, 2}`.

ping @aktech

**Comment by smichr** [comment] 2015-10-23 03:39
#10009 fixes the result from solve

```python
>>> solve(-1 + 1/Abs(x - 1), x)  # in master the result is [2]
[0, 2]
```

**Comment by smichr** [comment] 2015-10-23 03:40
(it does not fix the solveset result, however)

**Comment by smichr** [comment] 2015-10-23 17:40
`_solve_abs` should consider only working with the numerator of the expression it is given. If it does so, then the correct solution for the OP expression is obtained:

```python
diff --git a/sympy/solvers/solveset.py b/sympy/solvers/solveset.py
index ddc8a54..207698a 100644
--- a/sympy/solvers/solveset.py
+++ b/sympy/solvers/solveset.py
@@ -698,7 +698,7 @@ def _solve_abs(f, symbol):
     from sympy.solvers.inequalities import solve_univariate_inequality
     assert f.has(Abs)
     p, q, r = Wild('p'), Wild('q'), Wild('r')
-    pattern_match = f.match(p*Abs(q) + r)
+    pattern_match = f.as_numer_denom()[0].match(p*Abs(q) + r)
     if not pattern_match[p].is_zero:
         f_p, f_q, f_r = pattern_match[p], pattern_match[q], pattern_match[r]
         q_pos_cond = solve_univariate_inequality(f_q >= 0, symbol,
```

```
>>> solveset(-1 + abs(1/(x - 1)), x,domain=S.Reals)
{0, 2}
```

**Comment by hargup** [comment] 2015-10-26 17:05
Ignoring the denominator can be dangerous for cases in which it attains zero value, #10042 attempts to fix that but it leads to infinite recursion in another test case.

**Comment by smichr** [comment] 2015-10-27 15:36
In what case is there infinite recursion? It looked like all tests passed so I committed it.

**Comment by smichr** [comment] 2015-10-31 21:41
I have a fix for this in my 9451 branch but other commits are in process. If I can separate out the changes that fix this I will do so.

**Comment by hargup** [comment] 2015-10-31 21:49
> If I can separate out the changes that fix this I will do so.

That'll be great, thanks!

**Comment by smichr** [comment] 2015-10-31 23:51
I took out the irrelevant parts but still have several commits that depend on each other at #10089. Since you worked on the g/h modification, perhaps you could take a look at the related commit at the PR.

**Comment by ishanaj** [comment] 2018-01-28 10:46
`solveset` currently produces the correct result
```
>>> solveset(-1 + 1/Abs(x - 1), x, domain=S.Reals)
{0, 2}
```
I think the issue is resolved and should be closed

**Comment by jondo** [comment] 2018-01-28 10:51
@ishanaj, I can confirm this on current master (and Python 2.7.12-64-bit).

**Comment by oscarbenjamin** [comment] 2019-03-20 23:06
Unless new examples of the problem can be found this issue should be closed.

**Closed** 2019-04-26 08:36 UTC
Labels: Could Close, functions.elementary.piecewise, solvers.solveset
