### ISSUE TITLE
Benchmarks builds are failing on CI

### ISSUE THREAD

**Issue by ThePauliPrinciple** [sympy/sympy#22459] opened 2021-11-10 17:46 UTC
Is there any known issue that can cause this? Considering this is also happening in a PR not from me, I don't think this is related to the PRs directly.

https://github.com/sympy/sympy/pull/22209
https://github.com/sympy/sympy/pull/22458
https://github.com/sympy/sympy/pull/22456
https://github.com/sympy/sympy/pull/22449
https://github.com/sympy/sympy/pull/22461
https://github.com/sympy/sympy/pull/22463
https://github.com/sympy/sympy/pull/22464
https://github.com/sympy/sympy/pull/22390

```
Run asv machine --yes --config asv.conf.actions.json
  asv machine --yes --config asv.conf.actions.json
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.9.8/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.8/x64/lib
· Config file /home/runner/work/sympy/sympy/asv.conf.json not found.
Error: Process completed with exit code 1.
```

**Comment by ThePauliPrinciple** [comment] 2021-11-10 18:41
For me, the current master also seems to fail these tests: https://github.com/ThePauliPrinciple/sympy/actions/runs/1445454106

**Comment by anutosh491** [comment] 2021-11-11 03:48
My Pr failed due to the same reason couple of hours back ! I've never experienced this error before . Offcourse all other tests pass

**Comment by oscargus** [comment] 2021-11-11 17:41
Something must have changed elsewhere. The config file `asv.conf.actions.json` is in the repo, but for some reason it now tries to open `asv.conf.json`...

**Comment by asmeurer** [comment] 2021-11-13 00:15
Pull requests should still be mergeable as the benchmarks build isn't required to pass for merging. However, we still need to figure this out as it makes it impossible to see at a glance if the tests are failing since every build has an ❌.

**Comment by asmeurer** [comment] 2021-11-13 00:18
The same build is working on Travis https://travis-ci.org/github/sympy/sympy/jobs/774762456#L325. This is what it used to look like for GitHub Actions when it was working https://github.com/sympy/sympy/runs/4157720998?check_suite_focus=true#step:9:1

**Comment by asmeurer** [comment] 2021-11-13 00:37
The first build it failed is https://github.com/sympy/sympy/runs/4173047399?check_suite_focus=true. The most recent build that passed is https://github.com/sympy/sympy/runs/4157720998?check_suite_focus=true. The only difference I see is that the Python version changed from 3.9.7 to 3.9.8. 

Looking at the [changelog for 3.9.8](https://docs.python.org/release/3.9.8/whatsnew/changelog.html) and the [asv sources](https://github.com/airspeed-velocity/asv/blob/9d5af5713357ccea00a518758fae6822cc69f539/asv/commands/machine.py) I believe this is caused by this issue https://bugs.python.org/issue45235. I haven't actually confirmed it, but it seems very related. `--config` is added to `asv machine` as a subparser option, and the behavior we see is comes from it being the default value instead of the provided value. It seems like this won't get fixed until 3.9.10 gets released in December. 

I think we can work around this by just renaming the file to asv.conf.json as it expects. Travis is still on 3.9.1 so it will only start failing if they update their Python before 3.9.10 is released.

**Comment by asmeurer** [comment] 2021-11-13 00:42
I have this workaround implemented at https://github.com/sympy/sympy/pull/22481.

**Closed** 2021-11-13 02:13 UTC

**Comment by hanspi42** [comment] 2021-11-26 15:41
The problem has returned, see https://github.com/sympy/sympy/runs/4327728192?check_suite_focus=true
