### ISSUE TITLE
simplify() rounds a numerical coefficient (indeed very close to unity) to 1

### ISSUE THREAD

**Issue by boffi** [sympy/sympy#9630] opened 2015-07-08 10:01 UTC
I have the following expression (it is the eigenfunction of a Euler beam)

```
from sympy import *
x, L = symbols('x L')
psi = -0.999999972295856*sin(13.3579685223169*x/L) + 1.0*cos(13.3579685223169*x/L) + 0.999999972295856*sinh(13.3579685223169*x/L) - 1.0*cosh(13.3579685223169*x/L)
```

if I `simplify` the expression above I have

```
print simplify(psi)
1.0*sqrt(2)*sin(pi/4 - 13.3579685223169*x/L) + 1.0*sinh(13.3579685223169*x/L) - 1.0*cosh(13.3579685223169*x/L)
```

and it seems that 0.999999972295856 was _simplified_ to 1. As `simplify`'s doc string has no wording to this respect it could be a bug either in simplify or in its doc string.

**Comment by smichr** [comment] 2015-07-16 04:02
perhaps a duplicate of #6349

**Comment by PoldoSbaffini** [comment] 2015-07-23 09:38
In my understanding, #6349's issue is that a high precision float is truncated to the standard 15 digits of precision, here I have a standard precision float, 0.999999972295856, that is coerced to 1. 
So no, imo it doesn't seem a duplicate of #6349

**Closed** 2017-08-26 22:09 UTC
