### ISSUE TITLE
Solving exponential equation using `solve` runs for minutes until memory runs out

### ISSUE THREAD

**Issue by iwoeix** [sympy/sympy#26832] opened 2024-07-19 02:53 UTC
Here's the code and error message:
```
Python 3.12.4 (tags/v3.12.4:8e8a4ba, Jun  6 2024, 19:30:16) [MSC v.1940 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from sympy import *
>>> x = var('x', real=True)
>>> solve(2**x+x-5)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\[HIDDEN]\AppData\Local\Programs\Python\Python312\Lib\site-packages\sympy\solvers\solvers.py", line 1170, in solve
    solution = _solve(f[0], *symbols, **flags)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\[HIDDEN]\AppData\Local\Programs\Python\Python312\Lib\site-packages\sympy\solvers\solvers.py", line 1734, in _solve
    result = [{k: d[k].simplify() for k in d} for d in result]
                  ^^^^^^^^^^^^^^^
  File "C:\Users\[HIDDEN]\AppData\Local\Programs\Python\Python312\Lib\site-packages\sympy\core\basic.py", line 1936, in simplify
    return simplify(self, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\[HIDDEN]\AppData\Local\Programs\Python\Python312\Lib\site-packages\sympy\simplify\simplify.py", line 615, in simplify
    expr = expr.replace(
           ^^^^^^^^^^^^^
  File "C:\Users\[HIDDEN]\AppData\Local\Programs\Python\Python312\Lib\site-packages\sympy\core\basic.py", line 1749, in replace
    rv = walk(self, rec_replace)
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\[HIDDEN]\AppData\Local\Programs\Python\Python312\Lib\site-packages\sympy\core\basic.py", line 1724, in walk
    newargs = tuple([walk(a, F) for a in args])
                     ^^^^^^^^^^
  File "C:\Users\[HIDDEN]\AppData\Local\Programs\Python\Python312\Lib\site-packages\sympy\core\basic.py", line 1724, in walk
    newargs = tuple([walk(a, F) for a in args])
                     ^^^^^^^^^^
  File "C:\Users\[HIDDEN]\AppData\Local\Programs\Python\Python312\Lib\site-packages\sympy\core\basic.py", line 1734, in walk
    rv = F(rv)
         ^^^^^
  File "C:\Users\[HIDDEN]\AppData\Local\Programs\Python\Python312\Lib\site-packages\sympy\core\basic.py", line 1742, in rec_replace
    v = _value(expr, result)
        ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\[HIDDEN]\AppData\Local\Programs\Python\Python312\Lib\site-packages\sympy\core\basic.py", line 1708, in <lambda>
    _value = lambda expr, result: value(expr)
                                  ^^^^^^^^^^^
  File "C:\Users\[HIDDEN]\AppData\Local\Programs\Python\Python312\Lib\site-packages\sympy\simplify\simplify.py", line 623, in <lambda>
    lambda x: x.func(*[simplify(i, **kwargs) for i in x.args]),
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\[HIDDEN]\AppData\Local\Programs\Python\Python312\Lib\site-packages\sympy\core\cache.py", line 72, in wrapper
    retval = cfunc(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\[HIDDEN]\AppData\Local\Programs\Python\Python312\Lib\site-packages\sympy\core\function.py", line 466, in __new__
    result = super().__new__(cls, *args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\[HIDDEN]\AppData\Local\Programs\Python\Python312\Lib\site-packages\sympy\core\cache.py", line 72, in wrapper
    retval = cfunc(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\[HIDDEN]\AppData\Local\Programs\Python\Python312\Lib\site-packages\sympy\core\function.py", line 307, in __new__
    evaluated = cls.eval(*args)
                ^^^^^^^^^^^^^^^
  File "C:\Users\[HIDDEN]\AppData\Local\Programs\Python\Python312\Lib\site-packages\sympy\functions\elementary\exponential.py", line 1175, in eval
    result = x.match(w**(w+1)*log(w))
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\[HIDDEN]\AppData\Local\Programs\Python\Python312\Lib\site-packages\sympy\core\basic.py", line 1874, in match
    m = canonical(pattern).matches(canonical(self), old=old)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\[HIDDEN]\AppData\Local\Programs\Python\Python312\Lib\site-packages\sympy\core\mul.py", line 1022, in matches
    return self._matches_commutative(expr, repl_dict, old)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\[HIDDEN]\AppData\Local\Programs\Python\Python312\Lib\site-packages\sympy\core\operations.py", line 299, in _matches_commutative
    d2 = self.xreplace(d1).matches(expr, d1)
         ^^^^^^^^^^^^^^^^^
  File "C:\Users\[HIDDEN]\AppData\Local\Programs\Python\Python312\Lib\site-packages\sympy\core\basic.py", line 1313, in xreplace
    value, _ = self._xreplace(rule)
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\[HIDDEN]\AppData\Local\Programs\Python\Python312\Lib\site-packages\sympy\core\basic.py", line 1328, in _xreplace
    a_xr = _xreplace(rule)
           ^^^^^^^^^^^^^^^
  File "C:\Users\[HIDDEN]\AppData\Local\Programs\Python\Python312\Lib\site-packages\sympy\core\basic.py", line 1335, in _xreplace
    return self.func(*args), True
           ^^^^^^^^^^^^^^^^
  File "C:\Users\[HIDDEN]\AppData\Local\Programs\Python\Python312\Lib\site-packages\sympy\core\cache.py", line 72, in wrapper
    retval = cfunc(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\[HIDDEN]\AppData\Local\Programs\Python\Python312\Lib\site-packages\sympy\core\power.py", line 207, in __new__
    obj = b._eval_power(e)
          ^^^^^^^^^^^^^^^^
  File "C:\Users\[HIDDEN]\AppData\Local\Programs\Python\Python312\Lib\site-packages\sympy\core\numbers.py", line 2047, in _eval_power
    result = Integer(x**abs(expt.p))
                     ~^^~~~~~~~~~~~
MemoryError
```
By the way, the solution is supposed to be `-LambertW(32*log(2))/log(2) + 5`.

**Comment by iwoeix** [comment] 2024-07-19 02:57
I'd expect `solve` raising `NotImplemented` if the equation isn't solvable using `solve`.

**Comment by smichr** [comment] 2024-07-19 05:49
With 1.11.1 (version of SymPy) I get `[(-LambertW(log(4294967296)) + log(32))/log(2)]` almost right away. And the expanded form is `-LambertW(32*log(2))/log(2) + 5`. What version are you using?

**Comment by oscarbenjamin** [comment] 2024-07-19 07:16
It was working before but stopped working after 4dab56ba615a726b1fd98bb2e60c43c3b68b6403 from gh-26471.

**Comment by oscarbenjamin** [comment] 2024-07-19 07:26
An answer is returned immediately for simplify=False:
```python
In [3]: >>> x = var('x', real=True)
   ...: >>> solve(2**x+x-5, simplify=False)
Out[3]:
⎡  W(32⋅log(2))    ⎤
⎢- ──────────── + 5⎥
⎣     log(2)       ⎦
```
What is slow is:
```python
In [4]: simplify(-LambertW(32*log(2))/log(2) + 5)
...
```
It hangs trying to compute an unreasonably large power:
```python
> /Users/enojb/work/dev/sympy/sympy/core/numbers.py(2048)_eval_power()
   2046         if xexact:
   2047             # if it's a perfect root we've finished
-> 2048             result = Integer(x**abs(expt.p))
   2049             if self.is_negative:
   2050                 result *= S.NegativeOne**expt

ipdb> p self
4294967296
ipdb> p x
4294967296
ipdb> p expt
4294967297
```
This is because it is trying to match:
```
> /Users/enojb/work/dev/sympy/sympy/functions/elementary/exponential.py(1174)eval()
   1172             # W(x**(x+1)*log(x)) = x*log(x) for x > 0
   1173             # e.g., W(81*log(3)) = 3*log(3)
-> 1174             result = x.match(w**(w+1)*log(w))
   1175             if result is not None and result[w].is_positive is True:
   1176                 return result[w]*log(result[w])

ipdb> p result
None
ipdb> p self
*** NameError: name 'self' is not defined
ipdb> p x
log(4294967296)
ipdb> p w
w_
ipdb> p w**(w+1)*log(w)
w_**(w_ + 1)*log(w_)
```
Maybe the Lambert evaluation code is being too clever.

**Comment by oscarbenjamin** [comment] 2024-07-19 07:32
This is what fails:
```python
In [7]: LambertW(log(10**20))
...
```

**Comment by oscarbenjamin** [comment] 2024-07-19 07:33
This is a regression in SymPy 1.13.0.

**Comment by oscarbenjamin** [comment] 2024-07-19 08:01
@smichr @haru-44 this is now the only outstanding regression reported for SymPy 1.13.0 although I expect others to come in future as well. It would be great to be able to fix this in a bugfix release but I am not personally going to go any further than the investigation above to make a fix for this.

**Comment by haru-44** [comment] 2024-07-19 13:17
If the goal is to get it to work for now, I think it would be okay to remove the `match` in `eval`. After all, since `log(2**32).match(w**(w+1)*log(w))` doesn't work, the bug remains. I believe that to solve the fundamental problem, the `match` needs to be fixed, but I'm not sure where to start.

**Comment by oscarbenjamin** [comment] 2024-07-19 14:57
Probably as a quick fix we should just remove the match. At least that would be the best for a 1.13.2 bugfix release.

Ideally `match` would be completely rewritten to use only well-defined structural pattern matching with conditional guards. Then it could be made much more efficient along the lines of matchpy. Unfortunately it is currently a heuristic mess that is impossible to improve in any significant way without breaking compatibility. It is perhaps worth implementing a new internal structural matching function though.

More generally there are issues around expressions that generate very large numbers. There should be some limit in `_eval_power` to prevent it from evaluating extremely large numbers. See e.g. gh-6835 and linked issues.

**Comment by asmeurer** [comment] 2024-07-21 03:06
We should come up with a new interface for pattern matching. The match API isn't amazing, so this wouldn't be the worst thing, and it would let us side-step backwards compatibility concerns. 

We could also just directly use the matchpy interface, though that may be undesirable for various reasons.

**Comment by oscarbenjamin** [comment] 2024-07-21 11:31
> We should come up with a new interface for pattern matching.

I agree.

We should design an interface that allows many to one matching and conditional guards. To start with I would say that we should have a purely structural pattern matcher i.e. what matchpy calls syntactic matching.

**Comment by oscarbenjamin** [comment] 2024-07-21 11:33
This issue is fixed now on both master and the 1.13 branch. The fix will be in 1.13.2. I'm not going to push the release yet because I want to wait a bit of time to collect more potential bug reports.

**Closed** 2024-07-21 11:33 UTC
Labels: functions, regression
