### ISSUE TITLE
Sphinx build fails on Python 3

### ISSUE THREAD

**Issue by hargup** [sympy/sympy#9794] opened 2015-08-08 19:51 UTC
Our sphinx build fails on python 3.4 because it has dropped the support for `ur` string prefix [#1] which is being used in `doc/ext/numpydoc`, also our travis build doesn't check for sphinx build in python 3.

[#1]: http://bugs.python.org/issue15096

**Comment by asmeurer** [comment] 2015-09-08 16:23
Dupe of https://github.com/sympy/sympy/issues/7186

**Closed by asmeurer** 2015-09-08 16:23 UTC
