### ISSUE TITLE
Issues with numeric inequalities

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#12534] opened 2017-04-11 22:21 UTC
This is ported from https://github.com/sympy/sympy/issues/11707. There are many issues with wrong answers with inequalities with floating point numbers, especially when they have precision greater than the default `evalf` precision.

```py
>>> Rational(pi.evalf(100)) > pi
True
>>> Rational(pi.evalf(101)) > pi
True
>>> Rational(pi.evalf(100)) < pi
True
>>> Rational(pi.evalf(101)) < pi
False
```

```py
>>> pi.evalf(100) > pi
True
>>> pi.evalf(100) < pi
True
>>> pi.evalf(100) > pi.evalf(101)
False
>>> pi.evalf(100) < pi.evalf(101)
False
```

```py
>>> (pi.evalf(100) - pi).is_positive
False
>>> (pi - pi.evalf(100)).is_positive
True
>>> (pi.evalf(100) - pi.evalf(101)).is_positive
False
>>> (pi.evalf(101) - pi.evalf(100)).is_positive
True
```

For reference, this is `pi.evalf(102)` (and pi.evalf(110), just to be sure):

```py
>>> pi.evalf(102)
3.14159265358979323846264338327950288419716939937510582097494459230781640628620899862803482534211706798
>>> pi.evalf(110)
3.1415926535897932384626433832795028841971693993751058209749445923078164062862089986280348253421170679821480865
```

So you can see the 100th digit should be rounded up, i.e., the 100-102 digits are 798, so when `pi.evalf(100)` gives the last digit as `8`, that should be greater than the real `pi`.

There are a few issues here:

- `Float.__lt__`, and so on call `evalf()` on the `other`, which loses precision.
- `Expr._eval_is_positive` uses `evalf(2)`, which isn't enough for the above comparisons (I am not 100% sure this is the source of the issue).

This results in many really nasty issues like `max` and `sorted` giving completely wrong answers (see https://github.com/sympy/sympy/issues/11707.). 

Note that there are also issues with Float equality comparisons, but those are separate issues. The issue for those is https://github.com/sympy/sympy/issues/11707..

**Comment by asmeurer** [comment] 2017-04-11 22:31
This is my patch in progress

```diff
diff --git a/sympy/core/numbers.py b/sympy/core/numbers.py
index 406f2fc..4cd0d0c 100644
--- a/sympy/core/numbers.py
+++ b/sympy/core/numbers.py
@@ -1125,13 +1125,9 @@ def __gt__(self, other):
             other = _sympify(other)
         except SympifyError:
             raise TypeError("Invalid comparison %s > %s" % (self, other))
-        if isinstance(other, NumberSymbol):
-            return other.__le__(self)
-        if other.is_comparable:
-            other = other.evalf()
-        if isinstance(other, Number) and other is not S.NaN:
-            return _sympify(bool(
-                mlib.mpf_gt(self._mpf_, other._as_mpf_val(self._prec))))
+        pos = (self - other).is_positive
+        if isinstance(pos, bool):
+            return pos
         return Expr.__gt__(self, other)
 
     def __ge__(self, other):
@@ -1139,13 +1135,9 @@ def __ge__(self, other):
             other = _sympify(other)
         except SympifyError:
             raise TypeError("Invalid comparison %s >= %s" % (self, other))
-        if isinstance(other, NumberSymbol):
-            return other.__lt__(self)
-        if other.is_comparable:
-            other = other.evalf()
-        if isinstance(other, Number) and other is not S.NaN:
-            return _sympify(bool(
-                mlib.mpf_ge(self._mpf_, other._as_mpf_val(self._prec))))
+        nneg = (self - other).is_nonnegative
+        if isinstance(nneg, bool):
+            return nneg
         return Expr.__ge__(self, other)
 
     def __lt__(self, other):
@@ -1153,13 +1145,10 @@ def __lt__(self, other):
             other = _sympify(other)
         except SympifyError:
             raise TypeError("Invalid comparison %s < %s" % (self, other))
-        if isinstance(other, NumberSymbol):
-            return other.__ge__(self)
-        if other.is_real and other.is_number:
-            other = other.evalf()
-        if isinstance(other, Number) and other is not S.NaN:
-            return _sympify(bool(
-                mlib.mpf_lt(self._mpf_, other._as_mpf_val(self._prec))))
+
+        neg = (self - other).is_negative
+        if isinstance(neg, bool):
+            return neg
         return Expr.__lt__(self, other)
 
     def __le__(self, other):
@@ -1167,13 +1156,9 @@ def __le__(self, other):
             other = _sympify(other)
         except SympifyError:
             raise TypeError("Invalid comparison %s <= %s" % (self, other))
-        if isinstance(other, NumberSymbol):
-            return other.__gt__(self)
-        if other.is_real and other.is_number:
-            other = other.evalf()
-        if isinstance(other, Number) and other is not S.NaN:
-            return _sympify(bool(
-                mlib.mpf_le(self._mpf_, other._as_mpf_val(self._prec))))
+        npos = (self - other).is_nonpositive
+        if isinstance(npos, bool):
+            return npos
         return Expr.__le__(self, other)
 
     def __hash__(self):
```

But with this, `pi.evalf(100) < pi` gives True, and I think it should be False. Maybe I'm being misled by decimal rounding vs. the binary rounding that should actually be used. But the Rational comparison is still wrong regardless.

**Comment by asmeurer** [comment] 2017-04-11 22:36
OK, I think the `pi.evalf(100) < pi` bit is actually right. The decimal rounding can be misleading, I supposed. Consider

```pi
>>> Rational(pi.evalf(100))
109943212936596175505913298521620533097335915961174408408712911656578469374718859347550214371967627157/34996011596528190789960035633881941845650710894291398982812329702559247987190014771576210832368861184
>>> (34996011596528190789960035633881941845650710894291398982812329702559247987190014771576210832368861184*pi).evalf(200)
109943212936596175505913298521620533097335915961174408408712911656578469374718859347550214371967627157.10039980575957652375773525616480114593383472064712667501507743469028267043682607551573693545273366
```

Basically, `Rational(pi.evalf(100)) = p/q`, and here `q*pi` is greater than `p`, meaning that `pi > p/q = pi.evalf(100)`.

**Comment by jksuom** [comment] 2017-04-12 17:08
The use of `is_positive` etc. is appealing as it takes care of different kinds of `other` all at once. However, some tests may have to be added if we want to continue raising `TypeError` for nonreal values of `other`.

**Comment by asmeurer** [comment] 2017-04-12 17:54
I fallback to the Expr methods if is_positive gives None, which is where the TypeErrors are raised. There's no possibility of nonreal > nonreal, since the lhs is always a Float.  

Anyway, all the core tests passed with the above change (I haven't run full suite yet).

**Comment by asmeurer** [comment] 2017-04-12 19:01
I think the Rational issue must be coming from `Rational.__lt__`. If you also fallback on it, it works

```
>>> Expr.__lt__(Rational(pi.evalf(100)), pi)
True
>>> Expr.__gt__(Rational(pi.evalf(100)), pi)
False
```

That's both before and after https://github.com/sympy/sympy/pull/12515, which potentially affects this.

**Comment by asmeurer** [comment] 2017-04-12 19:02
Minor bug with the above patch: needs to be `return sympify(pos)` (and so on).

**Comment by smichr** [comment] 2017-04-12 19:06
Didn't see this until committing #12515, sorry!

**Comment by asmeurer** [comment] 2017-04-12 19:07
That's fine, I don't think your change affects it.

**Comment by asmeurer** [comment] 2017-04-12 19:14
Ah, apparently pi compares specifically using the [approximation interval](https://github.com/sympy/sympy/blob/383c0fad7f8d131e8ddcad55088f2432535560f1/sympy/core/numbers.py#L3388) `(Rational(223, 71), Rational(22, 7))` smh

**Comment by smichr** [comment] 2017-04-12 19:15
Don't have time now to comment more, but check these out in the new master. I *think* your OP expressions should work better. The calcs below are basically how I handle the inequality evaluations in `_n2` and they give opposite signs as you reverse the direction of the args:

```
>>> [(pi.evalf(i)-pi).n(2) for i in range(99,102)]
[-1.5e-100, -2.9e-102, 7.0e-103]
>>> [(pi-pi.evalf(i)).n(2) for i in range(99,102)]  # output copied from live.sympy so read as expo. not.
[1.5⋅10−100,2.9⋅10−102,−7.0⋅10−103]

>>> [(pi.evalf(i+1)-pi.evalf(i)).n(2) for i in range(99,102)]
[1.4⋅10−100,3.6⋅10−102,−8.9⋅10−103]
>>> [(pi.evalf(i)-pi.evalf(i+1)).n(2) for i in range(99,102)]
[−1.4⋅10−100,−3.6⋅10−102,8.9⋅10−103]
```

hmmm...but I see you are tinkering with the methods in Number so maybe they won't make it to Expr level.

**Comment by asmeurer** [comment] 2017-04-12 19:18
I want to remove the logic in Number and have it all in one place, because you really do need to use full evalf() except in really simple cases (like Rational < Rational).  So let me know if you have any suggestions on how to keep the code deduplicated. Ideally the (a - b).evalf(2) logic should be in one place, whether that's some special method of Expr or _eval_is_positive or `__lt__` or somewhere else.

**Comment by asmeurer** [comment] 2017-04-12 19:56
Some other test failures. At least one is due to not using `sympify`. I haven't looked into the rest yet 

```
__________________________________________ sympy/functions/elementary/tests/test_miscellaneous.py:test_issue_11099 ___________________________________________
  File "/users/aaronmeurer/documents/python/sympy/sympy/sympy/functions/elementary/tests/test_miscellaneous.py", line 360, in test_issue_11099
    assert Min(x, y).evalf(subs=fixed_test_data) == \
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/functions/elementary/miscellaneous.py", line 457, in evalf
    return self.func(*[a.evalf(prec, **options) for a in self.args])
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/functions/elementary/miscellaneous.py", line 343, in __new__
    args = cls._find_localzeros(set(_args), **assumptions)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/functions/elementary/miscellaneous.py", line 399, in _find_localzeros
    con = cls._is_connected(v, z)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/functions/elementary/miscellaneous.py", line 421, in _is_connected
    r = hit(x >= y, Max, Min)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/functions/elementary/miscellaneous.py", line 416, in hit
    if not v.is_Relational:
AttributeError: 'bool' object has no attribute 'is_Relational'
______________________________________________________________________________________________________________________________________________________________
____________________________________ sympy/solvers/tests/test_inequalities.py:test_reduce_poly_inequalities_real_interval ____________________________________
  File "/users/aaronmeurer/documents/python/sympy/sympy/sympy/solvers/tests/test_inequalities.py", line 74, in test_reduce_poly_inequalities_real_interval
    x**2, 1.0)]], x, relational=False) == \
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/solvers/inequalities.py", line 266, in reduce_rational_inequalities
    solution = solution.evalf()
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/core/evalf.py", line 1394, in evalf
    result = evalf(self, prec + 4, options)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/core/evalf.py", line 1292, in evalf
    xe = x._eval_evalf(prec)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/sets/sets.py", line 1419, in _eval_evalf
    raise TypeError("Not all sets are evalf-able")
TypeError: Not all sets are evalf-able
______________________________________________________________________________________________________________________________________________________________
_________________________________ sympy/solvers/tests/test_inequalities.py:test_reduce_poly_inequalities_complex_relational __________________________________
  File "/users/aaronmeurer/documents/python/sympy/sympy/sympy/solvers/tests/test_inequalities.py", line 135, in test_reduce_poly_inequalities_complex_relational
    [[Ne(x**2, one)]], x, relational=True) == \
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/solvers/inequalities.py", line 266, in reduce_rational_inequalities
    solution = solution.evalf()
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/core/evalf.py", line 1394, in evalf
    result = evalf(self, prec + 4, options)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/core/evalf.py", line 1292, in evalf
    xe = x._eval_evalf(prec)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/sets/sets.py", line 1419, in _eval_evalf
    raise TypeError("Not all sets are evalf-able")
TypeError: Not all sets are evalf-able

______________________________________________________________________________________________________________________________________________________________
_____________________________________________________ sympy/plotting/tests/test_plot.py:test_matplotlib ______________________________________________________
  File "/users/aaronmeurer/documents/python/sympy/sympy/sympy/plotting/tests/test_plot.py", line 282, in test_matplotlib
    plot_and_save('test')
  File "/users/aaronmeurer/documents/python/sympy/sympy/sympy/plotting/tests/test_plot.py", line 248, in plot_and_save
    assert len(w) == 1
AssertionError
______________________________________________________________________________________________________________________________________________________________
_________________________________________________ sympy/plotting/tests/test_plot_implicit.py:test_matplotlib _________________________________________________
  File "/users/aaronmeurer/documents/python/sympy/sympy/sympy/plotting/tests/test_plot_implicit.py", line 78, in test_matplotlib
    plot_implicit_tests('test')
  File "/users/aaronmeurer/documents/python/sympy/sympy/sympy/plotting/tests/test_plot_implicit.py", line 64, in plot_implicit_tests
    assert len(w) == 1
AssertionError
______________________________________________________________________________________________________________________________________________________________
______________________________________________________ sympy/polys/tests/test_polytools.py:test_nroots _______________________________________________________
  File "/users/aaronmeurer/documents/python/sympy/sympy/sympy/polys/tests/test_polytools.py", line 2729, in test_nroots
    assert re(roots[0]).epsilon_eq(-0.75487, eps) is S.true
AssertionError
______________________________________________________________________________________________________________________________________________________________
__________________________________________________ sympy/polys/tests/test_rootoftools.py:test_RootSum_evalf __________________________________________________
  File "/users/aaronmeurer/documents/python/sympy/sympy/sympy/polys/tests/test_rootoftools.py", line 383, in test_RootSum_evalf
    Float("1.0806046117362794348", 20), Float("1e-20")) is S.true
AssertionError

========= tests finished: 6883 passed, 4 failed, 189 skipped, 347 expected to fail, 10 expected to fail but passed, 4 exceptions, in 5934.92 seconds =========
DO *NOT* COMMIT!
```

**Comment by asmeurer** [comment] 2017-04-12 19:58
PR of work so far https://github.com/sympy/sympy/pull/12537

**Comment by smichr** [comment] 2017-04-12 21:57
> should be in one place

I totally agree and that is why I abstracted the process to `_n2`. You would call it before trying an assumptions test as I have done in the Expr's inequality operators. I think I commented in the issue that I opened regarding the use of evaluation in assumptions that many of the queries don't make it to the numerical testing of the args. I'll have to look again to see what the issue is.

**Comment by smichr** [comment] 2017-10-11 00:51
> when pi.evalf(100) gives the last digit as 8, that should be greater than the real pi.

It is not rounded up by evalf. It has a fixed underlying value (which is less than pi):

```
>>> (pi.n(100)-pi).n()
-2.86889280175964e-102
>>> _._prec
53
```

See also the "show" examples of the Float docstring. If, however, you use round you will see what you expect:

```
pi.n(100 > pi
False
>>> pi.round(100) > pi
True
```

**Comment by asmeurer** [comment] 2017-10-12 17:24
> It is not rounded up by evalf. It has a fixed underlying value (which is less than pi):

I see. Here is the issue:

```
>>> pi.evalf(100).evalf(105)
3.14159265358979323846264338327950288419716939937510582097494459230781640628620899862803482534211706797928
>>> pi.evalf(100)
3.141592653589793238462643383279502884197169399375105820974944592307816406286208998628034825342117068
>>> pi.evalf(100).evalf(105)
3.14159265358979323846264338327950288419716939937510582097494459230781640628620899862803482534211706797928
>>> pi.evalf(105)
3.14159265358979323846264338327950288419716939937510582097494459230781640628620899862803482534211706798215
```

pi has `798` in that position, but `pi.evalf(100)` has `797`. But the printing for evalf(100) always rounds to 100 digits, so you see an 8.

**Comment by smichr** [comment] 2019-05-02 19:23
I just tested these all in master so will close this and let a new (cleaner) thread open as needed
```python
>>> def rel_check(a, b):
...     from sympy.utilities.pytest import raises
...     assert a.is_number and b.is_number
...     for do in range(len(set([type(a), type(b)]))):
...         if S.NaN in (a, b):
...             v = [(a == b), (a != b)]
...             assert len(set(v)) == 1 and v[0] == False
...             assert not (a != b) and not (a == b)
...             assert raises(TypeError, lambda: a < b)
...             assert raises(TypeError, lambda: a <= b)
...             assert raises(TypeError, lambda: a > b)
...             assert raises(TypeError, lambda: a >= b)
...         else:
...             E = [(a == b), (a != b)]
...             assert len(set(E)) == 2
...             v = [(a < b), (a <= b), (a > b), (a >= b)]
...             i = [
...             [True, True, False, False],
...             [False, True, False, True],
...             [False, False, True, True]].index(v)
...             if i != 1:
...                 assert E[1]
...             else:
...                 assert E[0]
...         a, b = b, a
...     return True
...
>>> rel_check(Rational(pi.evalf(100)), pi)
True
>>> rel_check(Rational(pi.evalf(101)), pi)
True
>>> rel_check((pi.evalf(100)), pi)
True
>>> rel_check((pi.evalf(101)), pi)
True
>>> rel_check((pi.evalf(101)), pi.evalf(100))
True
>>>
```

**Closed by smichr** 2019-05-02 19:23 UTC
Labels: core, core.evalf, floats
