### ISSUE TITLE
Issue with mixture distributions

### ISSUE THREAD

**Issue by JohnGriffiths** [sympy/sympy#14593] opened 2018-04-03 03:01 UTC
Following discussion on gitter, posting this as an issue as @asmeurer thinks it may be a bug.

See gist notebook [here](https://gist.github.com/JohnGriffiths/9454258a2dc210391385a575989d8156)

I'm trying to define mixture distributions in sympy - e.g. a sum of Gaussians. 

Basically the mixture distribution `G1G2` below does not seem to give the correct (?) result when it is sampled from  (c.f. figure in notebook gist). 

```python
# Gaussian 1
G1 = Normal('G1',5,1)

# Gaussian 2
G2 = Normal('G2',20,4)

# Sympy G1G2 mixture
G1G2 = G1 + G2
```

**Comment by bharatnishant** [comment] 2019-03-10 06:56
@oscarbenjamin I would like to take up this issue

**Comment by oscarbenjamin** [comment] 2019-03-10 09:31
Go ahead. I'm not sure I understand what the issue is though and I haven't looked at SymPy's stats modules so I don't think I can help you with this.

**Comment by jksuom** [comment] 2019-03-10 09:50
The distribution of a sum like `G1 + G2` is not a mixture distribution. A mixture involves also a weight distribution and is implemented in SymPy as a compound (or possibly joint) distribution.

**Comment by Smit-create** [comment] 2020-05-28 05:16
Closing in favour of #18730

**Closed by Smit-create** 2020-05-28 05:16 UTC
Labels: stats
