### ISSUE TITLE
Error in plot_implicit sympy-1.1.1

### ISSUE THREAD

**Issue by mfarrokh** [sympy/sympy#13252] opened 2017-09-03 05:57 UTC
Hi

When I run the following code in sympy-1.1.1:

```
from sympy import plot_implicit,And,symbols,Eq,Or

X1,X2=symbols('X1 X2')

p0=plot_implicit(And((X1**2*X2/20>1),(80/(X1**2+8*X2+5)>1),((X1+X2-5)**2/30+(X1-X2-12)**2/120>1)),
              (X1,0,10),(X2,0,10),show=False,line_color='g')
p1=plot_implicit(Or(Eq(X1**2*X2/20,1),Eq(80/(X1**2+8*X2+5),1),Eq((X1+X2-5)**2/30+(X1-X2-12)**2/120,1)), (X1,0,10),(X2,0,10),show=False,line_color='k')
p0.extend(p1)
p0.show()
```
getting the following result:
![figure_1](https://user-images.githubusercontent.com/7220244/30000929-224b3ae2-9092-11e7-9859-f3a318ac0388.png)

While the result of the above-mentioned code in sympy-1.0.0 is:

![figure_2](https://user-images.githubusercontent.com/7220244/30000921-f7bde3ba-9091-11e7-8f72-eaf07886e4c9.png)

I think that there is something wrong in sympy-1.1.1. 

Best

**Comment by asmeurer** [comment] 2017-09-09 02:28
Ran git bisect. Lots of skipped commits because of syntax errors or other bugs that prevented plot from working:

There are only 'skip'ped commits left to test.
The first bad commit could be any of:
7b82e8dac8af94652d7a00f8e97463b45b153341
dead1d9bf4474c49d61b54a3aa0e4845231f2b38
32a89142b7e242255a4c6e6bb949f1ccaf81673f
88fd46ac3a87833c80cbb88577c278a05bc065bf
c62cb0e3fe06aa217be13c57009f322785c3d5a8
efc4ddd01aa022c767a82ae59e9d178e6f2d630b
b0eb1b410469f47f9f821542f91f3741ebbd99b7
d7c335eb8b568d67ea0a740ef5f8cb70106e2eab
8d4e7b3f334f56939c2983f0b740f1546305d73b
9f3f6b99c729d243060c4f5f0f49b9452bfbc972
93d633babb89230b99650d4f5f1b5c8fa5684ad8
b477bd4a672e84db0ceffd34c8e5478324eea076
c6c1598ba4b2c4b26437ea7c06961f128244dd58
We cannot bisect more!

**Comment by asmeurer** [comment] 2017-09-09 02:29
At any rate, looks like the bug was introduced by https://github.com/sympy/sympy/pull/12108 CC @SagarB-97

**Comment by asmeurer** [comment] 2017-09-09 02:32
Here is the problem

```
>>> str(And((X1**2*X2/20>1),(80/(X1**2+8*X2+5)>1),((X1+X2-5)**2/30+(X1-X2-12)**2/120)))
'(X1**2*X2/20 > 1) & (80/(X1**2 + 8*X2 + 5) > 1) & (X1 - X2 - 12)**2/120 + (X1 + X2 - 5)**2/30'
```

The parenthesization isn't correct. The final term, `(X1 - X2 - 12)**2/120 + (X1 + X2 - 5)**2/30` should have parentheses around it.

**Comment by mfarrokh** [comment] 2017-09-10 18:01
Dear  asmeurer:

Thanks for your reply.
I did not get the problem. I added the parentheses around the last term but it did not affect.

**Comment by kenogo** [comment] 2017-10-02 21:50
@mfarrokh Where exactly did you add parentheses? The problem is apparently somewhere inside the And function not handling the brackets properly. I'll try fixing this.

**Comment by kenogo** [comment] 2017-10-02 23:12
Okay. So I found the issue. The problem is that `sympy.printing.str.StrPrinter._print_Add` function calls a function called `stringify` which eventually calls the function `parenthesize`, to which a precedence value gets passed on. The value used for this is `sympy.printing.precedence.PRECEDENCE["BitwiseAnd"]` and it's equal to 38, which is less than the addition operator with `PRECEDENCE["Add"]` being 40. This is mathematically correct (Addition has higher precedence than logical and) but it apparently just doesn't work with `plot_implicit`. So I don't know which way to go here. I don't want to just change `_print_Add` so that it always puts the parantheses, because again, the current result it prints is mathematically correct. What are your thoughts. @asmeurer?

**Comment by kenogo** [comment] 2017-10-02 23:15
If you wanna try it out: changing the precedence passed on to `stringify` in `_print_Add` to 41 makes @mfarrokh's code work again. But that's obviously not a real fix.

**Comment by kenogo** [comment] 2017-10-02 23:20
As a matter of fact, when I change the precedence passed on to the call of `stringify` in  `_print_Add` from `PRECEDENCE["BitwiseAnd"]` to 41, it return the parenthesization that you expected, @asmeurer, but @mfarrokh's code still doesn't produce the expected results. So maybe the problem isn't with printing after all?

**Comment by kenogo** [comment] 2017-10-03 09:31
I'm pretty sure the error is in `sympy.plotting.experimental_lambdify`. This function is called by `ImplicitSeries.get_raster` which is needed for the plotting matplotlib backend. I guess `experimental_lambdify` wasn't edited to support the new printing of `And` and `Or`. I'll try to fix this and send a pull request if I get it.

**Comment by kenogo** [comment] 2017-10-03 10:44
Further testing has shown that `experimental_lambdify` works correctly when its lambda function gets its values passed  as single nubers, e.g.

```
>>> func = experimental_lambdify((X1,X2), And(X2<X1,X2<(10-X1)),use_interval=True)
>>> func(0,4)
False
```

But it produces wrong output if you call `func` with intervals:

```
>>> func(interval(0,1),interval(4,5))
(True, True)
```

Here, it only seems to recognize the first epxression inside `And` and ignore all others.

**Comment by kenogo** [comment] 2017-10-03 11:24
Okay, so the problem is that the `and` operator has no different namespace for intervals defined in `experimental_lambdify`. For some reason though, the following is the case in python:

```
>>> (False, True) and (True, True)
(True, True)
>>> (True, True) and (False, True)
(False, True)
```

So I was actuallly wrong. It's not the first expression inside `And` that gets recognized, it's the last one.

**Comment by asmeurer** [comment] 2017-10-03 17:53
I would just change the printers to add parentheses. Apparently the precedence of & is indeed such that you don't need parentheses for the above expression, but that isn't obvious. I wouldn't assume that the precedence of the logical operators is obvious.

**Comment by sylee957** [comment] 2020-02-07 13:42
I'd consider this issue in #17711 after I've introduced the correct logic to compare the images.
I think that adding some test cases with the example can be helpful from here.
But if there isn't anyone grabbing this up, this can be closed.

**Comment by aaselvam** [comment] 2020-10-27 05:59
I believe this issue can be closed, I can't seem to replicate it in 1.1 or the most recent 1.6.2.

**Comment by Mayank-gaur** [comment] 2021-01-02 21:54
I am a beginner to the open source world and I want to begin with this issue. Can anyone please guide  how can I get started on this?

**Comment by migueltorrescosta** [comment] 2021-05-27 00:07
Issue ready for closing: it is old and isn't replicable in the latest version:

<img width="1230" alt="image" src="https://user-images.githubusercontent.com/6451658/119746241-e82c1e80-be87-11eb-9025-a5b2f94d2c1b.png">

**Comment by oscarbenjamin** [comment] 2021-05-27 00:20
Thanks

**Closed by oscarbenjamin** 2021-05-27 00:20 UTC
Labels: Easy to Fix, Wrong Result, good first issue, printing
