### ISSUE TITLE
Sympify test error in Python 3.5

### ISSUE THREAD

**Issue by jksuom** [sympy/sympy#10437] opened 2016-01-21 13:59 UTC
``bin/test sympify`` currently fails in Python 3.5 because of a ``TypeError`` in ``sympy_parser``.
```
>>> parse_expr("lambda *args: args")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jks/test/sympy/sympy/parsing/sympy_parser.py", line 892, in parse_expr
    return eval_expr(code, local_dict, global_dict)
  File "/home/jks/test/sympy/sympy/parsing/sympy_parser.py", line 805, in eval_expr
    code, global_dict, local_dict)  # take local objects in preference
  File "<string>", line 1, in <module>
TypeError: 'Symbol' object is not iterable
```
Python 2.7 and presumably the other versions before 3.5 raise ``SyntaxError``
```
>>> parse_expr("lambda *args: args")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sympy/parsing/sympy_parser.py", line 892, in parse_expr
    return eval_expr(code, local_dict, global_dict)
  File "sympy/parsing/sympy_parser.py", line 805, in eval_expr
    code, global_dict, local_dict)  # take local objects in preference
  File "<string>", line 1
    Lambda ((*Symbol ('args' )),Symbol ('args' ))
             ^
SyntaxError: invalid syntax
```
which is transformed into SympifyError [here](https://github.com/sympy/sympy/blob/master/sympy/core/sympify.py#L323).

This issue should be easy to fix by adding ``TypeError`` to the list. It must be tested in a Python 3.5 installation.

See also #9927 and #10084

**Comment by iamshubh22** [comment] 2016-01-21 19:19
@jksuom I would like to work on this.

**Comment by jksuom** [comment] 2016-01-21 20:00
Go ahead! Remember to test with Python 3.5.

**Comment by asmeurer** [comment] 2016-01-21 20:02
It's already been fixed at https://github.com/sympy/sympy/pull/10084.

**Comment by jksuom** [comment] 2016-01-21 20:07
But in a different way? Not in sympify.py?

**Comment by asmeurer** [comment] 2016-01-21 20:09
Yes. Your fix would have masked the problem. The issue is that the code was generating invalid syntax which became valid in Python 3.5 due to the advanced star unpacking features new in that version. This is the fix https://github.com/asmeurer/sympy/commit/1404fcf4fd00b0aede484b7e7685c9ee3c3bc789

**Comment by asmeurer** [comment] 2016-01-21 20:11
i.e., you can see from the error message, it was generating `Lambda ((*Symbol ('args' )),Symbol ('args' ))`, which is nonsensical (`*Symbol('args')` is wrong, since `Symbol('args')` is not iterable). In prior versions of Python this whole thing was a syntax error because of the function argument after the star (`f(*args, x)`), but in Python 3.5 this is allowed. Hence, the error propagated from somewhere that was catching the error to somewhere that wasn't.

**Comment by asmeurer** [comment] 2016-01-21 20:12
Going to close this as a dupe of https://github.com/sympy/sympy/issues/9927 to keep the issue count down.

**Closed by asmeurer** 2016-01-21 20:12 UTC
Labels: Easy to Fix, Python3

**Comment by jksuom** [comment] 2016-01-21 20:13
Ok. Thanks.
